# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zfogg/src/github.com/zfogg/ascii-chat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zfogg/src/github.com/zfogg/ascii-chat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zfogg/src/github.com/zfogg/ascii-chat/CMakeFiles /home/zfogg/src/github.com/zfogg/ascii-chat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zfogg/src/github.com/zfogg/ascii-chat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_version

# Build rule for target.
generate_version: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_version
.PHONY : generate_version

# fast build rule for target.
generate_version/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_version.dir/build.make CMakeFiles/generate_version.dir/build
.PHONY : generate_version/fast

#=============================================================================
# Target rules for targets named zstd-musl

# Build rule for target.
zstd-musl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd-musl
.PHONY : zstd-musl

# fast build rule for target.
zstd-musl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd-musl.dir/build.make CMakeFiles/zstd-musl.dir/build
.PHONY : zstd-musl/fast

#=============================================================================
# Target rules for targets named libsodium-musl

# Build rule for target.
libsodium-musl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libsodium-musl
.PHONY : libsodium-musl

# fast build rule for target.
libsodium-musl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libsodium-musl.dir/build.make CMakeFiles/libsodium-musl.dir/build
.PHONY : libsodium-musl/fast

#=============================================================================
# Target rules for targets named alsa-lib-musl

# Build rule for target.
alsa-lib-musl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alsa-lib-musl
.PHONY : alsa-lib-musl

# fast build rule for target.
alsa-lib-musl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alsa-lib-musl.dir/build.make CMakeFiles/alsa-lib-musl.dir/build
.PHONY : alsa-lib-musl/fast

#=============================================================================
# Target rules for targets named portaudio-musl

# Build rule for target.
portaudio-musl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 portaudio-musl
.PHONY : portaudio-musl

# fast build rule for target.
portaudio-musl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portaudio-musl.dir/build.make CMakeFiles/portaudio-musl.dir/build
.PHONY : portaudio-musl/fast

#=============================================================================
# Target rules for targets named libexecinfo-musl

# Build rule for target.
libexecinfo-musl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libexecinfo-musl
.PHONY : libexecinfo-musl

# fast build rule for target.
libexecinfo-musl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libexecinfo-musl.dir/build.make CMakeFiles/libexecinfo-musl.dir/build
.PHONY : libexecinfo-musl/fast

#=============================================================================
# Target rules for targets named bearssl_build

# Build rule for target.
bearssl_build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bearssl_build
.PHONY : bearssl_build

# fast build rule for target.
bearssl_build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bearssl_build.dir/build.make CMakeFiles/bearssl_build.dir/build
.PHONY : bearssl_build/fast

#=============================================================================
# Target rules for targets named ascii-chat-util

# Build rule for target.
ascii-chat-util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-util
.PHONY : ascii-chat-util

# fast build rule for target.
ascii-chat-util/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/build
.PHONY : ascii-chat-util/fast

#=============================================================================
# Target rules for targets named ascii-chat-data-structures

# Build rule for target.
ascii-chat-data-structures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-data-structures
.PHONY : ascii-chat-data-structures

# fast build rule for target.
ascii-chat-data-structures/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-data-structures.dir/build.make CMakeFiles/ascii-chat-data-structures.dir/build
.PHONY : ascii-chat-data-structures/fast

#=============================================================================
# Target rules for targets named ascii-chat-platform

# Build rule for target.
ascii-chat-platform: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-platform
.PHONY : ascii-chat-platform

# fast build rule for target.
ascii-chat-platform/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/build
.PHONY : ascii-chat-platform/fast

#=============================================================================
# Target rules for targets named ascii-chat-crypto

# Build rule for target.
ascii-chat-crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-crypto
.PHONY : ascii-chat-crypto

# fast build rule for target.
ascii-chat-crypto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/build
.PHONY : ascii-chat-crypto/fast

#=============================================================================
# Target rules for targets named ascii-chat-simd

# Build rule for target.
ascii-chat-simd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-simd
.PHONY : ascii-chat-simd

# fast build rule for target.
ascii-chat-simd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/build
.PHONY : ascii-chat-simd/fast

#=============================================================================
# Target rules for targets named ascii-chat-video

# Build rule for target.
ascii-chat-video: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-video
.PHONY : ascii-chat-video

# fast build rule for target.
ascii-chat-video/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/build
.PHONY : ascii-chat-video/fast

#=============================================================================
# Target rules for targets named ascii-chat-audio

# Build rule for target.
ascii-chat-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-audio
.PHONY : ascii-chat-audio

# fast build rule for target.
ascii-chat-audio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/build
.PHONY : ascii-chat-audio/fast

#=============================================================================
# Target rules for targets named ascii-chat-core

# Build rule for target.
ascii-chat-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-core
.PHONY : ascii-chat-core

# fast build rule for target.
ascii-chat-core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/build
.PHONY : ascii-chat-core/fast

#=============================================================================
# Target rules for targets named ascii-chat-network

# Build rule for target.
ascii-chat-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-network
.PHONY : ascii-chat-network

# fast build rule for target.
ascii-chat-network/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/build
.PHONY : ascii-chat-network/fast

#=============================================================================
# Target rules for targets named ascii-chat-shared

# Build rule for target.
ascii-chat-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-shared
.PHONY : ascii-chat-shared

# fast build rule for target.
ascii-chat-shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-shared.dir/build.make CMakeFiles/ascii-chat-shared.dir/build
.PHONY : ascii-chat-shared/fast

#=============================================================================
# Target rules for targets named ascii-chat-static

# Build rule for target.
ascii-chat-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat-static
.PHONY : ascii-chat-static

# fast build rule for target.
ascii-chat-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-static.dir/build.make CMakeFiles/ascii-chat-static.dir/build
.PHONY : ascii-chat-static/fast

#=============================================================================
# Target rules for targets named ascii-chat

# Build rule for target.
ascii-chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-chat
.PHONY : ascii-chat

# fast build rule for target.
ascii-chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/build
.PHONY : ascii-chat/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named clang-format

# Build rule for target.
clang-format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clang-format
.PHONY : clang-format

# fast build rule for target.
clang-format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clang-format.dir/build.make CMakeFiles/clang-format.dir/build
.PHONY : clang-format/fast

#=============================================================================
# Target rules for targets named format-check

# Build rule for target.
format-check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format-check
.PHONY : format-check

# fast build rule for target.
format-check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format-check.dir/build.make CMakeFiles/format-check.dir/build
.PHONY : format-check/fast

#=============================================================================
# Target rules for targets named clang-tidy

# Build rule for target.
clang-tidy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clang-tidy
.PHONY : clang-tidy

# fast build rule for target.
clang-tidy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clang-tidy.dir/build.make CMakeFiles/clang-tidy.dir/build
.PHONY : clang-tidy/fast

#=============================================================================
# Target rules for targets named scan-build

# Build rule for target.
scan-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scan-build
.PHONY : scan-build

# fast build rule for target.
scan-build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scan-build.dir/build.make CMakeFiles/scan-build.dir/build
.PHONY : scan-build/fast

#=============================================================================
# Target rules for targets named clean_all

# Build rule for target.
clean_all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_all
.PHONY : clean_all

# fast build rule for target.
clean_all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_all.dir/build.make CMakeFiles/clean_all.dir/build
.PHONY : clean_all/fast

empty.o: empty.c.o
.PHONY : empty.o

# target to build an object file
empty.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-shared.dir/build.make CMakeFiles/ascii-chat-shared.dir/empty.c.o
.PHONY : empty.c.o

empty.i: empty.c.i
.PHONY : empty.i

# target to preprocess a source file
empty.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-shared.dir/build.make CMakeFiles/ascii-chat-shared.dir/empty.c.i
.PHONY : empty.c.i

empty.s: empty.c.s
.PHONY : empty.s

# target to generate assembly for a file
empty.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-shared.dir/build.make CMakeFiles/ascii-chat-shared.dir/empty.c.s
.PHONY : empty.c.s

lib/asciichat_errno.o: lib/asciichat_errno.c.o
.PHONY : lib/asciichat_errno.o

# target to build an object file
lib/asciichat_errno.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/asciichat_errno.c.o
.PHONY : lib/asciichat_errno.c.o

lib/asciichat_errno.i: lib/asciichat_errno.c.i
.PHONY : lib/asciichat_errno.i

# target to preprocess a source file
lib/asciichat_errno.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/asciichat_errno.c.i
.PHONY : lib/asciichat_errno.c.i

lib/asciichat_errno.s: lib/asciichat_errno.c.s
.PHONY : lib/asciichat_errno.s

# target to generate assembly for a file
lib/asciichat_errno.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/asciichat_errno.c.s
.PHONY : lib/asciichat_errno.c.s

lib/audio.o: lib/audio.c.o
.PHONY : lib/audio.o

# target to build an object file
lib/audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/audio.c.o
.PHONY : lib/audio.c.o

lib/audio.i: lib/audio.c.i
.PHONY : lib/audio.i

# target to preprocess a source file
lib/audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/audio.c.i
.PHONY : lib/audio.c.i

lib/audio.s: lib/audio.c.s
.PHONY : lib/audio.s

# target to generate assembly for a file
lib/audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/audio.c.s
.PHONY : lib/audio.c.s

lib/buffer_pool.o: lib/buffer_pool.c.o
.PHONY : lib/buffer_pool.o

# target to build an object file
lib/buffer_pool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/buffer_pool.c.o
.PHONY : lib/buffer_pool.c.o

lib/buffer_pool.i: lib/buffer_pool.c.i
.PHONY : lib/buffer_pool.i

# target to preprocess a source file
lib/buffer_pool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/buffer_pool.c.i
.PHONY : lib/buffer_pool.c.i

lib/buffer_pool.s: lib/buffer_pool.c.s
.PHONY : lib/buffer_pool.s

# target to generate assembly for a file
lib/buffer_pool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/buffer_pool.c.s
.PHONY : lib/buffer_pool.c.s

lib/common.o: lib/common.c.o
.PHONY : lib/common.o

# target to build an object file
lib/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/common.c.o
.PHONY : lib/common.c.o

lib/common.i: lib/common.c.i
.PHONY : lib/common.i

# target to preprocess a source file
lib/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/common.c.i
.PHONY : lib/common.c.i

lib/common.s: lib/common.c.s
.PHONY : lib/common.s

# target to generate assembly for a file
lib/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/common.c.s
.PHONY : lib/common.c.s

lib/compression.o: lib/compression.c.o
.PHONY : lib/compression.o

# target to build an object file
lib/compression.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/compression.c.o
.PHONY : lib/compression.c.o

lib/compression.i: lib/compression.c.i
.PHONY : lib/compression.i

# target to preprocess a source file
lib/compression.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/compression.c.i
.PHONY : lib/compression.c.i

lib/compression.s: lib/compression.c.s
.PHONY : lib/compression.s

# target to generate assembly for a file
lib/compression.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/compression.c.s
.PHONY : lib/compression.c.s

lib/crc32.o: lib/crc32.c.o
.PHONY : lib/crc32.o

# target to build an object file
lib/crc32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/crc32.c.o
.PHONY : lib/crc32.c.o

lib/crc32.i: lib/crc32.c.i
.PHONY : lib/crc32.i

# target to preprocess a source file
lib/crc32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/crc32.c.i
.PHONY : lib/crc32.c.i

lib/crc32.s: lib/crc32.c.s
.PHONY : lib/crc32.s

# target to generate assembly for a file
lib/crc32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/crc32.c.s
.PHONY : lib/crc32.c.s

lib/crypto/crypto.o: lib/crypto/crypto.c.o
.PHONY : lib/crypto/crypto.o

# target to build an object file
lib/crypto/crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/crypto.c.o
.PHONY : lib/crypto/crypto.c.o

lib/crypto/crypto.i: lib/crypto/crypto.c.i
.PHONY : lib/crypto/crypto.i

# target to preprocess a source file
lib/crypto/crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/crypto.c.i
.PHONY : lib/crypto/crypto.c.i

lib/crypto/crypto.s: lib/crypto/crypto.c.s
.PHONY : lib/crypto/crypto.s

# target to generate assembly for a file
lib/crypto/crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/crypto.c.s
.PHONY : lib/crypto/crypto.c.s

lib/crypto/gpg.o: lib/crypto/gpg.c.o
.PHONY : lib/crypto/gpg.o

# target to build an object file
lib/crypto/gpg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/gpg.c.o
.PHONY : lib/crypto/gpg.c.o

lib/crypto/gpg.i: lib/crypto/gpg.c.i
.PHONY : lib/crypto/gpg.i

# target to preprocess a source file
lib/crypto/gpg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/gpg.c.i
.PHONY : lib/crypto/gpg.c.i

lib/crypto/gpg.s: lib/crypto/gpg.c.s
.PHONY : lib/crypto/gpg.s

# target to generate assembly for a file
lib/crypto/gpg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/gpg.c.s
.PHONY : lib/crypto/gpg.c.s

lib/crypto/handshake.o: lib/crypto/handshake.c.o
.PHONY : lib/crypto/handshake.o

# target to build an object file
lib/crypto/handshake.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/handshake.c.o
.PHONY : lib/crypto/handshake.c.o

lib/crypto/handshake.i: lib/crypto/handshake.c.i
.PHONY : lib/crypto/handshake.i

# target to preprocess a source file
lib/crypto/handshake.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/handshake.c.i
.PHONY : lib/crypto/handshake.c.i

lib/crypto/handshake.s: lib/crypto/handshake.c.s
.PHONY : lib/crypto/handshake.s

# target to generate assembly for a file
lib/crypto/handshake.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/handshake.c.s
.PHONY : lib/crypto/handshake.c.s

lib/crypto/http_client.o: lib/crypto/http_client.c.o
.PHONY : lib/crypto/http_client.o

# target to build an object file
lib/crypto/http_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/http_client.c.o
.PHONY : lib/crypto/http_client.c.o

lib/crypto/http_client.i: lib/crypto/http_client.c.i
.PHONY : lib/crypto/http_client.i

# target to preprocess a source file
lib/crypto/http_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/http_client.c.i
.PHONY : lib/crypto/http_client.c.i

lib/crypto/http_client.s: lib/crypto/http_client.c.s
.PHONY : lib/crypto/http_client.s

# target to generate assembly for a file
lib/crypto/http_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/http_client.c.s
.PHONY : lib/crypto/http_client.c.s

lib/crypto/keys/gpg_keys.o: lib/crypto/keys/gpg_keys.c.o
.PHONY : lib/crypto/keys/gpg_keys.o

# target to build an object file
lib/crypto/keys/gpg_keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/gpg_keys.c.o
.PHONY : lib/crypto/keys/gpg_keys.c.o

lib/crypto/keys/gpg_keys.i: lib/crypto/keys/gpg_keys.c.i
.PHONY : lib/crypto/keys/gpg_keys.i

# target to preprocess a source file
lib/crypto/keys/gpg_keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/gpg_keys.c.i
.PHONY : lib/crypto/keys/gpg_keys.c.i

lib/crypto/keys/gpg_keys.s: lib/crypto/keys/gpg_keys.c.s
.PHONY : lib/crypto/keys/gpg_keys.s

# target to generate assembly for a file
lib/crypto/keys/gpg_keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/gpg_keys.c.s
.PHONY : lib/crypto/keys/gpg_keys.c.s

lib/crypto/keys/https_keys.o: lib/crypto/keys/https_keys.c.o
.PHONY : lib/crypto/keys/https_keys.o

# target to build an object file
lib/crypto/keys/https_keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/https_keys.c.o
.PHONY : lib/crypto/keys/https_keys.c.o

lib/crypto/keys/https_keys.i: lib/crypto/keys/https_keys.c.i
.PHONY : lib/crypto/keys/https_keys.i

# target to preprocess a source file
lib/crypto/keys/https_keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/https_keys.c.i
.PHONY : lib/crypto/keys/https_keys.c.i

lib/crypto/keys/https_keys.s: lib/crypto/keys/https_keys.c.s
.PHONY : lib/crypto/keys/https_keys.s

# target to generate assembly for a file
lib/crypto/keys/https_keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/https_keys.c.s
.PHONY : lib/crypto/keys/https_keys.c.s

lib/crypto/keys/keys.o: lib/crypto/keys/keys.c.o
.PHONY : lib/crypto/keys/keys.o

# target to build an object file
lib/crypto/keys/keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/keys.c.o
.PHONY : lib/crypto/keys/keys.c.o

lib/crypto/keys/keys.i: lib/crypto/keys/keys.c.i
.PHONY : lib/crypto/keys/keys.i

# target to preprocess a source file
lib/crypto/keys/keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/keys.c.i
.PHONY : lib/crypto/keys/keys.c.i

lib/crypto/keys/keys.s: lib/crypto/keys/keys.c.s
.PHONY : lib/crypto/keys/keys.s

# target to generate assembly for a file
lib/crypto/keys/keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/keys.c.s
.PHONY : lib/crypto/keys/keys.c.s

lib/crypto/keys/ssh_keys.o: lib/crypto/keys/ssh_keys.c.o
.PHONY : lib/crypto/keys/ssh_keys.o

# target to build an object file
lib/crypto/keys/ssh_keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/ssh_keys.c.o
.PHONY : lib/crypto/keys/ssh_keys.c.o

lib/crypto/keys/ssh_keys.i: lib/crypto/keys/ssh_keys.c.i
.PHONY : lib/crypto/keys/ssh_keys.i

# target to preprocess a source file
lib/crypto/keys/ssh_keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/ssh_keys.c.i
.PHONY : lib/crypto/keys/ssh_keys.c.i

lib/crypto/keys/ssh_keys.s: lib/crypto/keys/ssh_keys.c.s
.PHONY : lib/crypto/keys/ssh_keys.s

# target to generate assembly for a file
lib/crypto/keys/ssh_keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/ssh_keys.c.s
.PHONY : lib/crypto/keys/ssh_keys.c.s

lib/crypto/keys/validation.o: lib/crypto/keys/validation.c.o
.PHONY : lib/crypto/keys/validation.o

# target to build an object file
lib/crypto/keys/validation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/validation.c.o
.PHONY : lib/crypto/keys/validation.c.o

lib/crypto/keys/validation.i: lib/crypto/keys/validation.c.i
.PHONY : lib/crypto/keys/validation.i

# target to preprocess a source file
lib/crypto/keys/validation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/validation.c.i
.PHONY : lib/crypto/keys/validation.c.i

lib/crypto/keys/validation.s: lib/crypto/keys/validation.c.s
.PHONY : lib/crypto/keys/validation.s

# target to generate assembly for a file
lib/crypto/keys/validation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/keys/validation.c.s
.PHONY : lib/crypto/keys/validation.c.s

lib/crypto/known_hosts.o: lib/crypto/known_hosts.c.o
.PHONY : lib/crypto/known_hosts.o

# target to build an object file
lib/crypto/known_hosts.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/known_hosts.c.o
.PHONY : lib/crypto/known_hosts.c.o

lib/crypto/known_hosts.i: lib/crypto/known_hosts.c.i
.PHONY : lib/crypto/known_hosts.i

# target to preprocess a source file
lib/crypto/known_hosts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/known_hosts.c.i
.PHONY : lib/crypto/known_hosts.c.i

lib/crypto/known_hosts.s: lib/crypto/known_hosts.c.s
.PHONY : lib/crypto/known_hosts.s

# target to generate assembly for a file
lib/crypto/known_hosts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/known_hosts.c.s
.PHONY : lib/crypto/known_hosts.c.s

lib/crypto/pem_utils.o: lib/crypto/pem_utils.c.o
.PHONY : lib/crypto/pem_utils.o

# target to build an object file
lib/crypto/pem_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/pem_utils.c.o
.PHONY : lib/crypto/pem_utils.c.o

lib/crypto/pem_utils.i: lib/crypto/pem_utils.c.i
.PHONY : lib/crypto/pem_utils.i

# target to preprocess a source file
lib/crypto/pem_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/pem_utils.c.i
.PHONY : lib/crypto/pem_utils.c.i

lib/crypto/pem_utils.s: lib/crypto/pem_utils.c.s
.PHONY : lib/crypto/pem_utils.s

# target to generate assembly for a file
lib/crypto/pem_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/pem_utils.c.s
.PHONY : lib/crypto/pem_utils.c.s

lib/crypto/ssh_agent.o: lib/crypto/ssh_agent.c.o
.PHONY : lib/crypto/ssh_agent.o

# target to build an object file
lib/crypto/ssh_agent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/ssh_agent.c.o
.PHONY : lib/crypto/ssh_agent.c.o

lib/crypto/ssh_agent.i: lib/crypto/ssh_agent.c.i
.PHONY : lib/crypto/ssh_agent.i

# target to preprocess a source file
lib/crypto/ssh_agent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/ssh_agent.c.i
.PHONY : lib/crypto/ssh_agent.c.i

lib/crypto/ssh_agent.s: lib/crypto/ssh_agent.c.s
.PHONY : lib/crypto/ssh_agent.s

# target to generate assembly for a file
lib/crypto/ssh_agent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-crypto.dir/build.make CMakeFiles/ascii-chat-crypto.dir/lib/crypto/ssh_agent.c.s
.PHONY : lib/crypto/ssh_agent.c.s

lib/hashtable.o: lib/hashtable.c.o
.PHONY : lib/hashtable.o

# target to build an object file
lib/hashtable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-data-structures.dir/build.make CMakeFiles/ascii-chat-data-structures.dir/lib/hashtable.c.o
.PHONY : lib/hashtable.c.o

lib/hashtable.i: lib/hashtable.c.i
.PHONY : lib/hashtable.i

# target to preprocess a source file
lib/hashtable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-data-structures.dir/build.make CMakeFiles/ascii-chat-data-structures.dir/lib/hashtable.c.i
.PHONY : lib/hashtable.c.i

lib/hashtable.s: lib/hashtable.c.s
.PHONY : lib/hashtable.s

# target to generate assembly for a file
lib/hashtable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-data-structures.dir/build.make CMakeFiles/ascii-chat-data-structures.dir/lib/hashtable.c.s
.PHONY : lib/hashtable.c.s

lib/image2ascii/ansi_fast.o: lib/image2ascii/ansi_fast.c.o
.PHONY : lib/image2ascii/ansi_fast.o

# target to build an object file
lib/image2ascii/ansi_fast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/ansi_fast.c.o
.PHONY : lib/image2ascii/ansi_fast.c.o

lib/image2ascii/ansi_fast.i: lib/image2ascii/ansi_fast.c.i
.PHONY : lib/image2ascii/ansi_fast.i

# target to preprocess a source file
lib/image2ascii/ansi_fast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/ansi_fast.c.i
.PHONY : lib/image2ascii/ansi_fast.c.i

lib/image2ascii/ansi_fast.s: lib/image2ascii/ansi_fast.c.s
.PHONY : lib/image2ascii/ansi_fast.s

# target to generate assembly for a file
lib/image2ascii/ansi_fast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/ansi_fast.c.s
.PHONY : lib/image2ascii/ansi_fast.c.s

lib/image2ascii/ascii.o: lib/image2ascii/ascii.c.o
.PHONY : lib/image2ascii/ascii.o

# target to build an object file
lib/image2ascii/ascii.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/ascii.c.o
.PHONY : lib/image2ascii/ascii.c.o

lib/image2ascii/ascii.i: lib/image2ascii/ascii.c.i
.PHONY : lib/image2ascii/ascii.i

# target to preprocess a source file
lib/image2ascii/ascii.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/ascii.c.i
.PHONY : lib/image2ascii/ascii.c.i

lib/image2ascii/ascii.s: lib/image2ascii/ascii.c.s
.PHONY : lib/image2ascii/ascii.s

# target to generate assembly for a file
lib/image2ascii/ascii.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/ascii.c.s
.PHONY : lib/image2ascii/ascii.c.s

lib/image2ascii/image.o: lib/image2ascii/image.c.o
.PHONY : lib/image2ascii/image.o

# target to build an object file
lib/image2ascii/image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/image.c.o
.PHONY : lib/image2ascii/image.c.o

lib/image2ascii/image.i: lib/image2ascii/image.c.i
.PHONY : lib/image2ascii/image.i

# target to preprocess a source file
lib/image2ascii/image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/image.c.i
.PHONY : lib/image2ascii/image.c.i

lib/image2ascii/image.s: lib/image2ascii/image.c.s
.PHONY : lib/image2ascii/image.s

# target to generate assembly for a file
lib/image2ascii/image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/image2ascii/image.c.s
.PHONY : lib/image2ascii/image.c.s

lib/image2ascii/output_buffer.o: lib/image2ascii/output_buffer.c.o
.PHONY : lib/image2ascii/output_buffer.o

# target to build an object file
lib/image2ascii/output_buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/output_buffer.c.o
.PHONY : lib/image2ascii/output_buffer.c.o

lib/image2ascii/output_buffer.i: lib/image2ascii/output_buffer.c.i
.PHONY : lib/image2ascii/output_buffer.i

# target to preprocess a source file
lib/image2ascii/output_buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/output_buffer.c.i
.PHONY : lib/image2ascii/output_buffer.c.i

lib/image2ascii/output_buffer.s: lib/image2ascii/output_buffer.c.s
.PHONY : lib/image2ascii/output_buffer.s

# target to generate assembly for a file
lib/image2ascii/output_buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/output_buffer.c.s
.PHONY : lib/image2ascii/output_buffer.c.s

lib/image2ascii/simd/ascii_simd.o: lib/image2ascii/simd/ascii_simd.c.o
.PHONY : lib/image2ascii/simd/ascii_simd.o

# target to build an object file
lib/image2ascii/simd/ascii_simd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/ascii_simd.c.o
.PHONY : lib/image2ascii/simd/ascii_simd.c.o

lib/image2ascii/simd/ascii_simd.i: lib/image2ascii/simd/ascii_simd.c.i
.PHONY : lib/image2ascii/simd/ascii_simd.i

# target to preprocess a source file
lib/image2ascii/simd/ascii_simd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/ascii_simd.c.i
.PHONY : lib/image2ascii/simd/ascii_simd.c.i

lib/image2ascii/simd/ascii_simd.s: lib/image2ascii/simd/ascii_simd.c.s
.PHONY : lib/image2ascii/simd/ascii_simd.s

# target to generate assembly for a file
lib/image2ascii/simd/ascii_simd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/ascii_simd.c.s
.PHONY : lib/image2ascii/simd/ascii_simd.c.s

lib/image2ascii/simd/ascii_simd_color.o: lib/image2ascii/simd/ascii_simd_color.c.o
.PHONY : lib/image2ascii/simd/ascii_simd_color.o

# target to build an object file
lib/image2ascii/simd/ascii_simd_color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/ascii_simd_color.c.o
.PHONY : lib/image2ascii/simd/ascii_simd_color.c.o

lib/image2ascii/simd/ascii_simd_color.i: lib/image2ascii/simd/ascii_simd_color.c.i
.PHONY : lib/image2ascii/simd/ascii_simd_color.i

# target to preprocess a source file
lib/image2ascii/simd/ascii_simd_color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/ascii_simd_color.c.i
.PHONY : lib/image2ascii/simd/ascii_simd_color.c.i

lib/image2ascii/simd/ascii_simd_color.s: lib/image2ascii/simd/ascii_simd_color.c.s
.PHONY : lib/image2ascii/simd/ascii_simd_color.s

# target to generate assembly for a file
lib/image2ascii/simd/ascii_simd_color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/ascii_simd_color.c.s
.PHONY : lib/image2ascii/simd/ascii_simd_color.c.s

lib/image2ascii/simd/avx2.o: lib/image2ascii/simd/avx2.c.o
.PHONY : lib/image2ascii/simd/avx2.o

# target to build an object file
lib/image2ascii/simd/avx2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/avx2.c.o
.PHONY : lib/image2ascii/simd/avx2.c.o

lib/image2ascii/simd/avx2.i: lib/image2ascii/simd/avx2.c.i
.PHONY : lib/image2ascii/simd/avx2.i

# target to preprocess a source file
lib/image2ascii/simd/avx2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/avx2.c.i
.PHONY : lib/image2ascii/simd/avx2.c.i

lib/image2ascii/simd/avx2.s: lib/image2ascii/simd/avx2.c.s
.PHONY : lib/image2ascii/simd/avx2.s

# target to generate assembly for a file
lib/image2ascii/simd/avx2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/avx2.c.s
.PHONY : lib/image2ascii/simd/avx2.c.s

lib/image2ascii/simd/common.o: lib/image2ascii/simd/common.c.o
.PHONY : lib/image2ascii/simd/common.o

# target to build an object file
lib/image2ascii/simd/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/common.c.o
.PHONY : lib/image2ascii/simd/common.c.o

lib/image2ascii/simd/common.i: lib/image2ascii/simd/common.c.i
.PHONY : lib/image2ascii/simd/common.i

# target to preprocess a source file
lib/image2ascii/simd/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/common.c.i
.PHONY : lib/image2ascii/simd/common.c.i

lib/image2ascii/simd/common.s: lib/image2ascii/simd/common.c.s
.PHONY : lib/image2ascii/simd/common.s

# target to generate assembly for a file
lib/image2ascii/simd/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-simd.dir/build.make CMakeFiles/ascii-chat-simd.dir/lib/image2ascii/simd/common.c.s
.PHONY : lib/image2ascii/simd/common.c.s

lib/lock_debug.o: lib/lock_debug.c.o
.PHONY : lib/lock_debug.o

# target to build an object file
lib/lock_debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/lock_debug.c.o
.PHONY : lib/lock_debug.c.o

lib/lock_debug.i: lib/lock_debug.c.i
.PHONY : lib/lock_debug.i

# target to preprocess a source file
lib/lock_debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/lock_debug.c.i
.PHONY : lib/lock_debug.c.i

lib/lock_debug.s: lib/lock_debug.c.s
.PHONY : lib/lock_debug.s

# target to generate assembly for a file
lib/lock_debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/lock_debug.c.s
.PHONY : lib/lock_debug.c.s

lib/logging.o: lib/logging.c.o
.PHONY : lib/logging.o

# target to build an object file
lib/logging.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/logging.c.o
.PHONY : lib/logging.c.o

lib/logging.i: lib/logging.c.i
.PHONY : lib/logging.i

# target to preprocess a source file
lib/logging.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/logging.c.i
.PHONY : lib/logging.c.i

lib/logging.s: lib/logging.c.s
.PHONY : lib/logging.s

# target to generate assembly for a file
lib/logging.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/logging.c.s
.PHONY : lib/logging.c.s

lib/mixer.o: lib/mixer.c.o
.PHONY : lib/mixer.o

# target to build an object file
lib/mixer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/mixer.c.o
.PHONY : lib/mixer.c.o

lib/mixer.i: lib/mixer.c.i
.PHONY : lib/mixer.i

# target to preprocess a source file
lib/mixer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/mixer.c.i
.PHONY : lib/mixer.c.i

lib/mixer.s: lib/mixer.c.s
.PHONY : lib/mixer.s

# target to generate assembly for a file
lib/mixer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/mixer.c.s
.PHONY : lib/mixer.c.s

lib/musl_c23_compat.o: lib/musl_c23_compat.c.o
.PHONY : lib/musl_c23_compat.o

# target to build an object file
lib/musl_c23_compat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/musl_c23_compat.c.o
.PHONY : lib/musl_c23_compat.c.o

lib/musl_c23_compat.i: lib/musl_c23_compat.c.i
.PHONY : lib/musl_c23_compat.i

# target to preprocess a source file
lib/musl_c23_compat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/musl_c23_compat.c.i
.PHONY : lib/musl_c23_compat.c.i

lib/musl_c23_compat.s: lib/musl_c23_compat.c.s
.PHONY : lib/musl_c23_compat.s

# target to generate assembly for a file
lib/musl_c23_compat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/musl_c23_compat.c.s
.PHONY : lib/musl_c23_compat.c.s

lib/network/av.o: lib/network/av.c.o
.PHONY : lib/network/av.o

# target to build an object file
lib/network/av.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/av.c.o
.PHONY : lib/network/av.c.o

lib/network/av.i: lib/network/av.c.i
.PHONY : lib/network/av.i

# target to preprocess a source file
lib/network/av.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/av.c.i
.PHONY : lib/network/av.c.i

lib/network/av.s: lib/network/av.c.s
.PHONY : lib/network/av.s

# target to generate assembly for a file
lib/network/av.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/av.c.s
.PHONY : lib/network/av.c.s

lib/network/network.o: lib/network/network.c.o
.PHONY : lib/network/network.o

# target to build an object file
lib/network/network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/network.c.o
.PHONY : lib/network/network.c.o

lib/network/network.i: lib/network/network.c.i
.PHONY : lib/network/network.i

# target to preprocess a source file
lib/network/network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/network.c.i
.PHONY : lib/network/network.c.i

lib/network/network.s: lib/network/network.c.s
.PHONY : lib/network/network.s

# target to generate assembly for a file
lib/network/network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/network.c.s
.PHONY : lib/network/network.c.s

lib/network/packet.o: lib/network/packet.c.o
.PHONY : lib/network/packet.o

# target to build an object file
lib/network/packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/packet.c.o
.PHONY : lib/network/packet.c.o

lib/network/packet.i: lib/network/packet.c.i
.PHONY : lib/network/packet.i

# target to preprocess a source file
lib/network/packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/packet.c.i
.PHONY : lib/network/packet.c.i

lib/network/packet.s: lib/network/packet.c.s
.PHONY : lib/network/packet.s

# target to generate assembly for a file
lib/network/packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/network/packet.c.s
.PHONY : lib/network/packet.c.s

lib/options.o: lib/options.c.o
.PHONY : lib/options.o

# target to build an object file
lib/options.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/options.c.o
.PHONY : lib/options.c.o

lib/options.i: lib/options.c.i
.PHONY : lib/options.i

# target to preprocess a source file
lib/options.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/options.c.i
.PHONY : lib/options.c.i

lib/options.s: lib/options.c.s
.PHONY : lib/options.s

# target to generate assembly for a file
lib/options.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/options.c.s
.PHONY : lib/options.c.s

lib/os/linux/webcam_v4l2.o: lib/os/linux/webcam_v4l2.c.o
.PHONY : lib/os/linux/webcam_v4l2.o

# target to build an object file
lib/os/linux/webcam_v4l2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/os/linux/webcam_v4l2.c.o
.PHONY : lib/os/linux/webcam_v4l2.c.o

lib/os/linux/webcam_v4l2.i: lib/os/linux/webcam_v4l2.c.i
.PHONY : lib/os/linux/webcam_v4l2.i

# target to preprocess a source file
lib/os/linux/webcam_v4l2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/os/linux/webcam_v4l2.c.i
.PHONY : lib/os/linux/webcam_v4l2.c.i

lib/os/linux/webcam_v4l2.s: lib/os/linux/webcam_v4l2.c.s
.PHONY : lib/os/linux/webcam_v4l2.s

# target to generate assembly for a file
lib/os/linux/webcam_v4l2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/os/linux/webcam_v4l2.c.s
.PHONY : lib/os/linux/webcam_v4l2.c.s

lib/os/webcam.o: lib/os/webcam.c.o
.PHONY : lib/os/webcam.o

# target to build an object file
lib/os/webcam.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/os/webcam.c.o
.PHONY : lib/os/webcam.c.o

lib/os/webcam.i: lib/os/webcam.c.i
.PHONY : lib/os/webcam.i

# target to preprocess a source file
lib/os/webcam.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/os/webcam.c.i
.PHONY : lib/os/webcam.c.i

lib/os/webcam.s: lib/os/webcam.c.s
.PHONY : lib/os/webcam.s

# target to generate assembly for a file
lib/os/webcam.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/os/webcam.c.s
.PHONY : lib/os/webcam.c.s

lib/packet_queue.o: lib/packet_queue.c.o
.PHONY : lib/packet_queue.o

# target to build an object file
lib/packet_queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/packet_queue.c.o
.PHONY : lib/packet_queue.c.o

lib/packet_queue.i: lib/packet_queue.c.i
.PHONY : lib/packet_queue.i

# target to preprocess a source file
lib/packet_queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/packet_queue.c.i
.PHONY : lib/packet_queue.c.i

lib/packet_queue.s: lib/packet_queue.c.s
.PHONY : lib/packet_queue.s

# target to generate assembly for a file
lib/packet_queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-network.dir/build.make CMakeFiles/ascii-chat-network.dir/lib/packet_queue.c.s
.PHONY : lib/packet_queue.c.s

lib/palette.o: lib/palette.c.o
.PHONY : lib/palette.o

# target to build an object file
lib/palette.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/palette.c.o
.PHONY : lib/palette.c.o

lib/palette.i: lib/palette.c.i
.PHONY : lib/palette.i

# target to preprocess a source file
lib/palette.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/palette.c.i
.PHONY : lib/palette.c.i

lib/palette.s: lib/palette.c.s
.PHONY : lib/palette.s

# target to generate assembly for a file
lib/palette.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/palette.c.s
.PHONY : lib/palette.c.s

lib/platform/abstraction.o: lib/platform/abstraction.c.o
.PHONY : lib/platform/abstraction.o

# target to build an object file
lib/platform/abstraction.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/abstraction.c.o
.PHONY : lib/platform/abstraction.c.o

lib/platform/abstraction.i: lib/platform/abstraction.c.i
.PHONY : lib/platform/abstraction.i

# target to preprocess a source file
lib/platform/abstraction.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/abstraction.c.i
.PHONY : lib/platform/abstraction.c.i

lib/platform/abstraction.s: lib/platform/abstraction.c.s
.PHONY : lib/platform/abstraction.s

# target to generate assembly for a file
lib/platform/abstraction.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/abstraction.c.s
.PHONY : lib/platform/abstraction.c.s

lib/platform/posix/cond.o: lib/platform/posix/cond.c.o
.PHONY : lib/platform/posix/cond.o

# target to build an object file
lib/platform/posix/cond.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/cond.c.o
.PHONY : lib/platform/posix/cond.c.o

lib/platform/posix/cond.i: lib/platform/posix/cond.c.i
.PHONY : lib/platform/posix/cond.i

# target to preprocess a source file
lib/platform/posix/cond.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/cond.c.i
.PHONY : lib/platform/posix/cond.c.i

lib/platform/posix/cond.s: lib/platform/posix/cond.c.s
.PHONY : lib/platform/posix/cond.s

# target to generate assembly for a file
lib/platform/posix/cond.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/cond.c.s
.PHONY : lib/platform/posix/cond.c.s

lib/platform/posix/mutex.o: lib/platform/posix/mutex.c.o
.PHONY : lib/platform/posix/mutex.o

# target to build an object file
lib/platform/posix/mutex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/mutex.c.o
.PHONY : lib/platform/posix/mutex.c.o

lib/platform/posix/mutex.i: lib/platform/posix/mutex.c.i
.PHONY : lib/platform/posix/mutex.i

# target to preprocess a source file
lib/platform/posix/mutex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/mutex.c.i
.PHONY : lib/platform/posix/mutex.c.i

lib/platform/posix/mutex.s: lib/platform/posix/mutex.c.s
.PHONY : lib/platform/posix/mutex.s

# target to generate assembly for a file
lib/platform/posix/mutex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/mutex.c.s
.PHONY : lib/platform/posix/mutex.c.s

lib/platform/posix/password.o: lib/platform/posix/password.c.o
.PHONY : lib/platform/posix/password.o

# target to build an object file
lib/platform/posix/password.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/password.c.o
.PHONY : lib/platform/posix/password.c.o

lib/platform/posix/password.i: lib/platform/posix/password.c.i
.PHONY : lib/platform/posix/password.i

# target to preprocess a source file
lib/platform/posix/password.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/password.c.i
.PHONY : lib/platform/posix/password.c.i

lib/platform/posix/password.s: lib/platform/posix/password.c.s
.PHONY : lib/platform/posix/password.s

# target to generate assembly for a file
lib/platform/posix/password.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/password.c.s
.PHONY : lib/platform/posix/password.c.s

lib/platform/posix/rwlock.o: lib/platform/posix/rwlock.c.o
.PHONY : lib/platform/posix/rwlock.o

# target to build an object file
lib/platform/posix/rwlock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/rwlock.c.o
.PHONY : lib/platform/posix/rwlock.c.o

lib/platform/posix/rwlock.i: lib/platform/posix/rwlock.c.i
.PHONY : lib/platform/posix/rwlock.i

# target to preprocess a source file
lib/platform/posix/rwlock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/rwlock.c.i
.PHONY : lib/platform/posix/rwlock.c.i

lib/platform/posix/rwlock.s: lib/platform/posix/rwlock.c.s
.PHONY : lib/platform/posix/rwlock.s

# target to generate assembly for a file
lib/platform/posix/rwlock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/rwlock.c.s
.PHONY : lib/platform/posix/rwlock.c.s

lib/platform/posix/socket.o: lib/platform/posix/socket.c.o
.PHONY : lib/platform/posix/socket.o

# target to build an object file
lib/platform/posix/socket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/socket.c.o
.PHONY : lib/platform/posix/socket.c.o

lib/platform/posix/socket.i: lib/platform/posix/socket.c.i
.PHONY : lib/platform/posix/socket.i

# target to preprocess a source file
lib/platform/posix/socket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/socket.c.i
.PHONY : lib/platform/posix/socket.c.i

lib/platform/posix/socket.s: lib/platform/posix/socket.c.s
.PHONY : lib/platform/posix/socket.s

# target to generate assembly for a file
lib/platform/posix/socket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/socket.c.s
.PHONY : lib/platform/posix/socket.c.s

lib/platform/posix/string.o: lib/platform/posix/string.c.o
.PHONY : lib/platform/posix/string.o

# target to build an object file
lib/platform/posix/string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/string.c.o
.PHONY : lib/platform/posix/string.c.o

lib/platform/posix/string.i: lib/platform/posix/string.c.i
.PHONY : lib/platform/posix/string.i

# target to preprocess a source file
lib/platform/posix/string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/string.c.i
.PHONY : lib/platform/posix/string.c.i

lib/platform/posix/string.s: lib/platform/posix/string.c.s
.PHONY : lib/platform/posix/string.s

# target to generate assembly for a file
lib/platform/posix/string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/string.c.s
.PHONY : lib/platform/posix/string.c.s

lib/platform/posix/symbols.o: lib/platform/posix/symbols.c.o
.PHONY : lib/platform/posix/symbols.o

# target to build an object file
lib/platform/posix/symbols.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/symbols.c.o
.PHONY : lib/platform/posix/symbols.c.o

lib/platform/posix/symbols.i: lib/platform/posix/symbols.c.i
.PHONY : lib/platform/posix/symbols.i

# target to preprocess a source file
lib/platform/posix/symbols.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/symbols.c.i
.PHONY : lib/platform/posix/symbols.c.i

lib/platform/posix/symbols.s: lib/platform/posix/symbols.c.s
.PHONY : lib/platform/posix/symbols.s

# target to generate assembly for a file
lib/platform/posix/symbols.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/symbols.c.s
.PHONY : lib/platform/posix/symbols.c.s

lib/platform/posix/system.o: lib/platform/posix/system.c.o
.PHONY : lib/platform/posix/system.o

# target to build an object file
lib/platform/posix/system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/system.c.o
.PHONY : lib/platform/posix/system.c.o

lib/platform/posix/system.i: lib/platform/posix/system.c.i
.PHONY : lib/platform/posix/system.i

# target to preprocess a source file
lib/platform/posix/system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/system.c.i
.PHONY : lib/platform/posix/system.c.i

lib/platform/posix/system.s: lib/platform/posix/system.c.s
.PHONY : lib/platform/posix/system.s

# target to generate assembly for a file
lib/platform/posix/system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/system.c.s
.PHONY : lib/platform/posix/system.c.s

lib/platform/posix/terminal.o: lib/platform/posix/terminal.c.o
.PHONY : lib/platform/posix/terminal.o

# target to build an object file
lib/platform/posix/terminal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/terminal.c.o
.PHONY : lib/platform/posix/terminal.c.o

lib/platform/posix/terminal.i: lib/platform/posix/terminal.c.i
.PHONY : lib/platform/posix/terminal.i

# target to preprocess a source file
lib/platform/posix/terminal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/terminal.c.i
.PHONY : lib/platform/posix/terminal.c.i

lib/platform/posix/terminal.s: lib/platform/posix/terminal.c.s
.PHONY : lib/platform/posix/terminal.s

# target to generate assembly for a file
lib/platform/posix/terminal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/terminal.c.s
.PHONY : lib/platform/posix/terminal.c.s

lib/platform/posix/thread.o: lib/platform/posix/thread.c.o
.PHONY : lib/platform/posix/thread.o

# target to build an object file
lib/platform/posix/thread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/thread.c.o
.PHONY : lib/platform/posix/thread.c.o

lib/platform/posix/thread.i: lib/platform/posix/thread.c.i
.PHONY : lib/platform/posix/thread.i

# target to preprocess a source file
lib/platform/posix/thread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/thread.c.i
.PHONY : lib/platform/posix/thread.c.i

lib/platform/posix/thread.s: lib/platform/posix/thread.c.s
.PHONY : lib/platform/posix/thread.s

# target to generate assembly for a file
lib/platform/posix/thread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-platform.dir/build.make CMakeFiles/ascii-chat-platform.dir/lib/platform/posix/thread.c.s
.PHONY : lib/platform/posix/thread.c.s

lib/ringbuffer.o: lib/ringbuffer.c.o
.PHONY : lib/ringbuffer.o

# target to build an object file
lib/ringbuffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/ringbuffer.c.o
.PHONY : lib/ringbuffer.c.o

lib/ringbuffer.i: lib/ringbuffer.c.i
.PHONY : lib/ringbuffer.i

# target to preprocess a source file
lib/ringbuffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/ringbuffer.c.i
.PHONY : lib/ringbuffer.c.i

lib/ringbuffer.s: lib/ringbuffer.c.s
.PHONY : lib/ringbuffer.s

# target to generate assembly for a file
lib/ringbuffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-audio.dir/build.make CMakeFiles/ascii-chat-audio.dir/lib/ringbuffer.c.s
.PHONY : lib/ringbuffer.c.s

lib/util/aspect_ratio.o: lib/util/aspect_ratio.c.o
.PHONY : lib/util/aspect_ratio.o

# target to build an object file
lib/util/aspect_ratio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/aspect_ratio.c.o
.PHONY : lib/util/aspect_ratio.c.o

lib/util/aspect_ratio.i: lib/util/aspect_ratio.c.i
.PHONY : lib/util/aspect_ratio.i

# target to preprocess a source file
lib/util/aspect_ratio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/aspect_ratio.c.i
.PHONY : lib/util/aspect_ratio.c.i

lib/util/aspect_ratio.s: lib/util/aspect_ratio.c.s
.PHONY : lib/util/aspect_ratio.s

# target to generate assembly for a file
lib/util/aspect_ratio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/aspect_ratio.c.s
.PHONY : lib/util/aspect_ratio.c.s

lib/util/format.o: lib/util/format.c.o
.PHONY : lib/util/format.o

# target to build an object file
lib/util/format.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/format.c.o
.PHONY : lib/util/format.c.o

lib/util/format.i: lib/util/format.c.i
.PHONY : lib/util/format.i

# target to preprocess a source file
lib/util/format.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/format.c.i
.PHONY : lib/util/format.c.i

lib/util/format.s: lib/util/format.c.s
.PHONY : lib/util/format.s

# target to generate assembly for a file
lib/util/format.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/format.c.s
.PHONY : lib/util/format.c.s

lib/util/ip.o: lib/util/ip.c.o
.PHONY : lib/util/ip.o

# target to build an object file
lib/util/ip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/ip.c.o
.PHONY : lib/util/ip.c.o

lib/util/ip.i: lib/util/ip.c.i
.PHONY : lib/util/ip.i

# target to preprocess a source file
lib/util/ip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/ip.c.i
.PHONY : lib/util/ip.c.i

lib/util/ip.s: lib/util/ip.c.s
.PHONY : lib/util/ip.s

# target to generate assembly for a file
lib/util/ip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/ip.c.s
.PHONY : lib/util/ip.c.s

lib/util/math.o: lib/util/math.c.o
.PHONY : lib/util/math.o

# target to build an object file
lib/util/math.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/math.c.o
.PHONY : lib/util/math.c.o

lib/util/math.i: lib/util/math.c.i
.PHONY : lib/util/math.i

# target to preprocess a source file
lib/util/math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/math.c.i
.PHONY : lib/util/math.c.i

lib/util/math.s: lib/util/math.c.s
.PHONY : lib/util/math.s

# target to generate assembly for a file
lib/util/math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/math.c.s
.PHONY : lib/util/math.c.s

lib/util/parsing.o: lib/util/parsing.c.o
.PHONY : lib/util/parsing.o

# target to build an object file
lib/util/parsing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/parsing.c.o
.PHONY : lib/util/parsing.c.o

lib/util/parsing.i: lib/util/parsing.c.i
.PHONY : lib/util/parsing.i

# target to preprocess a source file
lib/util/parsing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/parsing.c.i
.PHONY : lib/util/parsing.c.i

lib/util/parsing.s: lib/util/parsing.c.s
.PHONY : lib/util/parsing.s

# target to generate assembly for a file
lib/util/parsing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/parsing.c.s
.PHONY : lib/util/parsing.c.s

lib/util/path.o: lib/util/path.c.o
.PHONY : lib/util/path.o

# target to build an object file
lib/util/path.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/path.c.o
.PHONY : lib/util/path.c.o

lib/util/path.i: lib/util/path.c.i
.PHONY : lib/util/path.i

# target to preprocess a source file
lib/util/path.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/path.c.i
.PHONY : lib/util/path.c.i

lib/util/path.s: lib/util/path.c.s
.PHONY : lib/util/path.s

# target to generate assembly for a file
lib/util/path.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/path.c.s
.PHONY : lib/util/path.c.s

lib/util/string.o: lib/util/string.c.o
.PHONY : lib/util/string.o

# target to build an object file
lib/util/string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/string.c.o
.PHONY : lib/util/string.c.o

lib/util/string.i: lib/util/string.c.i
.PHONY : lib/util/string.i

# target to preprocess a source file
lib/util/string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/string.c.i
.PHONY : lib/util/string.c.i

lib/util/string.s: lib/util/string.c.s
.PHONY : lib/util/string.s

# target to generate assembly for a file
lib/util/string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-util.dir/build.make CMakeFiles/ascii-chat-util.dir/lib/util/string.c.s
.PHONY : lib/util/string.c.s

lib/util/utf8.o: lib/util/utf8.c.o
.PHONY : lib/util/utf8.o

# target to build an object file
lib/util/utf8.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/util/utf8.c.o
.PHONY : lib/util/utf8.c.o

lib/util/utf8.i: lib/util/utf8.c.i
.PHONY : lib/util/utf8.i

# target to preprocess a source file
lib/util/utf8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/util/utf8.c.i
.PHONY : lib/util/utf8.c.i

lib/util/utf8.s: lib/util/utf8.c.s
.PHONY : lib/util/utf8.s

# target to generate assembly for a file
lib/util/utf8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/util/utf8.c.s
.PHONY : lib/util/utf8.c.s

lib/version.o: lib/version.c.o
.PHONY : lib/version.o

# target to build an object file
lib/version.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/version.c.o
.PHONY : lib/version.c.o

lib/version.i: lib/version.c.i
.PHONY : lib/version.i

# target to preprocess a source file
lib/version.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/version.c.i
.PHONY : lib/version.c.i

lib/version.s: lib/version.c.s
.PHONY : lib/version.s

# target to generate assembly for a file
lib/version.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-core.dir/build.make CMakeFiles/ascii-chat-core.dir/lib/version.c.s
.PHONY : lib/version.c.s

lib/video_frame.o: lib/video_frame.c.o
.PHONY : lib/video_frame.o

# target to build an object file
lib/video_frame.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/video_frame.c.o
.PHONY : lib/video_frame.c.o

lib/video_frame.i: lib/video_frame.c.i
.PHONY : lib/video_frame.i

# target to preprocess a source file
lib/video_frame.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/video_frame.c.i
.PHONY : lib/video_frame.c.i

lib/video_frame.s: lib/video_frame.c.s
.PHONY : lib/video_frame.s

# target to generate assembly for a file
lib/video_frame.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat-video.dir/build.make CMakeFiles/ascii-chat-video.dir/lib/video_frame.c.s
.PHONY : lib/video_frame.c.s

src/client/audio.o: src/client/audio.c.o
.PHONY : src/client/audio.o

# target to build an object file
src/client/audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/audio.c.o
.PHONY : src/client/audio.c.o

src/client/audio.i: src/client/audio.c.i
.PHONY : src/client/audio.i

# target to preprocess a source file
src/client/audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/audio.c.i
.PHONY : src/client/audio.c.i

src/client/audio.s: src/client/audio.c.s
.PHONY : src/client/audio.s

# target to generate assembly for a file
src/client/audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/audio.c.s
.PHONY : src/client/audio.c.s

src/client/capture.o: src/client/capture.c.o
.PHONY : src/client/capture.o

# target to build an object file
src/client/capture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/capture.c.o
.PHONY : src/client/capture.c.o

src/client/capture.i: src/client/capture.c.i
.PHONY : src/client/capture.i

# target to preprocess a source file
src/client/capture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/capture.c.i
.PHONY : src/client/capture.c.i

src/client/capture.s: src/client/capture.c.s
.PHONY : src/client/capture.s

# target to generate assembly for a file
src/client/capture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/capture.c.s
.PHONY : src/client/capture.c.s

src/client/crypto.o: src/client/crypto.c.o
.PHONY : src/client/crypto.o

# target to build an object file
src/client/crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/crypto.c.o
.PHONY : src/client/crypto.c.o

src/client/crypto.i: src/client/crypto.c.i
.PHONY : src/client/crypto.i

# target to preprocess a source file
src/client/crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/crypto.c.i
.PHONY : src/client/crypto.c.i

src/client/crypto.s: src/client/crypto.c.s
.PHONY : src/client/crypto.s

# target to generate assembly for a file
src/client/crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/crypto.c.s
.PHONY : src/client/crypto.c.s

src/client/display.o: src/client/display.c.o
.PHONY : src/client/display.o

# target to build an object file
src/client/display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/display.c.o
.PHONY : src/client/display.c.o

src/client/display.i: src/client/display.c.i
.PHONY : src/client/display.i

# target to preprocess a source file
src/client/display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/display.c.i
.PHONY : src/client/display.c.i

src/client/display.s: src/client/display.c.s
.PHONY : src/client/display.s

# target to generate assembly for a file
src/client/display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/display.c.s
.PHONY : src/client/display.c.s

src/client/keepalive.o: src/client/keepalive.c.o
.PHONY : src/client/keepalive.o

# target to build an object file
src/client/keepalive.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/keepalive.c.o
.PHONY : src/client/keepalive.c.o

src/client/keepalive.i: src/client/keepalive.c.i
.PHONY : src/client/keepalive.i

# target to preprocess a source file
src/client/keepalive.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/keepalive.c.i
.PHONY : src/client/keepalive.c.i

src/client/keepalive.s: src/client/keepalive.c.s
.PHONY : src/client/keepalive.s

# target to generate assembly for a file
src/client/keepalive.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/keepalive.c.s
.PHONY : src/client/keepalive.c.s

src/client/main.o: src/client/main.c.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/main.c.o
.PHONY : src/client/main.c.o

src/client/main.i: src/client/main.c.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/main.c.i
.PHONY : src/client/main.c.i

src/client/main.s: src/client/main.c.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/main.c.s
.PHONY : src/client/main.c.s

src/client/protocol.o: src/client/protocol.c.o
.PHONY : src/client/protocol.o

# target to build an object file
src/client/protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/protocol.c.o
.PHONY : src/client/protocol.c.o

src/client/protocol.i: src/client/protocol.c.i
.PHONY : src/client/protocol.i

# target to preprocess a source file
src/client/protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/protocol.c.i
.PHONY : src/client/protocol.c.i

src/client/protocol.s: src/client/protocol.c.s
.PHONY : src/client/protocol.s

# target to generate assembly for a file
src/client/protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/protocol.c.s
.PHONY : src/client/protocol.c.s

src/client/server.o: src/client/server.c.o
.PHONY : src/client/server.o

# target to build an object file
src/client/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/server.c.o
.PHONY : src/client/server.c.o

src/client/server.i: src/client/server.c.i
.PHONY : src/client/server.i

# target to preprocess a source file
src/client/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/server.c.i
.PHONY : src/client/server.c.i

src/client/server.s: src/client/server.c.s
.PHONY : src/client/server.s

# target to generate assembly for a file
src/client/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/client/server.c.s
.PHONY : src/client/server.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/main.c.s
.PHONY : src/main.c.s

src/server/client.o: src/server/client.c.o
.PHONY : src/server/client.o

# target to build an object file
src/server/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/client.c.o
.PHONY : src/server/client.c.o

src/server/client.i: src/server/client.c.i
.PHONY : src/server/client.i

# target to preprocess a source file
src/server/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/client.c.i
.PHONY : src/server/client.c.i

src/server/client.s: src/server/client.c.s
.PHONY : src/server/client.s

# target to generate assembly for a file
src/server/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/client.c.s
.PHONY : src/server/client.c.s

src/server/crypto.o: src/server/crypto.c.o
.PHONY : src/server/crypto.o

# target to build an object file
src/server/crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/crypto.c.o
.PHONY : src/server/crypto.c.o

src/server/crypto.i: src/server/crypto.c.i
.PHONY : src/server/crypto.i

# target to preprocess a source file
src/server/crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/crypto.c.i
.PHONY : src/server/crypto.c.i

src/server/crypto.s: src/server/crypto.c.s
.PHONY : src/server/crypto.s

# target to generate assembly for a file
src/server/crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/crypto.c.s
.PHONY : src/server/crypto.c.s

src/server/main.o: src/server/main.c.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/main.c.o
.PHONY : src/server/main.c.o

src/server/main.i: src/server/main.c.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/main.c.i
.PHONY : src/server/main.c.i

src/server/main.s: src/server/main.c.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/main.c.s
.PHONY : src/server/main.c.s

src/server/protocol.o: src/server/protocol.c.o
.PHONY : src/server/protocol.o

# target to build an object file
src/server/protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/protocol.c.o
.PHONY : src/server/protocol.c.o

src/server/protocol.i: src/server/protocol.c.i
.PHONY : src/server/protocol.i

# target to preprocess a source file
src/server/protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/protocol.c.i
.PHONY : src/server/protocol.c.i

src/server/protocol.s: src/server/protocol.c.s
.PHONY : src/server/protocol.s

# target to generate assembly for a file
src/server/protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/protocol.c.s
.PHONY : src/server/protocol.c.s

src/server/render.o: src/server/render.c.o
.PHONY : src/server/render.o

# target to build an object file
src/server/render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/render.c.o
.PHONY : src/server/render.c.o

src/server/render.i: src/server/render.c.i
.PHONY : src/server/render.i

# target to preprocess a source file
src/server/render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/render.c.i
.PHONY : src/server/render.c.i

src/server/render.s: src/server/render.c.s
.PHONY : src/server/render.s

# target to generate assembly for a file
src/server/render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/render.c.s
.PHONY : src/server/render.c.s

src/server/stats.o: src/server/stats.c.o
.PHONY : src/server/stats.o

# target to build an object file
src/server/stats.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/stats.c.o
.PHONY : src/server/stats.c.o

src/server/stats.i: src/server/stats.c.i
.PHONY : src/server/stats.i

# target to preprocess a source file
src/server/stats.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/stats.c.i
.PHONY : src/server/stats.c.i

src/server/stats.s: src/server/stats.c.s
.PHONY : src/server/stats.s

# target to generate assembly for a file
src/server/stats.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/stats.c.s
.PHONY : src/server/stats.c.s

src/server/stream.o: src/server/stream.c.o
.PHONY : src/server/stream.o

# target to build an object file
src/server/stream.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/stream.c.o
.PHONY : src/server/stream.c.o

src/server/stream.i: src/server/stream.c.i
.PHONY : src/server/stream.i

# target to preprocess a source file
src/server/stream.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/stream.c.i
.PHONY : src/server/stream.c.i

src/server/stream.s: src/server/stream.c.s
.PHONY : src/server/stream.s

# target to generate assembly for a file
src/server/stream.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-chat.dir/build.make CMakeFiles/ascii-chat.dir/src/server/stream.c.s
.PHONY : src/server/stream.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... alsa-lib-musl"
	@echo "... ascii-chat-static"
	@echo "... bearssl_build"
	@echo "... clang-format"
	@echo "... clang-tidy"
	@echo "... clean_all"
	@echo "... format"
	@echo "... format-check"
	@echo "... generate_version"
	@echo "... libexecinfo-musl"
	@echo "... libsodium-musl"
	@echo "... portaudio-musl"
	@echo "... scan-build"
	@echo "... zstd-musl"
	@echo "... ascii-chat"
	@echo "... ascii-chat-audio"
	@echo "... ascii-chat-core"
	@echo "... ascii-chat-crypto"
	@echo "... ascii-chat-data-structures"
	@echo "... ascii-chat-network"
	@echo "... ascii-chat-platform"
	@echo "... ascii-chat-shared"
	@echo "... ascii-chat-simd"
	@echo "... ascii-chat-util"
	@echo "... ascii-chat-video"
	@echo "... empty.o"
	@echo "... empty.i"
	@echo "... empty.s"
	@echo "... lib/asciichat_errno.o"
	@echo "... lib/asciichat_errno.i"
	@echo "... lib/asciichat_errno.s"
	@echo "... lib/audio.o"
	@echo "... lib/audio.i"
	@echo "... lib/audio.s"
	@echo "... lib/buffer_pool.o"
	@echo "... lib/buffer_pool.i"
	@echo "... lib/buffer_pool.s"
	@echo "... lib/common.o"
	@echo "... lib/common.i"
	@echo "... lib/common.s"
	@echo "... lib/compression.o"
	@echo "... lib/compression.i"
	@echo "... lib/compression.s"
	@echo "... lib/crc32.o"
	@echo "... lib/crc32.i"
	@echo "... lib/crc32.s"
	@echo "... lib/crypto/crypto.o"
	@echo "... lib/crypto/crypto.i"
	@echo "... lib/crypto/crypto.s"
	@echo "... lib/crypto/gpg.o"
	@echo "... lib/crypto/gpg.i"
	@echo "... lib/crypto/gpg.s"
	@echo "... lib/crypto/handshake.o"
	@echo "... lib/crypto/handshake.i"
	@echo "... lib/crypto/handshake.s"
	@echo "... lib/crypto/http_client.o"
	@echo "... lib/crypto/http_client.i"
	@echo "... lib/crypto/http_client.s"
	@echo "... lib/crypto/keys/gpg_keys.o"
	@echo "... lib/crypto/keys/gpg_keys.i"
	@echo "... lib/crypto/keys/gpg_keys.s"
	@echo "... lib/crypto/keys/https_keys.o"
	@echo "... lib/crypto/keys/https_keys.i"
	@echo "... lib/crypto/keys/https_keys.s"
	@echo "... lib/crypto/keys/keys.o"
	@echo "... lib/crypto/keys/keys.i"
	@echo "... lib/crypto/keys/keys.s"
	@echo "... lib/crypto/keys/ssh_keys.o"
	@echo "... lib/crypto/keys/ssh_keys.i"
	@echo "... lib/crypto/keys/ssh_keys.s"
	@echo "... lib/crypto/keys/validation.o"
	@echo "... lib/crypto/keys/validation.i"
	@echo "... lib/crypto/keys/validation.s"
	@echo "... lib/crypto/known_hosts.o"
	@echo "... lib/crypto/known_hosts.i"
	@echo "... lib/crypto/known_hosts.s"
	@echo "... lib/crypto/pem_utils.o"
	@echo "... lib/crypto/pem_utils.i"
	@echo "... lib/crypto/pem_utils.s"
	@echo "... lib/crypto/ssh_agent.o"
	@echo "... lib/crypto/ssh_agent.i"
	@echo "... lib/crypto/ssh_agent.s"
	@echo "... lib/hashtable.o"
	@echo "... lib/hashtable.i"
	@echo "... lib/hashtable.s"
	@echo "... lib/image2ascii/ansi_fast.o"
	@echo "... lib/image2ascii/ansi_fast.i"
	@echo "... lib/image2ascii/ansi_fast.s"
	@echo "... lib/image2ascii/ascii.o"
	@echo "... lib/image2ascii/ascii.i"
	@echo "... lib/image2ascii/ascii.s"
	@echo "... lib/image2ascii/image.o"
	@echo "... lib/image2ascii/image.i"
	@echo "... lib/image2ascii/image.s"
	@echo "... lib/image2ascii/output_buffer.o"
	@echo "... lib/image2ascii/output_buffer.i"
	@echo "... lib/image2ascii/output_buffer.s"
	@echo "... lib/image2ascii/simd/ascii_simd.o"
	@echo "... lib/image2ascii/simd/ascii_simd.i"
	@echo "... lib/image2ascii/simd/ascii_simd.s"
	@echo "... lib/image2ascii/simd/ascii_simd_color.o"
	@echo "... lib/image2ascii/simd/ascii_simd_color.i"
	@echo "... lib/image2ascii/simd/ascii_simd_color.s"
	@echo "... lib/image2ascii/simd/avx2.o"
	@echo "... lib/image2ascii/simd/avx2.i"
	@echo "... lib/image2ascii/simd/avx2.s"
	@echo "... lib/image2ascii/simd/common.o"
	@echo "... lib/image2ascii/simd/common.i"
	@echo "... lib/image2ascii/simd/common.s"
	@echo "... lib/lock_debug.o"
	@echo "... lib/lock_debug.i"
	@echo "... lib/lock_debug.s"
	@echo "... lib/logging.o"
	@echo "... lib/logging.i"
	@echo "... lib/logging.s"
	@echo "... lib/mixer.o"
	@echo "... lib/mixer.i"
	@echo "... lib/mixer.s"
	@echo "... lib/musl_c23_compat.o"
	@echo "... lib/musl_c23_compat.i"
	@echo "... lib/musl_c23_compat.s"
	@echo "... lib/network/av.o"
	@echo "... lib/network/av.i"
	@echo "... lib/network/av.s"
	@echo "... lib/network/network.o"
	@echo "... lib/network/network.i"
	@echo "... lib/network/network.s"
	@echo "... lib/network/packet.o"
	@echo "... lib/network/packet.i"
	@echo "... lib/network/packet.s"
	@echo "... lib/options.o"
	@echo "... lib/options.i"
	@echo "... lib/options.s"
	@echo "... lib/os/linux/webcam_v4l2.o"
	@echo "... lib/os/linux/webcam_v4l2.i"
	@echo "... lib/os/linux/webcam_v4l2.s"
	@echo "... lib/os/webcam.o"
	@echo "... lib/os/webcam.i"
	@echo "... lib/os/webcam.s"
	@echo "... lib/packet_queue.o"
	@echo "... lib/packet_queue.i"
	@echo "... lib/packet_queue.s"
	@echo "... lib/palette.o"
	@echo "... lib/palette.i"
	@echo "... lib/palette.s"
	@echo "... lib/platform/abstraction.o"
	@echo "... lib/platform/abstraction.i"
	@echo "... lib/platform/abstraction.s"
	@echo "... lib/platform/posix/cond.o"
	@echo "... lib/platform/posix/cond.i"
	@echo "... lib/platform/posix/cond.s"
	@echo "... lib/platform/posix/mutex.o"
	@echo "... lib/platform/posix/mutex.i"
	@echo "... lib/platform/posix/mutex.s"
	@echo "... lib/platform/posix/password.o"
	@echo "... lib/platform/posix/password.i"
	@echo "... lib/platform/posix/password.s"
	@echo "... lib/platform/posix/rwlock.o"
	@echo "... lib/platform/posix/rwlock.i"
	@echo "... lib/platform/posix/rwlock.s"
	@echo "... lib/platform/posix/socket.o"
	@echo "... lib/platform/posix/socket.i"
	@echo "... lib/platform/posix/socket.s"
	@echo "... lib/platform/posix/string.o"
	@echo "... lib/platform/posix/string.i"
	@echo "... lib/platform/posix/string.s"
	@echo "... lib/platform/posix/symbols.o"
	@echo "... lib/platform/posix/symbols.i"
	@echo "... lib/platform/posix/symbols.s"
	@echo "... lib/platform/posix/system.o"
	@echo "... lib/platform/posix/system.i"
	@echo "... lib/platform/posix/system.s"
	@echo "... lib/platform/posix/terminal.o"
	@echo "... lib/platform/posix/terminal.i"
	@echo "... lib/platform/posix/terminal.s"
	@echo "... lib/platform/posix/thread.o"
	@echo "... lib/platform/posix/thread.i"
	@echo "... lib/platform/posix/thread.s"
	@echo "... lib/ringbuffer.o"
	@echo "... lib/ringbuffer.i"
	@echo "... lib/ringbuffer.s"
	@echo "... lib/util/aspect_ratio.o"
	@echo "... lib/util/aspect_ratio.i"
	@echo "... lib/util/aspect_ratio.s"
	@echo "... lib/util/format.o"
	@echo "... lib/util/format.i"
	@echo "... lib/util/format.s"
	@echo "... lib/util/ip.o"
	@echo "... lib/util/ip.i"
	@echo "... lib/util/ip.s"
	@echo "... lib/util/math.o"
	@echo "... lib/util/math.i"
	@echo "... lib/util/math.s"
	@echo "... lib/util/parsing.o"
	@echo "... lib/util/parsing.i"
	@echo "... lib/util/parsing.s"
	@echo "... lib/util/path.o"
	@echo "... lib/util/path.i"
	@echo "... lib/util/path.s"
	@echo "... lib/util/string.o"
	@echo "... lib/util/string.i"
	@echo "... lib/util/string.s"
	@echo "... lib/util/utf8.o"
	@echo "... lib/util/utf8.i"
	@echo "... lib/util/utf8.s"
	@echo "... lib/version.o"
	@echo "... lib/version.i"
	@echo "... lib/version.s"
	@echo "... lib/video_frame.o"
	@echo "... lib/video_frame.i"
	@echo "... lib/video_frame.s"
	@echo "... src/client/audio.o"
	@echo "... src/client/audio.i"
	@echo "... src/client/audio.s"
	@echo "... src/client/capture.o"
	@echo "... src/client/capture.i"
	@echo "... src/client/capture.s"
	@echo "... src/client/crypto.o"
	@echo "... src/client/crypto.i"
	@echo "... src/client/crypto.s"
	@echo "... src/client/display.o"
	@echo "... src/client/display.i"
	@echo "... src/client/display.s"
	@echo "... src/client/keepalive.o"
	@echo "... src/client/keepalive.i"
	@echo "... src/client/keepalive.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/protocol.o"
	@echo "... src/client/protocol.i"
	@echo "... src/client/protocol.s"
	@echo "... src/client/server.o"
	@echo "... src/client/server.i"
	@echo "... src/client/server.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/server/client.o"
	@echo "... src/server/client.i"
	@echo "... src/server/client.s"
	@echo "... src/server/crypto.o"
	@echo "... src/server/crypto.i"
	@echo "... src/server/crypto.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/protocol.o"
	@echo "... src/server/protocol.i"
	@echo "... src/server/protocol.s"
	@echo "... src/server/render.o"
	@echo "... src/server/render.i"
	@echo "... src/server/render.s"
	@echo "... src/server/stats.o"
	@echo "... src/server/stats.i"
	@echo "... src/server/stats.s"
	@echo "... src/server/stream.o"
	@echo "... src/server/stream.i"
	@echo "... src/server/stream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

