ascii-chat: abstraction.c File Reference
abstraction.c File Reference
🏗️ Common platform abstraction stubs (OS-specific code in posix/ and windows/ subdirectories)
Functions
size_t platform_write_all (int fd, const void *buf, size_t count)
Write all data to file descriptor with automatic retry on transient errors.
bool terminal_should_use_control_sequences (int fd)
Check if terminal control sequences should be used for the given fd.
Detailed Description
🏗️ Common platform abstraction stubs (OS-specific code in posix/ and windows/ subdirectories)
Definition in file abstraction.c.
Function Documentation
platform_write_all()
size_t platform_write_all (int fd, const void * buf, size_t count)
Write all data to file descriptor with automatic retry on transient errors.
Handles incomplete writes and transient errors (EAGAIN, EWOULDBLOCK) by retrying. This ensures complete writes even under high load or when piping to tools like tee.
Parameters
fd File descriptor to write to
buf Buffer containing data to write
count Number of bytes to write
Returns
Number of bytes written (should equal count if all data written), or -1 if failed
Definition at line 39 of file abstraction.c.
{
  if (!buf || count == 0) {
    return 0;
  }
  size_t written_total = 0;
  int attempts = 0;
  const int MAX_ATTEMPTS = 1000;
  while (written_total < count && attempts < MAX_ATTEMPTS) {
    ssize_t result = platform_write(fd, (const char *)buf + written_total, count - written_total);
    if (result > 0) {
      written_total += (size_t)result;
      attempts = 0; // Reset attempt counter on successful write
    } else if (result < 0) {
      // Handle EAGAIN (non-blocking would-block) with sleep instead of tight loop
      if (errno == EAGAIN || errno == EWOULDBLOCK) {
        // Sleep 100us before retrying to avoid busy-waiting and spinning CPU
        platform_sleep_us(100);
      } else {
        // Other write errors - log and retry
        log_warn("platform_write_all: write() error on fd=%d (wrote %zu/%zu so far, errno=%d)", fd, written_total,
                 count, errno);
      }
      attempts++;
    } else {
      // result == 0: no bytes written, retry
      attempts++;
    }
  }
  if (attempts >= MAX_ATTEMPTS && written_total < count) {
    log_warn("platform_write_all: Hit retry limit on fd=%d: wrote %zu of %zu bytes", fd, written_total, count);
  }
  return written_total;
}
References platform_sleep_us(), and platform_write().
Referenced by ascii_write(), config_create_default(), frame_buffer_flush(), log_console_impl(), log_json_async_safe(), log_search_render_input_line(), session_client_like_run(), session_display_render_fps_overlay(), session_display_write_ascii(), session_display_write_raw(), and terminal_screen_render().
terminal_should_use_control_sequences()
bool terminal_should_use_control_sequences (int fd)
Check if terminal control sequences should be used for the given fd.
Parameters
fd File descriptor to check
Returns
true if terminal control sequences should be used, false otherwise
This function determines whether to send terminal POSITIONING and CONTROL sequences (cursor home, clear screen, hide cursor, etc.) which should only be sent to TTY and never to pipes/redirected output.
Note: This does NOT control ANSI COLOR CODES, which are controlled by –color-mode option and may be sent to pipes if explicitly requested.
Definition at line 90 of file abstraction.c.
{
  if (fd < 0) {
    return false;
  }
  if (GET_OPTION(snapshot_mode)) {
    return false;
  }
  const char *testing_env = SAFE_GETENV("TESTING");
  if (testing_env != NULL) {
    return false;
  }
  return platform_isatty(fd) != 0;
}
References platform_isatty().
Referenced by ascii_write(), ascii_write_destroy(), and ascii_write_init().