ascii-chat: asciichat_errno.c File Reference
asciichat_errno.c File Reference
🚨 Custom error code system with formatted messages, thread-local storage, and errno mapping
Macros
#define MAX_THREAD_ERRORS 64
Functions
void log_labeled (const char *label, log_color_t color, const char *message,...)
void asciichat_set_errno (asciichat_error_t code, const char *file, int line, const char *function, const char *context_message)
void asciichat_set_errno_with_message (asciichat_error_t code, const char *file, int line, const char *function, const char *format,...)
void asciichat_set_errno_with_system_error (asciichat_error_t code, const char *file, int line, const char *function, int sys_errno)
void asciichat_set_errno_with_system_error_and_message (asciichat_error_t code, const char *file, int line, const char *function, int sys_errno, const char *format,...)
void asciichat_set_errno_with_wsa_error (asciichat_error_t code, const char *file, int line, const char *function, int wsa_error)
bool asciichat_has_wsa_error (void)
bool asciichat_has_errno (asciichat_error_context_t *context)
void asciichat_clear_errno (void)
asciichat_error_t asciichat_get_errno (void)
void asciichat_fatal_with_context (asciichat_error_t code, const char *file, int line, const char *function, const char *format,...)
void asciichat_print_error_context (const asciichat_error_context_t *context)
void asciichat_error_stats_init (void)
void asciichat_error_stats_record (asciichat_error_t code)
void asciichat_error_stats_print (void)
void asciichat_error_stats_reset (void)
asciichat_error_stats_t asciichat_error_stats_get (void)
asciichat_error_t asciichat_get_thread_error (int thread_id)
void asciichat_set_thread_error (int thread_id, asciichat_error_t code)
void asciichat_clear_thread_error (int thread_id)
void asciichat_errno_suppress (bool suppress)
void asciichat_errno_destroy (void)
Variables
__thread asciichat_error_context_t asciichat_errno_context
__thread asciichat_error_t asciichat_errno = ASCIICHAT_OK
Detailed Description
🚨 Custom error code system with formatted messages, thread-local storage, and errno mapping
Definition in file asciichat_errno.c.
Macro Definition Documentation
MAX_THREAD_ERRORS
#define MAX_THREAD_ERRORS 64
Definition at line 64 of file asciichat_errno.c.
Referenced by asciichat_clear_thread_error(), asciichat_get_thread_error(), and asciichat_set_thread_error().
Function Documentation
asciichat_clear_errno()
void asciichat_clear_errno (void)
Definition at line 233 of file asciichat_errno.c.
{
  if (asciichat_errno_context.context_message) {
    SAFE_FREE(asciichat_errno_context.context_message);
    asciichat_errno_context.context_message = NULL;
  }
  backtrace_t_free(&asciichat_errno_context.backtrace);
  memset(&asciichat_errno_context, 0, sizeof(asciichat_errno_context));
  asciichat_errno_context.code = ASCIICHAT_OK;
  asciichat_errno_context.system_errno = 0;
  asciichat_errno_context.has_system_error = false;
  asciichat_errno_context.has_wsa_error = false;
  asciichat_errno_context.wsa_error = 0;
  /* Clear platform-specific error state */
  platform_clear_error_state();
}
References asciichat_errno_context, backtrace_t_free(), and platform_clear_error_state().
asciichat_clear_thread_error()
void asciichat_clear_thread_error (int thread_id)
Definition at line 477 of file asciichat_errno.c.
{
  for (int i = 0; i < MAX_THREAD_ERRORS; i++) {
    if (thread_errors[i].valid && thread_errors[i].thread_id == thread_id) {
      thread_errors[i].valid = false;
      break;
    }
  }
}
References MAX_THREAD_ERRORS, thread_id, and valid.
asciichat_errno_destroy()
void asciichat_errno_destroy (void)
Definition at line 495 of file asciichat_errno.c.
{
  backtrace_t_free(&asciichat_errno_context.backtrace);
  if (asciichat_errno_context.context_message != NULL) {
    SAFE_FREE(asciichat_errno_context.context_message);
  }
  // Reset the context to a clean state
  memset(&asciichat_errno_context, 0, sizeof(asciichat_errno_context));
  asciichat_errno_context.code = ASCIICHAT_OK;
  // Suppress any further error context allocation to prevent cleanup-phase leaks
  // This prevents other atexit() functions from allocating new contexts after we've cleaned up
  g_suppress_error_context = true;
}
References asciichat_errno_context, and backtrace_t_free().
Referenced by asciichat_shared_destroy(), client_audio_render_thread(), client_receive_thread(), client_send_thread_func(), client_video_render_thread(), and stats_logger_thread().
asciichat_errno_suppress()
void asciichat_errno_suppress (bool suppress)
Definition at line 491 of file asciichat_errno.c.
{
  g_suppress_error_context = suppress;
}
asciichat_error_stats_get()
asciichat_error_stats_t asciichat_error_stats_get (void)
Definition at line 431 of file asciichat_errno.c.
{
  if (!lifecycle_is_initialized(&g_error_stats.lifecycle)) {
    lifecycle_init(&g_error_stats.lifecycle, "error_stats");
  }
  mutex_lock(&g_error_stats.mutex);
  asciichat_error_stats_t result = g_error_stats.stats;
  mutex_unlock(&g_error_stats.mutex);
  return result;
}
References lifecycle_init(), and lifecycle_is_initialized().
asciichat_error_stats_init()
void asciichat_error_stats_init (void)
Definition at line 359 of file asciichat_errno.c.
{
  if (lifecycle_init(&g_error_stats.lifecycle, "error_stats")) {
    memset(&g_error_stats.stats, 0, sizeof(g_error_stats.stats));
  }
}
References lifecycle_init().
asciichat_error_stats_print()
void asciichat_error_stats_print (void)
Definition at line 382 of file asciichat_errno.c.
{
  if (!lifecycle_is_initialized(&g_error_stats.lifecycle)) {
    log_plain("No errors recorded.\n");
    return;
  }
  mutex_lock(&g_error_stats.mutex);
  if (g_error_stats.stats.total_errors == 0) {
    mutex_unlock(&g_error_stats.mutex);
    log_plain("No errors recorded.\n");
    return;
  }
  // Copy stats to local variable to minimize lock hold time
  asciichat_error_stats_t local_stats = g_error_stats.stats;
  mutex_unlock(&g_error_stats.mutex);
  log_plain("\n=== ascii-chat Error Statistics ===\n");
  log_plain("Total errors: %llu\n", (unsigned long long)local_stats.total_errors);
  if (local_stats.last_error_time > 0) {
    time_t sec = (time_t)(local_stats.last_error_time / NS_PER_MS_INT);
    struct tm tm_info;
    if (platform_localtime(&sec, &tm_info) == ASCIICHAT_OK) {
      char time_str[64];
      strftime(time_str, sizeof(time_str), "%Y-%m-%d %H:%M:%S", &tm_info);
      log_plain("Last error: %s (code %d)\n", time_str, (int)local_stats.last_error_code);
    }
  }
  log_plain("\nError breakdown:\n");
  for (int i = 0; i < 256; i++) {
    if (local_stats.error_counts[i] > 0) {
      log_plain("  %3d (%s): %llu\n", i, asciichat_error_string((asciichat_error_t)i),
                (unsigned long long)local_stats.error_counts[i]);
    }
  }
  log_plain("\n");
}
References lifecycle_is_initialized(), and platform_localtime().
Referenced by server_main(), and stats_logger_thread().
asciichat_error_stats_record()
void asciichat_error_stats_record (asciichat_error_t code)
Definition at line 365 of file asciichat_errno.c.
{
  if (!lifecycle_is_initialized(&g_error_stats.lifecycle)) {
    lifecycle_init(&g_error_stats.lifecycle, "error_stats");
  }
  mutex_lock(&g_error_stats.mutex);
  if (code >= 0 && code < 256) {
    g_error_stats.stats.error_counts[code]++;
  }
  g_error_stats.stats.total_errors++;
  g_error_stats.stats.last_error_time = time_ns_to_us(time_get_realtime_ns());
  g_error_stats.stats.last_error_code = code;
  mutex_unlock(&g_error_stats.mutex);
}
References lifecycle_init(), lifecycle_is_initialized(), and time_get_realtime_ns().
Referenced by asciichat_set_errno().
asciichat_error_stats_reset()
void asciichat_error_stats_reset (void)
Definition at line 423 of file asciichat_errno.c.
{
  if (lifecycle_is_initialized(&g_error_stats.lifecycle)) {
    mutex_lock(&g_error_stats.mutex);
    memset(&g_error_stats.stats, 0, sizeof(g_error_stats.stats));
    mutex_unlock(&g_error_stats.mutex);
  }
}
References lifecycle_is_initialized().
asciichat_fatal_with_context()
void asciichat_fatal_with_context (asciichat_error_t code, const char * file, int line, const char * function, const char * format, ...)
Definition at line 261 of file asciichat_errno.c.
{
  (void)file;
  (void)line;
  (void)function;
  // Print library error context if available
  asciichat_error_context_t err_ctx;
  if (HAS_ERRNO(&err_ctx)) {
    log_labeled("\nasciichat_errno: libary code error context", LOG_COLOR_ERROR, "");
    asciichat_print_error_context(&err_ctx);
  } else {
    log_plain("WARNING: No error context found (asciichat_errno_context.code=%d)", asciichat_errno_context.code);
  }
  safe_fprintf(stderr, "\n");
  log_labeled("FATAL ERROR", LOG_COLOR_FATAL, "exit code %d (%s)", (int)code, asciichat_error_string(code));
#ifndef NDEBUG
  const char *relative_file = extract_project_relative_path(file);
  log_plain("  Location: %s:%d in %s()", relative_file, line, function);
#endif
  if (format) {
    va_list args;
    va_start(args, format);
    char *formatted_message = format_message(format, args);
    log_plain("  Error message: %s", formatted_message);
    SAFE_FREE(formatted_message);
    va_end(args);
  }
#ifndef NDEBUG
  // Always print platform backtrace in debug/dev builds
  backtrace_t bt = {0};
  backtrace_capture_and_symbolize(&bt);
  if (bt.count > 0) {
    backtrace_print("\nFATAL BACKTRACE", &bt, 0, 0, skip_backtrace_frame);
    backtrace_t_free(&bt);
  }
#endif
  exit(code);
}
References args, asciichat_errno_context, asciichat_print_error_context(), backtrace_capture_and_symbolize(), backtrace_print(), backtrace_t_free(), extract_project_relative_path(), format_message(), log_labeled(), and safe_fprintf().
asciichat_get_errno()
asciichat_error_t asciichat_get_errno (void)
Definition at line 252 of file asciichat_errno.c.
{
  return asciichat_errno_context.code;
}
References asciichat_errno_context.
asciichat_get_thread_error()
asciichat_error_t asciichat_get_thread_error (int thread_id)
Definition at line 448 of file asciichat_errno.c.
{
  for (int i = 0; i < MAX_THREAD_ERRORS; i++) {
    if (thread_errors[i].valid && thread_errors[i].thread_id == thread_id) {
      return thread_errors[i].error_code;
    }
  }
  return ASCIICHAT_OK;
}
References MAX_THREAD_ERRORS, thread_id, and valid.
asciichat_has_errno()
bool asciichat_has_errno (asciichat_error_context_t * context)
Definition at line 221 of file asciichat_errno.c.
{
  if (asciichat_errno_context.code == ASCIICHAT_OK) {
    return false;
  }
  if (context) {
    *context = asciichat_errno_context;
  }
  return true;
}
References asciichat_errno_context.
asciichat_has_wsa_error()
bool asciichat_has_wsa_error (void)
Definition at line 212 of file asciichat_errno.c.
{
  return asciichat_errno_context.has_wsa_error;
}
References asciichat_errno_context.
asciichat_print_error_context()
void asciichat_print_error_context (const asciichat_error_context_t * context)
Definition at line 310 of file asciichat_errno.c.
{
  if (!context || context->code == ASCIICHAT_OK) {
    return;
  }
  if (context->file && context->line && context->function) {
    log_plain("  Location: %s:%d in %s()", extract_project_relative_path(context->file), context->line,
              context->function);
  } else {
    log_plain("  Location: unknown (set by system code)");
  }
  if (context->context_message) {
    safe_fprintf(stderr, "  %s %s\n", colored_string(LOG_COLOR_WARN, "Context:"), context->context_message);
    log_file("  Context: %s", context->context_message);
  }
  if (context->has_system_error) {
    log_plain("  System error: %s (code: %d, meaning: %s)", SAFE_STRERROR(context->system_errno), context->system_errno,
              SAFE_STRERROR(context->system_errno));
  }
  // Print timestamp
  if (context->timestamp > 0) {
    time_t sec = (time_t)(context->timestamp / NS_PER_MS_INT);
    long usec = (long)(context->timestamp % NS_PER_MS_INT);
    struct tm tm_info;
    if (platform_localtime(&sec, &tm_info) == ASCIICHAT_OK) {
      char time_str[64];
      (void)strftime(time_str, sizeof(time_str), "%Y-%m-%d %H:%M:%S", &tm_info);
      log_plain("  Timestamp: %s.%06ld", time_str, usec);
    }
  }
  // Print stack trace from library error
  if (context->backtrace.count > 0) {
    // Symbolize backtrace only when actually printing it (not at capture time)
    backtrace_symbolize(&context->backtrace);
    if (context->backtrace.symbols) {
      backtrace_print("\nBacktrace from library error", &context->backtrace, 0, 0, skip_backtrace_frame);
    }
  }
}
References backtrace_print(), backtrace_symbolize(), colored_string(), extract_project_relative_path(), platform_localtime(), and safe_fprintf().
Referenced by asciichat_fatal_with_context().
asciichat_set_errno()
void asciichat_set_errno (asciichat_error_t code, const char * file, int line, const char * function, const char * context_message)
Definition at line 113 of file asciichat_errno.c.
{
  // Suppress error context allocation during cleanup to prevent leaks
  if (g_suppress_error_context) {
    return;
  }
  // Clear any existing context message
  if (asciichat_errno_context.context_message) {
    SAFE_FREE(asciichat_errno_context.context_message);
    asciichat_errno_context.context_message = NULL;
  }
  // Set the error context
  asciichat_errno_context.code = code;
  asciichat_errno_context.file = file;
  asciichat_errno_context.line = line;
  asciichat_errno_context.function = function;
  asciichat_errno_context.timestamp = time_ns_to_us(time_get_realtime_ns());
  asciichat_errno_context.has_system_error = false;
  // Set the simple error code variable
  asciichat_errno = code;
  // Copy context message if provided
  if (context_message == NULL) {
    log_error("context_message is NULL");
    const char *fallback = "No context message (this is invalid - set a context message)";
    size_t len = strlen(fallback) + 1;
    asciichat_errno_context.context_message = SAFE_MALLOC(len, char *);
    if (asciichat_errno_context.context_message) {
      SAFE_STRNCPY(asciichat_errno_context.context_message, fallback, len);
    } else {
      log_error("SAFE_MALLOC failed for fallback context_message");
    }
  } else {
    size_t len = strlen(context_message) + 1;
    asciichat_errno_context.context_message = SAFE_MALLOC(len, char *);
    if (asciichat_errno_context.context_message) {
      SAFE_STRNCPY(asciichat_errno_context.context_message, context_message, len);
    } else {
      log_error("SAFE_MALLOC failed for context_message");
    }
  }
  // Capture stack trace in debug builds
  backtrace_t_free(&asciichat_errno_context.backtrace);
  capture_backtrace(&asciichat_errno_context.backtrace);
  // Record in statistics
  asciichat_error_stats_record(code);
}
References asciichat_errno, asciichat_errno_context, asciichat_error_stats_record(), backtrace_t_free(), and time_get_realtime_ns().
Referenced by asciichat_set_errno_with_message(), asciichat_set_errno_with_system_error(), asciichat_set_errno_with_system_error_and_message(), and asciichat_set_errno_with_wsa_error().
asciichat_set_errno_with_message()
void asciichat_set_errno_with_message (asciichat_error_t code, const char * file, int line, const char * function, const char * format, ...)
Definition at line 166 of file asciichat_errno.c.
{
  va_list args;
  va_start(args, format);
  char *context_message = format_message(format, args);
  asciichat_set_errno(code, file, line, function, context_message);
  if (context_message) {
    SAFE_FREE(context_message);
  }
  va_end(args);
}
References args, asciichat_set_errno(), and format_message().
asciichat_set_errno_with_system_error()
void asciichat_set_errno_with_system_error (asciichat_error_t code, const char * file, int line, const char * function, int sys_errno)
Definition at line 181 of file asciichat_errno.c.
{
  asciichat_set_errno(code, file, line, function, NULL);
  asciichat_errno_context.system_errno = sys_errno;
  asciichat_errno_context.has_system_error = true;
}
References asciichat_errno_context, and asciichat_set_errno().
asciichat_set_errno_with_system_error_and_message()
void asciichat_set_errno_with_system_error_and_message (asciichat_error_t code, const char * file, int line, const char * function, int sys_errno, const char * format, ...)
Definition at line 188 of file asciichat_errno.c.
{
  va_list args;
  va_start(args, format);
  char *context_message = format_message(format, args);
  asciichat_set_errno(code, file, line, function, context_message);
  asciichat_errno_context.system_errno = sys_errno;
  asciichat_errno_context.has_system_error = true;
  if (context_message) {
    SAFE_FREE(context_message);
  }
  va_end(args);
}
References args, asciichat_errno_context, asciichat_set_errno(), and format_message().
asciichat_set_errno_with_wsa_error()
void asciichat_set_errno_with_wsa_error (asciichat_error_t code, const char * file, int line, const char * function, int wsa_error)
Definition at line 205 of file asciichat_errno.c.
{
  asciichat_set_errno(code, file, line, function, NULL);
  asciichat_errno_context.wsa_error = wsa_error;
  asciichat_errno_context.has_wsa_error = true;
}
References asciichat_errno_context, and asciichat_set_errno().
asciichat_set_thread_error()
void asciichat_set_thread_error (int thread_id, asciichat_error_t code)
Definition at line 457 of file asciichat_errno.c.
{
  // Find existing entry or empty slot
  int slot = -1;
  for (int i = 0; i < MAX_THREAD_ERRORS; i++) {
    if (thread_errors[i].valid && thread_errors[i].thread_id == thread_id) {
      slot = i;
      break;
    }
    if (!thread_errors[i].valid && slot == -1) {
      slot = i;
    }
  }
  if (slot >= 0) {
    thread_errors[slot].thread_id = thread_id;
    thread_errors[slot].error_code = code;
    thread_errors[slot].valid = true;
  }
}
References MAX_THREAD_ERRORS, thread_id, and valid.
log_labeled()
void log_labeled (const char * label, log_color_t color, const char * message, ...)
Definition at line 95 of file asciichat_errno.c.
{
  va_list args;
  va_start(args, message);
  char *formatted_message = format_message(message, args);
  va_end(args);
  safe_fprintf(stderr, "%s: %s\n", colored_string(color, label), formatted_message);
  log_file("%s: %s", label, formatted_message);
  SAFE_FREE(formatted_message);
}
References args, colored_string(), format_message(), and safe_fprintf().
Referenced by asciichat_fatal_with_context().
Variable Documentation
asciichat_errno
__thread asciichat_error_t asciichat_errno = ASCIICHAT_OK
Definition at line 43 of file asciichat_errno.c.
Referenced by accept_with_timeout(), and asciichat_set_errno().
asciichat_errno_context
__thread asciichat_error_context_t asciichat_errno_context
Initial value:
= {.code = ASCIICHAT_OK,
   .file = NULL,
   .line = 0,
   .function = NULL,
   .context_message = NULL,
   .timestamp = 0,
   .system_errno = 0,
   .backtrace = {.count = 0, .symbols = NULL},
   .has_system_error = false}
Definition at line 33 of file asciichat_errno.c.
                                                           {.code = ASCIICHAT_OK,
                                                              .file = NULL,
                                                              .line = 0,
                                                              .function = NULL,
                                                              .context_message = NULL,
                                                              .timestamp = 0,
                                                              .system_errno = 0,
                                                              .backtrace = {.count = 0, .symbols = NULL},
                                                              .has_system_error = false};
Referenced by accept_with_timeout(), asciichat_clear_errno(), asciichat_errno_destroy(), asciichat_fatal_with_context(), asciichat_get_errno(), asciichat_has_errno(), asciichat_has_wsa_error(), asciichat_set_errno(), asciichat_set_errno_with_system_error(), asciichat_set_errno_with_system_error_and_message(), and asciichat_set_errno_with_wsa_error().
error_code
asciichat_error_t error_code
Definition at line 67 of file asciichat_errno.c.
Referenced by accept_with_timeout(), acip_send_error(), acip_server_send_error(), connect_with_timeout(), packet_send_error(), send_error_packet(), send_error_packet_message(), and webcam_print_init_error_help().
lifecycle
lifecycle_t lifecycle
Definition at line 56 of file asciichat_errno.c.
mutex
mutex_t mutex
Definition at line 55 of file asciichat_errno.c.
Referenced by cond_on_wait(), debug_sync_cond_timedwait(), debug_sync_cond_wait(), debug_sync_mutex_lock(), debug_sync_mutex_trylock(), debug_sync_mutex_unlock(), mutex_destroy(), mutex_format_state(), mutex_init(), mutex_lock_impl(), mutex_log_state(), mutex_on_lock(), mutex_on_trylock(), mutex_on_unlock(), mutex_trylock_impl(), mutex_unlock_impl(), and outputRegistryMutex().
stats
asciichat_error_stats_t stats
Definition at line 54 of file asciichat_errno.c.
Referenced by stats_logger_thread(), update_server_stats(), video_frame_get_stats(), and websocket_callback_timing_record().
thread_id
int thread_id
Definition at line 66 of file asciichat_errno.c.
Referenced by asciichat_clear_thread_error(), asciichat_get_thread_error(), asciichat_set_thread_error(), mutex_stack_cleanup_current_thread(), mutex_stack_detect_deadlocks(), ascii_query::LLDBController::operator=(), and ascii_query::LLDBController::selectThread().
valid
bool valid
Definition at line 68 of file asciichat_errno.c.
Referenced by asciichat_clear_thread_error(), asciichat_get_thread_error(), asciichat_set_thread_error(), and database_session_verify_key().