ascii-chat: aspect_ratio.c File Reference
aspect_ratio.c File Reference
📐 Terminal cell aspect ratio calculations for accurate image dimension scaling
Macros
#define CHAR_ASPECT 2.0f
Enumerations
enum { MIN_DIMENSION = 1 }
Functions
void aspect_ratio (const ssize_t img_w, const ssize_t img_h, const ssize_t width, const ssize_t height, const bool stretch, ssize_t *out_width, ssize_t *out_height)
void aspect_ratio2 (const ssize_t img_w, const ssize_t img_h, const ssize_t target_w, const ssize_t target_h, ssize_t *out_width, ssize_t *out_height)
void calculate_fit_dimensions_pixel (int img_width, int img_height, int max_width, int max_height, int *out_width, int *out_height)
Detailed Description
📐 Terminal cell aspect ratio calculations for accurate image dimension scaling
Definition in file aspect_ratio.c.
Macro Definition Documentation
CHAR_ASPECT
#define CHAR_ASPECT 2.0f
Definition at line 10 of file aspect_ratio.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MIN_DIMENSION
Definition at line 13 of file aspect_ratio.c.
     {
  MIN_DIMENSION = 1 // minimum width/height to prevent zero dimensions
};
Function Documentation
aspect_ratio()
void aspect_ratio (const ssize_t img_w, const ssize_t img_h, const ssize_t width, const ssize_t height, const bool stretch, ssize_t * out_width, ssize_t * out_height)
Definition at line 69 of file aspect_ratio.c.
{
  // Input validation
  if (!out_width || !out_height) {
    return; // or log error
  }
  if (img_w <= 0 || img_h <= 0) {
    // Handle degenerate image dimensions
    *out_width = MIN_DIMENSION;
    *out_height = MIN_DIMENSION;
    return;
  }
  if (stretch) {
    // If stretching is enabled, just use the full terminal dimensions
    *out_width = width;
    *out_height = height;
  } else {
    // Calculate aspect-correct dimensions to fit within the given width/height
    calculate_fit_dimensions(img_w, img_h, width, height, out_width, out_height);
  }
}
References MIN_DIMENSION.
Referenced by ascii_convert(), ascii_convert_with_capabilities(), and mirror_convert_frame().
aspect_ratio2()
void aspect_ratio2 (const ssize_t img_w, const ssize_t img_h, const ssize_t target_w, const ssize_t target_h, ssize_t * out_width, ssize_t * out_height)
Definition at line 95 of file aspect_ratio.c.
{
  // Input validation
  if (!out_width || !out_height) {
    return;
  }
  if (img_w <= 0 || img_h <= 0 || target_w <= 0 || target_h <= 0) {
    // Handle invalid dimensions
    *out_width = MIN_DIMENSION;
    *out_height = MIN_DIMENSION;
    return;
  }
  // Calculate aspect ratio
  float img_aspect = (float)img_w / (float)img_h;
  // We want the image to fill at least one dimension of the target box
  // while maintaining aspect ratio and fitting within the box
  // Calculate dimensions if we scale to fill width
  ssize_t width_if_fill_width = target_w;
  ssize_t height_if_fill_width = (ssize_t)((float)target_w / img_aspect);
  // Calculate dimensions if we scale to fill height
  ssize_t width_if_fill_height = (ssize_t)((float)target_h * img_aspect);
  ssize_t height_if_fill_height = target_h;
  // Choose the scaling that maximizes usage of the target box
  // We want to fill at least one dimension completely
  if (height_if_fill_width <= target_h) {
    // Filling width fits within height - use it
    *out_width = width_if_fill_width;
    *out_height = height_if_fill_width;
  } else {
    // Filling width would exceed height, so fill height instead
    *out_width = width_if_fill_height;
    *out_height = height_if_fill_height;
  }
  // Ensure minimum dimensions
  if (*out_width <= 0) {
    *out_width = MIN_DIMENSION;
  }
  if (*out_height <= 0) {
    *out_height = MIN_DIMENSION;
  }
}
References MIN_DIMENSION.
calculate_fit_dimensions_pixel()
void calculate_fit_dimensions_pixel (int img_width, int img_height, int max_width, int max_height, int * out_width, int * out_height)
Definition at line 146 of file aspect_ratio.c.
{
  if (!out_width || !out_height || img_width <= 0 || img_height <= 0) {
    if (out_width)
      *out_width = max_width;
    if (out_height)
      *out_height = max_height;
    return;
  }
  float src_aspect = (float)img_width / (float)img_height;
  // Try filling width
  int width_if_fill_w = max_width;
  int height_if_fill_w = (int)(((float)max_width / src_aspect) + 0.5f);
  // Try filling height
  int width_if_fill_h = (int)(((float)max_height * src_aspect) + 0.5f);
  int height_if_fill_h = max_height;
  // log_debug("calculate_fit_dimensions: img %dx%d (aspect %.3f), max %dx%d", img_width, img_height, src_aspect,
  //           max_width, max_height);
  // log_debug("  Fill width: %dx%d, Fill height: %dx%d", width_if_fill_w, height_if_fill_w, width_if_fill_h,
  //           height_if_fill_h);
  // Choose the option that fits
  if (height_if_fill_w <= max_height) {
    // Filling width fits
    // log_debug("  Choosing fill width: %dx%d", width_if_fill_w, height_if_fill_w);
    *out_width = width_if_fill_w;
    *out_height = height_if_fill_w;
  } else {
    // Fill height instead
    // log_debug("  Choosing fill height: %dx%d", width_if_fill_h, height_if_fill_h);
    *out_width = width_if_fill_h;
    *out_height = height_if_fill_h;
  }
  // Clamp to bounds
  if (*out_width > max_width)
    *out_width = max_width;
  if (*out_height > max_height)
    *out_height = max_height;
  if (*out_width < 1)
    *out_width = 1;
  if (*out_height < 1)
    *out_height = 1;
  // log_debug("  Final output: %dx%d", *out_width, *out_height);
}