ascii-chat: atomic.c File Reference
atomic.c File Reference
Implementation of atomic operations abstraction.
Functions
bool atomic_load_bool_impl (const atomic_t *a)
void atomic_store_bool_impl (atomic_t *a, uint64_t value)
bool atomic_cas_bool_impl (atomic_t *a, uint64_t *expected, uint64_t new_value)
int atomic_load_int_impl (const atomic_t *a)
void atomic_store_int_impl (atomic_t *a, uint64_t value)
int atomic_fetch_add_int_impl (atomic_t *a, int64_t delta)
int atomic_fetch_sub_int_impl (atomic_t *a, int64_t delta)
uint64_t atomic_load_u64_impl (const atomic_t *a)
void atomic_store_u64_impl (atomic_t *a, uint64_t value)
uint64_t atomic_fetch_add_u64_impl (atomic_t *a, uint64_t delta)
uint64_t atomic_fetch_sub_u64_impl (atomic_t *a, uint64_t delta)
bool atomic_cas_u64_impl (atomic_t *a, uint64_t *expected, uint64_t new_value)
bool atomic_cas_int_impl (atomic_t *a, int64_t *expected, int64_t new_value)
void * atomic_ptr_load_impl (const atomic_ptr_t *a)
void atomic_ptr_store_impl (atomic_ptr_t *a, void *value)
bool atomic_ptr_cas_impl (atomic_ptr_t *a, void **expected, void *new_value)
void * atomic_ptr_exchange_impl (atomic_ptr_t *a, void *new_value)
bool atomic_exchange_bool_impl (atomic_t *a, bool new_value)
int atomic_exchange_int_impl (atomic_t *a, int new_value)
uint64_t atomic_exchange_u64_impl (atomic_t *a, uint64_t new_value)
bool atomic_load_bool (atomic_t *a)
void atomic_store_bool (atomic_t *a, bool value)
bool atomic_cas_bool (atomic_t *a, bool *expected, bool new_value)
int atomic_load_int (atomic_t *a)
void atomic_store_int (atomic_t *a, int value)
int atomic_fetch_add_int (atomic_t *a, int delta)
int atomic_fetch_sub_int (atomic_t *a, int delta)
bool atomic_cas_int (atomic_t *a, int *expected, int new_value)
uint64_t atomic_load_u64 (atomic_t *a)
void atomic_store_u64 (atomic_t *a, uint64_t value)
uint64_t atomic_fetch_add_u64 (atomic_t *a, uint64_t delta)
uint64_t atomic_fetch_sub_u64 (atomic_t *a, uint64_t delta)
bool atomic_cas_u64 (atomic_t *a, uint64_t *expected, uint64_t new_value)
void * atomic_ptr_load (atomic_ptr_t *a)
void atomic_ptr_store (atomic_ptr_t *a, void *value)
bool atomic_ptr_cas (atomic_ptr_t *a, void **expected, void *new_value)
void * atomic_ptr_exchange (atomic_ptr_t *a, void *new_value)
bool atomic_exchange_bool (atomic_t *a, bool new_value)
int atomic_exchange_int (atomic_t *a, int new_value)
uint64_t atomic_exchange_u64 (atomic_t *a, uint64_t new_value)
bool debug_atomic_is_initialized (void)
void atomic_on_load (atomic_t *a)
void atomic_on_store (atomic_t *a)
void atomic_on_cas (atomic_t *a, bool success)
void atomic_on_fetch (atomic_t *a)
void atomic_ptr_on_load (atomic_ptr_t *a)
void atomic_ptr_on_store (atomic_ptr_t *a)
void atomic_ptr_on_cas (atomic_ptr_t *a, bool success)
void atomic_ptr_on_exchange (atomic_ptr_t *a)
Detailed Description
Implementation of atomic operations abstraction.
Date
March 2026
Provides _impl functions for atomic operations. In debug builds, these functions are wrapped by the typed macros to include debug hooks. In release builds, the macros call these directly for zero overhead.
Design: Uses raw C11 atomic operations internally, never calls back into the atomic_t system (no recursion). Debug hooks are called after the atomic operation completes.
Definition in file atomic.c.
Function Documentation
atomic_cas_bool()
bool atomic_cas_bool (atomic_t * a, bool * expected, bool new_value)
Definition at line 159 of file atomic.c.
{
    if (!a || !expected) return false;
    uint64_t exp = (uint64_t)*expected;
    bool success = atomic_compare_exchange_strong((_Atomic(uint64_t) *)&a->impl, &exp, (uint64_t)new_value);
    *expected = (bool)exp;
    atomic_on_cas(a, success);
    return success;
}
References atomic_on_cas(), and bool.
Referenced by handle_image_frame_packet(), log_lock_terminal(), log_search_check_signal_cancel(), splash_intro_start(), and symbol_cache_init().
atomic_cas_bool_impl()
bool atomic_cas_bool_impl (atomic_t * a, uint64_t * expected, uint64_t new_value)
Definition at line 35 of file atomic.c.
{
    if (!a || !expected) return false;
    return atomic_compare_exchange_strong((_Atomic(uint64_t) *)&a->impl, expected, new_value);
}
atomic_cas_int()
bool atomic_cas_int (atomic_t * a, int * expected, int new_value)
Definition at line 195 of file atomic.c.
{
    if (!a || !expected) return false;
    int64_t exp = (int64_t)*expected;
    bool success = atomic_cas_int_impl(a, &exp, (int64_t)new_value);
    *expected = (int)exp;
    atomic_on_cas(a, success);
    return success;
}
References atomic_cas_int_impl(), and atomic_on_cas().
atomic_cas_int_impl()
bool atomic_cas_int_impl (atomic_t * a, int64_t * expected, int64_t new_value)
Definition at line 93 of file atomic.c.
{
    if (!a || !expected) return false;
    uint64_t expected_u64 = (uint64_t)*expected;
    bool result = atomic_compare_exchange_strong((_Atomic(uint64_t) *)&a->impl, &expected_u64, (uint64_t)new_value);
    *expected = (int64_t)expected_u64;
    return result;
}
Referenced by atomic_cas_int().
atomic_cas_u64()
bool atomic_cas_u64 (atomic_t * a, uint64_t * expected, uint64_t new_value)
Definition at line 231 of file atomic.c.
{
    if (!a || !expected) return false;
    bool success = atomic_compare_exchange_strong((_Atomic(uint64_t) *)&a->impl, expected, new_value);
    atomic_on_cas(a, success);
    return success;
}
References atomic_on_cas().
Referenced by buffer_pool_alloc(), create_mixed_ascii_frame_for_client(), lifecycle_destroy_once(), lifecycle_init(), lifecycle_init_once(), lifecycle_reset(), lifecycle_shutdown(), lifecycle_shutdown_forever(), and websocket_callback_timing_record().
atomic_cas_u64_impl()
bool atomic_cas_u64_impl (atomic_t * a, uint64_t * expected, uint64_t new_value)
Definition at line 88 of file atomic.c.
{
    if (!a || !expected) return false;
    return atomic_compare_exchange_strong((_Atomic(uint64_t) *)&a->impl, expected, new_value);
}
atomic_exchange_bool()
bool atomic_exchange_bool (atomic_t * a, bool new_value)
Definition at line 265 of file atomic.c.
{
    if (!a) return false;
    bool result = (bool)atomic_exchange((_Atomic(uint64_t) *)&a->impl, (uint64_t)new_value);
    atomic_on_store(a);
    return result;
}
References atomic_on_store(), and bool.
Referenced by disconnect_client_for_bad_data(), display_disable_logging_for_first_frame(), handle_image_frame_h265_packet(), and session_display_write_ascii().
atomic_exchange_bool_impl()
bool atomic_exchange_bool_impl (atomic_t * a, bool new_value)
Definition at line 125 of file atomic.c.
{
    if (!a) return false;
    return (bool)atomic_exchange((_Atomic(uint64_t) *)&a->impl, (uint64_t)new_value);
}
atomic_exchange_int()
int atomic_exchange_int (atomic_t * a, int new_value)
Definition at line 272 of file atomic.c.
{
    if (!a) return 0;
    int result = (int)(int32_t)atomic_exchange((_Atomic(uint64_t) *)&a->impl, (uint64_t)(int32_t)new_value);
    atomic_on_store(a);
    return result;
}
References atomic_on_store().
atomic_exchange_int_impl()
int atomic_exchange_int_impl (atomic_t * a, int new_value)
Definition at line 130 of file atomic.c.
{
    if (!a) return 0;
    return (int)(int32_t)atomic_exchange((_Atomic(uint64_t) *)&a->impl, (uint64_t)(int32_t)new_value);
}
atomic_exchange_u64()
uint64_t atomic_exchange_u64 (atomic_t * a, uint64_t new_value)
Definition at line 279 of file atomic.c.
{
    if (!a) return 0;
    uint64_t result = atomic_exchange((_Atomic(uint64_t) *)&a->impl, new_value);
    atomic_on_store(a);
    return result;
}
References atomic_on_store().
atomic_exchange_u64_impl()
uint64_t atomic_exchange_u64_impl (atomic_t * a, uint64_t new_value)
Definition at line 135 of file atomic.c.
{
    if (!a) return 0;
    return atomic_exchange((_Atomic(uint64_t) *)&a->impl, new_value);
}
atomic_fetch_add_int()
int atomic_fetch_add_int (atomic_t * a, int delta)
Definition at line 181 of file atomic.c.
{
    if (!a) return 0;
    int result = (int)(int32_t)atomic_fetch_add((_Atomic(uint64_t) *)&a->impl, (uint64_t)(int64_t)delta);
    atomic_on_fetch(a);
    return result;
}
References atomic_on_fetch().
atomic_fetch_add_int_impl()
int atomic_fetch_add_int_impl (atomic_t * a, int64_t delta)
Definition at line 54 of file atomic.c.
{
    if (!a) return 0;
    return (int)(int32_t)atomic_fetch_add((_Atomic(uint64_t) *)&a->impl, (uint64_t)delta);
}
atomic_fetch_add_u64()
uint64_t atomic_fetch_add_u64 (atomic_t * a, uint64_t delta)
Definition at line 217 of file atomic.c.
{
    if (!a) return 0;
    uint64_t result = atomic_fetch_add((_Atomic(uint64_t) *)&a->impl, delta);
    atomic_on_fetch(a);
    return result;
}
References atomic_on_fetch().
Referenced by audio_ring_buffer_read(), buffer_pool_alloc(), buffer_pool_free(), buffer_pool_shrink(), client_send_thread_func(), cond_on_wait(), get_utf8_palette_cache(), log_mmap_rotate(), log_mmap_write(), node_pool_get(), packet_queue_enqueue(), packet_queue_enqueue_packet(), packet_queue_try_dequeue(), ringbuffer_write(), rwlock_on_rdlock(), session_log_buffer_append(), symbol_cache_lookup(), video_frame_commit(), and websocket_callback_timing_record().
atomic_fetch_add_u64_impl()
uint64_t atomic_fetch_add_u64_impl (atomic_t * a, uint64_t delta)
Definition at line 78 of file atomic.c.
{
    if (!a) return 0;
    return atomic_fetch_add((_Atomic(uint64_t) *)&a->impl, delta);
}
atomic_fetch_sub_int()
int atomic_fetch_sub_int (atomic_t * a, int delta)
Definition at line 188 of file atomic.c.
{
    if (!a) return 0;
    int result = (int)(int32_t)atomic_fetch_sub((_Atomic(uint64_t) *)&a->impl, (uint64_t)(int64_t)delta);
    atomic_on_fetch(a);
    return result;
}
References atomic_on_fetch().
atomic_fetch_sub_int_impl()
int atomic_fetch_sub_int_impl (atomic_t * a, int64_t delta)
Definition at line 59 of file atomic.c.
{
    if (!a) return 0;
    return (int)(int32_t)atomic_fetch_sub((_Atomic(uint64_t) *)&a->impl, (uint64_t)delta);
}
atomic_fetch_sub_u64()
uint64_t atomic_fetch_sub_u64 (atomic_t * a, uint64_t delta)
Definition at line 224 of file atomic.c.
{
    if (!a) return 0;
    uint64_t result = atomic_fetch_sub((_Atomic(uint64_t) *)&a->impl, delta);
    atomic_on_fetch(a);
    return result;
}
References atomic_on_fetch().
Referenced by buffer_pool_alloc(), buffer_pool_free(), buffer_pool_shrink(), cond_on_signal(), log_mmap_write(), node_pool_put(), packet_queue_enqueue(), packet_queue_enqueue_packet(), packet_queue_try_dequeue(), ringbuffer_read(), and rwlock_on_unlock().
atomic_fetch_sub_u64_impl()
uint64_t atomic_fetch_sub_u64_impl (atomic_t * a, uint64_t delta)
Definition at line 83 of file atomic.c.
{
    if (!a) return 0;
    return atomic_fetch_sub((_Atomic(uint64_t) *)&a->impl, delta);
}
atomic_load_bool()
bool atomic_load_bool (atomic_t * a)
Definition at line 146 of file atomic.c.
{
    if (!a) return false;
    bool result = (bool)atomic_load((const _Atomic(uint64_t) *)&a->impl);
    atomic_on_load(a);
    return result;
}
References atomic_on_load(), and bool.
Referenced by acds_client_handler(), add_client(), add_webrtc_client(), any_clients_sending_video(), audio_start_thread(), audio_stop_thread(), audio_thread_exited(), audio_write_samples(), broadcast_server_state_to_all_clients(), capture_stop_thread(), capture_thread_exited(), client_audio_render_thread(), client_dispatch_thread(), client_receive_thread(), client_send_thread_func(), client_video_render_thread(), debug_sync_is_cleanup_in_progress(), find_client_by_socket(), handle_audio_batch_packet(), handle_audio_opus_packet(), handle_image_frame_h265_packet(), handle_image_frame_packet(), handle_ping_packet(), keepalive_stop_thread(), keepalive_thread_exited(), keyboard_help_is_active(), keyboard_help_toggle(), log_lock_terminal(), log_msg(), log_search_needs_rerender(), mutex_stack_cleanup(), mutex_stack_cleanup_current_thread(), packet_queue_enqueue(), packet_queue_enqueue_packet(), packet_queue_try_dequeue(), protocol_connection_lost(), protocol_stop_connection(), remove_client(), send_server_state_to_client(), server_connection_is_active(), server_connection_is_lost(), server_main(), session_display_has_first_frame(), session_display_write_ascii(), session_pipeline_run_main(), should_exit(), simple_frame_swap_update(), splash_is_running(), splash_wait_for_animation(), stats_logger_thread(), stop_client_render_threads(), tcp_client_is_active(), tcp_client_is_lost(), tcp_client_send_packet(), tcp_client_signal_lost(), tcp_server_run(), threaded_send_audio_batch_packet(), threaded_send_audio_opus(), threaded_send_audio_opus_batch(), threaded_send_packet(), update_server_stats(), video_frame_commit(), websocket_client_is_active(), websocket_client_is_lost(), websocket_client_send_packet(), and websocket_server_run().
atomic_load_bool_impl()
bool atomic_load_bool_impl (const atomic_t * a)
Definition at line 25 of file atomic.c.
{
    if (!a) return false;
    return (bool)atomic_load((const _Atomic(uint64_t) *)&a->impl);
}
atomic_load_int()
int atomic_load_int (atomic_t * a)
Definition at line 168 of file atomic.c.
{
    if (!a) return 0;
    int result = (int)(int32_t)atomic_load((const _Atomic(uint64_t) *)&a->impl);
    atomic_on_load(a);
    return result;
}
References atomic_on_load().
Referenced by log_console_impl(), log_destroy(), log_disable_file_output(), log_init(), log_msg(), log_plain_msg(), log_search_get_global_highlight(), log_search_get_match_info(), log_search_get_pattern_singleton(), log_search_is_active(), log_search_is_entering(), log_search_is_entering_atomic(), log_truncate_if_large(), mutex_stack_cleanup(), mutex_stack_cleanup_current_thread(), and mutex_stack_get_all_threads().
atomic_load_int_impl()
int atomic_load_int_impl (const atomic_t * a)
Definition at line 44 of file atomic.c.
{
    if (!a) return 0;
    return (int)(int32_t)atomic_load((const _Atomic(uint64_t) *)&a->impl);
}
atomic_load_u64()
uint64_t atomic_load_u64 (atomic_t * a)
Definition at line 204 of file atomic.c.
{
    if (!a) return 0;
    uint64_t result = atomic_load((const _Atomic(uint64_t) *)&a->impl);
    atomic_on_load(a);
    return result;
}
References atomic_on_load().
Referenced by asciichat_pcre2_cleanup_all(), asciichat_pcre2_singleton_free(), asciichat_pcre2_singleton_get_code(), asciichat_pcre2_singleton_is_initialized(), audio_ring_buffer_available_read(), audio_ring_buffer_peek(), audio_ring_buffer_read(), audio_ring_buffer_write(), buffer_pool_alloc(), buffer_pool_free(), buffer_pool_get_stats(), buffer_pool_log_stats(), buffer_pool_shrink(), cond_format_state(), cond_on_signal(), create_mixed_ascii_frame_for_client(), get_utf8_palette_cache(), lifecycle_is_dead(), lifecycle_is_initialized(), lifecycle_shutdown_forever(), log_file_msg(), log_get_force_stderr(), log_get_level(), log_get_terminal_output(), log_init(), log_mmap_destroy(), log_mmap_get_stats(), log_mmap_get_usage(), log_mmap_rotate(), log_msg(), log_plain_msg(), log_shutdown_begin(), log_terminal_msg(), node_pool_get(), packet_queue_enqueue(), packet_queue_enqueue_packet(), packet_queue_get_stats(), packet_queue_is_full(), packet_queue_size(), packet_queue_try_dequeue(), protocol_stop_connection(), ringbuffer_peek(), ringbuffer_read(), ringbuffer_size(), ringbuffer_write(), rwlock_format_state(), rwlock_on_unlock(), session_display_write_audio(), session_log_buffer_append(), session_log_buffer_get_recent(), simple_frame_swap_get(), symbol_cache_destroy(), symbol_cache_get_stats(), symbol_cache_print_stats(), threaded_send_client_join_packet(), video_frame_get_stats(), websocket_callback_timing_log_stats(), and websocket_callback_timing_record().
atomic_load_u64_impl()
uint64_t atomic_load_u64_impl (const atomic_t * a)
Definition at line 68 of file atomic.c.
{
    if (!a) return 0;
    return atomic_load((const _Atomic(uint64_t) *)&a->impl);
}
atomic_on_cas()
void atomic_on_cas (atomic_t * a, bool success)
Definition at line 305 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->cas_count++;
    if (success) {
        a->cas_success_count++;
        a->last_store_time_ns = time_get_ns();
    }
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_cas_bool(), atomic_cas_int(), and atomic_cas_u64().
atomic_on_fetch()
void atomic_on_fetch (atomic_t * a)
Definition at line 314 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->fetch_count++;
    a->last_store_time_ns = time_get_ns();
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_fetch_add_int(), atomic_fetch_add_u64(), atomic_fetch_sub_int(), and atomic_fetch_sub_u64().
atomic_on_load()
void atomic_on_load (atomic_t * a)
Definition at line 293 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->last_load_time_ns = time_get_ns();
    a->load_count++;
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_load_bool(), atomic_load_int(), and atomic_load_u64().
atomic_on_store()
void atomic_on_store (atomic_t * a)
Definition at line 299 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->last_store_time_ns = time_get_ns();
    a->store_count++;
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_exchange_bool(), atomic_exchange_int(), atomic_exchange_u64(), atomic_store_bool(), atomic_store_int(), and atomic_store_u64().
atomic_ptr_cas()
bool atomic_ptr_cas (atomic_ptr_t * a, void ** expected, void * new_value)
Definition at line 251 of file atomic.c.
{
    if (!a || !expected) return false;
    bool success = atomic_compare_exchange_strong((_Atomic(void *) *)&a->impl, expected, new_value);
    atomic_ptr_on_cas(a, success);
    return success;
}
References atomic_ptr_on_cas().
Referenced by buffer_pool_alloc(), buffer_pool_free(), buffer_pool_shrink(), node_pool_get(), node_pool_put(), packet_queue_enqueue(), packet_queue_enqueue_packet(), and packet_queue_try_dequeue().
atomic_ptr_cas_impl()
bool atomic_ptr_cas_impl (atomic_ptr_t * a, void ** expected, void * new_value)
Definition at line 115 of file atomic.c.
{
    if (!a || !expected) return false;
    return atomic_compare_exchange_strong((_Atomic(void *) *)&a->impl, expected, new_value);
}
atomic_ptr_exchange()
void * atomic_ptr_exchange (atomic_ptr_t * a, void * new_value)
Definition at line 258 of file atomic.c.
{
    if (!a) return NULL;
    void *result = atomic_exchange((_Atomic(void *) *)&a->impl, new_value);
    atomic_ptr_on_exchange(a);
    return result;
}
References atomic_ptr_on_exchange().
Referenced by buffer_pool_shrink().
atomic_ptr_exchange_impl()
void * atomic_ptr_exchange_impl (atomic_ptr_t * a, void * new_value)
Definition at line 120 of file atomic.c.
{
    if (!a) return NULL;
    return atomic_exchange((_Atomic(void *) *)&a->impl, new_value);
}
atomic_ptr_load()
void * atomic_ptr_load (atomic_ptr_t * a)
Definition at line 238 of file atomic.c.
{
    if (!a) return NULL;
    void *result = atomic_load((const _Atomic(void *) *)&a->impl);
    atomic_ptr_on_load(a);
    return result;
}
References atomic_ptr_on_load().
Referenced by buffer_pool_alloc(), buffer_pool_destroy(), buffer_pool_free(), buffer_pool_shrink(), log_get_session_log_buffer(), node_pool_get(), node_pool_put(), options_get(), options_state_destroy(), options_state_set(), packet_queue_enqueue(), packet_queue_enqueue_packet(), packet_queue_try_dequeue(), and shutdown_is_requested().
atomic_ptr_load_impl()
void * atomic_ptr_load_impl (const atomic_ptr_t * a)
Definition at line 105 of file atomic.c.
{
    if (!a) return NULL;
    return atomic_load((const _Atomic(void *) *)&a->impl);
}
atomic_ptr_on_cas()
void atomic_ptr_on_cas (atomic_ptr_t * a, bool success)
Definition at line 332 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->cas_count++;
    if (success) {
        a->cas_success_count++;
        a->last_store_time_ns = time_get_ns();
    }
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_ptr_cas().
atomic_ptr_on_exchange()
void atomic_ptr_on_exchange (atomic_ptr_t * a)
Definition at line 341 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->exchange_count++;
    a->last_store_time_ns = time_get_ns();
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_ptr_exchange().
atomic_ptr_on_load()
void atomic_ptr_on_load (atomic_ptr_t * a)
Definition at line 320 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->last_load_time_ns = time_get_ns();
    a->load_count++;
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_ptr_load().
atomic_ptr_on_store()
void atomic_ptr_on_store (atomic_ptr_t * a)
Definition at line 326 of file atomic.c.
{
    if (!a || !debug_atomic_is_initialized()) return;
    a->last_store_time_ns = time_get_ns();
    a->store_count++;
}
References debug_atomic_is_initialized(), and time_get_ns().
Referenced by atomic_ptr_store().
atomic_ptr_store()
void atomic_ptr_store (atomic_ptr_t * a, void * value)
Definition at line 245 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(void *) *)&a->impl, value);
    atomic_ptr_on_store(a);
}
References atomic_ptr_on_store().
Referenced by buffer_pool_alloc(), buffer_pool_create(), buffer_pool_free(), buffer_pool_shrink(), log_clear_session_log_buffer(), log_set_session_log_buffer(), node_pool_create(), node_pool_get(), node_pool_put(), options_state_destroy(), options_state_init(), packet_queue_create_with_pools(), packet_queue_enqueue(), packet_queue_enqueue_packet(), packet_queue_try_dequeue(), and shutdown_register_callback().
atomic_ptr_store_impl()
void atomic_ptr_store_impl (atomic_ptr_t * a, void * value)
Definition at line 110 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(void *) *)&a->impl, value);
}
atomic_store_bool()
void atomic_store_bool (atomic_t * a, bool value)
Definition at line 153 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(uint64_t) *)&a->impl, (uint64_t)value);
    atomic_on_store(a);
}
References atomic_on_store().
Referenced by acds_server_init(), acds_server_shutdown(), acip_websocket_client_transport_create(), add_client(), add_webrtc_client(), app_client_create(), audio_destroy(), audio_init(), audio_sender_cleanup(), audio_sender_init(), audio_start_duplex(), audio_start_thread(), audio_stop_duplex(), audio_stop_thread(), capture_start_thread(), client_receive_thread(), client_send_thread_func(), client_video_render_thread(), create_client_render_threads(), debug_sync_cleanup_thread(), debug_sync_print_backtrace_delayed(), debug_sync_print_state_delayed(), debug_sync_start_thread(), debug_sync_trigger_print(), disconnect_client_for_bad_data(), display_reset_for_new_connection(), handle_client_leave_packet(), handle_stream_start_packet(), handle_stream_stop_packet(), keepalive_start_thread(), keyboard_help_toggle(), log_destroy(), log_init(), log_search_enter_mode(), log_search_exit_mode(), log_search_handle_key(), log_search_init(), log_search_needs_rerender(), log_search_signal_cancel(), log_set_level(), log_shutdown_begin(), mutex_stack_cleanup(), packet_queue_create_with_pools(), protocol_start_connection(), remove_client(), server_connection_close(), server_connection_establish(), server_connection_init(), server_connection_lost(), server_connection_set_transport(), server_connection_shutdown(), server_main(), session_client_like_run(), session_display_create(), session_display_reset_first_frame(), session_pipeline_create(), session_pipeline_destroy(), session_pipeline_run_main(), signal_exit(), simple_frame_swap_create(), simple_frame_swap_update(), splash_intro_start(), splash_wait_for_animation(), stop_client_render_threads(), stop_client_threads(), tcp_client_close(), tcp_client_connect(), tcp_client_create(), tcp_client_shutdown(), tcp_client_signal_lost(), tcp_server_destroy(), tcp_server_init(), video_frame_buffer_create(), video_frame_commit(), video_frame_get_latest(), websocket_client_close(), websocket_client_connect(), websocket_client_create(), websocket_client_shutdown(), websocket_client_signal_lost(), websocket_server_destroy(), and websocket_server_init().
atomic_store_bool_impl()
void atomic_store_bool_impl (atomic_t * a, uint64_t value)
Definition at line 30 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(uint64_t) *)&a->impl, value);
}
atomic_store_int()
void atomic_store_int (atomic_t * a, int value)
Definition at line 175 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(uint64_t) *)&a->impl, (uint64_t)(int32_t)value);
    atomic_on_store(a);
}
References atomic_on_store().
Referenced by log_destroy(), log_disable_file_output(), log_init(), log_search_enter_mode(), log_search_exit_mode(), log_search_init(), log_set_json_output(), and mutex_stack_cleanup().
atomic_store_int_impl()
void atomic_store_int_impl (atomic_t * a, uint64_t value)
Definition at line 49 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(uint64_t) *)&a->impl, value);
}
atomic_store_u64()
void atomic_store_u64 (atomic_t * a, uint64_t value)
Definition at line 211 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(uint64_t) *)&a->impl, value);
    atomic_on_store(a);
}
References atomic_on_store().
Referenced by add_client(), add_webrtc_client(), asciichat_pcre2_cleanup_all(), asciichat_pcre2_singleton_compile(), asciichat_pcre2_singleton_get_code(), audio_ring_buffer_clear(), audio_ring_buffer_read(), audio_ring_buffer_write(), buffer_pool_alloc(), buffer_pool_create(), buffer_pool_free(), client_send_thread_func(), cond_on_broadcast(), get_utf8_palette_cache(), lifecycle_destroy_commit(), lifecycle_init_abort(), lifecycle_init_commit(), log_init(), log_lock_terminal(), log_mmap_init(), log_mmap_rotate(), log_set_flush_delay(), log_set_force_stderr(), log_set_format(), log_set_level(), log_set_terminal_output(), log_shutdown_end(), log_truncate_if_large(), log_unlock_terminal(), node_pool_create(), packet_queue_create_with_pools(), packet_queue_stop(), ringbuffer_clear(), ringbuffer_read(), ringbuffer_write(), server_main(), session_display_write_audio(), session_log_buffer_append(), session_log_buffer_clear(), session_log_buffer_create(), session_pipeline_create(), simple_frame_swap_create(), simple_frame_swap_update(), splash_intro_done(), symbol_cache_init(), video_frame_buffer_create(), and websocket_callback_timing_reset().
atomic_store_u64_impl()
void atomic_store_u64_impl (atomic_t * a, uint64_t value)
Definition at line 73 of file atomic.c.
{
    if (!a) return;
    atomic_store((_Atomic(uint64_t) *)&a->impl, value);
}
debug_atomic_is_initialized()
bool debug_atomic_is_initialized (void) extern
Definition at line 36 of file debug/atomic.c.
{
    return g_atomic_debug_initialized;
}
Referenced by atomic_on_cas(), atomic_on_fetch(), atomic_on_load(), atomic_on_store(), atomic_ptr_on_cas(), atomic_ptr_on_exchange(), atomic_ptr_on_load(), and atomic_ptr_on_store().