ascii-chat: ascii_query::json::JsonArray Class Reference
ascii_query::json::JsonArray Class Reference
JSON array builder.
#include <src/tooling/query/json.h>
Public Member Functions
JsonArray ()=default
JsonArray & add (const JsonValue &value)
JsonArray & add (const JsonArray &arr)
JsonArray & add (const JsonObject &obj)
std::string toString () const
bool empty () const
size_t size () const
Detailed Description
JSON array builder.
Definition at line 146 of file json.h.
Constructor & Destructor Documentation
JsonArray()
ascii_query::json::JsonArray::JsonArray () default
Referenced by add(), add(), and add().
Member Function Documentation
add() [1/3]
JsonArray & ascii_query::json::JsonArray::add (const JsonArray & arr) inline
Definition at line 155 of file json.h.
{
    values_.push_back(JsonValue::fromArray(arr.toString()));
    return *this;
  }
References ascii_query::json::JsonValue::fromArray(), JsonArray(), and toString().
add() [2/3]
JsonArray & ascii_query::json::JsonArray::add (const JsonObject & obj) inline
Definition at line 235 of file json.h.
{
  values_.push_back(JsonValue::fromObject(obj.toString()));
  return *this;
}
References ascii_query::json::JsonValue::fromObject(), JsonArray(), and ascii_query::json::JsonObject::toString().
add() [3/3]
JsonArray & ascii_query::json::JsonArray::add (const JsonValue & value) inline
Definition at line 150 of file json.h.
{
    values_.push_back(value);
    return *this;
  }
References JsonArray().
empty()
bool ascii_query::json::JsonArray::empty () const inline nodiscard
Definition at line 175 of file json.h.
{
    return values_.empty();
  }
size()
size_t ascii_query::json::JsonArray::size () const inline nodiscard
Definition at line 178 of file json.h.
{
    return values_.size();
  }
toString()
std::string ascii_query::json::JsonArray::toString () const inline nodiscard
Definition at line 162 of file json.h.
{
    std::string result = "[";
    bool first = true;
    for (const auto &v : values_) {
      if (!first)
        result += ",";
      first = false;
      result += v.toString();
    }
    result += "]";
    return result;
  }
Referenced by add(), and ascii_query::json::JsonObject::set().
The documentation for this class was generated from the following file:
json.h