ascii-chat: ascii_query::json::JsonObject Class Reference
ascii_query::json::JsonObject Class Reference
JSON object builder.
#include <src/tooling/query/json.h>
Public Member Functions
JsonObject ()=default
JsonObject & set (const std::string &key, const JsonValue &value)
JsonObject & set (const std::string &key, const JsonArray &arr)
JsonObject & set (const std::string &key, const JsonObject &obj)
std::string toString () const
bool empty () const
size_t size () const
Detailed Description
JSON object builder.
Definition at line 189 of file json.h.
Constructor & Destructor Documentation
JsonObject()
ascii_query::json::JsonObject::JsonObject () default
Referenced by set(), set(), and set().
Member Function Documentation
empty()
bool ascii_query::json::JsonObject::empty () const inline nodiscard
Definition at line 222 of file json.h.
{
    return keys_.empty();
  }
set() [1/3]
JsonObject & ascii_query::json::JsonObject::set (const std::string & key, const JsonArray & arr) inline
Definition at line 199 of file json.h.
{
    keys_.push_back(key);
    values_.push_back(JsonValue::fromArray(arr.toString()));
    return *this;
  }
References ascii_query::json::JsonValue::fromArray(), JsonObject(), and ascii_query::json::JsonArray::toString().
set() [2/3]
JsonObject & ascii_query::json::JsonObject::set (const std::string & key, const JsonObject & obj) inline
Definition at line 205 of file json.h.
{
    keys_.push_back(key);
    values_.push_back(JsonValue::fromObject(obj.toString()));
    return *this;
  }
References ascii_query::json::JsonValue::fromObject(), JsonObject(), and toString().
set() [3/3]
JsonObject & ascii_query::json::JsonObject::set (const std::string & key, const JsonValue & value) inline
Definition at line 193 of file json.h.
{
    keys_.push_back(key);
    values_.push_back(value);
    return *this;
  }
References JsonObject().
size()
size_t ascii_query::json::JsonObject::size () const inline nodiscard
Definition at line 225 of file json.h.
{
    return keys_.size();
  }
toString()
std::string ascii_query::json::JsonObject::toString () const inline nodiscard
Definition at line 211 of file json.h.
{
    std::string result = "{";
    for (size_t i = 0; i < keys_.size(); i++) {
      if (i > 0)
        result += ",";
      result += "\"" + escape(keys_[i]) + "\":" + values_[i].toString();
    }
    result += "}";
    return result;
  }
References ascii_query::json::escape().
Referenced by ascii_query::json::JsonArray::add(), and set().
The documentation for this class was generated from the following file:
json.h