ascii-chat: ascii_query::HttpServer Class Reference
ascii_query::HttpServer Class Reference
Simple single-threaded HTTP server.
#include <src/tooling/query/http_server.h>
Public Member Functions
HttpServer ()
~HttpServer ()
HttpServer (const HttpServer &)=delete
HttpServer & operator= (const HttpServer &)=delete
void addRoute (const std::string &method, const std::string &path, RouteHandler handler)
Add a route handler.
void setDefaultHandler (RouteHandler handler)
Set a default handler for unmatched routes.
bool start (uint16_t port)
Start the server.
void stop ()
Stop the server.
bool isRunning () const
Check if server is running.
uint16_t port () const
Get the port the server is listening on.
const std::string & lastError () const
Get the last error message.
bool processOneRequest ()
Process one request (blocking).
Detailed Description
Simple single-threaded HTTP server.
Definition at line 162 of file http_server.h.
Constructor & Destructor Documentation
HttpServer() [1/2]
ascii_query::HttpServer::HttpServer ()
Definition at line 111 of file http_server.cpp.
                       {
#if defined(_WIN32)
    // Initialize Winsock
    WSADATA wsa_data;
    WSAStartup(MAKEWORD(2, 2), &wsa_data);
#endif
    // Default 404 handler
    default_handler_ = [](const HttpRequest &) { return HttpResponse::notFound(); };
}
References ascii_query::HttpResponse::notFound().
Referenced by HttpServer(), and operator=().
~HttpServer()
ascii_query::HttpServer::~HttpServer ()
Definition at line 122 of file http_server.cpp.
{
    stop();
#if defined(_WIN32)
    WSACleanup();
#endif
}
References stop().
HttpServer() [2/2]
ascii_query::HttpServer::HttpServer (const HttpServer &) delete
References HttpServer().
Member Function Documentation
addRoute()
void ascii_query::HttpServer::addRoute (const std::string & method, const std::string & path, RouteHandler handler)
Add a route handler.
Parameters
method HTTP method (GET, POST, etc.)
path URL path (exact match)
handler Handler function
Definition at line 130 of file http_server.cpp.
{
    routes_.push_back({method, path, std::move(handler)});
}
isRunning()
bool ascii_query::HttpServer::isRunning () const inline nodiscard
Check if server is running.
Definition at line 200 of file http_server.h.
{
    return running_;
  }
lastError()
const std::string & ascii_query::HttpServer::lastError () const inline nodiscard
Get the last error message.
Definition at line 214 of file http_server.h.
{
    return last_error_;
  }
Referenced by main().
operator=()
HttpServer & ascii_query::HttpServer::operator= (const HttpServer &) delete
References HttpServer(), and port().
port()
uint16_t ascii_query::HttpServer::port () const inline nodiscard
Get the port the server is listening on.
Definition at line 207 of file http_server.h.
{
    return port_;
  }
Referenced by operator=(), and start().
processOneRequest()
bool ascii_query::HttpServer::processOneRequest ()
Process one request (blocking).
Used for testing or manual control. Normally you'd call start() instead.
Returns
true if a request was processed, false on error
Definition at line 230 of file http_server.cpp.
{
    if (server_socket_ < 0) {
        return false;
    }
    struct sockaddr_in client_addr {};
    socklen_t client_len = sizeof(client_addr);
    socket_t client_socket = accept(server_socket_, reinterpret_cast<struct sockaddr *>(&client_addr), &client_len);
    if (client_socket == INVALID_SOCKET_VAL) {
        return false;
    }
    handleClient(static_cast<int>(client_socket));
    return true;
}
References INVALID_SOCKET_VAL.
setDefaultHandler()
void ascii_query::HttpServer::setDefaultHandler (RouteHandler handler)
Set a default handler for unmatched routes.
Parameters
handler Handler function
Definition at line 134 of file http_server.cpp.
{ default_handler_ = std::move(handler); }
start()
bool ascii_query::HttpServer::start (uint16_t port)
Start the server.
Parameters
port Port to listen on
Returns
true if server started successfully
Definition at line 136 of file http_server.cpp.
{
    if (running_) {
        last_error_ = "Server already running";
        return false;
    }
    // Create socket
    server_socket_ = static_cast<int>(socket(AF_INET, SOCK_STREAM, 0));
    if (server_socket_ == INVALID_SOCKET_VAL) {
        last_error_ = "Failed to create socket";
        return false;
    }
    // Set SO_REUSEADDR
    int opt = 1;
#if defined(_WIN32)
    setsockopt(server_socket_, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<const char *>(&opt), sizeof(opt));
#else
    setsockopt(server_socket_, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
#endif
    // Bind
    struct sockaddr_in addr {};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); // localhost only for security
    addr.sin_port = htons(port);
    if (bind(server_socket_, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr)) < 0) {
        last_error_ = "Failed to bind to port " + std::to_string(port);
        close_socket(server_socket_);
        server_socket_ = -1;
        return false;
    }
    // Listen
    if (listen(server_socket_, 10) < 0) {
        last_error_ = "Failed to listen on socket";
        close_socket(server_socket_);
        server_socket_ = -1;
        return false;
    }
    port_ = port;
    running_ = true;
    // Start server thread
    server_thread_ = std::thread(&HttpServer::serverLoop, this);
    return true;
}
References close_socket, INVALID_SOCKET_VAL, and port().
Referenced by main().
stop()
void ascii_query::HttpServer::stop ()
Stop the server.
Definition at line 187 of file http_server.cpp.
                      {
    if (!running_) {
        return;
    }
    running_ = false;
    // Close server socket to unblock accept()
    if (server_socket_ >= 0) {
#if defined(_WIN32)
        shutdown(server_socket_, SD_BOTH);
#else
        shutdown(server_socket_, SHUT_RDWR);
#endif
        close_socket(server_socket_);
        server_socket_ = -1;
    }
    // Wait for server thread
    if (server_thread_.joinable()) {
        server_thread_.join();
    }
}
References close_socket.
Referenced by main(), and ~HttpServer().
The documentation for this class was generated from the following files:
http_server.h
http_server.cpp