ascii-chat: ascii_query::json::JsonValue Class Reference
ascii_query::json::JsonValue Class Reference
JSON value wrapper (can hold any JSON type).
#include <src/tooling/query/json.h>
Public Types
enum class Type {
Null , Bool , Int , UInt ,
Double , String , Array , Object
}
Public Member Functions
JsonValue ()
JsonValue (std::nullptr_t)
JsonValue (bool b)
JsonValue (int i)
JsonValue (int64_t i)
JsonValue (uint64_t u)
JsonValue (double d)
JsonValue (const char *s)
JsonValue (const std::string &s)
JsonValue (std::string &&s)
std::string toString () const
Static Public Member Functions
static JsonValue fromArray (const std::string &serialized)
static JsonValue fromObject (const std::string &serialized)
Detailed Description
JSON value wrapper (can hold any JSON type).
Definition at line 80 of file json.h.
Member Enumeration Documentation
Type
enum class ascii_query::json::JsonValue::Type strong
Enumerator
Null
Bool
Int
UInt
Double
String
Array
Object
Definition at line 82 of file json.h.
{ Null, Bool, Int, UInt, Double, String, Array, Object };
Constructor & Destructor Documentation
JsonValue() [1/10]
ascii_query::json::JsonValue::JsonValue () inline
Definition at line 84 of file json.h.
: type_(Type::Null) {}
Referenced by fromArray(), and fromObject().
JsonValue() [2/10]
ascii_query::json::JsonValue::JsonValue (std::nullptr_t) inline
Definition at line 85 of file json.h.
: type_(Type::Null) {}
JsonValue() [3/10]
ascii_query::json::JsonValue::JsonValue (bool b) inline
Definition at line 86 of file json.h.
: type_(Type::Bool), bool_val_(b) {}
JsonValue() [4/10]
ascii_query::json::JsonValue::JsonValue (int i) inline
Definition at line 87 of file json.h.
: type_(Type::Int), int_val_(i) {}
JsonValue() [5/10]
ascii_query::json::JsonValue::JsonValue (int64_t i) inline
Definition at line 88 of file json.h.
: type_(Type::Int), int_val_(i) {}
JsonValue() [6/10]
ascii_query::json::JsonValue::JsonValue (uint64_t u) inline
Definition at line 89 of file json.h.
: type_(Type::UInt), uint_val_(u) {}
JsonValue() [7/10]
ascii_query::json::JsonValue::JsonValue (double d) inline
Definition at line 90 of file json.h.
: type_(Type::Double), double_val_(d) {}
JsonValue() [8/10]
ascii_query::json::JsonValue::JsonValue (const char * s) inline
Definition at line 91 of file json.h.
: type_(Type::String), str_val_(s) {}
JsonValue() [9/10]
ascii_query::json::JsonValue::JsonValue (const std::string & s) inline
Definition at line 92 of file json.h.
: type_(Type::String), str_val_(s) {}
JsonValue() [10/10]
ascii_query::json::JsonValue::JsonValue (std::string && s) inline
Definition at line 93 of file json.h.
: type_(Type::String), str_val_(std::move(s)) {}
Member Function Documentation
fromArray()
JsonValue ascii_query::json::JsonValue::fromArray (const std::string & serialized) inline static
Definition at line 96 of file json.h.
{
    JsonValue v;
    v.type_ = Type::Array;
    v.str_val_ = serialized;
    return v;
  }
References Array, and JsonValue().
Referenced by ascii_query::json::JsonArray::add(), and ascii_query::json::JsonObject::set().
fromObject()
JsonValue ascii_query::json::JsonValue::fromObject (const std::string & serialized) inline static
Definition at line 103 of file json.h.
{
    JsonValue v;
    v.type_ = Type::Object;
    v.str_val_ = serialized;
    return v;
  }
References JsonValue(), and Object.
Referenced by ascii_query::json::JsonArray::add(), and ascii_query::json::JsonObject::set().
toString()
std::string ascii_query::json::JsonValue::toString () const inline nodiscard
Definition at line 110 of file json.h.
{
    switch (type_) {
    case Type::Null:
      return "null";
    case Type::Bool:
      return bool_val_ ? "true" : "false";
    case Type::Int:
      return std::to_string(int_val_);
    case Type::UInt:
      return std::to_string(uint_val_);
    case Type::Double: {
      std::ostringstream oss;
      oss << double_val_;
      return oss.str();
    }
    case Type::String:
      return "\"" + escape(str_val_) + "\"";
    case Type::Array:
    case Type::Object:
      return str_val_; // Already serialized
    }
    return "null";
  }
References Array, Bool, Double, ascii_query::json::escape(), Int, Null, Object, String, and UInt.
The documentation for this class was generated from the following file:
json.h