ascii-chat: display.h File Reference
display.h File Reference
ascii-chat Client Display Management Interface
Typedefs
typedef struct session_display_ctx session_display_ctx_t
Opaque session display context handle.
Functions
void display_set_context (session_display_ctx_t *display_ctx)
Set the display context (framework integration).
int display_init ()
Initialize display subsystem.
bool display_has_tty ()
Check if display has TTY capability.
void display_full_reset ()
Perform full display reset.
void display_reset_for_new_connection ()
Reset display state for new connection.
void display_disable_logging_for_first_frame ()
Disable terminal logging for first frame.
void display_render_frame (const char *frame_data)
Render ASCII frame to display.
void display_cleanup ()
Cleanup display subsystem.
Variables
tty_info_t g_tty_info
Detailed Description
ascii-chat Client Display Management Interface
Defines the display subsystem interface for terminal rendering, TTY management, frame output operations, and terminal capability detection.
The display subsystem handles all interactions with the terminal:
Terminal capability detection (color depth, Unicode, half-blocks)
TTY control (raw mode, terminal reset)
ASCII frame rendering to stdout
Terminal logging suppression during rendering
Clean terminal restoration on shutdown
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
2025
See also
topic_client_display "Terminal Display Architecture"
Definition in file client/display.h.
Function Documentation
display_cleanup()
void display_cleanup ()
Cleanup display subsystem.
Restores terminal to original state and releases display resources. Must be called before process exit to ensure terminal is left in a usable state.
The cleanup process:
Re-enables terminal echo (if it was disabled)
Re-enables canonical mode (line buffering)
Moves cursor to clean location (below last frame)
Restores original terminal color (if color was used)
Restores original terminal settings
Releases terminal state structures
Critical: Must be called even if display_init() failed - partial init may need cleanup.
See also
display_init "Initialize display subsystem"
Destroys session display context and releases all resources including keyboard input handling.
Definition at line 363 of file src/client/display.c.
                       {
  // Cleanup keyboard input if it was initialized
  if (g_keyboard_enabled) {
    keyboard_destroy();
    g_keyboard_enabled = false;
  }
  // Cleanup optional local media capture context if it was created
  if (g_display_capture_ctx) {
    session_capture_destroy(g_display_capture_ctx);
    g_display_capture_ctx = NULL;
  }
  // Display context is now managed by session_client_like framework
  // Do not destroy it here - the framework will handle cleanup
  g_display_ctx = NULL;
}
References session_capture_destroy().
display_disable_logging_for_first_frame()
void display_disable_logging_for_first_frame ()
Disable terminal logging for first frame.
Temporarily disables terminal logging output to prevent debug/info messages from corrupting the first rendered ASCII frame.
Call sequence:
display_disable_logging_for_first_frame() - before rendering frame
display_render_frame() - renders frame with logging disabled
Logging re-enabled automatically after first frame
Why: The first frame render clears the terminal and draws the ASCII grid. If logging is active, log messages would overwrite or corrupt the grid.
See also
display_render_frame "Render ASCII frame"
Disables terminal logging before clearing the display for the first frame to prevent log output from interfering with ASCII display.
Definition at line 290 of file src/client/display.c.
{
  // Atomically check if this is the first frame and mark as not-first
  // Avoids TOCTOU race where multiple threads could both think they're first
  bool was_first_frame = atomic_exchange_bool(&g_is_first_frame_of_connection, false);
  if (was_first_frame) {
    // Disable terminal logging before clearing display and rendering first frame
    log_set_terminal_output(false);
    // Signal the intro splash screen to stop - first frame is ready to render
    splash_intro_done();
  }
}
References atomic_exchange_bool(), log_set_terminal_output(), and splash_intro_done().
Referenced by display_render_frame().
display_full_reset()
void display_full_reset ()
Perform full display reset.
Clears the terminal and resets display state. Called by server clear commands or on SIGWINCH terminal resize events.
The reset:
Clears the terminal screen
Resets cursor to home position
Resets text attributes (color, bold, etc.)
Resets first-frame tracking (re-suppresses logging on next frame)
See also
display_reset_for_new_connection "Reset for new connection"
Executes complete terminal reset sequence for clean display state. Safe to call multiple times and handles mode-specific behavior.
Definition at line 264 of file src/client/display.c.
{
  if (g_display_ctx && !should_exit()) {
    session_display_reset(g_display_ctx);
  }
}
References session_display_reset(), and should_exit().
Referenced by server_connection_lost().
display_has_tty()
bool display_has_tty ()
Check if display has TTY capability.
Checks if stdout is connected to a terminal (TTY) or redirected to a file/pipe. The client requires TTY for interactive rendering unless in snapshot or test mode.
Returns
true if TTY available (interactive terminal), false if piped/redirected
Note
Test pattern and snapshot modes can proceed without TTY, but real webcam streaming requires a terminal for rendering.
Returns
true if TTY is available for interactive output, false otherwise
Definition at line 252 of file src/client/display.c.
                       {
  return session_display_has_tty(g_display_ctx);
}
References session_display_has_tty().
display_init()
int display_init ()
Initialize display subsystem.
Sets up terminal for ASCII rendering and detects terminal capabilities.
Initialization steps:
Checks if stdout is a TTY (error if not, unless snapshot mode or test pattern)
Detects terminal color depth (24-bit true color, 256-color, 16-color, or ANSI)
Detects Unicode/UTF-8 support
Detects half-block character support (for 2x vertical resolution)
Sets raw terminal mode (disables echo, canonical mode)
Saves original terminal settings for restoration
Options affecting initialization:
--color: Force enable/disable color
--palette: Select ASCII rendering palette
--width, --height: Terminal dimensions (auto-detected if not set)
--half-block: Enable 2x vertical resolution using half-block chars
Returns
0 on success, negative on error:
ERROR_TERMINAL: TTY error or terminal control failed
ERROR_DISPLAY: Terminal dimensions invalid
Note
Called during client initialization before connection attempts. Must be paired with display_cleanup() for proper terminal restoration.
See also
display_cleanup "Cleanup display and restore terminal"
Initialize display subsystem.
Creates session display context for TTY management and frame rendering. Must be called once during client startup.
Returns
0 on success, negative on error
Definition at line 180 of file src/client/display.c.
                   {
  // Build display configuration from options
  session_display_config_t config = {
      .snapshot_mode = GET_OPTION(snapshot_mode),
      .palette_type = GET_OPTION(palette_type),
      .custom_palette = GET_OPTION(palette_custom_set) ? GET_OPTION(palette_custom) : NULL,
      .color_mode = TERM_COLOR_AUTO // Will be overridden by command-line options
  };
  // Create display context using session library
  g_display_ctx = session_display_create(&config);
  if (!g_display_ctx) {
    SET_ERRNO(ERROR_DISPLAY, "Failed to initialize display");
    return -1;
  }
  // Check if client mode should load local media (--file or --url)
  const char *media_url = GET_OPTION(media_url);
  const char *media_file = GET_OPTION(media_file);
  if ((media_url && strlen(media_url) > 0) || (media_file && strlen(media_file) > 0)) {
    // Client mode with local media file/URL - create capture context for keyboard controls
    session_capture_config_t capture_config = {0};
    capture_config.target_fps = 60;
    capture_config.resize_for_network = false;
    capture_config.should_exit_callback = NULL;
    capture_config.callback_data = NULL;
    if (media_url && strlen(media_url) > 0) {
      capture_config.type = MEDIA_SOURCE_FILE;
      capture_config.path = media_url;
    } else {
      if (strcmp(media_file, "-") == 0) {
        capture_config.type = MEDIA_SOURCE_STDIN;
        capture_config.path = NULL;
      } else {
        capture_config.type = MEDIA_SOURCE_FILE;
        capture_config.path = media_file;
      }
    }
    capture_config.loop = GET_OPTION(media_loop);
    capture_config.initial_seek_timestamp = GET_OPTION(media_seek_timestamp);
    g_display_capture_ctx = session_capture_create(&capture_config);
    if (!g_display_capture_ctx) {
      log_warn("Failed to create capture context for local media - keyboard seek/pause disabled");
      g_display_capture_ctx = NULL;
    }
  }
  // Keyboard is pre-initialized from asciichat_shared_init()
  // Only enable keyboard input if stdin is a TTY (avoid interfering with piped/redirected I/O)
  g_keyboard_enabled = terminal_is_stdin_tty();
  // Register display atomics with named debug registry
  static bool display_atomics_registered = false;
  if (!display_atomics_registered) {
    NAMED_REGISTER_ATOMIC(&g_is_first_frame_of_connection, "first_frame_of_display_connection", NULL);
    display_atomics_registered = true;
  }
  return 0;
}
References session_capture_config_t::callback_data, session_capture_config_t::initial_seek_timestamp, session_capture_config_t::loop, session_capture_config_t::path, session_capture_config_t::resize_for_network, session_capture_create(), session_display_create(), session_capture_config_t::should_exit_callback, session_capture_config_t::target_fps, terminal_is_stdin_tty(), and session_capture_config_t::type.
display_render_frame()
void display_render_frame (const char * frame_data)
Render ASCII frame to display.
Outputs the ASCII frame data to the terminal. This is called by the protocol thread when receiving PACKET_TYPE_ASCII_FRAME from the server.
The function:
Verifies TTY is still available
If first frame: disables logging, clears terminal
Outputs frame data to stdout
Flushes output to ensure visible immediately
Re-enables logging after first frame
In snapshot mode, exits immediately after rendering.
Parameters
frame_data ASCII frame data to render (null-terminated string or binary data)
Note
Called by protocol thread - must be thread-safe with respect to terminal state (stdout writes are atomic for single call).
See also
display_init "Initialize display subsystem"
Render ASCII frame to display
Uses session display library for frame output routing based on display mode and snapshot requirements. Also polls for keyboard input for interactive controls (volume, color mode, flip).
Parameters
frame_data ASCII frame data to render
is_snapshot_frame Whether this is the final snapshot frame
Definition at line 316 of file src/client/display.c.
{
  if (!frame_data) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Attempted to render NULL frame data");
    return;
  }
  // Stop splash screen animation on first frame
  // This must be called BEFORE any frame rendering to prevent splash/frame flickering
  display_disable_logging_for_first_frame();
  // Render help screen if active (suppresses frame rendering)
  if (keyboard_help_is_active(g_display_ctx)) {
    keyboard_help_render(g_display_ctx);
    // Still poll keyboard for interactive controls while help is visible
    if (g_keyboard_enabled) {
      keyboard_key_t key = keyboard_read_nonblocking();
      if (key != KEY_NONE) {
        session_handle_keyboard_input(g_display_capture_ctx, g_display_ctx, key);
      }
    }
    return; // Skip normal frame rendering
  }
  // Use session display library for frame rendering
  session_display_render_frame(g_display_ctx, frame_data);
  // Poll for keyboard input and handle interactive controls
  // - If client mode has local media (--file/--url), pass capture context for full controls
  //   (seek, pause, play, volume, color mode, flip)
  // - If client mode is network-only, pass NULL (volume, color mode, flip work; seek/pause ignored)
  if (g_keyboard_enabled) {
    keyboard_key_t key = keyboard_read_nonblocking();
    if (key != KEY_NONE) {
      session_handle_keyboard_input(g_display_capture_ctx, g_display_ctx, key);
    }
  }
}
References display_disable_logging_for_first_frame(), keyboard_help_is_active(), keyboard_help_render(), session_display_render_frame(), and session_handle_keyboard_input().
display_reset_for_new_connection()
void display_reset_for_new_connection ()
Reset display state for new connection.
Call this when starting a new connection after reconnection to reset first-frame tracking and clear any residual state from the previous connection.
The reset:
Clears the terminal screen (like display_full_reset)
Resets first-frame flag to suppress logging on first frame of new connection
Prepares for fresh frame rendering
See also
display_reset_for_new_connection "Reset for new connection"
Resets the first frame tracking flag to prepare for a new connection. Call this when starting a new connection to reset first frame tracking.
Definition at line 278 of file src/client/display.c.
{
  atomic_store_bool(&g_is_first_frame_of_connection, true);
}
References atomic_store_bool().
Referenced by protocol_start_connection().
display_set_context()
void display_set_context (session_display_ctx_t * display_ctx)
Set the display context (framework integration).
Called by client_run() to pass the display context created by session_client_like_run() to the display module so protocol threads can render frames.
Parameters
display_ctx Display context from framework (may be NULL)
Set the display context (framework integration).
Client mode doesn't create its own display context anymore. Instead, session_client_like_run() creates it and passes it to client_run(). This setter allows client_run() to make the framework-created context available to protocol threads that need to render frames.
Parameters
display_ctx Display context created by framework (may be NULL)
Definition at line 162 of file src/client/display.c.
{
  g_display_ctx = display_ctx;
}
Variable Documentation
g_tty_info
tty_info_t g_tty_info extern