ascii-chat: protocol.h File Reference
protocol.h File Reference
ascii-chat Client Protocol Handler Interface
Functions
int protocol_start_connection ()
Start protocol connection handling.
void protocol_stop_connection ()
Stop protocol connection handling.
bool protocol_connection_lost ()
Check if connection has been lost.
const acip_client_callbacks_t * protocol_get_acip_callbacks ()
Get ACIP client callbacks for packet dispatch.
Detailed Description
ascii-chat Client Protocol Handler Interface
Defines the protocol handling interface for client-side packet processing and data reception thread management.
The protocol handler manages the data reception thread, which continuously receives packets from the server, decrypts them, and dispatches them to appropriate handlers based on packet type. It also detects connection loss and signals the main thread to initiate reconnection.
Command Types Handled
The client processes these command/packet types from the server:
PACKET_TYPE_ASCII_FRAME: Terminal display frame (rendered to stdout)
PACKET_TYPE_AUDIO_BATCH: Opus-encoded audio samples (sent to audio playback)
PACKET_TYPE_PONG: Keepalive response (recorded for timeout detection)
PACKET_TYPE_CLEAR_CONSOLE: Terminal clear command (resets display)
PACKET_TYPE_SERVER_STATE: Server state updates (logged for debugging)
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
2025
See also
topic_client_protocol "Protocol Architecture"
Definition in file client/protocol.h.
Function Documentation
protocol_connection_lost()
bool protocol_connection_lost ()
Check if connection has been lost.
Atomically checks whether the data reception thread has detected connection loss. Connection loss is detected by:
Socket read error (recv() returns error)
Socket closed by server (recv() returns 0)
Decryption failure (corrupted stream)
Invalid packet magic number (out of sync)
Once loss is detected, this flag remains true until the next successful connection.
Returns
true if connection lost (detected by protocol thread), false otherwise
Note
This is checked by the main thread to trigger reconnection logic. The flag is set atomically by the protocol thread and checked atomically by main.
See also
server_connection_lost "Signal connection loss (called by protocol thread)"
Check if connection has been lost
Returns
true if protocol detected connection loss, false otherwise
Definition at line 1358 of file client/protocol.c.
{
  return atomic_load_bool(&g_data_thread_exited) || server_connection_is_lost();
}
References atomic_load_bool(), and server_connection_is_lost().
protocol_get_acip_callbacks()
const acip_client_callbacks_t * protocol_get_acip_callbacks ()
Get ACIP client callbacks for packet dispatch.
Returns the packet dispatch callbacks structure used to route received packets to appropriate handlers. This is primarily used for ACDS signaling packet dispatch and WebRTC peer negotiation.
The callbacks structure includes handlers for:
ASCII frame rendering
Audio batch processing
Server state updates
Connection control commands (clear, reset, etc.)
Returns
Pointer to client callbacks structure (never NULL)
Used by WebRTC sessions to receive and dispatch ACDS signaling packets.
Returns pointer to the global callback structure for use by WebRTC sessions that need to receive ACDS signaling packets.
Returns
Pointer to client callbacks (never NULL)
Definition at line 957 of file client/protocol.c.
{
  return &g_acip_client_callbacks;
}
protocol_start_connection()
int protocol_start_connection ()
Start protocol connection handling.
Spawns the data reception thread in the global client worker thread pool. The thread begins receiving and processing packets from the server. Must be called after the server connection is established and the cryptographic handshake is complete.
The thread will:
Continuously receive packets from the server socket
Decrypt packets using the negotiated session key
Dispatch packets to appropriate handlers based on type
Detect connection loss and signal the main thread
Returns
0 on success, negative on error (thread pool full or other resources exhausted)
Note
Must be paired with protocol_stop_connection() to properly shut down the thread before reconnection or exit.
See also
protocol_stop_connection "Stop data reception thread"
protocol_connection_lost "Check if connection was lost"
Start protocol connection handling
Initializes protocol state and starts the data reception thread. Must be called after successful server connection establishment.
Returns
0 on success, negative on error
Definition at line 1155 of file client/protocol.c.
{
  log_warn("[FRAME_RECV_INIT] 🟢 PROTOCOL_START: Starting client protocol initialization");
  // Register protocol atomics with named debug registry
  static bool protocol_atomics_registered = false;
  if (!protocol_atomics_registered) {
    NAMED_REGISTER_ATOMIC(&g_data_thread_exited, "protocol_data_reception_thread_exit_confirmation", NULL);
    NAMED_REGISTER_ATOMIC(&g_frames_rendered, "protocol_frames_successfully_rendered", NULL);
    protocol_atomics_registered = true;
  }
  // Reset protocol state for new connection
  g_server_state_initialized = false;
  g_last_active_count = 0;
  g_should_clear_before_next_frame = false;
  log_info("[FRAME_RECV_INIT] ✅ STATE_RESET: server_initialized=false, active_count=0, clear_flag=false");
  // Reset display state for new connection
  display_reset_for_new_connection();
  // Send CLIENT_CAPABILITIES packet FIRST before starting any threads
  // Server expects this as the first packet after crypto handshake
  log_debug("[FRAME_RECV_INIT] 📤 SENDING_CAPABILITIES: terminal_size negotiation");
  asciichat_error_t cap_result = threaded_send_terminal_size_with_auto_detect((int)terminal_get_effective_width(),
                                                                              (int)terminal_get_effective_height());
  if (cap_result != ASCIICHAT_OK) {
    log_error("[FRAME_RECV_INIT] ❌ CAPABILITIES_FAILED: cannot send terminal size");
    return -1;
  }
  log_debug("[FRAME_RECV_INIT] ✅ CAPABILITIES_SENT: terminal_size sent successfully");
  // Send STREAM_START packet with combined stream types BEFORE starting worker threads
  // This tells the server what streams to expect before any data arrives
  uint32_t stream_types = STREAM_TYPE_VIDEO; // Always have video
  if (GET_OPTION(audio_enabled)) {
    stream_types |= STREAM_TYPE_AUDIO; // Add audio if enabled
  }
  log_info("[FRAME_RECV_INIT] 📤 SENDING_STREAM_START: types=0x%x (video%s)", stream_types,
           (stream_types & STREAM_TYPE_AUDIO) ? "+audio" : "");
  asciichat_error_t stream_result = threaded_send_stream_start_packet(stream_types);
  if (stream_result != ASCIICHAT_OK) {
    log_error("[FRAME_RECV_INIT] ❌ STREAM_START_FAILED: cannot send stream types");
    return -1;
  }
  log_info("[FRAME_RECV_INIT] ✅ STREAM_START_SENT: stream_types=0x%x, server will send frames", stream_types);
  // Start data reception thread
  log_warn("[FRAME_RECV_INIT] 🔄 STARTING_DATA_THREAD: callbacks registered, about to spawn thread");
  atomic_store_bool(&g_data_thread_exited, false);
  if (thread_pool_spawn(g_client_worker_pool, data_reception_thread_func, NULL, 1, "data_reception") != ASCIICHAT_OK) {
    log_error("[FRAME_RECV_INIT] ❌ DATA_THREAD_SPAWN_FAILED: cannot start frame receive thread");
    LOG_ERRNO_IF_SET("Data reception thread creation failed");
    return -1;
  }
  log_warn("[FRAME_RECV_INIT] ✅ DATA_THREAD_SPAWNED: frame receive thread is now running, waiting for frames...");
  // Start webcam capture thread
  log_debug("Starting webcam capture thread...");
  if (capture_start_thread() != 0) {
    log_error("Failed to start webcam capture thread");
    return -1;
  }
  log_debug("Webcam capture thread started successfully");
  // Initialize audio sender thread BEFORE starting audio capture
  // This ensures sender is ready when capture thread starts queueing packets
  // Must happen after connection succeeds to prevent deadlock if connection fails
  audio_sender_init();
  // Start audio capture thread if audio is enabled
  log_debug("Starting audio capture thread...");
  if (audio_start_thread() != 0) {
    log_error("Failed to start audio capture thread");
    return -1;
  }
  log_debug("Audio capture thread started successfully (or skipped if audio disabled)");
  // Start keepalive/ping thread to prevent server timeout
  log_debug("Starting keepalive/ping thread...");
  if (keepalive_start_thread() != 0) {
    log_error("Failed to start keepalive/ping thread");
    return -1;
  }
  log_debug("Keepalive/ping thread started successfully");
  g_data_thread_created = true;
  return 0;
}
References atomic_store_bool(), audio_sender_init(), audio_start_thread(), capture_start_thread(), display_reset_for_new_connection(), g_client_worker_pool, keepalive_start_thread(), terminal_get_effective_height(), terminal_get_effective_width(), thread_pool_spawn(), threaded_send_stream_start_packet(), and threaded_send_terminal_size_with_auto_detect().
protocol_stop_connection()
void protocol_stop_connection ()
Stop protocol connection handling.
Signals the data reception thread to exit and waits for it to join. Performs proper cleanup to prevent resource leaks and race conditions during reconnection or shutdown.
The function:
Closes the server socket (interrupts blocking recv() in data thread)
Sets the global shutdown flag (signals thread to exit)
Waits for the data reception thread to join (polls for thread exit)
This must be called before reconnecting to prevent socket descriptor leaks and to ensure the thread has fully cleaned up before reuse.
Note
This function blocks until the data reception thread exits. Typical wait time: <100ms (socket closure immediately interrupts recv()).
See also
protocol_start_connection "Start data reception thread"
Stop protocol connection handling
Gracefully shuts down the data reception thread and cleans up protocol state. Safe to call multiple times.
Definition at line 1253 of file client/protocol.c.
{
  // Log final frame count before shutting down (always log for diagnostic purposes)
  int final_frame_count = atomic_load_u64(&g_frames_rendered);
  log_info("📊 CLIENT SESSION STATS: %d unique frames rendered during connection", final_frame_count);
  log_debug("[PROTOCOL_STOP] 1. Starting protocol_stop_connection");
  // In snapshot mode, data reception thread was never started, but capture thread may still be running
  // Always stop the capture thread to prevent use-after-free when transport is destroyed
  if (GET_OPTION(snapshot_mode)) {
    log_debug("[PROTOCOL_STOP] Snapshot mode: flushing H.265 encoder before stopping capture thread");
    // Flush the encoder to output any buffered frames before exiting
    if (g_h265_encoder) {
      uint8_t flush_buf[1024];
      size_t flush_size = sizeof(flush_buf);
      asciichat_error_t flush_result = h265_encoder_flush(g_h265_encoder, flush_buf, &flush_size);
      if (flush_result == ASCIICHAT_OK && flush_size > 0) {
        log_info("[PROTOCOL_STOP] Flushed H.265 encoder: got %zu bytes of buffered frames", flush_size);
        // Send the flushed frame if we got one
        acip_transport_t *transport = server_connection_get_transport();
        if (transport && server_connection_is_active()) {
          uint32_t width = 320, height = 240; // TODO: track actual dimensions
          log_debug("[PROTOCOL_STOP] Sending flushed frame: %ux%u, %zu bytes", width, height, flush_size);
        }
      }
    }
    log_debug("[PROTOCOL_STOP] Snapshot mode: stopping capture thread before returning");
    capture_stop_thread();
    return;
  }
  // Don't call signal_exit() here - that's for global shutdown only!
  // We just want to stop threads for this connection, not exit the entire client
  // Shutdown the socket FIRST to interrupt any blocking network operations in worker threads
  // This must happen BEFORE audio_stop_thread() so audio sender thread unblocks from network send
  log_debug("[PROTOCOL_STOP] 2. About to call server_connection_shutdown");
  server_connection_shutdown();
  log_debug("[PROTOCOL_STOP] 3. server_connection_shutdown() returned");
  // Signal audio sender thread to exit
  // Must happen after socket shutdown so any blocked network calls fail
  // Audio sender is created in ALL modes except snapshot mode
  log_debug("[PROTOCOL_STOP] 4. About to call audio_stop_thread");
  audio_stop_thread();
  log_debug("[PROTOCOL_STOP] 5. audio_stop_thread() returned");
  // Early return if data thread was never created (e.g., mirror mode)
  // In mirror mode, we only need to stop the audio sender (done above)
  if (!g_data_thread_created) {
    log_debug("[PROTOCOL_STOP] 6. Data thread not created, returning");
    return;
  }
  // Stop keepalive/ping thread - it checks connection status and will exit
  log_debug("[PROTOCOL_STOP] 7. About to call keepalive_stop_thread");
  keepalive_stop_thread();
  log_debug("[PROTOCOL_STOP] 8. keepalive_stop_thread() returned");
  // Stop webcam capture thread
  log_debug("[PROTOCOL_STOP] 9. About to call capture_stop_thread");
  capture_stop_thread();
  log_debug("[PROTOCOL_STOP] 10. capture_stop_thread() returned");
  // Wait for data reception thread to exit gracefully
  log_debug("[PROTOCOL_STOP] 11. Waiting for data thread to exit");
  // Thread checks should_exit() every read cycle (typically <1-5ms), so timeout can be much shorter
  int wait_count = 0;
  while (wait_count < 5 && !atomic_load_bool(&g_data_thread_exited)) {
    platform_sleep_us(10 * US_PER_MS_INT); // 10ms * 5 = 50ms max wait
    wait_count++;
  }
  if (!atomic_load_bool(&g_data_thread_exited)) {
    log_warn("Data thread not responding after 50ms - will be joined by thread pool");
  }
  log_debug("[PROTOCOL_STOP] 12. Data thread wait complete");
  // Join all threads in the client worker pool (in stop_id order)
  // This handles the data reception thread and (eventually) all other worker threads
  log_debug("[PROTOCOL_STOP] 13. About to call thread_pool_stop_all");
  if (g_client_worker_pool) {
    asciichat_error_t result = thread_pool_stop_all(g_client_worker_pool);
    if (result != ASCIICHAT_OK) {
      log_error("Failed to stop client worker threads");
      LOG_ERRNO_IF_SET("Thread pool stop failed");
    }
  }
  log_debug("[PROTOCOL_STOP] 14. thread_pool_stop_all() returned");
  g_data_thread_created = false;
#ifdef DEBUG_THREADS
  log_debug("Data reception thread stopped and joined by thread pool");
#endif
  log_debug("[PROTOCOL_STOP] 15. protocol_stop_connection complete");
}
References atomic_load_bool(), atomic_load_u64(), audio_stop_thread(), capture_stop_thread(), g_client_worker_pool, g_h265_encoder, h265_encoder_flush(), keepalive_stop_thread(), platform_sleep_us(), server_connection_get_transport(), server_connection_is_active(), server_connection_shutdown(), and thread_pool_stop_all().