ascii-chat: capture.h File Reference
capture.h File Reference
ascii-chat Client Media Capture Management Interface
Functions
int capture_init ()
Initialize capture subsystem.
int capture_start_thread ()
Start capture thread.
void capture_stop_thread ()
Stop capture thread.
bool capture_thread_exited ()
Check if capture thread has exited.
void capture_cleanup ()
Cleanup capture subsystem.
Detailed Description
ascii-chat Client Media Capture Management Interface
Defines the interface for video capture and transmission management in the ascii-chat client. Abstracts over multiple media sources (webcam, files, stdin, test patterns) and handles frame processing, resizing, and FPS sync.
The capture subsystem:
Manages platform-specific webcam access via abstraction layer
Supports multiple media sources (webcam, local files, stdin, test patterns)
Performs frame resizing and format conversion for network efficiency
Synchronizes frame transmission with configurable FPS rates
Handles periodic frame transmission to the server
Media Source Types
The capture subsystem supports four media source types via the media_source_t abstraction (see media):
WEBCAM: Hardware camera device (webcam/camera)
Platform-specific access (V4L2 on Linux, AVFoundation on macOS)
Real-time capture with variable frame rate
Selected via --webcam-index <N> (default: 0, first camera)
FILE: Local media file or network stream
Supported formats: mp4, avi, mkv, webm, mov, flv, wmv, gif
Specified via --file <path> option
Playback at configurable frame rate
Loop support via --media-loop option
STDIN: Piped or redirected media data
Specified via --file - (dash indicates stdin)
Any format supported by FFmpeg (detected automatically)
Useful for streaming pipes: ffmpeg ... | ascii-chat client --file -
Does not support seeking/rewinding
TEST: Procedural test pattern generator
Enabled via --test-pattern option
Generates animated test pattern without hardware
Useful for testing without webcam access
Always available (no hardware requirements)
Media source selection is automatic based on command-line options:
./ascii-chat client --test-pattern           # Use test pattern
./ascii-chat client --file video.mp4         # Play file
./ascii-chat client --file -                 # Read from stdin
./ascii-chat client --webcam-index 0         # Use default camera
./ascii-chat client                          # Auto-detect (webcam or test)
Frame Format and Negotiation
All media sources are normalized to a common frame format:
Color Space: RGB (24-bit) - three bytes per pixel (R, G, B)
Byte Order: Platform-native (little-endian on x86/ARM)
Frame Dimensions: Variable (see Resize Behavior below)
Pixel Layout: Continuous row-major array (no padding between rows)
Frame format is opaque to the caller - the media source abstraction handles all conversions. Consumers always receive RGB frames ready to use:
// Get frame from any media source (format already normalized)
image_t *frame = media_source_read_video(source);
// Frame is guaranteed to be:
// - RGB format (8-bit per channel)
// - Dimensions: frame->width x frame->height pixels
// - Memory: frame->data[y * frame->width * 3 + x * 3 + channel]
Different input types undergo conversion:
WEBCAM: V4L2/AVFoundation -> RGB (platform layer conversion)
FILE/STDIN: FFmpeg decoder -> RGB (FFmpeg handles all codecs)
TEST: Generated directly as RGB (no conversion needed)
Frame Resizing and Aspect Ratio
Captured frames are resized for network efficiency while preserving aspect ratio:
Maximum Dimensions: 800x600 pixels (default) - reasonable bandwidth
Aspect Ratio: Original aspect ratio preserved via fit-to-bounds
Scaling Algorithm: Letterboxing - frame fits within bounds with padding
Padding Color: Black (0, 0, 0) for empty regions
Resize process:
Calculate scale factor to fit frame within 800x600
Compute new dimensions maintaining aspect ratio
Scale frame using resizing algorithm (maintains quality)
Add black padding to fill remaining space (if needed)
Example resizes:
1920x1440 (4:3) → 800x600 (fits exactly)
1280x720 (16:9) → 800x450 (with 75px black bars top/bottom)
640x480 (4:3) → 640x480 (no resize, smaller than max)
3840x2160 (16:9) → 800x450 (same 16:9 aspect)
Frame resizing options (future):
--resize-width <W> - Custom max width (default: 800)
--resize-height <H> - Custom max height (default: 600)
--no-resize - Disable resizing (use original dimensions)
Frame Rate Synchronization (FPS Control)
The capture system implements frame rate limiting for bandwidth efficiency and smooth playback:
Capture Rate: Up to 144 FPS (high refresh rate support)
Target FPS: Configurable via --fps <rate> (default: 60)
Range: 1 to 144 FPS (1 = slowest, 144 = fastest)
Timing Method: Monotonic clock for accuracy
Adaptive Delay: Dynamic sleep adjustment for consistent frame intervals
FPS configuration:
./ascii-chat client --fps 30               # 30 FPS (slower, less bandwidth)
./ascii-chat client --fps 60               # 60 FPS (default, balanced)
./ascii-chat client --fps 144              # 144 FPS (max, high refresh)
FPS behavior by source type:
WEBCAM: Captures at hardware rate, then throttles to target FPS
FILE: Plays at media file's native FPS, then throttles to target
STDIN: Decodes frames, then throttles to target FPS
TEST: Generates at target FPS directly (no throttling needed)
Frame rate calculation:
Calculate frame interval: interval_ms = 1000 / fps
Record capture start time (monotonic clock)
Capture and process frame
Calculate elapsed time
Sleep for remaining interval to achieve consistent rate
Example timing (60 FPS target = 16.67ms per frame):
Frame start: 0ms
Capture: 5ms
Process: 2ms
Elapsed: 7ms
Sleep: 9.67ms (to reach 16.67ms total)
Frame complete: 16.67ms ✓ (on schedule)
Capture Lifecycle
Initialization (capture_init): Set up platform-specific webcam drivers
Thread Start (capture_start_thread): Spawn capture thread in connection loop
Capture Loop: Continuously grab frames and send to server
Thread Stop (capture_stop_thread): Signal thread to exit and wait
Cleanup (capture_cleanup): Release platform resources
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
2025
See also
topic_client_capture "Video Capture Architecture"
media/source.h "Media Source Abstraction"
Definition in file client/capture.h.
Function Documentation
capture_cleanup()
void capture_cleanup ()
Cleanup capture subsystem.
Releases all platform resources associated with webcam access. This must be called after capture_stop_thread() and before process exit.
The cleanup process:
Closes webcam device (platform-specific close)
Frees frame buffers
Releases platform driver resources
Cleans up thread handles
Must be called in proper order during shutdown to avoid resource leaks and to restore the platform to a clean state.
See also
capture_init "Initialize capture subsystem"
Cleanup capture subsystem
Stops capture thread and cleans up media source resources. Called during client shutdown.
Definition at line 546 of file client/capture.c.
                       {
  capture_stop_thread();
  // Destroy capture context
  if (g_capture_capture_ctx) {
    session_capture_destroy(g_capture_capture_ctx);
    g_capture_capture_ctx = NULL;
  }
}
References capture_stop_thread(), and session_capture_destroy().
Referenced by client_crypto_handshake().
capture_init()
int capture_init ()
Initialize capture subsystem.
Initializes the media source and capture resources. Determines media source type from command-line options, then sets up platform-specific drivers and buffers. This must be called before any other capture functions.
The initialization process:
Determines media source type from options (test pattern, file, stdin, or webcam)
Creates appropriate media source (media_source_create())
For WEBCAM: Initializes platform driver (V4L2/AVFoundation/Media Foundation)
For FILE/STDIN: Opens FFmpeg decoder with format detection
For TEST: Initializes procedural test pattern generator
Initializes frame buffers and capture parameters
Media source selection (in order):
If --test-pattern → MEDIA_SOURCE_TEST
Else if --file - → MEDIA_SOURCE_STDIN
Else if --file <path> → MEDIA_SOURCE_FILE
Else if --url <url> → MEDIA_SOURCE_FILE (network URL)
Else → MEDIA_SOURCE_WEBCAM (with –webcam-index)
Options affecting initialization:
--test-pattern: Use synthetic test pattern (any platform, no hardware needed)
--file <path>: Media file to play (mp4, avi, mkv, gif, etc.)
--file -: Read media from stdin (any FFmpeg format)
--url <url>: Network stream (HTTP/HTTPS/RTSP/YouTube/etc.)
--webcam-index <N>: Which camera to open (default: 0, first camera)
--media-loop: Loop file playback when EOF reached
--webcam-flip: Flip video vertically (webcam and test patterns only)
--fps <rate>: Target frame rate in FPS (1-144, default: 60)
Error handling:
WEBCAM: Device not found, driver error, device busy
FILE: File not found, unsupported format, FFmpeg error
STDIN: FFmpeg format detection failure
TEST: Rarely fails (only if display dimensions unavailable)
Returns
ASCIICHAT_OK on success, error code on failure:
ERROR_WEBCAM: Device not found or driver error
ERROR_WEBCAM_IN_USE: Device busy (another app using it)
ERROR_FILE_NOT_FOUND: Media file not found
ERROR_FORMAT: Unsupported media format
ERROR_NOT_SUPPORTED: Platform doesn't support this source type
Note
This is called during client initialization, before entering the connection loop.
The actual frame capture happens in the capture thread (capture_start_thread).
Frame resizing to 800x600 (max) happens during capture, not initialization.
See also
media_source_create "Media source creation"
capture_start_thread "Start capture thread"
capture_cleanup "Cleanup resources"
Initialize capture subsystem
Sets up media source (webcam, file, or stdin) and prepares capture system for operation. Must be called once during client initialization.
Returns
0 on success, negative on error
Definition at line 405 of file client/capture.c.
                   {
  // Build capture configuration from options
  session_capture_config_t config = {0};
  const char *media_url = GET_OPTION(media_url);
  const char *media_file = GET_OPTION(media_file);
  bool media_from_stdin = GET_OPTION(media_from_stdin);
  if (media_url && media_url[0] != '\0') {
    // Network URL streaming (takes priority over --file)
    // Don't open webcam when streaming from URL
    config.type = MEDIA_SOURCE_FILE;
    config.path = media_url;
    config.loop = false; // Network URLs cannot be looped
    log_debug("Using network URL: %s (webcam disabled)", media_url);
  } else if (media_file && media_file[0] != '\0') {
    // File or stdin streaming - don't open webcam
    config.type = media_from_stdin ? MEDIA_SOURCE_STDIN : MEDIA_SOURCE_FILE;
    config.path = media_file;
    config.loop = GET_OPTION(media_loop) && !media_from_stdin;
    log_debug("Using media %s: %s (webcam disabled)", media_from_stdin ? "stdin" : "file", media_file);
  } else if (GET_OPTION(test_pattern)) {
    // Test pattern mode - don't open real webcam
    config.type = MEDIA_SOURCE_TEST;
    config.path = NULL;
    log_debug("Using test pattern mode");
  } else {
    // Webcam mode (default)
    static char webcam_index_str[32];
    safe_snprintf(webcam_index_str, sizeof(webcam_index_str), "%u", GET_OPTION(webcam_index));
    config.type = MEDIA_SOURCE_WEBCAM;
    config.path = webcam_index_str;
    log_debug("Using webcam device %u", GET_OPTION(webcam_index));
  }
  config.target_fps = CAPTURE_TARGET_FPS;
  config.resize_for_network = true; // Client always resizes for network transmission
  // Configure audio capture with fallback to microphone
  config.enable_audio = true;
  config.audio_fallback_to_mic = true;
  config.mic_audio_ctx = audio_get_context();
  // Add seek timestamp if specified
  config.initial_seek_timestamp = GET_OPTION(media_seek_timestamp);
  // Create capture context using session library
  g_capture_capture_ctx = session_capture_create(&config);
  if (!g_capture_capture_ctx) {
    // Check if there's already an error set (e.g., ERROR_WEBCAM_IN_USE)
    asciichat_error_t existing_error = GET_ERRNO();
    log_debug("session_capture_create failed, GET_ERRNO() returned: %d", existing_error);
    if (existing_error != ASCIICHAT_OK) {
      log_debug("Returning existing error code %d", existing_error);
      return existing_error;
    }
    SET_ERRNO(ERROR_MEDIA_INIT, "Failed to initialize capture source");
    return -1;
  }
  return 0;
}
References session_capture_config_t::audio_fallback_to_mic, audio_get_context(), CAPTURE_TARGET_FPS, session_capture_config_t::enable_audio, session_capture_config_t::initial_seek_timestamp, session_capture_config_t::loop, session_capture_config_t::mic_audio_ctx, session_capture_config_t::path, session_capture_config_t::resize_for_network, safe_snprintf(), session_capture_create(), session_capture_config_t::target_fps, and session_capture_config_t::type.
capture_start_thread()
int capture_start_thread ()
Start capture thread.
Spawns the capture thread in the global client worker thread pool. The thread runs the main capture loop, continuously acquiring frames from the media source, processing them (resize, format conversion), and transmitting to the server with FPS rate limiting.
The capture loop implements this pipeline:
Frame Acquisition:
Read frame from media source (media_source_read_video())
Verify frame is valid (non-null, valid dimensions)
Measure acquisition time for timing/debug
Frame Processing (Resize & Format):
Calculate optimal resize dimensions (fit-to-bounds, aspect ratio preserved)
Scale frame to max 800x600 using high-quality resizing
Format frame as RGB (already normalized by media source)
Add black padding if frame smaller than target area
FPS Synchronization:
Calculate frame interval from target FPS (e.g., 60 FPS = 16.67ms)
Measure actual processing time (acquisition + resize)
Sleep for remaining interval to maintain target FPS
Account for monotonic clock drift and OS scheduling
Network Transmission:
Optionally compress frame if –compress is enabled
Serialize frame to PACKET_TYPE_IMAGE_FRAME format (width + height + pixels)
Send packet to server via send_packet_to_server()
Log transmission metrics (size, latency, dropped frames)
Loop Control:
Check if in snapshot mode and should exit (–snapshot mode)
Check for shutdown signal (capture_stop_thread() called)
Check for connection loss (reconnect trigger)
Loop back to step 1
FPS Behavior:
Target FPS from --fps option (default: 60)
Achieved via sleep-based rate limiting (monotonic clock)
Maintains consistent frame intervals even if processing takes variable time
Adapts to system load and media source frame availability
Must be called after server connection is established and protocol thread started.
Returns
ASCIICHAT_OK on success, error code on failure:
ERROR_THREAD: Thread pool full or system thread creation failed
ERROR_NO_MEMORY: Insufficient memory for thread resources
Note
Must be paired with capture_stop_thread() to properly clean up.
Frame resizing and FPS limiting are handled transparently by the capture thread.
Rate limiting is frame-by-frame, not based on network round-trip time.
See also
capture_stop_thread "Stop capture thread"
capture_thread_exited "Check if thread has exited"
media_source_read_video "Frame acquisition from media source"
Start capture thread
Creates and starts the webcam capture thread. Also sends stream start notification to server.
Returns
0 on success, negative on error
Definition at line 475 of file client/capture.c.
{
  if (THREAD_IS_CREATED(g_capture_thread_created)) {
    log_warn("Capture thread already created");
    return 0;
  }
  // Register capture atomics with named debug registry
  static bool capture_atomics_registered = false;
  if (!capture_atomics_registered) {
    NAMED_REGISTER_ATOMIC(&g_capture_thread_exited, "capture_webcam_thread_exit_confirmation", NULL);
    capture_atomics_registered = true;
  }
  // Start webcam capture thread
  atomic_store_bool(&g_capture_thread_exited, false);
  if (thread_pool_spawn(g_client_worker_pool, webcam_capture_thread_func, NULL, 2, "webcam_capture") != ASCIICHAT_OK) {
    SET_ERRNO(ERROR_THREAD, "Webcam capture thread creation failed");
    LOG_ERRNO_IF_SET("Webcam capture thread creation failed");
    return -1;
  }
  g_capture_thread_created = true;
  log_debug("Webcam capture thread created successfully");
  return 0;
}
References atomic_store_bool(), g_client_worker_pool, and thread_pool_spawn().
Referenced by protocol_start_connection().
capture_stop_thread()
void capture_stop_thread ()
Stop capture thread.
Signals the capture thread to exit and waits for it to join cleanly. Called during connection loss handling or shutdown.
The function:
Sets shutdown flag
Polls capture_thread_exited() until thread exits
Releases thread-specific resources
Must be called before reconnection to prevent resource leaks.
Note
This function blocks until the capture thread exits. Typical wait time: <1 second (one frame interval).
See also
capture_start_thread "Start capture thread"
Stop capture thread
Gracefully stops the capture thread and cleans up resources. Safe to call multiple times.
Definition at line 509 of file client/capture.c.
{
  if (!THREAD_IS_CREATED(g_capture_thread_created)) {
    return;
  }
  // Wait for thread to exit gracefully
  int wait_count = 0;
  while (wait_count < 20 && !atomic_load_bool(&g_capture_thread_exited)) {
    platform_sleep_us(100 * US_PER_MS_INT); // 100ms
    wait_count++;
  }
  if (!atomic_load_bool(&g_capture_thread_exited)) {
    log_warn("Capture thread not responding after 2 seconds - will be joined by thread pool");
  }
  // Thread will be joined by thread_pool_stop_all() in protocol_stop_connection()
  g_capture_thread_created = false;
}
References atomic_load_bool(), and platform_sleep_us().
Referenced by capture_cleanup(), and protocol_stop_connection().
capture_thread_exited()
bool capture_thread_exited ()
Check if capture thread has exited.
Atomically checks whether the capture thread has finished execution. The main thread uses this to wait for clean thread shutdown before reconnection or final cleanup.
Returns
true if thread exited, false otherwise
Note
The main thread typically polls this in a 10-100ms loop until true.
See also
capture_stop_thread "Stop capture thread"
Check if capture thread has exited
Returns
true if thread has exited, false otherwise
Definition at line 535 of file client/capture.c.
{
  return atomic_load_bool(&g_capture_thread_exited);
}
References atomic_load_bool().