ascii-chat: compression.c File Reference
compression.c File Reference
🗜️ Fast zstd compression/decompression utilities for network payload optimization
Functions
asciichat_error_t compress_data (const void *input, size_t input_size, void **output, size_t *output_size, int compression_level)
asciichat_error_t decompress_data (const void *input, size_t input_size, void *output, size_t output_size)
bool should_compress (size_t original_size, size_t compressed_size)
Detailed Description
🗜️ Fast zstd compression/decompression utilities for network payload optimization
Definition in file compression.c.
Function Documentation
compress_data()
asciichat_error_t compress_data (const void * input, size_t input_size, void ** output, size_t * output_size, int compression_level)
Definition at line 14 of file compression.c.
{
  if (!input || input_size == 0 || !output || !output_size) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: input=%p, input_size=%zu, output=%p, output_size=%p",
                     input, input_size, output, output_size);
  }
  // Validate compression level (1-9 for real-time streaming)
  if (compression_level < 1 || compression_level > 9) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid compression level %d: must be between 1 and 9", compression_level);
  }
  // Calculate maximum compressed size
  size_t compressed_size = ZSTD_compressBound(input_size);
  // Sanity check ZSTD_compressBound result
  // ZSTD_compressBound returns 0 for errors or very large values for huge inputs
  if (compressed_size == 0 || compressed_size > 256 * 1024 * 1024) { // Max 256MB compressed buffer
    return SET_ERRNO(ERROR_INVALID_PARAM, "ZSTD_compressBound returned unreasonable size: %zu for input %zu",
                     compressed_size, input_size);
  }
  unsigned char *compressed_data = NULL;
  compressed_data = SAFE_MALLOC(compressed_size, unsigned char *);
  if (!compressed_data) {
    return SET_ERRNO(ERROR_MEMORY, "Failed to allocate compressed data buffer");
  }
  // Compress using zstd with user-specified compression level
  size_t ret = ZSTD_compress(compressed_data, compressed_size, input, input_size, compression_level);
  if (ZSTD_isError(ret)) {
    SAFE_FREE(compressed_data);
    return SET_ERRNO(ERROR_GENERAL, "zstd compression failed: %s", ZSTD_getErrorName(ret));
  }
  *output = compressed_data;
  *output_size = ret;
  return ASCIICHAT_OK;
}
Referenced by send_packet_secure().
decompress_data()
asciichat_error_t decompress_data (const void * input, size_t input_size, void * output, size_t output_size)
Definition at line 58 of file compression.c.
{
  if (!input || input_size == 0 || !output || output_size == 0) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: input=%p, input_size=%zu, output=%p, output_size=%zu",
                     input, input_size, output, output_size);
  }
  size_t ret = ZSTD_decompress(output, output_size, input, input_size);
  if (ZSTD_isError(ret)) {
    return SET_ERRNO(ERROR_GENERAL, "zstd decompression failed: %s", ZSTD_getErrorName(ret));
  }
  return ASCIICHAT_OK;
}
Referenced by packet_decode_frame_data_buffer(), and packet_decode_frame_data_malloc().
should_compress()
bool should_compress (size_t original_size, size_t compressed_size)
Definition at line 74 of file compression.c.
{
  if (original_size == 0)
    return false;
  float ratio = (float)compressed_size / (float)original_size;
  return ratio < COMPRESSION_RATIO_THRESHOLD;
}
Referenced by send_packet_secure().