ascii-chat: console.c File Reference
console.c File Reference
Browser console logging for WASM via Emscripten.
Functions
EM_JS (void, js_console_log,(int level, const char *message), { const msg=UTF8ToString($1);switch($0) { case 0:case 1:console.debug(msg);break;case 2:console.log(msg);break;case 3:console.warn(msg);break;case 4:case 5:console.error(msg);break;default:console.log(msg);} })
void platform_log_hook (log_level_t level, const char *message)
int wasm_parse_log_level (const uint8_t *buf, size_t count)
void wasm_log_to_console (int fd, const uint8_t *buf, size_t count)
Detailed Description
Browser console logging for WASM via Emscripten.
Definition in file console.c.
Function Documentation
EM_JS()
EM_JS (void , js_console_log , (int level, const char *message) , { const msg=UTF8ToString($1);switch($0) { case 0:case 1:console.debug(msg);break;case 2:console.log(msg);break;case 3:console.warn(msg);break;case 4:case 5:console.error(msg);break;default:console.log(msg);} })
platform_log_hook()
void platform_log_hook (log_level_t level, const char * message)
Definition at line 40 of file console.c.
{
  if (message) {
    js_console_log((int)level, message);
  }
}
Referenced by log_msg().
wasm_log_to_console()
void wasm_log_to_console (int fd, const uint8_t * buf, size_t count)
Definition at line 99 of file console.c.
{
  // For WASM, route stdout/stderr to browser console
  if ((fd == 1 || fd == 2) && buf && count > 0) {
    // Parse log level from formatted message
    int level = wasm_parse_log_level(buf, count);
    if (level >= 0) {
      // Create null-terminated string for console output
      // Copy buffer to local array and null-terminate
      static char msg_buffer[4096];
      size_t copy_len = (count < sizeof(msg_buffer) - 1) ? count : (sizeof(msg_buffer) - 1);
      memcpy(msg_buffer, buf, copy_len);
      msg_buffer[copy_len] = '\0';
      // Remove trailing newline if present (console adds it automatically)
      if (copy_len > 0 && msg_buffer[copy_len - 1] == '\n') {
        msg_buffer[copy_len - 1] = '\0';
      }
      // Route to console
      js_console_log(level, msg_buffer);
    }
  }
}
References wasm_parse_log_level().
Referenced by platform_write().
wasm_parse_log_level()
int wasm_parse_log_level (const uint8_t * buf, size_t count)
Definition at line 48 of file console.c.
{
  if (!buf || count < 5) {
    return -1; // Too short to contain [LEVEL]
  }
  // Check if message starts with [
  if (buf[0] != '[') {
    return -1;
  }
  // Look for closing ]
  int bracket_end = -1;
  for (size_t i = 1; i < count && i < 10; i++) {
    if (buf[i] == ']') {
      bracket_end = (int)i;
      break;
    }
  }
  if (bracket_end < 3) {
    return -1; // Too short, minimum is [XX]
  }
  // Extract level string
  int level_len = bracket_end - 1;
  const char *level_start = (const char *)&buf[1];
  // Match against known level strings (from logging.c)
  if (level_len == 3 && strncmp(level_start, "DEV", 3) == 0) {
    return LOG_DEV;
  }
  if (level_len == 5 && strncmp(level_start, "DEBUG", 5) == 0) {
    return LOG_DEBUG;
  }
  if (level_len == 4 && strncmp(level_start, "INFO", 4) == 0) {
    return LOG_INFO;
  }
  if (level_len == 4 && strncmp(level_start, "WARN", 4) == 0) {
    return LOG_WARN;
  }
  if (level_len == 5 && strncmp(level_start, "ERROR", 5) == 0) {
    return LOG_ERROR;
  }
  if (level_len == 5 && strncmp(level_start, "FATAL", 5) == 0) {
    return LOG_FATAL;
  }
  return -1; // Level not recognized
}
Referenced by wasm_log_to_console().