ascii-chat: crc32.c File Reference
crc32.c File Reference
⚡ Hardware-accelerated CRC32 checksum with ARM64 and x86_64 CPU feature detection
Functions
uint32_t asciichat_crc32_hw (const void *data, size_t len)
bool crc32_hw_is_available (void)
uint32_t asciichat_crc32_sw (const void *data, size_t len)
Detailed Description
⚡ Hardware-accelerated CRC32 checksum with ARM64 and x86_64 CPU feature detection
Definition in file crc32.c.
Function Documentation
asciichat_crc32_hw()
uint32_t asciichat_crc32_hw (const void * data, size_t len)
Definition at line 132 of file crc32.c.
{
  check_crc32_hw_support();
  if (!crc32_hw_available) {
    // DEBUG: Log fallback to software
    static bool logged_fallback = false;
    if (!logged_fallback) {
      log_debug("Using software CRC32 (no hardware acceleration)");
      logged_fallback = true;
    }
    return asciichat_crc32_sw(data, len);
  }
#ifdef ARCH_ARM64
  static bool logged_arm = false;
  if (!logged_arm) {
    log_debug("Using ARM64 hardware CRC32");
    logged_arm = true;
  }
  return crc32_arm_hw(data, len);
#elif defined(ARCH_X86_64)
  static bool logged_intel = false;
  if (!logged_intel) {
    log_debug("Using Intel x86_64 hardware CRC32 (SSE4.2)");
    logged_intel = true;
  }
  return crc32_intel_hw(data, len);
#else
  return asciichat_crc32_sw(data, len);
#endif
}
References asciichat_crc32_sw().
asciichat_crc32_sw()
uint32_t asciichat_crc32_sw (const void * data, size_t len)
Definition at line 171 of file crc32.c.
{
  const uint8_t *bytes = (const uint8_t *)data;
  uint32_t crc = 0xFFFFFFFF;
  // CRC32-C (Castagnoli) polynomial: 0x1EDC6F41
  // Reversed (for LSB-first): 0x82F63B78
  for (size_t i = 0; i < len; i++) {
    crc ^= bytes[i];
    for (int j = 0; j < 8; j++) {
      if (crc & 1) {
        crc = (crc >> 1) ^ 0x82F63B78; // CRC32-C polynomial (reversed)
      } else {
        crc >>= 1;
      }
    }
  }
  return ~crc;
}
Referenced by asciichat_crc32_hw(), and client_serialize_packet().
crc32_hw_is_available()
bool crc32_hw_is_available (void)
Definition at line 164 of file crc32.c.
{
  check_crc32_hw_support();
  return crc32_hw_available;
}