ascii-chat: atomic.c File Reference
atomic.c File Reference
Debug formatting and state tracking for atomic operations.
Functions
void debug_atomic_init (void)
void debug_atomic_shutdown (void)
bool debug_atomic_is_initialized (void)
int debug_atomic_format_timing (const atomic_t *atomic, char *buffer, size_t size)
Format timing info for an atomic and write to buffer.
int debug_atomic_ptr_format_timing (const atomic_ptr_t *atomic, char *buffer, size_t size)
Format timing info for an atomic_ptr_t and write to buffer.
void debug_atomic_print_state (void)
Detailed Description
Debug formatting and state tracking for atomic operations.
Date
March 2026
Implements debug-specific functions: initialization/shutdown, and state formatting for display via –sync-state.
Hook implementations (atomic_on_load, atomic_on_store, etc.) are now in lib/atomic.c alongside the wrapper functions they support.
Definition in file debug/atomic.c.
Function Documentation
debug_atomic_format_timing()
int debug_atomic_format_timing (const atomic_t * atomic, char * buffer, size_t size)
Format timing info for an atomic and write to buffer.
Parameters
atomic Pointer to atomic_t
buffer Output buffer
size Buffer size
Returns
Number of bytes written to buffer
Definition at line 51 of file debug/atomic.c.
{
    if (!atomic || !buffer || size == 0) return 0;
    // If never accessed, return empty (so caller can skip output)
    if (atomic->last_load_time_ns == 0 && atomic->last_store_time_ns == 0) {
        return 0;
    }
    int offset = 0;
    uint64_t now_ns = time_get_ns();
    char load_str[64] = "";
    char store_str[64] = "";
    char count_str[128] = "";
    if (atomic->last_load_time_ns > 0 && atomic->last_load_time_ns <= now_ns) {
        char elapsed_str[64];
        time_pretty(now_ns - atomic->last_load_time_ns, -1, elapsed_str, sizeof(elapsed_str));
        snprintf(load_str, sizeof(load_str), "load=%s", elapsed_str);
    }
    if (atomic->last_store_time_ns > 0 && atomic->last_store_time_ns <= now_ns) {
        char elapsed_str[64];
        time_pretty(now_ns - atomic->last_store_time_ns, -1, elapsed_str, sizeof(elapsed_str));
        snprintf(store_str, sizeof(store_str), "store=%s", elapsed_str);
    }
    if (atomic->load_count > 0 || atomic->store_count > 0 || atomic->cas_count > 0 || atomic->fetch_count > 0) {
        snprintf(count_str, sizeof(count_str), "[ops: load=%lu store=%lu cas=%lu/%lu fetch=%lu]",
                 atomic->load_count, atomic->store_count, atomic->cas_success_count, atomic->cas_count, atomic->fetch_count);
    }
    offset += snprintf(buffer + offset, size - offset, "%s %s %s", load_str, store_str, count_str);
    return offset;
}
References time_get_ns(), and time_pretty().
debug_atomic_init()
void debug_atomic_init (void)
Definition at line 28 of file debug/atomic.c.
{
    g_atomic_debug_initialized = true;
}
Referenced by main().
debug_atomic_is_initialized()
bool debug_atomic_is_initialized (void)
Definition at line 36 of file debug/atomic.c.
{
    return g_atomic_debug_initialized;
}
Referenced by atomic_on_cas(), atomic_on_fetch(), atomic_on_load(), atomic_on_store(), atomic_ptr_on_cas(), atomic_ptr_on_exchange(), atomic_ptr_on_load(), and atomic_ptr_on_store().
debug_atomic_print_state()
void debug_atomic_print_state (void)
Definition at line 130 of file debug/atomic.c.
{
    if (!g_atomic_debug_initialized) return;
    // Iterate named registry for atomic entries
    // Note: this is now kept for backward compatibility
    // The preferred method is to use sync.c's atomic_iter_callback
    // which integrates atomics into the synchronized output buffer
}
debug_atomic_ptr_format_timing()
int debug_atomic_ptr_format_timing (const atomic_ptr_t * atomic, char * buffer, size_t size)
Format timing info for an atomic_ptr_t and write to buffer.
Parameters
atomic Pointer to atomic_ptr_t
buffer Output buffer
size Buffer size
Returns
Number of bytes written to buffer
Definition at line 94 of file debug/atomic.c.
{
    if (!atomic || !buffer || size == 0) return 0;
    // If never accessed, return empty (so caller can skip output)
    if (atomic->last_load_time_ns == 0 && atomic->last_store_time_ns == 0) {
        return 0;
    }
    int offset = 0;
    uint64_t now_ns = time_get_ns();
    char load_str[64] = "";
    char store_str[64] = "";
    char count_str[128] = "";
    if (atomic->last_load_time_ns > 0 && atomic->last_load_time_ns <= now_ns) {
        char elapsed_str[64];
        time_pretty(now_ns - atomic->last_load_time_ns, -1, elapsed_str, sizeof(elapsed_str));
        snprintf(load_str, sizeof(load_str), "load=%s", elapsed_str);
    }
    if (atomic->last_store_time_ns > 0 && atomic->last_store_time_ns <= now_ns) {
        char elapsed_str[64];
        time_pretty(now_ns - atomic->last_store_time_ns, -1, elapsed_str, sizeof(elapsed_str));
        snprintf(store_str, sizeof(store_str), "store=%s", elapsed_str);
    }
    if (atomic->load_count > 0 || atomic->store_count > 0 || atomic->cas_count > 0 || atomic->exchange_count > 0) {
        snprintf(count_str, sizeof(count_str), "[ops: load=%lu store=%lu cas=%lu/%lu exchange=%lu]",
                 atomic->load_count, atomic->store_count, atomic->cas_success_count, atomic->cas_count, atomic->exchange_count);
    }
    offset += snprintf(buffer + offset, size - offset, "%s %s %s", load_str, store_str, count_str);
    return offset;
}
References time_get_ns(), and time_pretty().
debug_atomic_shutdown()
void debug_atomic_shutdown (void)
Definition at line 32 of file debug/atomic.c.
{
    g_atomic_debug_initialized = false;
}
Referenced by asciichat_shared_destroy().