ascii-chat: named.c File Reference
named.c File Reference
Named object registry for debugging.
Data Structures
struct named_entry
Registry entry for uthash.
struct named_registry_t
Global registry with uthash and rwlock.
struct named_iter_entry_t
Macros
#define MAX_NAME_LEN 256
#define DESCRIBE_BUFFER_SIZE 768
Typedefs
typedef struct named_entry named_entry_t
Registry entry for uthash.
Functions
asciichat_error_t named_init (void)
void named_destroy (void)
const char * named_register (uintptr_t key, const char *base_name, const char *type, const char *format_spec, const char *file, int line, const char *func, uintptr_t parent_key)
const char * named_register_fmt (uintptr_t key, const char *type, const char *format_spec, const char *file, int line, const char *func, const char *fmt,...)
void named_unregister (uintptr_t key)
const char * named_update_name (uintptr_t key, const char *new_base_name)
const char * named_get (uintptr_t key)
const char * named_get_type (uintptr_t key)
const char * named_get_format_spec (uintptr_t key)
const char * named_describe (uintptr_t key, const char *type_hint)
const char * named_describe_thread (void *thread)
void named_registry_for_each (named_iter_callback_t callback, void *user_data)
const char * named_search_by_type_id (const char *type, void *id)
const char * named_register_fd (int fd, const char *file, int line, const char *func)
const char * named_get_fd (int fd)
const char * named_get_fd_format_spec (int fd)
const char * named_register_packet_type (int pkt_type, const char *file, int line, const char *func)
const char * named_get_packet_type (int pkt_type)
const char * named_get_packet_type_format_spec (int pkt_type)
void named_registry_register_packet_types (void)
Detailed Description
Named object registry for debugging.
Provides a centralized registry for naming any addressable resource. Uses uthash for O(1) lookup by uintptr_t key. Rwlock protects the hash table with minimal critical section.
Definition in file debug/named.c.
Macro Definition Documentation
DESCRIBE_BUFFER_SIZE
#define DESCRIBE_BUFFER_SIZE 768
Definition at line 25 of file debug/named.c.
Referenced by named_describe().
MAX_NAME_LEN
#define MAX_NAME_LEN 256
Definition at line 24 of file debug/named.c.
Referenced by named_registry_for_each().
Typedef Documentation
named_entry_t
typedef struct named_entry named_entry_t
Registry entry for uthash.
Function Documentation
named_describe()
const char * named_describe (uintptr_t key, const char * type_hint)
Definition at line 336 of file debug/named.c.
{
  if (!type_hint) type_hint = "object";
  static _Thread_local char buffer[DESCRIBE_BUFFER_SIZE];
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    snprintf(buffer, sizeof(buffer), "%s (0x%tx)", type_hint, (ptrdiff_t)key);
    return buffer;
  }
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  rwlock_rdunlock(&g_named_registry.entries_lock);
  if (entry) {
    const char *type = entry->type ? entry->type : type_hint;
    const char *name = entry->name ? entry->name : "unknown";
    if (entry->file && entry->func && entry->line > 0) {
      snprintf(buffer, sizeof(buffer), "%s/%s (0x%tx) @ %s:%d:%s()", type, name, (ptrdiff_t)key,
               entry->file, entry->line, entry->func);
    } else {
      snprintf(buffer, sizeof(buffer), "%s/%s (0x%tx)", type, name, (ptrdiff_t)key);
    }
  } else {
    snprintf(buffer, sizeof(buffer), "%s (0x%tx)", type_hint ? type_hint : "unknown", (ptrdiff_t)key);
  }
  return buffer;
}
References DESCRIBE_BUFFER_SIZE, named_entry::file, named_entry::func, lifecycle_is_initialized(), named_entry::line, named_entry::name, and named_entry::type.
Referenced by named_describe_thread().
named_describe_thread()
const char * named_describe_thread (void * thread)
Definition at line 367 of file debug/named.c.
{
  uintptr_t key = asciichat_thread_to_key((asciichat_thread_t)thread);
  return named_describe(key, "thread");
}
References named_describe().
named_destroy()
void named_destroy (void)
Definition at line 93 of file debug/named.c.
{
  // Always attempt to shut down the lifecycle, but always cleanup entries
  lifecycle_shutdown(&g_named_registry.lifecycle);
  rwlock_wrlock(&g_named_registry.entries_lock);
  // Find the registry's own rwlock entry (allocated during named_init bootstrap)
  // This entry will be unregistered by rwlock_destroy, so we must not free it here
  uintptr_t registry_lock_key = (uintptr_t)(const void *)&g_named_registry.entries_lock;
  named_entry_t *registry_lock_entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &registry_lock_key, sizeof(uintptr_t), registry_lock_entry);
  for (named_entry_t *e = g_named_registry.entries; e != NULL;) {
    named_entry_t *next = e->hh.next;
    // Skip the registry lock entry - it will be cleaned up by rwlock_destroy
    // which calls NAMED_UNREGISTER after we release the lock
    if (e == registry_lock_entry) {
      e = next;
      continue;
    }
    // Free all other entries
    free(e->name);
    if (e->type) free(e->type);
    if (e->format_spec) free(e->format_spec);
    if (e->file) free(e->file);
    if (e->func) free(e->func);
    free(e);
    e = next;
  }
  rwlock_wrunlock(&g_named_registry.entries_lock);
  // rwlock_destroy will call NAMED_UNREGISTER on the lock entry, which will:
  // 1. Acquire the lock (now safe since we released it)
  // 2. Find and remove the lock entry from the hash
  // 3. Free the lock entry's fields
  rwlock_destroy(&g_named_registry.entries_lock);
}
References lifecycle_shutdown().
Referenced by asciichat_shared_destroy().
named_get()
const char * named_get (uintptr_t key)
Definition at line 297 of file debug/named.c.
{
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return NULL;
  }
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  const char *result = entry ? entry->name : NULL;
  rwlock_rdunlock(&g_named_registry.entries_lock);
  return result;
}
References lifecycle_is_initialized(), and named_entry::name.
Referenced by log_template_apply().
named_get_fd()
const char * named_get_fd (int fd)
Definition at line 450 of file debug/named.c.
{
  if (fd < 0) return NULL;
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return NULL;
  }
  uintptr_t key = encode_fd_key(fd);
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  const char *result = entry ? entry->name : NULL;
  rwlock_rdunlock(&g_named_registry.entries_lock);
  return result;
}
References lifecycle_is_initialized(), and named_entry::name.
Referenced by log_named_format_message().
named_get_fd_format_spec()
const char * named_get_fd_format_spec (int fd)
Definition at line 466 of file debug/named.c.
{
  if (fd < 0) return NULL;
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return NULL;
  }
  uintptr_t key = encode_fd_key(fd);
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  const char *result = entry ? entry->format_spec : NULL;
  rwlock_rdunlock(&g_named_registry.entries_lock);
  return result;
}
References named_entry::format_spec, and lifecycle_is_initialized().
named_get_format_spec()
const char * named_get_format_spec (uintptr_t key)
Definition at line 323 of file debug/named.c.
{
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return NULL;
  }
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  const char *result = entry ? entry->format_spec : NULL;
  rwlock_rdunlock(&g_named_registry.entries_lock);
  return result;
}
References named_entry::format_spec, and lifecycle_is_initialized().
named_get_packet_type()
const char * named_get_packet_type (int pkt_type)
Definition at line 511 of file debug/named.c.
{
  if (pkt_type < 0) return NULL;
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return NULL;
  }
  uintptr_t key = encode_pkt_type_key(pkt_type);
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  const char *result = entry ? entry->name : NULL;
  rwlock_rdunlock(&g_named_registry.entries_lock);
  return result;
}
References lifecycle_is_initialized(), and named_entry::name.
Referenced by log_named_format_message().
named_get_packet_type_format_spec()
const char * named_get_packet_type_format_spec (int pkt_type)
Definition at line 527 of file debug/named.c.
{
  if (pkt_type < 0) return NULL;
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return NULL;
  }
  uintptr_t key = encode_pkt_type_key(pkt_type);
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  const char *result = entry ? entry->format_spec : NULL;
  rwlock_rdunlock(&g_named_registry.entries_lock);
  return result;
}
References named_entry::format_spec, and lifecycle_is_initialized().
named_get_type()
const char * named_get_type (uintptr_t key)
Definition at line 310 of file debug/named.c.
{
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return NULL;
  }
  rwlock_rdlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  const char *result = entry ? entry->type : NULL;
  rwlock_rdunlock(&g_named_registry.entries_lock);
  return result;
}
References lifecycle_is_initialized(), and named_entry::type.
named_init()
asciichat_error_t named_init (void)
Definition at line 74 of file debug/named.c.
{
  // Idempotent: if already initialized, return success
  if (lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return ASCIICHAT_OK;
  }
  if (!lifecycle_init(&g_named_registry.lifecycle, "named_registry")) {
    return ASCIICHAT_OK;
  }
  if (rwlock_init(&g_named_registry.entries_lock, "named_registry_lock") != 0) {
    lifecycle_shutdown(&g_named_registry.lifecycle);
    return ASCIICHAT_OK;  // Continue even if rwlock init fails
  }
  lifecycle_init_commit(&g_named_registry.lifecycle);
  return ASCIICHAT_OK;
}
References lifecycle_init(), lifecycle_init_commit(), lifecycle_is_initialized(), lifecycle_shutdown(), and rwlock_init().
Referenced by asciichat_shared_init(), and main().
named_register()
const char * named_register (uintptr_t key, const char * base_name, const char * type, const char * format_spec, const char * file, int line, const char * func, uintptr_t parent_key)
Definition at line 168 of file debug/named.c.
{
  if (!base_name || !type || !format_spec) {
    return "?";
  }
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return base_name;
  }
  // If parent_key provided, look up parent name and create hierarchical name
  char final_base_name[256];
  if (parent_key != 0) {
    rwlock_rdlock(&g_named_registry.entries_lock);
    const char *parent_name = named_lookup_name_unlocked(parent_key);
    rwlock_rdunlock(&g_named_registry.entries_lock);
    if (parent_name) {
      snprintf(final_base_name, sizeof(final_base_name), "%s#%s", parent_name, base_name);
    } else {
      // Parent not found, fall back to base name
      snprintf(final_base_name, sizeof(final_base_name), "%s", base_name);
    }
  } else {
    snprintf(final_base_name, sizeof(final_base_name), "%s", base_name);
  }
  // Generate unique name using atomic counters (only for non-hierarchical names)
  char name_buffer[256];
  if (parent_key == 0) {
    uint64_t counter = 0;
    if (strcmp(type, "mutex") == 0) {
      counter = __sync_fetch_and_add(&mutex_counter, 1);
    } else if (strcmp(type, "rwlock") == 0) {
      counter = __sync_fetch_and_add(&rwlock_counter, 1);
    } else if (strcmp(type, "cond") == 0) {
      counter = __sync_fetch_and_add(&cond_counter, 1);
    } else if (strcmp(type, "atomic") == 0) {
      counter = __sync_fetch_and_add(&atomic_counter, 1);
    }
    snprintf(name_buffer, sizeof(name_buffer), "%s.%"PRIu64, final_base_name, counter);
  } else {
    // Hierarchical names don't get counters - parent already has one
    snprintf(name_buffer, sizeof(name_buffer), "%s", final_base_name);
  }
  // Allocate entry BEFORE acquiring lock (avoid long critical section)
  named_entry_t *entry = malloc(sizeof(named_entry_t));
  if (!entry) return base_name;
  entry->key = key;
  entry->name = entry_strdup(name_buffer);
  named_entry_init(entry, type, format_spec, file, line, func);
  // Only hold lock for the hash table operation
  rwlock_wrlock(&g_named_registry.entries_lock);
  HASH_ADD(hh, g_named_registry.entries, key, sizeof(uintptr_t), entry);
  rwlock_wrunlock(&g_named_registry.entries_lock);
  return entry->name;
}
References named_entry::key, lifecycle_is_initialized(), and named_entry::name.
named_register_fd()
const char * named_register_fd (int fd, const char * file, int line, const char * func)
Definition at line 421 of file debug/named.c.
{
  if (fd < 0) {
    return "?";
  }
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return "?";
  }
  char name_buffer[256];
  snprintf(name_buffer, sizeof(name_buffer), "fd=%d", fd);
  // Allocate entry BEFORE acquiring lock
  named_entry_t *entry = malloc(sizeof(named_entry_t));
  if (!entry) return "?";
  uintptr_t key = encode_fd_key(fd);
  entry->key = key;
  entry->name = entry_strdup(name_buffer);
  named_entry_init(entry, "fd", "%d", file, line, func);
  // Only hold lock for the hash table operation
  rwlock_wrlock(&g_named_registry.entries_lock);
  HASH_ADD(hh, g_named_registry.entries, key, sizeof(uintptr_t), entry);
  rwlock_wrunlock(&g_named_registry.entries_lock);
  return entry->name;
}
References named_entry::key, lifecycle_is_initialized(), and named_entry::name.
named_register_fmt()
const char * named_register_fmt (uintptr_t key, const char * type, const char * format_spec, const char * file, int line, const char * func, const char * fmt, ...)
Definition at line 230 of file debug/named.c.
{
  if (!type || !format_spec || !fmt) {
    return "?";
  }
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return fmt;
  }
  // Format the name BEFORE acquiring lock
  va_list args;
  va_start(args, fmt);
  char *full_name = NULL;
  int ret = vasprintf(&full_name, fmt, args);
  va_end(args);
  if (ret < 0) {
    return "?";
  }
  // Allocate entry BEFORE acquiring lock
  named_entry_t *entry = malloc(sizeof(named_entry_t));
  if (!entry) {
    free(full_name);
    return "?";
  }
  // Initialize entry (name is pre-allocated as full_name)
  entry->key = key;
  entry->name = full_name;
  named_entry_init(entry, type, format_spec, file, line, func);
  // Only hold lock for the hash table operation
  rwlock_wrlock(&g_named_registry.entries_lock);
  HASH_ADD(hh, g_named_registry.entries, key, sizeof(uintptr_t), entry);
  rwlock_wrunlock(&g_named_registry.entries_lock);
  return entry->name;
}
References args, named_entry::key, lifecycle_is_initialized(), and named_entry::name.
named_register_packet_type()
const char * named_register_packet_type (int pkt_type, const char * file, int line, const char * func)
Definition at line 482 of file debug/named.c.
{
  if (pkt_type < 0) {
    return "?";
  }
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return "?";
  }
  char name_buffer[256];
  snprintf(name_buffer, sizeof(name_buffer), "PACKET_TYPE=%d", pkt_type);
  // Allocate entry BEFORE acquiring lock
  named_entry_t *entry = malloc(sizeof(named_entry_t));
  if (!entry) return "?";
  uintptr_t key = encode_pkt_type_key(pkt_type);
  entry->key = key;
  entry->name = entry_strdup(name_buffer);
  named_entry_init(entry, "packet_type", "%d", file, line, func);
  // Only hold lock for the hash table operation
  rwlock_wrlock(&g_named_registry.entries_lock);
  HASH_ADD(hh, g_named_registry.entries, key, sizeof(uintptr_t), entry);
  rwlock_wrunlock(&g_named_registry.entries_lock);
  return entry->name;
}
References named_entry::key, lifecycle_is_initialized(), and named_entry::name.
named_registry_for_each()
void named_registry_for_each (named_iter_callback_t callback, void * user_data)
Definition at line 377 of file debug/named.c.
{
  if (!callback || !lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return;
  }
  // Snapshot entries while holding read lock
  named_iter_entry_t entries[256];
  int count = 0;
  rwlock_rdlock(&g_named_registry.entries_lock);
  for (named_entry_t *e = g_named_registry.entries; e != NULL && count < 256; e = e->hh.next) {
    entries[count].key = e->key;
    strncpy(entries[count].name, e->name ? e->name : "?", MAX_NAME_LEN - 1);
    entries[count].name[MAX_NAME_LEN - 1] = '\0';
    count++;
  }
  rwlock_rdunlock(&g_named_registry.entries_lock);
  // Call callback outside the lock
  for (int i = 0; i < count; i++) {
    callback(entries[i].key, entries[i].name, user_data);
  }
}
References named_iter_entry_t::key, lifecycle_is_initialized(), MAX_NAME_LEN, and named_iter_entry_t::name.
Referenced by debug_sync_check_cond_deadlocks(), and debug_sync_print_state().
named_registry_register_packet_types()
void named_registry_register_packet_types (void)
Definition at line 543 of file debug/named.c.
{
  // No-op
}
Referenced by main().
named_search_by_type_id()
const char * named_search_by_type_id (const char * type, void * id)
Definition at line 401 of file debug/named.c.
{
  (void)type;
  (void)id;
  return NULL;
}
named_unregister()
void named_unregister (uintptr_t key)
Definition at line 271 of file debug/named.c.
{
  if (!lifecycle_is_initialized(&g_named_registry.lifecycle)) {
    return;
  }
  rwlock_wrlock(&g_named_registry.entries_lock);
  named_entry_t *entry = NULL;
  HASH_FIND(hh, g_named_registry.entries, &key, sizeof(uintptr_t), entry);
  if (entry) {
    HASH_DEL(g_named_registry.entries, entry);
    free(entry->name);
    if (entry->type) free(entry->type);
    if (entry->format_spec) free(entry->format_spec);
    if (entry->file) free(entry->file);
    if (entry->func) free(entry->func);
    free(entry);
  }
  rwlock_wrunlock(&g_named_registry.entries_lock);
}
References named_entry::file, named_entry::format_spec, named_entry::func, lifecycle_is_initialized(), named_entry::name, and named_entry::type.
named_update_name()
const char * named_update_name (uintptr_t key, const char * new_base_name)
Definition at line 291 of file debug/named.c.
{
  (void)key;
  (void)new_base_name;
  return NULL;
}
Referenced by tcp_client_connect(), and websocket_client_connect().