ascii-chat: main.c File Reference
main.c File Reference
ascii-chat Discovery Mode Entry Point
Functions
int discovery_main (void)
Run discovery mode main loop.
Detailed Description
ascii-chat Discovery Mode Entry Point
Discovery mode enables zero-configuration video chat where participants can dynamically become hosts based on NAT quality. This implements the "one command to start, one command to join" philosophy.
Discovery Flow
Parse session string (word-word-word format)
Query ACDS for session information
Assess NAT quality (STUN test)
Either: a. Connect to existing host as participant b. Become host if no host exists or better NAT quality
Handle dynamic role changes during session
Implementation Architecture
Discovery mode uses lib/session APIs for media handling:
session_host_t: For rendering and broadcasting when elected host
session_participant_t: For capture and display when not host
discovery_session_t: For ACDS connection and host negotiation
No network protocol code duplication - all media handling via lib/session.
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
Version
1.0
Definition in file discovery/main.c.
Function Documentation
discovery_main()
int discovery_main (void)
Run discovery mode main loop.
Discovery mode entry point for unified binary.
Handles session discovery, host negotiation, and media flow.
Returns
0 on success, non-zero error code on failure
Definition at line 323 of file discovery/main.c.
{
  log_debug("discovery_main() starting");
  // Discovery-specific setup: initialize ACDS connection and session negotiation
  // Note: Shared setup (keepawake, splash, terminal, capture, display, audio)
  // is handled by session_client_like_run()
  // Get session string from options (command-line argument)
  const char *session_string = GET_OPTION(session_string);
  bool is_initiator = (session_string == NULL || session_string[0] == '\0');
  int port_int = GET_OPTION(port);
  log_debug("Discovery: is_initiator=%d, port=%d", is_initiator, port_int);
  // Create discovery session configuration
  discovery_config_t discovery_config = {
      .acds_address = GET_OPTION(discovery_server),
      .acds_port = (uint16_t)GET_OPTION(discovery_port),
      .session_string = is_initiator ? NULL : session_string,
      .local_port = (uint16_t)port_int,
      .on_state_change = on_discovery_state_change,
      .on_session_ready = on_session_ready,
      .on_error = on_discovery_error,
      .callback_user_data = NULL,
      .should_exit_callback = discovery_capture_should_exit_adapter,
      .exit_callback_data = NULL,
  };
  // Create discovery session (stored in global for discovery_run() to access)
  g_discovery = discovery_session_create(&discovery_config);
  if (!g_discovery) {
    log_fatal("Failed to create discovery session");
    return ERROR_MEMORY;
  }
  // Start discovery session (connects to ACDS, creates/joins, initiates NAT negotiation)
  log_debug("Discovery: starting discovery session");
  asciichat_error_t result = discovery_session_start(g_discovery);
  if (result != ASCIICHAT_OK) {
    log_fatal("Failed to start discovery session: %d", result);
    discovery_session_destroy(g_discovery);
    g_discovery = NULL;
    return result;
  }
  // No network interrupt callback needed - discovery session handles its own shutdown
  set_interrupt_callback(NULL);
  /* ========================================================================
   * Configure and Run Shared Client-Like Session Framework
   * ========================================================================
   * session_client_like_run() handles all shared initialization:
   * - Terminal output management
   * - Keepawake system
   * - Splash screen lifecycle
   * - Media source selection
   * - FPS probing
   * - Audio initialization
   * - Display context creation
   * - Proper cleanup ordering
   *
   * Discovery mode provides:
   * - discovery_run() callback: NAT negotiation, role determination, media handling
   * - discovery_keyboard_handler: interactive controls for participant role
   */
  session_client_like_config_t config = {
      .run_fn = discovery_run,
      .run_user_data = NULL,
      .tcp_client = NULL,
      .websocket_client = NULL,
      .discovery = (void *)g_discovery, // Opaque pointer to discovery session
      .custom_should_exit = NULL,
      .exit_user_data = NULL,
      .keyboard_handler = discovery_keyboard_handler,
      .max_reconnect_attempts = 0, // Discovery doesn't retry - role is determined once
      .should_reconnect_callback = NULL,
      .reconnect_user_data = NULL,
      .reconnect_delay_ms = 0,
      .print_newline_on_tty_exit = false, // Server/participant manages cursor
  };
  log_debug("Discovery: calling session_client_like_run()");
  asciichat_error_t session_result = session_client_like_run(&config);
  log_debug("Discovery: session_client_like_run() returned %d", session_result);
  // Cleanup discovery session
  log_debug("Discovery: cleaning up");
  if (g_discovery) {
    discovery_session_stop(g_discovery);
    discovery_session_destroy(g_discovery);
    g_discovery = NULL;
  }
  return (session_result == ASCIICHAT_OK) ? 0 : (int)session_result;
}
References discovery_session_create(), discovery_session_destroy(), discovery_session_start(), discovery_session_stop(), session_client_like_run(), and set_interrupt_callback().