ascii-chat: election.c File Reference
election.c File Reference
Deterministic election algorithm.
Functions
uint32_t consensus_election_compute_score (const participant_metrics_t *metrics)
asciichat_error_t consensus_election_choose_hosts (const participant_metrics_t *metrics, int num_metrics, int *out_best_index, int *out_backup_index)
asciichat_error_t consensus_election_verify (const participant_metrics_t *metrics, int num_metrics, const uint8_t announced_host_id[16], const uint8_t announced_backup_id[16], bool *out_valid)
Detailed Description
Deterministic election algorithm.
Definition in file election.c.
Function Documentation
consensus_election_choose_hosts()
asciichat_error_t consensus_election_choose_hosts (const participant_metrics_t * metrics, int num_metrics, int * out_best_index, int * out_backup_index)
Definition at line 67 of file election.c.
{
  if (!metrics || !out_best_index || !out_backup_index || num_metrics < 1) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid election parameters");
  }
  // Compute scores for all participants
  uint32_t *scores = SAFE_MALLOC(sizeof(uint32_t) * num_metrics, uint32_t *);
  for (int i = 0; i < num_metrics; i++) {
    scores[i] = consensus_election_compute_score(&metrics[i]);
  }
  // Find best and second-best
  find_best_two(scores, num_metrics, out_best_index, out_backup_index);
  SAFE_FREE(scores);
  return ASCIICHAT_OK;
}
References consensus_election_compute_score().
Referenced by consensus_election_verify().
consensus_election_compute_score()
uint32_t consensus_election_compute_score (const participant_metrics_t * metrics)
Definition at line 13 of file election.c.
{
  if (!metrics)
    return 0;
  // NAT tier: 0=LAN (best), 4=TURN (worst)
  // (4 - tier) * 1000 makes LAN score 4000, TURN score 0
  uint32_t nat_score = (4 - metrics->nat_tier) * 1000;
  // Bandwidth: higher is better
  // Divide by 10 to keep in reasonable scale (10Mbps = +1000)
  uint32_t bw_score = metrics->upload_kbps / 10;
  // Latency: lower is better
  // (500ms - rtt_ns) means 0ns RTT = +500, 500ms = 0, high latency = negative (but capped at 0)
  // 500ms = 500,000,000ns
  uint32_t rtt_score = (metrics->rtt_ns < 500 * NS_PER_MS) ? (500 - (metrics->rtt_ns / NS_PER_MS)) : 0;
  // STUN probe success: 0-100%
  uint32_t probe_score = metrics->stun_probe_success_pct;
  // Total score
  uint32_t total = nat_score + bw_score + rtt_score + probe_score;
  return total;
}
Referenced by consensus_election_choose_hosts().
consensus_election_verify()
asciichat_error_t consensus_election_verify (const participant_metrics_t * metrics, int num_metrics, const uint8_t announced_host_id[16], const uint8_t announced_backup_id[16], bool * out_valid)
Definition at line 87 of file election.c.
{
  if (!metrics || !announced_host_id || !announced_backup_id || !out_valid) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid verification parameters");
  }
  // Find which indices the announced IDs correspond to
  int host_idx = -1, backup_idx = -1;
  for (int i = 0; i < num_metrics; i++) {
    if (memcmp(metrics[i].participant_id, announced_host_id, 16) == 0) {
      host_idx = i;
    }
    if (memcmp(metrics[i].participant_id, announced_backup_id, 16) == 0) {
      backup_idx = i;
    }
  }
  // If we can't find announced IDs, result is invalid
  if (host_idx < 0 || backup_idx < 0) {
    *out_valid = false;
    return ASCIICHAT_OK;
  }
  // Run our own election
  int computed_host, computed_backup;
  asciichat_error_t err = consensus_election_choose_hosts(metrics, num_metrics, &computed_host, &computed_backup);
  if (err != ASCIICHAT_OK) {
    return err;
  }
  // Check if computed result matches announced
  *out_valid = (host_idx == computed_host && backup_idx == computed_backup);
  return ASCIICHAT_OK;
}
References consensus_election_choose_hosts(), and participant_id.