ascii-chat: embedded.c File Reference
embedded.c File Reference
Functions
int get_manpage_template (FILE **out_file, const char **out_content, size_t *out_len)
int get_manpage_content (FILE **out_file, const char **out_content, size_t *out_len)
void release_manpage_resources (FILE *file)
Function Documentation
get_manpage_content()
int get_manpage_content (FILE ** out_file, const char ** out_content, size_t * out_len)
Definition at line 75 of file embedded.c.
{
  // Content is now consolidated into the template - return empty
  if (out_content) {
    *out_content = "";
  }
  if (out_len) {
    *out_len = 0;
  }
  if (out_file) {
    *out_file = NULL;
  }
  log_debug("Man page content is now consolidated into template (empty)");
  return 0;
}
get_manpage_template()
int get_manpage_template (FILE ** out_file, const char ** out_content, size_t * out_len)
Definition at line 22 of file embedded.c.
{
#ifdef NDEBUG
  // Release build: Return embedded data
  if (out_content) {
    *out_content = embedded_manpage_template;
  }
  if (out_len) {
    *out_len = embedded_manpage_template_size;
  }
  if (out_file) {
    *out_file = NULL;
  }
  log_debug("Using embedded man page template (%zu bytes)", embedded_manpage_template_size);
  return 0;
#else
  // Debug build: Read from filesystem
  if (!out_file) {
    SET_ERRNO(ERROR_INVALID_PARAM, "out_file cannot be NULL in development mode");
    return -1;
  }
  // Construct absolute path using ASCIICHAT_RESOURCE_DIR (set at build time)
#ifdef ASCIICHAT_RESOURCE_DIR
  static char path_buffer[PATH_MAX];
  safe_snprintf(path_buffer, sizeof(path_buffer), "%s/share/man/man1/ascii-chat.1.in", ASCIICHAT_RESOURCE_DIR);
  const char *path = path_buffer;
#else
  // Fallback: try relative path if ASCIICHAT_RESOURCE_DIR not defined
  const char *path = "share/man/man1/ascii-chat.1.in";
#endif
  // Use binary mode to ensure fread byte count matches ftell file size.
  // Text mode on Windows translates \r\n to \n, causing size mismatch.
  FILE *f = platform_fopen("file_stream", path, "rb");
  if (!f) {
    SET_ERRNO_SYS(ERROR_CONFIG, "Failed to open man page template: %s", path);
    return -1;
  }
  *out_file = f;
  if (out_content) {
    *out_content = NULL;
  }
  if (out_len) {
    *out_len = 0;
  }
  log_debug("Using filesystem man page template: %s", path);
  return 0;
#endif
}
References platform_fopen(), and safe_snprintf().
Referenced by manpage_resources_load().
release_manpage_resources()
void release_manpage_resources (FILE * file)
Definition at line 91 of file embedded.c.
{
#ifdef NDEBUG
  // Release build: No-op (embedded data is static, not heap-allocated)
  (void)file; // Suppress unused parameter warning
#else
  // Debug build: Close file handle if present
  if (file) {
    fclose(file);
  }
#endif
}