ascii-chat: examples.c File Reference
examples.c File Reference
EXAMPLES section generator for man pages.
Data Structures
struct mode_bit_name_t
Mode name mapping for bitmask extraction.
Functions
char * manpage_content_generate_examples (const options_config_t *config)
void manpage_content_free_examples (char *content)
Detailed Description
EXAMPLES section generator for man pages.
Definition in file examples.c.
Function Documentation
manpage_content_free_examples()
void manpage_content_free_examples (char * content)
Definition at line 141 of file examples.c.
{
  if (content) {
    SAFE_FREE(content);
  }
}
Referenced by options_config_generate_manpage_merged(), and options_config_generate_manpage_template().
manpage_content_generate_examples()
char * manpage_content_generate_examples (const options_config_t * config)
Definition at line 79 of file examples.c.
{
  if (!config || config->num_examples == 0) {
    char *buffer = SAFE_MALLOC(1, char *);
    buffer[0] = '\0';
    return buffer;
  }
  // Seed random number generator for mode selection
  // Use config pointer address for deterministic-but-varied seed
  srand((unsigned int)((uintptr_t)config));
  // Allocate growing buffer for examples section
  size_t buffer_capacity = 8192;
  char *buffer = SAFE_MALLOC(buffer_capacity, char *);
  size_t offset = 0;
  for (size_t i = 0; i < config->num_examples; i++) {
    const example_descriptor_t *example = &config->examples[i];
    // Get all mode names from bitmask (examples can apply to multiple modes)
    // For man pages, we only show each example once, randomly selecting one mode
    size_t num_modes = 0;
    const char **mode_names = get_all_mode_names_from_bitmask(example->mode_bitmask, &num_modes);
    // Ensure buffer is large enough
    if (offset + 512 >= buffer_capacity) {
      buffer_capacity *= 2;
      buffer = SAFE_REALLOC(buffer, buffer_capacity, char *);
    }
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".TP\n");
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".B ascii-chat");
    // Add mode name if applicable (randomly select one mode for multi-mode examples)
    if (num_modes > 0) {
      size_t selected_mode = (size_t)rand() % num_modes;
      if (mode_names[selected_mode]) {
        offset += safe_snprintf(buffer + offset, buffer_capacity - offset, " %s", mode_names[selected_mode]);
      }
    }
    if (example->args) {
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, " %s", example->args);
    }
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, "\n");
    if (example->description) {
      offset +=
          safe_snprintf(buffer + offset, buffer_capacity - offset, "%s\n", escape_groff_special(example->description));
    }
    // Free mode names array
    if (mode_names) {
      SAFE_FREE(mode_names);
    }
  }
  offset += safe_snprintf(buffer + offset, buffer_capacity - offset, "\n");
  return buffer;
}
References escape_groff_special(), and safe_snprintf().
Referenced by options_config_generate_manpage_merged(), and options_config_generate_manpage_template().