ascii-chat: filesystem.c File Reference
filesystem.c File Reference
Cross-platform filesystem utilities and binary PATH cache.
Data Structures
struct bin_cache_entry_t
Cache entry for binary PATH lookup.
Functions
const char * file_read_error_message (const char *path)
const char * file_write_error_message (const char *path)
void platform_cleanup_binary_path_cache (void)
bool platform_is_binary_in_path (const char *bin_name)
bool platform_get_executable_path (char *exe_path, size_t path_size)
Get the path to the current executable.
Detailed Description
Cross-platform filesystem utilities and binary PATH cache.
Definition in file filesystem.c.
Function Documentation
file_read_error_message()
const char * file_read_error_message (const char * path)
Definition at line 20 of file filesystem.c.
{
  switch (errno) {
  case ENOENT:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "File does not exist: %s", path);
    break;
  case EACCES:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Permission denied (cannot read): %s", path);
    break;
  case EISDIR:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Is a directory, not a file: %s", path);
    break;
  default:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Failed to open for reading: %s (%s)", path,
             platform_strerror(errno));
    break;
  }
  return error_msg_buffer;
}
References platform_strerror().
Referenced by update_check_load_cache().
file_write_error_message()
const char * file_write_error_message (const char * path)
Definition at line 39 of file filesystem.c.
{
  switch (errno) {
  case ENOENT:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Directory does not exist: %s", path);
    break;
  case EACCES:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Permission denied (cannot write): %s", path);
    break;
  case EROFS:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Read-only filesystem: %s", path);
    break;
  case ENOSPC:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "No space left on device: %s", path);
    break;
  case EISDIR:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Is a directory, not a file: %s", path);
    break;
  default:
    snprintf(error_msg_buffer, sizeof(error_msg_buffer), "Failed to open for writing: %s (%s)", path,
             platform_strerror(errno));
    break;
  }
  return error_msg_buffer;
}
References platform_strerror().
Referenced by update_check_save_cache().
platform_cleanup_binary_path_cache()
void platform_cleanup_binary_path_cache (void)
Definition at line 109 of file filesystem.c.
{
  if (!lifecycle_shutdown(&g_cache_lc)) {
    return;
  }
  if (g_bin_path_cache) {
    rwlock_wrlock(&g_cache_rwlock);
    bin_cache_entry_t *entry, *tmp;
    HASH_ITER(hh, g_bin_path_cache, entry, tmp) {
      HASH_DELETE(hh, g_bin_path_cache, entry);
      free_cache_entry(entry);
    }
    rwlock_wrunlock(&g_cache_rwlock);
    rwlock_destroy(&g_cache_rwlock);
    g_bin_path_cache = NULL;
  }
}
References lifecycle_shutdown().
Referenced by asciichat_shared_destroy().
platform_get_executable_path()
bool platform_get_executable_path (char * exe_path, size_t path_size)
Get the path to the current executable.
Parameters
exe_path Buffer to store the executable path
path_size Size of the buffer
Returns
true on success, false on failure
Definition at line 185 of file filesystem.c.
{
  if (!exe_path || path_size == 0) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: exe_path=%p, path_size=%zu", (void *)exe_path, path_size);
    return false;
  }
#ifdef _WIN32
  DWORD len = GetModuleFileNameA(NULL, exe_path, (DWORD)path_size);
  if (len == 0) {
    SET_ERRNO_SYS(ERROR_INVALID_STATE, "GetModuleFileNameA failed: error code %lu", GetLastError());
    return false;
  }
  if (len >= path_size) {
    SET_ERRNO(ERROR_BUFFER_OVERFLOW,
              "Executable path exceeds buffer size (path length >= %zu bytes, buffer size = %zu bytes)", (size_t)len,
              path_size);
    return false;
  }
  return true;
#elif defined(__linux__)
  ssize_t len = readlink("/proc/self/exe", exe_path, path_size - 1);
  if (len < 0) {
    SET_ERRNO_SYS(ERROR_INVALID_STATE, "readlink(\"/proc/self/exe\") failed: %s", SAFE_STRERROR(errno));
    return false;
  }
  if ((size_t)len >= path_size - 1) {
    SET_ERRNO(ERROR_BUFFER_OVERFLOW,
              "Executable path exceeds buffer size (path length >= %zu bytes, buffer size = %zu bytes)", (size_t)len,
              path_size);
    return false;
  }
  exe_path[len] = '\0';
  return true;
#elif defined(__APPLE__)
  uint32_t bufsize = (uint32_t)path_size;
  int result = _NSGetExecutablePath(exe_path, &bufsize);
  if (result != 0) {
    SET_ERRNO(ERROR_BUFFER_OVERFLOW, "_NSGetExecutablePath failed: path requires %u bytes, buffer size = %zu bytes",
              bufsize, path_size);
    return false;
  }
  return true;
#else
  SET_ERRNO(ERROR_GENERAL, "Unsupported platform - cannot get executable path");
  return false;
#endif
}
platform_is_binary_in_path()
bool platform_is_binary_in_path (const char * bin_name)
Definition at line 129 of file filesystem.c.
{
  if (!bin_name || bin_name[0] == '\0') {
    return false;
  }
  init_cache_once();
  if (!lifecycle_is_initialized(&g_cache_lc)) {
    SET_ERRNO(ERROR_INVALID_STATE, "Binary PATH cache not initialized, checking directly (this should never happen)");
    return check_binary_in_path_uncached(bin_name);
  }
  rwlock_rdlock(&g_cache_rwlock);
  bin_cache_entry_t *entry = NULL;
  HASH_FIND_STR(g_bin_path_cache, bin_name, entry);
  rwlock_rdunlock(&g_cache_rwlock);
  if (entry) {
    log_dev("Binary '%s' %s in PATH (%s)", bin_name, colored_string(LOG_COLOR_INFO, "found"),
            colored_string(LOG_COLOR_WARN, "cached"));
    return entry->in_path;
  }
  bool found = check_binary_in_path_uncached(bin_name);
  entry = SAFE_MALLOC(sizeof(bin_cache_entry_t), bin_cache_entry_t *);
  if (!entry) {
    SET_ERRNO(ERROR_MEMORY, "Failed to allocate cache entry");
    return found;
  }
  entry->bin_name = platform_strdup(bin_name);
  if (!entry->bin_name) {
    SET_ERRNO(ERROR_MEMORY, "Failed to duplicate binary name");
    SAFE_FREE(entry);
    return found;
  }
  entry->in_path = found;
  rwlock_wrlock(&g_cache_rwlock);
  HASH_ADD_KEYPTR(hh, g_bin_path_cache, entry->bin_name, strlen(entry->bin_name), entry);
  rwlock_wrunlock(&g_cache_rwlock);
  char *found_notfound_str =
      found ? colored_string(LOG_COLOR_INFO, "found") : colored_string(LOG_COLOR_ERROR, "NOT found");
  log_dev("Binary '%s' %s in PATH", bin_name, found_notfound_str);
  return found;
}
References bin_cache_entry_t::bin_name, check_binary_in_path_uncached(), colored_string(), bin_cache_entry_t::in_path, lifecycle_is_initialized(), and platform_strdup().