ascii-chat: formatter.c File Reference
formatter.c File Reference
Groff/troff formatting utilities for man page generation.
Functions
const char * manpage_fmt_escape_groff (const char *str)
void manpage_fmt_write_section (FILE *f, const char *section_name)
void manpage_fmt_write_blank_line (FILE *f)
void manpage_fmt_write_bold (FILE *f, const char *text)
void manpage_fmt_write_italic (FILE *f, const char *text)
void manpage_fmt_write_tagged_paragraph (FILE *f)
void manpage_fmt_write_text (FILE *f, const char *text)
void manpage_fmt_write_title (FILE *f, const char *program_name, const char *mode_name, const char *brief_description)
Detailed Description
Groff/troff formatting utilities for man page generation.
Provides utilities for generating properly formatted groff/troff output for man pages.
Definition in file formatter.c.
Function Documentation
manpage_fmt_escape_groff()
const char * manpage_fmt_escape_groff (const char * str)
Definition at line 21 of file formatter.c.
{
  // For simplicity, we'll just return the string as-is
  // In a more robust implementation, we'd escape special characters
  // But for man page content, most strings don't have problematic characters
  return str ? str : "";
}
Referenced by manpage_fmt_write_title().
manpage_fmt_write_blank_line()
void manpage_fmt_write_blank_line (FILE * f)
Definition at line 35 of file formatter.c.
{
  if (!f) {
    return;
  }
  fprintf(f, "\n");
}
Referenced by options_config_generate_manpage_template().
manpage_fmt_write_bold()
void manpage_fmt_write_bold (FILE * f, const char * text)
Definition at line 42 of file formatter.c.
{
  if (!f || !text) {
    return;
  }
  fprintf(f, ".B %s\n", text);
}
manpage_fmt_write_italic()
void manpage_fmt_write_italic (FILE * f, const char * text)
Definition at line 49 of file formatter.c.
{
  if (!f || !text) {
    return;
  }
  fprintf(f, ".I %s\n", text);
}
manpage_fmt_write_section()
void manpage_fmt_write_section (FILE * f, const char * section_name)
Definition at line 28 of file formatter.c.
{
  if (!f || !section_name) {
    return;
  }
  fprintf(f, ".SH %s\n", section_name);
}
Referenced by options_config_generate_manpage_template().
manpage_fmt_write_tagged_paragraph()
void manpage_fmt_write_tagged_paragraph (FILE * f)
Definition at line 56 of file formatter.c.
{
  if (!f) {
    return;
  }
  fprintf(f, ".TP\n");
}
manpage_fmt_write_text()
void manpage_fmt_write_text (FILE * f, const char * text)
Definition at line 63 of file formatter.c.
{
  if (!f) {
    return;
  }
  if (text) {
    fprintf(f, "%s\n", text);
  } else {
    fprintf(f, "\n");
  }
}
manpage_fmt_write_title()
void manpage_fmt_write_title (FILE * f, const char * program_name, const char * mode_name, const char * brief_description)
Definition at line 75 of file formatter.c.
{
  if (!f || !program_name || !brief_description) {
    return;
  }
  time_t now = time(NULL);
  struct tm tm_buf;
  platform_localtime(&now, &tm_buf);
  char date_str[32];
  strftime(date_str, sizeof(date_str), "%B %Y", &tm_buf);
  // Build full program name (e.g., "ascii-chat-server" or just "ascii-chat")
  char full_name[256];
  if (mode_name) {
    safe_snprintf(full_name, sizeof(full_name), "%s-%s", program_name, mode_name);
  } else {
    safe_snprintf(full_name, sizeof(full_name), "%s", program_name);
  }
  // .TH NAME SECTION DATE SOURCE MANUAL
  // Section 1 = user commands, 5 = file formats
  fprintf(f, ".TH %s 1 \"%s\" \"%s\" \"User Commands\"\n", full_name, date_str, program_name);
  fprintf(f, ".SH NAME\n");
  fprintf(f, ".B %s\n", full_name);
  fprintf(f, "\\- %s\n", manpage_fmt_escape_groff(brief_description));
  fprintf(f, "\n");
}
References manpage_fmt_escape_groff(), platform_localtime(), and safe_snprintf().
Referenced by options_config_generate_manpage_template().