ascii-chat: fps_counter.c File Reference
fps_counter.c File Reference
Session
FPS counter implementation using rolling-window timestamp buffer.
Data Structures
struct fps_counter_s
FPS counter state.
Macros
#define FPS_WINDOW_SIZE 30
Number of frames to average over.
Functions
fps_counter_t * fps_counter_create (void)
void fps_counter_destroy (fps_counter_t *counter)
void fps_counter_tick (fps_counter_t *counter)
float fps_counter_get (fps_counter_t *counter)
Detailed Description
FPS counter implementation using rolling-window timestamp buffer.
Definition in file fps_counter.c.
Macro Definition Documentation
FPS_WINDOW_SIZE
#define FPS_WINDOW_SIZE 30
Number of frames to average over.
Definition at line 15 of file fps_counter.c.
Referenced by fps_counter_get(), and fps_counter_tick().
Function Documentation
fps_counter_create()
fps_counter_t * fps_counter_create (void)
Definition at line 33 of file fps_counter.c.
{
  fps_counter_t *counter = SAFE_CALLOC(1, sizeof(fps_counter_t), fps_counter_t *);
  if (!counter) {
    return NULL;
  }
  // Initialize circular buffer pointers
  counter->head = 0;
  counter->count = 0;
  memset(counter->frame_times, 0, sizeof(counter->frame_times));
  return counter;
}
Referenced by session_display_create().
fps_counter_destroy()
void fps_counter_destroy (fps_counter_t * counter)
Definition at line 47 of file fps_counter.c.
{
  if (counter) {
    SAFE_FREE(counter);
  }
}
Referenced by session_display_destroy().
fps_counter_get()
float fps_counter_get (fps_counter_t * counter)
Definition at line 74 of file fps_counter.c.
{
  if (!counter || counter->count < 2) {
    return 0.0f;
  }
  // Find indices of oldest and newest timestamps in the buffer
  int oldest_idx = (counter->head - counter->count + FPS_WINDOW_SIZE) % FPS_WINDOW_SIZE;
  int newest_idx = (counter->head - 1 + FPS_WINDOW_SIZE) % FPS_WINDOW_SIZE;
  // Get the elapsed time between oldest and newest frames
  uint64_t oldest_time = counter->frame_times[oldest_idx];
  uint64_t newest_time = counter->frame_times[newest_idx];
  uint64_t elapsed_ns = newest_time - oldest_time;
  // Avoid division by zero
  if (elapsed_ns == 0) {
    return 0.0f;
  }
  // FPS = (number of frames) / elapsed_time
  // We have (count - 1) frames across the elapsed time
  // (count - 1) frames means count timestamps, so count-1 intervals
  return (float)(counter->count - 1) * 1e9f / (float)elapsed_ns;
}
References FPS_WINDOW_SIZE.
Referenced by session_display_render_fps_overlay().
fps_counter_tick()
void fps_counter_tick (fps_counter_t * counter)
Definition at line 57 of file fps_counter.c.
{
  if (!counter) {
    return;
  }
  // Record current time at head position
  counter->frame_times[counter->head] = time_get_ns();
  // Advance head pointer with wraparound
  counter->head = (counter->head + 1) % FPS_WINDOW_SIZE;
  // Track how many valid entries we have (up to FPS_WINDOW_SIZE)
  if (counter->count < FPS_WINDOW_SIZE) {
    counter->count++;
  }
}
References FPS_WINDOW_SIZE, and time_get_ns().
Referenced by session_display_write_ascii().