ascii-chat: frame_buffer.c File Reference
frame_buffer.c File Reference
Buffered terminal frame rendering implementation.
Data Structures
struct frame_buffer
Frame buffer structure.
Functions
frame_buffer_t * frame_buffer_create (int rows, int cols)
void frame_buffer_destroy (frame_buffer_t *buf)
void frame_buffer_reset (frame_buffer_t *buf)
void frame_buffer_append (frame_buffer_t *buf, const char *str, size_t len)
void frame_buffer_printf (frame_buffer_t *buf, const char *fmt,...)
void frame_buffer_cursor_home (frame_buffer_t *buf)
void frame_buffer_clear_screen (frame_buffer_t *buf)
void frame_buffer_flush (frame_buffer_t *buf)
void frame_buffer_set_screen_output_fd (int fd)
int frame_buffer_get_screen_output_fd (void)
size_t frame_buffer_get_length (const frame_buffer_t *buf)
const char * frame_buffer_get_content (const frame_buffer_t *buf)
void frame_buffer_render_border (frame_buffer_t *buf, int cols, const char *color)
int frame_buffer_render_centered (frame_buffer_t *buf, const char *text, int cols)
Detailed Description
Buffered terminal frame rendering implementation.
Accumulates terminal output into a growable buffer and flushes atomically.
Definition in file frame_buffer.c.
Function Documentation
frame_buffer_append()
void frame_buffer_append (frame_buffer_t * buf, const char * str, size_t len)
Definition at line 66 of file frame_buffer.c.
{
  if (!buf || !str || len == 0) {
    return;
  }
  // Grow buffer if needed
  if (buf->len + len > buf->capacity) {
    size_t new_capacity = buf->capacity * 2;
    while (new_capacity < buf->len + len) {
      new_capacity *= 2;
    }
    char *new_data = SAFE_MALLOC(new_capacity, char *);
    if (!new_data) {
      return; // Failed to grow, silently ignore
    }
    if (buf->len > 0 && buf->data) {
      memcpy(new_data, buf->data, buf->len);
    }
    SAFE_FREE(buf->data);
    buf->data = new_data;
    buf->capacity = new_capacity;
  }
  // Append the data
  memcpy(buf->data + buf->len, str, len);
  buf->len += len;
}
Referenced by frame_buffer_clear_screen(), and frame_buffer_cursor_home().
frame_buffer_clear_screen()
void frame_buffer_clear_screen (frame_buffer_t * buf)
Definition at line 143 of file frame_buffer.c.
{
  if (!buf) {
    return;
  }
  // Combine clear screen and home in one operation
  frame_buffer_append(buf, "\033[2J\033[H", 8);
}
References frame_buffer_append().
Referenced by terminal_screen_render().
frame_buffer_create()
frame_buffer_t * frame_buffer_create (int rows, int cols)
Definition at line 28 of file frame_buffer.c.
{
  frame_buffer_t *buf = SAFE_MALLOC(sizeof(frame_buffer_t), frame_buffer_t *);
  if (!buf) {
    return NULL;
  }
  // Initial capacity: rows * cols * 16 to account for ANSI codes
  size_t initial_capacity = (rows > 0 && cols > 0) ? (size_t)rows * cols * 16 : 4096;
  buf->data = SAFE_MALLOC(initial_capacity, char *);
  if (!buf->data) {
    SAFE_FREE(buf);
    return NULL;
  }
  buf->len = 0;
  buf->capacity = initial_capacity;
  return buf;
}
Referenced by terminal_screen_render().
frame_buffer_cursor_home()
void frame_buffer_cursor_home (frame_buffer_t * buf)
Definition at line 135 of file frame_buffer.c.
{
  if (!buf) {
    return;
  }
  frame_buffer_append(buf, "\033[H", 3);
}
References frame_buffer_append().
Referenced by terminal_screen_render().
frame_buffer_destroy()
void frame_buffer_destroy (frame_buffer_t * buf)
Definition at line 49 of file frame_buffer.c.
{
  if (!buf) {
    return;
  }
  SAFE_FREE(buf->data);
  SAFE_FREE(buf);
}
Referenced by terminal_screen_cleanup(), and terminal_screen_render().
frame_buffer_flush()
void frame_buffer_flush (frame_buffer_t * buf)
Definition at line 155 of file frame_buffer.c.
{
  if (!buf || buf->len == 0 || !buf->data) {
    return;
  }
  // Write entire buffer to configured FD in one atomic operation
  // Uses the terminal screen output FD which may be stderr when piped
  platform_write_all(g_terminal_screen_output_fd, buf->data, buf->len);
}
References platform_write_all().
Referenced by terminal_screen_render().
frame_buffer_get_content()
const char * frame_buffer_get_content (const frame_buffer_t * buf)
Definition at line 180 of file frame_buffer.c.
{
  if (!buf || !buf->data) {
    return NULL;
  }
  return buf->data;
}
Referenced by terminal_screen_render().
frame_buffer_get_length()
size_t frame_buffer_get_length (const frame_buffer_t * buf)
Definition at line 173 of file frame_buffer.c.
{
  if (!buf) {
    return 0;
  }
  return buf->len;
}
Referenced by terminal_screen_render().
frame_buffer_get_screen_output_fd()
int frame_buffer_get_screen_output_fd (void)
Definition at line 169 of file frame_buffer.c.
{
  return g_terminal_screen_output_fd;
}
Referenced by terminal_screen_render().
frame_buffer_printf()
void frame_buffer_printf (frame_buffer_t * buf, const char * fmt, ...)
Definition at line 97 of file frame_buffer.c.
{
  if (!buf || !fmt) {
    return;
  }
  // Ensure we have space for a formatted string
  // Start with a reasonable buffer size
  size_t remaining = buf->capacity - buf->len;
  if (remaining < 256) {
    // Grow buffer to have at least 512 bytes of space
    size_t new_capacity = buf->capacity + 512;
    char *new_data = SAFE_MALLOC(new_capacity, char *);
    if (!new_data) {
      return;
    }
    if (buf->len > 0 && buf->data) {
      memcpy(new_data, buf->data, buf->len);
    }
    SAFE_FREE(buf->data);
    buf->data = new_data;
    buf->capacity = new_capacity;
    remaining = buf->capacity - buf->len;
  }
  // Format the string into the buffer
  va_list args;
  va_start(args, fmt);
  int written = vsnprintf(buf->data + buf->len, remaining, fmt, args);
  va_end(args);
  if (written > 0 && written < (int)remaining) {
    buf->len += (size_t)written;
  }
  // If vsnprintf failed or truncated, we silently ignore (buffer may be full)
}
References args.
Referenced by frame_buffer_render_border(), frame_buffer_render_centered(), and terminal_screen_render().
frame_buffer_render_border()
void frame_buffer_render_border (frame_buffer_t * buf, int cols, const char * color)
Definition at line 187 of file frame_buffer.c.
{
  if (!buf || cols <= 0) {
    return;
  }
  if (color) {
    frame_buffer_printf(buf, "%s━", color);
  } else {
    frame_buffer_printf(buf, "━");
  }
  for (int i = 1; i < cols - 1; i++) {
    frame_buffer_printf(buf, "━");
  }
  if (color) {
    frame_buffer_printf(buf, "\033[0m");
  }
  frame_buffer_printf(buf, "\n");
}
References frame_buffer_printf().
frame_buffer_render_centered()
int frame_buffer_render_centered (frame_buffer_t * buf, const char * text, int cols)
Definition at line 206 of file frame_buffer.c.
{
  if (!buf || !text || cols <= 0) {
    return 0;
  }
  // Calculate visible width accounting for ANSI codes
  int visible_width = display_width(text);
  if (visible_width < 0) {
    visible_width = (int)strlen(text);
  }
  int padding = (cols - visible_width) / 2;
  if (padding < 0) {
    padding = 0;
  }
  for (int i = 0; i < padding; i++) {
    frame_buffer_printf(buf, " ");
  }
  frame_buffer_printf(buf, "%s\n", text);
  return padding;
}
References display_width(), and frame_buffer_printf().
frame_buffer_reset()
void frame_buffer_reset (frame_buffer_t * buf)
Definition at line 58 of file frame_buffer.c.
{
  if (!buf) {
    return;
  }
  buf->len = 0;
}
Referenced by terminal_screen_render().
frame_buffer_set_screen_output_fd()
void frame_buffer_set_screen_output_fd (int fd)
Definition at line 165 of file frame_buffer.c.
{
  g_terminal_screen_output_fd = fd;
}
Referenced by terminal_screen_set_output_fd().