ascii-chat: Session
Session
Files
file fps_counter.c
FPS counter implementation using rolling-window timestamp buffer.
file keyboard_help.c
Keyboard help overlay TUI rendering implementation.
file splash.c
Intro and status screen display implementation with animated rainbow effects.
file audio.c
🔊 Session-level audio coordination implementation
file audio.h
🔊 Session-level audio coordination wrapper
file capture.c
📹 Unified media capture implementation
file capture.h
📹 Unified media capture abstraction for session-based video sources
file client_like.c
Shared initialization and teardown for client-like modes.
file client_like.h
Shared initialization and teardown for client-like modes (mirror, client, discovery).
file consensus.c
Mode-agnostic ring consensus abstraction implementation.
file consensus.h
Mode-agnostic ring consensus abstraction for session discovery.
file consensus_integration.c
Integration helpers for session consensus in discovery mode.
file consensus_integration.h
Integration helpers for session consensus across modes.
file display.c
🖥️ Unified terminal display implementation
file display.h
🖥️ Unified terminal display abstraction for session-based rendering
file host.c
🏠 Server-side session hosting implementation
file host.h
🏠 Server-side session hosting abstraction
file keyboard_handler.c
Keyboard input handler implementation.
file keyboard_handler.h
🎮 Keyboard input handler for interactive session controls
file participant.c
👤 Client-side session participation implementation
file participant.h
👤 Client-side session participation abstraction
file pipeline.c
Three-thread render pipeline implementation.
file pipeline.h
Three-thread render pipeline: capture → display/encode.
file render.c
Unified render loop implementation for all display modes.
file render.h
Centralized render loop abstraction for all display modes.
file server_like.c
Implementation of server_like abstraction for unified server mode lifecycle.
file server_like.h
Shared initialization and teardown for server-like modes (server, discovery-service).
file settings.c
⚙️ Session settings serialization implementation
file settings.h
⚙️ Session settings serialization and synchronization
Data Structures
struct session_capture_config_t
Configuration for session capture context.
struct session_display_config_t
Configuration for session display context.
struct session_host_client_info_t
Client information structure.
struct session_host_callbacks_t
Callback function prototypes for session host events.
struct session_host_config_t
Configuration for session host.
struct session_participant_callbacks_t
Callback function prototypes for session participant events.
struct session_participant_config_t
Configuration for session participant.
struct session_server_like_config
struct session_settings_t
Session settings for transmission between peers.
Macros
#define SESSION_SETTINGS_VERSION 1
Current session settings structure version.
#define SESSION_SETTINGS_SERIALIZED_SIZE 64
Size of serialized session settings in bytes.
Typedefs
typedef struct session_audio_ctx session_audio_ctx_t
Opaque session audio context handle.
typedef bool(* session_capture_should_exit_fn) (void *user_data)
Callback type to check if initialization should be cancelled.
typedef struct session_capture_ctx session_capture_ctx_t
Opaque session capture context handle.
typedef bool(* session_display_should_exit_fn) (void *user_data)
Callback type to check if initialization should be cancelled.
typedef struct session_display_ctx session_display_ctx_t
Opaque session display context handle.
typedef struct session_host session_host_t
Internal session host structure.
typedef struct acip_transport acip_transport_t
Forward declaration of ACIP transport.
typedef struct session_display_ctx session_display_ctx_t
Internal session display context structure.
typedef struct session_participant session_participant_t
Internal session participant structure.
typedef struct acip_transport acip_transport_t
Forward declaration of ACIP transport.
typedef bool(* session_should_exit_fn) (void *user_data)
Exit condition callback type.
typedef image_t *(* session_capture_fn) (void *user_data)
Capture callback for event-driven frame source.
typedef void(* session_sleep_for_frame_fn) (void *user_data)
Sleep callback for custom frame timing.
typedef void(* session_keyboard_handler_fn) (session_capture_ctx_t *capture, int key, void *user_data)
Keyboard input handler callback type.
typedef asciichat_error_t(* session_server_like_init_fn) (void *user_data)
typedef asciichat_error_t(* session_server_like_run_fn) (void *user_data)
typedef void(* session_server_like_interrupt_fn) (void)
typedef void(* session_server_like_status_fn) (void *user_data, ui_status_t *out_status)
typedef struct session_server_like_config session_server_like_config_t
Functions
session_audio_ctx_t * session_audio_create (bool is_host)
Create a new session audio context.
void session_audio_destroy (session_audio_ctx_t *ctx)
Destroy session audio context and free resources.
asciichat_error_t session_audio_start_capture (session_audio_ctx_t *ctx)
Start audio capture (microphone input).
asciichat_error_t session_audio_start_playback (session_audio_ctx_t *ctx)
Start audio playback (speaker output).
asciichat_error_t session_audio_start_duplex (session_audio_ctx_t *ctx)
Start full-duplex audio (simultaneous capture and playback).
void session_audio_stop (session_audio_ctx_t *ctx)
Stop all audio streams.
bool session_audio_is_running (session_audio_ctx_t *ctx)
Check if audio is currently running.
size_t session_audio_read_captured (session_audio_ctx_t *ctx, float *buffer, size_t num_samples)
Read captured audio samples.
asciichat_error_t session_audio_write_playback (session_audio_ctx_t *ctx, const float *buffer, size_t num_samples)
Write audio samples for playback.
asciichat_error_t session_audio_add_source (session_audio_ctx_t *ctx, uint32_t source_id)
Add an audio source for mixing (host only).
void session_audio_remove_source (session_audio_ctx_t *ctx, uint32_t source_id)
Remove an audio source from mixing (host only).
asciichat_error_t session_audio_write_source (session_audio_ctx_t *ctx, uint32_t source_id, const float *samples, size_t num_samples)
Write audio samples from a specific source (host only).
size_t session_audio_mix_excluding (session_audio_ctx_t *ctx, uint32_t exclude_id, float *output, size_t num_samples)
Mix all sources except one and return the result (host only).
session_capture_ctx_t * session_mirror_capture_create (const session_capture_config_t *config)
Create a new session capture context.
session_capture_ctx_t * session_network_capture_create (uint32_t target_fps)
Create network mode capture context without media source.
session_capture_ctx_t * session_capture_create (const session_capture_config_t *config)
Legacy function - creates either mirror or network capture based on options.
void session_capture_destroy (session_capture_ctx_t *ctx)
Destroy session capture context and free resources.
image_t * session_capture_read_frame (session_capture_ctx_t *ctx)
Read the next video frame from the capture source.
image_t * session_capture_process_for_transmission (session_capture_ctx_t *ctx, image_t *frame)
Process a frame for network transmission (resize if needed).
void session_capture_sleep_for_fps (session_capture_ctx_t *ctx)
Sleep to maintain target frame rate.
bool session_capture_at_end (session_capture_ctx_t *ctx)
Check if capture source has reached end of stream.
bool session_capture_is_valid (session_capture_ctx_t *ctx)
Check if capture context is initialized and valid.
double session_capture_get_current_fps (session_capture_ctx_t *ctx)
Get the current FPS being achieved by the capture source.
uint32_t session_capture_get_target_fps (session_capture_ctx_t *ctx)
Get the target FPS configured for this capture context.
bool session_capture_has_audio (session_capture_ctx_t *ctx)
Check if capture source has audio available.
size_t session_capture_read_audio (session_capture_ctx_t *ctx, float *buffer, size_t num_samples)
Read audio samples from capture source.
bool session_capture_using_file_audio (session_capture_ctx_t *ctx)
Check if currently using file audio vs microphone fallback.
void * session_capture_get_media_source (session_capture_ctx_t *ctx)
Get the underlying media source from capture context.
terminal_fd_reader_t * session_client_like_get_stdin_reader (void)
session_display_ctx_t * session_display_create (const session_display_config_t *config)
Create a new session display context.
void session_display_destroy (session_display_ctx_t *ctx)
Destroy session display context and free resources.
void session_display_set_stdin_reader (session_display_ctx_t *ctx, void *reader)
Set stdin frame reader for ASCII-to-video rendering.
bool session_display_has_tty (session_display_ctx_t *ctx)
Check if display has a TTY (terminal) available.
const terminal_capabilities_t * session_display_get_caps (session_display_ctx_t *ctx)
Get detected terminal capabilities.
const char * session_display_get_palette_chars (session_display_ctx_t *ctx)
Get the palette characters string.
size_t session_display_get_palette_len (session_display_ctx_t *ctx)
Get the palette character count.
const char * session_display_get_luminance_palette (session_display_ctx_t *ctx)
Get the luminance mapping palette.
int session_display_get_tty_fd (session_display_ctx_t *ctx)
Get the TTY file descriptor.
void * session_display_get_stdin_reader (session_display_ctx_t *ctx)
Get the stdin frame reader for ASCII-to-video rendering.
bool session_display_has_render_file (session_display_ctx_t *ctx)
Check if display has render-file configured.
uint32_t session_display_get_render_fps (session_display_ctx_t *ctx)
Get the render FPS configured for file output.
void session_display_set_render_fps (session_display_ctx_t *ctx, uint32_t fps)
Set the render FPS for file output encoding.
bool session_display_has_first_frame (session_display_ctx_t *ctx)
Check if the display has rendered its first frame.
void session_display_reset_first_frame (session_display_ctx_t *ctx)
Reset the first frame flag to allow splash screen to show again on next render.
char * session_display_convert_to_ascii (session_display_ctx_t *ctx, const image_t *image)
Convert an image to ASCII art using display context and command-line options.
void session_display_write_ascii (session_display_ctx_t *ctx, const char *frame_data)
Write ASCII frame to terminal only (no encoding).
void session_display_encode_frame (session_display_ctx_t *ctx, const image_t *image, uint64_t captured_ns)
Encode frame to render-file (FFmpeg only, no terminal output).
void session_display_render_frame (session_display_ctx_t *ctx, const char *frame_data)
Render an ASCII frame to the terminal.
void session_display_write_raw (session_display_ctx_t *ctx, const char *data, size_t len)
Render raw bytes to the terminal without frame processing.
void session_display_render_fps_overlay (session_display_ctx_t *ctx)
Render FPS counter overlay in top-right corner.
void session_display_set_snapshot_actual_duration (session_display_ctx_t *ctx, double actual_duration_sec)
Set the actual wall-clock duration for snapshot mode frame timing.
void session_display_reset (session_display_ctx_t *ctx)
Reset terminal to default state.
void session_display_clear (session_display_ctx_t *ctx)
Clear the terminal screen.
void session_display_cursor_home (session_display_ctx_t *ctx)
Move cursor to home position (top-left).
bool session_display_has_audio_playback (session_display_ctx_t *ctx)
Check if display has audio playback configured.
asciichat_error_t session_display_write_audio (session_display_ctx_t *ctx, const float *buffer, size_t num_samples)
Write audio samples to playback buffer.
session_host_t * session_host_create (const session_host_config_t *config)
Create a new session host.
void session_host_destroy (session_host_t *host)
Destroy session host and free resources.
asciichat_error_t session_host_start (session_host_t *host)
Start accepting client connections.
void session_host_stop (session_host_t *host)
Stop accepting connections and disconnect all clients.
bool session_host_is_running (session_host_t *host)
Check if host is running.
uint32_t session_host_add_client (session_host_t *host, socket_t socket, const char *ip, int port)
Add a client from an accepted socket.
uint32_t session_host_add_memory_participant (session_host_t *host)
Add a memory participant (host's own media).
asciichat_error_t session_host_inject_frame (session_host_t *host, uint32_t participant_id, const image_t *frame)
Inject a video frame from memory participant.
asciichat_error_t session_host_inject_audio (session_host_t *host, uint32_t participant_id, const float *samples, size_t count)
Inject audio samples from memory participant.
asciichat_error_t session_host_remove_client (session_host_t *host, uint32_t client_id)
Remove a client by ID.
asciichat_error_t session_host_find_client (session_host_t *host, uint32_t client_id, session_host_client_info_t *info)
Find a client by ID.
int session_host_get_client_count (session_host_t *host)
Get number of connected clients.
int session_host_get_client_ids (session_host_t *host, uint32_t *ids, int max_ids)
Get list of all connected client IDs.
asciichat_error_t session_host_broadcast_frame (session_host_t *host, const char *frame)
Broadcast ASCII frame to all clients.
asciichat_error_t session_host_send_frame (session_host_t *host, uint32_t client_id, const char *frame)
Send ASCII frame to a specific client.
asciichat_error_t session_host_start_render (session_host_t *host)
Start media rendering thread (video mixing and audio distribution).
void session_host_stop_render (session_host_t *host)
Stop media rendering thread.
asciichat_error_t session_host_set_client_transport (session_host_t *host, uint32_t client_id, acip_transport_t *transport)
Set an alternative transport for a specific client in the host.
acip_transport_t * session_host_get_client_transport (session_host_t *host, uint32_t client_id)
Get the current transport for a specific client in the host.
bool session_host_client_has_transport (session_host_t *host, uint32_t client_id)
Check if a specific client has an active alternative transport.
void session_handle_keyboard_input (session_capture_ctx_t *capture, session_display_ctx_t *display, keyboard_key_t key)
Handle keyboard input in a session.
session_participant_t * session_participant_create (const session_participant_config_t *config)
Create a new session participant.
void session_participant_destroy (session_participant_t *p)
Destroy session participant and free resources.
asciichat_error_t session_participant_connect (session_participant_t *p)
Connect to session server.
void session_participant_disconnect (session_participant_t *p)
Disconnect from session server.
bool session_participant_is_connected (session_participant_t *p)
Check if participant is connected.
uint32_t session_participant_get_client_id (session_participant_t *p)
Get assigned client ID.
asciichat_error_t session_participant_start_video (session_participant_t *p)
Start video capture and streaming.
void session_participant_stop_video (session_participant_t *p)
Stop video capture and streaming.
bool session_participant_is_video_active (session_participant_t *p)
Check if video is streaming.
asciichat_error_t session_participant_start_audio (session_participant_t *p)
Start audio capture and streaming.
void session_participant_stop_audio (session_participant_t *p)
Stop audio capture and streaming.
bool session_participant_is_audio_active (session_participant_t *p)
Check if audio is streaming.
asciichat_error_t session_participant_get_settings (session_participant_t *p, session_settings_t *settings)
Get current session settings.
asciichat_error_t session_participant_request_settings (session_participant_t *p, const session_settings_t *settings)
Request session settings update (if permitted).
asciichat_error_t session_participant_start_video_capture (session_participant_t *p)
Start video capture and transmission to host.
void session_participant_stop_video_capture (session_participant_t *p)
Stop video capture and transmission.
asciichat_error_t session_participant_start_audio_capture (session_participant_t *p)
Start audio capture and transmission to host.
void session_participant_stop_audio_capture (session_participant_t *p)
Stop audio capture and transmission.
socket_t session_participant_get_socket (session_participant_t *p)
Get the socket from a participant context.
asciichat_error_t session_participant_set_transport (session_participant_t *p, acip_transport_t *transport)
Set an alternative transport for the participant.
acip_transport_t * session_participant_get_transport (session_participant_t *p)
Get the current transport for the participant.
bool session_participant_has_transport (session_participant_t *p)
Check if participant has an active alternative transport.
asciichat_error_t session_render_loop (session_capture_ctx_t *capture, session_display_ctx_t *display, session_should_exit_fn should_exit, session_capture_fn capture_cb, session_sleep_for_frame_fn sleep_cb, session_keyboard_handler_fn keyboard_handler, void *user_data)
Unified render loop for all display modes.
asciichat_error_t session_server_like_run (const session_server_like_config_t *config)
void session_settings_init (session_settings_t *settings)
Initialize session settings to defaults.
asciichat_error_t session_settings_serialize (const session_settings_t *settings, uint8_t *buffer, size_t *len)
Serialize session settings to binary buffer.
asciichat_error_t session_settings_deserialize (const uint8_t *buffer, size_t len, session_settings_t *settings)
Deserialize session settings from binary buffer.
asciichat_error_t session_settings_from_options (session_settings_t *settings)
Populate settings from current global options.
asciichat_error_t session_settings_apply_to_options (const session_settings_t *settings)
Apply settings to global options.
bool session_settings_needs_update (uint32_t local_version, uint32_t remote_version)
Check if settings need update based on versions.
bool session_settings_equal (const session_settings_t *a, const session_settings_t *b)
Compare two settings structures for equality.
Detailed Description
This header provides a thin wrapper around the lib/audio/ system for session-level audio coordination. It handles the differences between host (mixing) and participant (simple capture/playback) modes.
CORE FEATURES:
Unified API for both host and participant audio handling
Host-only audio mixing for multi-participant sessions
Source management for tracking participant audio streams
Clean startup/shutdown coordination
USAGE:
// Create audio context for a participant
session_audio_ctx_t *ctx = session_audio_create(false);
// Start capture and playback
session_audio_start_capture(ctx);
session_audio_start_playback(ctx);
// Cleanup
session_audio_destroy(ctx);
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
This header provides a unified interface for media capture that abstracts over webcam, file, stdin, and test pattern sources. It is designed to be reusable across different modes (client, mirror, and discovery mode).
CORE FEATURES:
Unified API for all media source types (webcam, file, stdin, test)
Configurable frame rate with adaptive sleep
Optional frame resizing for network transmission
FPS tracking and reporting
Loop support for file sources
USAGE:
// Create capture context for webcam at 60 FPS
session_capture_config_t config = {
    .type = MEDIA_SOURCE_WEBCAM,
    .path = "0",
    .target_fps = 60,
    .loop = false,
    .resize_for_network = false
};
session_capture_ctx_t *ctx = session_capture_create(&config);
// Read and process frames
while (!done) {
    image_t *frame = session_capture_read_frame(ctx);
    if (frame) {
        // Process frame...
    }
    session_capture_sleep_for_fps(ctx);
}
// Cleanup
session_capture_destroy(ctx);
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
This header provides a unified interface for terminal display that abstracts TTY detection, palette initialization, and frame rendering. It is designed to be reusable across different modes (client, mirror, and discovery mode).
CORE FEATURES:
TTY detection and management
Terminal capability detection (color, UTF-8)
Palette initialization and luminance mapping
Frame rendering with RLE expansion support
Snapshot mode support for single-frame capture
USAGE:
// Create display context with color support
session_display_config_t config = {
    .snapshot_mode = false,
    .palette_type = PALETTE_STANDARD,
    .custom_palette = NULL,
    .color_mode = TERM_COLOR_AUTO
};
session_display_ctx_t *ctx = session_display_create(&config);
// Render frames
const char *frame_data = ...; // ASCII frame from server
session_display_render_frame(ctx, frame_data, false);
// Cleanup
session_display_destroy(ctx);
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
This header provides the server-side session hosting abstraction, encapsulating client management, connection acceptance, and event handling for session hosts.
CORE FEATURES:
Server lifecycle management (start, stop)
Client connection handling (add, remove, lookup)
Callback-based event notification
Encryption and authentication support
USAGE:
// Define callbacks
void on_client_join(session_host_t *h, uint32_t id, void *data) {
    printf("Client %u joined\n", id);
}
void on_frame(session_host_t *h, uint32_t id, const image_t *frame, void *data) {
    // Process video frame from client
}
// Create and start host
session_host_config_t config = {
    .port = 27224,
    .max_clients = 32,
    .callbacks = { .on_client_join = on_client_join, .on_frame_received = on_frame }
};
session_host_t *h = session_host_create(&config);
session_host_start(h);
// Run until stopped...
// Cleanup
session_host_destroy(h);
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
Provides keyboard input handling for session-level controls including:
Media playback control (play/pause, seek)
Audio control (volume, mute)
Display control (color mode, webcam flip)
Help screen toggle
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
This header provides the client-side session participation abstraction, encapsulating connection management, media streaming, and event handling for session participants.
CORE FEATURES:
Connection lifecycle management (connect, disconnect, reconnect)
Video and audio stream control
Callback-based event notification
Encryption and authentication support
USAGE:
// Define callbacks
void on_connected(session_participant_t *p, uint32_t id, void *data) {
    printf("Connected with ID %u\n", id);
}
void on_frame(session_participant_t *p, const char *frame, void *data) {
    // Render ASCII frame
}
// Create and connect
session_participant_config_t config = {
    .address = "127.0.0.1",
    .port = 27224,
    .callbacks = { .on_connected = on_connected, .on_frame_received = on_frame }
};
session_participant_t *p = session_participant_create(&config);
session_participant_connect(p);
// Start streaming
session_participant_start_video(p);
// Cleanup
session_participant_destroy(p);
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
This header provides settings structures and serialization functions for session configuration that can be transmitted between peers in discovery mode.
CORE FEATURES:
Compact binary serialization for network transmission
Version-based conflict detection
Bidirectional conversion with options system
Future-proof extensible structure with reserved bytes
USAGE:
// Create settings from current options
session_settings_t settings;
session_settings_from_options(&settings);
// Serialize for transmission
uint8_t buffer[SESSION_SETTINGS_SERIALIZED_SIZE];
size_t len;
session_settings_serialize(&settings, buffer, &len);
// Deserialize received settings
session_settings_t received;
session_settings_deserialize(buffer, len, &received);
// Check if update needed
if (session_settings_needs_update(local_version, received.version)) {
    session_settings_apply_to_options(&received);
}
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
Macro Definition Documentation
SESSION_SETTINGS_SERIALIZED_SIZE
#define SESSION_SETTINGS_SERIALIZED_SIZE 64
#include <src/common/session/settings.h>
Size of serialized session settings in bytes.
Definition at line 59 of file settings.h.
Referenced by session_settings_deserialize().
SESSION_SETTINGS_VERSION
#define SESSION_SETTINGS_VERSION 1
#include <src/common/session/settings.h>
Current session settings structure version.
Definition at line 56 of file settings.h.
Typedef Documentation
acip_transport_t [1/2]
typedef struct acip_transport acip_transport_t
#include <src/common/session/host.h>
Forward declaration of ACIP transport.
Opaque transport interface for send/receive operations. Used for WebRTC DataChannels, WebSockets, and other transports.
See also
acip_transport_t in network/acip/transport.h
Definition at line 455 of file host.h.
acip_transport_t [2/2]
typedef struct acip_transport acip_transport_t
#include <src/common/session/participant.h>
Forward declaration of ACIP transport.
Opaque transport interface for send/receive operations. Used for WebRTC DataChannels, WebSockets, and other transports.
See also
acip_transport_t in network/acip/transport.h
Definition at line 435 of file participant.h.
session_audio_ctx_t
typedef struct session_audio_ctx session_audio_ctx_t
#include <src/common/session/audio.h>
Opaque session audio context handle.
Manages audio capture, playback, and optional mixing state. Created via session_audio_create(), destroyed via session_audio_destroy().
Definition at line 56 of file src/common/session/audio.h.
session_capture_ctx_t
typedef struct session_capture_ctx session_capture_ctx_t
#include <src/common/session/capture.h>
Opaque session capture context handle.
Manages media source, FPS tracking, and adaptive sleep state. Created via session_capture_create(), destroyed via session_capture_destroy().
Definition at line 127 of file common/session/capture.h.
session_capture_fn
typedef image_t *(* session_capture_fn) (void *user_data)
#include <src/common/session/render.h>
Capture callback for event-driven frame source.
Called to obtain the next frame for rendering. Can return NULL if no frame is currently available.
Used when capture context is NULL (event-driven mode). Not called if capture context is provided (synchronous mode).
Parameters
user_data Opaque pointer provided by caller
Returns
Pointer to frame (caller must not free), or NULL if unavailable
Definition at line 59 of file common/session/render.h.
session_capture_should_exit_fn
typedef bool(* session_capture_should_exit_fn) (void *user_data)
#include <src/common/session/capture.h>
Callback type to check if initialization should be cancelled.
Called periodically during initialization to allow graceful cancellation. Should return true if initialization should stop immediately.
Parameters
user_data Opaque pointer provided by caller
Returns
true to cancel initialization, false to continue
Definition at line 71 of file common/session/capture.h.
session_display_ctx_t [1/2]
typedef struct session_display_ctx session_display_ctx_t
#include <src/client/display.h>
Opaque session display context handle.
Manages TTY state, terminal capabilities, palette, and rendering state. Created via session_display_create(), destroyed via session_display_destroy().
Definition at line 28 of file client/display.h.
session_display_ctx_t [2/2]
typedef struct session_display_ctx session_display_ctx_t
#include <src/common/session/display.c>
Internal session display context structure.
Contains all state for terminal display including TTY info, capabilities, palette, and rendering state.
session_display_should_exit_fn
typedef bool(* session_display_should_exit_fn) (void *user_data)
#include <src/common/session/display.h>
Callback type to check if initialization should be cancelled.
Called periodically during initialization to allow graceful cancellation. Should return true if initialization should stop immediately.
Parameters
user_data Opaque pointer provided by caller
Returns
true to cancel initialization, false to continue
Definition at line 66 of file common/session/display.h.
session_host_t
typedef struct session_host session_host_t
#include <src/common/session/host.c>
Internal session host structure.
Opaque session host handle.
Contains server state, client list, and callback configuration.
Manages server state, client connections, and event callbacks. Created via session_host_create(), destroyed via session_host_destroy().
session_keyboard_handler_fn
typedef void(* session_keyboard_handler_fn) (session_capture_ctx_t *capture, int key, void *user_data)
#include <src/common/session/render.h>
Keyboard input handler callback type.
Called when keyboard input is detected during render loop iteration. Allows applications to respond to interactive keyboard controls.
Parameters
capture Capture context (may be NULL for client mode)
key Keyboard key code from keyboard_read_nonblocking()
user_data Opaque pointer provided by caller
Definition at line 87 of file common/session/render.h.
session_participant_t
typedef struct session_participant session_participant_t
#include <src/common/session/participant.c>
Internal session participant structure.
Opaque session participant handle.
Contains connection state, media stream state, and callback configuration.
Manages connection state, media streams, and event callbacks. Created via session_participant_create(), destroyed via session_participant_destroy().
session_server_like_config_t
typedef struct session_server_like_config session_server_like_config_t
#include <src/common/session/server_like.h>
Configuration for session_server_like_run()
All logging, terminal, and signal settings are read automatically from GET_OPTION() inside the function. Callers only provide the callbacks and user data below.
session_server_like_init_fn
typedef asciichat_error_t(* session_server_like_init_fn) (void *user_data)
#include <src/common/session/server_like.h>
Mode-specific initialization callback.
Called once after shared setup (keepawake, logging) completes. Should create sockets, load keys, start worker threads—everything the mode needs before its main accept loop starts.
Parameters
user_data Opaque pointer from config.init_user_data
Returns
ASCIICHAT_OK, or error code to abort (cleanup still runs)
Definition at line 68 of file server_like.h.
session_server_like_interrupt_fn
typedef void(* session_server_like_interrupt_fn) (void)
#include <src/common/session/server_like.h>
Async-signal-safe interrupt callback.
Called from signal handler context (SIGINT / SIGTERM). Must only use async-signal-safe operations. Responsible for closing listening sockets to unblock the blocking run_fn (accept loop or poll).
Examples:
Server mode: close g_tcp_server listen sockets + websocket cancel
Discovery-Service mode: set g_server->tcp_server.running = false + acds_signal_exit()
Definition at line 98 of file server_like.h.
session_server_like_run_fn
typedef asciichat_error_t(* session_server_like_run_fn) (void *user_data)
#include <src/common/session/server_like.h>
Mode-specific blocking main loop.
Called after init_fn succeeds. Blocks until the server shuts down. Typical implementations:
Server mode: tcp_server_run(&g_tcp_server)
Discovery-Service mode: acds_server_run(&g_server)
Parameters
user_data Opaque pointer from config.run_user_data
Returns
ASCIICHAT_OK, or error code (cleanup always runs)
Definition at line 83 of file server_like.h.
session_server_like_status_fn
typedef void(* session_server_like_status_fn) (void *user_data, ui_status_t *out_status)
#include <src/common/session/server_like.h>
Status screen data callback.
Called at GET_OPTION(fps) Hz by the status screen thread. Should fill *out_status with current state for ui_status_display(). If NULL, the status screen is not shown even if –status-screen is set.
The callback receives a zeroed ui_status_t and must populate ALL fields it wants displayed (mode_name, addresses, port, connected_count, session_string, start_time, etc.). No static fields are inherited from the config — status_fn owns the entire ui_status_t.
Parameters
user_data Opaque pointer from config.status_user_data
out_status Output struct to populate (pre-zeroed by caller, not NULL)
Definition at line 117 of file server_like.h.
session_should_exit_fn
typedef bool(* session_should_exit_fn) (void *user_data)
#include <src/common/session/render.h>
Exit condition callback type.
Called each iteration to check if render loop should terminate. Return true to exit, false to continue.
Parameters
user_data Opaque pointer provided by caller
Returns
true if loop should exit, false to continue
Definition at line 43 of file common/session/render.h.
session_sleep_for_frame_fn
typedef void(* session_sleep_for_frame_fn) (void *user_data)
#include <src/common/session/render.h>
Sleep callback for custom frame timing.
Called to sleep/wait until the next frame is ready. Allows custom timing logic.
Used when capture context is NULL (event-driven mode). Not called if capture context is provided (synchronous mode).
Parameters
user_data Opaque pointer provided by caller
Definition at line 73 of file common/session/render.h.
Function Documentation
session_audio_add_source()
asciichat_error_t session_audio_add_source (session_audio_ctx_t * ctx, uint32_t source_id)
#include <src/common/session/audio.h>
Add an audio source for mixing (host only).
Parameters
ctx Audio context (must not be NULL, must be host context)
source_id Unique identifier for this source
Returns
ASCIICHAT_OK on success, error code on failure
Registers a new audio source for the mixer. Each participant should have a unique source_id.
Note
Only available when context was created with is_host=true.
Definition at line 225 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_audio_add_source: invalid context");
  }
  if (!ctx->is_host) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_audio_add_source: not a host context");
  }
  // Check if source already exists
  for (int i = 0; i < SESSION_AUDIO_MAX_SOURCES; i++) {
    if (ctx->sources[i].active && ctx->sources[i].source_id == source_id) {
      return ASCIICHAT_OK; // Already registered
    }
  }
  // Find empty slot
  for (int i = 0; i < SESSION_AUDIO_MAX_SOURCES; i++) {
    if (!ctx->sources[i].active) {
      ctx->sources[i].source_id = source_id;
      ctx->sources[i].active = true;
      ctx->sources[i].buffer = audio_ring_buffer_create();
      if (!ctx->sources[i].buffer) {
        ctx->sources[i].active = false;
        return SET_ERRNO(ERROR_MEMORY, "Failed to create audio buffer for source");
      }
      ctx->source_count++;
      return ASCIICHAT_OK;
    }
  }
  return SET_ERRNO(ERROR_RESOURCE_EXHAUSTED, "Maximum audio sources reached");
}
References session_audio_source_t::active, audio_ring_buffer_create(), session_audio_source_t::buffer, session_audio_ctx::initialized, session_audio_ctx::is_host, SESSION_AUDIO_MAX_SOURCES, session_audio_ctx::source_count, session_audio_source_t::source_id, and session_audio_ctx::sources.
session_audio_create()
session_audio_ctx_t * session_audio_create (bool is_host)
#include <src/common/session/audio.h>
Create a new session audio context.
Parameters
is_host true if this context is for a session host (enables mixing)
Returns
Pointer to audio context, or NULL on failure
Creates and initializes a session audio context. Hosts get audio mixing capabilities while participants only get basic capture/playback.
Note
Call session_audio_destroy() to free resources when done.
On failure, sets asciichat_errno with error details.
Definition at line 74 of file src/common/session/audio.c.
{
  // Allocate context
  session_audio_ctx_t *ctx = SAFE_CALLOC(1, sizeof(session_audio_ctx_t), session_audio_ctx_t *);
  ctx->is_host = is_host;
  ctx->running = false;
  // Initialize underlying audio context
  asciichat_error_t result = audio_init(&ctx->audio_ctx);
  if (result != ASCIICHAT_OK) {
    log_error("Failed to initialize audio context: %d", result);
    SAFE_FREE(ctx);
    return NULL;
  }
  // Initialize mixing resources for host
  if (is_host) {
    // Allocate mix buffer (enough for one audio buffer worth)
    ctx->mix_buffer_size = AUDIO_BUFFER_SIZE * 4; // Extra space for safety
    ctx->mix_buffer = SAFE_CALLOC(ctx->mix_buffer_size, sizeof(float), float *);
    // Initialize source array
    for (int i = 0; i < SESSION_AUDIO_MAX_SOURCES; i++) {
      ctx->sources[i].source_id = 0;
      ctx->sources[i].active = false;
      ctx->sources[i].buffer = NULL;
    }
    ctx->source_count = 0;
  }
  ctx->initialized = true;
  return ctx;
}
References session_audio_source_t::active, session_audio_ctx::audio_ctx, audio_init(), session_audio_source_t::buffer, session_audio_ctx::initialized, session_audio_ctx::is_host, session_audio_ctx::mix_buffer, session_audio_ctx::mix_buffer_size, session_audio_ctx::running, SESSION_AUDIO_MAX_SOURCES, session_audio_ctx::source_count, session_audio_source_t::source_id, and session_audio_ctx::sources.
Referenced by session_host_start_render(), and session_participant_start_audio_capture().
session_audio_destroy()
void session_audio_destroy (session_audio_ctx_t * ctx)
#include <src/common/session/audio.h>
Destroy session audio context and free resources.
Parameters
ctx Audio context to destroy (can be NULL)
Stops all audio streams, cleans up mixers (if host), and releases all resources. Safe to call with NULL.
Definition at line 108 of file src/common/session/audio.c.
{
  if (!ctx) {
    return;
  }
  // Stop audio if running
  if (ctx->running) {
    session_audio_stop(ctx);
  }
  // Cleanup host-specific resources
  if (ctx->is_host) {
    // Destroy source buffers
    for (int i = 0; i < SESSION_AUDIO_MAX_SOURCES; i++) {
      if (ctx->sources[i].buffer) {
        audio_ring_buffer_destroy(ctx->sources[i].buffer);
        ctx->sources[i].buffer = NULL;
      }
    }
    // Free mix buffer
    if (ctx->mix_buffer) {
      SAFE_FREE(ctx->mix_buffer);
    }
  }
  // Destroy underlying audio context
  audio_destroy(&ctx->audio_ctx);
  ctx->initialized = false;
  SAFE_FREE(ctx);
}
References session_audio_ctx::audio_ctx, audio_destroy(), audio_ring_buffer_destroy(), session_audio_source_t::buffer, session_audio_ctx::initialized, session_audio_ctx::is_host, session_audio_ctx::mix_buffer, session_audio_ctx::running, SESSION_AUDIO_MAX_SOURCES, session_audio_stop(), and session_audio_ctx::sources.
Referenced by session_host_destroy(), session_host_start_render(), session_host_stop_render(), and session_participant_destroy().
session_audio_is_running()
bool session_audio_is_running (session_audio_ctx_t * ctx)
#include <src/common/session/audio.h>
Check if audio is currently running.
Parameters
ctx Audio context (can be NULL)
Returns
true if audio is active, false otherwise
Definition at line 189 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized) {
    return false;
  }
  return ctx->running;
}
References session_audio_ctx::initialized, and session_audio_ctx::running.
session_audio_mix_excluding()
size_t session_audio_mix_excluding (session_audio_ctx_t * ctx, uint32_t exclude_id, float * output, size_t num_samples)
#include <src/common/session/audio.h>
Mix all sources except one and return the result (host only).
Parameters
ctx Audio context (must not be NULL, must be host context)
exclude_id Source ID to exclude from mix (for echo prevention)
output Output buffer for mixed audio (must not be NULL)
num_samples Number of samples to mix
Returns
Number of samples actually mixed
Mixes audio from all registered sources except exclude_id. This allows sending each participant a mix of all other participants without their own audio (preventing echo).
Note
Only available when context was created with is_host=true.
Definition at line 301 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized || !output || num_samples == 0) {
    return 0;
  }
  if (!ctx->is_host) {
    return 0;
  }
  // Initialize output to silence
  memset(output, 0, num_samples * sizeof(float));
  // Ensure we have a mix buffer
  if (!ctx->mix_buffer || num_samples > ctx->mix_buffer_size) {
    return 0;
  }
  int sources_mixed = 0;
  // Mix all active sources except the excluded one
  for (int i = 0; i < SESSION_AUDIO_MAX_SOURCES; i++) {
    if (!ctx->sources[i].active || ctx->sources[i].source_id == exclude_id) {
      continue;
    }
    if (!ctx->sources[i].buffer) {
      continue;
    }
    // Read samples from this source
    size_t samples_read = audio_ring_buffer_read(ctx->sources[i].buffer, ctx->mix_buffer, num_samples);
    if (samples_read == 0) {
      continue;
    }
    // Add to output mix
    for (size_t j = 0; j < samples_read; j++) {
      output[j] += ctx->mix_buffer[j];
    }
    sources_mixed++;
  }
  // Apply simple clipping prevention if multiple sources were mixed
  if (sources_mixed > 1) {
    float scale = 1.0f / (float)sources_mixed;
    for (size_t i = 0; i < num_samples; i++) {
      output[i] *= scale;
      // Soft clipping
      if (output[i] > 1.0f) {
        output[i] = 1.0f;
      } else if (output[i] < -1.0f) {
        output[i] = -1.0f;
      }
    }
  }
  return num_samples;
}
References session_audio_source_t::active, audio_ring_buffer_read(), session_audio_source_t::buffer, session_audio_ctx::initialized, session_audio_ctx::is_host, session_audio_ctx::mix_buffer, session_audio_ctx::mix_buffer_size, SESSION_AUDIO_MAX_SOURCES, session_audio_source_t::source_id, and session_audio_ctx::sources.
session_audio_read_captured()
size_t session_audio_read_captured (session_audio_ctx_t * ctx, float * buffer, size_t num_samples)
#include <src/common/session/audio.h>
Read captured audio samples.
Parameters
ctx Audio context (must not be NULL)
buffer Output buffer for audio samples (must not be NULL)
num_samples Maximum number of samples to read
Returns
Number of samples actually read
Reads captured audio samples from the capture ring buffer. Samples are in float format (-1.0 to 1.0 range).
Definition at line 200 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized || !buffer || num_samples == 0) {
    return 0;
  }
  asciichat_error_t result = audio_read_samples(&ctx->audio_ctx, buffer, (int)num_samples);
  if (result != ASCIICHAT_OK) {
    return 0;
  }
  return num_samples;
}
References session_audio_ctx::audio_ctx, audio_read_samples(), and session_audio_ctx::initialized.
session_audio_remove_source()
void session_audio_remove_source (session_audio_ctx_t * ctx, uint32_t source_id)
#include <src/common/session/audio.h>
Remove an audio source from mixing (host only).
Parameters
ctx Audio context (must not be NULL, must be host context)
source_id Source identifier to remove
Unregisters an audio source from the mixer.
Note
Only available when context was created with is_host=true.
Definition at line 259 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized || !ctx->is_host) {
    return;
  }
  for (int i = 0; i < SESSION_AUDIO_MAX_SOURCES; i++) {
    if (ctx->sources[i].active && ctx->sources[i].source_id == source_id) {
      if (ctx->sources[i].buffer) {
        audio_ring_buffer_destroy(ctx->sources[i].buffer);
        ctx->sources[i].buffer = NULL;
      }
      ctx->sources[i].active = false;
      ctx->sources[i].source_id = 0;
      ctx->source_count--;
      return;
    }
  }
}
References session_audio_source_t::active, audio_ring_buffer_destroy(), session_audio_source_t::buffer, session_audio_ctx::initialized, session_audio_ctx::is_host, SESSION_AUDIO_MAX_SOURCES, session_audio_ctx::source_count, session_audio_source_t::source_id, and session_audio_ctx::sources.
session_audio_start_capture()
asciichat_error_t session_audio_start_capture (session_audio_ctx_t * ctx)
#include <src/common/session/audio.h>
Start audio capture (microphone input).
Parameters
ctx Audio context (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Starts capturing audio from the default input device. Captured audio is available for transmission via session_audio_read_captured().
Definition at line 145 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_audio_start_capture: invalid context");
  }
  // Use full duplex for proper echo cancellation
  return session_audio_start_duplex(ctx);
}
References session_audio_ctx::initialized, and session_audio_start_duplex().
session_audio_start_duplex()
asciichat_error_t session_audio_start_duplex (session_audio_ctx_t * ctx)
#include <src/common/session/audio.h>
Start full-duplex audio (simultaneous capture and playback).
Parameters
ctx Audio context (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Starts both capture and playback in a single full-duplex stream. This is preferred over separate start_capture/start_playback calls as it provides better echo cancellation support.
Definition at line 163 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_audio_start_duplex: invalid context");
  }
  if (ctx->running) {
    return ASCIICHAT_OK; // Already running
  }
  asciichat_error_t result = audio_start_duplex(&ctx->audio_ctx);
  if (result == ASCIICHAT_OK) {
    ctx->running = true;
  }
  return result;
}
References session_audio_ctx::audio_ctx, audio_start_duplex(), session_audio_ctx::initialized, and session_audio_ctx::running.
Referenced by session_audio_start_capture(), session_audio_start_playback(), and session_participant_start_audio_capture().
session_audio_start_playback()
asciichat_error_t session_audio_start_playback (session_audio_ctx_t * ctx)
#include <src/common/session/audio.h>
Start audio playback (speaker output).
Parameters
ctx Audio context (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Starts playback on the default output device. Audio for playback should be provided via session_audio_write_playback().
Definition at line 154 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_audio_start_playback: invalid context");
  }
  // Use full duplex for proper echo cancellation
  return session_audio_start_duplex(ctx);
}
References session_audio_ctx::initialized, and session_audio_start_duplex().
session_audio_stop()
void session_audio_stop (session_audio_ctx_t * ctx)
#include <src/common/session/audio.h>
Stop all audio streams.
Parameters
ctx Audio context (must not be NULL)
Stops capture, playback, and any mixing operations.
Definition at line 180 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized || !ctx->running) {
    return;
  }
  (void)audio_stop_duplex(&ctx->audio_ctx);
  ctx->running = false;
}
References session_audio_ctx::audio_ctx, audio_stop_duplex(), session_audio_ctx::initialized, and session_audio_ctx::running.
Referenced by session_audio_destroy(), session_participant_start_audio_capture(), and session_participant_stop_audio_capture().
session_audio_write_playback()
asciichat_error_t session_audio_write_playback (session_audio_ctx_t * ctx, const float * buffer, size_t num_samples)
#include <src/common/session/audio.h>
Write audio samples for playback.
Parameters
ctx Audio context (must not be NULL)
buffer Input buffer with audio samples (must not be NULL)
num_samples Number of samples to write
Returns
ASCIICHAT_OK on success, error code on failure
Writes audio samples to the playback ring buffer. Samples should be in float format (-1.0 to 1.0 range).
Definition at line 213 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized || !buffer) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_audio_write_playback: invalid parameter");
  }
  return audio_write_samples(&ctx->audio_ctx, buffer, (int)num_samples);
}
References session_audio_ctx::audio_ctx, audio_write_samples(), and session_audio_ctx::initialized.
session_audio_write_source()
asciichat_error_t session_audio_write_source (session_audio_ctx_t * ctx, uint32_t source_id, const float * samples, size_t num_samples)
#include <src/common/session/audio.h>
Write audio samples from a specific source (host only).
Parameters
ctx Audio context (must not be NULL, must be host context)
source_id Source identifier
samples Audio samples from this source
num_samples Number of samples
Returns
ASCIICHAT_OK on success, error code on failure
Provides audio data from a specific participant to the mixer.
Note
Only available when context was created with is_host=true.
Definition at line 278 of file src/common/session/audio.c.
{
  if (!ctx || !ctx->initialized || !samples) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_audio_write_source: invalid parameter");
  }
  if (!ctx->is_host) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_audio_write_source: not a host context");
  }
  // Find the source
  for (int i = 0; i < SESSION_AUDIO_MAX_SOURCES; i++) {
    if (ctx->sources[i].active && ctx->sources[i].source_id == source_id) {
      if (ctx->sources[i].buffer) {
        return audio_ring_buffer_write(ctx->sources[i].buffer, samples, (int)num_samples);
      }
      return SET_ERRNO(ERROR_INVALID_STATE, "Source buffer not initialized");
    }
  }
  return SET_ERRNO(ERROR_NOT_FOUND, "Audio source not found: %u", source_id);
}
References session_audio_source_t::active, audio_ring_buffer_write(), session_audio_source_t::buffer, session_audio_ctx::initialized, session_audio_ctx::is_host, SESSION_AUDIO_MAX_SOURCES, session_audio_source_t::source_id, and session_audio_ctx::sources.
session_capture_at_end()
bool session_capture_at_end (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Check if capture source has reached end of stream.
Parameters
ctx Capture context (must not be NULL)
Returns
true if end of stream reached, false otherwise
Useful for detecting end of file sources. Webcam and test pattern sources never reach end.
Definition at line 477 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized || !ctx->source) {
    return true;
  }
  return media_source_at_end(ctx->source);
}
References session_capture_ctx::initialized, media_source_at_end(), and session_capture_ctx::source.
session_capture_create()
session_capture_ctx_t * session_capture_create (const session_capture_config_t * config)
#include <src/common/session/capture.h>
Legacy function - creates either mirror or network capture based on options.
Maintained for backwards compatibility. New code should use session_mirror_capture_create() or session_network_capture_create() directly.
Parameters
config Capture configuration
Returns
Capture context, or NULL on error
Deprecated
Use session_mirror_capture_create() or session_network_capture_create()
Definition at line 193 of file common/session/capture.c.
{
  // Auto-create config from command-line options if NULL
  session_capture_config_t auto_config = {0};
  if (!config) {
    // Auto-initialization from GET_OPTION() only works when options have been parsed
    // Verify by checking if we can access options (would SET_ERRNO if not)
    const char *media_file = GET_OPTION(media_file);
    bool media_from_stdin = GET_OPTION(media_from_stdin);
    if (media_file[0] != '\0') {
      // File or stdin streaming
      auto_config.type = media_from_stdin ? MEDIA_SOURCE_STDIN : MEDIA_SOURCE_FILE;
      auto_config.path = media_file;
      auto_config.loop = GET_OPTION(media_loop) && !media_from_stdin;
    } else if (GET_OPTION(test_pattern)) {
      // Test pattern mode
      auto_config.type = MEDIA_SOURCE_TEST;
      auto_config.path = NULL;
    } else {
      // Webcam mode (default)
      static char webcam_index_str[32];
      unsigned int idx = GET_OPTION(webcam_index);
      safe_snprintf(webcam_index_str, sizeof(webcam_index_str), "%u", idx);
      auto_config.type = MEDIA_SOURCE_WEBCAM;
      auto_config.path = webcam_index_str;
      log_debug("Webcam mode: using device index %u", idx);
    }
    // Default settings suitable for local display
    auto_config.target_fps = 60;
    auto_config.resize_for_network = false;
    config = &auto_config;
  }
  // Check if we should exit before starting initialization
  if (config->should_exit_callback && config->should_exit_callback(config->callback_data)) {
    return NULL;
  }
  // Allocate context
  session_capture_ctx_t *ctx = SAFE_CALLOC(1, sizeof(session_capture_ctx_t), session_capture_ctx_t *);
  // Store configuration
  ctx->target_fps = config->target_fps > 0 ? config->target_fps : 60;
  ctx->resize_for_network = config->resize_for_network;
  // Store audio configuration
  ctx->audio_enabled = config->enable_audio;
  ctx->audio_fallback_enabled = config->audio_fallback_to_mic;
  ctx->mic_audio_ctx = config->mic_audio_ctx;
  ctx->using_file_audio = false;
  ctx->file_has_audio = false;
  // Create media source from config type and path
  ctx->source = media_source_create(config->type, config->path);
  if (!ctx->source) {
    // Preserve existing error if set, otherwise set generic error
    asciichat_error_t existing_error = GET_ERRNO();
    if (existing_error == ASCIICHAT_OK) {
      SET_ERRNO(ERROR_MEDIA_INIT, "Failed to create media source");
    }
    SAFE_FREE(ctx);
    return NULL;
  }
  // Set up exit callback on media source for graceful shutdown during I/O
  // This allows Ctrl+C to abort blocking FFmpeg calls like YouTube HTTP requests
  if (config->should_exit_callback && ctx->source) {
    media_source_set_exit_callback(ctx->source, config->should_exit_callback, config->callback_data);
  }
  // Detect if media source has audio
  if (ctx->audio_enabled && ctx->source) {
    ctx->file_has_audio = media_source_has_audio(ctx->source);
    if (ctx->file_has_audio) {
      ctx->using_file_audio = true;
      log_info("Audio capture enabled: using file audio");
    } else if (ctx->audio_fallback_enabled && ctx->mic_audio_ctx) {
      ctx->using_file_audio = false;
      log_info("Audio capture enabled: file has no audio, using microphone fallback");
    } else {
      ctx->audio_enabled = false;
      log_debug("Audio capture disabled: no file audio and no fallback configured");
    }
  }
  // Enable loop if requested (only for file sources)
  if (config->loop && config->type == MEDIA_SOURCE_FILE) {
    media_source_set_loop(ctx->source, true);
  }
  // Set initial pause state if requested (only for file sources)
  // Note: We don't pause yet - we'll pause AFTER reading the first frame in the render loop
  // This is because paused sources return NULL from read_video()
  if (config->type == MEDIA_SOURCE_FILE && GET_OPTION(pause)) {
    ctx->should_pause_after_first_frame = true;
    log_debug("Will pause after first frame (--pause flag)");
  }
  // Perform initial seek if requested
  if (config->initial_seek_timestamp > 0.0) {
    log_debug("Seeking to %.2f seconds", config->initial_seek_timestamp);
    asciichat_error_t seek_err = media_source_seek(ctx->source, config->initial_seek_timestamp);
    if (seek_err != ASCIICHAT_OK) {
      log_warn("Failed to seek to %.2f seconds: %d", config->initial_seek_timestamp, seek_err);
      // Continue anyway - seeking is best-effort
    } else {
      log_debug("Successfully seeked to %.2f seconds", config->initial_seek_timestamp);
      // Codec buffers are flushed during seek, so next frame read will use correct position
      // Reset timing state after seek to prevent FPS calculation confusion
      // (frame_count and elapsed_time must match the new playback position)
      ctx->frame_count = 0;
      ctx->start_time_ns = time_get_ns();
      // For snapshot mode with immediate snapshot (delay=0), we need to wait for prefetch thread to
      // decode the seeked frame. This is a workaround for a timing issue where the prefetch thread
      // needs time to decode the frame at the new position after seeking.
      // The sleep duration must be long enough for the prefetch thread to decode one frame.
      float snapshot_delay = GET_OPTION(snapshot_delay);
      if (GET_OPTION(snapshot_mode) && snapshot_delay == 0.0f) {
        // HTTP streams are slow - need 1+ second for first frame decode after seek
        // Local files are faster - 100-200ms is usually sufficient
        // Use 1 second as a safe default to handle both cases
        log_debug("Waiting for prefetch thread after seek (snapshot_delay=0, HTTP streams need ~1 second)");
        platform_sleep_us(US_PER_SEC_INT); // 1 second - ensures prefetch thread has delivered seeked frame
      }
    }
  }
  // Initialize adaptive sleep for frame rate limiting
  // Calculate baseline sleep time in nanoseconds from target FPS
  uint64_t baseline_sleep_ns = NS_PER_SEC_INT / ctx->target_fps;
  adaptive_sleep_config_t sleep_config = {
      .baseline_sleep_ns = baseline_sleep_ns,
      .min_speed_multiplier = 0.5, // Allow slowing down to 50% of baseline
      .max_speed_multiplier = 2.0, // Allow speeding up to 200% of baseline
      .speedup_rate = 0.1,         // Adapt by 10% per frame if possible
      .slowdown_rate = 0.1         // Adapt by 10% per frame if possible
  };
  adaptive_sleep_init(&ctx->sleep_state, &sleep_config);
  // Initialize FPS tracker
  // Note: Must allocate tracker_name on heap since fps_init stores a pointer to it
  char *tracker_name = SAFE_MALLOC(32, char *);
  if (!tracker_name) {
    media_source_destroy(ctx->source);
    SAFE_FREE(ctx);
    return NULL;
  }
  safe_snprintf(tracker_name, 32, "CAPTURE_%u", ctx->target_fps);
  fps_init(&ctx->fps_tracker, (int)ctx->target_fps, tracker_name);
  // Record start time for FPS calculation (nanoseconds)
  ctx->start_time_ns = time_get_ns();
  ctx->initialized = true;
  return ctx;
}
References adaptive_sleep_init(), session_capture_ctx::audio_enabled, session_capture_ctx::audio_fallback_enabled, session_capture_config_t::audio_fallback_to_mic, session_capture_config_t::callback_data, session_capture_config_t::enable_audio, session_capture_ctx::file_has_audio, fps_init(), session_capture_ctx::fps_tracker, session_capture_ctx::frame_count, session_capture_config_t::initial_seek_timestamp, session_capture_ctx::initialized, session_capture_config_t::loop, media_source_create(), media_source_destroy(), media_source_has_audio(), media_source_seek(), media_source_set_exit_callback(), media_source_set_loop(), session_capture_config_t::mic_audio_ctx, session_capture_ctx::mic_audio_ctx, session_capture_config_t::path, platform_sleep_us(), session_capture_config_t::resize_for_network, session_capture_ctx::resize_for_network, safe_snprintf(), session_capture_config_t::should_exit_callback, session_capture_ctx::should_pause_after_first_frame, session_capture_ctx::sleep_state, session_capture_ctx::source, session_capture_ctx::start_time_ns, session_capture_config_t::target_fps, session_capture_ctx::target_fps, time_get_ns(), session_capture_config_t::type, and session_capture_ctx::using_file_audio.
Referenced by capture_init(), display_init(), session_mirror_capture_create(), and session_participant_start_video_capture().
session_capture_destroy()
void session_capture_destroy (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Destroy session capture context and free resources.
Parameters
ctx Capture context to destroy (can be NULL)
Cleans up the capture context and releases all resources including the media source. Safe to call with NULL.
Definition at line 354 of file common/session/capture.c.
{
  if (!ctx) {
    return;
  }
  // Destroy media source
  if (ctx->source) {
    media_source_destroy(ctx->source);
    ctx->source = NULL;
  }
  // Free FPS tracker name (allocated in session_capture_create)
  if (ctx->fps_tracker.tracker_name) {
    char *temp = (char *)ctx->fps_tracker.tracker_name;
    SAFE_FREE(temp);
  }
  ctx->initialized = false;
  SAFE_FREE(ctx);
}
References session_capture_ctx::fps_tracker, session_capture_ctx::initialized, media_source_destroy(), and session_capture_ctx::source.
Referenced by capture_cleanup(), display_cleanup(), session_client_like_run(), and session_participant_destroy().
session_capture_get_current_fps()
double session_capture_get_current_fps (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Get the current FPS being achieved by the capture source.
Parameters
ctx Capture context (must not be NULL)
Returns
Current FPS, or 0.0 if not enough frames captured yet
Definition at line 489 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized || ctx->frame_count == 0) {
    return 0.0;
  }
  // Calculate elapsed time in nanoseconds then convert to seconds
  uint64_t elapsed_ns = time_elapsed_ns(ctx->start_time_ns, time_get_ns());
  double elapsed_sec = time_ns_to_s(elapsed_ns);
  if (elapsed_sec <= 0.0) {
    return 0.0;
  }
  return (double)ctx->frame_count / elapsed_sec;
}
References session_capture_ctx::frame_count, session_capture_ctx::initialized, session_capture_ctx::start_time_ns, time_elapsed_ns(), and time_get_ns().
session_capture_get_media_source()
void * session_capture_get_media_source (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Get the underlying media source from capture context.
Parameters
ctx Capture context (must not be NULL)
Returns
Pointer to media source (cast to media_source_t*), or NULL if not available
Returns the underlying media_source_t for operations like seeking, pause/resume, or checking media type. Used by audio playback and interactive controls (keyboard input).
Note
Pointer is owned by the capture context and should not be freed
Use for advanced control like pause/resume or seek operations
Definition at line 553 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized || !ctx->source) {
    return NULL;
  }
  return (void *)ctx->source;
}
References session_capture_ctx::initialized, and session_capture_ctx::source.
Referenced by session_client_like_run(), and session_handle_keyboard_input().
session_capture_get_target_fps()
uint32_t session_capture_get_target_fps (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Get the target FPS configured for this capture context.
Parameters
ctx Capture context (must not be NULL)
Returns
Target FPS from configuration
Definition at line 505 of file common/session/capture.c.
{
  if (!ctx) {
    return 0;
  }
  return ctx->target_fps;
}
References session_capture_ctx::target_fps.
session_capture_has_audio()
bool session_capture_has_audio (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Check if capture source has audio available.
Parameters
ctx Capture context (must not be NULL)
Returns
true if audio is available, false otherwise
Returns whether the capture source has audio and it is enabled.
Definition at line 512 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized) {
    return false;
  }
  return ctx->audio_enabled;
}
References session_capture_ctx::audio_enabled, and session_capture_ctx::initialized.
session_capture_is_valid()
bool session_capture_is_valid (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Check if capture context is initialized and valid.
Parameters
ctx Capture context (can be NULL)
Returns
true if context is valid and initialized, false otherwise
Definition at line 485 of file common/session/capture.c.
{
  return ctx != NULL && ctx->initialized && ctx->source != NULL;
}
References session_capture_ctx::initialized, and session_capture_ctx::source.
session_capture_process_for_transmission()
image_t * session_capture_process_for_transmission (session_capture_ctx_t * ctx, image_t * frame)
#include <src/common/session/capture.h>
Process a frame for network transmission (resize if needed).
Parameters
ctx Capture context (must not be NULL)
frame Input frame from session_capture_read_frame() (must not be NULL)
Returns
Processed image ready for transmission, or NULL on error
Resizes the frame to network-optimal dimensions if resize_for_network was enabled in the configuration. The returned image is a new allocation owned by the caller and must be freed with image_destroy().
Note
Returns a copy if no resizing is needed.
Caller owns the returned image and must call image_destroy().
Definition at line 421 of file common/session/capture.c.
{
  if (!ctx || !frame) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_capture_process_for_transmission: NULL parameter");
    return NULL;
  }
  // If resize is not enabled, just create a copy
  if (!ctx->resize_for_network) {
    image_t *copy = image_new(frame->w, frame->h);
    if (!copy) {
      SET_ERRNO(ERROR_MEMORY, "Failed to allocate image copy");
      return NULL;
    }
    memcpy(copy->pixels, frame->pixels, (size_t)frame->w * (size_t)frame->h * sizeof(rgb_pixel_t));
    return copy;
  }
  // Calculate optimal dimensions for network transmission
  ssize_t resized_width, resized_height;
  calculate_optimal_dimensions(frame->w, frame->h, SESSION_MAX_FRAME_WIDTH, SESSION_MAX_FRAME_HEIGHT, &resized_width,
                               &resized_height);
  // Check if resizing is actually needed
  if (frame->w == resized_width && frame->h == resized_height) {
    // No resizing needed - create a copy
    image_t *copy = image_new(frame->w, frame->h);
    if (!copy) {
      SET_ERRNO(ERROR_MEMORY, "Failed to allocate image copy");
      return NULL;
    }
    memcpy(copy->pixels, frame->pixels, (size_t)frame->w * (size_t)frame->h * sizeof(rgb_pixel_t));
    return copy;
  }
  // Create new image for resized frame
  image_t *resized = image_new(resized_width, resized_height);
  if (!resized) {
    SET_ERRNO(ERROR_MEMORY, "Failed to allocate resized image buffer");
    return NULL;
  }
  // Perform resizing operation
  image_resize(frame, resized);
  return resized;
}
References frame, image_new(), image_resize(), session_capture_ctx::resize_for_network, SESSION_MAX_FRAME_HEIGHT, and SESSION_MAX_FRAME_WIDTH.
session_capture_read_audio()
size_t session_capture_read_audio (session_capture_ctx_t * ctx, float * buffer, size_t num_samples)
#include <src/common/session/capture.h>
Read audio samples from capture source.
Parameters
ctx Capture context (must not be NULL)
buffer Output buffer for audio samples (must not be NULL)
num_samples Number of samples to read
Returns
Number of samples actually read (0 if no audio available)
Reads audio samples from the media source. Audio is read from either:
File if available and enabled
Microphone if using fallback
Returns 0 if audio is not enabled or available.
Definition at line 519 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized || !buffer || num_samples == 0) {
    return 0;
  }
  if (!ctx->audio_enabled) {
    return 0;
  }
  // If using file audio, read from media source
  if (ctx->using_file_audio && ctx->source) {
    return media_source_read_audio(ctx->source, buffer, num_samples);
  }
  // If using microphone fallback, read from mic context
  if (ctx->mic_audio_ctx) {
    // mic_audio_ctx is actually an audio_context_t pointer
    // We need to read from its capture_buffer audio ring buffer
    audio_context_t *audio_ctx = (audio_context_t *)ctx->mic_audio_ctx;
    if (audio_ctx && audio_ctx->capture_buffer) {
      return audio_ring_buffer_read(audio_ctx->capture_buffer, buffer, num_samples);
    }
  }
  return 0;
}
References session_capture_ctx::audio_enabled, audio_ring_buffer_read(), session_capture_ctx::initialized, media_source_read_audio(), session_capture_ctx::mic_audio_ctx, session_capture_ctx::source, and session_capture_ctx::using_file_audio.
session_capture_read_frame()
image_t * session_capture_read_frame (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Read the next video frame from the capture source.
Parameters
ctx Capture context (must not be NULL)
Returns
Pointer to image frame, or NULL on error/end
Reads the next video frame from the media source. The returned image is owned by the media source and should NOT be freed by the caller.
Note
Frame is valid until next call or context destruction.
Check session_capture_at_end() to distinguish error from EOF.
Definition at line 379 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized || !ctx->source) {
    return NULL;
  }
  static uint64_t last_frame_time_ns = 0;
  uint64_t frame_request_time_ns = time_get_ns();
  image_t *frame = media_source_read_video(ctx->source);
  if (frame) {
    uint64_t frame_available_time_ns = time_get_ns();
    // Track frame for FPS reporting
    fps_frame_ns(&ctx->fps_tracker, frame_available_time_ns, "frame captured");
    ctx->frame_count++;
    // Log frame-to-frame timing
    if (last_frame_time_ns > 0) {
      uint64_t time_since_last_frame_ns = time_elapsed_ns(last_frame_time_ns, frame_request_time_ns);
      uint64_t time_to_get_frame_ns = time_elapsed_ns(frame_request_time_ns, frame_available_time_ns);
      double since_last_ms = (double)time_since_last_frame_ns / NS_PER_MS;
      double to_get_ms = (double)time_to_get_frame_ns / NS_PER_MS;
      if (ctx->frame_count % 30 == 0) {
        log_dev_every(3 * US_PER_SEC_INT, "FRAME_TIMING[%lu]: since_last=%.1f ms, to_get=%.1f ms", ctx->frame_count,
                      since_last_ms, to_get_ms);
      }
    }
    last_frame_time_ns = frame_available_time_ns;
    // Handle --pause flag: pause after first frame is read
    if (ctx->should_pause_after_first_frame && !ctx->paused_after_first_frame) {
      media_source_pause(ctx->source);
      ctx->paused_after_first_frame = true;
      log_info("Paused (--pause flag)");
    }
  }
  return frame;
}
References fps_frame_ns(), session_capture_ctx::fps_tracker, frame, session_capture_ctx::frame_count, session_capture_ctx::initialized, media_source_pause(), media_source_read_video(), session_capture_ctx::paused_after_first_frame, session_capture_ctx::should_pause_after_first_frame, session_capture_ctx::source, time_elapsed_ns(), and time_get_ns().
session_capture_sleep_for_fps()
void session_capture_sleep_for_fps (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Sleep to maintain target frame rate.
Parameters
ctx Capture context (must not be NULL)
Implements adaptive sleep to maintain the configured target frame rate. Call this once per frame capture iteration.
Note
Uses adaptive sleep for smooth frame rate limiting.
Definition at line 468 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized) {
    return;
  }
  // Use adaptive sleep with queue_depth=0, target_depth=0 for constant rate
  adaptive_sleep_do(&ctx->sleep_state, 0, 0);
}
References adaptive_sleep_do(), session_capture_ctx::initialized, and session_capture_ctx::sleep_state.
session_capture_using_file_audio()
bool session_capture_using_file_audio (session_capture_ctx_t * ctx)
#include <src/common/session/capture.h>
Check if currently using file audio vs microphone fallback.
Parameters
ctx Capture context (must not be NULL)
Returns
true if using file audio, false if using microphone or no audio
Useful for logging and debugging which audio source is active.
Definition at line 546 of file common/session/capture.c.
{
  if (!ctx || !ctx->initialized) {
    return false;
  }
  return ctx->using_file_audio;
}
References session_capture_ctx::initialized, and session_capture_ctx::using_file_audio.
session_client_like_get_stdin_reader()
terminal_fd_reader_t * session_client_like_get_stdin_reader (void)
#include <src/common/session/client_like.h>
Get the stdin frame reader for ASCII-to-video rendering (stdin render mode only).
Returns the stdin reader created when stdin render mode is active. Only valid after session_client_like_run() is called and during run_fn execution. May be NULL if not in stdin render mode.
Returns
Pointer to terminal_fd_reader_t, or NULL if not in stdin render mode
Definition at line 69 of file client_like.c.
{
  return g_stdin_reader;
}
session_display_clear()
void session_display_clear (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Clear the terminal screen.
Parameters
ctx Display context (must not be NULL)
Clears the terminal screen and moves cursor to home position.
Definition at line 1018 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL or uninitialized");
    return;
  }
  // Skip terminal clear in snapshot mode to preserve rendered output
  if (ctx->snapshot_mode) {
    return;
  }
  // Only perform terminal operations when we have a valid TTY (not when piping)
  if (ctx->has_tty && ctx->tty_info.fd >= 0) {
    (void)terminal_clear_screen();
    (void)terminal_cursor_home(ctx->tty_info.fd);
  }
}
References session_display_ctx::has_tty, session_display_ctx::initialized, session_display_ctx::snapshot_mode, and session_display_ctx::tty_info.
session_display_convert_to_ascii()
char * session_display_convert_to_ascii (session_display_ctx_t * ctx, const image_t * image)
#include <src/common/session/display.h>
Convert an image to ASCII art using display context and command-line options.
Parameters
ctx Display context (must not be NULL)
image Image to convert (must not be NULL)
Returns
Dynamically allocated ASCII string, or NULL on error
Converts the given image to ASCII art using:
Palette and terminal capabilities from display context
Width, height, stretch, and aspect ratio settings from GET_OPTION()
This completely encapsulates ASCII conversion complexity so callers don't need to manage palette, terminal capabilities, or conversion options.
The returned string must be freed by caller with SAFE_FREE().
Definition at line 493 of file src/common/session/display.c.
{
  if (!ctx) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_display_convert_to_ascii: ctx is NULL");
    return NULL;
  }
  if (!ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_STATE, "session_display_convert_to_ascii: ctx not initialized");
    return NULL;
  }
  if (!image) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_display_convert_to_ascii: image is NULL");
    return NULL;
  }
  // Get conversion parameters from command-line options
  unsigned short int width = GET_OPTION(width);
  unsigned short int height = GET_OPTION(height);
  bool stretch = GET_OPTION(stretch);
  bool preserve_aspect_ratio = !stretch;
  // Determine if we should apply flip_x and flip_y
  bool flip_x_enabled = GET_OPTION(flip_x);
  bool flip_y_enabled = GET_OPTION(flip_y);
  color_filter_t color_filter = GET_OPTION(color_filter);
  // Handle dynamic matrix rain effect toggle
  bool matrix_rain_enabled = GET_OPTION(matrix_rain);
  if (matrix_rain_enabled && !ctx->digital_rain) {
    // Initialize digital rain if it's now enabled but wasn't before
    unsigned short int width_us = terminal_get_effective_width();
    unsigned short int height_us = terminal_get_effective_height();
    int width_for_rain = (int)width_us;
    int height_for_rain = (int)height_us;
    ctx->digital_rain = digital_rain_init(width_for_rain, height_for_rain);
    if (ctx->digital_rain) {
      digital_rain_set_color_from_filter(ctx->digital_rain, color_filter);
      log_info("Matrix rain effect: enabled");
    }
  } else if (!matrix_rain_enabled && ctx->digital_rain) {
    // Disable digital rain if it's now disabled but was enabled before
    digital_rain_destroy(ctx->digital_rain);
    ctx->digital_rain = NULL;
    log_info("Matrix rain effect: disabled");
  }
  // Make a mutable copy of terminal capabilities for ascii_convert_with_capabilities
  terminal_capabilities_t caps_copy = ctx->caps;
  // Re-evaluate render_mode on every frame to pick up live changes
  caps_copy.render_mode = (render_mode_t)GET_OPTION(render_mode);
  // MEASURE EVERY OPERATION - Debug systematic timing
  uint64_t t_flip_start = time_get_ns();
  // Apply horizontal and/or vertical flips if requested
  image_t *flipped_image = NULL;
  const image_t *display_image = image;
  if ((flip_x_enabled || flip_y_enabled) && image->w > 1 && image->h > 1 && image->pixels) {
    START_TIMER("image_flip");
    uint64_t t_flip_alloc_start = time_get_ns();
    flipped_image = image_new((size_t)image->w, (size_t)image->h);
    uint64_t t_flip_alloc_end = time_get_ns();
    if (flipped_image) {
      uint64_t t_flip_memcpy_start = time_get_ns();
      // OPTIMIZATION: Copy entire image first (sequential memory access - cache-friendly)
      memcpy(flipped_image->pixels, image->pixels, (size_t)image->w * (size_t)image->h * sizeof(rgb_pixel_t));
      uint64_t t_flip_memcpy_end = time_get_ns();
      uint64_t t_flip_reverse_start = time_get_ns();
      // Apply horizontal flip (X-axis)
      if (flip_x_enabled) {
#if SIMD_SUPPORT_NEON
        // Use NEON-accelerated flip on ARM processors
        image_flip_horizontal_neon(flipped_image);
#else
        // Scalar fallback for non-NEON systems
        for (int y = 0; y < image->h; y++) {
          rgb_pixel_t *row = &flipped_image->pixels[y * image->w];
          for (int x = 0; x < image->w / 2; x++) {
            rgb_pixel_t temp = row[x];
            row[x] = row[image->w - 1 - x];
            row[image->w - 1 - x] = temp;
          }
        }
#endif
      }
      // Apply vertical flip (Y-axis)
      if (flip_y_enabled) {
        for (int y = 0; y < image->h / 2; y++) {
          rgb_pixel_t *top_row = &flipped_image->pixels[y * image->w];
          rgb_pixel_t *bottom_row = &flipped_image->pixels[(image->h - 1 - y) * image->w];
          for (int x = 0; x < image->w; x++) {
            rgb_pixel_t temp = top_row[x];
            top_row[x] = bottom_row[x];
            bottom_row[x] = temp;
          }
        }
      }
      uint64_t t_flip_reverse_end = time_get_ns();
      display_image = flipped_image;
      log_dev("TIMING_FLIP: alloc=%llu us, memcpy=%llu us, flip=%llu us (x=%d, y=%d)",
              (t_flip_alloc_end - t_flip_alloc_start) / 1000, (t_flip_memcpy_end - t_flip_memcpy_start) / 1000,
              (t_flip_reverse_end - t_flip_reverse_start) / 1000, flip_x_enabled, flip_y_enabled);
    }
    STOP_TIMER_AND_LOG_EVERY(dev, 3 * NS_PER_SEC_INT, 3 * NS_PER_MS_INT, "image_flip",
                             "IMAGE_FLIP: Flip complete (%.2f ms)");
  }
  uint64_t t_flip_end = time_get_ns();
  uint64_t t_filter_start = time_get_ns();
  // Apply color filter to RGB pixels before ASCII conversion
  // Rainbow filter is handled separately via ANSI color replacement
  image_t *filtered_image = NULL;
  if (color_filter != COLOR_FILTER_NONE && color_filter != COLOR_FILTER_RAINBOW) {
    // Create a copy to avoid modifying the original
    filtered_image = image_new((size_t)display_image->w, (size_t)display_image->h);
    if (filtered_image) {
      memcpy(filtered_image->pixels, display_image->pixels,
             (size_t)display_image->w * (size_t)display_image->h * sizeof(rgb_pixel_t));
      // Apply filter to the copy
      int stride = (int)display_image->w * 3;
      float time_seconds = (float)t_filter_start / (float)NS_PER_SEC_INT;
      apply_color_filter((uint8_t *)filtered_image->pixels, (uint32_t)display_image->w, (uint32_t)display_image->h,
                         (uint32_t)stride, color_filter, time_seconds);
    }
  }
  const image_t *ascii_input_image = filtered_image ? filtered_image : display_image;
  uint64_t t_filter_end = time_get_ns();
  uint64_t t_convert_start = time_get_ns();
  // Call the standard ASCII conversion using the filtered (or original) image
  START_TIMER("ascii_convert_with_capabilities");
  char *result = ascii_convert_with_capabilities(ascii_input_image, width, height, &caps_copy, preserve_aspect_ratio,
                                                 stretch, ctx->palette_chars);
  STOP_TIMER_AND_LOG_EVERY(dev, 3 * NS_PER_SEC_INT, 5 * NS_PER_MS_INT, "ascii_convert_with_capabilities",
                           "ASCII_CONVERT: Conversion complete (%.2f ms)");
  uint64_t t_convert_end = time_get_ns();
  // Apply rainbow color filter to ANSI output by replacing RGB values
  // This preserves character selection while applying the filter colors
  if (result && color_filter == COLOR_FILTER_RAINBOW) {
    uint64_t t_color_replace_start = time_get_ns();
    float time_seconds = (float)t_filter_start / (float)NS_PER_SEC_INT;
    char *rainbow_result = rainbow_replace_ansi_colors(result, time_seconds);
    if (rainbow_result) {
      SAFE_FREE(result);
      result = rainbow_result;
    }
    uint64_t t_color_replace_end = time_get_ns();
    char color_replace_str[32];
    time_pretty(t_color_replace_end - t_color_replace_start, -1, color_replace_str, sizeof(color_replace_str));
    log_dev("COLOR_REPLACE: %s", color_replace_str);
  }
  // Apply digital rain effect if enabled
  if (result && ctx->digital_rain) {
    uint64_t t_rain_start = time_get_ns();
    uint64_t current_time_ns = t_rain_start;
    float delta_time = (float)(current_time_ns - ctx->last_frame_time_ns) / (float)NS_PER_SEC_INT;
    ctx->last_frame_time_ns = current_time_ns;
    // Update digital rain color from current filter (allows live filter changes)
    color_filter_t current_filter = GET_OPTION(color_filter);
    digital_rain_set_color_from_filter(ctx->digital_rain, current_filter);
    char *rain_result = digital_rain_apply(ctx->digital_rain, result, delta_time);
    if (rain_result) {
      SAFE_FREE(result);
      result = rain_result;
    }
    uint64_t t_rain_end = time_get_ns();
    char rain_str[32];
    time_pretty(t_rain_end - t_rain_start, -1, rain_str, sizeof(rain_str));
    log_dev("DIGITAL_RAIN: Effect applied (%s)", rain_str);
  }
  uint64_t t_cleanup_start = time_get_ns();
  // Clean up flipped and filtered images if created
  START_TIMER("ascii_convert_cleanup");
  if (filtered_image) {
    image_destroy(filtered_image);
  }
  if (flipped_image) {
    image_destroy(flipped_image);
  }
  STOP_TIMER_AND_LOG_EVERY(dev, 3 * NS_PER_SEC_INT, 2 * NS_PER_MS_INT, "ascii_convert_cleanup",
                           "ASCII_CONVERT_CLEANUP: Cleanup complete (%.2f ms)");
  uint64_t t_cleanup_end = time_get_ns();
  // Log total breakdown with actual measured times
  log_dev("CONVERT_TIMING: flip=%llu us, filter=%llu us, convert=%llu us, cleanup=%llu us, TOTAL=%llu us",
          (t_flip_end - t_flip_start) / 1000, (t_filter_end - t_filter_start) / 1000,
          (t_convert_end - t_convert_start) / 1000, (t_cleanup_end - t_cleanup_start) / 1000,
          (t_cleanup_end - t_flip_start) / 1000);
  return result;
}
References apply_color_filter(), ascii_convert_with_capabilities(), session_display_ctx::caps, session_display_ctx::digital_rain, digital_rain_apply(), digital_rain_destroy(), digital_rain_init(), digital_rain_set_color_from_filter(), image_destroy(), image_new(), session_display_ctx::initialized, session_display_ctx::last_frame_time_ns, session_display_ctx::palette_chars, rainbow_replace_ansi_colors(), terminal_get_effective_height(), terminal_get_effective_width(), time_get_ns(), and time_pretty().
Referenced by session_display_encode_frame(), session_pipeline_run_main(), and session_render_loop().
session_display_create()
session_display_ctx_t * session_display_create (const session_display_config_t * config)
#include <src/common/session/display.h>
Create a new session display context.
Parameters
config Display configuration (must not be NULL)
Returns
Pointer to display context, or NULL on failure
Creates and initializes a session display context with the specified configuration. Detects terminal capabilities and initializes palette.
Note
Call session_display_destroy() to free resources when done.
On failure, sets asciichat_errno with error details.
Create a new session display context.
Executes comprehensive terminal reset sequence for clean display state. Skips terminal control operations in snapshot mode.
Parameters
snapshot_mode Whether snapshot mode is enabled
Definition at line 131 of file src/common/session/display.c.
{
  // Auto-create config from command-line options if NULL
  session_display_config_t auto_config = {0};
  if (!config) {
    auto_config.snapshot_mode = GET_OPTION(snapshot_mode);
    auto_config.palette_type = GET_OPTION(palette_type);
    auto_config.custom_palette = GET_OPTION(palette_custom_set) ? GET_OPTION(palette_custom) : NULL;
    auto_config.color_mode = TERM_COLOR_AUTO;
    config = &auto_config;
  }
  // Check if we should exit before starting initialization
  if (config->should_exit_callback && config->should_exit_callback(config->callback_data)) {
    return NULL;
  }
  // Allocate context
  session_display_ctx_t *ctx = SAFE_CALLOC(1, sizeof(session_display_ctx_t), session_display_ctx_t *);
  // Store configuration
  ctx->snapshot_mode = config->snapshot_mode;
  ctx->palette_type = config->palette_type;
  ctx->audio_playback_enabled = config->enable_audio_playback;
  ctx->audio_ctx = config->audio_ctx;
  ctx->render_fps = config->render_fps;
  atomic_store_bool(&ctx->first_frame, true);
  atomic_store_bool(&ctx->keyboard_help_active, false);
  // Initialize FPS counter
  ctx->fps_counter = fps_counter_create();
  // Get TTY info for direct terminal access
  ctx->tty_info = get_current_tty();
  // Determine if we have a valid TTY
  // Check if stdout is a TTY, not just any fd (stdin/stderr could be TTY while stdout is piped).
  // If stdout is piped/redirected, never perform terminal operations regardless of other fds.
  if (ctx->tty_info.fd >= 0) {
    ctx->has_tty = (platform_isatty(ctx->tty_info.fd) != 0) && terminal_is_stdout_tty();
  }
  // In piped mode, force all logs to stderr to prevent frame data corruption
  if (terminal_should_force_stderr()) {
    log_set_force_stderr(true);
    // Disable buffering for stdout to ensure frames appear immediately
    // Each frame ends with newline, so unbuffered output is critical for real-time display
    (void)setvbuf(stdout, NULL, _IONBF, 0);
  }
  // Also disable buffering for TTY mode to ensure smooth 40+ FPS animation
  setvbuf(stdout, NULL, _IONBF, 0);
  // Detect terminal capabilities
  ctx->caps = detect_terminal_capabilities();
  // Set wants_padding based on terminal output mode
  // Enable padding for all rendering modes (including snapshot) to center output
  // The padding adds newlines at the top, which is useful for visual centering
  bool is_snapshot_mode = config->snapshot_mode;
  ctx->caps.wants_padding = true;
  // Calculate pad_height: when padding is enabled, add top padding for centering
  // Halfblock mode uses 2 source rows per output row, so padding is halved
  if (ctx->caps.wants_padding) {
    ctx->caps.pad_height = 5; // Halfblock needs half the padding (10 / 2 = 5)
  } else {
    ctx->caps.pad_height = 0;
  }
  log_debug("Padding mode: wants_padding=%d (snapshot=%d, has_tty=%d, stdin_tty=%d, stdout_tty=%d), pad_height=%zu",
            ctx->caps.wants_padding, is_snapshot_mode, ctx->has_tty, terminal_is_stdin_tty(), terminal_is_stdout_tty(),
            ctx->caps.pad_height);
  // Apply color mode override if specified
  if (config->color_mode != TERM_COLOR_AUTO) {
    ctx->caps.color_level = config->color_mode;
  }
  // Apply command-line overrides
  ctx->caps = apply_color_mode_override(ctx->caps);
  // Initialize palette
  int palette_result = initialize_client_palette(config->palette_type, config->custom_palette, ctx->palette_chars,
                                                 &ctx->palette_len, ctx->luminance_palette);
  if (palette_result != ASCIICHAT_OK) {
    log_warn("Failed to initialize palette, using default");
    // Fall back to standard palette
    (void)initialize_client_palette(PALETTE_STANDARD, NULL, ctx->palette_chars, &ctx->palette_len,
                                    ctx->luminance_palette);
  }
  // Pre-warm UTF-8 palette cache during initialization (not during rendering)
  // This is expensive on first use (creates lookup tables), so warm it up now to avoid frame lag
  // This function is imported from lib/video/simd/common.h
  (void)get_utf8_palette_cache((const char *)ctx->palette_chars);
  log_debug("UTF-8 palette cache pre-warmed during display initialization");
  // Initialize ANSI fast lookup tables based on terminal capabilities
  if (ctx->caps.color_level == TERM_COLOR_TRUECOLOR) {
    ansi_fast_init();
  } else if (ctx->caps.color_level == TERM_COLOR_256) {
    ansi_fast_init_256color();
  } else if (ctx->caps.color_level == TERM_COLOR_16) {
    ansi_fast_init_16color();
  }
  // TERM_COLOR_MONO requires no init
  // Initialize ASCII output system if we have a TTY
  if (ctx->has_tty && ctx->tty_info.fd >= 0) {
    ascii_write_init(ctx->tty_info.fd, false);
  }
  // Initialize digital rain effect if enabled
  if (GET_OPTION(matrix_rain)) {
    // Get terminal dimensions for grid size
    unsigned short int width_us = terminal_get_effective_width();
    unsigned short int height_us = terminal_get_effective_height();
    int width = (int)width_us;
    int height = (int)height_us;
    ctx->digital_rain = digital_rain_init(width, height);
    if (ctx->digital_rain) {
      // Set color from color filter if active
      color_filter_t filter = GET_OPTION(color_filter);
      digital_rain_set_color_from_filter(ctx->digital_rain, filter);
      log_info("Digital rain effect enabled: %dx%d grid", width, height);
    } else {
      log_warn("Failed to initialize digital rain effect");
    }
    ctx->last_frame_time_ns = time_get_ns();
  }
#ifndef _WIN32
  // Initialize render-file if enabled (FFmpeg encodes to stdout when "-" is specified)
  const char *render_file_opt = GET_OPTION(render_file);
  log_info("DISPLAY_CREATE: render-file opt='%s' (len=%zu), will initialize=%s",
           render_file_opt ? render_file_opt : "(null)",
           render_file_opt ? strlen(render_file_opt) : 0,
           (render_file_opt && strlen(render_file_opt) > 0) ? "YES" : "NO");
  if (render_file_opt && strlen(render_file_opt) > 0) {
    int width = (int)GET_OPTION(width);
    int height = (int)GET_OPTION(height);
    log_info("render-file: Creating encoder with cols=%d, rows=%d", width, height);
    // Determine encoder FPS: in snapshot mode, use actual capture rate for correct duration;
    // in normal mode, use configured fps option
    uint32_t encoder_fps = 0;
    if (GET_OPTION(snapshot_mode) && config->render_fps > 0) {
      // Snapshot mode with known capture rate - use capture rate for correct duration
      encoder_fps = config->render_fps;
      log_debug("render-file: SNAPSHOT MODE - using capture rate FPS=%u (snapshot_delay=%.2f sec)", encoder_fps,
                GET_OPTION(snapshot_delay));
    } else if (config->render_fps > 0) {
      // Normal mode with known capture rate - use it
      encoder_fps = config->render_fps;
      log_debug("render-file: Using capture rate FPS=%u for encoding", encoder_fps);
    } else {
      // No capture rate available - use option default
      encoder_fps = (uint32_t)GET_OPTION(fps);
      if (encoder_fps == 0)
        encoder_fps = 60;
      log_debug("render-file: Using option FPS=%u (no capture rate available)", encoder_fps);
    }
    log_info("render-file: Final encoder FPS=%u (config_render_fps=%u, option_fps=%u)", encoder_fps, config->render_fps,
             (uint32_t)GET_OPTION(fps));
    log_info("render-file: Calling render_file_create with path='%s', %dx%d, fps=%d",
             render_file_opt, width, height, encoder_fps);
    asciichat_error_t rf_err = render_file_create(render_file_opt, width, height, (int)encoder_fps,
                                                  GET_OPTION(render_theme), &ctx->render_file);
    if (rf_err != ASCIICHAT_OK) {
      log_error("render-file: FAILED to create with error %d (ctx->render_file=%p)",
                rf_err, (void *)ctx->render_file);
    } else {
      log_info("render-file: SUCCESS - encoder initialized, ctx->render_file=%p", (void *)ctx->render_file);
      // Set audio sources if render_file_set_audio_source is available
      if (ctx->render_file && config->render_file_audio_source) {
        render_file_set_audio_source((render_file_ctx_t *)ctx->render_file, config->render_file_audio_source, NULL);
        log_debug("render-file: audio source set (media_source=%p)", config->render_file_audio_source);
      }
      if (ctx->render_file && config->render_file_audio_capture_rb) {
        render_file_set_audio_source((render_file_ctx_t *)ctx->render_file, NULL, config->render_file_audio_capture_rb);
        log_debug("render-file: audio capture ring buffer set");
      }
    }
  } else {
    log_info("render-file: NOT initializing (render_file_opt is %s)", render_file_opt ? "empty" : "NULL");
  }
#endif
  ctx->initialized = true;
  return ctx;
}
References ansi_fast_init(), ansi_fast_init_16color(), ansi_fast_init_256color(), ascii_write_init(), atomic_store_bool(), session_display_config_t::audio_ctx, session_display_ctx::audio_ctx, session_display_ctx::audio_playback_enabled, session_display_config_t::callback_data, session_display_ctx::caps, session_display_config_t::color_mode, session_display_config_t::custom_palette, detect_terminal_capabilities(), session_display_ctx::digital_rain, digital_rain_init(), digital_rain_set_color_from_filter(), session_display_config_t::enable_audio_playback, session_display_ctx::first_frame, session_display_ctx::fps_counter, fps_counter_create(), get_utf8_palette_cache(), session_display_ctx::has_tty, initialize_client_palette(), session_display_ctx::initialized, session_display_ctx::keyboard_help_active, session_display_ctx::last_frame_time_ns, log_set_force_stderr(), session_display_ctx::luminance_palette, session_display_ctx::palette_chars, session_display_ctx::palette_len, session_display_config_t::palette_type, session_display_ctx::palette_type, platform_isatty(), session_display_ctx::render_file, session_display_config_t::render_file_audio_capture_rb, session_display_config_t::render_file_audio_source, render_file_create(), render_file_set_audio_source(), session_display_config_t::render_fps, session_display_ctx::render_fps, session_display_config_t::should_exit_callback, session_display_config_t::snapshot_mode, session_display_ctx::snapshot_mode, terminal_get_effective_height(), terminal_get_effective_width(), terminal_is_stdin_tty(), terminal_is_stdout_tty(), terminal_should_force_stderr(), time_get_ns(), and session_display_ctx::tty_info.
Referenced by display_init(), and session_client_like_run().
session_display_cursor_home()
void session_display_cursor_home (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Move cursor to home position (top-left).
Parameters
ctx Display context (must not be NULL)
Moves the cursor to the top-left corner (1,1) of the terminal.
Definition at line 1036 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL or uninitialized");
    return;
  }
  int fd = ctx->has_tty ? ctx->tty_info.fd : STDOUT_FILENO;
  if (fd >= 0) {
    (void)terminal_cursor_home(fd);
  }
}
References session_display_ctx::has_tty, session_display_ctx::initialized, and session_display_ctx::tty_info.
session_display_destroy()
void session_display_destroy (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Destroy session display context and free resources.
Parameters
ctx Display context to destroy (can be NULL)
Cleans up the display context, restores terminal state, and releases all resources. Safe to call with NULL.
Definition at line 324 of file src/common/session/display.c.
{
  if (!ctx) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL");
    return;
  }
  // Cleanup ASCII rendering if we had a TTY
  // Don't reset terminal in snapshot mode to preserve the rendered output
  if (ctx->has_tty && ctx->tty_info.fd >= 0) {
    ascii_write_destroy(ctx->tty_info.fd, !ctx->snapshot_mode);
  }
  // Close the controlling terminal if we opened it
  if (ctx->tty_info.owns_fd && ctx->tty_info.fd >= 0) {
    (void)platform_close(ctx->tty_info.fd);
    ctx->tty_info.fd = -1;
    ctx->tty_info.owns_fd = false;
  }
  // Cleanup digital rain effect
  if (ctx->digital_rain) {
    digital_rain_destroy(ctx->digital_rain);
    ctx->digital_rain = NULL;
  }
  // Cleanup FPS counter
  if (ctx->fps_counter) {
    fps_counter_destroy(ctx->fps_counter);
    ctx->fps_counter = NULL;
  }
#ifndef _WIN32
  // Cleanup render-file if active
  if (ctx->render_file) {
    render_file_destroy(ctx->render_file);
    ctx->render_file = NULL;
  }
#endif
  ctx->initialized = false;
  // Clear the cached display context in splash state to prevent use-after-free
  // when worker threads try to access the display after it's been freed
  splash_clear_display_context();
  SAFE_FREE(ctx);
}
References ascii_write_destroy(), session_display_ctx::digital_rain, digital_rain_destroy(), session_display_ctx::fps_counter, fps_counter_destroy(), session_display_ctx::has_tty, session_display_ctx::initialized, platform_close(), session_display_ctx::render_file, render_file_destroy(), session_display_ctx::snapshot_mode, splash_clear_display_context(), and session_display_ctx::tty_info.
Referenced by session_client_like_run().
session_display_encode_frame()
void session_display_encode_frame (session_display_ctx_t * ctx, const image_t * image, uint64_t captured_ns)
#include <src/common/session/display.h>
Encode frame to render-file (FFmpeg only, no terminal output).
Parameters
ctx Display context (must not be NULL)
image Raw image to encode (must not be NULL)
Encodes image via render_file/FFmpeg encoder. No-op if –render-file not set. Used by the encode thread in the threaded pipeline.
Definition at line 906 of file src/common/session/display.c.
{
  static int call_count = 0;
  if (call_count++ < 5) {
    log_info("session_display_encode_frame: CALLED (ctx=%p, image=%p, captured_ns=%llu, ctx->render_file=%p)",
             (void *)ctx, (void *)image, (unsigned long long)captured_ns, ctx ? (void *)ctx->render_file : NULL);
  }
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Display context is NULL or uninitialized");
    return;
  }
  if (!image) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Image is NULL");
    return;
  }
  // Only encode if render_file is active
  if (!ctx->render_file) {
    log_warn_every(10 * NS_PER_SEC_INT, "session_display_encode_frame: render_file is NULL, skipping encode");
    return;
  }
  // Convert image to ASCII
  char *ascii = session_display_convert_to_ascii(ctx, image);
  if (!ascii) {
    log_warn("session_display_encode_frame: Failed to convert image to ASCII");
    return;
  }
  // Write ASCII to render-file encoder
#ifndef _WIN32
  asciichat_error_t fe = render_file_write_frame(ctx->render_file, ascii, captured_ns);
  if (fe != ASCIICHAT_OK) {
    log_warn_every(5 * NS_PER_SEC_INT, "render-file: encode failed (%s)", asciichat_error_string(fe));
  }
#endif
  SAFE_FREE(ascii);
}
References session_display_ctx::initialized, session_display_ctx::render_file, render_file_write_frame(), and session_display_convert_to_ascii().
session_display_get_caps()
const terminal_capabilities_t * session_display_get_caps (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Get detected terminal capabilities.
Parameters
ctx Display context (must not be NULL)
Returns
Pointer to terminal capabilities structure
Returns the detected terminal capabilities including color level, UTF-8 support, and render mode preferences.
Note
Returns NULL if context is NULL or not initialized.
Definition at line 398 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p", ctx);
    return NULL;
  }
  return &ctx->caps;
}
References session_display_ctx::caps, and session_display_ctx::initialized.
session_display_get_luminance_palette()
const char * session_display_get_luminance_palette (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Get the luminance mapping palette.
Parameters
ctx Display context (must not be NULL)
Returns
Pointer to 256-entry luminance mapping array
Returns the luminance mapping palette for direct brightness-to-character lookup during rendering.
Definition at line 422 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p", ctx);
    return NULL;
  }
  return ctx->luminance_palette;
}
References session_display_ctx::initialized, and session_display_ctx::luminance_palette.
session_display_get_palette_chars()
const char * session_display_get_palette_chars (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Get the palette characters string.
Parameters
ctx Display context (must not be NULL)
Returns
Pointer to palette character string
Returns the initialized palette character string used for luminance-to-character mapping.
Definition at line 406 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p", ctx);
    return NULL;
  }
  return ctx->palette_chars;
}
References session_display_ctx::initialized, and session_display_ctx::palette_chars.
session_display_get_palette_len()
size_t session_display_get_palette_len (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Get the palette character count.
Parameters
ctx Display context (must not be NULL)
Returns
Number of characters in the palette
Definition at line 414 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p", ctx);
    return 0;
  }
  return ctx->palette_len;
}
References session_display_ctx::initialized, and session_display_ctx::palette_len.
session_display_get_render_fps()
uint32_t session_display_get_render_fps (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Get the render FPS configured for file output.
Parameters
ctx Display context (can be NULL)
Returns
Render FPS value, or 0 if ctx is NULL
Definition at line 451 of file src/common/session/display.c.
{
  if (!ctx)
    return 0;
  return ctx->render_fps;
}
References session_display_ctx::render_fps.
Referenced by session_pipeline_create().
session_display_get_stdin_reader()
void * session_display_get_stdin_reader (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Get the stdin frame reader for ASCII-to-video rendering.
Parameters
ctx Display context (must not be NULL)
Returns
Pointer to stdin reader, or NULL if not configured
Definition at line 438 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p", ctx);
    return NULL;
  }
#ifndef _WIN32
  return ctx->stdin_reader;
#else
  return NULL;
#endif
}
References session_display_ctx::initialized, and session_display_ctx::stdin_reader.
session_display_get_tty_fd()
int session_display_get_tty_fd (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Get the TTY file descriptor.
Parameters
ctx Display context (must not be NULL)
Returns
TTY file descriptor, or -1 if no TTY available
Definition at line 430 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p", ctx);
    return -1;
  }
  return ctx->tty_info.fd;
}
References session_display_ctx::initialized, and session_display_ctx::tty_info.
Referenced by keyboard_help_render().
session_display_has_audio_playback()
bool session_display_has_audio_playback (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Check if display has audio playback configured.
Parameters
ctx Display context (must not be NULL)
Returns
true if audio playback is available, false otherwise
Definition at line 1048 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL or uninitialized");
    return false;
  }
  return ctx->audio_playback_enabled;
}
References session_display_ctx::audio_playback_enabled, and session_display_ctx::initialized.
session_display_has_first_frame()
bool session_display_has_first_frame (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Check if the display has rendered its first frame.
Parameters
ctx Display context (can be NULL)
Returns
true if first frame has been rendered, false if not yet rendered or ctx is NULL
Definition at line 466 of file src/common/session/display.c.
{
  if (!ctx) {
    return false;
  }
  // Return true if first_frame flag is false (meaning first frame has been rendered)
  return !atomic_load_bool(&ctx->first_frame);
}
References atomic_load_bool(), and session_display_ctx::first_frame.
session_display_has_render_file()
bool session_display_has_render_file (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Check if display has render-file configured.
Parameters
ctx Display context (can be NULL)
Returns
true if render-file is configured, false otherwise
Definition at line 482 of file src/common/session/display.c.
{
  if (!ctx) {
    return false;
  }
  return ctx->render_file != NULL;
}
References session_display_ctx::render_file.
Referenced by session_pipeline_create().
session_display_has_tty()
bool session_display_has_tty (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Check if display has a TTY (terminal) available.
Parameters
ctx Display context (must not be NULL)
Returns
true if TTY is available, false otherwise
Returns whether the display has detected and opened a TTY. When no TTY is available, output goes to stdout.
Definition at line 390 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p", ctx);
    return false;
  }
  return ctx->has_tty;
}
References session_display_ctx::has_tty, and session_display_ctx::initialized.
Referenced by display_has_tty(), and keyboard_help_render().
session_display_render_fps_overlay()
void session_display_render_fps_overlay (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Render FPS counter overlay in top-right corner.
Parameters
ctx Display context (must not be NULL)
Displays the current FPS value as a reverse-video overlay in the top-right corner of the terminal. Only renders in TTY mode. Safe to call when fps_counter is NULL.
Definition at line 967 of file src/common/session/display.c.
{
  if (!ctx || !ctx->fps_counter || !ctx->initialized) {
    return;
  }
  // Only render overlay in TTY mode
  if (!ctx->has_tty) {
    return;
  }
  // Get current FPS value from counter
  float fps = fps_counter_get(ctx->fps_counter);
  // Get terminal width for right-alignment
  int term_cols = (int)terminal_get_effective_width();
  // Position at row 1, right side of screen
  // Column = term_cols - 7 (to fit "FPS:144" which is 7 chars)
  // Use reverse video (\033[7m) for visibility, then reset (\033[0m)
  char overlay[64];
  int overlay_len = snprintf(overlay, sizeof(overlay), "\033[1;%dH\033[7mFPS:%3.0f\033[0m", term_cols - 6, fps);
  if (overlay_len > 0 && overlay_len < (int)sizeof(overlay)) {
    // Write overlay to TTY
    int fd = (ctx->has_tty && ctx->tty_info.fd >= 0) ? ctx->tty_info.fd : STDOUT_FILENO;
    (void)platform_write_all(fd, overlay, overlay_len);
    // Flush to ensure overlay appears immediately
    (void)terminal_flush(fd);
  }
}
References session_display_ctx::fps_counter, fps_counter_get(), session_display_ctx::has_tty, session_display_ctx::initialized, platform_write_all(), terminal_flush(), terminal_get_effective_width(), and session_display_ctx::tty_info.
Referenced by session_display_write_ascii().
session_display_render_frame()
void session_display_render_frame (session_display_ctx_t * ctx, const char * frame_data)
#include <src/common/session/display.h>
Render an ASCII frame to the terminal.
Parameters
ctx Display context (must not be NULL)
frame_data ASCII frame data to render (must not be NULL)
is_final true if this is the final frame (for snapshot mode)
Renders the ASCII frame to the terminal. Handles cursor positioning, RLE expansion if needed, and snapshot mode behavior.
In snapshot mode, renders all frames during the snapshot window. (Legacy function; new code should use split functions for threading.)
Definition at line 713 of file src/common/session/display.c.
{
  // Legacy function: shim that calls both new split functions for backward compatibility
  // This maintains API compatibility with existing code while delegating to specialized functions
  if (!ctx || !frame_data) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Display context or frame data is NULL");
    return;
  }
  // Write ASCII to terminal (main thread output path)
  session_display_write_ascii(ctx, frame_data);
}
References session_display_write_ascii().
Referenced by display_render_frame(), and session_render_loop().
session_display_reset()
void session_display_reset (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Reset terminal to default state.
Parameters
ctx Display context (must not be NULL)
Resets terminal attributes (colors, cursor visibility, etc.) to defaults. Useful for cleanup or error recovery.
Definition at line 999 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL or uninitialized");
    return;
  }
  // Skip terminal reset in snapshot mode to preserve rendered output
  if (ctx->snapshot_mode) {
    return;
  }
  // Only perform terminal operations if we have a valid TTY
  if (ctx->has_tty && ctx->tty_info.fd >= 0) {
    (void)terminal_reset(ctx->tty_info.fd);
    (void)terminal_cursor_show();
    (void)terminal_flush(ctx->tty_info.fd);
  }
}
References session_display_ctx::has_tty, session_display_ctx::initialized, session_display_ctx::snapshot_mode, terminal_cursor_show(), terminal_flush(), and session_display_ctx::tty_info.
Referenced by display_full_reset().
session_display_reset_first_frame()
void session_display_reset_first_frame (session_display_ctx_t * ctx)
#include <src/common/session/display.h>
Reset the first frame flag to allow splash screen to show again on next render.
Parameters
ctx Display context (must not be NULL)
Used during reconnection attempts to re-enable splash screen display. After calling this, the next call to session_display_render_frame() will trigger splash cleanup logic, allowing the splash to be shown again.
Definition at line 474 of file src/common/session/display.c.
{
  if (!ctx) {
    return;
  }
  // Reset first_frame flag to true so splash screen can be shown again on next render
  atomic_store_bool(&ctx->first_frame, true);
}
References atomic_store_bool(), and session_display_ctx::first_frame.
Referenced by session_client_like_run().
session_display_set_render_fps()
void session_display_set_render_fps (session_display_ctx_t * ctx, uint32_t fps)
#include <src/common/session/display.h>
Set the render FPS for file output encoding.
Parameters
ctx Display context
fps Target FPS for video encoding (detected from input media)
Definition at line 457 of file src/common/session/display.c.
{
  if (!ctx)
    return;
  ctx->render_fps = fps;
  if (fps > 0) {
    log_debug("session_display_set_render_fps: Updated render FPS to %u (for correct video duration)", fps);
  }
}
References session_display_ctx::render_fps.
Referenced by session_client_like_run().
session_display_set_snapshot_actual_duration()
void session_display_set_snapshot_actual_duration (session_display_ctx_t * ctx, double actual_duration_sec)
#include <src/common/session/display.h>
Set the actual wall-clock duration for snapshot mode frame timing.
Parameters
ctx Display context (must not be NULL)
actual_duration_sec Actual elapsed time in seconds
In snapshot mode, this function provides the actual wall-clock duration of frame capture, allowing the encoder to calculate correct frame durations so the output video spans exactly the specified duration.
Definition at line 1147 of file src/common/session/display.c.
{
  log_info("session_display_set_snapshot_actual_duration: CALLED with duration=%.3f, ctx=%p, render_file=%p",
           actual_duration_sec, (void *)ctx, ctx ? (void *)ctx->render_file : NULL);
  if (!ctx) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL");
    return;
  }
  if (!ctx->render_file) {
    log_warn("  -> render_file is NULL, cannot set duration");
    return; // No render_file context, nothing to do
  }
#ifndef _WIN32
  // Pass the actual duration to the render_file module, which passes it to the encoder
  if (ctx->render_file) {
    log_info("  -> Passing duration %.3f to render_file encoder", actual_duration_sec);
    render_file_set_snapshot_actual_duration(ctx->render_file, actual_duration_sec);
  }
#endif
}
References session_display_ctx::render_file, and render_file_set_snapshot_actual_duration().
Referenced by session_render_loop().
session_display_set_stdin_reader()
void session_display_set_stdin_reader (session_display_ctx_t * ctx, void * reader)
#include <src/common/session/display.h>
Set stdin frame reader for ASCII-to-video rendering.
Parameters
ctx Display context (must not be NULL)
reader Stdin frame reader (borrowed reference, not owned)
Only used when reading ASCII frames from stdin for rendering.
Definition at line 372 of file src/common/session/display.c.
{
  if (!ctx) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Display context is NULL");
    return;
  }
#ifndef _WIN32
  ctx->stdin_reader = (terminal_fd_reader_t *)reader;
  log_debug("session_display: stdin_reader set");
#else
  (void)reader; // Unused on Windows
#endif
}
References session_display_ctx::stdin_reader.
Referenced by session_client_like_run().
session_display_write_ascii()
void session_display_write_ascii (session_display_ctx_t * ctx, const char * frame_data)
#include <src/common/session/display.h>
Write ASCII frame to terminal only (no encoding).
Parameters
ctx Display context (must not be NULL)
frame_data ASCII frame data (must not be NULL)
Writes ANSI string to terminal/stdout without encoding to file. Used by the main thread in the threaded pipeline.
Definition at line 726 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Display context is NULL or uninitialized");
    return;
  }
  if (!ascii) {
    SET_ERRNO(ERROR_INVALID_PARAM, "ASCII data is NULL");
    return;
  }
  // Re-evaluate color_level on every frame to pick up live color_mode changes
  terminal_color_mode_t color_mode = (terminal_color_mode_t)GET_OPTION(color_mode);
  if (color_mode != TERM_COLOR_AUTO) {
    ctx->caps.color_level = color_mode;
  }
  // Suppress frame rendering when help screen is active
  if (atomic_load_bool(&ctx->keyboard_help_active)) {
    return;
  }
  // Calculate frame length
  size_t frame_len = strnlen(ascii, 1024 * 1024); // Max 1MB frame
  if (frame_len == 0) {
    SET_ERRNO(ERROR_INVALID_PARAM, "ASCII data is empty");
    return;
  }
  // Apply digital rain effect if enabled
  char *display_frame = (char *)ascii;
  char *rain_result = NULL;
  if (ctx->digital_rain) {
    uint64_t t_rain_start = time_get_ns();
    uint64_t current_time_ns = t_rain_start;
    float delta_time = (float)(current_time_ns - ctx->last_frame_time_ns) / (float)NS_PER_SEC_INT;
    ctx->last_frame_time_ns = current_time_ns;
    // Update digital rain color from current filter
    color_filter_t current_filter = GET_OPTION(color_filter);
    digital_rain_set_color_from_filter(ctx->digital_rain, current_filter);
    rain_result = digital_rain_apply(ctx->digital_rain, (char *)ascii, delta_time);
    if (rain_result) {
      display_frame = rain_result;
      frame_len = strnlen(rain_result, 1024 * 1024);
      uint64_t t_rain_end = time_get_ns();
      char rain_str[32];
      time_pretty(t_rain_end - t_rain_start, -1, rain_str, sizeof(rain_str));
      log_info("DIGITAL_RAIN (write_ascii): Effect applied (%s)", rain_str);
    }
  }
  // Handle first frame - perform initial terminal reset and splash cleanup
  bool was_first_frame = atomic_exchange_bool(&ctx->first_frame, false);
  if (was_first_frame) {
    // Stop splash screen when first frame is ready
    splash_intro_done();
    // Perform initial terminal reset
    if (ctx->has_tty && !ctx->render_file) {
      (void)terminal_reset(STDOUT_FILENO);
      (void)terminal_clear_screen();
      (void)terminal_cursor_home(STDOUT_FILENO);
      (void)terminal_clear_scrollback(STDOUT_FILENO);
      (void)terminal_cursor_show();
      if (!ctx->snapshot_mode) {
        (void)terminal_cursor_hide();
      }
      (void)terminal_flush(STDOUT_FILENO);
    }
  }
  // Output routing logic
  bool use_tty_control = ctx->has_tty && (!ctx->snapshot_mode || terminal_is_interactive());
  START_TIMER("frame_write");
  if (use_tty_control) {
    // TTY mode: Buffer cursor control + frame data together for atomic frame display
    const char *cursor_home_sequence = "\033[H\033[3J"; // 7 bytes total
    size_t cursor_seq_len = 7;
    size_t total_size = cursor_seq_len + frame_len;
    char *frame_buffer = SAFE_MALLOC(total_size, char *);
    if (frame_buffer) {
      memcpy(frame_buffer, cursor_home_sequence, cursor_seq_len);
      memcpy(frame_buffer + cursor_seq_len, display_frame, frame_len);
      log_debug("FRAME_WRITE_TTY: Writing %zu bytes (cursor=%zu + frame=%zu) to stdout", total_size, cursor_seq_len,
                frame_len);
      ssize_t written = platform_write_all(STDOUT_FILENO, frame_buffer, total_size);
      log_debug("FRAME_WRITE_TTY: Wrote %zd bytes (requested %zu)", written, total_size);
      // Start snapshot timer on first ASCII frame rendered
      if (GET_OPTION(snapshot_mode) && !g_snapshot_first_frame_rendered) {
        g_snapshot_first_frame_rendered = true;
        g_snapshot_first_frame_rendered_ns = time_get_ns();
        log_info("SNAPSHOT: FIRST ASCII FRAME RENDERED (write_ascii) - Timer started");
      }
      // Tick FPS counter
      if (ctx->fps_counter) {
        fps_counter_tick(ctx->fps_counter);
      }
      SAFE_FREE(frame_buffer);
    }
    // Flush buffers
    log_debug("FRAME_FLUSH: Flushing stdout");
    (void)fflush(stdout);
    int flush_fd = (ctx->tty_info.fd >= 0) ? ctx->tty_info.fd : STDOUT_FILENO;
    (void)terminal_flush(flush_fd);
    // Render FPS counter overlay if enabled
    if (ctx->fps_counter && GET_OPTION(fps_counter)) {
      session_display_render_fps_overlay(ctx);
    }
  } else if (terminal_is_interactive()) {
    // Piped to interactive terminal: output ASCII frames with newline
    char *write_buf = SAFE_MALLOC(frame_len + 1, char *);
    if (write_buf) {
      memcpy(write_buf, display_frame, frame_len);
      write_buf[frame_len] = '\n';
      (void)platform_write_all(STDOUT_FILENO, write_buf, frame_len + 1);
      SAFE_FREE(write_buf);
    }
    // Flush buffers
    (void)fflush(stdout);
    int flush_fd = (ctx->tty_info.fd >= 0) ? ctx->tty_info.fd : STDOUT_FILENO;
    (void)terminal_flush(flush_fd);
  } else {
    // Non-interactive piped output
    // BUT: Don't write ASCII frames to stdout if render_file is using stdout (--render-file="-")
    if (!ctx->render_file) {
      // No render-file, safe to write ASCII frames to stdout
      char *write_buf = SAFE_MALLOC(frame_len + 1, char *);
      if (write_buf) {
        memcpy(write_buf, display_frame, frame_len);
        write_buf[frame_len] = '\n';
        (void)platform_write_all(STDOUT_FILENO, write_buf, frame_len + 1);
        // Start snapshot timer on first ASCII frame rendered
        if (GET_OPTION(snapshot_mode) && !g_snapshot_first_frame_rendered) {
          g_snapshot_first_frame_rendered = true;
          g_snapshot_first_frame_rendered_ns = time_get_ns();
          log_info("SNAPSHOT: FIRST ASCII FRAME RENDERED (write_ascii piped) - Timer started");
        }
        SAFE_FREE(write_buf);
      }
      // Flush buffers (skip terminal_flush on pipes to avoid blocking in snapshot mode)
      (void)fflush(stdout);
      if (!GET_OPTION(snapshot_mode) || ctx->has_tty) {
        int flush_fd = (ctx->tty_info.fd >= 0) ? ctx->tty_info.fd : STDOUT_FILENO;
        (void)terminal_flush(flush_fd);
      }
    } else {
      // render_file is using stdout: skip ASCII output to avoid mixing with video
      if (GET_OPTION(snapshot_mode) && !g_snapshot_first_frame_rendered) {
        g_snapshot_first_frame_rendered = true;
        g_snapshot_first_frame_rendered_ns = time_get_ns();
        log_info("SNAPSHOT: FIRST FRAME RENDERED (render_file piped) - Timer started");
      }
    }
  }
  STOP_TIMER_AND_LOG_EVERY(dev, 3 * NS_PER_SEC_INT, 5 * NS_PER_MS_INT, "frame_write",
                           "FRAME_WRITE: Write and flush complete (%.2f ms)");
  // Clean up digital rain result if allocated
  if (rain_result) {
    SAFE_FREE(rain_result);
  }
}
References atomic_exchange_bool(), atomic_load_bool(), session_display_ctx::caps, session_display_ctx::digital_rain, digital_rain_apply(), digital_rain_set_color_from_filter(), session_display_ctx::first_frame, session_display_ctx::fps_counter, fps_counter_tick(), g_snapshot_first_frame_rendered, g_snapshot_first_frame_rendered_ns, session_display_ctx::has_tty, session_display_ctx::initialized, session_display_ctx::keyboard_help_active, session_display_ctx::last_frame_time_ns, platform_write_all(), session_display_ctx::render_file, session_display_render_fps_overlay(), session_display_ctx::snapshot_mode, splash_intro_done(), terminal_cursor_hide(), terminal_cursor_show(), terminal_flush(), terminal_is_interactive(), time_get_ns(), time_pretty(), and session_display_ctx::tty_info.
Referenced by session_display_render_frame(), and session_pipeline_run_main().
session_display_write_audio()
asciichat_error_t session_display_write_audio (session_display_ctx_t * ctx, const float * buffer, size_t num_samples)
#include <src/common/session/display.h>
Write audio samples to playback buffer.
Parameters
ctx Display context (must not be NULL)
buffer Audio samples to write (must not be NULL)
num_samples Number of samples to write
Returns
ASCIICHAT_OK on success, error code on failure
Writes audio samples to the playback ring buffer for playback through speakers. Used in mirror mode to play file audio or other audio sources.
Definition at line 1056 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized || !buffer || num_samples == 0) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p, buffer=%p, num_samples=%zu", ctx, buffer,
                     num_samples);
  }
  if (!ctx->audio_playback_enabled || !ctx->audio_ctx) {
    // Audio not enabled, but not an error - just skip silently
    return ASCIICHAT_OK;
  }
  // For mirror mode with local files: write samples directly without jitter buffering
  // The jitter buffer is designed for network scenarios with irregular packet arrivals
  // For local playback, we just want raw samples flowing to the speakers
  audio_context_t *audio_ctx = (audio_context_t *)ctx->audio_ctx;
  if (audio_ctx && audio_ctx->playback_buffer) {
    audio_ring_buffer_t *rb = audio_ctx->playback_buffer;
    // Simple direct write: append samples to ring buffer without network-oriented complexity
    uint32_t write_idx = (uint32_t)atomic_load_u64(&rb->write_index);
    uint32_t read_idx = (uint32_t)atomic_load_u64(&rb->read_index);
    // Calculate available space in ring buffer
    uint32_t available = (read_idx - write_idx - 1) & (AUDIO_RING_BUFFER_SIZE - 1);
    if ((uint32_t)num_samples > available) {
      // Buffer full - just skip this write to avoid distortion from overwriting old audio
      return ASCIICHAT_OK;
    }
    // Direct memcpy to ring buffer, handling wrap-around
    uint32_t space_before_wrap = AUDIO_RING_BUFFER_SIZE - write_idx;
    if ((uint32_t)num_samples <= space_before_wrap) {
      memcpy(&rb->data[write_idx], buffer, num_samples * sizeof(float));
    } else {
      // Split write: first part to end of buffer, second part wraps to beginning
      uint32_t first_part = space_before_wrap;
      uint32_t second_part = num_samples - first_part;
      memcpy(&rb->data[write_idx], buffer, first_part * sizeof(float));
      memcpy(&rb->data[0], &buffer[first_part], second_part * sizeof(float));
    }
    // Update write index atomically
    atomic_store_u64(&rb->write_index, (write_idx + num_samples) % AUDIO_RING_BUFFER_SIZE);
    return ASCIICHAT_OK;
  }
  return ASCIICHAT_OK;
}
References atomic_load_u64(), atomic_store_u64(), session_display_ctx::audio_ctx, session_display_ctx::audio_playback_enabled, and session_display_ctx::initialized.
session_display_write_raw()
void session_display_write_raw (session_display_ctx_t * ctx, const char * data, size_t len)
#include <src/common/session/display.h>
Render raw bytes to the terminal without frame processing.
Parameters
ctx Display context (must not be NULL)
data Raw byte data to write (must not be NULL)
len Length of data in bytes
Directly writes raw bytes to the terminal without any frame processing. Useful for RLE-expanded frames or pre-formatted output.
Definition at line 947 of file src/common/session/display.c.
{
  if (!ctx || !ctx->initialized || !data || len == 0) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters: ctx=%p, data=%p, len=%zu", ctx, data, len);
    return;
  }
  int fd = -1;
  if (ctx->has_tty && ctx->tty_info.fd >= 0) {
    fd = ctx->tty_info.fd;
  } else {
    fd = STDOUT_FILENO;
  }
  // Write all data with automatic retry on transient errors
  (void)platform_write_all(fd, data, len);
  // Flush immediately after write to TTY to ensure data is sent
  (void)terminal_flush(fd);
}
References session_display_ctx::has_tty, session_display_ctx::initialized, platform_write_all(), terminal_flush(), and session_display_ctx::tty_info.
Referenced by keyboard_help_render().
session_handle_keyboard_input()
void session_handle_keyboard_input (session_capture_ctx_t * capture, session_display_ctx_t * display, keyboard_key_t key)
#include <src/common/session/keyboard_handler.h>
Handle keyboard input in a session.
Parameters
capture Capture context (may be NULL for client-only mode)
display Display context (may be NULL if not needed)
key Keyboard key code from keyboard_key_t enumeration
Processes keyboard input and performs appropriate session actions. Supports both mirror mode (local capture) and client mode (network rendering).
Keyboard Controls:
'?' key: Toggle help screen on/off (all modes)
Left Arrow: Seek -30 seconds (file/URL sources only)
Right Arrow: Seek +30 seconds (file/URL sources only)
Up Arrow: Increase volume +10% (all modes with audio)
Down Arrow: Decrease volume -10% (all modes with audio)
Spacebar: Play/pause toggle (file/URL sources only)
'c' key: Cycle through color modes (mono → 16 → 256 → truecolor)
'm' key: Toggle mute (remembers previous volume for unmute)
'x' key: Flip webcam horizontally (mirroring)
'y' key: Flip webcam vertically
Source-specific behavior:
Help screen: Works in all modes (toggles with '?')
Seek/pause controls: Only work with file and URL sources (not webcam)
Volume/mute: Work with any audio-capable source
Color cycling: Works with all rendering modes
Flip: Works with all capture sources (webcam, media files, etc.)
Audio volume:
Volume range: [0.0, 1.0] (0% = silent, 100% = maximum/normal)
Default volume: 1.0 (100%)
Mute state: Remembers the previous non-zero volume when toggled back on
Unrecognized keys are silently ignored (no error returned)
Thread safety:
Safe to call from render thread (video/audio threads)
Safe to call concurrently from multiple render threads
Uses RCU-protected options for atomic updates
No explicit locking required (option system handles synchronization)
Does not block waiting for I/O or locks
Error handling:
Always succeeds (void return)
Invalid or unrecognized keys are silently ignored
If capture is NULL (client-only mode), seek/pause requests are silently ignored
If display is NULL (non-TTY mode), help screen toggle is silently ignored
If audio system is unavailable, volume changes are silently ignored
Parameters
capture NULL for client-only mode (network rendering), non-NULL for local capture
display Display context for help screen toggle (may be NULL)
key Valid key code from keyboard_key_t enum (0-127 for ASCII, special key codes)
Note
Safe to call without prior keyboard_init() (silently handles invalid keys)
In client-only mode, capture is NULL (seek/pause unavailable, other controls work)
Volume adjustments are immediate without audible artifacts
Mute persists across multiple mute toggles with volume memory
Definition at line 87 of file keyboard_handler.c.
{
  // Debug: log all key codes to help identify unknown keys
  if (key != KEY_NONE) {
    log_info("KEYBOARD INPUT: code=%d (0x%02x) char='%c'", key, key, (key >= 32 && key < 127) ? key : '?');
    if (key == 'x' || key == 'X') {
      log_info("!!! X KEY DETECTED AT HANDLER ENTRY !!!");
    }
  }
  switch ((int)key) {
  // ===== HELP SCREEN TOGGLE =====
  case KEY_QUESTION: {
    log_info("✓✓✓ USER PRESSED ? KEY - HELP SCREEN TOGGLE ✓✓✓");
    if (display) {
      log_info("Toggling help screen (display=%p)", (void *)display);
      keyboard_help_toggle(display);
      // Render help screen immediately so user sees it
      keyboard_help_render(display);
      log_info("✓ Help screen toggle complete");
    } else {
      log_error("ERROR: Cannot toggle help - display context is NULL");
    }
    break;
  }
  // ===== HELP SCREEN CLOSE / QUIT =====
  case KEY_ESCAPE: {
    if (display && keyboard_help_is_active(display)) {
      // Close help screen if it's active
      keyboard_help_toggle(display);
      terminal_clear_screen();
    } else {
      // If help screen is not active, quit the app (like Ctrl-C)
      // The signal handler will gracefully shutdown all modes (client, server, mirror, etc.)
      raise(SIGINT);
    }
    break;
  }
  // ===== SEEK CONTROLS (file sources only) =====
  case KEY_LEFT: { // Seek backward 30 seconds
    if (capture) {
      media_source_t *source = (media_source_t *)session_capture_get_media_source(capture);
      if (source && media_source_get_type(source) == MEDIA_SOURCE_FILE) {
        double current_pos = media_source_get_position(source);
        if (current_pos >= 0.0) {
          double new_pos = current_pos - 30.0;
          if (new_pos < 0.0) {
            new_pos = 0.0;
          }
          asciichat_error_t err = media_source_seek(source, new_pos);
          if (err == ASCIICHAT_OK) {
            log_info("Seeked backward to %.1f seconds", new_pos);
          }
          void *audio_ctx = session_capture_get_audio_context(capture);
          if (audio_ctx) {
            audio_flush_playback_buffers((audio_context_t *)audio_ctx);
          }
        }
      }
    }
    break;
  }
  case KEY_RIGHT: { // Seek forward 30 seconds
    if (capture) {
      media_source_t *source = (media_source_t *)session_capture_get_media_source(capture);
      if (source && media_source_get_type(source) == MEDIA_SOURCE_FILE) {
        double current_pos = media_source_get_position(source);
        double duration = media_source_get_duration(source);
        if (current_pos >= 0.0) {
          double new_pos = current_pos + 30.0;
          // Clamp to duration if known
          if (duration > 0.0 && new_pos > duration) {
            new_pos = duration;
          }
          asciichat_error_t err = media_source_seek(source, new_pos);
          if (err == ASCIICHAT_OK) {
            log_info("Seeked forward to %.1f seconds", new_pos);
          }
          void *audio_ctx = session_capture_get_audio_context(capture);
          if (audio_ctx) {
            audio_flush_playback_buffers((audio_context_t *)audio_ctx);
          }
        }
      }
    }
    break;
  }
  // ===== VOLUME CONTROLS =====
  case KEY_DOWN: { // Decrease volume 10%
    double current_volume = GET_OPTION(speakers_volume);
    double new_volume = clamp_volume(current_volume - 0.1);
    options_set_double("speakers_volume", new_volume);
    double verify_volume = GET_OPTION(speakers_volume);
    log_info("Volume DOWN: %.0f%% → %.0f%% (verified: %.0f%%)", current_volume * 100.0, new_volume * 100.0,
             verify_volume * 100.0);
    break;
  }
  case KEY_UP: { // Increase volume 10%
    double current_volume = GET_OPTION(speakers_volume);
    double new_volume = clamp_volume(current_volume + 0.1);
    options_set_double("speakers_volume", new_volume);
    double verify_volume = GET_OPTION(speakers_volume);
    log_info("Volume UP: %.0f%% → %.0f%% (verified: %.0f%%)", current_volume * 100.0, new_volume * 100.0,
             verify_volume * 100.0);
    break;
  }
  // ===== PLAY/PAUSE CONTROL =====
  case KEY_SPACE: { // Toggle play/pause
    if (capture) {
      media_source_t *source = (media_source_t *)session_capture_get_media_source(capture);
      if (source && media_source_get_type(source) == MEDIA_SOURCE_FILE) {
        media_source_toggle_pause(source);
        if (media_source_is_paused(source)) {
          log_info("Paused");
        } else {
          log_info("Playing");
        }
      }
    }
    break;
  }
  // ===== COLOR MODE CONTROL =====
  case KEY_C:
  case 'C': {
    int current_mode = (int)GET_OPTION(color_mode);
    int next_mode = next_color_mode(current_mode);
    options_set_int("color_mode", next_mode);
    const char *mode_names[] = {"Mono", "16-color", "256-color", "Truecolor"};
    if (next_mode >= 0 && next_mode <= 3) {
      log_info("Color mode: %s", mode_names[next_mode]);
    }
    break;
  }
  // ===== MUTE CONTROL =====
  case KEY_M:
  case 'M': {
    double current_volume = GET_OPTION(speakers_volume);
    log_debug("Mute toggle: current_volume=%.2f, g_mute_saved_volume=%.2f, threshold=0.01", current_volume,
              g_mute_saved_volume);
    if (current_volume > 0.01) { // If not already muted
      // Save current volume and mute
      g_mute_saved_volume = current_volume;
      options_set_double("speakers_volume", 0.0);
      double verify = GET_OPTION(speakers_volume);
      log_info("Muted: saved %.0f%%, set to 0%% (verified: %.2f)", g_mute_saved_volume * 100.0, verify);
    } else {
      // Restore previous volume
      double restore_volume = g_mute_saved_volume > 0.0 ? g_mute_saved_volume : 0.5;
      options_set_double("speakers_volume", restore_volume);
      double verify = GET_OPTION(speakers_volume);
      log_info("Unmuted: restored %.0f%% (verified: %.2f)", restore_volume * 100.0, verify);
    }
    break;
  }
  // ===== RENDER MODE CONTROL =====
  case KEY_R:
  case 'R': {
    int current_mode = (int)GET_OPTION(render_mode);
    int next_mode = next_render_mode(current_mode);
    options_set_int("render_mode", next_mode);
    const char *mode_names[] = {"Foreground", "Background", "Half-block"};
    if (next_mode >= 0 && next_mode <= 2) {
      log_info("Render mode: %s", mode_names[next_mode]);
    }
    break;
  }
  // ===== COLOR FILTER CONTROL =====
  case KEY_F:
  case 'F': {
    int current_filter = (int)GET_OPTION(color_filter);
    int next_filter = next_color_filter(current_filter);
    options_set_int("color_filter", next_filter);
    const char *filter_names[] = {"None", "Black", "White", "Green", "Magenta", "Fuchsia", "Orange",
                                  "Teal", "Cyan",  "Pink",  "Red",   "Yellow",  "Rainbow"};
    if (next_filter >= 0 && next_filter < (int)COLOR_FILTER_COUNT) {
      log_info("Color filter: %s", filter_names[next_filter]);
    }
    break;
  }
  // ===== HORIZONTAL FLIP CONTROL =====
  case 'X':
  case 'x': {
    log_info("✓ X KEY PRESSED - handling horizontal flip");
    bool current_flip_x = (bool)GET_OPTION(flip_x);
    options_set_bool("flip_x", !current_flip_x);
    log_info("Horizontal flip: %s (was: %s)", !current_flip_x ? "enabled" : "disabled",
             current_flip_x ? "enabled" : "disabled");
    break;
  }
  // ===== VERTICAL FLIP CONTROL =====
  case 'Y':
  case 'y': {
    bool current_flip_y = (bool)GET_OPTION(flip_y);
    options_set_bool("flip_y", !current_flip_y);
    log_info("Vertical flip: %s", !current_flip_y ? "enabled" : "disabled");
    break;
  }
  // ===== MATRIX RAIN EFFECT CONTROL =====
  case KEY_0: {
    bool current_matrix = (bool)GET_OPTION(matrix_rain);
    options_set_bool("matrix_rain", !current_matrix);
    log_info("Matrix rain effect: %s", !current_matrix ? "enabled" : "disabled");
    break;
  }
  // ===== FPS COUNTER TOGGLE =====
  case '-': {
    bool current = (bool)GET_OPTION(fps_counter);
    options_set_bool("fps_counter", !current);
    log_info("FPS counter: %s", !current ? "enabled" : "disabled");
    break;
  }
  // ===== LOCK DEBUG (debug builds only) =====
#ifndef NDEBUG
  case KEY_BACKTICK: {
    debug_sync_trigger_print();
    log_debug("Lock state dump triggered via backtick key");
    break;
  }
#endif
  default:
    // Unknown key - silently ignore
    break;
  }
}
References audio_flush_playback_buffers(), bool, debug_sync_trigger_print(), keyboard_help_is_active(), keyboard_help_render(), keyboard_help_toggle(), media_source_get_duration(), media_source_get_position(), media_source_get_type(), media_source_is_paused(), media_source_seek(), media_source_toggle_pause(), options_set_bool(), options_set_double(), options_set_int(), session_capture_get_audio_context(), and session_capture_get_media_source().
Referenced by display_render_frame().
session_host_add_client()
uint32_t session_host_add_client (session_host_t * host, socket_t socket, const char * ip, int port)
#include <src/common/session/host.h>
Add a client from an accepted socket.
Parameters
host Host handle (must not be NULL)
socket Accepted client socket
ip Client IP address
port Client port
Returns
Assigned client ID on success, 0 on failure
Registers a new client from an accepted socket connection. This is typically called internally by the accept loop, but can be used for testing.
Note
on_client_join callback is invoked on successful registration.
Definition at line 928 of file host.c.
{
  if (!host || !host->initialized) {
    return 0;
  }
  mutex_lock(&host->clients_mutex);
  // Check if we have room
  if (host->client_count >= host->max_clients) {
    mutex_unlock(&host->clients_mutex);
    SET_ERRNO(ERROR_SESSION_FULL, "Maximum clients reached");
    return 0;
  }
  // Find empty slot
  for (int i = 0; i < host->max_clients; i++) {
    if (!host->clients[i].active) {
      host->clients[i].participant_type = PARTICIPANT_TYPE_NETWORK;
      host->clients[i].client_id = host->next_client_id++;
      host->clients[i].socket = socket;
      if (ip) {
        SAFE_STRNCPY(host->clients[i].ip_address, ip, sizeof(host->clients[i].ip_address));
      }
      host->clients[i].port = port;
      host->clients[i].active = true;
      host->clients[i].video_active = false;
      host->clients[i].audio_active = false;
      host->clients[i].connected_at = (uint64_t)time(NULL);
      host->clients[i].transport = NULL; // No alternative transport initially
      // Allocate media buffers
      host->clients[i].incoming_video = image_new(480, 270);                        // Network-optimal size (HD preview)
      host->clients[i].incoming_audio = ringbuffer_create(sizeof(float), 960 * 10); // ~200ms buffer @ 48kHz
      if (!host->clients[i].incoming_video || !host->clients[i].incoming_audio) {
        // Cleanup on allocation failure
        if (host->clients[i].incoming_video) {
          image_destroy(host->clients[i].incoming_video);
          host->clients[i].incoming_video = NULL;
        }
        if (host->clients[i].incoming_audio) {
          ringbuffer_destroy(host->clients[i].incoming_audio);
          host->clients[i].incoming_audio = NULL;
        }
        host->clients[i].active = false;
        mutex_unlock(&host->clients_mutex);
        SET_ERRNO(ERROR_MEMORY, "Failed to allocate media buffers for client");
        return 0;
      }
      uint32_t client_id = host->clients[i].client_id;
      host->client_count++;
      mutex_unlock(&host->clients_mutex);
      // Invoke callback
      if (host->callbacks.on_client_join) {
        host->callbacks.on_client_join(host, client_id, host->user_data);
      }
      return client_id;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return 0;
}
References session_host_client_t::active, session_host_client_t::audio_active, session_host::callbacks, session_host::client_count, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host_client_t::connected_at, image_destroy(), image_new(), session_host_client_t::incoming_audio, session_host_client_t::incoming_video, session_host::initialized, session_host_client_t::ip_address, session_host::max_clients, session_host::next_client_id, session_host_callbacks_t::on_client_join, session_host_client_t::participant_type, session_host_client_t::port, ringbuffer_create(), ringbuffer_destroy(), session_host_client_t::socket, session_host_client_t::transport, session_host::user_data, and session_host_client_t::video_active.
Referenced by add_client(), and add_webrtc_client().
session_host_add_memory_participant()
uint32_t session_host_add_memory_participant (session_host_t * host)
#include <src/common/session/host.h>
Add a memory participant (host's own media).
Parameters
host Host handle (must not be NULL)
Returns
Assigned participant ID on success, 0 on failure
Registers a memory participant for the host's own webcam/audio. This allows the host to participate in the session without network loopback. Media is injected directly into the mixer via session_host_inject_frame().
Note
on_client_join callback is invoked on successful registration.
Only one memory participant per host is supported.
Definition at line 996 of file host.c.
{
  if (!host || !host->initialized) {
    return 0;
  }
  mutex_lock(&host->clients_mutex);
  // Check if we have room
  if (host->client_count >= host->max_clients) {
    mutex_unlock(&host->clients_mutex);
    SET_ERRNO(ERROR_SESSION_FULL, "Maximum clients reached");
    return 0;
  }
  // Check if memory participant already exists (only one allowed)
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].participant_type == PARTICIPANT_TYPE_MEMORY) {
      mutex_unlock(&host->clients_mutex);
      SET_ERRNO(ERROR_INVALID_PARAM, "Memory participant already exists");
      return 0;
    }
  }
  // Find empty slot
  for (int i = 0; i < host->max_clients; i++) {
    if (!host->clients[i].active) {
      host->clients[i].participant_type = PARTICIPANT_TYPE_MEMORY;
      host->clients[i].client_id = host->next_client_id++;
      host->clients[i].socket = INVALID_SOCKET_VALUE; // No socket for memory participant
      SAFE_STRNCPY(host->clients[i].ip_address, "memory", sizeof(host->clients[i].ip_address));
      host->clients[i].port = 0;
      host->clients[i].active = true;
      host->clients[i].video_active = false;
      host->clients[i].audio_active = false;
      host->clients[i].connected_at = (uint64_t)time(NULL);
      host->clients[i].transport = NULL;
      // Allocate media buffers (same as network clients)
      host->clients[i].incoming_video = image_new(480, 270);
      host->clients[i].incoming_audio = ringbuffer_create(sizeof(float), 960 * 10);
      if (!host->clients[i].incoming_video || !host->clients[i].incoming_audio) {
        if (host->clients[i].incoming_video) {
          image_destroy(host->clients[i].incoming_video);
          host->clients[i].incoming_video = NULL;
        }
        if (host->clients[i].incoming_audio) {
          ringbuffer_destroy(host->clients[i].incoming_audio);
          host->clients[i].incoming_audio = NULL;
        }
        host->clients[i].active = false;
        mutex_unlock(&host->clients_mutex);
        SET_ERRNO(ERROR_MEMORY, "Failed to allocate media buffers for memory participant");
        return 0;
      }
      uint32_t participant_id = host->clients[i].client_id;
      host->client_count++;
      mutex_unlock(&host->clients_mutex);
      log_info("Added memory participant with ID %u", participant_id);
      // Invoke callback
      if (host->callbacks.on_client_join) {
        host->callbacks.on_client_join(host, participant_id, host->user_data);
      }
      return participant_id;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return 0;
}
References session_host_client_t::active, session_host_client_t::audio_active, session_host::callbacks, session_host::client_count, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host_client_t::connected_at, image_destroy(), image_new(), session_host_client_t::incoming_audio, session_host_client_t::incoming_video, session_host::initialized, session_host_client_t::ip_address, session_host::max_clients, session_host::next_client_id, session_host_callbacks_t::on_client_join, participant_id, session_host_client_t::participant_type, session_host_client_t::port, ringbuffer_create(), ringbuffer_destroy(), session_host_client_t::socket, session_host_client_t::transport, session_host::user_data, and session_host_client_t::video_active.
session_host_broadcast_frame()
asciichat_error_t session_host_broadcast_frame (session_host_t * host, const char * frame)
#include <src/common/session/host.h>
Broadcast ASCII frame to all clients.
Parameters
host Host handle (must not be NULL)
frame ASCII frame data (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Sends an ASCII frame to all connected clients.
Definition at line 1258 of file host.c.
{
  if (!host || !host->initialized || !frame) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_broadcast_frame: invalid parameter");
  }
  if (!host->running) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_host_broadcast_frame: not running");
  }
  // Broadcast ASCII frame to all connected clients
  size_t frame_len = strlen(frame) + 1; // Include null terminator
  asciichat_error_t result = ASCIICHAT_OK;
  mutex_lock(&host->clients_mutex);
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].socket != INVALID_SOCKET_VALUE) {
      asciichat_error_t send_result =
          packet_send(host->clients[i].socket, PACKET_TYPE_ASCII_FRAME, (const void *)frame, frame_len);
      if (send_result != ASCIICHAT_OK) {
        log_warn("Failed to send ASCII frame to client %u", host->clients[i].client_id);
        result = send_result; // Store error but continue broadcasting to other clients
      }
    }
  }
  mutex_unlock(&host->clients_mutex);
  return result;
}
References session_host_client_t::active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, frame, session_host::initialized, session_host::max_clients, packet_send(), session_host::running, and session_host_client_t::socket.
session_host_client_has_transport()
bool session_host_client_has_transport (session_host_t * host, uint32_t client_id)
#include <src/common/session/host.h>
Check if a specific client has an active alternative transport.
Convenient way to check if a client is using an alternative transport (WebRTC, WebSocket, etc.) instead of raw TCP socket.
Parameters
host Host handle (must not be NULL)
client_id Client ID to check
Returns
true if alternative transport is set, false otherwise
Definition at line 1461 of file host.c.
{
  if (!host || !host->initialized) {
    return false;
  }
  mutex_lock(&host->clients_mutex);
  // Find client with matching ID
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].client_id == client_id) {
      bool has_transport = host->clients[i].transport != NULL;
      mutex_unlock(&host->clients_mutex);
      return has_transport;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return false;
}
References session_host_client_t::active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host::initialized, session_host::max_clients, and session_host_client_t::transport.
session_host_create()
session_host_t * session_host_create (const session_host_config_t * config)
#include <src/common/session/host.h>
Create a new session host.
Parameters
config Host configuration (must not be NULL)
Returns
Pointer to host handle, or NULL on failure
Creates a session host with the specified configuration. The host is not started until session_host_start() is called.
Note
Call session_host_destroy() to free resources when done.
On failure, sets asciichat_errno with error details.
Definition at line 167 of file host.c.
{
  if (!config) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_host_create: NULL config");
    return NULL;
  }
  // Allocate host
  session_host_t *host = SAFE_CALLOC(1, sizeof(session_host_t), session_host_t *);
  // Copy configuration
  host->port = config->port > 0 ? config->port : OPT_PORT_INT_DEFAULT;
  host->max_clients = config->max_clients > 0 ? config->max_clients : SESSION_HOST_DEFAULT_MAX_CLIENTS;
  host->encryption_enabled = config->encryption_enabled;
  if (config->ipv4_address) {
    SAFE_STRNCPY(host->ipv4_address, config->ipv4_address, sizeof(host->ipv4_address));
  }
  if (config->ipv6_address) {
    SAFE_STRNCPY(host->ipv6_address, config->ipv6_address, sizeof(host->ipv6_address));
  }
  if (config->key_path) {
    SAFE_STRNCPY(host->key_path, config->key_path, sizeof(host->key_path));
  }
  if (config->password) {
    SAFE_STRNCPY(host->password, config->password, sizeof(host->password));
  }
  host->callbacks = config->callbacks;
  host->user_data = config->user_data;
  // Initialize sockets to invalid
  host->socket_v4 = INVALID_SOCKET_VALUE;
  host->socket_v6 = INVALID_SOCKET_VALUE;
  host->running = false;
  // Allocate client array
  host->clients = SAFE_CALLOC((size_t)host->max_clients, sizeof(session_host_client_t), session_host_client_t *);
  host->client_count = 0;
  host->next_client_id = 1;
  // Initialize mutex
  if (mutex_init(&host->clients_mutex, "host_clients") != 0) {
    SET_ERRNO(ERROR_THREAD, "Failed to initialize clients mutex");
    SAFE_FREE(host->clients);
    SAFE_FREE(host);
    return NULL;
  }
  host->initialized = true;
  return host;
}
References session_host::callbacks, session_host_config_t::callbacks, session_host::client_count, session_host::clients, session_host::clients_mutex, session_host::encryption_enabled, session_host_config_t::encryption_enabled, session_host::initialized, session_host::ipv4_address, session_host_config_t::ipv4_address, session_host::ipv6_address, session_host_config_t::ipv6_address, session_host::key_path, session_host_config_t::key_path, session_host::max_clients, session_host_config_t::max_clients, mutex_init(), session_host::next_client_id, session_host::password, session_host_config_t::password, session_host::port, session_host_config_t::port, session_host::running, SESSION_HOST_DEFAULT_MAX_CLIENTS, session_host::socket_v4, session_host::socket_v6, session_host::user_data, and session_host_config_t::user_data.
Referenced by discovery_session_become_host(), discovery_session_process(), and server_main().
session_host_destroy()
void session_host_destroy (session_host_t * host)
#include <src/common/session/host.h>
Destroy session host and free resources.
Parameters
host Host to destroy (can be NULL)
Stops if running, disconnects all clients, and releases all resources. Safe to call with NULL.
Definition at line 223 of file host.c.
{
  if (!host) {
    return;
  }
  // Stop if running
  if (host->running) {
    session_host_stop(host);
  }
  // Clean up audio resources
  if (host->audio_ctx) {
    session_audio_destroy(host->audio_ctx);
    host->audio_ctx = NULL;
  }
  if (host->opus_decoder) {
    opus_codec_destroy(host->opus_decoder);
    host->opus_decoder = NULL;
  }
  // Close sockets
  if (host->socket_v4 != INVALID_SOCKET_VALUE) {
    socket_close(host->socket_v4);
    host->socket_v4 = INVALID_SOCKET_VALUE;
  }
  if (host->socket_v6 != INVALID_SOCKET_VALUE) {
    socket_close(host->socket_v6);
    host->socket_v6 = INVALID_SOCKET_VALUE;
  }
  // Free client array and per-client resources
  if (host->clients) {
    for (int i = 0; i < host->max_clients; i++) {
      if (host->clients[i].incoming_video) {
        image_destroy(host->clients[i].incoming_video);
        host->clients[i].incoming_video = NULL;
      }
      if (host->clients[i].incoming_audio) {
        ringbuffer_destroy(host->clients[i].incoming_audio);
        host->clients[i].incoming_audio = NULL;
      }
    }
    SAFE_FREE(host->clients);
  }
  // Destroy mutex
  mutex_destroy(&host->clients_mutex);
  // Clear sensitive data
  memset(host->password, 0, sizeof(host->password));
  host->initialized = false;
  SAFE_FREE(host);
}
References session_host::audio_ctx, session_host::clients, session_host::clients_mutex, image_destroy(), session_host_client_t::incoming_audio, session_host_client_t::incoming_video, session_host::initialized, session_host::max_clients, mutex_destroy(), opus_codec_destroy(), session_host::opus_decoder, session_host::password, ringbuffer_destroy(), session_host::running, session_audio_destroy(), session_host_stop(), session_host::socket_v4, and session_host::socket_v6.
Referenced by discovery_session_destroy(), and server_main().
session_host_find_client()
asciichat_error_t session_host_find_client (session_host_t * host, uint32_t client_id, session_host_client_info_t * info)
#include <src/common/session/host.h>
Find a client by ID.
Parameters
host Host handle (must not be NULL)
client_id Client ID to find
info Output client info structure (must not be NULL)
Returns
ASCIICHAT_OK on success, ERROR_NOT_FOUND if not found
Retrieves information about a connected client.
Definition at line 1204 of file host.c.
{
  if (!host || !host->initialized || !info) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_find_client: invalid parameter");
  }
  mutex_lock(&host->clients_mutex);
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].client_id == client_id) {
      info->client_id = host->clients[i].client_id;
      SAFE_STRNCPY(info->ip_address, host->clients[i].ip_address, sizeof(info->ip_address));
      info->port = host->clients[i].port;
      info->video_active = host->clients[i].video_active;
      info->audio_active = host->clients[i].audio_active;
      info->connected_at = host->clients[i].connected_at;
      mutex_unlock(&host->clients_mutex);
      return ASCIICHAT_OK;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return SET_ERRNO(ERROR_NOT_FOUND, "Client not found: %u", client_id);
}
References session_host_client_t::active, session_host_client_info_t::audio_active, session_host_client_t::audio_active, session_host_client_info_t::client_id, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host_client_info_t::connected_at, session_host_client_t::connected_at, session_host::initialized, session_host_client_info_t::ip_address, session_host_client_t::ip_address, session_host::max_clients, session_host_client_info_t::port, session_host_client_t::port, session_host_client_info_t::video_active, and session_host_client_t::video_active.
session_host_get_client_count()
int session_host_get_client_count (session_host_t * host)
#include <src/common/session/host.h>
Get number of connected clients.
Parameters
host Host handle (can be NULL)
Returns
Number of connected clients, 0 if NULL
Definition at line 1229 of file host.c.
{
  if (!host || !host->initialized) {
    return 0;
  }
  return host->client_count;
}
References session_host::client_count, and session_host::initialized.
session_host_get_client_ids()
int session_host_get_client_ids (session_host_t * host, uint32_t * ids, int max_ids)
#include <src/common/session/host.h>
Get list of all connected client IDs.
Parameters
host Host handle (must not be NULL)
ids Output array for client IDs (must not be NULL)
max_ids Maximum number of IDs to return (size of ids array)
Returns
Number of IDs written to array
Definition at line 1236 of file host.c.
{
  if (!host || !host->initialized || !ids || max_ids <= 0) {
    return 0;
  }
  mutex_lock(&host->clients_mutex);
  int count = 0;
  for (int i = 0; i < host->max_clients && count < max_ids; i++) {
    if (host->clients[i].active) {
      ids[count++] = host->clients[i].client_id;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return count;
}
References session_host_client_t::active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host::initialized, and session_host::max_clients.
session_host_get_client_transport()
acip_transport_t * session_host_get_client_transport (session_host_t * host, uint32_t client_id)
#include <src/common/session/host.h>
Get the current transport for a specific client in the host.
Returns the currently active transport for the client, if any. May return NULL if only socket transport is in use.
Parameters
host Host handle (must not be NULL)
client_id Client ID whose transport should be retrieved
Returns
Transport pointer if set, NULL if using socket transport or client not found
Definition at line 1441 of file host.c.
{
  if (!host || !host->initialized) {
    return NULL;
  }
  mutex_lock(&host->clients_mutex);
  // Find client with matching ID
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].client_id == client_id) {
      acip_transport_t *transport = host->clients[i].transport;
      mutex_unlock(&host->clients_mutex);
      return transport;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return NULL;
}
References session_host_client_t::active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host::initialized, session_host::max_clients, and session_host_client_t::transport.
session_host_inject_audio()
asciichat_error_t session_host_inject_audio (session_host_t * host, uint32_t participant_id, const float * samples, size_t count)
#include <src/common/session/host.h>
Inject audio samples from memory participant.
Parameters
host Host handle (must not be NULL)
participant_id Memory participant ID
samples Audio sample buffer (float format, must not be NULL)
count Number of samples
Returns
ASCIICHAT_OK on success, error code on failure
Injects audio samples directly into the mixer from a memory participant. This bypasses network I/O and is used when the host participates in the session with their own audio.
Note
Sample data is copied, so caller retains ownership.
Definition at line 1117 of file host.c.
{
  if (!host || !host->initialized || !samples || count == 0) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_inject_audio: invalid parameters");
  }
  mutex_lock(&host->clients_mutex);
  // Find memory participant
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].client_id == participant_id &&
        host->clients[i].participant_type == PARTICIPANT_TYPE_MEMORY) {
      if (!host->clients[i].incoming_audio) {
        mutex_unlock(&host->clients_mutex);
        return SET_ERRNO(ERROR_INVALID_STATE, "Memory participant has no audio buffer");
      }
      // Write samples to ringbuffer (one at a time)
      size_t written = 0;
      for (size_t j = 0; j < count; j++) {
        if (ringbuffer_write(host->clients[i].incoming_audio, &samples[j])) {
          written++;
        } else {
          break; // Buffer full
        }
      }
      if (written < count) {
        log_warn_every(NS_PER_MS_INT, "Audio ringbuffer full, dropped %zu samples", count - written);
      }
      host->clients[i].audio_active = true;
      mutex_unlock(&host->clients_mutex);
      return ASCIICHAT_OK;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return SET_ERRNO(ERROR_NOT_FOUND, "Memory participant not found");
}
References session_host_client_t::active, session_host_client_t::audio_active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host_client_t::incoming_audio, session_host::initialized, session_host::max_clients, participant_id, session_host_client_t::participant_type, and ringbuffer_write().
session_host_inject_frame()
asciichat_error_t session_host_inject_frame (session_host_t * host, uint32_t participant_id, const image_t * frame)
#include <src/common/session/host.h>
Inject a video frame from memory participant.
Parameters
host Host handle (must not be NULL)
participant_id Memory participant ID
frame Video frame image (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Injects a video frame directly into the mixer from a memory participant. This bypasses network I/O and is used when the host participates in the session with their own webcam.
Note
Frame data is copied, so caller retains ownership.
Definition at line 1072 of file host.c.
{
  if (!host || !host->initialized || !frame) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_inject_frame: invalid parameters");
  }
  mutex_lock(&host->clients_mutex);
  // Find memory participant
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].client_id == participant_id &&
        host->clients[i].participant_type == PARTICIPANT_TYPE_MEMORY) {
      if (!host->clients[i].incoming_video) {
        mutex_unlock(&host->clients_mutex);
        return SET_ERRNO(ERROR_INVALID_STATE, "Memory participant has no video buffer");
      }
      // Copy frame data into buffer
      image_t *dest = host->clients[i].incoming_video;
      if (dest->w != frame->w || dest->h != frame->h) {
        // Reallocate if size changed
        image_destroy(dest);
        dest = image_new(frame->w, frame->h);
        if (!dest) {
          host->clients[i].incoming_video = NULL;
          mutex_unlock(&host->clients_mutex);
          return SET_ERRNO(ERROR_MEMORY, "Failed to reallocate video buffer");
        }
        host->clients[i].incoming_video = dest;
      }
      // Copy pixel data
      memcpy(dest->pixels, frame->pixels, frame->w * frame->h * sizeof(rgb_pixel_t));
      host->clients[i].video_active = true;
      mutex_unlock(&host->clients_mutex);
      return ASCIICHAT_OK;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return SET_ERRNO(ERROR_NOT_FOUND, "Memory participant not found");
}
References session_host_client_t::active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, frame, image_destroy(), image_new(), session_host_client_t::incoming_video, session_host::initialized, session_host::max_clients, participant_id, session_host_client_t::participant_type, and session_host_client_t::video_active.
session_host_is_running()
bool session_host_is_running (session_host_t * host)
#include <src/common/session/host.h>
Check if host is running.
Parameters
host Host handle (can be NULL)
Returns
true if running, false otherwise
Definition at line 917 of file host.c.
{
  if (!host || !host->initialized) {
    return false;
  }
  return host->running;
}
References session_host::initialized, and session_host::running.
session_host_remove_client()
asciichat_error_t session_host_remove_client (session_host_t * host, uint32_t client_id)
#include <src/common/session/host.h>
Remove a client by ID.
Parameters
host Host handle (must not be NULL)
client_id Client ID to remove
Returns
ASCIICHAT_OK on success, error code on failure
Disconnects and removes a client from the session.
Note
on_client_leave callback is invoked before removal.
Definition at line 1160 of file host.c.
{
  if (!host || !host->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_remove_client: invalid host");
  }
  mutex_lock(&host->clients_mutex);
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].client_id == client_id) {
      // Invoke callback before removing
      mutex_unlock(&host->clients_mutex);
      if (host->callbacks.on_client_leave) {
        host->callbacks.on_client_leave(host, client_id, host->user_data);
      }
      mutex_lock(&host->clients_mutex);
      // Close socket
      if (host->clients[i].socket != INVALID_SOCKET_VALUE) {
        socket_close(host->clients[i].socket);
        host->clients[i].socket = INVALID_SOCKET_VALUE;
      }
      // Clean up media buffers
      if (host->clients[i].incoming_video) {
        image_destroy(host->clients[i].incoming_video);
        host->clients[i].incoming_video = NULL;
      }
      if (host->clients[i].incoming_audio) {
        ringbuffer_destroy(host->clients[i].incoming_audio);
        host->clients[i].incoming_audio = NULL;
      }
      host->clients[i].active = false;
      host->client_count--;
      mutex_unlock(&host->clients_mutex);
      return ASCIICHAT_OK;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return SET_ERRNO(ERROR_NOT_FOUND, "Client not found: %u", client_id);
}
References session_host_client_t::active, session_host::callbacks, session_host::client_count, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, image_destroy(), session_host_client_t::incoming_audio, session_host_client_t::incoming_video, session_host::initialized, session_host::max_clients, session_host_callbacks_t::on_client_leave, ringbuffer_destroy(), session_host_client_t::socket, and session_host::user_data.
Referenced by remove_client().
session_host_send_frame()
asciichat_error_t session_host_send_frame (session_host_t * host, uint32_t client_id, const char * frame)
#include <src/common/session/host.h>
Send ASCII frame to a specific client.
Parameters
host Host handle (must not be NULL)
client_id Target client ID
frame ASCII frame data (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Definition at line 1287 of file host.c.
{
  if (!host || !host->initialized || !frame) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_send_frame: invalid parameter");
  }
  if (!host->running) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_host_send_frame: not running");
  }
  // Send ASCII frame to specific client
  size_t frame_len = strlen(frame) + 1; // Include null terminator
  mutex_lock(&host->clients_mutex);
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].client_id == client_id && host->clients[i].active &&
        host->clients[i].socket != INVALID_SOCKET_VALUE) {
      asciichat_error_t result =
          packet_send(host->clients[i].socket, PACKET_TYPE_ASCII_FRAME, (const void *)frame, frame_len);
      mutex_unlock(&host->clients_mutex);
      return result;
    }
  }
  mutex_unlock(&host->clients_mutex);
  return SET_ERRNO(ERROR_NOT_FOUND, "session_host_send_frame: client %u not found", client_id);
}
References session_host_client_t::active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, frame, session_host::initialized, session_host::max_clients, packet_send(), session_host::running, and session_host_client_t::socket.
session_host_set_client_transport()
asciichat_error_t session_host_set_client_transport (session_host_t * host, uint32_t client_id, acip_transport_t * transport)
#include <src/common/session/host.h>
Set an alternative transport for a specific client in the host.
Allows replacing a client's default TCP socket transport with an alternative transport such as WebRTC DataChannel. Once set, the host will use this transport for send/receive operations with the specified client.
Parameters
host Host handle (must not be NULL)
client_id Client ID whose transport should be replaced
transport Alternative transport to use (can be NULL to clear)
Returns
ASCIICHAT_OK on success, ERROR_NOT_FOUND if client not found, other error on failure
Note
This is used for WebRTC integration when DataChannel becomes ready
Transport ownership remains with caller (host does not free it)
If both socket and transport exist, transport takes precedence
Definition at line 1409 of file host.c.
{
  if (!host || !host->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Host is NULL or not initialized");
  }
  mutex_lock(&host->clients_mutex);
  // Find client with matching ID
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active && host->clients[i].client_id == client_id) {
      log_info("session_host_set_client_transport: Setting transport=%p for client %u (was=%p)", transport, client_id,
               host->clients[i].transport);
      host->clients[i].transport = transport;
      if (transport) {
        log_info("WebRTC transport now active for client %u", client_id);
      } else {
        log_info("WebRTC transport cleared for client %u, reverting to socket", client_id);
      }
      mutex_unlock(&host->clients_mutex);
      return ASCIICHAT_OK;
    }
  }
  mutex_unlock(&host->clients_mutex);
  log_warn("Client %u not found", client_id);
  return SET_ERRNO(ERROR_NOT_FOUND, "Client not found");
}
References session_host_client_t::active, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host::initialized, session_host::max_clients, and session_host_client_t::transport.
session_host_start()
asciichat_error_t session_host_start (session_host_t * host)
#include <src/common/session/host.h>
Start accepting client connections.
Parameters
host Host handle (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Binds to the configured port and starts accepting connections. This function may start background threads for connection handling.
Definition at line 797 of file host.c.
{
  if (!host || !host->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_start: invalid host");
  }
  if (host->running) {
    return ASCIICHAT_OK; // Already running
  }
  // Create listen socket(s)
  // For simplicity, we bind to IPv4 if specified, otherwise default to 0.0.0.0
  const char *bind_address = host->ipv4_address[0] ? host->ipv4_address : "0.0.0.0";
  host->socket_v4 = create_listen_socket(bind_address, host->port);
  if (host->socket_v4 == INVALID_SOCKET_VALUE) {
    log_error("Failed to create IPv4 listen socket");
    if (host->callbacks.on_error) {
      host->callbacks.on_error(host, ERROR_NETWORK_BIND, "Failed to create listen socket", host->user_data);
    }
    return GET_ERRNO();
  }
  host->running = true;
  log_info("Session host listening on %s:%d", bind_address, host->port);
  // Spawn accept loop thread
  host->accept_thread_running = true;
  if (asciichat_thread_create(&host->accept_thread, "accept", accept_loop_thread, host) != 0) {
    log_error("Failed to spawn accept loop thread");
    host->accept_thread_running = false;
    if (host->callbacks.on_error) {
      host->callbacks.on_error(host, ERROR_THREAD, "Failed to spawn accept loop thread", host->user_data);
    }
    socket_close(host->socket_v4);
    host->socket_v4 = INVALID_SOCKET_VALUE;
    host->running = false;
    return SET_ERRNO(ERROR_THREAD, "Failed to spawn accept loop thread");
  }
  // Spawn receive loop thread
  host->receive_thread_running = true;
  if (asciichat_thread_create(&host->receive_thread, "host_recv", receive_loop_thread, host) != 0) {
    log_error("Failed to spawn receive loop thread");
    host->receive_thread_running = false;
    host->accept_thread_running = false;
    asciichat_thread_join(&host->accept_thread, NULL);
    if (host->callbacks.on_error) {
      host->callbacks.on_error(host, ERROR_THREAD, "Failed to spawn receive loop thread", host->user_data);
    }
    socket_close(host->socket_v4);
    host->socket_v4 = INVALID_SOCKET_VALUE;
    host->running = false;
    return SET_ERRNO(ERROR_THREAD, "Failed to spawn receive loop thread");
  }
  // Spawn render thread (optional - can be started later)
  // This thread handles video mixing and audio distribution
  return ASCIICHAT_OK;
}
References session_host::accept_thread, session_host::accept_thread_running, asciichat_thread_create(), asciichat_thread_join(), session_host::callbacks, session_host::initialized, session_host::ipv4_address, session_host_callbacks_t::on_error, session_host::port, session_host::receive_thread, session_host::receive_thread_running, session_host::running, session_host::socket_v4, and session_host::user_data.
Referenced by discovery_session_become_host(), and discovery_session_process().
session_host_start_render()
asciichat_error_t session_host_start_render (session_host_t * host)
#include <src/common/session/host.h>
Start media rendering thread (video mixing and audio distribution).
Parameters
host Host handle (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Starts the render thread which collects video frames from all participants, generates mixed ASCII frames, and broadcasts them to all clients. Also handles audio mixing and distribution.
Note
The host must be running before starting the render thread.
Call session_host_stop_render() to stop the thread.
Definition at line 1318 of file host.c.
{
  if (!host || !host->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_host_start_render: invalid host");
  }
  if (!host->running) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_host_start_render: not running");
  }
  if (host->render_thread_running) {
    return ASCIICHAT_OK; // Already running
  }
  // Create audio context for mixing (host mode = true)
  if (!host->audio_ctx) {
    host->audio_ctx = session_audio_create(true);
    if (!host->audio_ctx) {
      return SET_ERRNO(ERROR_INVALID_STATE, "Failed to create audio context");
    }
  }
  // Create Opus decoder for decoding incoming Opus audio (48kHz)
  if (!host->opus_decoder) {
    host->opus_decoder = opus_codec_create_decoder(48000);
    if (!host->opus_decoder) {
      session_audio_destroy(host->audio_ctx);
      host->audio_ctx = NULL;
      return SET_ERRNO(ERROR_INVALID_STATE, "Failed to create Opus decoder");
    }
  }
  // Create Opus encoder for encoding mixed audio for broadcast (48kHz, VOIP mode, 24kbps)
  if (!host->opus_encoder) {
    host->opus_encoder = opus_codec_create_encoder(OPUS_APPLICATION_VOIP, 48000, 24000);
    if (!host->opus_encoder) {
      opus_codec_destroy(host->opus_decoder);
      host->opus_decoder = NULL;
      session_audio_destroy(host->audio_ctx);
      host->audio_ctx = NULL;
      return SET_ERRNO(ERROR_INVALID_STATE, "Failed to create Opus encoder");
    }
  }
  // Spawn render thread
  host->render_thread_running = true;
  if (asciichat_thread_create(&host->render_thread, "render", host_render_thread, host) != 0) {
    log_error("Failed to spawn render thread");
    host->render_thread_running = false;
    return SET_ERRNO(ERROR_THREAD, "Failed to spawn render thread");
  }
  log_info("Host render thread started");
  return ASCIICHAT_OK;
}
References asciichat_thread_create(), session_host::audio_ctx, session_host::initialized, opus_codec_create_decoder(), opus_codec_create_encoder(), opus_codec_destroy(), session_host::opus_decoder, session_host::opus_encoder, session_host::render_thread, session_host::render_thread_running, session_host::running, session_audio_create(), and session_audio_destroy().
session_host_stop()
void session_host_stop (session_host_t * host)
#include <src/common/session/host.h>
Stop accepting connections and disconnect all clients.
Parameters
host Host handle (must not be NULL)
Gracefully stops the server, disconnects all clients, and cleans up.
Definition at line 857 of file host.c.
{
  if (!host || !host->initialized || !host->running) {
    return;
  }
  // Stop render thread if running
  if (host->render_thread_running) {
    host->render_thread_running = false;
    asciichat_thread_join(&host->render_thread, NULL);
    log_info("Render thread joined");
  }
  // Stop receive loop thread (reads from client sockets)
  if (host->receive_thread_running) {
    host->receive_thread_running = false;
    asciichat_thread_join(&host->receive_thread, NULL);
    log_info("Receive loop thread joined");
  }
  // Stop accept loop thread (before closing listen socket)
  if (host->accept_thread_running) {
    host->accept_thread_running = false;
    asciichat_thread_join(&host->accept_thread, NULL);
    log_info("Accept loop thread joined");
  }
  // Disconnect all clients
  mutex_lock(&host->clients_mutex);
  for (int i = 0; i < host->max_clients; i++) {
    if (host->clients[i].active) {
      // Invoke callback
      if (host->callbacks.on_client_leave) {
        host->callbacks.on_client_leave(host, host->clients[i].client_id, host->user_data);
      }
      // Close socket
      if (host->clients[i].socket != INVALID_SOCKET_VALUE) {
        socket_close(host->clients[i].socket);
        host->clients[i].socket = INVALID_SOCKET_VALUE;
      }
      host->clients[i].active = false;
    }
  }
  host->client_count = 0;
  mutex_unlock(&host->clients_mutex);
  // Close listen sockets
  if (host->socket_v4 != INVALID_SOCKET_VALUE) {
    socket_close(host->socket_v4);
    host->socket_v4 = INVALID_SOCKET_VALUE;
  }
  if (host->socket_v6 != INVALID_SOCKET_VALUE) {
    socket_close(host->socket_v6);
    host->socket_v6 = INVALID_SOCKET_VALUE;
  }
  host->running = false;
}
References session_host::accept_thread, session_host::accept_thread_running, session_host_client_t::active, asciichat_thread_join(), session_host::callbacks, session_host::client_count, session_host_client_t::client_id, session_host::clients, session_host::clients_mutex, session_host::initialized, session_host::max_clients, session_host_callbacks_t::on_client_leave, session_host::receive_thread, session_host::receive_thread_running, session_host::render_thread, session_host::render_thread_running, session_host::running, session_host_client_t::socket, session_host::socket_v4, session_host::socket_v6, and session_host::user_data.
Referenced by session_host_destroy().
session_host_stop_render()
void session_host_stop_render (session_host_t * host)
#include <src/common/session/host.h>
Stop media rendering thread.
Parameters
host Host handle (must not be NULL)
Gracefully stops the render thread and cleans up audio resources.
Definition at line 1373 of file host.c.
{
  if (!host || !host->initialized) {
    return;
  }
  if (!host->render_thread_running) {
    return;
  }
  // Signal thread to stop
  host->render_thread_running = false;
  // Wait for thread to complete
  asciichat_thread_join(&host->render_thread, NULL);
  // Clean up audio resources
  if (host->audio_ctx) {
    session_audio_destroy(host->audio_ctx);
    host->audio_ctx = NULL;
  }
  if (host->opus_decoder) {
    opus_codec_destroy(host->opus_decoder);
    host->opus_decoder = NULL;
  }
  if (host->opus_encoder) {
    opus_codec_destroy(host->opus_encoder);
    host->opus_encoder = NULL;
  }
  log_info("Host render thread stopped");
}
References asciichat_thread_join(), session_host::audio_ctx, session_host::initialized, opus_codec_destroy(), session_host::opus_decoder, session_host::opus_encoder, session_host::render_thread, session_host::render_thread_running, and session_audio_destroy().
session_mirror_capture_create()
session_capture_ctx_t * session_mirror_capture_create (const session_capture_config_t * config)
#include <src/common/session/capture.h>
Create a new session capture context.
Parameters
config Capture configuration (must not be NULL)
Returns
Pointer to capture context, or NULL on failure
Creates and initializes a session capture context with the specified configuration. The media source is opened and ready for reading.
Note
Call session_capture_destroy() to free resources when done.
On failure, sets asciichat_errno with error details.
Create mirror mode capture context with local media source
Creates a capture context for local media (webcam, file, URL, test pattern). Used by mirror mode and snapshot operations that need to capture video locally.
Parameters
config Capture configuration (type, path, FPS, etc.)
Returns
Capture context with media source, or NULL on error
Note
Call session_capture_destroy() to free resources when done.
On failure, sets asciichat_errno with error details.
Definition at line 143 of file common/session/capture.c.
{
  // Mirror capture requires a config with media source info
  if (!config) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Mirror capture requires explicit config"), NULL;
  }
  // Delegate to the main implementation
  return session_capture_create(config);
}
References session_capture_create().
Referenced by session_client_like_run().
session_network_capture_create()
session_capture_ctx_t * session_network_capture_create (uint32_t target_fps)
#include <src/common/session/capture.h>
Create network mode capture context without media source.
Creates a minimal capture context for network modes (client, discovery) that receive video frames from the network instead of capturing locally. Only initializes keyboard and audio support; no media source is created.
Parameters
target_fps Target FPS (0 = default 60 FPS)
Returns
Capture context without media source, or NULL on error
Note
Call session_capture_destroy() to free resources when done.
On failure, sets asciichat_errno with error details.
Definition at line 153 of file common/session/capture.c.
{
  // Network modes don't capture media - create minimal context for keyboard/audio only
  session_capture_ctx_t *ctx = SAFE_CALLOC(1, sizeof(session_capture_ctx_t), session_capture_ctx_t *);
  if (!ctx) {
    return NULL;
  }
  // Set FPS (use provided value or default to 60)
  ctx->target_fps = target_fps > 0 ? target_fps : 60;
  ctx->resize_for_network = false;
  // Audio and keyboard will be set up separately by callers
  ctx->audio_enabled = false;
  ctx->source = NULL;
  // Initialize adaptive sleep for consistency
  uint64_t baseline_sleep_ns = NS_PER_SEC_INT / ctx->target_fps;
  adaptive_sleep_config_t sleep_config = {.baseline_sleep_ns = baseline_sleep_ns,
                                          .min_speed_multiplier = 0.5,
                                          .max_speed_multiplier = 2.0,
                                          .speedup_rate = 0.1,
                                          .slowdown_rate = 0.1};
  adaptive_sleep_init(&ctx->sleep_state, &sleep_config);
  // Initialize minimal FPS tracker (won't be used but keep structure consistent)
  char *tracker_name = SAFE_MALLOC(32, char *);
  if (!tracker_name) {
    SAFE_FREE(ctx);
    return NULL;
  }
  safe_snprintf(tracker_name, 32, "NETWORK_CAPTURE");
  fps_init(&ctx->fps_tracker, 60, tracker_name);
  ctx->start_time_ns = time_get_ns();
  ctx->initialized = true;
  log_debug("Created network capture context (no local media source)");
  return ctx;
}
References adaptive_sleep_init(), session_capture_ctx::audio_enabled, fps_init(), session_capture_ctx::fps_tracker, session_capture_ctx::initialized, session_capture_ctx::resize_for_network, safe_snprintf(), session_capture_ctx::sleep_state, session_capture_ctx::source, session_capture_ctx::start_time_ns, session_capture_ctx::target_fps, and time_get_ns().
Referenced by session_client_like_run().
session_participant_connect()
asciichat_error_t session_participant_connect (session_participant_t * p)
#include <src/common/session/participant.h>
Connect to session server.
Parameters
p Participant handle (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Initiates connection to the configured server. Connection establishment is synchronous but callbacks are invoked asynchronously.
Note
on_connected callback is invoked on successful connection.
on_error callback is invoked on failure.
Definition at line 272 of file participant.c.
{
  log_debug("session_participant_connect: enter - p=%p", p);
  if (!p || !p->initialized) {
    log_debug("session_participant_connect: invalid param or not initialized");
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_connect: invalid participant");
  }
  log_debug("session_participant_connect: p->initialized=%d, p->connected=%d", p->initialized, p->connected);
  if (p->connected) {
    log_debug("session_participant_connect: already connected, returning OK");
    return ASCIICHAT_OK; // Already connected
  }
  // Create TCP connection to server
  log_debug("session_participant_connect: calling connect_to_server(%s, %d)", p->address, p->port);
  p->socket = connect_to_server(p->address, p->port);
  log_debug("session_participant_connect: connect_to_server returned socket=%d (INVALID=%d)", p->socket,
            INVALID_SOCKET_VALUE);
  if (p->socket == INVALID_SOCKET_VALUE) {
    log_error("Failed to connect to server at %s:%d", p->address, p->port);
    if (p->callbacks.on_error) {
      p->callbacks.on_error(p, ERROR_NETWORK_CONNECT, "Failed to connect to server", p->user_data);
    }
    return GET_ERRNO();
  }
  log_debug("session_participant_connect: setting p->connected=true");
  p->connected = true;
  p->client_id = 0; // Will be assigned by server
  log_info("Connected to server at %s:%d (socket=%d)", p->address, p->port, p->socket);
  log_debug("session_participant_connect: p->connected=%d after setting", p->connected);
  // Invoke callback
  if (p->callbacks.on_connected) {
    p->callbacks.on_connected(p, p->client_id, p->user_data);
  }
  log_debug("session_participant_connect: returning ASCIICHAT_OK");
  return ASCIICHAT_OK;
}
References session_participant::address, session_participant::callbacks, session_participant::client_id, session_participant::connected, session_participant::initialized, session_participant_callbacks_t::on_connected, session_participant_callbacks_t::on_error, session_participant::port, session_participant::socket, and session_participant::user_data.
Referenced by discovery_session_connect_to_future_host(), and discovery_session_process().
session_participant_create()
session_participant_t * session_participant_create (const session_participant_config_t * config)
#include <src/common/session/participant.h>
Create a new session participant.
Parameters
config Participant configuration (must not be NULL)
Returns
Pointer to participant handle, or NULL on failure
Creates a session participant with the specified configuration. The participant is not connected until session_participant_connect() is called.
Note
Call session_participant_destroy() to free resources when done.
On failure, sets asciichat_errno with error details.
Definition at line 121 of file participant.c.
{
  log_info("session_participant_create: START - config=%p", config);
  if (!config) {
    log_error("session_participant_create: config is NULL");
    SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_create: NULL config");
    return NULL;
  }
  // Allocate participant
  session_participant_t *p = SAFE_CALLOC(1, sizeof(session_participant_t), session_participant_t *);
  log_info("session_participant_create: allocated p=%p", p);
  // Copy configuration
  if (config->address) {
    SAFE_STRNCPY(p->address, config->address, sizeof(p->address));
  } else {
    SAFE_STRNCPY(p->address, "127.0.0.1", sizeof(p->address));
  }
  p->port = config->port > 0 ? config->port : OPT_PORT_INT_DEFAULT;
  p->encryption_enabled = config->encryption_enabled;
  log_info("session_participant_create: address=%s, port=%d", p->address, p->port);
  if (config->password) {
    SAFE_STRNCPY(p->password, config->password, sizeof(p->password));
  }
  if (config->server_key) {
    SAFE_STRNCPY(p->server_key, config->server_key, sizeof(p->server_key));
  }
  p->enable_audio = config->enable_audio;
  p->enable_video = config->enable_video;
  p->callbacks = config->callbacks;
  p->user_data = config->user_data;
  // Initialize socket to invalid
  p->socket = INVALID_SOCKET_VALUE;
  p->transport = NULL; // No alternative transport initially
  p->connected = false;
  p->client_id = 0;
  p->video_active = false;
  p->audio_active = false;
  // Initialize settings
  session_settings_init(&p->settings);
  p->initialized = true;
  log_info("session_participant_create: DONE - returning p=%p (initialized=%d, connected=%d)", p, p->initialized,
           p->connected);
  return p;
}
References session_participant::address, session_participant_config_t::address, session_participant::audio_active, session_participant::callbacks, session_participant_config_t::callbacks, session_participant::client_id, session_participant::connected, session_participant::enable_audio, session_participant_config_t::enable_audio, session_participant::enable_video, session_participant_config_t::enable_video, session_participant::encryption_enabled, session_participant_config_t::encryption_enabled, session_participant::initialized, session_participant::password, session_participant_config_t::password, session_participant::port, session_participant_config_t::port, session_participant::server_key, session_participant_config_t::server_key, session_settings_init(), session_participant::settings, session_participant::socket, session_participant::transport, session_participant::user_data, session_participant_config_t::user_data, and session_participant::video_active.
Referenced by discovery_session_connect_to_future_host(), and discovery_session_process().
session_participant_destroy()
void session_participant_destroy (session_participant_t * p)
#include <src/common/session/participant.h>
Destroy session participant and free resources.
Parameters
p Participant to destroy (can be NULL)
Disconnects if connected, stops all streams, and releases all resources. Safe to call with NULL.
Definition at line 176 of file participant.c.
{
  if (!p) {
    return;
  }
  // Disconnect if connected
  if (p->connected) {
    session_participant_disconnect(p);
  }
  // Stop capture threads if running
  if (p->video_capture_running) {
    session_participant_stop_video_capture(p);
  }
  if (p->audio_capture_running) {
    session_participant_stop_audio_capture(p);
  }
  // Clean up media capture contexts
  if (p->video_capture) {
    session_capture_destroy(p->video_capture);
    p->video_capture = NULL;
  }
  if (p->audio_capture) {
    session_audio_destroy(p->audio_capture);
    p->audio_capture = NULL;
  }
  if (p->opus_encoder) {
    opus_codec_destroy(p->opus_encoder);
    p->opus_encoder = NULL;
  }
  // Close socket if open
  if (p->socket != INVALID_SOCKET_VALUE) {
    socket_close(p->socket);
    p->socket = INVALID_SOCKET_VALUE;
  }
  // Clear sensitive data
  memset(p->password, 0, sizeof(p->password));
  memset(p->server_key, 0, sizeof(p->server_key));
  p->initialized = false;
  SAFE_FREE(p);
}
References session_participant::audio_capture, session_participant::audio_capture_running, session_participant::connected, session_participant::initialized, opus_codec_destroy(), session_participant::opus_encoder, session_participant::password, session_participant::server_key, session_audio_destroy(), session_capture_destroy(), session_participant_disconnect(), session_participant_stop_audio_capture(), session_participant_stop_video_capture(), session_participant::socket, session_participant::video_capture, and session_participant::video_capture_running.
Referenced by discovery_session_connect_to_future_host(), and discovery_session_destroy().
session_participant_disconnect()
void session_participant_disconnect (session_participant_t * p)
#include <src/common/session/participant.h>
Disconnect from session server.
Parameters
p Participant handle (must not be NULL)
Gracefully disconnects from the server and stops all streams.
Note
on_disconnected callback is invoked after disconnection.
Definition at line 317 of file participant.c.
{
  if (!p || !p->initialized) {
    return;
  }
  if (!p->connected) {
    return;
  }
  // Stop media streams
  if (p->video_active) {
    session_participant_stop_video(p);
  }
  if (p->audio_active) {
    session_participant_stop_audio(p);
  }
  // Close socket
  if (p->socket != INVALID_SOCKET_VALUE) {
    socket_close(p->socket);
    p->socket = INVALID_SOCKET_VALUE;
  }
  p->connected = false;
  p->client_id = 0;
  // Invoke callback
  if (p->callbacks.on_disconnected) {
    p->callbacks.on_disconnected(p, p->user_data);
  }
}
References session_participant::audio_active, session_participant::callbacks, session_participant::client_id, session_participant::connected, session_participant::initialized, session_participant_callbacks_t::on_disconnected, session_participant_stop_audio(), session_participant_stop_video(), session_participant::socket, session_participant::user_data, and session_participant::video_active.
Referenced by discovery_session_process(), and session_participant_destroy().
session_participant_get_client_id()
uint32_t session_participant_get_client_id (session_participant_t * p)
#include <src/common/session/participant.h>
Get assigned client ID.
Parameters
p Participant handle (can be NULL)
Returns
Client ID if connected, 0 otherwise
Definition at line 356 of file participant.c.
{
  if (!p || !p->initialized || !p->connected) {
    return 0;
  }
  return p->client_id;
}
References session_participant::client_id, session_participant::connected, and session_participant::initialized.
session_participant_get_settings()
asciichat_error_t session_participant_get_settings (session_participant_t * p, session_settings_t * settings)
#include <src/common/session/participant.h>
Get current session settings.
Parameters
p Participant handle (must not be NULL)
settings Output settings structure (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Definition at line 466 of file participant.c.
{
  if (!p || !p->initialized || !settings) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_get_settings: invalid parameter");
  }
  memcpy(settings, &p->settings, sizeof(session_settings_t));
  return ASCIICHAT_OK;
}
References session_participant::initialized, and session_participant::settings.
session_participant_get_socket()
socket_t session_participant_get_socket (session_participant_t * p)
#include <src/common/session/participant.h>
Get the socket from a participant context.
Parameters
p Participant handle (must not be NULL)
Returns
The socket file descriptor, or INVALID_SOCKET_VALUE if not connected
Definition at line 363 of file participant.c.
{
  if (!p || !p->initialized) {
    return INVALID_SOCKET_VALUE;
  }
  return p->socket;
}
References session_participant::initialized, and session_participant::socket.
Referenced by discovery_session_check_host_alive(), and discovery_session_process().
session_participant_get_transport()
acip_transport_t * session_participant_get_transport (session_participant_t * p)
#include <src/common/session/participant.h>
Get the current transport for the participant.
Returns the currently active transport, if any. May return NULL if only socket transport is in use.
Parameters
p Participant handle (must not be NULL)
Returns
Transport pointer if set, NULL if using socket transport
Definition at line 744 of file participant.c.
{
  if (!p || !p->initialized) {
    return NULL;
  }
  return p->transport;
}
References session_participant::initialized, and session_participant::transport.
session_participant_has_transport()
bool session_participant_has_transport (session_participant_t * p)
#include <src/common/session/participant.h>
Check if participant has an active alternative transport.
Convenient way to check if the participant is using an alternative transport (WebRTC, WebSocket, etc.) instead of raw TCP socket.
Parameters
p Participant handle (can be NULL)
Returns
true if alternative transport is set, false otherwise
Definition at line 752 of file participant.c.
{
  if (!p) {
    return false;
  }
  return p->transport != NULL;
}
References session_participant::transport.
session_participant_is_audio_active()
bool session_participant_is_audio_active (session_participant_t * p)
#include <src/common/session/participant.h>
Check if audio is streaming.
Parameters
p Participant handle (can be NULL)
Returns
true if audio is active, false otherwise
Definition at line 455 of file participant.c.
{
  if (!p || !p->initialized) {
    return false;
  }
  return p->audio_active;
}
References session_participant::audio_active, and session_participant::initialized.
session_participant_is_connected()
bool session_participant_is_connected (session_participant_t * p)
#include <src/common/session/participant.h>
Check if participant is connected.
Parameters
p Participant handle (can be NULL)
Returns
true if connected, false otherwise
Definition at line 349 of file participant.c.
{
  if (!p || !p->initialized) {
    return false;
  }
  return p->connected;
}
References session_participant::connected, and session_participant::initialized.
Referenced by discovery_session_process().
session_participant_is_video_active()
bool session_participant_is_video_active (session_participant_t * p)
#include <src/common/session/participant.h>
Check if video is streaming.
Parameters
p Participant handle (can be NULL)
Returns
true if video is active, false otherwise
Definition at line 411 of file participant.c.
{
  if (!p || !p->initialized) {
    return false;
  }
  return p->video_active;
}
References session_participant::initialized, and session_participant::video_active.
session_participant_request_settings()
asciichat_error_t session_participant_request_settings (session_participant_t * p, const session_settings_t * settings)
#include <src/common/session/participant.h>
Request session settings update (if permitted).
Parameters
p Participant handle (must not be NULL)
settings New settings to request (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Requests the host to update session settings. The host may accept or reject the request.
Note
Actual settings change is signaled via on_settings_changed callback.
Definition at line 475 of file participant.c.
{
  if (!p || !p->initialized || !settings) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_request_settings: invalid parameter");
  }
  if (!p->connected) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_request_settings: not connected");
  }
  // TODO: Send settings update request to server
  return SET_ERRNO(ERROR_NOT_SUPPORTED, "session_participant_request_settings: not implemented yet");
}
References session_participant::connected, and session_participant::initialized.
session_participant_set_transport()
asciichat_error_t session_participant_set_transport (session_participant_t * p, acip_transport_t * transport)
#include <src/common/session/participant.h>
Set an alternative transport for the participant.
Allows replacing the default TCP socket transport with an alternative transport such as WebRTC DataChannel. Once set, the participant will use this transport for send/receive operations.
Parameters
p Participant handle (must not be NULL)
transport Alternative transport to use (can be NULL to clear)
Returns
ASCIICHAT_OK on success, error code on failure
Note
This is used for WebRTC integration when DataChannel becomes ready
Transport ownership remains with caller (participant does not free it)
If both socket and transport exist, transport takes precedence
Definition at line 726 of file participant.c.
{
  if (!p || !p->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Participant is NULL or not initialized");
  }
  log_info("session_participant_set_transport: Setting transport=%p (was=%p)", transport, p->transport);
  p->transport = transport;
  if (transport) {
    log_info("WebRTC transport now active for participant");
  } else {
    log_info("WebRTC transport cleared, reverting to socket");
  }
  return ASCIICHAT_OK;
}
References session_participant::initialized, and session_participant::transport.
session_participant_start_audio()
asciichat_error_t session_participant_start_audio (session_participant_t * p)
#include <src/common/session/participant.h>
Start audio capture and streaming.
Parameters
p Participant handle (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Starts capturing audio from the microphone and streaming to the server. Also starts audio playback for receiving audio from other participants.
Definition at line 418 of file participant.c.
{
  if (!p || !p->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_start_audio: invalid participant");
  }
  if (!p->connected) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_audio: not connected");
  }
  if (p->audio_active) {
    return ASCIICHAT_OK; // Already active
  }
  if (!p->enable_audio) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_audio: audio not enabled");
  }
  // TODO: Start audio using session_audio_ctx_t
  p->audio_active = true;
  return ASCIICHAT_OK;
}
References session_participant::audio_active, session_participant::connected, session_participant::enable_audio, and session_participant::initialized.
session_participant_start_audio_capture()
asciichat_error_t session_participant_start_audio_capture (session_participant_t * p)
#include <src/common/session/participant.h>
Start audio capture and transmission to host.
Parameters
p Participant handle (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Spawns a background thread that:
Captures audio from microphone
Encodes to Opus (lossy compression)
Sends AUDIO packets to the host
Audio capture respects the participant's enable_audio flag and connection state. Multiple calls are safe (returns OK if already running).
Note
Requires connection to be established first via session_participant_connect()
Use session_participant_stop_audio_capture() to stop transmission
Definition at line 647 of file participant.c.
{
  if (!p || !p->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_start_audio_capture: invalid participant");
  }
  if (!p->connected) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_audio_capture: not connected");
  }
  if (!p->enable_audio) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_audio_capture: audio not enabled");
  }
  if (p->audio_capture_running) {
    return ASCIICHAT_OK; // Already running
  }
  // Create audio capture context if not already created
  if (!p->audio_capture) {
    p->audio_capture = session_audio_create(false); // false = participant mode (no mixing)
    if (!p->audio_capture) {
      return SET_ERRNO(ERROR_INVALID_STATE, "Failed to create audio capture context");
    }
  }
  // Start audio capture and playback
  asciichat_error_t err = session_audio_start_duplex(p->audio_capture);
  if (err != ASCIICHAT_OK) {
    return SET_ERRNO(err, "Failed to start audio duplex");
  }
  // Create Opus encoder for audio compression (48kHz, VOIP mode, 24 kbps)
  if (!p->opus_encoder) {
    p->opus_encoder = opus_codec_create_encoder(OPUS_APPLICATION_VOIP, 48000, 24000);
    if (!p->opus_encoder) {
      session_audio_stop(p->audio_capture);
      return SET_ERRNO(ERROR_INVALID_STATE, "Failed to create Opus encoder");
    }
  }
  // Spawn audio capture thread
  p->audio_capture_running = true;
  if (asciichat_thread_create(&p->audio_capture_thread, "audio_capture", participant_audio_capture_thread, p) != 0) {
    log_error("Failed to spawn audio capture thread");
    p->audio_capture_running = false;
    return SET_ERRNO(ERROR_THREAD, "Failed to spawn audio capture thread");
  }
  log_info("Audio capture started");
  return ASCIICHAT_OK;
}
References asciichat_thread_create(), session_participant::audio_capture, session_participant::audio_capture_running, session_participant::audio_capture_thread, session_participant::connected, session_participant::enable_audio, session_participant::initialized, opus_codec_create_encoder(), session_participant::opus_encoder, session_audio_create(), session_audio_start_duplex(), and session_audio_stop().
session_participant_start_video()
asciichat_error_t session_participant_start_video (session_participant_t * p)
#include <src/common/session/participant.h>
Start video capture and streaming.
Parameters
p Participant handle (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Starts capturing video from the webcam and streaming to the server.
Definition at line 374 of file participant.c.
{
  if (!p || !p->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_start_video: invalid participant");
  }
  if (!p->connected) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_video: not connected");
  }
  if (p->video_active) {
    return ASCIICHAT_OK; // Already active
  }
  if (!p->enable_video) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_video: video not enabled");
  }
  // TODO: Start webcam capture thread using session_capture_ctx_t
  p->video_active = true;
  return ASCIICHAT_OK;
}
References session_participant::connected, session_participant::enable_video, session_participant::initialized, and session_participant::video_active.
session_participant_start_video_capture()
asciichat_error_t session_participant_start_video_capture (session_participant_t * p)
#include <src/common/session/participant.h>
Start video capture and transmission to host.
Parameters
p Participant handle (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Spawns a background thread that:
Captures video from webcam/file/test pattern
Resizes for network efficiency (bandwidth optimization)
Sends IMAGE_FRAME packets to the host
Video capture respects the participant's enable_video flag and connection state. Multiple calls are safe (returns OK if already running).
Note
Requires connection to be established first via session_participant_connect()
Use session_participant_stop_video_capture() to stop transmission
Definition at line 586 of file participant.c.
{
  if (!p || !p->initialized) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_participant_start_video_capture: invalid participant");
  }
  if (!p->connected) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_video_capture: not connected");
  }
  if (!p->enable_video) {
    return SET_ERRNO(ERROR_INVALID_STATE, "session_participant_start_video_capture: video not enabled");
  }
  if (p->video_capture_running) {
    return ASCIICHAT_OK; // Already running
  }
  // Create video capture context if not already created
  if (!p->video_capture) {
    session_capture_config_t config = {
        .type = MEDIA_SOURCE_WEBCAM,
        .path = "0", // Default device
        .target_fps = 60,
        .resize_for_network = true, // Optimize for bandwidth
    };
    p->video_capture = session_capture_create(&config);
    if (!p->video_capture) {
      return SET_ERRNO(ERROR_INVALID_STATE, "Failed to create video capture context");
    }
  }
  // Spawn video capture thread (media source is ready in ctx)
  p->video_capture_running = true;
  if (asciichat_thread_create(&p->video_capture_thread, "video_capture", participant_video_capture_thread, p) != 0) {
    log_error("Failed to spawn video capture thread");
    p->video_capture_running = false;
    return SET_ERRNO(ERROR_THREAD, "Failed to spawn video capture thread");
  }
  log_info("Video capture started");
  return ASCIICHAT_OK;
}
References asciichat_thread_create(), session_participant::connected, session_participant::enable_video, session_participant::initialized, session_capture_create(), session_participant::video_capture, session_participant::video_capture_running, and session_participant::video_capture_thread.
session_participant_stop_audio()
void session_participant_stop_audio (session_participant_t * p)
#include <src/common/session/participant.h>
Stop audio capture and streaming.
Parameters
p Participant handle (must not be NULL)
Definition at line 441 of file participant.c.
{
  if (!p || !p->initialized) {
    return;
  }
  if (!p->audio_active) {
    return;
  }
  // TODO: Stop audio
  p->audio_active = false;
}
References session_participant::audio_active, and session_participant::initialized.
Referenced by session_participant_disconnect().
session_participant_stop_audio_capture()
void session_participant_stop_audio_capture (session_participant_t * p)
#include <src/common/session/participant.h>
Stop audio capture and transmission.
Parameters
p Participant handle (must not be NULL)
Stops the audio capture background thread and cleans up resources. Safe to call if audio is not running.
Definition at line 699 of file participant.c.
{
  if (!p || !p->initialized) {
    return;
  }
  if (!p->audio_capture_running) {
    return;
  }
  // Signal thread to stop
  p->audio_capture_running = false;
  // Wait for thread to complete
  asciichat_thread_join(&p->audio_capture_thread, NULL);
  // Stop audio streams
  if (p->audio_capture) {
    session_audio_stop(p->audio_capture);
  }
  log_info("Audio capture stopped");
}
References asciichat_thread_join(), session_participant::audio_capture, session_participant::audio_capture_running, session_participant::audio_capture_thread, session_participant::initialized, and session_audio_stop().
Referenced by session_participant_destroy().
session_participant_stop_video()
void session_participant_stop_video (session_participant_t * p)
#include <src/common/session/participant.h>
Stop video capture and streaming.
Parameters
p Participant handle (must not be NULL)
Definition at line 397 of file participant.c.
{
  if (!p || !p->initialized) {
    return;
  }
  if (!p->video_active) {
    return;
  }
  // TODO: Stop webcam capture thread
  p->video_active = false;
}
References session_participant::initialized, and session_participant::video_active.
Referenced by session_participant_disconnect().
session_participant_stop_video_capture()
void session_participant_stop_video_capture (session_participant_t * p)
#include <src/common/session/participant.h>
Stop video capture and transmission.
Parameters
p Participant handle (must not be NULL)
Stops the video capture background thread and cleans up resources. Safe to call if video is not running.
Definition at line 629 of file participant.c.
{
  if (!p || !p->initialized) {
    return;
  }
  if (!p->video_capture_running) {
    return;
  }
  // Signal thread to stop
  p->video_capture_running = false;
  // Wait for thread to complete
  asciichat_thread_join(&p->video_capture_thread, NULL);
  log_info("Video capture stopped");
}
References asciichat_thread_join(), session_participant::initialized, session_participant::video_capture_running, and session_participant::video_capture_thread.
Referenced by session_participant_destroy().
session_render_loop()
asciichat_error_t session_render_loop (session_capture_ctx_t * capture, session_display_ctx_t * display, session_should_exit_fn should_exit, session_capture_fn capture_cb, session_sleep_for_frame_fn sleep_cb, session_keyboard_handler_fn keyboard_handler, void * user_data)
#include <src/common/session/render.h>
Unified render loop for all display modes.
Flexible render loop that supports both synchronous and event-driven modes. Optionally integrates keyboard input handling for interactive controls.
Synchronous Mode (capture != NULL, callbacks == NULL): Handles complete render lifecycle:
Frame rate limiting via session_capture_sleep_for_fps()
Frame capture via session_capture_read_frame()
ASCII conversion via session_display_convert_to_ascii()
Terminal rendering via session_display_render_frame()
Keyboard input polling and handling (if handler provided)
Memory cleanup with SAFE_FREE()
Used by: mirror mode, discovery participant mode
Event-Driven Mode (capture == NULL, callbacks != NULL): Delegates all frame operations to callbacks:
Custom frame capture via capture callback (can return NULL)
Custom timing via sleep_for_frame callback
ASCII conversion via session_display_convert_to_ascii()
Terminal rendering via session_display_render_frame()
Keyboard input polling and handling (if handler provided)
Memory cleanup with SAFE_FREE()
Used by: client mode, async frame sources
Keyboard Support:
If keyboard_handler is provided, initializes keyboard input at loop start
Polls for keyboard input each frame iteration
Calls keyboard_handler callback when keys are pressed
Cleans up keyboard on loop exit
Safe to pass NULL for no keyboard support (backward compatible)
Parameters
capture Capture context for synchronous mode (NULL if using callbacks)
display Display context (must not be NULL)
should_exit Callback to check exit condition each iteration (must not be NULL)
capture_cb Custom capture callback for event-driven mode (NULL if using capture context)
sleep_cb Custom sleep callback for event-driven mode (NULL if using capture context)
keyboard_handler Optional keyboard handler callback (NULL for no keyboard support)
user_data Opaque pointer passed to all callbacks
Returns
ASCIICHAT_OK on success, error code on failure
Note
Either capture XOR (capture_cb && sleep_cb) must be provided, not both
Caller must free capture and display contexts after this returns
In synchronous mode, capture callback can return NULL on frame unavailability
In event-driven mode, capture callback can return NULL gracefully
keyboard_handler is optional - pass NULL to disable keyboard support
Synchronous Example (Mirror Mode)
static bool my_should_exit(void *user_data) {
  return atomic_load(&g_exit_flag);
}
int main(void) {
  session_capture_ctx_t *capture = session_capture_create(NULL);
  session_display_ctx_t *display = session_display_create(NULL);
  platform_set_console_ctrl_handler(my_ctrl_handler);
  asciichat_error_t result = session_render_loop(
      capture, display, my_should_exit,
      NULL, NULL,  // No custom callbacks
      NULL         // No user_data needed
  );
  session_display_destroy(display);
  session_capture_destroy(capture);
  return result == ASCIICHAT_OK ? 0 : (int)result;
}
Event-Driven Example (Client Mode)
static image_t *client_capture_frame(void *user_data) {
  client_ctx_t *ctx = (client_ctx_t *)user_data;
  return network_frame_queue_pop_nonblocking(ctx->frame_queue);
}
static void client_sleep_for_frame(void *user_data) {
  client_ctx_t *ctx = (client_ctx_t *)user_data;
  if (network_frame_queue_empty(ctx->frame_queue)) {
    platform_sleep_ms(10);
  }
}
static bool client_should_exit(void *user_data) {
  return !server_connection_is_active();
}
int main(void) {
  session_display_ctx_t *display = session_display_create(NULL);
  client_ctx_t client_ctx = {...};
  asciichat_error_t result = session_render_loop(
      NULL, display, client_should_exit,  // NULL capture = event-driven
      client_capture_frame,               // Custom capture
      client_sleep_for_frame,             // Custom sleep
      &client_ctx                         // Context for callbacks
  );
  session_display_destroy(display);
  return result == ASCIICHAT_OK ? 0 : (int)result;
}
Definition at line 55 of file common/session/render.c.
{
  // Validate required parameters
  log_info("[SESSION_RENDER_LOOP] START: capture=%p, display=%p, mode=%s",
           (void *)capture, (void *)display, capture ? "SYNCHRONOUS" : "EVENT-DRIVEN");
  if (!display) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_render_loop: display context is NULL");
    return ERROR_INVALID_PARAM;
  }
  if (!should_exit) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_render_loop: should_exit callback is NULL");
    return ERROR_INVALID_PARAM;
  }
  // Validate mode: either capture context OR custom callbacks, not both
  if (!capture && !capture_cb) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_render_loop: must provide either capture context or capture callback");
    return ERROR_INVALID_PARAM;
  }
  if (capture && capture_cb) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_render_loop: cannot provide both capture context and capture callback");
    return ERROR_INVALID_PARAM;
  }
  // In event-driven mode, both capture_cb and sleep_cb must be provided together
  if (capture_cb && !sleep_cb) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_render_loop: capture_cb requires sleep_cb (must provide both or neither)");
    return ERROR_INVALID_PARAM;
  }
  if (sleep_cb && !capture_cb) {
    SET_ERRNO(ERROR_INVALID_PARAM, "session_render_loop: sleep_cb requires capture_cb (must provide both or neither)");
    return ERROR_INVALID_PARAM;
  }
  // SYNCHRONOUS MODE: Use threaded pipeline for capture + render
  if (capture != NULL) {
    log_info("[SESSION_RENDER_LOOP_SYNCHRONOUS] Creating pipeline... (capture=%p, display=%p)", (void*)capture, (void*)display);
    session_pipeline_t *pipeline = NULL;
    asciichat_error_t pipeline_err = session_pipeline_create(capture, display, &pipeline);
    log_info("[SESSION_RENDER_LOOP_SYNCHRONOUS] pipeline_create returned: %d (pipeline=%p)", pipeline_err, (void*)pipeline);
    if (pipeline_err != ASCIICHAT_OK) {
      log_error("[SESSION_RENDER_LOOP_SYNCHRONOUS] Pipeline creation failed: %d", pipeline_err);
      return pipeline_err;
    }
    log_info("[SESSION_RENDER_LOOP_SYNCHRONOUS] Pipeline created successfully, running main loop...");
    asciichat_error_t run_err = session_pipeline_run_main(pipeline, should_exit, keyboard_handler, user_data);
    // In snapshot mode, pass actual capture-based elapsed time to encoder for correct video duration
    if (GET_OPTION(snapshot_mode) && display && g_snapshot_first_capture_ns > 0) {
      uint64_t now_ns = time_get_ns();
      uint64_t elapsed_ns = now_ns - g_snapshot_first_capture_ns;
      double capture_elapsed_sec = (double)elapsed_ns / (double)NS_PER_SEC_INT;
      log_info("SNAPSHOT: Pipeline finished - passing capture_elapsed=%.3f to encoder", capture_elapsed_sec);
      session_display_set_snapshot_actual_duration(display, capture_elapsed_sec);
    }
    session_pipeline_destroy(pipeline);
    return run_err;
  } else {
    log_warn("[SESSION_RENDER_LOOP] capture is NULL - will not use pipeline (capture_cb=%p)", (void*)capture_cb);
  }
  // Snapshot mode state tracking
  bool snapshot_mode = GET_OPTION(snapshot_mode);
  bool snapshot_done = false;
  uint64_t frames_rendered_since_first = 0; // Track frames rendered after first frame (for snapshot delay)
  // NOTE: g_snapshot_first_frame_rendered is set by display.c when first frame is rendered via platform_write_all()
  // Help screen state tracking for clear-screen transition
  bool help_was_active = false;
  // Terminal resize tracking (for auto_width/auto_height mode)
  unsigned short int last_terminal_width = terminal_get_effective_width();
  unsigned short int last_terminal_height = terminal_get_effective_height();
  log_info("session_render_loop: STARTING - display=%p capture=%p capture_cb=%p snapshot_mode=%s snapshot_delay=%.2f",
           (void *)display, (void *)capture, (void *)capture_cb, snapshot_mode ? "YES" : "NO",
           snapshot_mode ? GET_OPTION(snapshot_delay) : 0.0);
  log_info("session_render_loop: About to enter main loop, should_exit fn check...");
  if (should_exit(user_data)) {
    log_warn("session_render_loop: EXIT signal already set at entry, aborting render loop");
    return ASCIICHAT_OK;
  }
  log_info("session_render_loop: OK to proceed with main loop");
  // Keyboard input initialization (if keyboard handler is provided)
  // Disable keyboard only in snapshot mode
  // Keyboard is pre-initialized from asciichat_shared_init()
  // Allow keyboard input in all other modes if handler provided
  bool keyboard_enabled = keyboard_handler && !snapshot_mode;
  // Pause mode state tracking (for pause/unpause transitions in event-driven mode)
  bool initial_paused_frame_rendered = false;
  bool is_paused = false;
  log_info("render_loop: Keyboard setup - handler=%p snapshot=%s enabled=%s", (void *)keyboard_handler,
           snapshot_mode ? "YES" : "NO", keyboard_enabled ? "YES" : "NO");
  // Log TTY detection status for debugging keyboard issues
  log_info("TTY Status: stdin_tty=%d stdout_tty=%d interactive=%d keyboard_enabled=%d", terminal_is_stdin_tty(),
           terminal_is_stdout_tty(), terminal_is_interactive(), keyboard_enabled);
  // Frame rate timing (event-driven mode only)
  uint64_t frame_count = 0;
  uint64_t frame_start_ns = 0;
  // Event-driven mode: disable console logging during rendering to prevent logs from corrupting frame display
  // This must be done BEFORE the render loop to avoid repeated lock/unlock cycles that could cause deadlocks
  log_info("[EVENT_DRIVEN_MODE] Entering render loop. snapshot_mode=%s", snapshot_mode ? "YES" : "NO");
  log_set_terminal_output(false);
  // Main render loop
  log_debug("session_render_loop: entering main loop");
  int loop_iteration = 0;
  log_info("[RENDER_LOOP_START] snapshot_mode=%s, snapshot_delay=%.2f", snapshot_mode ? "YES" : "NO",
           snapshot_mode ? GET_OPTION(snapshot_delay) : 0.0);
  // Wait for splash animation to complete before rendering first frame
  // This prevents ASCII art from mixing with splash screen output
  static bool splash_wait_done = false;
  if (!splash_wait_done) {
    splash_wait_done = true;
    // Re-enable logging briefly for splash wait, then disable again
    log_set_terminal_output(true);
    splash_wait_for_animation();
    log_set_terminal_output(false);
  }
  // In snapshot mode, we must render at least one frame before checking should_exit
  // to ensure the snapshot delay timer can start
  bool force_first_iteration = snapshot_mode && frame_count == 0;
  while (force_first_iteration || (!should_exit(user_data) && !(snapshot_mode && snapshot_done))) {
    force_first_iteration = false;
    loop_iteration++;
    log_info("[LOOP_ITER] iteration=%d, snapshot_done=%s, frame_count=%lu", loop_iteration, snapshot_done ? "YES" : "NO", frame_count);
    if (loop_iteration % 60 == 0) {
      log_debug("session_render_loop: iteration %d, should_exit check returning false", loop_iteration);
    }
    // Snapshot mode: exit at start of iteration if done
    // This prevents frame 2+ from being captured when snapshot_delay has elapsed
    if (snapshot_mode && snapshot_done && frame_count > 0) {
      log_info("[SNAPSHOT_EXIT] Snapshot mode: exiting at loop iteration start (snapshot_done=true, frames=%lu)", frame_count);
      break;
    }
    log_debug_every(US_PER_SEC_INT, "session_render_loop: frame %lu", frame_count);
    // Frame timing - measure total time to maintain target FPS
    frame_start_ns = time_get_ns();
    // Frame capture and timing - mode-dependent
    image_t *image = NULL;
    uint64_t capture_start_ns = 0;
    uint64_t capture_end_ns = 0;
    uint64_t pre_convert_ns = 0;
    uint64_t post_convert_ns = 0;
    uint64_t conversion_elapsed_ns = 0;
    // EVENT-DRIVEN MODE: Frames come from callbacks
    // Both sleep_cb and capture_cb are guaranteed non-NULL by validation above
    sleep_cb(user_data);
    image = capture_cb(user_data);
    if (!image) {
      // No frame available - this is normal in async modes (network latency, etc.)
      // Just continue to next iteration, don't exit
      continue;
    }
    // Event-driven mode: increment frame count
    frame_count++;
    // Check for terminal resize (if auto_width or auto_height is enabled)
    // This allows the render to adapt immediately when the user resizes the terminal
    bool auto_width = GET_OPTION(auto_width);
    bool auto_height = GET_OPTION(auto_height);
    if (auto_width || auto_height) {
      unsigned short int current_width = 0;
      unsigned short int current_height = 0;
      asciichat_error_t size_err = get_terminal_size(&current_width, &current_height);
      if (size_err == ASCIICHAT_OK) {
        bool width_changed = auto_width && (current_width != last_terminal_width);
        bool height_changed = auto_height && (current_height != last_terminal_height);
        if (width_changed || height_changed) {
          if (width_changed) {
            options_set_int("width", current_width);
            log_info("Terminal width changed: %u → %u", last_terminal_width, current_width);
            last_terminal_width = current_width;
          }
          if (height_changed) {
            options_set_int("height", current_height);
            log_info("Terminal height changed: %u → %u", last_terminal_height, current_height);
            last_terminal_height = current_height;
          }
          // Clear screen when terminal is resized to avoid visual artifacts
          terminal_clear_screen();
        }
      }
    }
    // Convert image to ASCII using display context
    // Handles all palette, terminal caps, width, height, stretch settings
    pre_convert_ns = time_get_ns();
    char *ascii_frame = session_display_convert_to_ascii(display, image);
    post_convert_ns = time_get_ns();
    conversion_elapsed_ns = post_convert_ns - pre_convert_ns;
    // DEBUG: Log frame conversion to file
    FILE *debug_log = fopen("/tmp/render_loop_debug.log", "a");
    if (debug_log) {
      fprintf(debug_log, "[FRAME_CONVERT] frame %lu: image=%p, ascii_frame=%p (len=%zu), conversion_ms=%u\n",
              frame_count, (void *)image, (void *)ascii_frame,
              ascii_frame ? strlen(ascii_frame) : 0,
              (unsigned)(conversion_elapsed_ns / NS_PER_MS_INT));
      fclose(debug_log);
    }
    if (frame_count <= 3) {
      log_info("RENDER_LOOP[%lu]: image=%p, ascii_frame=%p (conversion took %u ms)",
               frame_count, (void *)image, (void *)ascii_frame,
               (unsigned)(conversion_elapsed_ns / NS_PER_MS_INT));
    }
    // Declare variables that need scope beyond the if (ascii_frame) block
    bool is_paused_frame = initial_paused_frame_rendered && is_paused;
    bool output_paused_frame = snapshot_mode && is_paused_frame;
    uint64_t pre_render_ns = 0, post_render_ns = 0;
    if (ascii_frame) {
      log_info_every(1 * NS_PER_SEC_INT, "render_loop: ascii_frame ready (len=%zu)", strlen(ascii_frame));
      // Always attempt to render frames; the display context will handle filtering based on:
      // - TTY mode: render all frames with cursor control (even in snapshot mode, for animation)
      // - Piped mode: render all frames without cursor control (for continuous capture)
      // - Snapshot mode on non-TTY: only the display context renders the final frame
      // BUT: don't render if splash screen is still animating - wait for it to finish
      bool splash_running = splash_is_running();
      bool should_write = !splash_running;
      if (frame_count == 1) {
        log_dev("[RENDER_FRAME] Frame 1: splash_is_running=%s, should_write=%s", splash_running ? "YES" : "NO", should_write ? "YES" : "NO");
      }
      if (should_write) {
        // is_final = true when: snapshot done, or paused frame (for both snapshot and pause modes)
        // Profile: render frame
        pre_render_ns = time_get_ns();
        START_TIMER("render_frame");
        if (frame_count <= 5 || frame_count % 10 == 0) {
          log_info("RENDER_LOOP: Frame %lu - calling session_display_render_frame, display=%p",
                   (unsigned long)frame_count, (void *)display);
        }
        // Check if help screen is active - if so, render help instead of frame
        // Help screen is disabled in snapshot mode and non-interactive terminals (keyboard disabled)
        bool help_is_active = display && keyboard_help_is_active(display);
        // Detect transition from help to ASCII art rendering
        // When help closes, clear the screen before rendering ASCII art
        if (help_was_active && !help_is_active) {
          terminal_clear_screen();
          log_debug_every(1 * NS_PER_SEC_INT, "Cleared screen when transitioning from help to ASCII art");
        }
        if (help_is_active) {
          keyboard_help_render(display);
        } else {
          session_display_render_frame(display, ascii_frame);
        }
        // Snapshot mode: increment frame counter for all displayed frames
        // Counter starts at 1 for the first displayed frame, then 2, 3, 4... for subsequent frames
        // Timer is started by display.c when g_snapshot_first_frame_rendered is set
        if (snapshot_mode && g_snapshot_first_frame_rendered) {
          frames_rendered_since_first++;
          log_info_every(1 * NS_PER_SEC_INT, "[SNAPSHOT] Frame rendered: frames_rendered_since_first=%lu", frames_rendered_since_first);
        }
        // Update help state for next iteration
        help_was_active = help_is_active;
        STOP_TIMER("render_frame");
      }
      // Keyboard input polling (if enabled) - MUST come before snapshot exit check so help screen can be toggled
      // Allow keyboard in snapshot mode too (for help screen toggle debugging)
      // Only enable keyboard if BOTH stdin AND stdout are TTYs to avoid buffering issues
      // when tcsetattr() modifies the tty line discipline
      if (keyboard_enabled && keyboard_handler) {
        START_TIMER("keyboard_read_%lu", (unsigned long)frame_count);
        keyboard_key_t key = keyboard_read_nonblocking();
        double keyboard_elapsed_ns = STOP_TIMER("keyboard_read_%lu", (unsigned long)frame_count);
        if (keyboard_elapsed_ns >= 0.0) {
          char _duration_str[32];
          time_pretty((uint64_t)keyboard_elapsed_ns, -1, _duration_str, sizeof(_duration_str));
          log_dev_every(1 * NS_PER_SEC_INT, "RENDER[%lu] Keyboard read complete (key=%d) in %s",
                        (unsigned long)frame_count, key, _duration_str);
        }
        if (key != KEY_NONE) {
          log_debug("KEYBOARD: Key pressed: code=%d char='%c'", key, (key >= 32 && key < 127) ? key : '?');
          // Check if interactive grep should handle this key
          if (log_search_should_handle(key)) {
            log_debug("KEYBOARD: Grep handler taking key %d", key);
            log_search_handle_key(key);
            continue; // Force immediate re-render
          }
          // Normal keyboard handler
          log_debug("KEYBOARD: Normal handler taking key %d", key);
          keyboard_handler(capture, key, user_data);
        }
      }
      // Free frame before checking exit conditions to avoid double-free
      SAFE_FREE(ascii_frame);
    }
    // Snapshot mode: check if elapsed time has reached snapshot_delay duration (terminal render timing)
    // Separate from capture timing - both should measure their own snapshot_delay
    if (snapshot_mode && !snapshot_done) {
      if (g_snapshot_first_frame_rendered && g_snapshot_first_frame_rendered_ns > 0) {
        double snapshot_delay = GET_OPTION(snapshot_delay);
        uint64_t now_ns = time_get_ns();
        uint64_t elapsed_ns = now_ns - g_snapshot_first_frame_rendered_ns;
        double elapsed_sec = (double)elapsed_ns / (double)NS_PER_SEC_INT;
        if (frames_rendered_since_first == 1 || frames_rendered_since_first % 20 == 0) {
          log_info("SNAPSHOT: RENDER_CHECK iter=%lu elapsed=%.3f target=%.2f (from first_frame_rendered)",
                   frames_rendered_since_first, elapsed_sec, snapshot_delay);
        }
        // snapshot_delay=0 means exit after first frame
        // snapshot_delay>0 means wait that many seconds before exiting
        // Exit is based on elapsed wall-clock time, not frame count
        bool should_exit = (snapshot_delay == 0.0) || (elapsed_sec >= snapshot_delay);
        if (should_exit) {
          log_info("SNAPSHOT: RENDER_DONE at iteration %lu - elapsed=%.3f target=%.2f (setting snapshot_done=true)",
                   frames_rendered_since_first, elapsed_sec, snapshot_delay);
          // We don't end frames with newlines so the next log would print on the same line as the frame's
          // last row without an \n here. We only need this \n in stdout in snapshot mode and when interactive,
          // so piped snapshots don't have a weird newline in stdout that they don't need.
          if (snapshot_mode && terminal_is_interactive()) {
            printf("\n");
          }
          snapshot_done = true;
        }
      } else {
        if (frames_rendered_since_first == 0) {
          log_debug("SNAPSHOT: Waiting for first_frame_rendered (g_snapshot_first_frame_rendered=%d, g_snapshot_first_frame_rendered_ns=%llu)",
                    g_snapshot_first_frame_rendered, (unsigned long long)g_snapshot_first_frame_rendered_ns);
        }
      }
    }
    // Exit conditions: snapshot mode exits after capturing the final frame or initial paused frame
    if (snapshot_mode && (snapshot_done || output_paused_frame)) {
      log_info("SNAPSHOT: EXIT CONDITION MET - snapshot_done=%d, output_paused_frame=%d", snapshot_done, output_paused_frame);
      // Calculate elapsed time from first frame captured (for video file)
      // This is separate from render time - video should span from first capture to last capture
      double capture_elapsed_sec = 0.0;
      if (g_snapshot_first_capture_ns > 0) {
        uint64_t now_ns = time_get_ns();
        uint64_t elapsed_ns = now_ns - g_snapshot_first_capture_ns;
        capture_elapsed_sec = (double)elapsed_ns / (double)NS_PER_SEC_INT;
        log_info("SNAPSHOT: EXIT - Capture elapsed: %.3f seconds, render elapsed: %.3f seconds, g_snapshot_first_capture_ns=%llu",
                 capture_elapsed_sec,
                 (g_snapshot_first_frame_rendered_ns > 0) ? (double)(now_ns - g_snapshot_first_frame_rendered_ns) / NS_PER_SEC_INT : 0.0,
                 (unsigned long long)g_snapshot_first_capture_ns);
      } else {
        log_warn("SNAPSHOT: EXIT condition met but g_snapshot_first_capture_ns is 0!");
      }
      // Pass actual capture elapsed time to encoder for correct video duration
      log_info("SNAPSHOT: About to call session_display_set_snapshot_actual_duration with duration=%.3f, display=%p",
               capture_elapsed_sec, (void *)display);
      if (display) {
        session_display_set_snapshot_actual_duration(display, capture_elapsed_sec);
      } else {
        log_warn("SNAPSHOT: display context is NULL!");
      }
      // Signal application to exit in snapshot mode
      APP_CALLBACK_VOID(signal_exit);
      break;
    }
    // Frame rendering and timing details (moved down since snapshot exit is now above it)
    if (ascii_frame) {
      // Measure frame completion right after rendering, BEFORE keyboard polling
      // This gives us accurate timing for just the core frame operations
      uint64_t frame_end_render_ns = time_get_ns();
      // Calculate each phase duration
      uint64_t prestart_ms =
          (capture_start_ns > frame_start_ns) ? (capture_start_ns - frame_start_ns) / NS_PER_MS_INT : 0;
      uint64_t capture_ms =
          (capture_end_ns > capture_start_ns) ? (capture_end_ns - capture_start_ns) / NS_PER_MS_INT : 0;
      uint64_t convert_ms = conversion_elapsed_ns / NS_PER_MS_INT;
      uint64_t render_ms =
          (post_render_ns > pre_render_ns && post_render_ns > 0) ? (post_render_ns - pre_render_ns) / NS_PER_MS_INT : 0;
      uint64_t total_ms =
          (frame_end_render_ns > frame_start_ns) ? (frame_end_render_ns - frame_start_ns) / NS_PER_MS_INT : 0;
      // Log phase breakdown every 5 frames
      if (frame_count % 5 == 0) {
        log_dev_every(
            2 * NS_PER_SEC_INT,
            "PHASE_BREAKDOWN[%lu]: prestart=%llu ms, capture=%llu ms, convert=%llu ms, render=%llu ms (total=%llu ms)",
            frame_count, prestart_ms, capture_ms, convert_ms, render_ms, total_ms);
      }
    } else {
      // Snapshot mode: even if frame conversion failed, check if we should exit
      // This ensures snapshot_delay is honored even if display context isn't rendering
      if (snapshot_mode && snapshot_done) {
        break;
      }
    }
    // In event-driven mode, frame rate limiting is handled by the sleep_cb callback
    // Synchronous mode (with capture context) uses the pipeline and returns early above
    // Note: Images returned by media sources are cached/reused and should NOT be destroyed
    // The image pointers are managed by the source and will be cleaned up on source shutdown
  } // while (!should_exit(user_data)) {
  // Re-enable console logging after rendering completes
  log_set_terminal_output(true);
  if (!snapshot_mode && terminal_is_interactive()) {
    printf("\n");
  }
  // Keyboard input cleanup (if it was initialized)
  if (keyboard_enabled) {
    keyboard_destroy();
    log_debug_every(2 * NS_PER_SEC_INT, "Keyboard input disabled");
  }
  return ASCIICHAT_OK;
}
References auto_height, auto_width, g_snapshot_first_capture_ns, g_snapshot_first_frame_rendered, g_snapshot_first_frame_rendered_ns, get_terminal_size(), keyboard_help_is_active(), keyboard_help_render(), log_search_handle_key(), log_search_should_handle(), log_set_terminal_output(), options_set_int(), session_display_convert_to_ascii(), session_display_render_frame(), session_display_set_snapshot_actual_duration(), session_pipeline_create(), session_pipeline_destroy(), session_pipeline_run_main(), should_exit(), signal_exit(), splash_is_running(), splash_wait_for_animation(), terminal_get_effective_height(), terminal_get_effective_width(), terminal_is_interactive(), terminal_is_stdin_tty(), terminal_is_stdout_tty(), time_get_ns(), and time_pretty().
session_server_like_run()
asciichat_error_t session_server_like_run (const session_server_like_config_t * config)
#include <src/common/session/server_like.h>
Run a server-like mode with unified initialization and shutdown
This function orchestrates the complete lifecycle of server-like modes by handling common boilerplate (keepawake, signal handlers) while delegating mode-specific logic to callbacks. Status screen threading and keyboard handling are the responsibility of individual modes.
Initialization Sequence
Keepawake Validation & Setup:
Validates mutual exclusivity of –keepawake and –no-keepawake
Enables keepawake if requested (default: off for server modes)
Signal Handler Registration:
Stores mode's interrupt_fn in static scope for signal context
Registers SIGINT and SIGTERM to call server_like_signal_wrapper()
Ignores SIGPIPE (TCP/WebSocket friendly)
interrupt_fn must be async-signal-safe and close listening sockets
Mode-Specific Initialization:
Calls config->init_fn(config->init_user_data)
If init_fn fails, returns error code and proceeds to cleanup
Main Run Loop
Calls config->run_fn(config->run_user_data), which blocks until server shuts down. This is typically an accept loop (tcp_server_run, acds_server_run, etc.).
Cleanup (always runs, even on error)
Disables keepawake if it was enabled during init
Notes
Status screen threading is not managed by this layer. Modes that need status display should implement their own status_fn callback and thread management within run_fn.
The config->status_fn field is available for mode-specific use but is not invoked by server_like itself.
Parameters
config Mode configuration. Must not be NULL. init_fn, run_fn, and interrupt_fn must not be NULL.
Returns
ASCIICHAT_OK on success, or the first error code from initialization or from run_fn. Cleanup always runs regardless of return value.
Definition at line 38 of file server_like.c.
{
  if (!config) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "config is NULL");
  }
  if (!config->init_fn) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "init_fn is NULL");
  }
  if (!config->run_fn) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "run_fn is NULL");
  }
  if (!config->interrupt_fn) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "interrupt_fn is NULL");
  }
  asciichat_error_t result = ASCIICHAT_OK;
  /* === INITIALIZATION === */
  /* 1. Validate keepawake mutual exclusivity */
  bool keepawake_enabled = GET_OPTION(enable_keepawake);
  bool keepawake_disabled = GET_OPTION(disable_keepawake);
  if (keepawake_enabled && keepawake_disabled) {
    return SET_ERRNO(ERROR_INVALID_PARAM,
                     "Cannot specify both --keepawake and --no-keepawake");
  }
  /* 2. Enable keepawake if requested (default is off for servers) */
  if (keepawake_enabled) {
    platform_enable_keepawake();
  }
  /* 3. Store interrupt callback for signal handlers */
  g_server_like_interrupt_fn = config->interrupt_fn;
  /* 4. Register signal handlers - note: signal handlers call interrupt_fn */
  platform_signal(SIGINT, (signal_handler_t)server_like_signal_wrapper);
  platform_signal(SIGTERM, (signal_handler_t)server_like_signal_wrapper);
  platform_signal(SIGPIPE, SIG_IGN);
  /* 5. Call mode-specific initialization */
  result = config->init_fn(config->init_user_data);
  if (result != ASCIICHAT_OK) {
    log_error("Mode initialization failed");
    goto cleanup;
  }
  /* === RUN === */
  /* 6. Call mode-specific blocking run loop */
  result = config->run_fn(config->run_user_data);
cleanup:
  /* === CLEANUP === */
  /* 7. Disable keepawake */
  if (keepawake_enabled) {
    platform_disable_keepawake();
  }
  return result;
}
References session_server_like_config::init_fn, session_server_like_config::init_user_data, session_server_like_config::interrupt_fn, platform_disable_keepawake(), platform_enable_keepawake(), session_server_like_config::run_fn, and session_server_like_config::run_user_data.
session_settings_apply_to_options()
asciichat_error_t session_settings_apply_to_options (const session_settings_t * settings)
#include <src/common/session/settings.h>
Apply settings to global options.
Parameters
settings Settings to apply (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Updates the global options system with values from the settings structure. Only modifies options that are represented in settings.
Definition at line 198 of file settings.c.
{
  if (!settings) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_settings_apply_to_options: NULL settings");
  }
  // Update dimensions if specified
  if (settings->width > 0 && settings->height > 0) {
    asciichat_error_t width_result = options_set_int("width", (int)settings->width);
    asciichat_error_t height_result = options_set_int("height", (int)settings->height);
    if (width_result != ASCIICHAT_OK || height_result != ASCIICHAT_OK) {
      log_warn("Failed to apply dimension settings: width=%d, height=%d", width_result, height_result);
    }
  }
  // Note: Other options would require additional RCU update functions
  // For now, dimensions are the primary use case for runtime updates
  // Color mode, render mode, and palette typically don't change mid-session
  return ASCIICHAT_OK;
}
References session_settings_t::height, options_set_int(), and session_settings_t::width.
session_settings_deserialize()
asciichat_error_t session_settings_deserialize (const uint8_t * buffer, size_t len, session_settings_t * settings)
#include <src/common/session/settings.h>
Deserialize session settings from binary buffer.
Parameters
buffer Input buffer containing serialized settings
len Length of input buffer in bytes
settings Output settings structure (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Deserializes settings from binary format. Validates buffer length and extracts fields in network byte order.
Note
Returns ERROR_INVALID_PARAM if buffer is too small.
Definition at line 101 of file settings.c.
{
  if (!buffer || !settings) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_settings_deserialize: NULL parameter");
  }
  // Check minimum buffer size
  if (len < SESSION_SETTINGS_SERIALIZED_SIZE) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_settings_deserialize: buffer too small (%zu < %d)", len,
                     SESSION_SETTINGS_SERIALIZED_SIZE);
  }
  memset(settings, 0, sizeof(session_settings_t));
  size_t offset = 0;
  // Version (4 bytes, network byte order)
  uint32_t version_net;
  memcpy(&version_net, buffer + offset, sizeof(version_net));
  settings->version = ntohl(version_net);
  offset += sizeof(version_net);
  // Width (2 bytes, network byte order)
  uint16_t width_net;
  memcpy(&width_net, buffer + offset, sizeof(width_net));
  settings->width = (int16_t)ntohs(width_net);
  offset += sizeof(width_net);
  // Height (2 bytes, network byte order)
  uint16_t height_net;
  memcpy(&height_net, buffer + offset, sizeof(height_net));
  settings->height = (int16_t)ntohs(height_net);
  offset += sizeof(height_net);
  // Color mode (1 byte)
  settings->color_mode = buffer[offset++];
  // Render mode (1 byte)
  settings->render_mode = buffer[offset++];
  // Palette type (1 byte)
  settings->palette_type = buffer[offset++];
  // Custom palette (32 bytes)
  memcpy(settings->palette_custom, buffer + offset, 32);
  settings->palette_custom[31] = '\0'; // Ensure null termination
  offset += 32;
  // Audio enabled (1 byte)
  settings->audio_enabled = buffer[offset++];
  // Encryption required (1 byte)
  settings->encryption_required = buffer[offset++];
  // Reserved (16 bytes)
  memcpy(settings->reserved, buffer + offset, 16);
  // offset += 16; // Unused, commented to avoid warning
  return ASCIICHAT_OK;
}
References session_settings_t::audio_enabled, session_settings_t::color_mode, session_settings_t::encryption_required, session_settings_t::height, session_settings_t::palette_custom, session_settings_t::palette_type, session_settings_t::render_mode, session_settings_t::reserved, SESSION_SETTINGS_SERIALIZED_SIZE, session_settings_t::version, and session_settings_t::width.
session_settings_equal()
bool session_settings_equal (const session_settings_t * a, const session_settings_t * b)
#include <src/common/session/settings.h>
Compare two settings structures for equality.
Parameters
a First settings structure (must not be NULL)
b Second settings structure (must not be NULL)
Returns
true if settings are equal (ignoring version), false otherwise
Definition at line 224 of file settings.c.
{
  if (!a || !b) {
    return false;
  }
  // Compare all fields except version
  return a->width == b->width && a->height == b->height && a->color_mode == b->color_mode &&
         a->render_mode == b->render_mode && a->palette_type == b->palette_type &&
         strncmp(a->palette_custom, b->palette_custom, sizeof(a->palette_custom)) == 0 &&
         a->audio_enabled == b->audio_enabled && a->encryption_required == b->encryption_required;
}
References session_settings_t::audio_enabled, session_settings_t::color_mode, session_settings_t::encryption_required, session_settings_t::height, session_settings_t::palette_custom, session_settings_t::palette_type, session_settings_t::render_mode, and session_settings_t::width.
session_settings_from_options()
asciichat_error_t session_settings_from_options (session_settings_t * settings)
#include <src/common/session/settings.h>
Populate settings from current global options.
Parameters
settings Output settings structure (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Reads current values from the global options system and populates the settings structure. Version is set to current timestamp.
Definition at line 160 of file settings.c.
{
  if (!settings) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_settings_from_options: NULL settings");
  }
  // Initialize to defaults
  session_settings_init(settings);
  // Get current options
  const options_t *opts = options_get();
  if (!opts) {
    return SET_ERRNO(ERROR_CONFIG, "Options not initialized");
  }
  // Set version to current time for ordering
  settings->version = (uint32_t)time(NULL);
  // Copy dimension settings
  settings->width = (int16_t)opts->width;
  settings->height = (int16_t)opts->height;
  // Copy display settings
  settings->color_mode = (uint8_t)opts->color_mode;
  settings->render_mode = (uint8_t)opts->render_mode;
  settings->palette_type = (uint8_t)opts->palette_type;
  // Copy custom palette if set
  if (opts->palette_custom_set && opts->palette_custom[0] != '\0') {
    SAFE_STRNCPY(settings->palette_custom, opts->palette_custom, sizeof(settings->palette_custom));
  }
  // Copy audio/encryption settings
  settings->audio_enabled = (uint8_t)opts->audio_enabled;
  settings->encryption_required = opts->no_encrypt ? 0 : 1;
  return ASCIICHAT_OK;
}
References session_settings_t::audio_enabled, session_settings_t::color_mode, session_settings_t::encryption_required, session_settings_t::height, options_get(), session_settings_t::palette_custom, session_settings_t::palette_type, session_settings_t::render_mode, session_settings_init(), session_settings_t::version, and session_settings_t::width.
session_settings_init()
void session_settings_init (session_settings_t * settings)
#include <src/common/session/settings.h>
Initialize session settings to defaults.
Parameters
settings Settings structure to initialize (must not be NULL)
Initializes settings structure with sensible defaults:
Width/height: 0 (auto-detect)
Color mode: TERM_COLOR_AUTO
Render mode: RENDER_MODE_FOREGROUND
Palette: PALETTE_STANDARD
Audio: disabled
Encryption: required
Definition at line 26 of file settings.c.
{
  if (!settings) {
    return;
  }
  memset(settings, 0, sizeof(session_settings_t));
  // Read all defaults from the RCU options system
  settings->version = 0;
  settings->width = (int16_t)terminal_get_effective_width();
  settings->height = (int16_t)terminal_get_effective_height();
  settings->color_mode = (uint8_t)GET_OPTION(color_mode);
  settings->render_mode = (uint8_t)GET_OPTION(render_mode);
  settings->palette_type = (uint8_t)GET_OPTION(palette_type);
  // Custom palette
  const char *palette = GET_OPTION(palette_custom);
  if (palette && palette[0] != '\0') {
    SAFE_STRNCPY(settings->palette_custom, palette, sizeof(settings->palette_custom));
  }
  settings->audio_enabled = (uint8_t)GET_OPTION(audio_enabled);
  settings->encryption_required = GET_OPTION(no_encrypt) ? 0 : 1;
}
References session_settings_t::audio_enabled, session_settings_t::color_mode, session_settings_t::encryption_required, session_settings_t::height, session_settings_t::palette_custom, session_settings_t::palette_type, session_settings_t::render_mode, terminal_get_effective_height(), terminal_get_effective_width(), session_settings_t::version, and session_settings_t::width.
Referenced by session_participant_create(), and session_settings_from_options().
session_settings_needs_update()
bool session_settings_needs_update (uint32_t local_version, uint32_t remote_version)
#include <src/common/session/settings.h>
Check if settings need update based on versions.
Parameters
local_version Current local settings version
remote_version Received remote settings version
Returns
true if local should update to remote, false otherwise
Determines if local settings should be updated based on version comparison. Higher version number wins (newer settings).
Definition at line 219 of file settings.c.
{
  // Higher version wins (newer settings)
  return remote_version > local_version;
}
session_settings_serialize()
asciichat_error_t session_settings_serialize (const session_settings_t * settings, uint8_t * buffer, size_t * len)
#include <src/common/session/settings.h>
Serialize session settings to binary buffer.
Parameters
settings Settings to serialize (must not be NULL)
buffer Output buffer (must be at least SESSION_SETTINGS_SERIALIZED_SIZE bytes)
len Output parameter for actual serialized length (must not be NULL)
Returns
ASCIICHAT_OK on success, error code on failure
Serializes settings to a compact binary format suitable for network transmission. Uses network byte order for multi-byte integers.
Definition at line 51 of file settings.c.
{
  if (!settings || !buffer || !len) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "session_settings_serialize: NULL parameter");
  }
  // Fixed-size serialization format
  size_t offset = 0;
  // Version (4 bytes, network byte order)
  uint32_t version_net = htonl(settings->version);
  memcpy(buffer + offset, &version_net, sizeof(version_net));
  offset += sizeof(version_net);
  // Width (2 bytes, network byte order)
  uint16_t width_net = htons((uint16_t)(settings->width & 0xFFFF));
  memcpy(buffer + offset, &width_net, sizeof(width_net));
  offset += sizeof(width_net);
  // Height (2 bytes, network byte order)
  uint16_t height_net = htons((uint16_t)(settings->height & 0xFFFF));
  memcpy(buffer + offset, &height_net, sizeof(height_net));
  offset += sizeof(height_net);
  // Color mode (1 byte)
  buffer[offset++] = settings->color_mode;
  // Render mode (1 byte)
  buffer[offset++] = settings->render_mode;
  // Palette type (1 byte)
  buffer[offset++] = settings->palette_type;
  // Custom palette (32 bytes, null-padded)
  memcpy(buffer + offset, settings->palette_custom, 32);
  offset += 32;
  // Audio enabled (1 byte)
  buffer[offset++] = settings->audio_enabled;
  // Encryption required (1 byte)
  buffer[offset++] = settings->encryption_required;
  // Reserved (16 bytes)
  memcpy(buffer + offset, settings->reserved, 16);
  offset += 16;
  *len = offset;
  return ASCIICHAT_OK;
}
References session_settings_t::audio_enabled, session_settings_t::color_mode, session_settings_t::encryption_required, session_settings_t::height, session_settings_t::palette_custom, session_settings_t::palette_type, session_settings_t::render_mode, session_settings_t::reserved, session_settings_t::version, and session_settings_t::width.