ascii-chat: keepalive.h File Reference
keepalive.h File Reference
ascii-chat Client Connection Keepalive Management Interface
Functions
int keepalive_start_thread ()
Start keepalive/ping thread.
void keepalive_stop_thread ()
Stop keepalive/ping thread.
bool keepalive_thread_exited ()
Check if keepalive thread has exited.
Detailed Description
ascii-chat Client Connection Keepalive Management Interface
Defines the interface for connection keepalive thread management and ping/pong coordination in the ascii-chat client.
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
2025
Definition in file keepalive.h.
Function Documentation
keepalive_start_thread()
int keepalive_start_thread ()
Start keepalive/ping thread.
Returns
0 on success, negative on error
Start keepalive/ping thread
Creates and starts the ping thread for connection keepalive. Must be called after successful server connection establishment.
Returns
0 on success, negative on error
Definition at line 234 of file keepalive.c.
{
  if (g_ping_thread_created) {
    log_warn("Ping thread already created");
    return 0;
  }
  // Register keepalive atomics with named debug registry
  static bool keepalive_atomics_registered = false;
  if (!keepalive_atomics_registered) {
    NAMED_REGISTER_ATOMIC(&g_ping_thread_exited, "keepalive_ping_thread_exit_confirmation", NULL);
    keepalive_atomics_registered = true;
  }
  // Start ping thread for keepalive
  atomic_store_bool(&g_ping_thread_exited, false);
  if (thread_pool_spawn(g_client_worker_pool, ping_thread_func, NULL, 3, "keepalive_ping") != ASCIICHAT_OK) {
    log_error("Failed to spawn ping thread in worker pool");
    LOG_ERRNO_IF_SET("Ping thread creation failed");
    return -1;
  }
  g_ping_thread_created = true;
  return 0;
}
References atomic_store_bool(), g_client_worker_pool, and thread_pool_spawn().
Referenced by protocol_start_connection().
keepalive_stop_thread()
void keepalive_stop_thread ()
Stop keepalive/ping thread.
Stop keepalive/ping thread
Gracefully stops the ping thread and cleans up resources. Safe to call multiple times.
Definition at line 267 of file keepalive.c.
{
  if (!g_ping_thread_created) {
    return;
  }
  // Don't call signal_exit() here - that's for global shutdown only!
  // The ping thread monitors connection state and will exit when connection is lost
  // Wait for thread to exit gracefully
  int wait_count = 0;
  while (wait_count < 20 && !atomic_load_bool(&g_ping_thread_exited)) {
    platform_sleep_ns(100 * NS_PER_MS_INT); // 100ms
    wait_count++;
  }
  if (!atomic_load_bool(&g_ping_thread_exited)) {
    log_warn("Ping thread not responding - will be joined by thread pool");
  }
  // Thread will be joined by thread_pool_stop_all() in protocol_stop_connection()
  g_ping_thread_created = false;
  log_debug("Ping thread stopped and joined");
}
References atomic_load_bool().
Referenced by protocol_stop_connection().
keepalive_thread_exited()
bool keepalive_thread_exited ()
Check if keepalive thread has exited.
Returns
true if thread exited, false otherwise
Check if keepalive thread has exited
Returns
true if thread has exited, false otherwise
Definition at line 299 of file keepalive.c.
{
  return atomic_load_bool(&g_ping_thread_exited);
}
References atomic_load_bool().