ascii-chat: keepalive.c File Reference
keepalive.c File Reference
💓 Client keepalive: periodic ping/pong exchange for reliable connection failure detection
Macros
#define PING_INTERVAL_NS (1LL * NS_PER_SEC_INT)
#define PING_SLEEP_INTERVAL_NS (1LL * NS_PER_SEC_INT)
Functions
int keepalive_start_thread ()
Start keepalive/ping thread.
void keepalive_stop_thread ()
Stop keepalive/ping thread.
bool keepalive_thread_exited ()
Check if keepalive thread has exited.
Detailed Description
💓 Client keepalive: periodic ping/pong exchange for reliable connection failure detection
The keepalive system uses a dedicated ping thread:
Ping Thread: Sends periodic ping packets to server
Response Monitoring: Server responds with pong packets
Timeout Detection: Connection loss detected via failed pings
Coordinated Shutdown: Thread integrates with global shutdown logic
Timing Strategy
Keepalive timing optimized for connection reliability:
Ping Interval: 1 second between ping packets
Server Timeout: Server times out clients after 5 seconds of silence
Safety Margin: 4-second buffer prevents false disconnections
Network Tolerance: Accounts for network jitter and processing delays
Thread Management
Ping thread follows robust lifecycle management:
Creation: Thread started after successful connection
Monitoring: Continuous health checks and connection validation
Coordination: Respects global shutdown flags and connection state
Termination: Graceful shutdown with resource cleanup
Recovery: Thread recreated for each new connection
Connection Health Monitoring
Multiple layers of connection health detection:
Socket Validity: Check socket file descriptor before sending
Connection Flags: Monitor atomic connection state variables
Send Failures: Detect network errors during ping transmission
Global Shutdown: Respect application-wide shutdown requests
Integration Points
main.c: Keepalive thread lifecycle management
server.c: Ping packet transmission and connection monitoring
protocol.c: Pong packet reception and response handling
network.c: Low-level ping/pong packet formatting
Error Handling
Keepalive errors handled with appropriate escalation:
Ping Send Failures: Signal connection loss for reconnection
Socket Errors: Clean thread exit and connection cleanup
Network Timeouts: Graceful handling without false alarms
Thread Failures: Log errors and continue with degraded monitoring
Resource Management
Minimal resource usage for efficient keepalive:
Thread Resources: Single lightweight thread with minimal stack
Network Overhead: Small ping/pong packets with minimal bandwidth
Timing Precision: Efficient sleep implementation with early wake
Memory Usage: No dynamic allocations in steady-state operation
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
2025
Definition in file keepalive.c.
Macro Definition Documentation
PING_INTERVAL_NS
#define PING_INTERVAL_NS (1LL * NS_PER_SEC_INT)
Ping interval in nanoseconds (must be less than server timeout)
Definition at line 108 of file keepalive.c.
PING_SLEEP_INTERVAL_NS
#define PING_SLEEP_INTERVAL_NS (1LL * NS_PER_SEC_INT)
Sleep interval for ping timing loop (1 second in nanoseconds)
Definition at line 111 of file keepalive.c.
Function Documentation
keepalive_start_thread()
int keepalive_start_thread ()
Start keepalive/ping thread.
Start keepalive/ping thread
Creates and starts the ping thread for connection keepalive. Must be called after successful server connection establishment.
Returns
0 on success, negative on error
Definition at line 234 of file keepalive.c.
{
  if (g_ping_thread_created) {
    log_warn("Ping thread already created");
    return 0;
  }
  // Register keepalive atomics with named debug registry
  static bool keepalive_atomics_registered = false;
  if (!keepalive_atomics_registered) {
    NAMED_REGISTER_ATOMIC(&g_ping_thread_exited, "keepalive_ping_thread_exit_confirmation", NULL);
    keepalive_atomics_registered = true;
  }
  // Start ping thread for keepalive
  atomic_store_bool(&g_ping_thread_exited, false);
  if (thread_pool_spawn(g_client_worker_pool, ping_thread_func, NULL, 3, "keepalive_ping") != ASCIICHAT_OK) {
    log_error("Failed to spawn ping thread in worker pool");
    LOG_ERRNO_IF_SET("Ping thread creation failed");
    return -1;
  }
  g_ping_thread_created = true;
  return 0;
}
References atomic_store_bool(), g_client_worker_pool, and thread_pool_spawn().
Referenced by protocol_start_connection().
keepalive_stop_thread()
void keepalive_stop_thread ()
Stop keepalive/ping thread.
Stop keepalive/ping thread
Gracefully stops the ping thread and cleans up resources. Safe to call multiple times.
Definition at line 267 of file keepalive.c.
{
  if (!g_ping_thread_created) {
    return;
  }
  // Don't call signal_exit() here - that's for global shutdown only!
  // The ping thread monitors connection state and will exit when connection is lost
  // Wait for thread to exit gracefully
  int wait_count = 0;
  while (wait_count < 20 && !atomic_load_bool(&g_ping_thread_exited)) {
    platform_sleep_ns(100 * NS_PER_MS_INT); // 100ms
    wait_count++;
  }
  if (!atomic_load_bool(&g_ping_thread_exited)) {
    log_warn("Ping thread not responding - will be joined by thread pool");
  }
  // Thread will be joined by thread_pool_stop_all() in protocol_stop_connection()
  g_ping_thread_created = false;
  log_debug("Ping thread stopped and joined");
}
References atomic_load_bool().
Referenced by protocol_stop_connection().
keepalive_thread_exited()
bool keepalive_thread_exited ()
Check if keepalive thread has exited.
Check if keepalive thread has exited
Returns
true if thread has exited, false otherwise
Definition at line 299 of file keepalive.c.
{
  return atomic_load_bool(&g_ping_thread_exited);
}
References atomic_load_bool().