ascii-chat: keyboard_help.c File Reference
keyboard_help.c File Reference
Session
Keyboard help overlay TUI rendering implementation.
Macros
#define ENABLED_COLOR LOG_COLOR_INFO /* Green */
#define DISABLED_COLOR LOG_COLOR_ERROR /* Red */
#define APPEND(fmt, ...)
Functions
void keyboard_help_render (session_display_ctx_t *ctx)
Render keyboard help centered on terminal.
Detailed Description
Keyboard help overlay TUI rendering implementation.
Definition in file keyboard_help.c.
Macro Definition Documentation
APPEND
#define APPEND (fmt, ...)
Value:
do {                                                                                                                 \
  int written = snprintf(buffer + buf_pos, BUFFER_SIZE - buf_pos, fmt, ##__VA_ARGS__);                               \
  if (written > 0) {                                                                                                 \
    buf_pos += written;                                                                                              \
  }                                                                                                                  \
} while (0)
Referenced by keyboard_help_render().
DISABLED_COLOR
#define DISABLED_COLOR LOG_COLOR_ERROR /* Red */
Definition at line 23 of file keyboard_help.c.
ENABLED_COLOR
#define ENABLED_COLOR LOG_COLOR_INFO /* Green */
Definition at line 22 of file keyboard_help.c.
Function Documentation
keyboard_help_render()
void keyboard_help_render (session_display_ctx_t * ctx)
Render keyboard help centered on terminal.
Definition at line 318 of file keyboard_help.c.
{
  if (!ctx) {
    log_error("keyboard_help_render: ctx is NULL!");
    return;
  }
  log_info("keyboard_help_render: STARTING");
  // Get terminal dimensions
  int term_width = (int)terminal_get_effective_width();
  int term_height = (int)terminal_get_effective_height();
  log_info("keyboard_help_render: term_width=%d, term_height=%d", term_width, term_height);
  // Use available terminal width, capped at preferred width
  int box_width = term_width;
  if (box_width > 48)
    box_width = 48; // Cap at preferred width
  if (box_width < 30)
    box_width = 30; // Absolute minimum for readability
  // Calculate centering position (true mathematical centering)
  // Horizontal centering
  int start_col = (term_width - box_width) / 2;
  if (start_col < 0) {
    start_col = 0;
  }
  // Calculate box height dynamically based on content
  // With animations separator line added, the standard help screen is 25 rows
  int box_height = 25;
  // Vertical centering with dynamic box height
  int start_row = (term_height - box_height) / 2 - 3; // -3 offset for proper vertical centering
  if (start_row < 0) {
    start_row = 0;
  }
  // Build help screen content
  const size_t BUFFER_SIZE = 8192; // Increased from 4096 to ensure all content fits
  char *buffer = SAFE_MALLOC(BUFFER_SIZE, char *);
  size_t buf_pos = 0;
#define APPEND(fmt, ...)                                                                                               \
  do {                                                                                                                 \
    int written = snprintf(buffer + buf_pos, BUFFER_SIZE - buf_pos, fmt, ##__VA_ARGS__);                               \
    if (written > 0) {                                                                                                 \
      buf_pos += written;                                                                                              \
    }                                                                                                                  \
  } while (0)
  // Clear screen and position cursor
  APPEND("\033[2J"); // Clear screen
  APPEND("\033[H");  // Cursor to home
  // Build help screen with proper spacing using UTF-8 width-aware padding
  char line_buf[256];
  char border_buf[256];
  // Generate top border
  APPEND("\033[%d;%dH", start_row + 1, start_col + 1);
  border_buf[0] = '\0';
  strcat(border_buf, "╔");
  for (int i = 1; i < box_width - 1; i++)
    strcat(border_buf, "═");
  strcat(border_buf, "╗");
  APPEND("%s", border_buf);
  // Title
  APPEND("\033[%d;%dH", start_row + 2, start_col + 1);
  build_help_line(line_buf, sizeof(line_buf), "ascii-chat Keyboard Shortcuts", box_width);
  APPEND("%s", line_buf);
  // Generate separator border
  APPEND("\033[%d;%dH", start_row + 3, start_col + 1);
  border_buf[0] = '\0';
  strcat(border_buf, "╠");
  for (int i = 1; i < box_width - 1; i++)
    strcat(border_buf, "═");
  strcat(border_buf, "╣");
  APPEND("%s", border_buf);
  // Navigation section
  int current_row = 4;
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "Navigation & Control:");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "─────────────────────");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "?       Toggle this help screen");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "Esc     Close help / Quit app");
  // Check if media is provided (only show Space/Seek keys if media is loaded)
  const char *media_url = GET_OPTION(media_url);
  const char *media_file = GET_OPTION(media_file);
  bool has_media = (media_url && strlen(media_url) > 0) || (media_file && strlen(media_file) > 0);
  if (has_media) {
    append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                     "Space   Play/Pause (files only)");
    append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                     "← / →   Seek backward/forward 30s");
  }
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "m / M   Mute/Unmute audio");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "↑ / ↓   Volume up/down (10%)");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "c / C   Cycle color mode");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "f / F   Cycle color filter");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "x / X   Flip webcam horizontally");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "y / Y   Flip webcam vertically");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "r / R   Cycle render mode");
#ifndef NDEBUG
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "`       Print current sync primitive state");
#endif
  // Blank line before settings section
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "");
  // Current settings section
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Current Settings:");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "───────────────");
  // Get current option values
  double current_volume = GET_OPTION(speakers_volume);
  int current_color_mode = (int)GET_OPTION(color_mode);
  int current_render_mode = (int)GET_OPTION(render_mode);
  color_filter_t current_color_filter = GET_OPTION(color_filter);
  bool flip_x = (bool)GET_OPTION(flip_x);
  bool flip_y = (bool)GET_OPTION(flip_y);
  bool current_audio = (bool)GET_OPTION(audio_enabled);
  // Format volume bar as "[========  ] 80%"
  char volume_bar[32];
  format_volume_bar(current_volume, volume_bar, sizeof(volume_bar));
  // Get string values
  const char *color_str = color_mode_to_string(current_color_mode);
  const char *filter_str = color_filter_to_string(current_color_filter);
  const char *render_str = render_mode_to_string(current_render_mode);
  // Create status indicators for flip, audio, and matrix rain
  // Format flip status as "rows=X/O cols=X/O" (rows=flip_y, cols=flip_x)
  char flip_status[64];
  snprintf(flip_status, sizeof(flip_status), "rows=%s cols=%s", status_indicator(flip_y), status_indicator(flip_x));
  const char *audio_text = status_indicator(current_audio);
  bool matrix_rain_enabled = GET_OPTION(matrix_rain);
  const char *matrix_text = status_indicator(matrix_rain_enabled);
  // Build settings lines with UTF-8 width-aware padding (ordered to match keybinds: m, ↑/↓, c, f, x/y, r)
  append_settings_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Audio",
                       audio_text, 6);
  append_settings_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Volume",
                       volume_bar, 6);
  append_settings_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Color", color_str,
                       6);
  append_settings_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Filter",
                       filter_str, 6);
  append_settings_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Render",
                       render_str, 6);
  append_settings_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Flip",
                       flip_status, 6);
  // Blank line before animations section
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "");
  // Animations section
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "Animations (number key toggle):");
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width,
                   "───────────────────────────────");
  // Format: "(0) Matrix \"Digital Rain\" : X/O"
  char animation_line[256];
  snprintf(animation_line, sizeof(animation_line), "(0) Matrix \"Digital Rain\" : %s", matrix_text);
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, animation_line);
  // FPS Counter toggle
  char fps_line[256];
  snprintf(fps_line, sizeof(fps_line), "(-) FPS Counter : %s", status_indicator(GET_OPTION(fps_counter)));
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, fps_line);
  // Blank line before footer
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "");
  // Footer
  append_help_line(buffer, &buf_pos, BUFFER_SIZE, start_row, &current_row, start_col, box_width, "Press ? to close");
  // Bottom border
  int remaining_buf = BUFFER_SIZE - buf_pos;
  int written = snprintf(buffer + buf_pos, remaining_buf, "\033[%d;%dH", start_row + current_row, start_col + 1);
  if (written > 0) {
    buf_pos += written;
  }
  border_buf[0] = '\0';
  strcat(border_buf, "╚");
  for (int i = 1; i < box_width - 1; i++)
    strcat(border_buf, "═");
  strcat(border_buf, "╝");
  written = snprintf(buffer + buf_pos, BUFFER_SIZE - buf_pos, "%s", border_buf);
  if (written > 0) {
    buf_pos += written;
  }
#undef APPEND
  log_info("keyboard_help_render: buffer prepared, buf_pos=%zu", buf_pos);
  // Write buffer to terminal
  session_display_write_raw(ctx, buffer, buf_pos);
  log_info("keyboard_help_render: buffer written to terminal");
  // Flush output
  if (ctx && session_display_has_tty(ctx)) {
    int tty_fd = session_display_get_tty_fd(ctx);
    log_info("keyboard_help_render: tty_fd=%d", tty_fd);
    if (tty_fd >= 0) {
      (void)terminal_flush(tty_fd);
      log_info("keyboard_help_render: terminal flushed");
    }
  }
  SAFE_FREE(buffer);
  log_info("keyboard_help_render: COMPLETE");
}
References APPEND, bool, color_mode_to_string(), render_mode_to_string(), session_display_get_tty_fd(), session_display_has_tty(), session_display_write_raw(), terminal_flush(), terminal_get_effective_height(), and terminal_get_effective_width().
Referenced by display_render_frame(), session_handle_keyboard_input(), and session_render_loop().