ascii-chat: session.c File Reference
session.c File Reference
Functions
void session_entry_destroy (session_entry_t *entry)
Free a session entry and all its resources.
Function Documentation
session_entry_destroy()
void session_entry_destroy (session_entry_t * entry)
Free a session entry and all its resources.
Parameters
entry Session entry to free
Definition at line 15 of file lib/discovery/session.c.
{
  if (!entry) {
    return;
  }
  // Free all participants
  for (size_t i = 0; i < MAX_PARTICIPANTS; i++) {
    if (entry->participants[i]) {
      SAFE_FREE(entry->participants[i]);
    }
  }
  // Free the entry itself
  SAFE_FREE(entry);
}
References MAX_PARTICIPANTS.
Referenced by database_session_join(), signaling_broadcast(), signaling_relay_ice(), and signaling_relay_sdp().