ascii-chat: server.c File Reference
server.c File Reference
WebSocket server implementation.
Data Structures
struct websocket_connection_data_t
Per-connection user data.
Functions
asciichat_error_t websocket_server_init (websocket_server_t *server, const websocket_server_config_t *config)
asciichat_error_t websocket_server_run (websocket_server_t *server)
void websocket_server_cancel_service (websocket_server_t *server)
void websocket_server_destroy (websocket_server_t *server)
Detailed Description
WebSocket server implementation.
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
February 2026
Definition in file lib/network/websocket/server.c.
Function Documentation
websocket_server_cancel_service()
void websocket_server_cancel_service (websocket_server_t * server)
Definition at line 808 of file lib/network/websocket/server.c.
{
  if (server && server->context) {
    lws_cancel_service(server->context);
  }
}
Referenced by server_main().
websocket_server_destroy()
void websocket_server_destroy (websocket_server_t * server)
Definition at line 814 of file lib/network/websocket/server.c.
{
  if (!server) {
    return;
  }
  atomic_store_bool(&server->running, false);
  // Cancel any pending libwebsockets service calls to interrupt blocking lws_service()
  // This prevents the event loop from getting stuck in lws_service()
  if (server->context) {
    log_debug("[WEBSOCKET_SERVER_DESTROY] Cancelling libwebsockets service");
    lws_cancel_service(server->context);
  }
  // Unregister atomic fields
  NAMED_UNREGISTER(&server->running);
  // Destroy handler thread pool (waits for pending work to complete)
  if (server->handler_pool) {
    thread_pool_destroy(server->handler_pool);
    server->handler_pool = NULL;
  }
  // Context is normally destroyed by websocket_server_run (from the event loop
  // thread) for fast shutdown. This handles the case where run() wasn't called
  // or didn't complete normally.
  if (server->context) {
    NAMED_UNREGISTER(server->context);
    log_debug("WebSocket context still alive in destroy, cleaning up");
    lws_context_destroy(server->context);
    server->context = NULL;
  }
  log_debug("WebSocket server destroyed");
}
References atomic_store_bool(), and thread_pool_destroy().
Referenced by acds_main(), and server_main().
websocket_server_init()
asciichat_error_t websocket_server_init (websocket_server_t * server, const websocket_server_config_t * config)
Definition at line 680 of file lib/network/websocket/server.c.
{
  if (!server || !config || !config->client_handler) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
  }
  memset(server, 0, sizeof(*server));
  server->handler = config->client_handler;
  server->user_data = config->user_data;
  server->port = config->port;
  atomic_store_bool(&server->running, true);
  // Store server pointer in protocol user data so callbacks can access it
  // Both the HTTP and ACIP protocols need access to the server
  websocket_protocols[0].user = server; // http protocol
  websocket_protocols[1].user = server; // acip protocol
  // Enable libwebsockets logging through centralized logging system
  lws_log_init_server();
  // Configure libwebsockets context
  struct lws_context_creation_info info = {0};
  info.port = config->port;
  info.protocols = websocket_protocols;
  info.gid = (gid_t)-1;                                // Cast to avoid undefined behavior with unsigned type
  info.uid = (uid_t)-1;                                // Cast to avoid undefined behavior with unsigned type
  info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT; // Initialize SSL/TLS support (required for server binding)
  info.extensions = NULL;                              // Disable permessage-deflate - causing connection issues
  info.retry_and_idle_policy = &keep_alive_policy; // Configure keep-alive to prevent idle disconnects during handshake
  // Configure TLS/WSS support if certificates are provided (check for non-empty strings)
  if (config->tls_cert_path && config->tls_cert_path[0] != '\0' && config->tls_key_path &&
      config->tls_key_path[0] != '\0') {
#ifdef LWS_WITH_TLS
    info.ssl_cert_filepath = config->tls_cert_path;
    info.ssl_private_key_filepath = config->tls_key_path;
    log_info("WebSocket server configured for WSS (TLS): cert=%s, key=%s", config->tls_cert_path, config->tls_key_path);
#else
    log_warn("WebSocket server: TLS support not compiled in libwebsockets; WSS unavailable");
#endif
  } else if ((config->tls_cert_path && config->tls_cert_path[0] != '\0') ||
             (config->tls_key_path && config->tls_key_path[0] != '\0')) {
    log_warn("WebSocket server: Both TLS certificate and key must be provided for WSS; using plain WS");
  }
  // Increase per-thread service buffer to prevent fragmentation of large messages
  // Default is 4KB, causing large frames to fragment into many chunks
  // Video frames are 921KB, so increase to 2MB to handle them without fragmentation
  info.pt_serv_buf_size = 2 * 1024 * 1024; // 2MB per-thread service buffer
  // Disable ALL default timeouts and keep-alive mechanisms
  // Use only the explicit retry_and_idle_policy we set above (30/35 seconds)
  info.ka_time = 0;           // Disable TCP keep-alive probes (use WebSocket pings instead)
  info.ka_probes = 0;         // Disable TCP probes
  info.ka_interval = 0;       // Disable TCP probe intervals
  info.keepalive_timeout = 0; // Disable HTTP keep-alive timeout entirely
  // Explicitly set a very large idle timeout to prevent early disconnection
  // Without this, libwebsockets defaults to 5 seconds for HTTP connections
  // Set to effectively infinite (100 hours) since we use retry_and_idle_policy instead
  info.timeout_secs = 360000; // 100 hours - effectively disabled
  // Create libwebsockets context
  server->context = lws_create_context(&info);
  if (!server->context) {
    return SET_ERRNO(ERROR_NETWORK_BIND, "Failed to create libwebsockets context");
  }
  // Create thread pool for handling client connections
  // Use 4 worker threads to handle concurrent client handlers without blocking LWS event loop
  server->handler_pool = thread_pool_create_with_workers("websocket_handlers", 4);
  if (!server->handler_pool) {
    lws_context_destroy(server->context);
    server->context = NULL;
    return SET_ERRNO(ERROR_THREAD, "Failed to create WebSocket handler thread pool");
  }
  /* Register WebSocket server with named registry */
  char ws_port_name[32];
  snprintf(ws_port_name, sizeof(ws_port_name), "ws:%d", server->port);
  NAMED_REGISTER(server, ws_port_name, "websocket_server", "0x%tx", NULL);
  /* Register server's sync primitives with hierarchical naming */
  NAMED_REGISTER_ATOMIC(&server->running, "is_running", (uintptr_t)(const void *)(server));
  /* Register WebSocket context as child of server */
  NAMED_REGISTER_WEBSOCKET(server->context, "context", (uintptr_t)(const void *)(server));
  log_info("WebSocket server initialized on port %d with static file serving", config->port);
  return ASCIICHAT_OK;
}
References atomic_store_bool(), lws_log_init_server(), and thread_pool_create_with_workers().
Referenced by acds_main(), and server_main().
websocket_server_run()
asciichat_error_t websocket_server_run (websocket_server_t * server)
Definition at line 771 of file lib/network/websocket/server.c.
{
  if (!server || !server->context) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid server");
  }
  log_info("WebSocket server starting event loop on port %d", server->port);
  // Run libwebsockets event loop
  uint64_t last_service_ns = 0;
  int service_call_count = 0;
  while (atomic_load_bool(&server->running)) {
    // Service libwebsockets with 16ms timeout to match 60 FPS frame rate.
    // This provides frequent event processing (~60 callback invocations per second) so that
    // WebSocket frames queued by the render loop are sent promptly, matching TCP performance.
    // All client connections share this single server context, so a single lws_service() call
    // services fragments and events for all clients simultaneously.
    uint64_t service_start_ns = time_get_ns();
    if (last_service_ns && service_start_ns - last_service_ns > 30 * US_PER_MS_INT) {
      // > 30ms gap between service calls
      double gap_ms = (double)(service_start_ns - last_service_ns) / 1e6;
      log_info_every(1 * US_PER_MS_INT, "[LWS_SERVICE_GAP] %.1fms gap between lws_service calls", gap_ms);
    }
    service_call_count++;
    log_debug_every(500 * US_PER_MS_INT, "[LWS_SERVICE] Call #%d, context=%s", service_call_count,
                    NAMED_DESCRIBE(server->context, "websocket_server"));
    int result = lws_service(server->context, 1);
    if (result < 0) {
      log_error("libwebsockets service error: %d", result);
      break;
    }
  }
  log_info(
      "WebSocket server event loop exited (context will be destroyed by main thread after handler threads complete)");
  return ASCIICHAT_OK;
}
References atomic_load_bool(), and time_get_ns().