ascii-chat: init.c File Reference
init.c File Reference
Platform initialization for WASM/Emscripten.
Functions
asciichat_error_t platform_init (void)
void platform_destroy (void)
Detailed Description
Platform initialization for WASM/Emscripten.
Definition in file lib/platform/wasm/init.c.
Function Documentation
platform_destroy()
void platform_destroy (void)
Definition at line 15 of file lib/platform/wasm/init.c.
{
  // No cleanup needed for WASM
}
Referenced by asciichat_shared_destroy(), client_cleanup(), and mirror_cleanup().
platform_init()
asciichat_error_t platform_init (void)
Definition at line 10 of file lib/platform/wasm/init.c.
{
  // No special initialization needed for WASM
  return ASCIICHAT_OK;
}
Referenced by asciichat_shared_init(), client_init_with_args(), and mirror_init_with_args().