ascii-chat: lifecycle.c File Reference
lifecycle.c File Reference
Functions
bool lifecycle_init (lifecycle_t *lc, const char *name)
bool lifecycle_init_once (lifecycle_t *lc)
void lifecycle_init_commit (lifecycle_t *lc)
void lifecycle_init_abort (lifecycle_t *lc)
bool lifecycle_shutdown (lifecycle_t *lc)
bool lifecycle_shutdown_forever (lifecycle_t *lc)
bool lifecycle_is_initialized (const lifecycle_t *lc)
bool lifecycle_is_dead (const lifecycle_t *lc)
bool lifecycle_reset (lifecycle_t *lc)
bool lifecycle_destroy_once (lifecycle_t *lc)
void lifecycle_destroy_commit (lifecycle_t *lc)
Function Documentation
lifecycle_destroy_commit()
void lifecycle_destroy_commit (lifecycle_t * lc)
Definition at line 215 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] destroy_commit: NULL lifecycle pointer");
    return;
  }
  log_dev("[lifecycle] destroy_commit: transitioning DESTROYING → UNINITIALIZED");
  atomic_store_u64(&lc->state, LIFECYCLE_UNINITIALIZED);
}
References atomic_store_u64().
Referenced by audio_stop_thread().
lifecycle_destroy_once()
bool lifecycle_destroy_once (lifecycle_t * lc)
Definition at line 172 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] destroy_once: NULL lifecycle pointer");
    return false;
  }
  uint64_t expected = LIFECYCLE_INITIALIZED;
  if (!atomic_cas_u64(&lc->state, &expected, LIFECYCLE_DESTROYING)) {
    // If not initialized, nothing to destroy
    if (expected == LIFECYCLE_UNINITIALIZED) {
      log_dev("[lifecycle] destroy_once: already uninitialized, nothing to destroy");
      return false;
    }
    // If dead, never allow destruction (already permanently shut down)
    if (expected == LIFECYCLE_DEAD) {
      log_dev("[lifecycle] destroy_once: module is dead, no destruction allowed");
      return false;
    }
    // If already destroying, don't duplicate work (return false, let first destroyer finish)
    if (expected == LIFECYCLE_DESTROYING) {
      log_dev("[lifecycle] destroy_once: already destroying, skipping (first destroyer has priority)");
      return false;
    }
    // If initializing, skip destruction (init may still be in progress)
    if (expected == LIFECYCLE_INITIALIZING) {
      log_dev("[lifecycle] destroy_once: still initializing, skipping destruction");
      return false;
    }
    // Unexpected state
    log_dev("[lifecycle] destroy_once: unexpected state: %d", expected);
    return false;
  }
  // Winner: state is now LIFECYCLE_DESTROYING
  // Caller must call lifecycle_destroy_commit()
  log_dev("[lifecycle] destroy_once: won CAS, transitioned to DESTROYING");
  return true;
}
References atomic_cas_u64().
Referenced by audio_stop_thread().
lifecycle_init()
bool lifecycle_init (lifecycle_t * lc, const char * name)
Definition at line 6 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] init: NULL lifecycle pointer");
    return false;
  }
  uint64_t expected = LIFECYCLE_UNINITIALIZED;
  if (!atomic_cas_u64(&lc->state, &expected, LIFECYCLE_INITIALIZED)) {
    log_dev("[lifecycle] init: %s already initialized (current state: %llu)", name ? name : "<unnamed>", expected);
    return false; // Already initialized or in INITIALIZING/DEAD state
  }
  /* Winner: initialize sync primitive if configured */
  if (lc->sync_type == LIFECYCLE_SYNC_MUTEX && lc->sync.mutex != NULL) {
    log_dev("[lifecycle] init: %s initializing mutex", name ? name : "<unnamed>");
    mutex_init(lc->sync.mutex, name);
  } else if (lc->sync_type == LIFECYCLE_SYNC_RWLOCK && lc->sync.rwlock != NULL) {
    log_dev("[lifecycle] init: %s initializing rwlock", name ? name : "<unnamed>");
    rwlock_init(lc->sync.rwlock, name);
  } else {
    log_dev("[lifecycle] init: %s initialized (no sync primitive)", name ? name : "<unnamed>");
  }
  return true;
}
References atomic_cas_u64(), mutex_init(), and rwlock_init().
Referenced by ansi_fast_init_16color(), ansi_fast_init_256color(), asciichat_error_stats_get(), asciichat_error_stats_init(), asciichat_error_stats_record(), asciichat_pcre2_singleton_compile(), asciichat_pcre2_singleton_get_code(), audio_sender_init(), audio_stop_thread(), buffer_pool_init_global(), client_crypto_init(), colorscheme_init(), init_default_luminance_palette(), log_init(), log_search_init(), named_init(), options_state_init(), server_main(), stats_init(), symbol_cache_init(), and timer_system_init().
lifecycle_init_abort()
void lifecycle_init_abort (lifecycle_t * lc)
Definition at line 78 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] init_abort: NULL lifecycle pointer");
    return;
  }
  log_dev("[lifecycle] init_abort: transitioning INITIALIZING → UNINITIALIZED (retry allowed)");
  atomic_store_u64(&lc->state, LIFECYCLE_UNINITIALIZED);
}
References atomic_store_u64().
Referenced by audio_client_init(), and symbol_cache_init().
lifecycle_init_commit()
void lifecycle_init_commit (lifecycle_t * lc)
Definition at line 69 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] init_commit: NULL lifecycle pointer");
    return;
  }
  log_dev("[lifecycle] init_commit: transitioning INITIALIZING → INITIALIZED");
  atomic_store_u64(&lc->state, LIFECYCLE_INITIALIZED);
}
References atomic_store_u64().
Referenced by asciichat_instr_coverage_enabled(), asciichat_instr_runtime_get(), asciichat_pcre2_singleton_get_code(), audio_client_init(), log_search_init(), named_init(), and splash_set_update_notification().
lifecycle_init_once()
bool lifecycle_init_once (lifecycle_t * lc)
Definition at line 31 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] init_once: NULL lifecycle pointer");
    return false;
  }
  uint64_t expected = LIFECYCLE_UNINITIALIZED;
  if (!atomic_cas_u64(&lc->state, &expected, LIFECYCLE_INITIALIZING)) {
    // If already initialized, just return false (no work needed)
    if (expected == LIFECYCLE_INITIALIZED) {
      log_dev("[lifecycle] init_once: already initialized");
      return false;
    }
    // If dead, never allow re-init
    if (expected == LIFECYCLE_DEAD) {
      log_dev("[lifecycle] init_once: module is dead, no re-init allowed");
      return false;
    }
    // If initializing, don't spin (caller may be retrying or it may complete asynchronously)
    // Just return false to indicate this thread doesn't need to do init work
    if (expected == LIFECYCLE_INITIALIZING) {
      log_dev("[lifecycle] init_once: already initializing, skipping (will resolve asynchronously)");
      return false;
    }
    // Unexpected state
    log_dev("[lifecycle] init_once: unexpected state: %d", expected);
    return false;
  }
  // Winner: state is now LIFECYCLE_INITIALIZING
  // Caller must call lifecycle_init_commit() or lifecycle_init_abort()
  log_dev("[lifecycle] init_once: won CAS, transitioned to INITIALIZING");
  return true;
}
References atomic_cas_u64().
Referenced by asciichat_instr_coverage_enabled(), asciichat_instr_runtime_get(), audio_client_init(), log_search_init(), and splash_set_update_notification().
lifecycle_is_dead()
bool lifecycle_is_dead (const lifecycle_t * lc)
Definition at line 140 of file lifecycle.c.
{
  if (lc == NULL)
    return false;
  return atomic_load_u64(&lc->state) == LIFECYCLE_DEAD;
}
References atomic_load_u64().
lifecycle_is_initialized()
bool lifecycle_is_initialized (const lifecycle_t * lc)
Definition at line 134 of file lifecycle.c.
{
  if (lc == NULL)
    return false;
  return atomic_load_u64(&lc->state) == LIFECYCLE_INITIALIZED;
}
References atomic_load_u64().
Referenced by asciichat_error_stats_get(), asciichat_error_stats_print(), asciichat_error_stats_record(), asciichat_error_stats_reset(), asciichat_instr_coverage_enabled(), asciichat_instr_runtime_get(), asciichat_pcre2_singleton_get_code(), audio_client_init(), audio_sender_cleanup(), audio_stop_thread(), client_crypto_handshake(), colorscheme_destroy(), colorscheme_get_active_scheme(), colorscheme_init(), colorscheme_set_active_scheme(), crypto_client_initiate_rekey(), crypto_client_is_ready(), crypto_client_process_rekey_request(), crypto_client_process_rekey_response(), crypto_client_send_rekey_complete(), crypto_client_send_rekey_response(), crypto_client_should_rekey(), log_file_msg(), log_init(), log_init_colors(), log_msg(), log_plain_msg(), log_plain_stderr_msg(), log_plain_stderr_nonewline_msg(), log_server_stats(), log_terminal_msg(), named_describe(), named_get(), named_get_fd(), named_get_fd_format_spec(), named_get_format_spec(), named_get_packet_type(), named_get_packet_type_format_spec(), named_get_type(), named_init(), named_register(), named_register_fd(), named_register_fmt(), named_register_packet_type(), named_registry_for_each(), named_unregister(), options_state_destroy(), options_state_init(), options_state_set(), platform_is_binary_in_path(), simd_caches_destroy_all(), symbol_cache_insert(), symbol_cache_lookup(), symbol_cache_resolve_batch(), timer_is_initialized(), timer_start(), timer_stop(), timer_system_destroy(), timer_system_init(), and webrtc_create_peer_connection().
lifecycle_reset()
bool lifecycle_reset (lifecycle_t * lc)
Definition at line 146 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] reset: NULL lifecycle pointer");
    return false;
  }
  uint64_t expected = LIFECYCLE_INITIALIZED;
  if (!atomic_cas_u64(&lc->state, &expected, LIFECYCLE_UNINITIALIZED)) {
    log_dev("[lifecycle] reset: not in INITIALIZED state (current: %d)", expected);
    return false; // Not in INITIALIZED state
  }
  /* Winner: destroy sync primitive if configured (reset keeps same primitive) */
  if (lc->sync_type == LIFECYCLE_SYNC_MUTEX && lc->sync.mutex != NULL) {
    log_dev("[lifecycle] reset: destroying and resetting mutex");
    mutex_destroy(lc->sync.mutex);
  } else if (lc->sync_type == LIFECYCLE_SYNC_RWLOCK && lc->sync.rwlock != NULL) {
    log_dev("[lifecycle] reset: destroying and resetting rwlock");
    rwlock_destroy(lc->sync.rwlock);
  } else {
    log_dev("[lifecycle] reset: completed (no sync primitive, allows reinit)");
  }
  return true;
}
References atomic_cas_u64(), and mutex_destroy().
Referenced by client_crypto_init().
lifecycle_shutdown()
bool lifecycle_shutdown (lifecycle_t * lc)
Definition at line 87 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] shutdown: NULL lifecycle pointer");
    return false;
  }
  uint64_t expected = LIFECYCLE_INITIALIZED;
  if (!atomic_cas_u64(&lc->state, &expected, LIFECYCLE_UNINITIALIZED)) {
    log_dev("[lifecycle] shutdown: not in INITIALIZED state (current: %d)", expected);
    return false; // Not initialized or in unexpected state
  }
  /* Winner: destroy sync primitive if configured */
  if (lc->sync_type == LIFECYCLE_SYNC_MUTEX && lc->sync.mutex != NULL) {
    log_dev("[lifecycle] shutdown: destroying mutex");
    mutex_destroy(lc->sync.mutex);
  } else if (lc->sync_type == LIFECYCLE_SYNC_RWLOCK && lc->sync.rwlock != NULL) {
    log_dev("[lifecycle] shutdown: destroying rwlock");
    rwlock_destroy(lc->sync.rwlock);
  } else {
    log_dev("[lifecycle] shutdown: completed (no sync primitive)");
  }
  return true;
}
References atomic_cas_u64(), and mutex_destroy().
Referenced by acds_strings_destroy(), asciichat_instr_runtime_global_destroy(), asciichat_pcre2_cleanup_all(), audio_sender_cleanup(), audio_terminate_portaudio_final(), buffer_pool_cleanup_global(), colorscheme_destroy(), crypto_client_cleanup(), log_destroy(), log_search_destroy(), named_destroy(), named_init(), options_state_destroy(), options_state_init(), platform_cleanup_binary_path_cache(), simd_caches_destroy_all(), stats_cleanup(), symbol_cache_destroy(), and timer_system_destroy().
lifecycle_shutdown_forever()
bool lifecycle_shutdown_forever (lifecycle_t * lc)
Definition at line 112 of file lifecycle.c.
{
  if (lc == NULL) {
    log_dev("[lifecycle] shutdown_forever: NULL lifecycle pointer");
    return false;
  }
  uint64_t current;
  do {
    current = atomic_load_u64(&lc->state);
    if (current == LIFECYCLE_DEAD) {
      log_dev("[lifecycle] shutdown_forever: already DEAD");
      return false;
    }
    if (current == LIFECYCLE_INITIALIZING) {
      log_dev("[lifecycle] shutdown_forever: spinning on INITIALIZING");
    }
  } while (current == LIFECYCLE_INITIALIZING || !atomic_cas_u64(&lc->state, &current, LIFECYCLE_DEAD));
  log_dev("[lifecycle] shutdown_forever: transitioned to DEAD (was in state: %d)", current);
  return current == LIFECYCLE_INITIALIZED;
}
References atomic_cas_u64(), and atomic_load_u64().