ascii-chat: keepawake.c File Reference
keepawake.c File Reference
Linux system sleep prevention using systemd-inhibit.
Functions
asciichat_error_t platform_enable_keepawake (void)
void platform_disable_keepawake (void)
Detailed Description
Linux system sleep prevention using systemd-inhibit.
Definition in file linux/keepawake.c.
Function Documentation
platform_disable_keepawake()
void platform_disable_keepawake (void)
Definition at line 91 of file linux/keepawake.c.
{
#ifdef HAVE_LIBSYSTEMD
  if (g_inhibit_fd >= 0) {
    close(g_inhibit_fd);
    log_debug("Keepawake disabled (closed inhibit fd: %d)", g_inhibit_fd);
    // Unregister from named registry after logging
    NAMED_UNREGISTER_FD(g_inhibit_fd);
    g_inhibit_fd = -1;
  }
#endif
}
Referenced by acds_main(), server_main(), session_client_like_run(), and session_server_like_run().
platform_enable_keepawake()
asciichat_error_t platform_enable_keepawake (void)
Definition at line 21 of file linux/keepawake.c.
{
#ifdef HAVE_LIBSYSTEMD
  // Linux: Use systemd-inhibit if available
  if (g_inhibit_fd >= 0) {
    log_debug("Keepawake already enabled");
    return ASCIICHAT_OK;
  }
  // Check if systemd is available at runtime (weak symbol)
  if (sd_bus_default_system == NULL) {
    log_dev("systemd not available, keepawake not supported");
    return ASCIICHAT_OK; // Not an error, just unsupported
  }
  sd_bus *bus = NULL;
  sd_bus_message *reply = NULL;
  sd_bus_error error = SD_BUS_ERROR_NULL;
  if (sd_bus_default_system(&bus) < 0) {
    return SET_ERRNO(ERROR_PLATFORM_INIT, "Failed to connect to system bus");
  }
  if (!bus) {
    return SET_ERRNO(ERROR_PLATFORM_INIT, "System bus is NULL");
  }
  int r = sd_bus_call_method(bus, "org.freedesktop.login1", "/org/freedesktop/login1", "org.freedesktop.login1.Manager",
                             "Inhibit", &error, &reply, "ssss",
                             "sleep:idle",            // What to inhibit
                             "ascii-chat",            // Who
                             "Video/audio streaming", // Why
                             "block"                  // Mode
  );
  if (r < 0) {
    sd_bus_error_free(&error);
    sd_bus_unref(bus);
    return SET_ERRNO(ERROR_PLATFORM_INIT, "Failed to inhibit sleep via systemd");
  }
  if (!reply) {
    sd_bus_error_free(&error);
    sd_bus_unref(bus);
    return SET_ERRNO(ERROR_PLATFORM_INIT, "systemd inhibit reply is NULL");
  }
  if (sd_bus_message_read(reply, "h", &g_inhibit_fd) < 0) {
    sd_bus_message_unref(reply);
    sd_bus_error_free(&error);
    sd_bus_unref(bus);
    return SET_ERRNO(ERROR_PLATFORM_INIT, "Failed to read inhibit fd from systemd reply");
  }
  sd_bus_message_unref(reply);
  sd_bus_error_free(&error);
  sd_bus_unref(bus);
  // Register the inhibit fd with the named registry for debug logging
  NAMED_REGISTER_FD(g_inhibit_fd, "inhibit");
  log_debug("Keepawake enabled via systemd-inhibit (fd: %d)", g_inhibit_fd);
  return ASCIICHAT_OK;
#else
  // Other POSIX systems: not implemented
  log_debug("Keepawake not implemented on this platform");
  return ASCIICHAT_OK;
#endif
}
Referenced by acds_main(), server_main(), session_client_like_run(), and session_server_like_run().