ascii-chat: named.c File Reference
named.c File Reference
Format named objects in log messages (replaces hex addresses with type/name descriptions).
Data Structures
struct type_check_context
Check if a type string is actually registered in the named registry.
Macros
#define NAMED_FORMAT_BUFFER_SIZE (4096)
#define COLORIZE_BUFFERS 4
#define COLORIZE_BUFFER_SIZE 512
Functions
int log_named_format_message (const char *message, char *output, size_t output_size)
const char * log_named_format_or_original (const char *message)
Format named objects in a message (thread-local buffer).
const char * colorize_named_string (const char *name_str)
Colorize a "type/name (0xaddress)" string for display in memory reports.
Detailed Description
Format named objects in log messages (replaces hex addresses with type/name descriptions).
This module scans log message text for hex addresses (0x[0-9a-fA-F]+) and replaces them with friendly descriptions from the named object registry when available. For example, 0x7f1234567890 might become "mutex/recv_mutex.2 (0x7f1234567890)"
Output is colorized for better readability:
Type name: yellow (LOG_COLOR_WARN)
Name: orange (LOG_COLOR_DEV)
ID value: grey (LOG_COLOR_GREY)
Definition in file log/named.c.
Macro Definition Documentation
COLORIZE_BUFFER_SIZE
#define COLORIZE_BUFFER_SIZE 512
Referenced by colorize_named_string().
COLORIZE_BUFFERS
#define COLORIZE_BUFFERS 4
Referenced by colorize_named_string().
NAMED_FORMAT_BUFFER_SIZE
#define NAMED_FORMAT_BUFFER_SIZE (4096)
Definition at line 25 of file log/named.c.
Referenced by log_named_format_or_original().
Function Documentation
colorize_named_string()
const char * colorize_named_string (const char * name_str)
Colorize a "type/name (0xaddress)" string for display in memory reports.
Parameters
name_str String in "type/name (0xaddress)" format (e.g., "thread/splash_anim.0 (0x7f123456)")
Returns
Colorized string with ANSI codes: type(yellow)/name(blue) (id(grey))
Used by memory report to colorize named object display. Returns a pointer to a static rotating buffer (4 buffers, valid until next call).
Example: "thread/splash_anim.0 (0x7f123456)" displays with:
"thread" in yellow
"splash_anim.0" in blue
"0x7f123456" in grey
Definition at line 796 of file log/named.c.
{
#define COLORIZE_BUFFERS 4
#define COLORIZE_BUFFER_SIZE 512
  static char buffers[COLORIZE_BUFFERS][COLORIZE_BUFFER_SIZE];
  static int buffer_idx = 0;
  if (!name_str || name_str[0] == '\0') {
    return name_str;
  }
  char *current_buf = buffers[buffer_idx];
  buffer_idx = (buffer_idx + 1) % COLORIZE_BUFFERS;
  /* Find the slash separator (type/name) */
  const char *slash = strchr(name_str, '/');
  if (!slash) {
    /* No slash found - just return the string as-is */
    return name_str;
  }
  /* Find opening paren for address */
  const char *paren = strchr(name_str, '(');
  /* Extract type (before slash) */
  size_t type_len = slash - name_str;
  char type_buf[256];
  strncpy(type_buf, name_str, type_len < sizeof(type_buf) - 1 ? type_len : sizeof(type_buf) - 1);
  type_buf[type_len] = '\0';
  /* Extract name (between slash and paren, or end of string) */
  const char *name_start = slash + 1;
  size_t name_len;
  if (paren && paren > slash) {
    /* Skip spaces before paren */
    const char *name_end = paren - 1;
    while (name_end > name_start && *name_end == ' ') {
      name_end--;
    }
    name_len = name_end - name_start + 1;
  } else {
    name_len = strlen(name_start);
  }
  char name_buf[256];
  strncpy(name_buf, name_start, name_len < sizeof(name_buf) - 1 ? name_len : sizeof(name_buf) - 1);
  name_buf[name_len] = '\0';
  /* Apply colors */
  const char *type_colored = colored_string(LOG_COLOR_WARN, type_buf);
  const char *name_colored = colored_string(LOG_COLOR_DEV, name_buf);
  /* Format: type(yellow)/name(blue) and add address part if present */
  if (paren) {
    /* Extract address (0x...) from parentheses */
    const char *addr_start = paren + 1;
    const char *addr_end = strchr(addr_start, ')');
    if (addr_end) {
      size_t addr_len = addr_end - addr_start;
      char addr_buf[128];
      strncpy(addr_buf, addr_start, addr_len < sizeof(addr_buf) - 1 ? addr_len : sizeof(addr_buf) - 1);
      addr_buf[addr_len] = '\0';
      const char *addr_colored = colored_string(LOG_COLOR_GREY, addr_buf);
      safe_snprintf(current_buf, COLORIZE_BUFFER_SIZE, "%s/%s (%s)", type_colored, name_colored, addr_colored);
    } else {
      safe_snprintf(current_buf, COLORIZE_BUFFER_SIZE, "%s/%s %s", type_colored, name_colored, paren);
    }
  } else {
    safe_snprintf(current_buf, COLORIZE_BUFFER_SIZE, "%s/%s", type_colored, name_colored);
  }
  return current_buf;
#undef COLORIZE_BUFFERS
#undef COLORIZE_BUFFER_SIZE
}
References colored_string(), COLORIZE_BUFFER_SIZE, COLORIZE_BUFFERS, and safe_snprintf().
log_named_format_message()
int log_named_format_message (const char * message, char * output, size_t output_size)
Definition at line 467 of file log/named.c.
{
  if (!message || !output || output_size == 0) {
    return -1;
  }
  size_t out_pos = 0;
  const char *p = message;
  bool any_transformed = false;
  while (*p && out_pos < output_size - 1) {
    /* Look for "0x" prefix indicating a hex address */
    if (*p == '0' && *(p + 1) == 'x' && isxdigit(*(p + 2))) {
      const char *hex_start = p;
      if (try_format_hex_address(message, hex_start, output, output_size, &out_pos, &p)) {
        any_transformed = true;
        continue;
      }
      /* Not registered or formatting failed - copy original hex address */
      const char *hex_end = hex_start + 2; /* Start after "0x" */
      while (*hex_end && isxdigit(*hex_end)) {
        hex_end++;
      }
      size_t hex_len = hex_end - hex_start;
      if (hex_len < output_size - out_pos) {
        memcpy(output + out_pos, hex_start, hex_len);
        out_pos += hex_len;
        p = hex_end;
      } else {
        /* Buffer overflow - truncate and stop */
        break;
      }
    } else if (isdigit(*p)) {
      /* Look for decimal integers that might be FDs or packet types */
      const char *int_start = p;
      int fd_value = 0;
      int digit_count = 0;
      /* Parse decimal digits */
      while (*p && isdigit(*p) && digit_count < 6) { /* FDs rarely exceed 999999 */
        fd_value = fd_value * 10 + (*p - '0');
        p++;
        digit_count++;
      }
      /* Skip if this integer is part of already-formatted output like "(fd=20)" or "(type/name (...))" */
      bool is_already_formatted = false;
      if (int_start - message >= 5) {
        /* Check for "(fd=", "(pkt_type=", "(socket=", "(sockfd=", or "(type/" patterns to prevent re-formatting.
         * Named objects are formatted as: type/name (0xaddress) or type/name (key=value)
         * We need to detect if we're already inside a formatted output.
         */
        const char *check = int_start - 1;
        while (check > message && isspace(*check))
          check--;
        // Only access *check if pointer is within bounds
        if (check >= message && *check == '=') {
          /* Found "=", now check what prefix it has for patterns like "(fd=20)" or "(socket=20)" or "(pkt_type=123)" */
          const char *eq_pos = check;
          check--;
          while (check > message && (isalnum(*check) || *check == '_')) {
            check--;
          }
          check++;
          size_t prefix_len = eq_pos - check;
          if ((prefix_len == 2 && strncmp(check, "fd", 2) == 0) ||
              (prefix_len == 6 && strncmp(check, "socket", 6) == 0) ||
              (prefix_len == 6 && strncmp(check, "sockfd", 6) == 0) ||
              (prefix_len == 8 && strncmp(check, "pkt_type", 8) == 0)) {
            is_already_formatted = true;
          }
        } else if (check >= message && *check == '/') {
          /* Found "/", now check if this is a type/name pattern.
           * Format is "(type/name (...)" where type is word characters (thread, mutex, socket, etc.)
           * Must verify "/" is preceded by word characters AND "(" to ensure it's a formatted type.
           */
          const char *slash_pos = check;
          check--;
          while (check > message && (isalnum(*check) || *check == '_')) {
            check--;
          }
          check++;
          /* Check that the "/" was preceded by word characters (indicating a type name) */
          size_t type_len = slash_pos - check;
          if (type_len > 0 && (isalpha(*check) || *check == '_')) {
            /* Verify this is a registered type/name pattern by checking for "(" before the type
             * AND checking if the type actually exists in the registry */
            const char *type_start = check;
            const char *before_type = type_start - 1;
            while (before_type > message && isspace(*before_type)) {
              before_type--;
            }
            /* Only mark as formatted if:
             * 1. Preceded by "(" - ensures pattern looks like "(type/name ...)"
             * 2. Type exists in registry - prevents false positives on random text */
            if (before_type >= message && *before_type == '(' && is_type_in_registry(type_start, type_len)) {
              is_already_formatted = true;
            }
          }
        }
      }
      /* Check if this is a registered packet type */
      if (!is_already_formatted && digit_count > 0 && has_packet_type_prefix(message, int_start)) {
        const char *name = named_get_packet_type(fd_value);
        if (name) {
          const char *prefix_start = find_packet_type_prefix_start(message, int_start);
          size_t prefix_len = int_start - prefix_start;
          size_t saved_pos = out_pos;
          if (out_pos >= prefix_len) {
            out_pos -= prefix_len;
          }
          if (write_formatted_packet_type(fd_value, name, output, output_size, &out_pos)) {
            any_transformed = true;
            continue;
          }
          out_pos = saved_pos; /* Restore on failure */
        }
      }
      /* Check if this is a registered file descriptor */
      if (!is_already_formatted && digit_count > 0 && has_fd_prefix(message, int_start)) {
        const char *name = named_get_fd(fd_value);
        if (name) {
          const char *prefix_start = find_fd_prefix_start(message, int_start);
          size_t prefix_len = int_start - prefix_start;
          size_t saved_pos = out_pos;
          if (out_pos >= prefix_len) {
            out_pos -= prefix_len;
          }
          if (write_formatted_fd(fd_value, name, output, output_size, &out_pos)) {
            any_transformed = true;
            continue;
          }
          out_pos = saved_pos; /* Restore on failure */
        }
      }
      /* Check if this integer has a generic type prefix (socket, client, connection, etc.)
       * DISABLED: This feature has a backtracking bug that corrupts output when applied after
       * other formatting operations. Re-enable only after fixing the backtracking logic to
       * properly track correspondence between input and output positions.
       * See commit b86fed2a8 which introduced the bug.
       */
      if (false && !is_already_formatted && digit_count > 0) {
        const char *type_name = NULL;
        size_t type_len = 0;
        const char *prefix_start = find_generic_type_prefix(message, int_start, &type_name, &type_len);
        if (type_name && prefix_start != int_start) {
          /* Skip if already formatted with a name (e.g., "socket/listener.0" already has a /) */
          bool skip_format = false;
          /* Check if this looks like it's already been formatted by looking for / in the pattern */
          const char *check_ptr = prefix_start;
          while (check_ptr < int_start && *check_ptr && *check_ptr != '/') {
            check_ptr++;
          }
          if (check_ptr < int_start && *check_ptr == '/') {
            /* Already formatted (contains /), skip */
            skip_format = true;
          }
          if (!skip_format) {
            /* We found a type prefix like "socket", "client", etc.
             * Try to look up a registered name for this type+id */
            /* Normalize type name aliases: "sockfd" → "socket", "descriptor" → "fd" */
            const char *lookup_type = type_name;
            size_t lookup_len = type_len;
            if (type_len == 6 && strncmp(type_name, "sockfd", 6) == 0) {
              lookup_type = "socket";
              lookup_len = 6;
            } else if (type_len == 10 && strncmp(type_name, "descriptor", 10) == 0) {
              lookup_type = "fd";
              lookup_len = 2;
            }
            const char *name = named_get_by_type_and_id(lookup_type, lookup_len, fd_value);
            char temp_output[512];
            char type_str[32];
            char id_buffer[64];
            /* Safely copy type name */
            if (type_len < sizeof(type_str)) {
              memcpy(type_str, type_name, type_len);
              type_str[type_len] = '\0';
              int id_written = snprintf(id_buffer, sizeof(id_buffer), "%d", fd_value);
              if (id_written > 0 && id_written < (int)sizeof(id_buffer)) {
                int temp_written = 0;
                if (name) {
                  /* Format with name: type/name (type=value) */
                  temp_written =
                      snprintf(temp_output, sizeof(temp_output), "%s/%s (%s=%s)", type_str, name, type_str, id_buffer);
                  if (temp_written > 0 && (size_t)temp_written < sizeof(temp_output)) {
                    /* Backtrack to remove the prefix we already copied */
                    size_t prefix_len = int_start - prefix_start;
                    if (out_pos >= prefix_len) {
                      out_pos -= prefix_len;
                    }
                    int copy_len = temp_written;
                    if (out_pos + copy_len < output_size - 1) {
                      memcpy(output + out_pos, temp_output, copy_len);
                      out_pos += copy_len;
                      any_transformed = true;
                      continue;
                    }
                  }
                }
              }
            }
          }
        }
      }
      /* Not a registered FD or formatting failed - copy original number */
      if (!copy_unformatted_decimal(int_start, p, output, output_size, &out_pos)) {
        break;
      }
    } else {
      /* Check if this is the start of "type=DIGIT" pattern */
      if (*p == 't' && p + 4 < message + strlen(message) && is_type_equals_pattern(p)) {
        if (!type_equals_inside_parens(p, message)) {
          const char *digit_end = p + 5;
          int pkt_value = parse_decimal_digits(digit_end, &digit_end);
          if (pkt_value > 0) {
            const char *name = named_get_packet_type(pkt_value);
            if (name && write_formatted_type_equals(pkt_value, name, output, output_size, &out_pos)) {
              p = digit_end;
              any_transformed = true;
              continue;
            }
          }
        }
      }
      /* Regular character - copy it */
      copy_char_to_output(output, &out_pos, *p++);
    }
  }
  /* Null terminate */
  if (out_pos < output_size) {
    output[out_pos] = '\0';
  } else {
    output[output_size - 1] = '\0';
  }
  return any_transformed ? (int)out_pos : -1;
}
References named_get_fd(), and named_get_packet_type().
Referenced by log_named_format_or_original().
log_named_format_or_original()
const char * log_named_format_or_original (const char * message)
Format named objects in a message (thread-local buffer).
Parameters
message Input message
Returns
Formatted message string (thread-local buffer, valid only until next call)
Convenience wrapper that uses a thread-local buffer internally. Applies formatting iteratively until the message stops changing (fixpoint). Returns the original message if no formatting was applied.
Definition at line 742 of file log/named.c.
{
  if (!message) {
    return message;
  }
  static _Thread_local char format_buffer[NAMED_FORMAT_BUFFER_SIZE];
  static _Thread_local char work_buffer[NAMED_FORMAT_BUFFER_SIZE];
  /* Apply formatting iteratively until the message stabilizes (no more changes) */
  const char *current = message;
  size_t max_iterations = 3; /* Reduce iterations to prevent recursion (prevent transforming already-transformed output) */
  for (size_t iter = 0; iter < max_iterations; iter++) {
    int result = log_named_format_message(current, format_buffer, sizeof(format_buffer));
    if (result <= 0) {
      /* No transformation was made, we've reached a fixpoint */
      return current == message ? message : format_buffer;
    }
    /* Check if the message changed */
    if (strcmp(current, format_buffer) == 0) {
      /* No actual change, return the current version */
      return format_buffer;
    }
    /* Message changed, prepare for next iteration */
    if (current == message) {
      /* First iteration, use format_buffer as input for next iteration */
      current = format_buffer;
    } else {
      /* Subsequent iterations, swap buffers */
      strcpy(work_buffer, format_buffer);
      current = work_buffer;
    }
  }
  /* Max iterations reached, return last formatted version */
  return format_buffer;
}
References log_named_format_message(), and NAMED_FORMAT_BUFFER_SIZE.
Referenced by log_template_apply().