ascii-chat: merger.c File Reference
merger.c File Reference
Man page content merging and orchestration.
Functions
char * manpage_merger_merge_options (const options_config_t *config, const parsed_section_t *existing_section)
char * manpage_merger_merge_environment (const options_config_t *config, const parsed_section_t *existing_section)
char * manpage_merger_merge_positional (const options_config_t *config, const parsed_section_t *existing_section)
asciichat_error_t manpage_merger_generate_usage (const options_config_t *config, char **out_content, size_t *out_len)
asciichat_error_t manpage_merger_generate_synopsis (const char *mode_name, char **out_content, size_t *out_len)
void manpage_merger_free_content (char *content)
Detailed Description
Man page content merging and orchestration.
Orchestrates the man page generation pipeline and handles intelligent merging of auto-generated content with manual sections.
Definition in file merger.c.
Function Documentation
manpage_merger_free_content()
void manpage_merger_free_content (char * content)
Definition at line 179 of file merger.c.
{
  if (content) {
    SAFE_FREE(content);
  }
}
Referenced by options_config_generate_manpage_merged(), and options_config_generate_manpage_template().
manpage_merger_generate_synopsis()
asciichat_error_t manpage_merger_generate_synopsis (const char * mode_name, char ** out_content, size_t * out_len)
Definition at line 137 of file merger.c.
{
  if (!out_content || !out_len) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid output parameters for manpage_merger_generate_synopsis");
  }
  // Allocate buffer for synopsis
  size_t buffer_size = 512;
  char *buffer = SAFE_MALLOC(buffer_size, char *);
  size_t offset = 0;
  // Note: Section header is already in template, don't duplicate it
  if (mode_name) {
    // Mode-specific synopsis
    offset += safe_snprintf(buffer + offset, buffer_size - offset,
                            ".B ascii-chat\n"
                            ".I %s\n"
                            "[\\fIoptions\\fR]\n",
                            mode_name);
  } else {
    // Binary-level synopsis - show main modes
    offset += safe_snprintf(buffer + offset, buffer_size - offset,
                            ".B ascii-chat\n"
                            "[\\fIoptions\\fR]\n"
                            "\n"
                            ".B ascii-chat\n"
                            "[\\fIoptions\\fR] \\fI<session-string>\\fR\n"
                            "\n"
                            ".B ascii-chat\n"
                            "[\\fIoptions\\fR] [\\fBserver\\fR | \\fBclient\\fR | \\fBmirror\\fR | "
                            "\\fBdiscovery-service\\fR] [\\fImode-options\\fR]\n");
  }
  offset += safe_snprintf(buffer + offset, buffer_size - offset, "\n");
  *out_content = buffer;
  *out_len = offset;
  log_debug("Generated synopsis section (%zu bytes)", *out_len);
  return ASCIICHAT_OK;
}
References buffer_size, and safe_snprintf().
Referenced by options_config_generate_manpage_merged(), and options_config_generate_manpage_template().
manpage_merger_generate_usage()
asciichat_error_t manpage_merger_generate_usage (const options_config_t * config, char ** out_content, size_t * out_len)
Definition at line 79 of file merger.c.
{
  if (!out_content || !out_len) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid output parameters for manpage_merger_generate_usage");
  }
  if (!config || config->num_usage_lines == 0) {
    *out_content = SAFE_MALLOC(1, char *);
    (*out_content)[0] = '\0';
    *out_len = 0;
    return ASCIICHAT_OK;
  }
  // Allocate growing buffer for usage section
  size_t buffer_capacity = 4096;
  char *buffer = SAFE_MALLOC(buffer_capacity, char *);
  size_t offset = 0;
  for (size_t i = 0; i < config->num_usage_lines; i++) {
    const usage_descriptor_t *usage = &config->usage_lines[i];
    // Ensure buffer is large enough
    if (offset + 512 >= buffer_capacity) {
      buffer_capacity *= 2;
      buffer = SAFE_REALLOC(buffer, buffer_capacity, char *);
    }
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".TP\n");
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".B ascii-chat");
    if (usage->mode) {
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, " %s", usage->mode);
    }
    if (usage->positional) {
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, " %s", usage->positional);
    }
    if (usage->show_options) {
      // Use mode-specific options suffix for mode commands, regular options for binary-level
      if (usage->mode && strcmp(usage->mode, "<mode>") != 0) {
        offset += safe_snprintf(buffer + offset, buffer_capacity - offset, " [mode-options...]");
      } else {
        offset += safe_snprintf(buffer + offset, buffer_capacity - offset, " [options...]");
      }
    }
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, "\n");
    if (usage->description) {
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, "%s\n", usage->description);
    }
  }
  offset += safe_snprintf(buffer + offset, buffer_capacity - offset, "\n");
  *out_content = buffer;
  *out_len = offset;
  log_debug("Generated usage section (%zu bytes)", offset);
  return ASCIICHAT_OK;
}
References safe_snprintf(), and usage().
Referenced by options_config_generate_manpage_merged(), and options_config_generate_manpage_template().
manpage_merger_merge_environment()
char * manpage_merger_merge_environment (const options_config_t * config, const parsed_section_t * existing_section)
Definition at line 41 of file merger.c.
{
  (void)existing_section; // Unused for now
  if (!config) {
    return NULL;
  }
  // For now, return empty content. In a full implementation, this would:
  // 1. Extract environment variables from config options
  // 2. Parse existing section for manual env var documentation
  // 3. Merge and deduplicate
  // 4. Return sorted, merged content
  log_debug("Merging environment section (currently unimplemented - returns empty)");
  char *content = SAFE_MALLOC(1, char *);
  content[0] = '\0';
  return content;
}
manpage_merger_merge_options()
char * manpage_merger_merge_options (const options_config_t * config, const parsed_section_t * existing_section)
Definition at line 22 of file merger.c.
{
  (void)existing_section; // Unused for now
  if (!config) {
    return NULL;
  }
  // For now, return empty content. In a full implementation, this would:
  // 1. Generate options from config
  // 2. Parse existing section for manual options
  // 3. Merge them by option name
  // 4. Return merged content
  log_debug("Merging options section (currently unimplemented - returns empty)");
  char *content = SAFE_MALLOC(1, char *);
  content[0] = '\0';
  return content;
}
manpage_merger_merge_positional()
char * manpage_merger_merge_positional (const options_config_t * config, const parsed_section_t * existing_section)
Definition at line 60 of file merger.c.
{
  (void)existing_section; // Unused for now
  if (!config) {
    return NULL;
  }
  // For now, return empty content. In a full implementation, this would:
  // 1. Generate positional arguments from config
  // 2. Parse existing section for manual content
  // 3. Merge intelligently
  // 4. Return merged content
  log_debug("Merging positional section (currently unimplemented - returns empty)");
  char *content = SAFE_MALLOC(1, char *);
  content[0] = '\0';
  return content;
}