ascii-chat: ascii_query::json Namespace Reference
ascii_query::json Namespace Reference
Data Structures
class JsonValue
JSON value wrapper (can hold any JSON type).
class JsonArray
JSON array builder.
class JsonObject
JSON object builder.
Functions
std::string escape (const std::string &str)
Escape a string for JSON output.
Function Documentation
escape()
std::string ascii_query::json::escape (const std::string & str) inline
Escape a string for JSON output.
Definition at line 30 of file json.h.
{
  std::string result;
  result.reserve(str.size() + 16);
  for (char c : str) {
    switch (c) {
    case '"':
      result += "\\\"";
      break;
    case '\\':
      result += "\\\\";
      break;
    case '\b':
      result += "\\b";
      break;
    case '\f':
      result += "\\f";
      break;
    case '\n':
      result += "\\n";
      break;
    case '\r':
      result += "\\r";
      break;
    case '\t':
      result += "\\t";
      break;
    default:
      if (static_cast<unsigned char>(c) < 0x20) {
        // Control character - escape as \uXXXX
        char buf[8];
        snprintf(buf, sizeof(buf), "\\u%04x", static_cast<unsigned char>(c));
        result += buf;
      } else {
        result += c;
      }
      break;
    }
  }
  return result;
}
Referenced by ascii_query::HttpResponse::badRequest(), ascii_query::HttpResponse::notFound(), ascii_query::HttpResponse::serverError(), ascii_query::json::JsonObject::toString(), and ascii_query::json::JsonValue::toString().