ascii-chat: mdns.c File Reference
mdns.c File Reference
mDNS service discovery implementation for ascii-chat
Data Structures
struct asciichat_mdns_t
Internal mDNS context structure.
Macros
#define MDNS_BUFFER_SIZE (4 * 1024)
mDNS packet buffer size (4KB should handle most service records)
Functions
asciichat_mdns_t * asciichat_mdns_init (void)
void asciichat_mdns_destroy (asciichat_mdns_t *mdns)
asciichat_error_t asciichat_mdns_advertise (asciichat_mdns_t *mdns, const asciichat_mdns_service_t *service)
asciichat_error_t asciichat_mdns_unadvertise (asciichat_mdns_t *mdns, const char *service_name)
asciichat_error_t asciichat_mdns_query (asciichat_mdns_t *mdns, const char *service_type, asciichat_mdns_discovery_callback_fn callback, void *user_data)
asciichat_error_t asciichat_mdns_update (asciichat_mdns_t *mdns, int timeout_ms)
int asciichat_mdns_get_socket (asciichat_mdns_t *mdns)
Detailed Description
mDNS service discovery implementation for ascii-chat
Wraps the mdns library (https://github.com/mjansson/mdns) with ascii-chat specific API. This implementation provides service advertisement and discovery for LAN-based sessions.
Definition in file network/mdns/mdns.c.
Macro Definition Documentation
MDNS_BUFFER_SIZE
#define MDNS_BUFFER_SIZE (4 * 1024)
mDNS packet buffer size (4KB should handle most service records)
Definition at line 34 of file network/mdns/mdns.c.
Referenced by asciichat_mdns_init().
Function Documentation
asciichat_mdns_advertise()
asciichat_error_t asciichat_mdns_advertise (asciichat_mdns_t * mdns, const asciichat_mdns_service_t * service)
Definition at line 85 of file network/mdns/mdns.c.
{
  if (!mdns || !service) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "mDNS context or service is NULL");
  }
  if (!service->name || !service->type || !service->host) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Service name, type, or host is NULL");
  }
  log_debug("Advertising mDNS service: %s (%s:%d)", service->name, service->host, service->port);
  /* TODO: Implement actual advertisement using mdns library
   * This will involve creating service records and sending announcements
   * The mdns library provides mdns_announce_* functions for this
   */
  return ASCIICHAT_OK;
}
Referenced by acds_main().
asciichat_mdns_destroy()
void asciichat_mdns_destroy (asciichat_mdns_t * mdns)
Definition at line 71 of file network/mdns/mdns.c.
{
  if (!mdns) {
    return;
  }
  if (mdns->socket_fd >= 0) {
    mdns_socket_close(mdns->socket_fd);
  }
  SAFE_FREE(mdns->buffer);
  SAFE_FREE(mdns);
  log_debug("mDNS context shutdown");
}
References asciichat_mdns_t::buffer, and asciichat_mdns_t::socket_fd.
Referenced by acds_main(), discovery_mdns_query(), and server_main().
asciichat_mdns_get_socket()
int asciichat_mdns_get_socket (asciichat_mdns_t * mdns)
Definition at line 289 of file network/mdns/mdns.c.
{
  if (!mdns) {
    return -1;
  }
  return mdns->socket_fd;
}
References asciichat_mdns_t::socket_fd.
asciichat_mdns_init()
asciichat_mdns_t * asciichat_mdns_init (void)
Definition at line 36 of file network/mdns/mdns.c.
{
  asciichat_mdns_t *mdns = SAFE_MALLOC(sizeof(asciichat_mdns_t), asciichat_mdns_t *);
  if (!mdns) {
    SET_ERRNO(ERROR_MEMORY, "Failed to allocate mDNS context");
    return NULL;
  }
  memset(mdns, 0, sizeof(asciichat_mdns_t));
  /* Allocate I/O buffer for mDNS packets */
  mdns->buffer = SAFE_MALLOC(MDNS_BUFFER_SIZE, uint8_t *);
  if (!mdns->buffer) {
    SAFE_FREE(mdns);
    SET_ERRNO(ERROR_MEMORY, "Failed to allocate mDNS buffer");
    return NULL;
  }
  mdns->buffer_capacity = MDNS_BUFFER_SIZE;
  /* Open IPv4 mDNS socket */
  mdns->socket_fd = mdns_socket_open_ipv4(NULL);
  if (mdns->socket_fd < 0) {
    SAFE_FREE(mdns->buffer);
    SAFE_FREE(mdns);
    SET_ERRNO(ERROR_NETWORK_BIND, "Failed to open mDNS socket");
    return NULL;
  }
  log_dev("mDNS context initialized (socket: %d, buffer: %zu bytes)", mdns->socket_fd, mdns->buffer_capacity);
  // Register mDNS context for debugging
  NAMED_REGISTER_CONTEXT(mdns, "asciichat_mdns", "mdns_context", NULL);
  return mdns;
}
References asciichat_mdns_t::buffer, asciichat_mdns_t::buffer_capacity, MDNS_BUFFER_SIZE, and asciichat_mdns_t::socket_fd.
Referenced by acds_main(), discovery_mdns_query(), and server_main().
asciichat_mdns_query()
asciichat_error_t asciichat_mdns_query (asciichat_mdns_t * mdns, const char * service_type, asciichat_mdns_discovery_callback_fn callback, void * user_data)
Definition at line 229 of file network/mdns/mdns.c.
{
  if (!mdns || !service_type || !callback) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid mDNS query parameters");
  }
  /* Validate service type is non-empty and has minimum length
   * Prevents underflow bug in mdns library when processing empty strings
   */
  size_t service_type_len = strlen(service_type);
  if (service_type_len == 0) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Service type cannot be empty");
  }
  mdns->callback = callback;
  mdns->callback_data = user_data;
  log_info("Starting mDNS query for: %s", service_type);
  /* Send PTR query for service type (one-shot query)
   * PTR query discovers all instances of a service type
   * mdns_query_send returns the query ID for response filtering
   */
  int query_id = mdns_query_send(mdns->socket_fd, MDNS_RECORDTYPE_PTR, service_type, service_type_len, mdns->buffer,
                                 mdns->buffer_capacity, 0);
  if (query_id < 0) {
    return SET_ERRNO(ERROR_NETWORK, "mDNS query send failed for %s (query_id=%d)", service_type, query_id);
  }
  mdns->query_id = (uint16_t)query_id;
  log_debug("mDNS query sent for service type: %s (query_id: %d)", service_type, query_id);
  return ASCIICHAT_OK;
}
References asciichat_mdns_t::buffer, asciichat_mdns_t::buffer_capacity, asciichat_mdns_t::callback, asciichat_mdns_t::callback_data, asciichat_mdns_t::query_id, and asciichat_mdns_t::socket_fd.
Referenced by discovery_mdns_query().
asciichat_mdns_unadvertise()
asciichat_error_t asciichat_mdns_unadvertise (asciichat_mdns_t * mdns, const char * service_name)
Definition at line 103 of file network/mdns/mdns.c.
{
  if (!mdns || !service_name) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "mDNS context or service name is NULL");
  }
  log_info("Stopped advertising service: %s", service_name);
  /* TODO: Implement actual unadvertisement
   * This will involve sending goodbye records with TTL=0
   */
  return ASCIICHAT_OK;
}
asciichat_mdns_update()
asciichat_error_t asciichat_mdns_update (asciichat_mdns_t * mdns, int timeout_ms)
Definition at line 265 of file network/mdns/mdns.c.
{
  if (!mdns) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "mDNS context is NULL");
  }
  /* Process incoming mDNS packets (responses from previous queries)
   * mdns_query_recv processes all records received since last call
   * The callback function (mdns_record_callback) is invoked for each record
   */
  int num_records =
      mdns_query_recv(mdns->socket_fd, mdns->buffer, mdns->buffer_capacity, mdns_record_callback, mdns, mdns->query_id);
  if (num_records < 0) {
    return SET_ERRNO(ERROR_NETWORK, "Failed to receive mDNS query responses");
  }
  if (num_records > 0) {
    log_debug("Processed %d mDNS records", num_records);
  }
  (void)timeout_ms;
  return ASCIICHAT_OK;
}
References asciichat_mdns_t::buffer, asciichat_mdns_t::buffer_capacity, asciichat_mdns_t::query_id, and asciichat_mdns_t::socket_fd.
Referenced by discovery_mdns_query().