ascii-chat: handlers.c File Reference
handlers.c File Reference
ACIP protocol packet handlers implementation.
Data Structures
struct handler_hash_entry_t
Hash table entry for packet type to handler mapping.
Macros
#define HANDLER_HASH_SIZE 32
#define CLIENT_HANDLER_COUNT 19
#define SERVER_HANDLER_COUNT 20
#define HANDLER_HASH(type)
Typedefs
typedef asciichat_error_t(* acip_client_handler_func_t) (const void *payload, size_t payload_len, const acip_client_callbacks_t *callbacks)
typedef asciichat_error_t(* acip_server_handler_func_t) (const void *payload, size_t payload_len, void *client_ctx, const acip_server_callbacks_t *callbacks)
Functions
asciichat_error_t acip_handle_client_packet (acip_transport_t *transport, packet_type_t type, const void *payload, size_t payload_len, const acip_client_callbacks_t *callbacks)
asciichat_error_t acip_handle_server_packet (acip_transport_t *transport, packet_type_t type, const void *payload, size_t payload_len, void *client_ctx, const acip_server_callbacks_t *callbacks)
Detailed Description
ACIP protocol packet handlers implementation.
Implements packet dispatching for both client and server sides. Uses O(1) array-based dispatch instead of O(n) switch statements. Parses packet payloads and dispatches to registered callbacks.
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
Definition in file network/acip/handlers.c.
Macro Definition Documentation
CLIENT_HANDLER_COUNT
#define CLIENT_HANDLER_COUNT 19
Definition at line 42 of file network/acip/handlers.c.
HANDLER_HASH
#define HANDLER_HASH (type)
Value:
((type) % HANDLER_HASH_SIZE)
Definition at line 54 of file network/acip/handlers.c.
HANDLER_HASH_SIZE
#define HANDLER_HASH_SIZE 32
Definition at line 41 of file network/acip/handlers.c.
SERVER_HANDLER_COUNT
#define SERVER_HANDLER_COUNT 20
Definition at line 43 of file network/acip/handlers.c.
Typedef Documentation
acip_client_handler_func_t
typedef asciichat_error_t(* acip_client_handler_func_t) (const void *payload, size_t payload_len, const acip_client_callbacks_t *callbacks)
Definition at line 29 of file network/acip/handlers.c.
acip_server_handler_func_t
typedef asciichat_error_t(* acip_server_handler_func_t) (const void *payload, size_t payload_len, void *client_ctx, const acip_server_callbacks_t *callbacks)
Definition at line 32 of file network/acip/handlers.c.
Function Documentation
acip_handle_client_packet()
asciichat_error_t acip_handle_client_packet (acip_transport_t * transport, packet_type_t type, const void * payload, size_t payload_len, const acip_client_callbacks_t * callbacks)
Definition at line 196 of file network/acip/handlers.c.
{
  if (!transport || !callbacks) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid transport or callbacks");
  }
  (void)transport;
  // O(1) dispatch via hash table lookup
  int idx = handler_hash_lookup(g_client_handler_hash, type);
  if (idx < 0) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Unhandled client packet type: %d", type);
  }
  return g_client_handlers[idx](payload, payload_len, callbacks);
}
Referenced by acip_client_receive_and_dispatch().
acip_handle_server_packet()
asciichat_error_t acip_handle_server_packet (acip_transport_t * transport, packet_type_t type, const void * payload, size_t payload_len, void * client_ctx, const acip_server_callbacks_t * callbacks)
Definition at line 687 of file network/acip/handlers.c.
{
  if (!transport || !callbacks) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid transport or callbacks");
  }
  (void)transport;
  // DEBUG: Log all packet types received
  log_info("ACIP_HANDLE: Received packet type=%d (0x%04x), payload_len=%zu", type, type, payload_len);
  // O(1) dispatch via hash table lookup
  int idx = handler_hash_lookup(g_server_handler_hash, type);
  if (idx < 0) {
    log_error("ACIP_HANDLER_NOT_FOUND: No handler for packet type=%d (0x%04x, name=%s)", type, type,
              g_packet_type_name(type));
    return SET_ERRNO(ERROR_INVALID_PARAM, "Unhandled server packet type: %d", type);
  }
  log_info("📥 [HANDLER_DISPATCH] Calling handler: type=%d (%s), handler_idx=%d, payload=%zu bytes, client_ctx=%p",
           type, g_packet_type_name(type), idx, payload_len, client_ctx);
  asciichat_error_t result = g_server_handlers[idx](payload, payload_len, client_ctx, callbacks);
  if (result != ASCIICHAT_OK) {
    log_error("❌ [HANDLER_ERROR] Handler failed: type=%d (%s), result=%d", type, g_packet_type_name(type), result);
  } else {
    log_info("✅ [HANDLER_COMPLETE] Handler succeeded: type=%d (%s), payload=%zu bytes processed", type,
             g_packet_type_name(type), payload_len);
  }
  return result;
}
Referenced by acip_server_receive_and_dispatch(), and client_dispatch_thread().