ascii-chat: mode_defaults.c File Reference
mode_defaults.c File Reference
Mode-aware default value getters for options.
Data Structures
struct mode_descriptor_t
Metadata for a mode.
Functions
const mode_descriptor_t * get_mode_descriptor (asciichat_mode_t mode)
Get mode descriptor by mode.
const mode_descriptor_t * get_modes_by_group (const char *group, size_t *out_count)
Get all mode descriptors grouped by category.
const void * get_default_log_file (asciichat_mode_t mode)
Get mode-specific default value for –log-file.
const void * get_default_port (asciichat_mode_t mode)
Get mode-specific default value for –port.
const void * get_default_websocket_port (asciichat_mode_t mode)
Get mode-specific default value for –websocket-port.
void apply_mode_specific_defaults (options_t *opts)
Apply mode-specific defaults to an options struct after mode detection.
Detailed Description
Mode-aware default value getters for options.
Provides mode-specific default values for options that vary by mode, and mode metadata (names, descriptions, groups) for UI generation.
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
February 2026
Definition in file options/registry/mode_defaults.c.
Function Documentation
apply_mode_specific_defaults()
void apply_mode_specific_defaults (options_t * opts)
Apply mode-specific defaults to an options struct after mode detection.
This function updates options that have mode-dependent defaults (port and websocket_port) based on the detected mode. Log file paths are handled separately by options_get_log_filepath().
Parameters
opts Options struct to update (must have detected_mode already set)
Definition at line 192 of file options/registry/mode_defaults.c.
{
  if (!opts) {
    return;
  }
  // Apply port default based on mode
  const int *mode_port = (const int *)get_default_port(opts->detected_mode);
  if (mode_port) {
    // Only update if still at a generic default (27224 or 27225)
    if (opts->port == OPT_PORT_INT_DEFAULT || opts->port == OPT_ACDS_PORT_INT_DEFAULT) {
      opts->port = *mode_port;
    }
  }
  // Apply websocket-port default based on mode
  const int *mode_websocket_port = (const int *)get_default_websocket_port(opts->detected_mode);
  if (mode_websocket_port) {
    // Only update if still at a generic default (27226 or 27227)
    if (opts->websocket_port == OPT_WEBSOCKET_PORT_SERVER_DEFAULT ||
        opts->websocket_port == OPT_WEBSOCKET_PORT_ACDS_DEFAULT) {
      opts->websocket_port = *mode_websocket_port;
    }
  }
}
References get_default_port(), and get_default_websocket_port().
Referenced by options_init().
get_default_log_file()
const void * get_default_log_file (asciichat_mode_t mode)
Get mode-specific default value for –log-file.
Returns empty string - the actual log file path is determined by options_get_log_filepath() which properly handles debug vs release builds and platform-specific temp directories.
Debug builds: Uses current working directory (server.log, client.log, etc.) Release builds: Uses $TMPDIR/ascii-chat/server.log, etc.
Definition at line 117 of file options/registry/mode_defaults.c.
{
  (void)mode; // Unused
  // Return empty string - let options_get_log_filepath() handle the defaults
  return "";
}
get_default_port()
const void * get_default_port (asciichat_mode_t mode)
Get mode-specific default value for –port.
Definition at line 135 of file options/registry/mode_defaults.c.
{
  switch (mode) {
  case MODE_SERVER:
    return &g_port_server;
  case MODE_CLIENT:
    return &g_port_client;
  case MODE_DISCOVERY_SERVICE:
    return &g_port_discovery_service;
  case MODE_DISCOVERY:
    return &g_port_discovery;
  case MODE_MIRROR:
  case MODE_INVALID:
  default:
    // Fallback
    return &g_port_server;
  }
}
Referenced by apply_mode_specific_defaults().
get_default_websocket_port()
const void * get_default_websocket_port (asciichat_mode_t mode)
Get mode-specific default value for –websocket-port.
Definition at line 163 of file options/registry/mode_defaults.c.
{
  switch (mode) {
  case MODE_SERVER:
    return &g_websocket_port_server;
  case MODE_DISCOVERY_SERVICE:
    return &g_websocket_port_discovery_service;
  case MODE_CLIENT:
  case MODE_MIRROR:
  case MODE_DISCOVERY:
  case MODE_INVALID:
  default:
    // Fallback (should not be used for client/mirror/discovery)
    return &g_websocket_port_server;
  }
}
Referenced by apply_mode_specific_defaults().
get_mode_descriptor()
const mode_descriptor_t * get_mode_descriptor (asciichat_mode_t mode)
Get mode descriptor by mode.
Parameters
mode Mode to look up
Returns
Pointer to mode descriptor, or NULL if not found
Definition at line 49 of file options/registry/mode_defaults.c.
{
  for (size_t i = 0; g_mode_descriptors[i].name; i++) {
    if (g_mode_descriptors[i].mode == mode) {
      return &g_mode_descriptors[i];
    }
  }
  return NULL;
}
get_modes_by_group()
const mode_descriptor_t * get_modes_by_group (const char * group, size_t * out_count)
Get all mode descriptors grouped by category.
Parameters
group Group name ("server-like" or "client-like")
out_count OUTPUT: Number of modes in this group
Returns
Array of mode descriptors, or NULL if group not found
Definition at line 64 of file options/registry/mode_defaults.c.
{
  if (!group || !out_count) {
    return NULL;
  }
  // Count matching modes
  size_t count = 0;
  for (size_t i = 0; g_mode_descriptors[i].name; i++) {
    if (strcmp(g_mode_descriptors[i].group, group) == 0) {
      count++;
    }
  }
  if (count == 0) {
    *out_count = 0;
    return NULL;
  }
  // Allocate result array
  mode_descriptor_t *result = SAFE_MALLOC((count + 1) * sizeof(mode_descriptor_t), mode_descriptor_t *);
  size_t idx = 0;
  // Fill result array
  for (size_t i = 0; g_mode_descriptors[i].name && idx < count; i++) {
    if (strcmp(g_mode_descriptors[i].group, group) == 0) {
      result[idx++] = g_mode_descriptors[i];
    }
  }
  // Add terminator
  result[idx].mode = MODE_INVALID;
  result[idx].name = NULL;
  result[idx].description = NULL;
  result[idx].group = NULL;
  *out_count = count;
  return result;
}
References mode_descriptor_t::description, mode_descriptor_t::group, mode_descriptor_t::mode, and mode_descriptor_t::name.
Referenced by completions_generate_zsh().