ascii-chat: options.h File Reference
options.h File Reference
WASM option accessor declarations.
Functions
int set_width (int value)
int get_width (void)
int set_height (int value)
int get_height (void)
int set_color_mode (int mode)
int get_color_mode (void)
int set_color_filter (int filter)
int get_color_filter (void)
int set_palette (const char *palette_name)
int get_palette (void)
int set_palette_chars (const char *chars)
const char * get_palette_chars (void)
int set_matrix_rain (int enabled)
int get_matrix_rain (void)
int set_flip_x (int enabled)
int get_flip_x (void)
int set_target_fps (int fps)
int get_target_fps (void)
const char * get_help_text (int mode, const char *option_name)
Detailed Description
WASM option accessor declarations.
Declares setter/getter functions for common web settings. Implementations in options.c are compiled into both mirror.wasm and client.wasm.
Definition in file options.h.
Function Documentation
get_color_filter()
int get_color_filter (void)
Definition at line 74 of file src/web/common/options.c.
{
  return GET_OPTION(color_filter);
}
get_color_mode()
int get_color_mode (void)
Definition at line 59 of file src/web/common/options.c.
{
  return GET_OPTION(color_mode);
}
get_flip_x()
int get_flip_x (void)
Definition at line 146 of file src/web/common/options.c.
                     {
  return GET_OPTION(flip_x) ? 1 : 0;
}
get_height()
int get_height (void)
Definition at line 44 of file src/web/common/options.c.
                     {
  return GET_OPTION(height);
}
get_help_text()
const char * get_help_text (int mode, const char * option_name)
Get help text for a CLI option in a specific mode Exported to WASM for JavaScript access via FFI
Parameters
mode The mode (asciichat_mode_t as int)
option_name The long name of the option
Returns
Help text string or NULL if not applicable
Definition at line 195 of file src/web/common/options.c.
{
  if (!option_name || !option_name[0])
    return NULL;
  asciichat_mode_t mode_enum = (asciichat_mode_t)mode;
  return options_get_help_text(mode_enum, option_name);
}
References options_get_help_text().
get_matrix_rain()
int get_matrix_rain (void)
Definition at line 131 of file src/web/common/options.c.
{
  return GET_OPTION(matrix_rain) ? 1 : 0;
}
get_palette()
int get_palette (void)
Definition at line 103 of file src/web/common/options.c.
                      {
  return GET_OPTION(palette_type);
}
get_palette_chars()
const char * get_palette_chars (void)
Definition at line 116 of file src/web/common/options.c.
{
  return GET_OPTION(palette_custom);
}
get_target_fps()
int get_target_fps (void)
Definition at line 178 of file src/web/common/options.c.
{
  return GET_OPTION(fps);
}
get_width()
int get_width (void)
Definition at line 31 of file src/web/common/options.c.
                    {
  return GET_OPTION(width);
}
set_color_filter()
int set_color_filter (int filter)
Definition at line 68 of file src/web/common/options.c.
{
  asciichat_error_t err = options_set_int("color_filter", filter);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References options_set_int().
set_color_mode()
int set_color_mode (int mode)
Definition at line 53 of file src/web/common/options.c.
{
  asciichat_error_t err = options_set_int("color_mode", mode);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References options_set_int().
set_flip_x()
int set_flip_x (int enabled)
Definition at line 140 of file src/web/common/options.c.
{
  asciichat_error_t err = options_set_bool("flip_x", enabled != 0);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References enabled, and options_set_bool().
set_height()
int set_height (int value)
Definition at line 36 of file src/web/common/options.c.
{
  if (value <= 0 || value > 1000)
    return -1;
  asciichat_error_t err = options_set_int("height", value);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References options_set_int().
set_matrix_rain()
int set_matrix_rain (int enabled)
Definition at line 125 of file src/web/common/options.c.
{
  asciichat_error_t err = options_set_bool("matrix_rain", enabled != 0);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References enabled, and options_set_bool().
set_palette()
int set_palette (const char * palette_name)
Definition at line 83 of file src/web/common/options.c.
{
  if (!palette_name)
    return -1;
  palette_type_t palette_value;
  char *error_msg = NULL;
  if (!parse_palette_type(palette_name, &palette_value, &error_msg)) {
    if (error_msg) {
      log_error("Failed to parse palette '%s': %s", palette_name, error_msg);
      free(error_msg);
    }
    return -1;
  }
  asciichat_error_t err = options_set_int("palette_type", (int)palette_value);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References options_set_int(), and parse_palette_type().
set_palette_chars()
int set_palette_chars (const char * chars)
Definition at line 108 of file src/web/common/options.c.
{
  if (!chars)
    return -1;
  asciichat_error_t err = options_set_string("palette_custom", chars);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References options_set_string().
set_target_fps()
int set_target_fps (int fps)
Definition at line 170 of file src/web/common/options.c.
{
  if (fps < 15 || fps > 60)
    return -1;
  asciichat_error_t err = options_set_int("fps", fps);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References options_set_int().
set_width()
int set_width (int value)
Definition at line 23 of file src/web/common/options.c.
{
  if (value <= 0 || value > 1000)
    return -1;
  asciichat_error_t err = options_set_int("width", value);
  return (err == ASCIICHAT_OK) ? 0 : -1;
}
References options_set_int().