ascii-chat: output_buffer.c File Reference
output_buffer.c File Reference
Functions
void ob_reserve (outbuf_t *ob, size_t need)
void ob_putc (outbuf_t *ob, char c)
void ob_write (outbuf_t *ob, const char *s, size_t n)
void ob_term (outbuf_t *ob)
void ob_u8 (outbuf_t *ob, uint8_t v)
void ob_u32 (outbuf_t *ob, uint32_t v)
void emit_set_truecolor_fg (outbuf_t *ob, uint8_t r, uint8_t g, uint8_t b)
void emit_set_truecolor_bg (outbuf_t *ob, uint8_t r, uint8_t g, uint8_t b)
void emit_reset (outbuf_t *ob)
bool rep_is_profitable (uint32_t runlen)
void emit_rep (outbuf_t *ob, uint32_t extra)
void emit_set_256_color_fg (outbuf_t *ob, uint8_t color_idx)
void emit_set_256_color_bg (outbuf_t *ob, uint8_t color_idx)
void emit_set_fg (outbuf_t *ob, uint8_t r, uint8_t g, uint8_t b)
void emit_set_bg (outbuf_t *ob, uint8_t r, uint8_t g, uint8_t b)
Function Documentation
emit_rep()
void emit_rep (outbuf_t * ob, uint32_t extra)
Definition at line 156 of file output_buffer.c.
{
  if (!ob)
    return;
  // ESC [ extra b
  ob_putc(ob, 0x1b);
  ob_putc(ob, '[');
  ob_u32(ob, extra);
  ob_putc(ob, 'b');
}
References ob_putc(), and ob_u32().
Referenced by ansi_compress_rle(), image_print(), rgb_to_16color_halfblocks_scalar(), rgb_to_256color_halfblocks_scalar(), rgb_to_halfblocks_scalar(), and rgb_to_truecolor_halfblocks_scalar().
emit_reset()
void emit_reset (outbuf_t * ob)
Definition at line 138 of file output_buffer.c.
{
  if (!ob)
    return;
  ob_putc(ob, 0x1b);
  ob_putc(ob, '[');
  ob_putc(ob, '0');
  ob_putc(ob, 'm');
}
References ob_putc().
Referenced by rgb_to_16color_halfblocks_scalar(), rgb_to_256color_halfblocks_scalar(), and rgb_to_truecolor_halfblocks_scalar().
emit_set_256_color_bg()
void emit_set_256_color_bg (outbuf_t * ob, uint8_t color_idx)
Definition at line 177 of file output_buffer.c.
{
  if (!ob)
    return;
  // Use pre-cached color sequence instead of building on-demand
  uint8_t seq_len;
  const char *seq = get_sgr256_bg_string(color_idx, &seq_len);
  ob_write(ob, seq, seq_len);
}
References get_sgr256_bg_string(), and ob_write().
emit_set_256_color_fg()
void emit_set_256_color_fg (outbuf_t * ob, uint8_t color_idx)
Definition at line 167 of file output_buffer.c.
{
  if (!ob)
    return;
  // Use pre-cached color sequence instead of building on-demand
  uint8_t seq_len;
  const char *seq = get_sgr256_fg_string(color_idx, &seq_len);
  ob_write(ob, seq, seq_len);
}
References get_sgr256_fg_string(), and ob_write().
emit_set_bg()
void emit_set_bg (outbuf_t * ob, uint8_t r, uint8_t g, uint8_t b)
Definition at line 201 of file output_buffer.c.
{
  if (!ob)
    return;
  // ESC[48;2;R;G;Bm
  ob_putc(ob, 0x1b);
  ob_putc(ob, '[');
  ob_write(ob, "48;2;", 5);
  ob_u8(ob, r);
  ob_putc(ob, ';');
  ob_u8(ob, g);
  ob_putc(ob, ';');
  ob_u8(ob, b);
  ob_putc(ob, 'm');
}
References ob_putc(), ob_u8(), and ob_write().
Referenced by rgb_to_truecolor_halfblocks_scalar().
emit_set_fg()
void emit_set_fg (outbuf_t * ob, uint8_t r, uint8_t g, uint8_t b)
Definition at line 186 of file output_buffer.c.
{
  if (!ob)
    return;
  // ESC[38;2;R;G;Bm
  ob_putc(ob, 0x1b);
  ob_putc(ob, '[');
  ob_write(ob, "38;2;", 5);
  ob_u8(ob, r);
  ob_putc(ob, ';');
  ob_u8(ob, g);
  ob_putc(ob, ';');
  ob_u8(ob, b);
  ob_putc(ob, 'm');
}
References ob_putc(), ob_u8(), and ob_write().
Referenced by rgb_to_truecolor_halfblocks_scalar().
emit_set_truecolor_bg()
void emit_set_truecolor_bg (outbuf_t * ob, uint8_t r, uint8_t g, uint8_t b)
Definition at line 123 of file output_buffer.c.
{
  if (!ob)
    return;
  // ESC[48;2;R;G;Bm
  ob_putc(ob, 0x1b);
  ob_putc(ob, '[');
  ob_write(ob, "48;2;", 5);
  ob_u8(ob, r);
  ob_putc(ob, ';');
  ob_u8(ob, g);
  ob_putc(ob, ';');
  ob_u8(ob, b);
  ob_putc(ob, 'm');
}
References ob_putc(), ob_u8(), and ob_write().
emit_set_truecolor_fg()
void emit_set_truecolor_fg (outbuf_t * ob, uint8_t r, uint8_t g, uint8_t b)
Definition at line 107 of file output_buffer.c.
{
  if (!ob)
    return;
  // ESC[38;2;R;G;Bm
  ob_putc(ob, 0x1b);
  ob_putc(ob, '[');
  ob_write(ob, "38;2;", 5);
  ob_u8(ob, r);
  ob_putc(ob, ';');
  ob_u8(ob, g);
  ob_putc(ob, ';');
  ob_u8(ob, b);
  ob_putc(ob, 'm');
}
References ob_putc(), ob_u8(), and ob_write().
ob_putc()
void ob_putc (outbuf_t * ob, char c)
Definition at line 43 of file output_buffer.c.
{
  if (!ob)
    return;
  ob_reserve(ob, 1);
  ob->buf[ob->len++] = c;
}
References ob_reserve().
Referenced by ansi_compress_rle(), emit_rep(), emit_reset(), emit_set_bg(), emit_set_fg(), emit_set_truecolor_bg(), emit_set_truecolor_fg(), image_print(), ob_u8(), rgb_to_16color_halfblocks_scalar(), rgb_to_256color_halfblocks_scalar(), rgb_to_halfblocks_scalar(), and rgb_to_truecolor_halfblocks_scalar().
ob_reserve()
void ob_reserve (outbuf_t * ob, size_t need)
Definition at line 22 of file output_buffer.c.
{
  if (!ob)
    return;
  if (ob->cap == 0) {
    // Always allocate at least default capacity on first call
    size_t ncap = 4096;
    while (ncap < ob->len + need)
      ncap = (ncap * 3) / 2;
    // SAFE_REALLOC handles NULL ptr as malloc - this is safe
    ob->buf = SAFE_REALLOC(ob->buf, ncap, char *);
    ob->cap = ncap;
  } else if (ob->len + need > ob->cap) {
    // Expand existing buffer
    size_t ncap = ob->cap;
    while (ncap < ob->len + need)
      ncap = (ncap * 3) / 2;
    ob->buf = SAFE_REALLOC(ob->buf, ncap, char *);
    ob->cap = ncap;
  }
}
Referenced by ansi_compress_rle(), ansi_expand_rle(), ob_putc(), ob_term(), ob_u32(), and ob_write().
ob_term()
void ob_term (outbuf_t * ob)
Definition at line 58 of file output_buffer.c.
{
  if (!ob)
    return;
  // Reserve space for null terminator if needed
  if (ob->len >= ob->cap) {
    ob_reserve(ob, 1);
  }
  // Append null terminator WITHOUT incrementing length
  // (null terminator is not part of the string length)
  ob->buf[ob->len] = '\0';
}
References ob_reserve().
Referenced by ansi_compress_rle(), ansi_expand_rle(), image_print(), rgb_to_16color_halfblocks_scalar(), rgb_to_256color_halfblocks_scalar(), rgb_to_halfblocks_scalar(), and rgb_to_truecolor_halfblocks_scalar().
ob_u32()
void ob_u32 (outbuf_t * ob, uint32_t v)
Definition at line 92 of file output_buffer.c.
{
  if (!ob)
    return;
  char tmp[10];
  int i = 0;
  do {
    tmp[i++] = '0' + (v % 10u);
    v /= 10u;
  } while (v);
  ob_reserve(ob, (size_t)i);
  while (i--)
    ob->buf[ob->len++] = tmp[i];
}
References ob_reserve().
Referenced by emit_rep().
ob_u8()
void ob_u8 (outbuf_t * ob, uint8_t v)
Definition at line 71 of file output_buffer.c.
{
  if (!ob)
    return;
  if (v >= 100) {
    uint8_t d0 = v / 100;
    uint8_t r = v % 100;
    uint8_t d1 = r / 10;
    uint8_t d2 = r % 10;
    ob_putc(ob, '0' + d0);
    ob_putc(ob, '0' + d1);
    ob_putc(ob, '0' + d2);
  } else if (v >= 10) {
    uint8_t d1 = v / 10;
    uint8_t d2 = v % 10;
    ob_putc(ob, '0' + d1);
    ob_putc(ob, '0' + d2);
  } else {
    ob_putc(ob, '0' + v);
  }
}
References ob_putc().
Referenced by emit_set_bg(), emit_set_fg(), emit_set_truecolor_bg(), and emit_set_truecolor_fg().
ob_write()
void ob_write (outbuf_t * ob, const char * s, size_t n)
Definition at line 50 of file output_buffer.c.
{
  if (!ob || n == 0)
    return;
  ob_reserve(ob, n);
  SAFE_MEMCPY(ob->buf + ob->len, ob->cap - ob->len, s, n);
  ob->len += n;
}
References ob_reserve().
Referenced by ansi_compress_rle(), ansi_expand_rle(), emit_set_256_color_bg(), emit_set_256_color_fg(), emit_set_bg(), emit_set_fg(), emit_set_truecolor_bg(), emit_set_truecolor_fg(), image_print(), rgb_to_16color_halfblocks_scalar(), rgb_to_256color_halfblocks_scalar(), rgb_to_halfblocks_scalar(), and rgb_to_truecolor_halfblocks_scalar().
rep_is_profitable()
bool rep_is_profitable (uint32_t runlen)
Definition at line 148 of file output_buffer.c.
{
  if (runlen <= 2)
    return false;
  uint32_t k = runlen - 1;                           // Extra repetitions beyond the first character
  uint32_t rep_cost = (uint32_t)(digits_u32(k) + 3); // ESC [ digits b
  return k > rep_cost;                               // Manual repetition cost vs REP cost
}
Referenced by ansi_compress_rle(), image_print(), rgb_to_16color_halfblocks_scalar(), rgb_to_256color_halfblocks_scalar(), rgb_to_halfblocks_scalar(), and rgb_to_truecolor_halfblocks_scalar().