ascii-chat: parser.c File Reference
parser.c File Reference
Man page template parsing and section extraction implementation.
Functions
asciichat_error_t manpage_parser_parse_file (FILE *f, parsed_section_t **out_sections, size_t *out_count)
asciichat_error_t manpage_parser_parse_memory (const char *content, size_t content_len, parsed_section_t **out_sections, size_t *out_count)
void manpage_parser_free_sections (parsed_section_t *sections, size_t count)
const parsed_section_t * manpage_parser_find_section (const parsed_section_t *sections, size_t count, const char *section_name)
Detailed Description
Man page template parsing and section extraction implementation.
Parses man page templates to extract sections and detect their types (AUTO-generated, MANUAL, or MERGE sections).
Definition in file parser.c.
Function Documentation
manpage_parser_find_section()
const parsed_section_t * manpage_parser_find_section (const parsed_section_t * sections, size_t count, const char * section_name)
Definition at line 396 of file parser.c.
{
  if (!sections || !section_name) {
    return NULL;
  }
  for (size_t i = 0; i < count; i++) {
    if (sections[i].section_name && strcmp(sections[i].section_name, section_name) == 0) {
      return &sections[i];
    }
  }
  return NULL;
}
Referenced by find_section().
manpage_parser_free_sections()
void manpage_parser_free_sections (parsed_section_t * sections, size_t count)
Definition at line 379 of file parser.c.
{
  if (!sections) {
    return;
  }
  for (size_t i = 0; i < count; i++) {
    if (sections[i].section_name) {
      SAFE_FREE(sections[i].section_name);
    }
    if (sections[i].content) {
      SAFE_FREE(sections[i].content);
    }
  }
  SAFE_FREE(sections);
}
Referenced by free_parsed_sections().
manpage_parser_parse_file()
asciichat_error_t manpage_parser_parse_file (FILE * f, parsed_section_t ** out_sections, size_t * out_count)
Definition at line 338 of file parser.c.
{
  if (!f || !out_sections || !out_count) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters for manpage_parser_parse_file");
  }
  return parse_sections_internal(f, out_sections, out_count);
}
Referenced by parse_manpage_sections().
manpage_parser_parse_memory()
asciichat_error_t manpage_parser_parse_memory (const char * content, size_t content_len, parsed_section_t ** out_sections, size_t * out_count)
Definition at line 346 of file parser.c.
{
  if (!content || content_len == 0 || !out_sections || !out_count) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters for manpage_parser_parse_memory");
  }
  // Create temporary file from memory
  FILE *tmp = platform_tmpfile();
  if (!tmp) {
    return SET_ERRNO_SYS(ERROR_CONFIG, "Failed to create temporary file for memory parsing");
  }
  // Write content to temporary file
  // Write content_len + 1 to include the null terminator.
  // The embedded string is content_len + 1 bytes (content_len chars + null terminator).
  // platform_getline() needs the null terminator to properly handle EOF.
  size_t bytes_to_write = content_len + 1;
  size_t written = fwrite(content, 1, bytes_to_write, tmp);
  if (written != bytes_to_write) {
    fclose(tmp);
    return SET_ERRNO_SYS(ERROR_CONFIG, "Failed to write complete content to temporary file");
  }
  // Rewind to beginning for reading
  rewind(tmp);
  // Parse using common function
  asciichat_error_t err = parse_sections_internal(tmp, out_sections, out_count);
  fclose(tmp);
  return err;
}
References platform_tmpfile().