ascii-chat: pem.c File Reference
pem.c File Reference
📄 PEM format encoding/decoding utilities for certificates and keys (adapted from BearSSL)
Data Structures
struct bvector
Dynamic byte vector for PEM decoding.
struct pem_object_t
Parsed PEM object with name and data.
Macros
#define VECTOR(type)
#define VEC_INIT {0, 0, 0}
#define VEC_CLEAR(vec)
#define VEC_CLEAREXT(vec, fun)
#define VEC_ADD(vec, x)
#define VEC_ADDMANY(vec, xp, num)
#define VEC_ELT(vec, idx)
#define VEC_LEN(vec)
#define VEC_TOARRAY(vec)
Functions
void free_ta_contents (br_x509_trust_anchor *ta)
size_t read_trust_anchors_from_memory (anchor_list *dst, const unsigned char *pem_data, size_t pem_len)
Detailed Description
📄 PEM format encoding/decoding utilities for certificates and keys (adapted from BearSSL)
Copyright (c) 2016 Thomas Pornin porni.nosp@m.n@bo.nosp@m.let.o.nosp@m.rg Adapted for ascii-chat by Zachary Fogg me@zf.nosp@m.o.gg
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file pem.c.
Macro Definition Documentation
VEC_ADD
#define VEC_ADD (vec, x)
Value:
do {                                                                                                                 \
  (vec).buf = vector_expand((vec).buf, sizeof *((vec).buf), &(vec).ptr, &(vec).len, 1);                              \
  (vec).buf[(vec).ptr++] = (x);                                                                                      \
} while (0)
Definition at line 68 of file pem.c.
#define VEC_ADD(vec, x)                                                                                                \
  do {                                                                                                                 \
    (vec).buf = vector_expand((vec).buf, sizeof *((vec).buf), &(vec).ptr, &(vec).len, 1);                              \
    (vec).buf[(vec).ptr++] = (x);                                                                                      \
  } while (0)
Referenced by read_trust_anchors_from_memory().
VEC_ADDMANY
#define VEC_ADDMANY (vec, xp, num)
Value:
do {                                                                                                                 \
  size_t vec_num = (num);                                                                                            \
  (vec).buf = vector_expand((vec).buf, sizeof *((vec).buf), &(vec).ptr, &(vec).len, vec_num);                        \
  memcpy((vec).buf + (vec).ptr, (xp), vec_num * sizeof *((vec).buf));                                                \
  (vec).ptr += vec_num;                                                                                              \
} while (0)
Definition at line 74 of file pem.c.
#define VEC_ADDMANY(vec, xp, num)                                                                                      \
  do {                                                                                                                 \
    size_t vec_num = (num);                                                                                            \
    (vec).buf = vector_expand((vec).buf, sizeof *((vec).buf), &(vec).ptr, &(vec).len, vec_num);                        \
    memcpy((vec).buf + (vec).ptr, (xp), vec_num * sizeof *((vec).buf));                                                \
    (vec).ptr += vec_num;                                                                                              \
  } while (0)
Referenced by read_trust_anchors_from_memory().
VEC_CLEAR
#define VEC_CLEAR (vec)
Value:
do {                                                                                                                 \
  SAFE_FREE((vec).buf);                                                                                              \
  (vec).buf = NULL;                                                                                                  \
  (vec).ptr = 0;                                                                                                     \
  (vec).len = 0;                                                                                                     \
} while (0)
Definition at line 51 of file pem.c.
#define VEC_CLEAR(vec)                                                                                                 \
  do {                                                                                                                 \
    SAFE_FREE((vec).buf);                                                                                              \
    (vec).buf = NULL;                                                                                                  \
    (vec).ptr = 0;                                                                                                     \
    (vec).len = 0;                                                                                                     \
  } while (0)
Referenced by read_trust_anchors_from_memory().
VEC_CLEAREXT
#define VEC_CLEAREXT (vec, fun)
Value:
do {                                                                                                                 \
  size_t vec_tmp;                                                                                                    \
  for (vec_tmp = 0; vec_tmp < (vec).ptr; vec_tmp++) {                                                                \
    (fun)(&(vec).buf[vec_tmp]);                                                                                      \
  }                                                                                                                  \
  VEC_CLEAR(vec);                                                                                                    \
} while (0)
Definition at line 59 of file pem.c.
#define VEC_CLEAREXT(vec, fun)                                                                                         \
  do {                                                                                                                 \
    size_t vec_tmp;                                                                                                    \
    for (vec_tmp = 0; vec_tmp < (vec).ptr; vec_tmp++) {                                                                \
      (fun)(&(vec).buf[vec_tmp]);                                                                                      \
    }                                                                                                                  \
    VEC_CLEAR(vec);                                                                                                    \
  } while (0)
Referenced by read_trust_anchors_from_memory().
VEC_ELT
#define VEC_ELT (vec, idx)
Value:
((vec).buf[idx])
Definition at line 82 of file pem.c.
Referenced by read_trust_anchors_from_memory().
VEC_INIT
#define VEC_INIT {0, 0, 0}
Definition at line 48 of file pem.c.
Referenced by read_trust_anchors_from_memory().
VEC_LEN
#define VEC_LEN (vec)
Value:
((vec).ptr)
Definition at line 83 of file pem.c.
VEC_TOARRAY
#define VEC_TOARRAY (vec)
Value:
xblobdup((vec).buf, sizeof *((vec).buf) * (vec).ptr)
Definition at line 84 of file pem.c.
VECTOR
#define VECTOR (type)
Value:
struct {                                                                                                             \
  type *buf;                                                                                                         \
  size_t ptr, len;                                                                                                   \
}
Definition at line 41 of file pem.c.
#define VECTOR(type)                                                                                                   \
  struct {                                                                                                             \
    type *buf;                                                                                                         \
    size_t ptr, len;                                                                                                   \
  }
Function Documentation
free_ta_contents()
void free_ta_contents (br_x509_trust_anchor * ta)
Definition at line 428 of file pem.c.
{
  if (!ta) {
    return;
  }
  xfree(ta->dn.data);
  switch (ta->pkey.key_type) {
  case BR_KEYTYPE_RSA:
    xfree((void *)ta->pkey.key.rsa.n);
    xfree((void *)ta->pkey.key.rsa.e);
    break;
  case BR_KEYTYPE_EC:
    xfree((void *)ta->pkey.key.ec.q);
    break;
  default:
    SET_ERRNO(ERROR_CRYPTO, "Unknown public key type in CA");
    break;
  }
}
Referenced by https_get(), and read_trust_anchors_from_memory().
read_trust_anchors_from_memory()
size_t read_trust_anchors_from_memory (anchor_list * dst, const unsigned char * pem_data, size_t pem_len)
Definition at line 449 of file pem.c.
{
  br_x509_certificate *xcs;
  anchor_list tas = VEC_INIT;
  size_t u, num;
  xcs = read_certificates_from_memory(pem_data, pem_len, &num);
  if (xcs == NULL) {
    return 0;
  }
  for (u = 0; u < num; u++) {
    br_x509_trust_anchor ta;
    if (certificate_to_trust_anchor_inner(&ta, &xcs[u]) != ASCIICHAT_OK) {
      VEC_CLEAREXT(tas, free_ta_contents);
      free_certificates(xcs, num);
      return 0;
    }
    VEC_ADD(tas, ta);
  }
  VEC_ADDMANY(*dst, &VEC_ELT(tas, 0), num);
  VEC_CLEAR(tas);
  free_certificates(xcs, num);
  return num;
}
References free_ta_contents(), VEC_ADD, VEC_ADDMANY, VEC_CLEAR, VEC_CLEAREXT, VEC_ELT, and VEC_INIT.
Referenced by https_get().