ascii-chat: pipeline.c File Reference
pipeline.c File Reference
Session
Three-thread render pipeline implementation.
Data Structures
struct pipeline_frame_t
struct frame_queue_s
struct session_pipeline_s
Typedefs
typedef struct frame_queue_s frame_queue_t
Functions
asciichat_error_t session_pipeline_create (session_capture_ctx_t *capture, session_display_ctx_t *display, session_pipeline_t **out)
asciichat_error_t session_pipeline_run_main (session_pipeline_t *pipeline, session_should_exit_fn should_exit, session_keyboard_handler_fn keyboard_handler, void *user_data)
asciichat_error_t session_pipeline_destroy (session_pipeline_t *pipeline)
Variables
bool g_snapshot_first_frame_rendered
Detailed Description
Three-thread render pipeline implementation.
Definition in file pipeline.c.
Typedef Documentation
frame_queue_t
typedef struct frame_queue_s frame_queue_t
Function Documentation
session_pipeline_create()
asciichat_error_t session_pipeline_create (session_capture_ctx_t * capture, session_display_ctx_t * display, session_pipeline_t ** out)
Create and start the capture thread and (if –render-file) encode thread.
Parameters
capture Capture context (must have real media_source_t for synchronous mode)
display Display context (may have render_file set for –render-file mode)
out Pointer to receive allocated pipeline context
Returns
ASCIICHAT_OK on success, error code otherwise
Note
The pipeline does NOT own capture or display — caller must keep them alive until session_pipeline_destroy() returns.
Definition at line 379 of file pipeline.c.
{
    if (!capture || !display || !out) {
        return SET_ERRNO(ERROR_INVALID_PARAM, "session_pipeline_create: NULL argument");
    }
    session_pipeline_t *p = SAFE_CALLOC(1, sizeof(*p), session_pipeline_t *);
    p->capture = capture;
    p->display = display;
    p->display_queue = frame_queue_create(4, "display");
    p->encode_queue = frame_queue_create(256, "encode");  // Large buffer for slow encoding
    // Check if display has render_file configured (will be checked in encode thread)
    // We store a flag to know whether to enqueue frames for encoding
    double render_fps = session_display_get_render_fps(display);
    bool has_file = session_display_has_render_file(display);
    // Enable encode thread if render_file is available
    // Note: has_file can be true even if render_file creation failed (ctx->render_file exists)
    // OR if render_fps is explicitly set for playback speed control
    p->has_render_file = render_fps > 0 || has_file;
    log_info("[PIPELINE_CREATE] render_fps=%.1f, has_file=%d, has_render_file=%d",
             render_fps, has_file ? 1 : 0, p->has_render_file ? 1 : 0);
    atomic_store_bool(&p->stop, false);
    atomic_store_u64(&p->first_frame_ns, 0);
    // Start capture thread
    if (asciichat_thread_create(&p->capture_tid, "pipeline_capture", pipeline_capture_thread, p) != 0) {
        frame_queue_destroy(p->display_queue);
        frame_queue_destroy(p->encode_queue);
        SAFE_FREE(p);
        return SET_ERRNO(ERROR_INIT, "session_pipeline_create: failed to start capture thread");
    }
    // Start encode thread only if render_file is active
    if (p->has_render_file) {
        if (asciichat_thread_create(&p->encode_tid, "pipeline_encode", pipeline_encode_thread, p) != 0) {
            atomic_store_bool(&p->stop, true);
            asciichat_thread_join(&p->capture_tid, NULL);
            frame_queue_destroy(p->display_queue);
            frame_queue_destroy(p->encode_queue);
            SAFE_FREE(p);
            return SET_ERRNO(ERROR_INIT, "session_pipeline_create: failed to start encode thread");
        }
    }
    *out = p;
    return ASCIICHAT_OK;
}
References asciichat_thread_create(), asciichat_thread_join(), atomic_store_bool(), atomic_store_u64(), session_pipeline_s::capture, session_pipeline_s::capture_tid, session_pipeline_s::display, session_pipeline_s::display_queue, session_pipeline_s::encode_queue, session_pipeline_s::encode_tid, session_pipeline_s::first_frame_ns, session_pipeline_s::has_render_file, session_display_get_render_fps(), session_display_has_render_file(), and session_pipeline_s::stop.
Referenced by session_render_loop().
session_pipeline_destroy()
asciichat_error_t session_pipeline_destroy (session_pipeline_t * pipeline)
Stop threads and free pipeline.
Waits for capture and encode threads to exit cleanly.
Parameters
pipeline Pipeline context (safe to call with NULL)
Returns
ASCIICHAT_OK
Definition at line 522 of file pipeline.c.
{
    if (!pipeline) return ASCIICHAT_OK;
    log_info("[PIPELINE] Destroying pipeline, waiting for threads...");
    // Signal threads to stop (may already be stopped)
    atomic_store_bool(&pipeline->stop, true);
    // Drain and wait for capture thread
    if (asciichat_thread_is_initialized(&pipeline->capture_tid)) {
        asciichat_thread_join(&pipeline->capture_tid, NULL);
    }
    // Drain and wait for encode thread
    if (asciichat_thread_is_initialized(&pipeline->encode_tid)) {
        asciichat_thread_join(&pipeline->encode_tid, NULL);
    }
    // Flush queues
    frame_queue_flush(pipeline->display_queue, free_frame_generic);
    frame_queue_flush(pipeline->encode_queue, free_frame_generic);
    frame_queue_destroy(pipeline->display_queue);
    frame_queue_destroy(pipeline->encode_queue);
    SAFE_FREE(pipeline);
    log_info("[PIPELINE] Pipeline destroyed");
    return ASCIICHAT_OK;
}
References asciichat_thread_join(), atomic_store_bool(), session_pipeline_s::capture_tid, session_pipeline_s::display_queue, session_pipeline_s::encode_queue, session_pipeline_s::encode_tid, and session_pipeline_s::stop.
Referenced by session_render_loop().
session_pipeline_run_main()
asciichat_error_t session_pipeline_run_main (session_pipeline_t * pipeline, session_should_exit_fn should_exit, session_keyboard_handler_fn keyboard_handler, void * user_data)
Main thread loop: drives terminal output and keyboard handling.
Pops frames from display queue, converts to ASCII, writes to terminal. Handles snapshot delay timer and exit conditions.
Parameters
pipeline Pipeline context created by session_pipeline_create()
should_exit Callback to check if rendering should stop
keyboard_handler Optional keyboard handler callback
user_data Opaque data passed to callbacks
Returns
ASCIICHAT_OK on success
Note
This function blocks until should_exit() returns true or capture ends. Signals capture/encode threads to stop before returning.
Definition at line 433 of file pipeline.c.
{
    if (!pipeline || !should_exit) {
        return SET_ERRNO(ERROR_INVALID_PARAM, "session_pipeline_run_main: NULL argument");
    }
    log_info("[PIPELINE_MAIN] Starting main thread loop");
    bool snapshot_mode = GET_OPTION(snapshot_mode);
    bool snapshot_done = false;
    while (!should_exit(user_data) && !atomic_load_bool(&pipeline->stop) && !snapshot_done) {
        pipeline_frame_t *frame = (pipeline_frame_t *)frame_queue_pop(pipeline->display_queue, 100 * NS_PER_MS_INT);
        if (!frame) continue;  // timeout, check should_exit again
        // Log frame details IMMEDIATELY after popping
        log_debug("[PIPELINE_MAIN_POP] frame=%p, pixels=%p, w=%d, h=%d",
                  (void *)frame, (void *)frame->pixels, frame->w, frame->h);
        if (!frame->pixels) {
            // EOF sentinel
            log_info("[PIPELINE_MAIN_EOF] Received EOF sentinel, stopping");
            free_frame(frame);
            break;
        }
        // Validate frame before processing (catch memory corruption)
        if (!frame_is_valid(frame)) {
            log_error("Skipping frame with corrupted dimensions: w=%d, h=%d", frame->w, frame->h);
            free_frame(frame);
            continue;
        }
        log_info("[PIPELINE_MAIN_RENDER] Converting frame to ASCII: %dx%d", frame->w, frame->h);
        // Convert to ASCII
        image_t tmp = { .w = frame->w, .h = frame->h, .pixels = (rgb_pixel_t *)frame->pixels };
        char *ascii = session_display_convert_to_ascii(pipeline->display, &tmp);
        free_frame(frame);
        if (ascii) {
            // Write ASCII to terminal
            session_display_write_ascii(pipeline->display, ascii);
            SAFE_FREE(ascii);
        }
        // Keyboard polling
        if (keyboard_handler) {
            keyboard_key_t key = keyboard_read_nonblocking();
            if (key > 0) {
                keyboard_handler(NULL, (int)key, user_data);  // NULL capture ctx
            }
        }
        // Snapshot mode: check if elapsed time has reached snapshot_delay duration
        // This check runs every iteration after first frame is rendered (when display.c sets g_snapshot_first_frame_rendered)
        if (snapshot_mode && !snapshot_done) {
            if (g_snapshot_first_frame_rendered && g_snapshot_first_frame_rendered_ns > 0) {
                double snapshot_delay = GET_OPTION(snapshot_delay);
                uint64_t now_ns = time_get_ns();
                uint64_t elapsed_ns = now_ns - g_snapshot_first_frame_rendered_ns;
                double elapsed_sec = (double)elapsed_ns / (double)NS_PER_SEC_INT;
                if ((unsigned long)(elapsed_sec * 10) % 10 == 0 || elapsed_sec < 0.2) {
                    log_info("[SNAPSHOT_PIPELINE] CHECK: elapsed=%.3f target=%.2f", elapsed_sec, snapshot_delay);
                }
                // snapshot_delay=0 means exit after first frame
                // snapshot_delay>0 means wait that many seconds before exiting
                bool should_snapshot_exit = (snapshot_delay == 0.0) || (elapsed_sec >= snapshot_delay);
                if (should_snapshot_exit) {
                    log_info("[SNAPSHOT_PIPELINE] EXITING - elapsed=%.3f target=%.2f", elapsed_sec, snapshot_delay);
                    snapshot_done = true;
                }
            }
        }
    }
    log_info("[PIPELINE_MAIN] Main loop exiting, signaling threads to stop");
    atomic_store_bool(&pipeline->stop, true);
    return ASCIICHAT_OK;
}
References atomic_load_bool(), atomic_store_bool(), session_pipeline_s::display, session_pipeline_s::display_queue, frame, g_snapshot_first_frame_rendered, g_snapshot_first_frame_rendered_ns, session_display_convert_to_ascii(), session_display_write_ascii(), should_exit(), session_pipeline_s::stop, and time_get_ns().
Referenced by session_render_loop().
Variable Documentation
g_snapshot_first_frame_rendered
bool g_snapshot_first_frame_rendered extern
Definition at line 49 of file common/session/render.c.
Referenced by session_display_write_ascii(), session_pipeline_run_main(), and session_render_loop().