ascii-chat: time.c File Reference
time.c File Reference
Time functions for WASM/Emscripten.
Functions
uint64_t platform_get_time_ms (void)
uint64_t platform_get_time_us (void)
void platform_sleep_ms (unsigned int ms)
void platform_sleep_us (unsigned int us)
uint64_t platform_get_monotonic_time_ns (void)
uint64_t platform_get_monotonic_time_us (void)
Detailed Description
Time functions for WASM/Emscripten.
Definition in file platform/wasm/time.c.
Function Documentation
platform_get_monotonic_time_ns()
uint64_t platform_get_monotonic_time_ns (void)
Definition at line 38 of file platform/wasm/time.c.
{
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}
platform_get_monotonic_time_us()
uint64_t platform_get_monotonic_time_us (void)
Definition at line 44 of file platform/wasm/time.c.
{
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (uint64_t)ts.tv_sec * 1000000ULL + (uint64_t)ts.tv_nsec / 1000ULL;
}
Referenced by backtrace_print(), discovery_session_process(), server_main(), terminal_screen_render(), ui_status_update(), and webrtc_is_gathering_timed_out().
platform_get_time_ms()
uint64_t platform_get_time_ms (void)
Definition at line 12 of file platform/wasm/time.c.
{
  struct timeval tv;
  gettimeofday(&tv, NULL);
  return (uint64_t)tv.tv_sec * 1000 + (uint64_t)tv.tv_usec / 1000;
}
platform_get_time_us()
uint64_t platform_get_time_us (void)
Definition at line 18 of file platform/wasm/time.c.
{
  struct timeval tv;
  gettimeofday(&tv, NULL);
  return (uint64_t)tv.tv_sec * 1000000 + (uint64_t)tv.tv_usec;
}
platform_sleep_ms()
void platform_sleep_ms (unsigned int ms)
Definition at line 24 of file platform/wasm/time.c.
{
  struct timespec ts;
  ts.tv_sec = ms / 1000;
  ts.tv_nsec = (ms % 1000) * 1000000;
  nanosleep(&ts, NULL);
}
Referenced by acds_server_shutdown(), client_receive_thread(), client_video_render_thread(), disconnect_client_for_bad_data(), discovery_session_process(), session_client_like_run(), and ui_mdns_select().
platform_sleep_us()
void platform_sleep_us (unsigned int us)
Definition at line 31 of file platform/wasm/time.c.
{
  struct timespec ts;
  ts.tv_sec = us / 1000000;
  ts.tv_nsec = (us % 1000000) * 1000;
  nanosleep(&ts, NULL);
}
Referenced by acip_websocket_client_transport_create(), audio_client_init(), audio_stop_thread(), capture_stop_thread(), client_send_thread_func(), discovery_session_process(), platform_write_all(), protocol_stop_connection(), remove_client(), server_connection_establish(), server_main(), session_capture_create(), stats_logger_thread(), and time_sleep_ns().