ascii-chat: lifecycle.c File Reference
lifecycle.c File Reference
Functions
bool lifecycle_init (lifecycle_t *lc, const char *name)
bool lifecycle_init_once (lifecycle_t *lc)
void lifecycle_init_commit (lifecycle_t *lc)
void lifecycle_init_abort (lifecycle_t *lc)
bool lifecycle_shutdown (lifecycle_t *lc)
bool lifecycle_shutdown_forever (lifecycle_t *lc)
bool lifecycle_is_initialized (const lifecycle_t *lc)
Function Documentation
lifecycle_init()
bool lifecycle_init (lifecycle_t * lc, const char * name)
Definition at line 10 of file platform/wasm/lifecycle.c.
{
  (void)name;
  if (!lc) return false;
  atomic_store(&lc->state, LIFECYCLE_INITIALIZED);
  return true;
}
lifecycle_init_abort()
void lifecycle_init_abort (lifecycle_t * lc)
Definition at line 30 of file platform/wasm/lifecycle.c.
{
  if (!lc) return;
  atomic_store(&lc->state, LIFECYCLE_UNINITIALIZED);
}
lifecycle_init_commit()
void lifecycle_init_commit (lifecycle_t * lc)
Definition at line 25 of file platform/wasm/lifecycle.c.
{
  if (!lc) return;
  atomic_store(&lc->state, LIFECYCLE_INITIALIZED);
}
lifecycle_init_once()
bool lifecycle_init_once (lifecycle_t * lc)
Definition at line 17 of file platform/wasm/lifecycle.c.
{
  if (!lc) return false;
  // Try to transition from UNINITIALIZED to INITIALIZING
  int expected = LIFECYCLE_UNINITIALIZED;
  return atomic_cas_u64(&lc->state, &expected, LIFECYCLE_INITIALIZING);
}
References atomic_cas_u64().
lifecycle_is_initialized()
bool lifecycle_is_initialized (const lifecycle_t * lc)
Definition at line 45 of file platform/wasm/lifecycle.c.
{
  if (!lc) return false;
  return atomic_load(&((lifecycle_t *)lc)->state) == LIFECYCLE_INITIALIZED;
}
lifecycle_shutdown()
bool lifecycle_shutdown (lifecycle_t * lc)
Definition at line 35 of file platform/wasm/lifecycle.c.
{
  if (!lc) return false;
  atomic_store(&lc->state, LIFECYCLE_UNINITIALIZED);
  return true;
}
Referenced by lifecycle_shutdown_forever().
lifecycle_shutdown_forever()
bool lifecycle_shutdown_forever (lifecycle_t * lc)
Definition at line 41 of file platform/wasm/lifecycle.c.
{
  return lifecycle_shutdown(lc);
}
References lifecycle_shutdown().