ascii-chat: terminal.c File Reference
terminal.c File Reference
Terminal function stubs for WASM (not needed for mirror mode).
Functions
asciichat_error_t terminal_get_size (terminal_size_t *size)
asciichat_error_t terminal_cursor_hide (void)
asciichat_error_t terminal_cursor_show (void)
Detailed Description
Terminal function stubs for WASM (not needed for mirror mode).
Definition in file platform/wasm/stubs/terminal.c.
Function Documentation
terminal_cursor_hide()
asciichat_error_t terminal_cursor_hide (void)
Definition at line 15 of file platform/wasm/stubs/terminal.c.
{
  return ASCIICHAT_OK;
}
Referenced by ascii_write_init(), and session_display_write_ascii().
terminal_cursor_show()
asciichat_error_t terminal_cursor_show (void)
Definition at line 19 of file platform/wasm/stubs/terminal.c.
{
  return ASCIICHAT_OK;
}
Referenced by ascii_write_destroy(), log_search_enter_mode(), main(), session_display_reset(), session_display_write_ascii(), splash_intro_start(), and terminal_screen_render().
terminal_get_size()
asciichat_error_t terminal_get_size (terminal_size_t * size)
Definition at line 10 of file platform/wasm/stubs/terminal.c.
{
  (void)size;
  return SET_ERRNO(ERROR_NOT_SUPPORTED, "Terminal operations not supported in WASM");
}
Referenced by action_show_capabilities_immediate(), options_config_print_options_sections_with_width(), options_print_help_for_mode(), sdp_detect_terminal_capabilities(), terminal_get_effective_height(), terminal_get_effective_width(), and terminal_screen_render().