ascii-chat: terminal.c File Reference
terminal.c File Reference
Terminal abstraction for WASM/Emscripten via EM_JS bridge to xterm.js.
Functions
EM_JS (int, js_get_terminal_cols,(), { return Module.xterm ? Module.xterm.cols :80;})
EM_JS (int, js_get_terminal_rows,(), { return Module.xterm ? Module.xterm.rows :24;})
EM_JS (void, js_terminal_write,(const char *data, int len), { if(Module.xterm) { Module.xterm.write(UTF8ToString(data, len));} })
int platform_get_terminal_size (int *cols, int *rows)
int platform_write_terminal (const char *data, size_t len)
int platform_set_terminal_raw_mode (bool enable)
int platform_read_keyboard (char *buffer, size_t len)
bool platform_is_terminal (int fd)
int platform_get_cursor_position (int *row, int *col)
int platform_set_cursor_position (int row, int col)
asciichat_error_t get_terminal_size (unsigned short int *width, unsigned short int *height)
bool terminal_supports_utf8 (void)
bool terminal_is_piped_output (void)
bool terminal_should_color_output (int fd)
bool terminal_is_stdin_tty (void)
bool terminal_is_stdout_tty (void)
bool terminal_is_stderr_tty (void)
bool terminal_is_interactive (void)
bool terminal_should_force_stderr (void)
bool terminal_can_prompt_user (void)
bool terminal_has_dark_background (void)
asciichat_error_t terminal_flush (int fd)
terminal_capabilities_t detect_terminal_capabilities (void)
bool terminal_query_background_color (uint8_t *bg_r, uint8_t *bg_g, uint8_t *bg_b)
Detailed Description
Terminal abstraction for WASM/Emscripten via EM_JS bridge to xterm.js.
Definition in file platform/wasm/terminal.c.
Function Documentation
detect_terminal_capabilities()
terminal_capabilities_t detect_terminal_capabilities (void)
Definition at line 146 of file platform/wasm/terminal.c.
{
  terminal_capabilities_t caps = {0};
  caps.color_level = TERM_COLOR_256; // xterm.js supports 256 colors
  caps.capabilities = 0;
  caps.color_count = 256;
  caps.utf8_support = true; // xterm.js supports UTF-8
  caps.detection_reliable = true;
  caps.render_mode = RENDER_MODE_FOREGROUND; // Default to foreground mode
  platform_strlcpy(caps.term_type, "xterm-256color", sizeof(caps.term_type));
  platform_strlcpy(caps.colorterm, "truecolor", sizeof(caps.colorterm));
  caps.wants_background = true;
  caps.palette_type = 0; // Default palette
  caps.desired_fps = 30;
  caps.color_filter = COLOR_FILTER_NONE;
  return caps;
}
References platform_strlcpy().
Referenced by action_show_capabilities_immediate(), log_redetect_terminal_capabilities(), main(), session_display_create(), and threaded_send_terminal_size_with_auto_detect().
EM_JS() [1/3]
EM_JS (int , js_get_terminal_cols , () , { return Module.xterm ? Module.xterm.cols :80;})
EM_JS() [2/3]
EM_JS (int , js_get_terminal_rows , () , { return Module.xterm ? Module.xterm.rows :24;})
EM_JS() [3/3]
EM_JS (void , js_terminal_write , (const char *data, int len) , { if(Module.xterm) { Module.xterm.write(UTF8ToString(data, len));} })
get_terminal_size()
asciichat_error_t get_terminal_size (unsigned short int * width, unsigned short int * height)
Definition at line 80 of file platform/wasm/terminal.c.
{
  if (!width || !height) {
    return ERROR_INVALID_PARAM;
  }
  int cols, rows;
  if (platform_get_terminal_size(&cols, &rows) != 0) {
    return ERROR_PLATFORM_INIT;
  }
  *width = (unsigned short int)cols;
  *height = (unsigned short int)rows;
  return ASCIICHAT_OK;
}
References platform_get_terminal_size().
Referenced by session_render_loop(), update_dimensions_for_full_height(), and update_dimensions_to_terminal_size().
platform_get_cursor_position()
int platform_get_cursor_position (int * row, int * col)
Definition at line 67 of file platform/wasm/terminal.c.
{
  (void)row;
  (void)col;
  return -1; // Not supported in WASM
}
platform_get_terminal_size()
int platform_get_terminal_size (int * cols, int * rows)
Definition at line 33 of file platform/wasm/terminal.c.
{
  if (!cols || !rows) {
    return -1;
  }
  *cols = js_get_terminal_cols();
  *rows = js_get_terminal_rows();
  return 0;
}
Referenced by get_terminal_size().
platform_is_terminal()
bool platform_is_terminal (int fd)
Definition at line 62 of file platform/wasm/terminal.c.
{
  (void)fd;
  return true; // Always true for WASM terminal
}
platform_read_keyboard()
int platform_read_keyboard (char * buffer, size_t len)
Definition at line 56 of file platform/wasm/terminal.c.
{
  (void)buffer;
  (void)len;
  return -1; // Not supported: use JavaScript event listeners
}
platform_set_cursor_position()
int platform_set_cursor_position (int row, int col)
Definition at line 73 of file platform/wasm/terminal.c.
{
  (void)row;
  (void)col;
  return -1; // Not supported in WASM
}
platform_set_terminal_raw_mode()
int platform_set_terminal_raw_mode (bool enable)
Definition at line 51 of file platform/wasm/terminal.c.
{
  (void)enable;
  return 0; // No-op: xterm.js handles this
}
platform_write_terminal()
int platform_write_terminal (const char * data, size_t len)
Definition at line 45 of file platform/wasm/terminal.c.
{
  js_terminal_write(data, (int)len);
  return (int)len;
}
terminal_can_prompt_user()
bool terminal_can_prompt_user (void)
Definition at line 130 of file platform/wasm/terminal.c.
{
  return false; // Cannot prompt in WASM
}
terminal_flush()
asciichat_error_t terminal_flush (int fd)
Definition at line 140 of file platform/wasm/terminal.c.
{
  (void)fd;
  return ASCIICHAT_OK; // No-op - xterm.js handles flushing
}
Referenced by ascii_write(), config_create_default(), keyboard_help_render(), session_display_render_fps_overlay(), session_display_reset(), session_display_write_ascii(), session_display_write_raw(), and splash_wait_for_animation().
terminal_has_dark_background()
bool terminal_has_dark_background (void)
Definition at line 135 of file platform/wasm/terminal.c.
{
  return true; // Default to dark background for xterm.js
}
Referenced by detect_terminal_background().
terminal_is_interactive()
bool terminal_is_interactive (void)
Definition at line 122 of file platform/wasm/terminal.c.
{
  return false; // WASM mirror mode is not interactive
}
terminal_is_piped_output()
bool terminal_is_piped_output (void)
Definition at line 99 of file platform/wasm/terminal.c.
{
  return false; // WASM mirror mode is not piped
}
terminal_is_stderr_tty()
bool terminal_is_stderr_tty (void)
Definition at line 118 of file platform/wasm/terminal.c.
{
  return true; // xterm.js output is a TTY
}
terminal_is_stdin_tty()
bool terminal_is_stdin_tty (void)
Definition at line 110 of file platform/wasm/terminal.c.
{
  return false; // No stdin in WASM
}
terminal_is_stdout_tty()
bool terminal_is_stdout_tty (void)
Definition at line 114 of file platform/wasm/terminal.c.
{
  return true; // xterm.js output is a TTY
}
terminal_query_background_color()
bool terminal_query_background_color (uint8_t * bg_r, uint8_t * bg_g, uint8_t * bg_b)
Definition at line 164 of file platform/wasm/terminal.c.
{
  // Return dark background (black) for xterm.js
  if (bg_r)
    *bg_r = 0;
  if (bg_g)
    *bg_g = 0;
  if (bg_b)
    *bg_b = 0;
  return true;
}
terminal_should_color_output()
bool terminal_should_color_output (int fd)
Definition at line 104 of file platform/wasm/terminal.c.
{
  (void)fd;
  return true; // WASM mirror mode supports color
}
terminal_should_force_stderr()
bool terminal_should_force_stderr (void)
Definition at line 126 of file platform/wasm/terminal.c.
{
  return false; // Don't force stderr in WASM
}
terminal_supports_utf8()
bool terminal_supports_utf8 (void)
Definition at line 94 of file platform/wasm/terminal.c.
{
  return true; // xterm.js supports UTF-8
}
Referenced by detect_client_utf8_support(), and options_init().