ascii-chat: terminal.c File Reference
terminal.c File Reference
Cross-platform unified color detection and terminal capabilities.
Functions
bool terminal_should_color_output (int fd)
Determine if color output should be used.
terminal_color_mode_t terminal_get_effective_color_mode (void)
Get current color mode considering all overrides.
bool terminal_is_stdin_tty (void)
bool terminal_is_stdout_tty (void)
bool terminal_is_stderr_tty (void)
bool terminal_is_interactive (void)
unsigned short int terminal_get_effective_width (void)
Get effective terminal width with fallback priority.
unsigned short int terminal_get_effective_height (void)
Get effective terminal height with fallback priority.
bool terminal_is_piped_output (void)
bool terminal_should_force_stderr (void)
bool terminal_can_prompt_user (void)
int terminal_choose_log_fd (log_level_t level)
void terminal_get_default_foreground_color (int theme, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b)
Get theme-aware default foreground color for the renderer.
void terminal_get_default_background_color (int theme, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b)
Get theme-aware default background color for the renderer.
Detailed Description
Cross-platform unified color detection and terminal capabilities.
Definition in file platform/terminal.c.
Function Documentation
terminal_can_prompt_user()
bool terminal_can_prompt_user (void)
Definition at line 219 of file platform/terminal.c.
{
  // Must be fully interactive (stdin and stdout are TTYs)
  if (!terminal_is_interactive()) {
    return false;
  }
  // Must not be in snapshot mode (non-interactive capture)
  if (GET_OPTION(snapshot_mode)) {
    return false;
  }
  // Must not have automated prompt responses configured
  const char *auto_response = SAFE_GETENV("ASCII_CHAT_QUESTION_PROMPT_RESPONSE");
  if (auto_response && *auto_response != '\0') {
    return false; // Automated responses configured, not interactive
  }
  // All checks passed, interactive prompts are appropriate
  return true;
}
References terminal_is_interactive().
Referenced by prompt_unknown_host(), and server_main().
terminal_choose_log_fd()
int terminal_choose_log_fd (log_level_t level)
Definition at line 240 of file platform/terminal.c.
{
  // When force_stderr is enabled (client mode), send ALL logs to stderr
  // When terminal is NOT interactive (piped/redirected), send ALL logs to stderr
  // to keep stdout clean for piped data (JSON, frames, etc.)
  if (log_get_force_stderr() || !terminal_is_interactive()) {
    return STDERR_FILENO;
  }
  // In interactive mode, route based on level:
  // WARN and above (ERROR, FATAL) go to stderr
  // Others (DEV, DEBUG, INFO) go to stdout
  if (level >= LOG_WARN) {
    return STDERR_FILENO;
  }
  return STDOUT_FILENO;
}
References log_get_force_stderr(), and terminal_is_interactive().
Referenced by log_console_impl(), log_msg(), and log_plain_msg().
terminal_get_default_background_color()
void terminal_get_default_background_color (int theme, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b)
Get theme-aware default background color for the renderer.
Parameters
theme Terminal theme (dark or light)
out_r Pointer to store red component (0-255)
out_g Pointer to store green component (0-255)
out_b Pointer to store blue component (0-255)
Returns appropriate default background color based on terminal theme. Light theme uses white background, dark theme uses black background.
Definition at line 294 of file platform/terminal.c.
{
  if (theme == 1) { // TERM_RENDERER_THEME_LIGHT
    *out_r = TERMINAL_COLOR_THEME_LIGHT_BG_R;
    *out_g = TERMINAL_COLOR_THEME_LIGHT_BG_G;
    *out_b = TERMINAL_COLOR_THEME_LIGHT_BG_B;
  } else { // TERM_RENDERER_THEME_DARK or TERM_RENDERER_THEME_AUTO
    *out_r = TERMINAL_COLOR_THEME_DARK_BG_R;
    *out_g = TERMINAL_COLOR_THEME_DARK_BG_G;
    *out_b = TERMINAL_COLOR_THEME_DARK_BG_B;
  }
}
terminal_get_default_foreground_color()
void terminal_get_default_foreground_color (int theme, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b)
Get theme-aware default foreground color for the renderer.
Parameters
theme Terminal theme (dark or light)
out_r Pointer to store red component (0-255)
out_g Pointer to store green component (0-255)
out_b Pointer to store blue component (0-255)
Returns appropriate default text color based on terminal theme. Both Linux and macOS renderers use this for consistent color selection.
Definition at line 272 of file platform/terminal.c.
{
  if (theme == 1) { // TERM_RENDERER_THEME_LIGHT
    *out_r = TERMINAL_COLOR_THEME_LIGHT_FG_R;
    *out_g = TERMINAL_COLOR_THEME_LIGHT_FG_G;
    *out_b = TERMINAL_COLOR_THEME_LIGHT_FG_B;
  } else { // TERM_RENDERER_THEME_DARK or TERM_RENDERER_THEME_AUTO
    *out_r = TERMINAL_COLOR_THEME_DARK_FG_R;
    *out_g = TERMINAL_COLOR_THEME_DARK_FG_G;
    *out_b = TERMINAL_COLOR_THEME_DARK_FG_B;
  }
}
terminal_get_effective_color_mode()
terminal_color_mode_t terminal_get_effective_color_mode (void)
Get current color mode considering all overrides.
Determines effective color mode by checking:
–color flag (force enable)
–color-mode option (none/16/256/truecolor)
Terminal capability detection
Returns
Effective terminal_color_mode_t to use
Definition at line 112 of file platform/terminal.c.
{
  // If colors are disabled entirely by terminal_should_color_output(), return NONE
  if (!terminal_should_color_output(STDOUT_FILENO)) {
    return TERM_COLOR_NONE;
  }
  // If --color-mode is set to specific value, use it
  terminal_color_mode_t color_mode = GET_OPTION(color_mode);
  if (color_mode != TERM_COLOR_AUTO) {
    return color_mode;
  }
  // Otherwise auto-detect from terminal capabilities
  // For now, return the detected color mode from terminal capabilities
  // This will be used by apply_color_mode_override() if needed
  return TERM_COLOR_AUTO; // Let the calling code handle auto-detection
}
References terminal_should_color_output().
terminal_get_effective_height()
unsigned short int terminal_get_effective_height (void)
Get effective terminal height with fallback priority.
Returns height in priority order:
Option height if set to non-zero value
Detected terminal height
OPT_HEIGHT_DEFAULT fallback
Definition at line 184 of file platform/terminal.c.
{
  int height = GET_OPTION(height);
  // If height option is explicitly set to non-zero, use it
  if (height > 0) {
    return (unsigned short int)height;
  }
  // Try to detect actual terminal height
  terminal_size_t size;
  if (terminal_get_size(&size) == ASCIICHAT_OK && size.rows > 0) {
    return (unsigned short int)size.rows;
  }
  // Fallback to default
  return OPT_HEIGHT_DEFAULT;
}
References terminal_get_size().
Referenced by keyboard_help_render(), mirror_convert_frame(), protocol_start_connection(), server_connection_establish(), session_display_convert_to_ascii(), session_display_create(), session_render_loop(), session_settings_init(), and splash_intro_start().
terminal_get_effective_width()
unsigned short int terminal_get_effective_width (void)
Get effective terminal width with fallback priority.
Returns width in priority order:
Option width if set to non-zero value
Detected terminal width
OPT_WIDTH_DEFAULT fallback
Definition at line 158 of file platform/terminal.c.
{
  int width = GET_OPTION(width);
  // If width option is explicitly set to non-zero, use it
  if (width > 0) {
    return (unsigned short int)width;
  }
  // Try to detect actual terminal width
  terminal_size_t size;
  if (terminal_get_size(&size) == ASCIICHAT_OK && size.cols > 0) {
    return (unsigned short int)size.cols;
  }
  // Fallback to default
  return OPT_WIDTH_DEFAULT;
}
References terminal_get_size().
Referenced by keyboard_help_render(), mirror_convert_frame(), protocol_start_connection(), server_connection_establish(), session_display_convert_to_ascii(), session_display_create(), session_display_render_fps_overlay(), session_render_loop(), session_settings_init(), and splash_intro_start().
terminal_is_interactive()
bool terminal_is_interactive (void)
Definition at line 146 of file platform/terminal.c.
{
  return terminal_is_stdin_tty() && terminal_is_stdout_tty();
}
References terminal_is_stdin_tty(), and terminal_is_stdout_tty().
Referenced by main(), options_init(), server_main(), session_display_write_ascii(), session_render_loop(), terminal_can_prompt_user(), terminal_choose_log_fd(), threaded_send_terminal_size_with_auto_detect(), ui_status_display(), and ui_status_display_interactive().
terminal_is_piped_output()
bool terminal_is_piped_output (void)
Definition at line 202 of file platform/terminal.c.
{
  return !terminal_is_stdout_tty();
}
References terminal_is_stdout_tty().
Referenced by asciichat_shared_init(), log_init(), and terminal_should_force_stderr().
terminal_is_stderr_tty()
bool terminal_is_stderr_tty (void)
Definition at line 142 of file platform/terminal.c.
{
  return platform_isatty(STDERR_FILENO) != 0;
}
References platform_isatty().
terminal_is_stdin_tty()
bool terminal_is_stdin_tty (void)
Definition at line 134 of file platform/terminal.c.
{
  return platform_isatty(STDIN_FILENO) != 0;
}
References platform_isatty().
Referenced by display_init(), session_client_like_run(), session_display_create(), session_render_loop(), terminal_is_interactive(), and threaded_send_terminal_size_with_auto_detect().
terminal_is_stdout_tty()
bool terminal_is_stdout_tty (void)
Definition at line 138 of file platform/terminal.c.
{
  return platform_isatty(STDOUT_FILENO) != 0;
}
References platform_isatty().
Referenced by session_client_like_run(), session_display_create(), session_render_loop(), terminal_is_interactive(), terminal_is_piped_output(), and threaded_send_terminal_size_with_auto_detect().
terminal_should_color_output()
bool terminal_should_color_output (int fd)
Determine if color output should be used.
Priority order:
If –color flag is set → ALWAYS use colors (force override)
If CLAUDECODE env var is set → NEVER use colors (LLM automation)
If output is not a TTY (piping) → NO colors
If –color-mode=none → NO colors (user choice)
Otherwise → Use colors
Parameters
fd File descriptor to check (STDOUT_FILENO or STDERR_FILENO)
Returns
true if colors should be used, false otherwise
Definition at line 31 of file platform/terminal.c.
{
  // Check color_mode setting - if explicitly set to NONE, disable colors
  int color_mode = GET_OPTION(color_mode);
  if (color_mode == COLOR_MODE_NONE) {
    return false; // Color mode explicitly disabled
  }
  // Get current color setting (auto/true/false)
  int color_setting = GET_OPTION(color);
  // Priority 1: --color=true - Force colors ON (overrides everything)
  if (color_setting == COLOR_SETTING_TRUE) {
    return true; // ALWAYS colorize
  }
  // Priority 2: --color=false - Force colors OFF (overrides everything)
  if (color_setting == COLOR_SETTING_FALSE) {
    return false; // NEVER colorize
  }
  // Priority 3: --color=auto (default) - Smart detection
  // Special case: Show colors for --help and --version even if not a TTY
  // Check for help/version in global argv (set by main.c early)
  if (g_argc > 1 && g_argv) {
    for (int i = 1; i < g_argc; i++) {
      if (strcmp(g_argv[i], "--help") == 0 || strcmp(g_argv[i], "-h") == 0 || strcmp(g_argv[i], "--version") == 0 ||
          strcmp(g_argv[i], "-v") == 0 || strcmp(g_argv[i], "--show-capabilities") == 0) {
        // For help/version/show-capabilities, use colors only if output is a TTY
        // (respect piping convention: no colors unless --color=true)
        int is_tty = platform_isatty(fd);
        if (!is_tty) {
          // Piping detected - fall through to check environment overrides
          break;
        }
        // It's a TTY - show colors for help. Check environment overrides.
        if (SAFE_GETENV("ASCII_CHAT_COLOR")) {
          return true; // ASCII_CHAT_COLOR env var forces colors
        }
        // CLAUDECODE environment variable (LLM automation) - disable colors
        if (SAFE_GETENV("CLAUDECODE")) {
          return false; // NO colors in Claude Code environment
        }
        // For help output to TTY, show colors by default
        return true;
      }
    }
  }
  // Check environment variable overrides
  if (SAFE_GETENV("ASCII_CHAT_COLOR")) {
    return true; // ASCII_CHAT_COLOR env var forces colors
  }
  // CLAUDECODE environment variable (LLM automation) - disable colors
  if (SAFE_GETENV("CLAUDECODE")) {
    return false; // NO colors in Claude Code environment
  }
  // Check if output is a TTY (pipe detection)
  int is_tty = platform_isatty(fd);
  if (!is_tty) {
    return false; // NO colors when piping/redirecting
  }
  // Default: Use colors (we have TTY and no environment overrides)
  return true;
}
References g_argc, g_argv, and platform_isatty().
Referenced by action_show_capabilities_immediate(), action_show_version(), colored_string(), colorize_log_message(), log_plain_msg(), and terminal_get_effective_color_mode().
terminal_should_force_stderr()
bool terminal_should_force_stderr (void)
Definition at line 206 of file platform/terminal.c.
{
  // If stdout is piped/redirected, force logs to stderr to avoid corruption
  if (terminal_is_piped_output()) {
    // Unless in TESTING environment where test framework may capture stdout
    const char *testing = SAFE_GETENV("TESTING");
    if (testing && strcmp(testing, "1") == 0) {
      return false; // Allow stdout in test environments
    }
    return true; // Force stderr when piped
  }
  return false; // stdout is TTY, no need to force stderr
}
References terminal_is_piped_output().
Referenced by main(), session_client_like_run(), and session_display_create().