ascii-chat: mutex.c File Reference
mutex.c File Reference
Platform-agnostic mutex hooks and utilities.
Functions
void mutex_on_lock (mutex_t *mutex)
Hook called when a mutex is successfully locked.
void mutex_on_unlock (mutex_t *mutex)
Hook called when a mutex is unlocked.
void mutex_on_trylock (mutex_t *mutex, bool success)
Hook called when a mutex trylock is attempted.
int mutex_format_state (const mutex_t *mutex, char *buffer, size_t size)
Format mutex timing and state info into buffer.
void mutex_log_state (const mutex_t *mutex, const char *file, int line, const char *func)
Log the state of a mutex.
Detailed Description
Platform-agnostic mutex hooks and utilities.
This file provides hook functions that can be called from platform-specific mutex implementations to record events and debug information. All hooks are debug-only and disabled in release builds.
Definition in file platform/mutex.c.
Function Documentation
mutex_format_state()
int mutex_format_state (const mutex_t * mutex, char * buffer, size_t size)
Format mutex timing and state info into buffer.
Parameters
mutex Pointer to the mutex
buffer Output buffer
size Buffer size
Returns
Number of bytes written
Formats timing (lock/unlock), held-by info, and operation counts. Called by mutex_log_state() and –sync-state display code.
Definition at line 86 of file platform/mutex.c.
{
  if (!mutex || !buffer || size == 0) return 0;
  int offset = 0;
  uint64_t now_ns = time_get_ns();
  // Format timing information
  char lock_str[64] = "";
  char unlock_str[64] = "";
  char held_str[64] = "";
  char count_str[256] = "";
  if (mutex->last_lock_time_ns > 0 && mutex->last_lock_time_ns <= now_ns) {
    char elapsed_str[64];
    time_pretty(now_ns - mutex->last_lock_time_ns, -1, elapsed_str, sizeof(elapsed_str));
    snprintf(lock_str, sizeof(lock_str), "lock=%s", elapsed_str);
  }
  if (mutex->last_unlock_time_ns > 0 && mutex->last_unlock_time_ns <= now_ns) {
    char elapsed_str[64];
    time_pretty(now_ns - mutex->last_unlock_time_ns, -1, elapsed_str, sizeof(elapsed_str));
    snprintf(unlock_str, sizeof(unlock_str), "unlock=%s", elapsed_str);
  }
  if (mutex->currently_held_by_key != 0) {
    snprintf(held_str, sizeof(held_str), "[LOCKED_BY=thread.%lu]", (unsigned long)mutex->currently_held_by_key);
  }
  if (mutex->lock_count > 0 || mutex->unlock_count > 0 || mutex->trylock_count > 0) {
    snprintf(count_str, sizeof(count_str), "[ops: lock=%lu unlock=%lu trylock=%lu/%lu]",
             mutex->lock_count, mutex->unlock_count, mutex->trylock_success_count, mutex->trylock_count);
  }
  offset += snprintf(buffer + offset, size - offset, "%s %s %s %s", lock_str, unlock_str, held_str, count_str);
  return offset;
}
References mutex, time_get_ns(), and time_pretty().
Referenced by mutex_log_state().
mutex_log_state()
void mutex_log_state (const mutex_t * mutex, const char * file, int line, const char * func)
Log the state of a mutex.
Parameters
mutex Pointer to the mutex
file Source file of the caller
line Source line of the caller
func Source function of the caller
Formats and logs detailed state information about the mutex.
Definition at line 134 of file platform/mutex.c.
{
  if (!mutex) return;
  char buf[512];
  mutex_format_state(mutex, buf, sizeof(buf));
  log_msg(LOG_DEBUG, file, line, func, "mutex/state %p: %s", (const void *)mutex, buf);
}
References log_msg(), mutex, and mutex_format_state().
mutex_on_lock()
void mutex_on_lock (mutex_t * mutex)
Hook called when a mutex is successfully locked.
Parameters
mutex Pointer to the mutex that was locked
Called by platform-specific mutex_lock_impl() after the lock is acquired. Records timing, held-by thread, and increments lock count.
Definition at line 29 of file platform/mutex.c.
{
  if (!mutex) return;
  mutex->last_lock_time_ns = time_get_ns();
  asciichat_thread_t current_thread = (asciichat_thread_t)asciichat_thread_current_id();
  mutex->currently_held_by_key = asciichat_thread_to_key(current_thread);
  mutex->lock_count++;
}
References asciichat_thread_current_id(), mutex, and time_get_ns().
mutex_on_trylock()
void mutex_on_trylock (mutex_t * mutex, bool success)
Hook called when a mutex trylock is attempted.
Parameters
mutex Pointer to the mutex
success Whether the trylock succeeded
Called by platform-specific mutex_trylock_impl() after the attempt. Records timing and success/failure statistics.
Definition at line 63 of file platform/mutex.c.
{
  if (!mutex) return;
  mutex->trylock_count++;
  if (success) {
    mutex->trylock_success_count++;
    mutex->last_lock_time_ns = time_get_ns();
    asciichat_thread_t current_thread = (asciichat_thread_t)asciichat_thread_current_id();
    mutex->currently_held_by_key = asciichat_thread_to_key(current_thread);
  }
}
References asciichat_thread_current_id(), mutex, and time_get_ns().
mutex_on_unlock()
void mutex_on_unlock (mutex_t * mutex)
Hook called when a mutex is unlocked.
Parameters
mutex Pointer to the mutex that was unlocked
Called by platform-specific mutex_unlock_impl() before releasing the lock. Records timing and increments unlock count.
Definition at line 46 of file platform/mutex.c.
{
  if (!mutex) return;
  mutex->last_unlock_time_ns = time_get_ns();
  mutex->currently_held_by_key = 0;
  mutex->unlock_count++;
}
References mutex, and time_get_ns().