ascii-chat: string.c File Reference
string.c File Reference
String utility functions for WASM/Emscripten.
Functions
size_t platform_strlcpy (char *dst, const char *src, size_t size)
size_t platform_strlcat (char *dst, const char *src, size_t size)
int platform_strcasecmp (const char *s1, const char *s2)
int platform_asprintf (char **strp, const char *fmt,...)
char * platform_strdup (const char *s)
asciichat_error_t platform_memcpy (void *dest, size_t dest_size, const void *src, size_t count)
asciichat_error_t platform_memset (void *dest, size_t dest_size, int ch, size_t count)
int platform_vsnprintf (char *str, size_t size, const char *format, va_list ap)
int platform_strncasecmp (const char *s1, const char *s2, size_t n)
Detailed Description
String utility functions for WASM/Emscripten.
Definition in file platform/wasm/string.c.
Function Documentation
platform_asprintf()
int platform_asprintf (char ** strp, const char * fmt, ...)
Definition at line 48 of file platform/wasm/string.c.
{
  // Use standard asprintf (available in WASM/Emscripten)
  va_list args;
  va_start(args, fmt);
  int ret = vasprintf(strp, fmt, args);
  va_end(args);
  return ret;
}
References args.
platform_memcpy()
asciichat_error_t platform_memcpy (void * dest, size_t dest_size, const void * src, size_t count)
Definition at line 62 of file platform/wasm/string.c.
{
  if (!dest || !src) {
    return ERROR_INVALID_PARAM;
  }
  if (count > dest_size) {
    return ERROR_INVALID_PARAM; // Buffer overflow protection
  }
  memcpy(dest, src, count);
  return ASCIICHAT_OK;
}
platform_memset()
asciichat_error_t platform_memset (void * dest, size_t dest_size, int ch, size_t count)
Definition at line 73 of file platform/wasm/string.c.
{
  if (!dest) {
    return ERROR_INVALID_PARAM;
  }
  if (count > dest_size) {
    return ERROR_INVALID_PARAM; // Buffer overflow protection
  }
  memset(dest, ch, count);
  return ASCIICHAT_OK;
}
platform_strcasecmp()
int platform_strcasecmp (const char * s1, const char * s2)
Definition at line 43 of file platform/wasm/string.c.
{
  // Use standard strcasecmp (available in WASM)
  return strcasecmp(s1, s2);
}
Referenced by color_filter_from_cli_name(), detect_terminal_background(), options_init(), validate_opt_log_level(), and validate_opt_reconnect().
platform_strdup()
char * platform_strdup (const char * s)
Definition at line 57 of file platform/wasm/string.c.
{
  // Use standard strdup (available in WASM)
  return strdup(s);
}
Referenced by config_create_default(), config_load_and_apply(), expand_path(), media_source_create(), options_builder_add_example(), options_config_validate(), parse_audio_source(), parse_client_address(), parse_color_filter(), parse_color_mode(), parse_color_setting(), parse_log_file(), parse_log_level(), parse_mirror_media(), parse_palette_chars(), parse_palette_type(), parse_port_option(), parse_render_mode(), parse_render_theme(), parse_server_bind_address(), parse_ssh_private_key(), parse_timestamp(), parse_utf8_setting(), parse_volume(), platform_is_binary_in_path(), remove_known_host(), rgb_to_16color_halfblocks_scalar(), rgb_to_256color_halfblocks_scalar(), rgb_to_halfblocks_scalar(), rgb_to_truecolor_halfblocks_scalar(), symbol_cache_insert(), symbol_cache_lookup(), symbol_cache_resolve_batch(), and validate_port_callback().
platform_strlcat()
size_t platform_strlcat (char * dst, const char * src, size_t size)
Definition at line 27 of file platform/wasm/string.c.
{
  size_t dst_len = strlen(dst);
  size_t src_len = strlen(src);
  if (dst_len >= size) {
    return dst_len + src_len;
  }
  size_t remaining = size - dst_len;
  size_t copy_len = (src_len >= remaining) ? remaining - 1 : src_len;
  memcpy(dst + dst_len, src, copy_len);
  dst[dst_len + copy_len] = '\0';
  return dst_len + src_len;
}
platform_strlcpy()
size_t platform_strlcpy (char * dst, const char * src, size_t size)
Definition at line 13 of file platform/wasm/string.c.
{
  size_t src_len = strlen(src);
  if (size == 0) {
    return src_len;
  }
  size_t copy_len = (src_len >= size) ? size - 1 : src_len;
  memcpy(dst, src, copy_len);
  dst[copy_len] = '\0';
  return src_len;
}
Referenced by detect_terminal_capabilities(), platform_get_cwd(), and platform_get_temp_dir().
platform_strncasecmp()
int platform_strncasecmp (const char * s1, const char * s2, size_t n)
Definition at line 88 of file platform/wasm/string.c.
{
  return strncasecmp(s1, s2, n);
}
platform_vsnprintf()
int platform_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 84 of file platform/wasm/string.c.
{
  return vsnprintf(str, size, format, ap);
}
Referenced by safe_snprintf(), and safe_vsnprintf().