ascii-chat: positional.c File Reference
positional.c File Reference
POSITIONAL ARGUMENTS section generator for man pages.
Functions
char * manpage_content_generate_positional (const options_config_t *config)
void manpage_content_free_positional (char *content)
Detailed Description
POSITIONAL ARGUMENTS section generator for man pages.
Definition in file positional.c.
Function Documentation
manpage_content_free_positional()
void manpage_content_free_positional (char * content)
Definition at line 64 of file positional.c.
{
  if (content) {
    SAFE_FREE(content);
  }
}
Referenced by options_config_generate_manpage_merged(), and options_config_generate_manpage_template().
manpage_content_generate_positional()
char * manpage_content_generate_positional (const options_config_t * config)
Definition at line 15 of file positional.c.
{
  if (!config || config->num_positional_args == 0) {
    char *buffer = SAFE_MALLOC(1, char *);
    buffer[0] = '\0';
    return buffer;
  }
  // Allocate growing buffer for positional section
  size_t buffer_capacity = 4096;
  char *buffer = SAFE_MALLOC(buffer_capacity, char *);
  size_t offset = 0;
  for (size_t i = 0; i < config->num_positional_args; i++) {
    const positional_arg_descriptor_t *pos_arg = &config->positional_args[i];
    // Ensure buffer is large enough
    if (offset + 512 >= buffer_capacity) {
      buffer_capacity *= 2;
      buffer = SAFE_REALLOC(buffer, buffer_capacity, char *);
    }
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".TP\n");
    offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".B %s\n", pos_arg->name);
    if (pos_arg->help_text) {
      offset +=
          safe_snprintf(buffer + offset, buffer_capacity - offset, "%s\n", escape_groff_special(pos_arg->help_text));
    }
    // Add examples if present
    if (pos_arg->num_examples > 0) {
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".RS\n");
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".B Examples:\n");
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".RS\n");
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".nf\n");
      for (size_t j = 0; j < pos_arg->num_examples; j++) {
        offset += safe_snprintf(buffer + offset, buffer_capacity - offset, "%s\n",
                                escape_groff_special(pos_arg->examples[j]));
      }
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".fi\n");
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".RE\n");
      offset += safe_snprintf(buffer + offset, buffer_capacity - offset, ".RE\n");
    }
  }
  log_debug("Generated POSITIONAL ARGUMENTS section (%zu bytes)", offset);
  return buffer;
}
References escape_groff_special(), and safe_snprintf().
Referenced by options_config_generate_manpage_merged(), and options_config_generate_manpage_template().