ascii-chat: rate_limit.c File Reference
rate_limit.c File Reference
🚦 Rate limiting implementation with backend abstraction
Data Structures
struct rate_limiter_s
Rate limiter structure.
Functions
rate_limiter_t * rate_limiter_create_memory (void)
rate_limiter_t * rate_limiter_create_sqlite (const char *db_path)
void rate_limiter_set_sqlite_db (rate_limiter_t *limiter, void *db)
void rate_limiter_destroy (rate_limiter_t *limiter)
asciichat_error_t rate_limiter_check (rate_limiter_t *limiter, const char *ip_address, rate_event_type_t event_type, const rate_limit_config_t *config, bool *allowed)
asciichat_error_t rate_limiter_record (rate_limiter_t *limiter, const char *ip_address, rate_event_type_t event_type)
asciichat_error_t rate_limiter_prune (rate_limiter_t *limiter, uint32_t max_age_secs)
const char * rate_limiter_event_type_string (rate_event_type_t event_type)
Get event type string for logging.
Variables
const rate_limit_config_t DEFAULT_RATE_LIMITS [RATE_EVENT_MAX]
Detailed Description
🚦 Rate limiting implementation with backend abstraction
Definition in file rate_limit.c.
Function Documentation
rate_limiter_check()
asciichat_error_t rate_limiter_check (rate_limiter_t * limiter, const char * ip_address, rate_event_type_t event_type, const rate_limit_config_t * config, bool * allowed)
Definition at line 128 of file rate_limit.c.
{
  if (!limiter || !limiter->ops || !limiter->ops->check) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid rate limiter");
  }
  if (!ip_address || !allowed) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "ip_address or allowed is NULL");
  }
  if (event_type >= RATE_EVENT_MAX) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid event_type: %d", event_type);
  }
  return limiter->ops->check(limiter->backend_data, ip_address, event_type, config, allowed);
}
Referenced by check_and_record_rate_limit().
rate_limiter_create_memory()
rate_limiter_t * rate_limiter_create_memory (void)
Definition at line 73 of file rate_limit.c.
{
  rate_limiter_t *limiter = malloc(sizeof(rate_limiter_t));
  if (!limiter) {
    log_error("Failed to allocate rate limiter");
    return NULL;
  }
  limiter->backend_data = memory_backend_create();
  if (!limiter->backend_data) {
    free(limiter);
    return NULL;
  }
  limiter->ops = &memory_backend_ops;
  return limiter;
}
References memory_backend_create(), and memory_backend_ops.
Referenced by server_main().
rate_limiter_create_sqlite()
rate_limiter_t * rate_limiter_create_sqlite (const char * db_path)
Definition at line 90 of file rate_limit.c.
{
  rate_limiter_t *limiter = malloc(sizeof(rate_limiter_t));
  if (!limiter) {
    log_error("Failed to allocate rate limiter");
    return NULL;
  }
  limiter->backend_data = sqlite_backend_create(db_path);
  if (!limiter->backend_data) {
    free(limiter);
    return NULL;
  }
  limiter->ops = &sqlite_backend_ops;
  return limiter;
}
References sqlite_backend_create(), and sqlite_backend_ops.
Referenced by acds_server_init().
rate_limiter_destroy()
void rate_limiter_destroy (rate_limiter_t * limiter)
Definition at line 116 of file rate_limit.c.
{
  if (!limiter) {
    return;
  }
  if (limiter->ops && limiter->ops->destroy) {
    limiter->ops->destroy(limiter->backend_data);
  }
  free(limiter);
}
Referenced by acds_server_init(), acds_server_shutdown(), and server_main().
rate_limiter_event_type_string()
const char * rate_limiter_event_type_string (rate_event_type_t event_type)
Get event type string for logging.
Definition at line 176 of file rate_limit.c.
{
  if (event_type >= RATE_EVENT_MAX) {
    return "unknown";
  }
  return event_type_strings[event_type];
}
rate_limiter_prune()
asciichat_error_t rate_limiter_prune (rate_limiter_t * limiter, uint32_t max_age_secs)
Definition at line 161 of file rate_limit.c.
{
  if (!limiter || !limiter->ops || !limiter->ops->cleanup) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid rate limiter");
  }
  return limiter->ops->cleanup(limiter->backend_data, max_age_secs);
}
rate_limiter_record()
asciichat_error_t rate_limiter_record (rate_limiter_t * limiter, const char * ip_address, rate_event_type_t event_type)
Definition at line 145 of file rate_limit.c.
{
  if (!limiter || !limiter->ops || !limiter->ops->record) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid rate limiter");
  }
  if (!ip_address) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "ip_address is NULL");
  }
  if (event_type >= RATE_EVENT_MAX) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid event_type: %d", event_type);
  }
  return limiter->ops->record(limiter->backend_data, ip_address, event_type);
}
Referenced by check_and_record_rate_limit().
rate_limiter_set_sqlite_db()
void rate_limiter_set_sqlite_db (rate_limiter_t * limiter, void * db)
Definition at line 107 of file rate_limit.c.
{
  if (!limiter || !limiter->backend_data) {
    return;
  }
  // Call the SQLite backend function to set the database handle
  sqlite_backend_set_db(limiter->backend_data, (sqlite3 *)db);
}
References sqlite_backend_set_db().
Referenced by acds_server_init().
Variable Documentation
DEFAULT_RATE_LIMITS
const rate_limit_config_t DEFAULT_RATE_LIMITS[RATE_EVENT_MAX]
Initial value:
                                              = {
    [RATE_EVENT_SESSION_CREATE] = {.max_events = 15, .window_secs = 60},
    [RATE_EVENT_SESSION_LOOKUP] = {.max_events = 45, .window_secs = 60},
    [RATE_EVENT_SESSION_JOIN] = {.max_events = 30, .window_secs = 60},
    [RATE_EVENT_CONNECTION] = {.max_events = 75, .window_secs = 60},
    [RATE_EVENT_IMAGE_FRAME] = {.max_events = 12960, .window_secs = 60},
    [RATE_EVENT_AUDIO] = {.max_events = 15480, .window_secs = 60},
    [RATE_EVENT_PING] = {.max_events = 180, .window_secs = 60},
    [RATE_EVENT_CLIENT_JOIN] = {.max_events = 25, .window_secs = 60},
    [RATE_EVENT_CONTROL] = {.max_events = 150, .window_secs = 60},
}
Definition at line 30 of file rate_limit.c.
{
// ACDS discovery server limits
#ifdef NDEBUG
    // Release mode: production limits (144 FPS video, 172 FPS audio)
    [RATE_EVENT_SESSION_CREATE] = {.max_events = 10, .window_secs = 60}, // 10 creates per minute
    [RATE_EVENT_SESSION_LOOKUP] = {.max_events = 30, .window_secs = 60}, // 30 lookups per minute
    [RATE_EVENT_SESSION_JOIN] = {.max_events = 20, .window_secs = 60},   // 20 joins per minute
    [RATE_EVENT_CONNECTION] = {.max_events = 50, .window_secs = 60},     // 50 connections per minute
    [RATE_EVENT_IMAGE_FRAME] = {.max_events = 8640, .window_secs = 60},  // 8640 frames/min = 144 FPS
    [RATE_EVENT_AUDIO] = {.max_events = 10320, .window_secs = 60},       // 10320 packets/min = 172 FPS
    [RATE_EVENT_PING] = {.max_events = 120, .window_secs = 60},          // 120 pings/min = 2 Hz max
    [RATE_EVENT_CLIENT_JOIN] = {.max_events = 10, .window_secs = 60},    // 10 joins per minute
    [RATE_EVENT_CONTROL] = {.max_events = 100, .window_secs = 60},       // 100 control packets/min
#else
    // Debug mode: slightly relaxed limits for development/testing (1.5x production limits)
    [RATE_EVENT_SESSION_CREATE] = {.max_events = 15, .window_secs = 60}, // 15 creates per minute
    [RATE_EVENT_SESSION_LOOKUP] = {.max_events = 45, .window_secs = 60}, // 45 lookups per minute
    [RATE_EVENT_SESSION_JOIN] = {.max_events = 30, .window_secs = 60},   // 30 joins per minute
    [RATE_EVENT_CONNECTION] = {.max_events = 75, .window_secs = 60},     // 75 connections per minute
    [RATE_EVENT_IMAGE_FRAME] = {.max_events = 12960, .window_secs = 60}, // 12960 frames/min = 216 FPS
    [RATE_EVENT_AUDIO] = {.max_events = 15480, .window_secs = 60},       // 15480 packets/min = 258 FPS
    [RATE_EVENT_PING] = {.max_events = 180, .window_secs = 60},          // 180 pings/min = 3 Hz
    [RATE_EVENT_CLIENT_JOIN] = {.max_events = 25, .window_secs = 60},    // 25 joins per minute (for testing reconnects)
    [RATE_EVENT_CONTROL] = {.max_events = 150, .window_secs = 60},       // 150 control packets/min
#endif
};