ascii-chat: regex.c File Reference
regex.c File Reference
PCRE2-based regex patterns for cryptographic parsing.
Functions
bool crypto_regex_match_known_hosts (const char *line, char **ip_port_out, char **key_type_out, char **hex_key_out, char **comment_out)
bool crypto_regex_match_public_key (const char *line, char **base64_key_out, char **comment_out)
bool crypto_regex_extract_pem_base64 (const char *file_content, char **base64_data_out)
bool crypto_regex_extract_gpg_keygrip (const char *line, char **keygrip_out)
Detailed Description
PCRE2-based regex patterns for cryptographic parsing.
Implements regex-based parsing for SSH formats using PCRE2 with JIT compilation. Uses centralized PCRE2 singleton module for thread-safe lazy initialization.
Definition in file regex.c.
Function Documentation
crypto_regex_extract_gpg_keygrip()
bool crypto_regex_extract_gpg_keygrip (const char * line, char ** keygrip_out)
Definition at line 267 of file regex.c.
{
  if (!line || !keygrip_out) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
    return false;
  }
  pcre2_code *regex = crypto_regex_get_gpg_keygrip();
  if (!regex) {
    /* Regex not available - caller should use fallback manual parsing */
    return false;
  }
  pcre2_match_data *match_data = pcre2_match_data_create_from_pattern(regex, NULL);
  if (!match_data) {
    return false;
  }
  /* Perform JIT match (falls back to interpreted if JIT unavailable) */
  int rc = pcre2_jit_match(regex, (PCRE2_SPTR)line, strlen(line), 0, /* startoffset */
                           0,                                        /* options */
                           match_data, NULL);                        /* mcontext */
  if (rc < 0) {
    pcre2_match_data_free(match_data);
    return false;
  }
  /* Extract keygrip from named group */
  *keygrip_out = asciichat_pcre2_extract_named_group(regex, match_data, "keygrip", line);
  pcre2_match_data_free(match_data);
  /* Verify we got the keygrip */
  if (!*keygrip_out) {
    return false;
  }
  return true;
}
References asciichat_pcre2_extract_named_group().
Referenced by gpg_get_public_key().
crypto_regex_extract_pem_base64()
bool crypto_regex_extract_pem_base64 (const char * file_content, char ** base64_data_out)
Definition at line 227 of file regex.c.
{
  if (!file_content || !base64_data_out) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
    return false;
  }
  pcre2_code *regex = crypto_regex_get_openssh_pem();
  if (!regex) {
    SET_ERRNO(ERROR_INVALID_STATE, "Invalid validator state");
    return false;
  }
  pcre2_match_data *match_data = pcre2_match_data_create_from_pattern(regex, NULL);
  if (!match_data) {
    return false;
  }
  /* Perform JIT match (falls back to interpreted if JIT unavailable) */
  int rc = pcre2_jit_match(regex, (PCRE2_SPTR)file_content, strlen(file_content), 0, /* startoffset */
                           0,                                                        /* options */
                           match_data, NULL);                                        /* mcontext */
  if (rc < 0) {
    pcre2_match_data_free(match_data);
    return false;
  }
  /* Extract base64 data */
  *base64_data_out = asciichat_pcre2_extract_named_group(regex, match_data, "base64_data", file_content);
  pcre2_match_data_free(match_data);
  /* Verify we got the base64 data */
  if (!*base64_data_out) {
    return false;
  }
  return true;
}
References asciichat_pcre2_extract_named_group().
Referenced by parse_ssh_private_key().
crypto_regex_match_known_hosts()
bool crypto_regex_match_known_hosts (const char * line, char ** ip_port_out, char ** key_type_out, char ** hex_key_out, char ** comment_out)
Definition at line 136 of file regex.c.
{
  if (!line || !ip_port_out || !key_type_out || !hex_key_out || !comment_out) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
    return false;
  }
  pcre2_code *regex = crypto_regex_get_known_hosts();
  if (!regex) {
    SET_ERRNO(ERROR_INVALID_STATE, "Invalid validator state");
    return false;
  }
  pcre2_match_data *match_data = pcre2_match_data_create_from_pattern(regex, NULL);
  if (!match_data) {
    return false;
  }
  /* Perform JIT match (falls back to interpreted if JIT unavailable) */
  int rc = pcre2_jit_match(regex, (PCRE2_SPTR)line, strlen(line), 0, /* startoffset */
                           0,                                        /* options */
                           match_data, NULL);                        /* mcontext */
  if (rc < 0) {
    pcre2_match_data_free(match_data);
    return false;
  }
  /* Extract named groups */
  *ip_port_out = asciichat_pcre2_extract_named_group(regex, match_data, "ip_port", line);
  *key_type_out = asciichat_pcre2_extract_named_group(regex, match_data, "key_type", line);
  *hex_key_out = asciichat_pcre2_extract_named_group(regex, match_data, "hex_key", line);
  *comment_out = asciichat_pcre2_extract_named_group(regex, match_data, "comment", line);
  pcre2_match_data_free(match_data);
  /* Verify we got required fields */
  if (!*ip_port_out || !*key_type_out) {
    SAFE_FREE(*ip_port_out);
    SAFE_FREE(*key_type_out);
    SAFE_FREE(*hex_key_out);
    SAFE_FREE(*comment_out);
    return false;
  }
  return true;
}
References asciichat_pcre2_extract_named_group().
Referenced by check_known_host(), and check_known_host_no_identity().
crypto_regex_match_public_key()
bool crypto_regex_match_public_key (const char * line, char ** base64_key_out, char ** comment_out)
Definition at line 184 of file regex.c.
{
  if (!line || !base64_key_out || !comment_out) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
    return false;
  }
  pcre2_code *regex = crypto_regex_get_ssh_public_key();
  if (!regex) {
    SET_ERRNO(ERROR_INVALID_STATE, "Invalid validator state");
    return false;
  }
  pcre2_match_data *match_data = pcre2_match_data_create_from_pattern(regex, NULL);
  if (!match_data) {
    return false;
  }
  /* Perform JIT match (falls back to interpreted if JIT unavailable) */
  int rc = pcre2_jit_match(regex, (PCRE2_SPTR)line, strlen(line), 0, /* startoffset */
                           0,                                        /* options */
                           match_data, NULL);                        /* mcontext */
  if (rc < 0) {
    pcre2_match_data_free(match_data);
    return false;
  }
  /* Extract named groups */
  *base64_key_out = asciichat_pcre2_extract_named_group(regex, match_data, "base64_key", line);
  *comment_out = asciichat_pcre2_extract_named_group(regex, match_data, "comment", line);
  pcre2_match_data_free(match_data);
  /* Verify we got required field */
  if (!*base64_key_out) {
    SAFE_FREE(*base64_key_out);
    SAFE_FREE(*comment_out);
    return false;
  }
  return true;
}
References asciichat_pcre2_extract_named_group().
Referenced by parse_ssh_ed25519_line().