ascii-chat: resources.c File Reference
resources.c File Reference
Man page resource loading and management.
Functions
asciichat_error_t manpage_resources_load (manpage_resources_t *resources)
void manpage_resources_destroy (manpage_resources_t *resources)
bool manpage_resources_is_valid (const manpage_resources_t *resources)
Detailed Description
Man page resource loading and management.
Abstracts loading man page resources from either embedded (production) or filesystem (development) sources. Provides a clean interface that hides the complexity of the underlying embedded_resources API.
Definition in file resources.c.
Function Documentation
manpage_resources_destroy()
void manpage_resources_destroy (manpage_resources_t * resources)
Definition at line 151 of file resources.c.
{
  if (!resources) {
    return;
  }
  // Only free content if it was allocated (i.e., loaded from filesystem in debug builds)
  if (resources->allocated) {
#ifndef NDEBUG
    // In debug builds, template and content were allocated by load_single_resource
    if (resources->template_content) {
      char *template_ptr = (char *)resources->template_content;
      SAFE_FREE(template_ptr);
    }
    if (resources->content_sections) {
      char *content_ptr = (char *)resources->content_sections;
      SAFE_FREE(content_ptr);
    }
#endif
  }
  // Clear the structure
  resources->template_content = NULL;
  resources->template_len = 0;
  resources->content_sections = NULL;
  resources->content_len = 0;
  resources->is_embedded = false;
  resources->allocated = false;
}
Referenced by options_config_generate_manpage_merged().
manpage_resources_is_valid()
bool manpage_resources_is_valid (const manpage_resources_t * resources)
Definition at line 180 of file resources.c.
{
  if (!resources) {
    return false;
  }
  // Resources are valid if template is loaded (content is now optional/merged into template)
  return resources->template_content != NULL && resources->template_len > 0;
}
Referenced by options_config_generate_manpage_merged().
manpage_resources_load()
asciichat_error_t manpage_resources_load (manpage_resources_t * resources)
Definition at line 107 of file resources.c.
{
  if (!resources) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "resources pointer cannot be NULL");
  }
  // Initialize to safe state
  resources->template_content = NULL;
  resources->template_len = 0;
  resources->content_sections = NULL;
  resources->content_len = 0;
  resources->is_embedded = false;
  resources->allocated = false;
  // Load template resource
  asciichat_error_t err = load_single_resource(&resources->template_content, &resources->template_len,
                                               get_manpage_template, "man page template");
  if (err != ASCIICHAT_OK) {
    return err;
  }
  // Content is now merged into template - no separate content file needed
  // Set to NULL so cleanup doesn't try to free a string literal
  resources->content_sections = NULL;
  resources->content_len = 0;
  // Determine if resources came from embedded binary
  // In production (NDEBUG), both would be embedded; in development, both would be files
#ifdef NDEBUG
  resources->is_embedded = true;
#else
  resources->is_embedded = false;
#endif
  // Mark that we may have allocated memory (only in debug builds for filesystem reads)
#ifdef NDEBUG
  resources->allocated = false;
#else
  resources->allocated = true;
#endif
  log_debug("Resources loaded successfully (embedded=%d, allocated=%d)", resources->is_embedded, resources->allocated);
  return ASCIICHAT_OK;
}
References get_manpage_template().
Referenced by options_config_generate_manpage_merged().