ascii-chat: main.h File Reference
main.h File Reference
ascii-chat Server Mode Entry Point Header
Data Structures
struct server_context_t
Server context - encapsulates all server state.
Typedefs
typedef struct server_context_t server_context_t
Server context - encapsulates all server state.
Functions
int server_main (void)
Server mode entry point for unified binary.
Variables
atomic_t g_should_exit
Global application exit flag (shared across all modes).
rate_limiter_t * g_rate_limiter
Global connection rate limiter.
client_manager_t g_client_manager
Global client manager.
rwlock_t g_client_manager_rwlock
Read-write lock protecting client manager.
mixer_t *volatile g_audio_mixer
Global audio mixer.
h265_server_context_t *volatile g_h265_server
Global H.265 codec server context.
bool g_server_encryption_enabled
Server encryption enabled flag.
private_key_t g_server_private_key
Server's private key.
private_key_t g_server_identity_keys [MAX_IDENTITY_KEYS]
Array of server identity keys.
size_t g_num_server_identity_keys
Number of server identity keys in use.
public_key_t g_client_whitelist [MAX_CLIENTS]
Whitelist of allowed client public keys.
size_t g_num_whitelisted_clients
Number of whitelisted clients.
Detailed Description
ascii-chat Server Mode Entry Point Header
This header exposes the server mode entry point for the unified binary architecture. The unified binary dispatches to server_main() when invoked as ascii-chat server.
Unified Binary Architecture
The ascii-chat application uses a single binary with multiple operating modes:
ascii-chat server - Run as server (multi-client connection manager)
ascii-chat client - Run as client (connects to server, streams video/audio)
This design provides several benefits:
Simplified distribution (single binary to install)
Reduced disk space (shared library code)
Easier testing (one binary to build and deploy)
Consistent versioning across modes
Mode Entry Point Contract
Each mode entry point (server_main, client_main) must:
Accept no arguments: int mode_main(void)
Options are already parsed by main dispatcher (available via global opt_* variables)
Return 0 on success, non-zero error code on failure
Perform mode-specific initialization and main loop
Perform complete cleanup before returning
Implementation Notes
The server_main() function is the original main() from src/server/main.c, adapted to the new dispatcher pattern. Common initialization (options parsing, logging setup, lock debugging) now happens in src/main.c before dispatch.
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
2025
Version
2.0
Definition in file server/main.h.
Typedef Documentation
server_context_t
typedef struct server_context_t server_context_t
Server context - encapsulates all server state.
This structure holds all server-wide state that was previously stored in global variables. It's passed to client handlers via tcp_server user_data, reducing global state and improving modularity.
DESIGN RATIONALE:
Reduces global state: All server state in one place
Improves testability: Can create multiple independent server instances
Better encapsulation: Clear ownership of resources
Thread-safe: Context is read-only after initialization
LIFETIME:
Created in server_main() before tcp_server_init()
Passed to tcp_server via config.user_data
Available to client handlers via tcp_client_context_t.user_data
Destroyed in server_main() after tcp_server_destroy()
Function Documentation
server_main()
int server_main (void)
Server mode entry point for unified binary.
This function implements the complete server lifecycle including:
Server-specific initialization (crypto, shutdown callback)
Network socket setup and binding
Main connection accept loop
Client lifecycle management
Graceful shutdown and cleanup
Options are already parsed by the main dispatcher before this function is called, so they are available via global opt_* variables.
Returns
0 on success, non-zero error code on failure
Example
# Invoked by dispatcher after options are parsed:
ascii-chat server --port 8080
# Options parsed in main.c, then server_main() called
Definition at line 1774 of file server/main.c.
                      {
  // Common initialization (options, logging, lock debugging) now happens in main.c before dispatch
  // This function focuses on server-specific initialization
  // Register atomic for debug tracking
  ATOMIC_REGISTER_AUTO(g_should_exit, NULL);
  // Register shutdown check callback for library code
  shutdown_register_callback(check_shutdown);
  // Initialize status screen log buffer if:
  // 1. Terminal is interactive AND status_screen is enabled, OR
  // 2. User explicitly set --status-screen on command line AND option is enabled (force it regardless of terminal)
  // In non-interactive mode without explicit flag, logs go directly to stdout/stderr
  if ((GET_OPTION(status_screen) && terminal_is_interactive()) ||
      (GET_OPTION(status_screen_explicitly_set) && GET_OPTION(status_screen))) {
    ui_status_log_init();
    // Initialize interactive grep for status screen
    log_search_init();
  }
  // Initialize crypto after logging is ready
  log_debug("Initializing crypto...");
  if (init_server_crypto() != 0) {
    // Print detailed error context if available
    LOG_ERRNO_IF_SET("Crypto initialization failed");
    FATAL(ERROR_CRYPTO, "Crypto initialization failed");
  }
  log_debug("Crypto initialized successfully");
  // Handle keepawake: check for mutual exclusivity and apply mode default
  // Server default: keepawake DISABLED (use --keepawake to enable)
  if (GET_OPTION(enable_keepawake) && GET_OPTION(disable_keepawake)) {
    FATAL(ERROR_INVALID_PARAM, "--keepawake and --no-keepawake are mutually exclusive");
  }
  if (GET_OPTION(enable_keepawake)) {
    (void)platform_enable_keepawake();
  }
  log_info("ascii-chat server starting...");
  // log_info("SERVER: Options initialized, using log file: %s", log_filename);
  int port = GET_OPTION(port);
  if (port < 1 || port > 65535) {
    log_error("Invalid port configuration: %d", port);
    FATAL(ERROR_CONFIG, "Invalid port configuration: %d", port);
  }
  ascii_simd_init();
  precalc_rgb_palettes(weight_red, weight_green, weight_blue);
  // Simple signal handling (temporarily disable complex threading signal handling)
  log_debug("Setting up simple signal handlers...");
  // Handle Ctrl+C for cleanup
  platform_signal(SIGINT, server_handle_sigint);
  // Handle termination signal (SIGTERM is defined with limited support on Windows)
  platform_signal(SIGTERM, server_handle_sigterm);
#ifndef _WIN32
  // SIGPIPE not supported on Windows
  platform_signal(SIGPIPE, SIG_IGN);
  // Note: SIGUSR1 is registered in src/main.c for all modes
#endif
#ifndef NDEBUG
  // Lock debug thread is now started in src/main.c (all modes)
  // Initialize statistics system
  if (stats_init() != 0) {
    FATAL(ERROR_THREAD, "Statistics system initialization failed");
  }
#endif
  // Create background worker thread pool for server operations
  g_server_worker_pool = thread_pool_create("server_workers");
  if (!g_server_worker_pool) {
    LOG_ERRNO_IF_SET("Failed to create server worker thread pool");
    FATAL(ERROR_MEMORY, "Failed to create server worker thread pool");
  }
  // Spawn statistics logging thread in worker pool
  if (thread_pool_spawn(g_server_worker_pool, stats_logger_thread, NULL, 0, "stats_logger") != ASCIICHAT_OK) {
    LOG_ERRNO_IF_SET("Statistics logger thread creation failed");
  } else {
    log_debug("Statistics logger thread started");
  }
  // Network setup - Use tcp_server abstraction for dual-stack IPv4/IPv6 binding
  log_debug("Config check: GET_OPTION(address)='%s', GET_OPTION(address6)='%s'", GET_OPTION(address),
            GET_OPTION(address6));
  bool ipv4_has_value = (strlen(GET_OPTION(address)) > 0);
  bool ipv6_has_value = (strlen(GET_OPTION(address6)) > 0);
  // Check if address is localhost (any loopback address, not just exact default)
  bool ipv4_is_default = is_localhost_ipv4(GET_OPTION(address));
  bool ipv6_is_default = is_localhost_ipv6(GET_OPTION(address6));
  log_debug("Binding decision: ipv4_has_value=%d, ipv6_has_value=%d, ipv4_is_default=%d, ipv6_is_default=%d",
            ipv4_has_value, ipv6_has_value, ipv4_is_default, ipv6_is_default);
  // Determine bind configuration
  bool bind_ipv4 = false;
  bool bind_ipv6 = false;
  const char *ipv4_address = NULL;
  const char *ipv6_address = NULL;
  if (ipv4_has_value && ipv6_has_value && ipv4_is_default && ipv6_is_default) {
    // Both are defaults: dual-stack with default localhost addresses
    bind_ipv4 = true;
    bind_ipv6 = true;
    ipv4_address = "127.0.0.1";
    ipv6_address = "::1";
    log_info("Default dual-stack: binding to 127.0.0.1 (IPv4) and ::1 (IPv6)");
  } else if (ipv4_has_value && !ipv4_is_default && (!ipv6_has_value || ipv6_is_default)) {
    // IPv4 explicitly set, IPv6 is default or empty: bind only IPv4
    bind_ipv4 = true;
    bind_ipv6 = false;
    ipv4_address = GET_OPTION(address);
    log_info("Binding only to IPv4 address: %s", ipv4_address);
  } else if (ipv6_has_value && !ipv6_is_default && (ipv4_is_default || !ipv4_has_value)) {
    // IPv6 explicitly set, IPv4 is default or empty: bind only IPv6
    bind_ipv4 = false;
    bind_ipv6 = true;
    ipv6_address = GET_OPTION(address6);
    log_info("Binding only to IPv6 address: %s", ipv6_address);
  } else {
    // Both explicitly set or one explicit + one default: dual-stack
    bind_ipv4 = true;
    bind_ipv6 = true;
    ipv4_address = ipv4_has_value ? GET_OPTION(address) : "127.0.0.1";
    ipv6_address = ipv6_has_value ? GET_OPTION(address6) : "::1";
    log_info("Dual-stack binding: IPv4=%s, IPv6=%s", ipv4_address, ipv6_address);
  }
  // Create server context - encapsulates all server state for passing to client handlers
  // This reduces global state and improves modularity by using tcp_server.user_data
  // Create H.265 server decoder context for multi-client codec support
  h265_server_context_t *h265_server_ctx = h265_server_context_create();
  if (!h265_server_ctx) {
    log_error("Failed to create H.265 server context");
    FATAL(ERROR_MEDIA_INIT, "Cannot initialize H.265 codec support");
  }
  server_context_t server_ctx = {
      .tcp_server = &g_tcp_server,
      .rate_limiter = g_rate_limiter,
      .client_manager = &g_client_manager,
      .client_manager_rwlock = &g_client_manager_rwlock,
      .server_should_exit = &g_should_exit,
      .audio_mixer = g_audio_mixer,
      .stats = &g_stats,
      .stats_mutex = &g_stats_mutex,
      .encryption_enabled = g_server_encryption_enabled,
      .server_private_key = &g_server_private_key,
      .client_whitelist = g_client_whitelist,
      .num_whitelisted_clients = g_num_whitelisted_clients,
      .session_host = NULL,           // Will be created after TCP server init
      .h265_server = h265_server_ctx, // H.265 codec support
  };
  // Configure TCP server
  tcp_server_config_t tcp_config = {
      .port = port,
      .ipv4_address = ipv4_address,
      .ipv6_address = ipv6_address,
      .bind_ipv4 = bind_ipv4,
      .bind_ipv6 = bind_ipv6,
      .accept_timeout_sec = ACCEPT_TIMEOUT,
      .client_handler = ascii_chat_client_handler,
      .user_data = &server_ctx, // Pass server context to client handlers
      .status_update_fn = NULL, // Status screen runs in its own thread
      .status_update_data = NULL,
  };
  // Initialize TCP server (creates and binds sockets)
  memset(&g_tcp_server, 0, sizeof(g_tcp_server));
  asciichat_error_t tcp_init_result = tcp_server_init(&g_tcp_server, &tcp_config);
  if (tcp_init_result != ASCIICHAT_OK) {
    // Signal shutdown to allow threads to exit before we call FATAL
    atomic_store_bool(&g_should_exit, true);
    log_debug("TCP server init failed, signaling shutdown to threads");
    // Clean up worker thread pool if it was created
    if (g_server_worker_pool) {
      log_debug("Early cleanup: destroying server worker pool");
      thread_pool_destroy(g_server_worker_pool);
      g_server_worker_pool = NULL;
    }
    FATAL(ERROR_NETWORK, "Failed to initialize TCP server");
  }
  // Initialize WebSocket server (for browser clients)
  websocket_server_config_t ws_config = {
      .port = GET_OPTION(websocket_port),
      .client_handler = websocket_client_handler,
      .user_data = &server_ctx,
      .tls_cert_path = GET_OPTION(websocket_tls_cert),
      .tls_key_path = GET_OPTION(websocket_tls_key),
  };
  // Log WSS configuration if provided
  if (ws_config.tls_cert_path && ws_config.tls_key_path) {
    log_info("WebSocket server configured for WSS with cert=%s key=%s",
             ws_config.tls_cert_path, ws_config.tls_key_path);
  }
  memset(&g_websocket_server, 0, sizeof(g_websocket_server));
  asciichat_error_t ws_init_result = websocket_server_init(&g_websocket_server, &ws_config);
  if (ws_init_result != ASCIICHAT_OK) {
    log_warn("Failed to initialize WebSocket server - browser clients will not be supported");
  } else {
    log_info("WebSocket server initialized on port %d", GET_OPTION(websocket_port));
  }
  // DEBUG: Print lock state immediately after WebSocket init
  log_info("★★★ LOCK STATE AFTER WEBSOCKET INIT ★★★");
  // debug_sync_print_state();  // Disabled: causes AddressSanitizer stack-use-after-return crash
  // =========================================================================
  // UPnP Port Mapping (Quick Win for Direct TCP)
  // =========================================================================
  // Track UPnP success for ACDS session type decision
  // If UPnP fails, we need to create a WebRTC session to enable client connectivity
  bool upnp_succeeded = false;
  // Try to open port via UPnP so direct TCP works for ~70% of home users.
  // If this fails, clients fall back to WebRTC automatically - not fatal.
  //
  // Strategy:
  //   1. UPnP (works on ~90% of home routers)
  //   2. NAT-PMP fallback (Apple routers)
  //   3. If both fail: use ACDS + WebRTC (reliable, but slightly higher latency)
  if (GET_OPTION(enable_upnp)) {
    asciichat_error_t upnp_result = nat_upnp_open(port, "ascii-chat Server", &g_upnp_ctx);
    if (upnp_result == ASCIICHAT_OK && g_upnp_ctx) {
      char public_addr[22];
      if (nat_upnp_get_address(g_upnp_ctx, public_addr, sizeof(public_addr)) == ASCIICHAT_OK) {
        char msg[256];
        safe_snprintf(msg, sizeof(msg), "🌐 Public endpoint: %s (direct TCP)", public_addr);
        log_console(LOG_INFO, msg);
        log_info("UPnP: Port mapping successful, public endpoint: %s", public_addr);
        upnp_succeeded = true;
      }
    } else {
      log_info("UPnP: Port mapping unavailable or failed - will use WebRTC fallback");
      log_console(LOG_INFO, "📡 Clients behind strict NATs will use WebRTC fallback");
    }
  } else {
    log_debug("UPnP: Disabled (use --upnp to enable automatic port mapping)");
  }
  // Initialize synchronization primitives
  if (rwlock_init(&g_client_manager_rwlock, "clients") != 0) {
    FATAL(ERROR_THREAD, "Failed to initialize client manager rwlock");
  }
  // Register global sync primitives for debugging
  NAMED_REGISTER_RWLOCK(&g_client_manager_rwlock, "client_manager_rwlock", NULL);
  // Lock debug system already initialized earlier in main()
  // Check if SIGINT/SIGTERM was received during initialization
  // If so, skip the accept loop entirely and go to cleanup
  if (atomic_load_bool(&g_should_exit)) {
    log_info("Shutdown signal received during initialization, skipping server startup");
    goto cleanup;
  }
  // Lock debug thread already started earlier in main()
  // NOTE: g_client_manager is already zero-initialized in client.c with = {0}
  // We only need to initialize the mutex
  mutex_init(&g_client_manager.mutex, "client_manager");
  // Initialize uthash head pointer for O(1) lookup (uthash requires NULL initialization)
  g_client_manager.clients_by_id = NULL;
  // Initialize connection rate limiter (prevents DoS attacks)
  if (!atomic_load_bool(&g_should_exit)) {
    log_debug("Initializing connection rate limiter...");
    g_rate_limiter = rate_limiter_create_memory();
    if (!g_rate_limiter) {
      LOG_ERRNO_IF_SET("Failed to initialize rate limiter");
      if (!atomic_load_bool(&g_should_exit)) {
        FATAL(ERROR_MEMORY, "Failed to create connection rate limiter");
      }
    } else {
      log_info("Connection rate limiter initialized (50 connections/min per IP)");
    }
  }
  // Initialize audio mixer (always enabled on server)
  if (!atomic_load_bool(&g_should_exit)) {
    log_debug("Initializing audio mixer for per-client audio rendering...");
    g_audio_mixer = mixer_create(MAX_CLIENTS, AUDIO_SAMPLE_RATE);
    if (!g_audio_mixer) {
      LOG_ERRNO_IF_SET("Failed to initialize audio mixer");
      if (!atomic_load_bool(&g_should_exit)) {
        FATAL(ERROR_AUDIO, "Failed to initialize audio mixer");
      }
    } else {
      if (!atomic_load_bool(&g_should_exit)) {
        log_debug("Audio mixer initialized successfully for per-client audio rendering");
      }
    }
  }
  // Initialize H.265 codec server context (always enabled on server)
  if (!atomic_load_bool(&g_should_exit)) {
    log_debug("Initializing H.265 codec server context...");
    g_h265_server = h265_server_context_create();
    if (!g_h265_server) {
      LOG_ERRNO_IF_SET("Failed to initialize H.265 codec context");
      if (!atomic_load_bool(&g_should_exit)) {
        FATAL(ERROR_MEDIA_INIT, "Failed to initialize H.265 codec context");
      }
    } else {
      if (!atomic_load_bool(&g_should_exit)) {
        log_debug("H.265 codec server context initialized successfully");
      }
    }
  }
  // Initialize mDNS context for LAN service discovery (optional)
  // mDNS allows clients on the LAN to discover this server without knowing its IP
  // Can be disabled with --no-mdns-advertise
  // Note: Actual advertisement is deferred until after ACDS session creation (if --acds is enabled)
  if (!atomic_load_bool(&g_should_exit) && !GET_OPTION(no_mdns_advertise)) {
    log_debug("Initializing mDNS for LAN service discovery...");
    g_mdns_ctx = asciichat_mdns_init();
    if (!g_mdns_ctx) {
      LOG_ERRNO_IF_SET("Failed to initialize mDNS (non-fatal, LAN discovery disabled)");
      log_warn("mDNS disabled - LAN service discovery will not be available");
      g_mdns_ctx = NULL;
    } else {
      log_debug("mDNS context initialized, advertisement deferred until session string is ready");
    }
  } else if (GET_OPTION(no_mdns_advertise)) {
    log_info("mDNS service advertisement disabled via --no-mdns-advertise");
  }
  // ========================================================================
  // Session Host Creation (for discovery mode support)
  // ========================================================================
  // Create session_host to track clients in a transport-agnostic way.
  // This enables future discovery mode where participants can become hosts.
  if (!atomic_load_bool(&g_should_exit)) {
    session_host_config_t host_config = {
        .port = port,
        .ipv4_address = ipv4_address,
        .ipv6_address = ipv6_address,
        .max_clients = GET_OPTION(max_clients),
        .encryption_enabled = g_server_encryption_enabled,
        .key_path = GET_OPTION(encrypt_key),
        .password = GET_OPTION(password),
        .callbacks = {0}, // No callbacks for now
        .user_data = NULL,
    };
    server_ctx.session_host = session_host_create(&host_config);
    if (!server_ctx.session_host) {
      // Non-fatal: session_host is optional, server can work without it
      log_warn("Failed to create session_host (discovery mode support disabled)");
    } else {
      log_debug("Session host created for discovery mode support");
    }
  }
  // ========================================================================
  // MAIN CONNECTION LOOP - Delegated to tcp_server
  // ========================================================================
  //
  // The tcp_server module handles:
  // 1. Dual-stack IPv4/IPv6 accept loop with select() timeout
  // 2. Spawning client_handler threads for each connection
  // 3. Responsive shutdown when g_tcp_server.running is set to false
  //
  // Client lifecycle is managed by ascii_chat_client_handler() which:
  // - Performs rate limiting
  // - Calls add_client() to initialize structures and spawn workers
  // - Blocks until client disconnects
  // - Calls remove_client() to cleanup and stop worker threads
  // ACDS Session Creation: Register this server with discovery service
  // This also determines the session string for mDNS (if --acds is enabled)
  char session_string[64] = {0};
  bool session_is_mdns_only = false;
  // ACDS Registration (conditional on --discovery flag)
  if (GET_OPTION(discovery)) {
    // Security Requirement Check (Issue #239):
    // Server IP must be protected by password, identity verification, or explicit opt-in
    // Auto-detection: Check if password or identity verification is configured
    const char *password = GET_OPTION(password);
    bool has_password = password && strlen(password) > 0;
    const char *encrypt_key = GET_OPTION(encrypt_key);
    bool has_identity = encrypt_key && strlen(encrypt_key) > 0;
    bool explicit_expose = GET_OPTION(discovery_expose_ip) != 0;
    // Validate security configuration BEFORE attempting ACDS connection
    bool acds_expose_ip_flag = false;
    if (has_password || has_identity) {
      // Auto-enable privacy: IP revealed only after verification
      acds_expose_ip_flag = false;
      log_plain("🔒 ACDS privacy enabled: IP disclosed only after %s verification",
                has_password ? "password" : "identity");
    } else if (explicit_expose) {
      // Explicit opt-in to public IP disclosure
      // Only prompt if running interactively (can prompt user)
      // When non-interactive (automated/scripted), treat explicit flag as confirmation
      bool is_interactive = terminal_can_prompt_user();
      if (is_interactive) {
        log_plain_stderr("");
        log_plain_stderr("⚠️  WARNING: You are about to allow PUBLIC IP disclosure!");
        log_plain_stderr("⚠️  Anyone with the session string will be able to see your IP address.");
        log_plain_stderr("⚠️  This is NOT RECOMMENDED unless you understand the privacy implications.");
        log_plain_stderr("");
        if (!platform_prompt_yes_no("Do you want to proceed with public IP disclosure", false)) {
          log_plain_stderr("");
          log_plain_stderr("❌ IP disclosure not confirmed. Server will run WITHOUT discovery service.");
          goto skip_acds_session;
        }
      }
      // User confirmed (or running non-interactively with explicit flag) - proceed with public IP disclosure
      acds_expose_ip_flag = true;
      log_plain_stderr("");
      log_plain_stderr("⚠️  Public IP disclosure CONFIRMED");
      log_plain_stderr("⚠️  Your IP address will be visible to anyone with the session string");
    } else {
      // Security violation: No password, no identity, no explicit opt-in
      log_plain_stderr("❌ Cannot create ACDS session: No security configured!");
      log_plain_stderr("   You must either:");
      log_plain_stderr("   1. Set a password: --password \"your-secret\"");
      log_plain_stderr("   2. Use identity key: --key ~/.ssh/id_ed25519");
      log_plain_stderr("   3. Explicitly allow public IP: --acds-expose-ip (NOT RECOMMENDED)");
      log_plain_stderr("");
      log_plain_stderr("Server will run WITHOUT discovery service.");
      goto skip_acds_session;
    }
    // Security is configured, proceed with ACDS connection
    const char *acds_server = GET_OPTION(discovery_server);
    uint16_t acds_port = (uint16_t)GET_OPTION(discovery_port);
    log_info("Attempting to create session on ACDS server at %s:%d...", acds_server, acds_port);
    acds_client_config_t acds_config;
    acds_client_config_init_defaults(&acds_config);
    SAFE_STRNCPY(acds_config.server_address, acds_server, sizeof(acds_config.server_address));
    acds_config.server_port = acds_port;
    acds_config.timeout_ms = 5 * MS_PER_SEC_INT;
    // Allocate ACDS client on heap for server lifecycle
    g_acds_client = SAFE_MALLOC(sizeof(acds_client_t), acds_client_t *);
    if (!g_acds_client) {
      log_error("Failed to allocate ACDS client");
      goto skip_acds_session;
    }
    asciichat_error_t acds_connect_result = acds_client_connect(g_acds_client, &acds_config);
    if (acds_connect_result != ASCIICHAT_OK) {
      log_error("Failed to connect to ACDS server at %s:%d: %s", acds_server, acds_port,
                asciichat_error_string(acds_connect_result));
      goto skip_acds_session;
    }
    if (acds_connect_result == ASCIICHAT_OK) {
      // Prepare session creation parameters
      acds_session_create_params_t create_params;
      memset(&create_params, 0, sizeof(create_params));
      // Use server's Ed25519 identity public key if available
      if (g_server_encryption_enabled && has_identity) {
        memcpy(create_params.identity_pubkey, g_server_private_key.public_key, 32);
        log_debug("Using server identity key for ACDS session");
      } else {
        // No identity key available - use zero key
        // ACDS will accept this if identity verification is not required
        memset(create_params.identity_pubkey, 0, 32);
        log_debug("No server identity key - using zero key for ACDS session");
      }
      create_params.capabilities = 0x03; // Video + Audio
      create_params.max_participants = GET_OPTION(max_clients);
      log_debug("ACDS: max_clients option value = %d", GET_OPTION(max_clients));
      // Set password if configured
      create_params.has_password = has_password;
      if (has_password) {
        // TODO: Hash password with Argon2id
        SAFE_STRNCPY(create_params.password, password, sizeof(create_params.password));
      }
      // Set IP disclosure policy (determined above)
      create_params.acds_expose_ip = acds_expose_ip_flag;
      log_info("DEBUG: Server setting acds_expose_ip=%d (explicit_expose=%d, has_password=%d, has_identity=%d)",
               create_params.acds_expose_ip, explicit_expose, has_password, has_identity);
      // Set session type (Direct TCP or WebRTC)
      // Auto-detect: Use WebRTC if UPnP failed OR if explicitly requested via --webrtc
      // Exception: If bind address is 0.0.0.0, server is on public IP - use Direct TCP
      const char *bind_addr = GET_OPTION(address);
      bool bind_all_interfaces = (strcmp(bind_addr, "0.0.0.0") == 0);
      // Determine session type: prefer WebRTC by default (unless explicitly disabled)
      // Priority: explicit --webrtc flag > connection type detection > UPnP > default
      if (GET_OPTION(webrtc)) {
        // Explicit WebRTC request
        create_params.session_type = SESSION_TYPE_WEBRTC;
        log_info("ACDS session type: WebRTC (explicitly requested via --webrtc)");
      } else if (bind_all_interfaces) {
        // Bind to 0.0.0.0: use WebRTC as default (better NAT compatibility)
        create_params.session_type = SESSION_TYPE_WEBRTC;
        log_info("ACDS session type: WebRTC (default for 0.0.0.0 binding, provides NAT-agnostic connections)");
      } else if (upnp_succeeded) {
        // UPnP port mapping worked - can use direct TCP
        create_params.session_type = SESSION_TYPE_DIRECT_TCP;
        log_info("ACDS session type: Direct TCP (UPnP succeeded, server is publicly accessible)");
      } else {
        // UPnP failed and not on public IP - use WebRTC for NAT traversal
        create_params.session_type = SESSION_TYPE_WEBRTC;
        log_info("ACDS session type: WebRTC (UPnP failed, server behind NAT)");
      }
      // Server connection information (where clients should connect)
      // If bind address is 0.0.0.0, leave server_address empty for ACDS to auto-detect public IP
      if (bind_all_interfaces) {
        create_params.server_address[0] = '\0'; // Empty - ACDS will use connection source IP
        log_debug("Bind address is 0.0.0.0, ACDS will auto-detect public IP from connection");
      } else {
        SAFE_STRNCPY(create_params.server_address, bind_addr, sizeof(create_params.server_address));
      }
      create_params.server_port = port;
      // DEBUG: Log what we're sending to ACDS
      log_info("DEBUG: Before SESSION_CREATE - expose_ip_publicly=%d, server_address='%s' port=%u, session_type=%u",
               create_params.acds_expose_ip, create_params.server_address, create_params.server_port,
               create_params.session_type);
      // Create session
      acds_session_create_result_t create_result;
      asciichat_error_t create_err = acds_session_create(g_acds_client, &create_params, &create_result);
      if (create_err == ASCIICHAT_OK) {
        SAFE_STRNCPY(session_string, create_result.session_string, sizeof(session_string));
        SAFE_STRNCPY(g_session_string, create_result.session_string, sizeof(g_session_string));
        session_is_mdns_only = false; // Session is now registered with ACDS (globally discoverable)
        log_info("Session created: %s", session_string);
        // Server must join its own session so ACDS can route signaling messages
        log_debug("Server joining session as first participant for WebRTC signaling...");
        acds_session_join_params_t join_params = {0};
        join_params.session_string = session_string;
        // Use same identity key as session creation
        memcpy(join_params.identity_pubkey, create_params.identity_pubkey, 32);
        // Include password if session is password-protected
        if (has_password) {
          join_params.has_password = true;
          SAFE_STRNCPY(join_params.password, password, sizeof(join_params.password));
        }
        acds_session_join_result_t join_result = {0};
        asciichat_error_t join_err = acds_session_join(g_acds_client, &join_params, &join_result);
        if (join_err != ASCIICHAT_OK || !join_result.success) {
          log_error("Failed to join own session: %s (error: %s)", asciichat_error_string(join_err),
                    join_result.error_message[0] ? join_result.error_message : "unknown");
          // Continue anyway - this is not fatal for Direct TCP sessions
        } else {
          log_debug("Server joined session successfully (participant_id: %02x%02x...)", join_result.participant_id[0],
                    join_result.participant_id[1]);
          // Store participant ID for WebRTC signaling (needed to identify server in SDP/ICE messages)
          memcpy(g_server_participant_id, join_result.participant_id, 16);
          log_debug("Stored server participant_id for signaling: %02x%02x...", g_server_participant_id[0],
                    g_server_participant_id[1]);
          memcpy(create_result.session_id, join_result.session_id, 16);
        }
        // Keep ACDS connection alive for WebRTC signaling relay
        log_debug("Server staying connected to ACDS for signaling relay");
        // Create ACDS transport wrapper for sending signaling packets
        g_acds_transport = acip_tcp_transport_create("transport_acds_server", g_acds_client->socket, NULL);
        if (!g_acds_transport) {
          log_error("Failed to create ACDS transport wrapper");
        } else {
          log_debug("ACDS transport wrapper created for signaling");
          // Start ACDS ping thread to keep connection alive (for ALL session types)
          int ping_thread_result = asciichat_thread_create(&g_acds_ping_thread, "acds_ping", acds_ping_thread, NULL);
          if (ping_thread_result != 0) {
            log_error("Failed to create ACDS ping thread: %d", ping_thread_result);
          } else {
            log_debug("ACDS ping thread started to keep connection alive");
            g_acds_ping_thread_started = true;
          }
        }
        // Initialize WebRTC peer_manager if session type is WebRTC
        if (create_params.session_type == SESSION_TYPE_WEBRTC) {
          log_debug("Initializing WebRTC library and peer manager for session (role=CREATOR)...");
          // Initialize WebRTC library (libdatachannel)
          asciichat_error_t webrtc_init_result = webrtc_init();
          if (webrtc_init_result != ASCIICHAT_OK) {
            log_error("Failed to initialize WebRTC library: %s", asciichat_error_string(webrtc_init_result));
            g_webrtc_peer_manager = NULL;
          } else {
            log_debug("WebRTC library initialized successfully");
            // Configure STUN servers for ICE gathering (static to persist for peer_manager lifetime)
            static stun_server_t stun_servers[4] = {0};
            static lifecycle_t g_stun_lc = LIFECYCLE_INIT;
            static int stun_count = 0; // Store actual count separately
            if (lifecycle_init(&g_stun_lc, "stun")) {
              log_debug("Parsing STUN servers from options: '%s'", GET_OPTION(stun_servers));
              int count =
                  stun_servers_parse(GET_OPTION(stun_servers), OPT_ENDPOINT_STUN_SERVERS_DEFAULT, stun_servers, 4);
              if (count > 0) {
                stun_count = count;
                log_debug("Parsed %d STUN servers", count);
                for (int i = 0; i < count; i++) {
                  log_debug("  STUN[%d]: '%s' (len=%d)", i, stun_servers[i].host, stun_servers[i].host_len);
                }
              } else {
                log_warn("Failed to parse STUN servers, using defaults");
                stun_count = stun_servers_parse(OPT_ENDPOINT_STUN_SERVERS_DEFAULT, OPT_ENDPOINT_STUN_SERVERS_DEFAULT,
                                                stun_servers, 4);
                log_debug("Using default STUN servers, count=%d", stun_count);
                for (int i = 0; i < stun_count; i++) {
                  log_debug("  STUN[%d]: '%s' (len=%d)", i, stun_servers[i].host, stun_servers[i].host_len);
                }
              }
            }
            // Configure peer_manager
            webrtc_peer_manager_config_t pm_config = {
                .role = WEBRTC_ROLE_CREATOR, // Server accepts offers, generates answers
                .stun_servers = stun_servers,
                .stun_count = stun_count,
                .turn_servers = NULL, // No TURN for server (clients should have public IP or use TURN)
                .turn_count = 0,
                .on_transport_ready = on_webrtc_transport_ready,
                .user_data = &server_ctx,
                .crypto_ctx = NULL // WebRTC handles crypto internally
            };
            // Configure signaling callbacks for relaying SDP/ICE via ACDS
            webrtc_signaling_callbacks_t signaling_callbacks = {
                .send_sdp = server_send_sdp, .send_ice = server_send_ice, .user_data = NULL};
            // Create peer_manager
            asciichat_error_t pm_result =
                webrtc_peer_manager_create(&pm_config, &signaling_callbacks, &g_webrtc_peer_manager);
            if (pm_result != ASCIICHAT_OK) {
              log_error("Failed to create WebRTC peer_manager: %s", asciichat_error_string(pm_result));
              g_webrtc_peer_manager = NULL;
            } else {
              log_debug("WebRTC peer_manager initialized successfully");
              // Start ACDS receive thread for WebRTC signaling relay
              int thread_result =
                  asciichat_thread_create(&g_acds_receive_thread, "acds_recv", acds_receive_thread, NULL);
              if (thread_result != 0) {
                log_error("Failed to create ACDS receive thread: %d", thread_result);
                // Cleanup peer_manager since signaling won't work
                webrtc_peer_manager_destroy(g_webrtc_peer_manager);
                g_webrtc_peer_manager = NULL;
              } else {
                log_debug("ACDS receive thread started for WebRTC signaling relay");
                g_acds_receive_thread_started = true;
              }
            }
          } // Close else block from webrtc_init() success
        } else {
          log_debug("Session type is DIRECT_TCP, skipping WebRTC peer_manager initialization");
        }
        // Advertise mDNS with ACDS session string
        // This ensures both mDNS and ACDS discovery return the same session string
        advertise_mdns_with_session(session_string, (uint16_t)port);
      } else {
        log_warn("Failed to create session on ACDS server (server will run without discovery)");
        // Clean up failed ACDS client
        if (g_acds_client) {
          acds_client_disconnect(g_acds_client);
          SAFE_FREE(g_acds_client);
          g_acds_client = NULL;
        }
      }
    } else {
      log_warn("Could not connect to ACDS server at %s:%d (server will run without discovery)", acds_server, acds_port);
    }
  } else {
    log_info("ACDS registration disabled (use --acds to enable)");
  }
skip_acds_session:
  // Fallback: If no session string was set by ACDS (either disabled or failed),
  // generate a random session string for mDNS discovery only
  if (session_string[0] == '\0' && g_mdns_ctx) {
    log_debug("No ACDS session string available, generating random session for mDNS");
    // Use the proper session string generation from discovery module
    // This generates adjective-noun-noun format using the full wordlists
    if (acds_string_generate(session_string, sizeof(session_string)) != ASCIICHAT_OK) {
      log_error("Failed to generate session string for mDNS");
      return 1;
    }
    log_debug("Generated random session string for mDNS: '%s'", session_string);
    // Mark that this session is mDNS-only (not globally discoverable via ACDS)
    session_is_mdns_only = true;
    // Advertise mDNS with random session string
    advertise_mdns_with_session(session_string, (uint16_t)port);
  }
  // ====================================================================
  // Display session string prominently as the FINAL startup message
  // This ensures users see the connection info clearly without logs
  // wiping it away
  // ====================================================================
  if (session_string[0] != '\0') {
    if (session_is_mdns_only) {
      log_plain("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n📋 Session String: %s (LAN only via "
                "mDNS)\n🔗 Share with others on your LAN to join:\n   ascii-chat "
                "%s\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
                session_string, session_string);
    } else {
      log_plain("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n📋 Session String: %s\n🔗 Share this "
                "globally to join:\n   ascii-chat %s\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
                session_string, session_string);
    }
  }
  // Copy session info to globals for status screen display
  SAFE_STRNCPY(g_session_string, session_string, sizeof(g_session_string));
  g_session_is_mdns_only = session_is_mdns_only;
  log_debug("Server entering accept loop (port %d)...", port);
  // Initialize status screen
  g_server_start_time = time(NULL);
  g_last_status_update = platform_get_monotonic_time_us();
  // Clear status screen log buffer to discard initialization logs
  // This ensures only NEW logs (generated after status screen starts) are displayed
  if (GET_OPTION(status_screen)) {
    ui_status_log_clear();
  }
  // Start status screen thread if enabled
  // Runs independently at target FPS (default 60 Hz), decoupled from network accept loop
  if (GET_OPTION(status_screen)) {
    if (asciichat_thread_create(&g_status_screen_thread, "status_screen", status_screen_thread, NULL) != 0) {
      log_error("Failed to create status screen thread");
      goto cleanup;
    }
    log_debug("Status screen thread started");
  }
  // Start WebSocket server thread if initialized
  if (g_websocket_server.context != NULL) {
    if (asciichat_thread_create(&g_websocket_server_thread, "ws_server", websocket_server_thread_wrapper,
                                &g_websocket_server) != 0) {
      log_error("Failed to create WebSocket server thread");
    } else {
      g_websocket_server_thread_started = true;
      log_info("WebSocket server thread started");
    }
  }
  // Run TCP server (blocks until shutdown signal received)
  // tcp_server_run() handles:
  // - select() on IPv4/IPv6 sockets with timeout
  // - accept() new connections
  // - Spawn ascii_chat_client_handler() thread for each connection
  // - Responsive shutdown when atomic_store_bool(&g_tcp_server.running, false)
  asciichat_error_t run_result = tcp_server_run(&g_tcp_server);
  if (run_result != ASCIICHAT_OK) {
    log_error("TCP server exited with error");
  }
  log_debug("Server accept loop exited");
cleanup:
  // Signal status screen thread to exit
  atomic_store_bool(&g_should_exit, true);
  // Wait for status screen thread to finish if it was started
  if (GET_OPTION(status_screen)) {
    log_debug("Waiting for status screen thread to exit...");
    int join_result = asciichat_thread_join_timeout(&g_status_screen_thread, NULL, NS_PER_SEC_INT); // 1 second
    if (join_result != 0) {
      log_warn("Status screen thread did not exit cleanly (timeout)");
    } else {
      log_debug("Status screen thread exited");
    }
  }
  // Cleanup
  log_debug("Server shutting down...");
  memset(g_session_string, 0, sizeof(g_session_string)); // Clear session string for status screen
  // Wake up any threads that might be blocked on condition variables
  // (like packet queues) to ensure responsive shutdown
  // This must happen BEFORE client cleanup to wake up any blocked threads
  static_cond_broadcast(&g_shutdown_cond);
  // NOTE: Do NOT call cond_destroy() on statically-initialized condition variables
  // g_shutdown_cond uses STATIC_COND_INIT which doesn't allocate resources that need cleanup
  // Calling cond_destroy() on a static cond is undefined behavior on some platforms
  // Close all client sockets immediately to unblock receive threads.
  // The signal handler only closed the listening socket, but client receive threads
  // are still blocked in recv_with_timeout(). We need to close their sockets to unblock them.
  log_debug("Closing all client sockets to unblock receive threads...");
  // Use write lock since we're modifying client->socket
  rwlock_wrlock(&g_client_manager_rwlock);
  for (int i = 0; i < MAX_CLIENTS; i++) {
    client_info_t *client = &g_client_manager.clients[i];
    if (client->client_id[0] != '\0' && client->socket != INVALID_SOCKET_VALUE) {
      socket_close(client->socket);
      client->socket = INVALID_SOCKET_VALUE;
    }
  }
  rwlock_wrunlock(&g_client_manager_rwlock);
  log_debug("Signaling all clients to stop (sockets closed, g_should_exit set)...");
  // Stop and destroy server worker thread pool (stats logger, etc.)
  if (g_server_worker_pool) {
    thread_pool_destroy(g_server_worker_pool);
    g_server_worker_pool = NULL;
    log_debug("Server worker thread pool stopped");
  }
  // Destroy rate limiter
  if (g_rate_limiter) {
    rate_limiter_destroy(g_rate_limiter);
    g_rate_limiter = NULL;
  }
  // Shutdown WebSocket server BEFORE removing clients.
  // The LWS event thread runs callbacks that access transport data (impl_data).
  // If we destroy transports via remove_client while LWS is still running,
  // callbacks access freed memory (heap-use-after-free).
  // lws_context_destroy fires LWS_CALLBACK_CLOSED for all connections, which
  // closes transports and NULLs the per-session conn_data->transport pointer.
  // After this, remove_client can safely destroy the transport objects.
  bool websocket_exited_cleanly = true;  // Default to clean unless timeout detected
  if (g_websocket_server.context != NULL) {
    log_debug("Shutting down WebSocket server before client cleanup");
    atomic_store_u64(&g_websocket_server.running, false);
    // Wake the LWS event loop immediately instead of waiting for the 50ms
    // lws_service timeout. This is safe because the event loop thread can't
    // destroy the context until after it exits its loop (which requires
    // seeing running=false, which we just set).
    websocket_server_cancel_service(&g_websocket_server);
    // Join with 500ms timeout. If the WebSocket thread is deadlocked in lws_service(),
    // it won't exit and we skip the graceful handler thread cleanup to avoid prolonged
    // shutdown hangs. Forceful cleanup will happen in websocket_server_destroy().
    if (g_websocket_server_thread_started) {
      int join_result =
          asciichat_thread_join_timeout(&g_websocket_server_thread, NULL, 500 * NS_PER_MS_INT); // 500ms in ns
      if (join_result != 0) {
        log_warn("WebSocket thread did not exit within 500ms, skipping graceful handler cleanup");
        websocket_exited_cleanly = false;
      }
      g_websocket_server_thread_started = false;
    }
    if (websocket_exited_cleanly) {
      log_debug("WebSocket thread confirmed exited, waiting for handler threads to complete...");
    }
  }
  // Wait for all client handler threads to exit BEFORE destroying WebSocket context
  // Handler threads may still be working with WebSocket connections, so we must
  // ensure they complete before destroying the context (which would abort their operations).
  // Skip this if WebSocket thread didn't exit cleanly (deadlock detected).
  if (websocket_exited_cleanly) {
    int retry_count = 0;
    while (retry_count < 50) { // Max 500ms wait
      rwlock_rdlock(&g_client_manager_rwlock);
      bool all_cleaned = true;
      for (int i = 0; i < MAX_CLIENTS; i++) {
        if (g_client_manager.clients[i].client_id[0] != '\0') {
          all_cleaned = false;
          break;
        }
      }
      rwlock_rdunlock(&g_client_manager_rwlock);
      if (all_cleaned)
        break;
      platform_sleep_us(10 * US_PER_MS_INT); // 10ms
      retry_count++;
    }
    log_debug("Client handler threads cleaned up, destroying WebSocket server");
  } else {
    log_warn("Skipping graceful handler thread cleanup due to WebSocket deadlock");
  }
  // ★ CRITICAL: Cleanup debug sync BEFORE destroying websocket_server
  // The debug_sync thread runs concurrently and accesses the named registry.
  // If websocket_server_destroy() frees thread pool memory first, the debug thread
  // will get a use-after-free error trying to check condition variables.
  // Moving this before websocket destroy prevents the race condition.
#ifndef NDEBUG
  debug_sync_destroy();
#endif
  // Now destroy WebSocket server after all handler threads have completed
  // This ensures no handler threads are still accessing the context.
  // (It's safe to call even if context was already destroyed forcefully above)
  websocket_server_destroy(&g_websocket_server);
  log_debug("WebSocket server destroyed");
  // Cleanup status screen log capture (must be AFTER all client threads exit to avoid use-after-free)
  // Client threads may still be appending logs during the wait loop above, so we destroy the buffer only
  // after we've confirmed they've all exited.
  ui_status_log_destroy();
  // Clean up all connected clients
  log_debug("Cleaning up connected clients...");
  // FIXED: Simplified to collect client IDs first, then remove them without holding locks
  char clients_to_remove[MAX_CLIENTS][MAX_CLIENT_ID_LEN];
  int client_count = 0;
  rwlock_rdlock(&g_client_manager_rwlock);
  for (int i = 0; i < MAX_CLIENTS; i++) {
    client_info_t *client = &g_client_manager.clients[i];
    // Only attempt to clean up clients that were actually connected
    // (client_id is empty string for uninitialized clients)
    // FIXED: Only access mutex for initialized clients to avoid accessing uninitialized mutex
    if (client->client_id[0] == '\0') {
      continue; // Skip uninitialized clients
    }
    // Use snapshot pattern to avoid holding both locks simultaneously
    // This prevents deadlock by not acquiring client_state_mutex while holding rwlock
    SAFE_STRNCPY(clients_to_remove[client_count], client->client_id, MAX_CLIENT_ID_LEN - 1);
    // Clean up ANY client that was allocated, whether active or not
    // (disconnected clients may not be active but still have resources)
    client_count++;
  }
  rwlock_rdunlock(&g_client_manager_rwlock);
  // Remove all clients without holding any locks
  for (int i = 0; i < client_count; i++) {
    if (remove_client(&server_ctx, clients_to_remove[i]) != 0) {
      log_error("Failed to remove client %s during shutdown", clients_to_remove[i]);
    }
  }
  // Clean up hash table
  // Cannot use HASH_ITER when deleting - HASH_DELETE modifies the table and can set
  // the pointer to NULL, causing HASH_ITER to dereference a null pointer.
  // Instead, repeatedly delete the first item until the table is empty.
  while (g_client_manager.clients_by_id) {
    client_info_t *current_client = g_client_manager.clients_by_id;
    HASH_DELETE(hh, g_client_manager.clients_by_id, current_client);
    // Note: We don't free current_client here because it's part of the clients[] array
  }
  // Clean up audio mixer
  if (g_audio_mixer) {
    // Set to NULL first before destroying.
    // Client handler threads may still be running and checking g_audio_mixer.
    // Setting it to NULL first prevents use-after-free race condition.
    // volatile ensures this write is visible to other threads immediately
    mixer_t *mixer_to_destroy = g_audio_mixer;
    g_audio_mixer = NULL;
    mixer_destroy(mixer_to_destroy);
  }
  // Clean up H.265 codec server context
  if (g_h265_server) {
    // Set to NULL first before destroying, similar to g_audio_mixer
    // Client handler threads may still be running and checking g_h265_server.
    h265_server_context_t *h265_to_destroy = g_h265_server;
    g_h265_server = NULL;
    h265_server_context_destroy(h265_to_destroy);
    log_debug("H.265 codec server context shut down");
  }
  // Clean up mDNS context
  if (g_mdns_ctx) {
    asciichat_mdns_destroy(g_mdns_ctx);
    g_mdns_ctx = NULL;
    log_debug("mDNS context shut down");
  }
  // Clean up synchronization primitives
  rwlock_destroy(&g_client_manager_rwlock);
  mutex_destroy(&g_client_manager.mutex);
#ifndef NDEBUG
  // Clean up statistics system
  stats_cleanup();
  // Note: debug_sync_destroy() is now called earlier (before websocket_server_destroy)
  // to avoid use-after-free race condition with the debug monitoring thread
#endif
  // Destroy session host (before TCP server shutdown)
  if (server_ctx.session_host) {
    log_debug("Destroying session host");
    session_host_destroy(server_ctx.session_host);
    server_ctx.session_host = NULL;
  }
  // Destroy H.265 server codec context
  if (server_ctx.h265_server) {
    log_debug("Destroying H.265 server context");
    h265_server_context_destroy(server_ctx.h265_server);
    server_ctx.h265_server = NULL;
  }
  // Shutdown TCP server (closes listen sockets and cleans up)
  tcp_server_destroy(&g_tcp_server);
  // WebSocket server already shut down before client cleanup (above).
  // Join ACDS threads (if started)
  // NOTE: Must be done BEFORE destroying transport to ensure clean shutdown
  if (g_acds_ping_thread_started) {
    log_debug("Joining ACDS ping thread");
    asciichat_thread_join(&g_acds_ping_thread, NULL);
    g_acds_ping_thread_started = false;
    log_debug("ACDS ping thread joined");
  }
  if (g_acds_receive_thread_started) {
    log_debug("Joining ACDS receive thread");
    asciichat_thread_join(&g_acds_receive_thread, NULL);
    g_acds_receive_thread_started = false;
    log_debug("ACDS receive thread joined");
  }
  // Clean up WebRTC peer manager (if initialized for ACDS signaling relay)
  if (g_webrtc_peer_manager) {
    log_debug("Destroying WebRTC peer manager");
    webrtc_peer_manager_destroy(g_webrtc_peer_manager);
    g_webrtc_peer_manager = NULL;
  }
  // Clean up ACDS transport wrapper (if created)
  if (g_acds_transport) {
    log_debug("Destroying ACDS transport wrapper");
    acip_transport_destroy(g_acds_transport);
    g_acds_transport = NULL;
  }
  // Disconnect from ACDS server (if connected for WebRTC signaling relay)
  if (g_acds_client) {
    log_debug("Disconnecting from ACDS server");
    acds_client_disconnect(g_acds_client);
    SAFE_FREE(g_acds_client);
    g_acds_client = NULL;
  }
  // Disable keepawake mode (re-allow OS to sleep)
  platform_disable_keepawake();
  // Clean up platform-specific resources (Windows: Winsock cleanup, timer restoration)
  // POSIX: minimal cleanup (symbol cache already handled above on Windows)
  socket_cleanup();
  log_info("Server shutdown complete");
  asciichat_error_stats_print();
  // Use exit() to allow atexit() handlers to run
  // Cleanup functions are idempotent (check if initialized first)
  return 0;
}
References acds_client_config_init_defaults(), acds_client_connect(), acds_client_disconnect(), acds_session_create(), acds_session_join(), acds_string_generate(), acip_tcp_transport_create(), acip_transport_destroy(), ascii_simd_init(), asciichat_error_stats_print(), asciichat_mdns_destroy(), asciichat_mdns_init(), asciichat_thread_create(), asciichat_thread_join(), atomic_load_bool(), atomic_store_bool(), atomic_store_u64(), debug_sync_destroy(), g_audio_mixer, g_client_manager, g_client_manager_rwlock, g_client_whitelist, g_h265_server, g_num_whitelisted_clients, g_rate_limiter, g_server_encryption_enabled, g_server_private_key, g_should_exit, g_shutdown_cond, g_stats, g_stats_mutex, server_context_t::h265_server, h265_server_context_create(), h265_server_context_destroy(), is_localhost_ipv4(), is_localhost_ipv6(), lifecycle_init(), log_search_init(), mixer_create(), mixer_destroy(), mutex_destroy(), mutex_init(), nat_upnp_get_address(), nat_upnp_open(), platform_disable_keepawake(), platform_enable_keepawake(), platform_get_monotonic_time_us(), platform_prompt_yes_no(), platform_sleep_us(), precalc_rgb_palettes(), rate_limiter_create_memory(), rate_limiter_destroy(), remove_client(), rwlock_init(), safe_snprintf(), server_context_t::session_host, session_host_create(), session_host_destroy(), shutdown_register_callback(), stats_cleanup(), stats_init(), stats_logger_thread(), stun_servers_parse(), tcp_server_destroy(), tcp_server_init(), tcp_server_run(), terminal_can_prompt_user(), terminal_is_interactive(), thread_pool_create(), thread_pool_destroy(), thread_pool_spawn(), ui_status_log_clear(), ui_status_log_destroy(), ui_status_log_init(), webrtc_init(), webrtc_peer_manager_create(), webrtc_peer_manager_destroy(), websocket_server_cancel_service(), websocket_server_destroy(), websocket_server_init(), weight_blue, weight_green, and weight_red.
Variable Documentation
g_audio_mixer
mixer_t* volatile g_audio_mixer extern
Global audio mixer.
Volatile pointer to the multi-client audio mixer instance. Used to mix audio from multiple clients for playback.
Global audio mixer.
The mixer combines audio streams from multiple clients, excluding each client's own audio from their outbound stream (preventing echo). Created once during server initialization and shared by all audio render threads.
THREAD SAFETY: The mixer itself is thread-safe and can be used concurrently by multiple render.c audio threads without external synchronization. During shutdown, set to NULL before destroying to prevent use-after-free.
Definition at line 173 of file server/main.c.
Referenced by add_client(), add_webrtc_client(), client_audio_render_thread(), remove_client(), and server_main().
g_client_manager
client_manager_t g_client_manager extern
Global client manager.
Registry for all connected clients. Used to track client state, routing, and lifecycle management across server threads.
Global client manager.
This is the primary data structure for managing all connected clients. It serves as the bridge between main.c's connection accept loop and the per-client threading architecture.
STRUCTURE COMPONENTS:
clients[]: Array backing storage for client_info_t structs
client_hashtable: O(1) lookup table for client_id -> client_info_t*
client_count: Current number of active clients
mutex: Legacy mutex (mostly replaced by rwlock)
next_client_id: Monotonic counter for unique client identification
THREAD SAFETY: Protected by g_client_manager_rwlock for concurrent access
Definition at line 333 of file src/server/client.c.
Referenced by add_client(), add_webrtc_client(), any_clients_sending_video(), broadcast_server_state_to_all_clients(), find_client_by_id(), find_client_by_socket(), remove_client(), send_server_state_to_client(), server_main(), stats_logger_thread(), and update_server_stats().
g_client_manager_rwlock
rwlock_t g_client_manager_rwlock extern
Read-write lock protecting client manager.
Protects concurrent access to g_client_manager from server threads. Use rwlock_rdlock() for reads, rwlock_wrlock() for writes.
Read-write lock protecting client manager.
This lock enables high-performance concurrent access patterns:
Multiple threads can read client data simultaneously (stats, rendering)
Only one thread can modify client data at a time (add/remove operations)
Eliminates contention between read-heavy operations
USAGE PATTERN:
Read operations: rwlock_rdlock() for client lookups, stats gathering
Write operations: rwlock_wrlock() for add_client(), remove_client()
Always acquire THIS lock before per-client mutexes (lock ordering)
Definition at line 348 of file src/server/client.c.
{0};
Referenced by add_client(), add_webrtc_client(), broadcast_server_state_to_all_clients(), find_client_by_id(), find_client_by_socket(), remove_client(), server_main(), stats_logger_thread(), and update_server_stats().
g_client_whitelist
public_key_t g_client_whitelist[MAX_CLIENTS] extern
Whitelist of allowed client public keys.
Array of allowed client Ed25519 public keys for authentication. Size is limited by MAX_CLIENTS.
Whitelist of allowed client public keys.
Array of public keys for clients that are authorized to connect to the server. Used for client authentication when whitelist mode is enabled. Sized to hold up to MAX_CLIENTS entries.
Note
Only used when client authentication is enabled
Accessed from crypto.c for client authentication
Definition at line 523 of file server/main.c.
{0};
Referenced by server_crypto_handshake(), and server_main().
g_h265_server
h265_server_context_t* volatile g_h265_server extern
Global H.265 codec server context.
Shared H.265 decoding context used by all packet handlers to decode client H.265 frames. Each client gets its own decoder instance.
Shared H.265 decoding context used by all packet handlers to decode client H.265 frames. Each client gets its own decoder instance.
THREAD SAFETY: The h265_server context is thread-safe and can be used concurrently by multiple client handlers. Decoders are per-client. During shutdown, set to NULL before destroying to prevent use-after-free.
Definition at line 185 of file server/main.c.
Referenced by handle_image_frame_h265_packet(), and server_main().
g_num_server_identity_keys
size_t g_num_server_identity_keys extern
Number of server identity keys in use.
Tracks how many keys in g_server_identity_keys are valid.
Number of server identity keys in use.
Tracks how many identity keys were successfully loaded from –key flags. Zero means server is running in simple mode (no identity key).
Definition at line 510 of file server/main.c.
Referenced by server_crypto_handshake().
g_num_whitelisted_clients
size_t g_num_whitelisted_clients extern
Number of whitelisted clients.
Tracks how many keys in g_client_whitelist are valid.
Tracks the current number of entries in g_client_whitelist that are valid and active. Used to iterate the whitelist and check authorization.
Definition at line 533 of file server/main.c.
Referenced by server_crypto_handshake(), and server_main().
g_rate_limiter
rate_limiter_t* g_rate_limiter extern
Global connection rate limiter.
Shared rate limiter instance used by packet handlers to prevent DoS attacks. Tracks connection attempts and packet rates per IP address.
Global connection rate limiter.
In-memory rate limiter to prevent connection flooding and DoS attacks. Tracks connection attempts and packet rates per IP address with configurable limits.
Default limits (from rate_limit.c):
RATE_EVENT_CONNECTION: 50 connections per 60 seconds
RATE_EVENT_IMAGE_FRAME: 144 FPS (8640 frames/min)
RATE_EVENT_AUDIO: 172 FPS (10320 packets/min)
RATE_EVENT_PING: 2 Hz (120 pings/min)
RATE_EVENT_CLIENT_JOIN: 10 joins per 60 seconds
RATE_EVENT_CONTROL: 100 control packets per 60 seconds
THREAD SAFETY: The rate limiter is thread-safe and can be used concurrently from the main accept loop and packet handlers without external synchronization.
See also
main.h for extern declaration
Definition at line 215 of file server/main.c.
Referenced by process_decrypted_packet(), and server_main().
g_server_encryption_enabled
bool g_server_encryption_enabled extern
Server encryption enabled flag.
Indicates whether end-to-end encryption is enabled for this server.
Server encryption enabled flag.
Set to true when the server is configured to use encryption and has successfully loaded a private key. Controls whether the server performs cryptographic handshakes with clients.
Note
Accessed from crypto.c for server-side crypto operations
Definition at line 474 of file server/main.c.
Referenced by server_crypto_handshake(), and server_main().
g_server_identity_keys
private_key_t g_server_identity_keys[MAX_IDENTITY_KEYS] extern
Array of server identity keys.
Additional server identity keys for multi-key support. Size is limited by MAX_IDENTITY_KEYS.
Array of server identity keys.
Stores all server identity keys loaded from multiple –key flags. Enables servers to present different keys (SSH, GPG) based on client expectations. Server selects the appropriate key during handshake based on what the client downloaded from ACDS.
Note
g_server_private_key points to g_server_identity_keys[0] for compatibility
Definition at line 500 of file server/main.c.
{0};
Referenced by server_crypto_handshake().
g_server_private_key
private_key_t g_server_private_key extern
Server's private key.
Server's Ed25519 private key used for digital signatures and key exchange.
Server's private key.
Stores the server's primary private key loaded from the first –key flag. Used for cryptographic handshakes and packet encryption/decryption. Initialized during server startup from the configured key file path.
Note
This is an alias to g_server_identity_keys[0] for backward compatibility
Accessed from crypto.c for server-side crypto operations
Definition at line 487 of file server/main.c.
{0};
Referenced by server_crypto_handshake(), and server_main().
g_should_exit
atomic_t g_should_exit extern
Global application exit flag (shared across all modes).
Set by signal handlers to request graceful shutdown. Used by all server threads to check if they should exit their loops.
Global shutdown flag referenced by lib/logging.c and lib/debug/lock.c In production builds, this is defined in main.c and set during shutdown. For tests, we stub it out as false (tests don't perform shutdown).
Definition at line 34 of file globals.c.
{0};