ascii-chat: server.h File Reference
server.h File Reference
Server-side H.265 decoding pipeline for multi-client streams.
Typedefs
typedef struct h265_server_client h265_server_client_t
Functions
h265_server_context_t * h265_server_context_create (void)
void h265_server_context_destroy (h265_server_context_t *ctx)
h265_server_client_t * h265_server_get_client_decoder (h265_server_context_t *ctx, uint32_t client_id)
asciichat_error_t h265_server_decode_and_convert (h265_server_client_t *client, const uint8_t *h265_packet, size_t packet_size, uint8_t *output_rgba, uint16_t *output_width, uint16_t *output_height, size_t *output_size)
void h265_server_remove_client (h265_server_context_t *ctx, uint32_t client_id)
void h265_server_client_get_stats (h265_server_client_t *client, uint64_t *total_frames, uint64_t *keyframes, uint16_t *last_width, uint16_t *last_height)
Detailed Description
Server-side H.265 decoding pipeline for multi-client streams.
The server maintains a separate H.265 decoder for each connected client. When a client sends an H.265-encoded frame, the server:
Identifies the decoder for that client
Decodes the H.265 frame to ASCII art
Converts ASCII art to RGBA pixels for compositing
Adds the RGBA frame to the compositing pipeline
Definition in file session/h265/server.h.
Typedef Documentation
h265_server_client_t
typedef struct h265_server_client h265_server_client_t
Definition at line 20 of file session/h265/server.h.
Function Documentation
h265_server_client_get_stats()
void h265_server_client_get_stats (h265_server_client_t * client, uint64_t * total_frames, uint64_t * keyframes, uint16_t * last_width, uint16_t * last_height)
Get statistics for a client's decoder
Parameters
client Client decoder
total_frames Output: total frames decoded
keyframes Output: total keyframes decoded
last_width Output: width of last decoded frame
last_height Output: height of last decoded frame
Definition at line 167 of file src/session/h265/server.c.
  {
    if (!client) return;
    h265_client_decoder_t *client_dec = (h265_client_decoder_t *)client;
    if (!client_dec->decoder) return;
    h265_decoder_get_stats(client_dec->decoder, total_frames, keyframes, last_width, last_height);
}
References h265_client_decoder_t::decoder, and h265_decoder_get_stats().
h265_server_context_create()
h265_server_context_t * h265_server_context_create (void)
Create a server-side H.265 decoding context Manages decoders for all connected clients
Returns
Context handle, or NULL on error
Definition at line 27 of file src/session/h265/server.c.
{
    h265_server_context_t *ctx = SAFE_CALLOC(1, sizeof(h265_server_context_t), h265_server_context_t *);
    if (!ctx) {
        SET_ERRNO(ERROR_MEMORY, "Failed to allocate server context");
        return NULL;
    }
    for (int i = 0; i < MAX_CLIENTS; i++) {
        ctx->clients[i].in_use = false;
    }
    ctx->active_client_count = 0;
    log_info("H.265 server context created (max %d clients)", MAX_CLIENTS);
    return ctx;
}
References h265_server_context::active_client_count, h265_server_context::clients, and h265_client_decoder_t::in_use.
Referenced by server_main().
h265_server_context_destroy()
void h265_server_context_destroy (h265_server_context_t * ctx)
Destroy the server context and all client decoders
Parameters
ctx Context to destroy (may be NULL)
Definition at line 43 of file src/session/h265/server.c.
{
    if (!ctx) return;
    for (int i = 0; i < MAX_CLIENTS; i++) {
        if (ctx->clients[i].in_use && ctx->clients[i].decoder) {
            h265_decoder_destroy(ctx->clients[i].decoder);
        }
    }
    SAFE_FREE(ctx);
}
References h265_server_context::clients, h265_client_decoder_t::decoder, h265_decoder_destroy(), and h265_client_decoder_t::in_use.
Referenced by server_main().
h265_server_decode_and_convert()
asciichat_error_t h265_server_decode_and_convert (h265_server_client_t * client, const uint8_t * h265_packet, size_t packet_size, uint8_t * output_rgba, uint16_t * output_width, uint16_t * output_height, size_t * output_size)
Decode an H.265 frame from a client and convert to RGBA
Parameters
client Client decoder handle
h265_packet H.265 encoded packet data (with header)
packet_size Size of packet
output_rgba Output buffer for RGBA pixel data
output_width Output: frame width in pixels
output_height Output: frame height in pixels
output_size Input: buffer size, Output: actual RGBA size (width*height*4)
Returns
Error code (ASCIICHAT_OK on success)
RGBA conversion: Each ASCII character (0-255) becomes a grayscale pixel where pixel = (ascii_val, ascii_val, ascii_val, 255)
Definition at line 93 of file src/session/h265/server.c.
  {
    if (!client || !h265_packet || !output_rgba || !output_width || !output_height || !output_size) {
        return SET_ERRNO(ERROR_INTERNAL, "Invalid arguments to decode_and_convert");
    }
    h265_client_decoder_t *client_dec = (h265_client_decoder_t *)client;
    if (!client_dec->decoder || !client_dec->in_use) {
        return SET_ERRNO(ERROR_INTERNAL, "Invalid client decoder state");
    }
    uint8_t ascii_buf[256 * 64];
    size_t ascii_size = sizeof(ascii_buf);
    asciichat_error_t result = h265_decode(
        client_dec->decoder,
        h265_packet,
        packet_size,
        output_width,
        output_height,
        ascii_buf,
        &ascii_size
    );
    if (result != ASCIICHAT_OK) {
        return result;
    }
    size_t required_rgba_size = (size_t)(*output_width) * (*output_height) * 4;
    if (*output_size < required_rgba_size) {
        *output_size = required_rgba_size;
        return SET_ERRNO(ERROR_NETWORK_SIZE, "Output buffer too small: need %zu, have %zu",
                        required_rgba_size, *output_size);
    }
    for (size_t i = 0; i < ascii_size && i < (size_t)(*output_width) * (*output_height); i++) {
        uint8_t val = ascii_buf[i];
        output_rgba[i * 4 + 0] = val;
        output_rgba[i * 4 + 1] = val;
        output_rgba[i * 4 + 2] = val;
        output_rgba[i * 4 + 3] = 255;
    }
    *output_size = required_rgba_size;
    client_dec->last_width = *output_width;
    client_dec->last_height = *output_height;
    return ASCIICHAT_OK;
}
References h265_client_decoder_t::decoder, h265_decode(), h265_client_decoder_t::in_use, h265_client_decoder_t::last_height, and h265_client_decoder_t::last_width.
Referenced by handle_image_frame_h265_packet().
h265_server_get_client_decoder()
h265_server_client_t * h265_server_get_client_decoder (h265_server_context_t * ctx, uint32_t client_id)
Get or create a client decoder within the server context Each client gets its own H.265 decoder instance
Parameters
ctx Server context
client_id Unique client identifier
Returns
Client decoder handle, or NULL on error
Definition at line 54 of file src/session/h265/server.c.
  {
    if (!ctx) {
        SET_ERRNO(ERROR_INTERNAL, "Invalid server context");
        return NULL;
    }
    for (int i = 0; i < MAX_CLIENTS; i++) {
        if (ctx->clients[i].in_use && ctx->clients[i].client_id == client_id) {
            return (h265_server_client_t *)&ctx->clients[i];
        }
    }
    for (int i = 0; i < MAX_CLIENTS; i++) {
        if (!ctx->clients[i].in_use) {
            h265_decoder_t *decoder = h265_decoder_create();
            if (!decoder) {
                SET_ERRNO(ERROR_MEDIA_INIT, "Failed to create decoder for client %u", client_id);
                return NULL;
            }
            ctx->clients[i].client_id = client_id;
            ctx->clients[i].decoder = decoder;
            ctx->clients[i].in_use = true;
            ctx->clients[i].last_width = 0;
            ctx->clients[i].last_height = 0;
            ctx->active_client_count++;
            log_debug("Created H.265 decoder for client %u", client_id);
            return (h265_server_client_t *)&ctx->clients[i];
        }
    }
    SET_ERRNO(ERROR_INTERNAL, "No free decoder slots (max %d clients)", MAX_CLIENTS);
    return NULL;
}
References h265_server_context::active_client_count, h265_client_decoder_t::client_id, h265_server_context::clients, h265_client_decoder_t::decoder, h265_decoder_create(), h265_client_decoder_t::in_use, h265_client_decoder_t::last_height, and h265_client_decoder_t::last_width.
Referenced by handle_image_frame_h265_packet().
h265_server_remove_client()
void h265_server_remove_client (h265_server_context_t * ctx, uint32_t client_id)
Remove a client decoder (when client disconnects)
Parameters
ctx Server context
client_id Client identifier
Definition at line 150 of file src/session/h265/server.c.
{
    if (!ctx) return;
    for (int i = 0; i < MAX_CLIENTS; i++) {
        if (ctx->clients[i].in_use && ctx->clients[i].client_id == client_id) {
            if (ctx->clients[i].decoder) {
                h265_decoder_destroy(ctx->clients[i].decoder);
                ctx->clients[i].decoder = NULL;
            }
            ctx->clients[i].in_use = false;
            ctx->active_client_count--;
            log_debug("Removed H.265 decoder for client %u", client_id);
            return;
        }
    }
}
References h265_server_context::active_client_count, h265_client_decoder_t::client_id, h265_server_context::clients, h265_client_decoder_t::decoder, h265_decoder_destroy(), and h265_client_decoder_t::in_use.