ascii-chat: sgr.c File Reference
sgr.c File Reference
Data Structures
struct sgr256_seq_t
Pre-computed 256-color ANSI SGR sequence.
Macros
#define BGASCII_LUMA_THRESHOLD 128
#define CUBE_GRAY_THRESHOLD 10
Functions
void prewarm_sgr256_fg_cache (void)
void prewarm_sgr256_cache (void)
char * get_sgr256_fg_string (uint8_t fg, uint8_t *len_out)
char * get_sgr256_bg_string (uint8_t bg, uint8_t *len_out)
char * get_sgr256_fg_bg_string (uint8_t fg, uint8_t bg, uint8_t *len_out)
char * append_sgr_reset (char *dst)
char * append_sgr_truecolor_fg (char *dst, uint8_t r, uint8_t g, uint8_t b)
char * append_sgr_truecolor_bg (char *dst, uint8_t r, uint8_t g, uint8_t b)
char * append_sgr_truecolor_fg_bg (char *dst, uint8_t fr, uint8_t fg, uint8_t fb, uint8_t br, uint8_t bg, uint8_t bb)
char * image_print_color_simd (image_t *image, bool use_background_mode, bool use_256color, const char *ascii_chars)
Macro Definition Documentation
BGASCII_LUMA_THRESHOLD
#define BGASCII_LUMA_THRESHOLD 128
Definition at line 34 of file sgr.c.
CUBE_GRAY_THRESHOLD
#define CUBE_GRAY_THRESHOLD 10
Definition at line 38 of file sgr.c.
Function Documentation
append_sgr_reset()
char * append_sgr_reset (char * dst) inline
Definition at line 155 of file sgr.c.
{
  // "\x1b[0m"
  static const char RESET[] = "\033[0m";
  memcpy(dst, RESET, sizeof(RESET) - 1);
  return dst + (sizeof(RESET) - 1);
}
append_sgr_truecolor_bg()
char * append_sgr_truecolor_bg (char * dst, uint8_t r, uint8_t g, uint8_t b) inline
Definition at line 224 of file sgr.c.
{
  // Constructor ensures initialization
  // Direct character writes for "\033[48;2;"
  *dst++ = '\033';
  *dst++ = '[';
  *dst++ = '4';
  *dst++ = '8';
  *dst++ = ';';
  *dst++ = '2';
  *dst++ = ';';
  // Optimized digit copying
  const dec3_t *rd = &g_dec3_cache.dec3_table[r];
  if (rd->len == 1) {
    *dst++ = rd->s[0];
  } else if (rd->len == 2) {
    dst[0] = rd->s[0];
    dst[1] = rd->s[1];
    dst += 2;
  } else {
    dst[0] = rd->s[0];
    dst[1] = rd->s[1];
    dst[2] = rd->s[2];
    dst += 3;
  }
  *dst++ = ';';
  const dec3_t *gd = &g_dec3_cache.dec3_table[g];
  if (gd->len == 1) {
    *dst++ = gd->s[0];
  } else if (gd->len == 2) {
    dst[0] = gd->s[0];
    dst[1] = gd->s[1];
    dst += 2;
  } else {
    dst[0] = gd->s[0];
    dst[1] = gd->s[1];
    dst[2] = gd->s[2];
    dst += 3;
  }
  *dst++ = ';';
  const dec3_t *bd = &g_dec3_cache.dec3_table[b];
  if (bd->len == 1) {
    *dst++ = bd->s[0];
  } else if (bd->len == 2) {
    dst[0] = bd->s[0];
    dst[1] = bd->s[1];
    dst += 2;
  } else {
    dst[0] = bd->s[0];
    dst[1] = bd->s[1];
    dst[2] = bd->s[2];
    dst += 3;
  }
  *dst++ = 'm';
  return dst;
}
References g_dec3_cache.
append_sgr_truecolor_fg()
char * append_sgr_truecolor_fg (char * dst, uint8_t r, uint8_t g, uint8_t b) inline
Definition at line 163 of file sgr.c.
{
  // Constructor ensures initialization
  // Direct character writes (compiler will optimize to word operations)
  *dst++ = '\033';
  *dst++ = '[';
  *dst++ = '3';
  *dst++ = '8';
  *dst++ = ';';
  *dst++ = '2';
  *dst++ = ';';
  // Fast digit copying for 1-3 digit numbers (avoid memcpy overhead)
  const dec3_t *rd = &g_dec3_cache.dec3_table[r];
  if (rd->len == 1) {
    *dst++ = rd->s[0];
  } else if (rd->len == 2) {
    dst[0] = rd->s[0];
    dst[1] = rd->s[1];
    dst += 2;
  } else {
    dst[0] = rd->s[0];
    dst[1] = rd->s[1];
    dst[2] = rd->s[2];
    dst += 3;
  }
  *dst++ = ';';
  const dec3_t *gd = &g_dec3_cache.dec3_table[g];
  if (gd->len == 1) {
    *dst++ = gd->s[0];
  } else if (gd->len == 2) {
    dst[0] = gd->s[0];
    dst[1] = gd->s[1];
    dst += 2;
  } else {
    dst[0] = gd->s[0];
    dst[1] = gd->s[1];
    dst[2] = gd->s[2];
    dst += 3;
  }
  *dst++ = ';';
  const dec3_t *bd = &g_dec3_cache.dec3_table[b];
  if (bd->len == 1) {
    *dst++ = bd->s[0];
  } else if (bd->len == 2) {
    dst[0] = bd->s[0];
    dst[1] = bd->s[1];
    dst += 2;
  } else {
    dst[0] = bd->s[0];
    dst[1] = bd->s[1];
    dst[2] = bd->s[2];
    dst += 3;
  }
  *dst++ = 'm';
  return dst;
}
References g_dec3_cache.
append_sgr_truecolor_fg_bg()
char * append_sgr_truecolor_fg_bg (char * dst, uint8_t fr, uint8_t fg, uint8_t fb, uint8_t br, uint8_t bg, uint8_t bb) inline
Definition at line 285 of file sgr.c.
{
  // Constructor ensures initialization
  // Write "\033[38;2;" directly (7 chars)
  *dst++ = '\033';
  *dst++ = '[';
  *dst++ = '3';
  *dst++ = '8';
  *dst++ = ';';
  *dst++ = '2';
  *dst++ = ';';
  // Foreground RGB digits
  const dec3_t *d = &g_dec3_cache.dec3_table[fr];
  if (d->len == 1) {
    *dst++ = d->s[0];
  } else if (d->len == 2) {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst += 2;
  } else {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst[2] = d->s[2];
    dst += 3;
  }
  *dst++ = ';';
  d = &g_dec3_cache.dec3_table[fg];
  if (d->len == 1) {
    *dst++ = d->s[0];
  } else if (d->len == 2) {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst += 2;
  } else {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst[2] = d->s[2];
    dst += 3;
  }
  *dst++ = ';';
  d = &g_dec3_cache.dec3_table[fb];
  if (d->len == 1) {
    *dst++ = d->s[0];
  } else if (d->len == 2) {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst += 2;
  } else {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst[2] = d->s[2];
    dst += 3;
  }
  // Write ";48;2;" directly (6 chars)
  *dst++ = ';';
  *dst++ = '4';
  *dst++ = '8';
  *dst++ = ';';
  *dst++ = '2';
  *dst++ = ';';
  // Background RGB digits
  d = &g_dec3_cache.dec3_table[br];
  if (d->len == 1) {
    *dst++ = d->s[0];
  } else if (d->len == 2) {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst += 2;
  } else {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst[2] = d->s[2];
    dst += 3;
  }
  *dst++ = ';';
  d = &g_dec3_cache.dec3_table[bg];
  if (d->len == 1) {
    *dst++ = d->s[0];
  } else if (d->len == 2) {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst += 2;
  } else {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst[2] = d->s[2];
    dst += 3;
  }
  *dst++ = ';';
  d = &g_dec3_cache.dec3_table[bb];
  if (d->len == 1) {
    *dst++ = d->s[0];
  } else if (d->len == 2) {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst += 2;
  } else {
    dst[0] = d->s[0];
    dst[1] = d->s[1];
    dst[2] = d->s[2];
    dst += 3;
  }
  *dst++ = 'm';
  return dst;
}
References g_dec3_cache.
get_sgr256_bg_string()
char * get_sgr256_bg_string (uint8_t bg, uint8_t * len_out)
Definition at line 141 of file sgr.c.
{
  if (!sgr256_cache_initialized) {
    init_sgr256_cache();
  }
  *len_out = sgr256_bg_cache[bg].len;
  return sgr256_bg_cache[bg].seq;
}
Referenced by emit_set_256_color_bg().
get_sgr256_fg_bg_string()
char * get_sgr256_fg_bg_string (uint8_t fg, uint8_t bg, uint8_t * len_out)
Definition at line 149 of file sgr.c.
{
  // For FG+BG, still build on-demand since we'd need 256*256 cache
  static __thread char buf[32];
  return build_sgr256_fgbg(buf, fg, bg, len_out);
}
get_sgr256_fg_string()
char * get_sgr256_fg_string (uint8_t fg, uint8_t * len_out)
Definition at line 133 of file sgr.c.
{
  if (!sgr256_cache_initialized) {
    init_sgr256_cache();
  }
  *len_out = sgr256_fg_cache[fg].len;
  return sgr256_fg_cache[fg].seq;
}
Referenced by emit_set_256_color_fg().
image_print_color_simd()
char * image_print_color_simd (image_t * image, bool use_background_mode, bool use_256color, const char * ascii_chars)
Definition at line 412 of file sgr.c.
{
  if (!image || !ascii_chars) {
    return NULL;
  }
  log_dev_every(4500 * US_PER_MS_INT, "image_print_color_simd called: width=%d, height=%d, use_256color=%d",
                image->w, image->h, use_256color);
#if SIMD_SUPPORT_AVX2
  log_debug_every(10 * US_PER_SEC_INT, "Taking AVX2 path: width=%d, height=%d", image->w, image->h);
  // AVX2 implementation would go here
  // For now, fall through to scalar implementation
#endif
  // Fallback to scalar implementation
  if (use_background_mode) {
    return image_print_16color_dithered_with_background(image, use_background_mode, ascii_chars);
  } else if (use_256color) {
    return image_print_256color(image, ascii_chars);
  } else {
    return image_print_color(image, ascii_chars);
  }
}
References image_print_16color_dithered_with_background(), image_print_256color(), and image_print_color().
Referenced by ascii_convert(), and image_print_256color().
prewarm_sgr256_cache()
void prewarm_sgr256_cache (void)
Definition at line 128 of file sgr.c.
{
  init_sgr256_cache();
}
prewarm_sgr256_fg_cache()
void prewarm_sgr256_fg_cache (void)
Definition at line 124 of file sgr.c.
{
  init_sgr256_cache();
}