ascii-chat: sha1.c File Reference
sha1.c File Reference
Macros
#define SHA1HANDSOFF
#define BYTE_ORDER 1234
#define LITTLE_ENDIAN 1234
#define BIG_ENDIAN 4321
#define rol(value, bits)
#define blk0(i)
#define blk(i)
#define R0(v, w, x, y, z, i)
#define R1(v, w, x, y, z, i)
#define R2(v, w, x, y, z, i)
#define R3(v, w, x, y, z, i)
#define R4(v, w, x, y, z, i)
Functions
void SHA1Transform (uint32_t state[5], const unsigned char buffer[SHA1_BLOCK_LENGTH])
void SHA1Init (SHA1_CTX *context)
void SHA1Update (SHA1_CTX *context, const void *dataptr, unsigned int len)
void SHA1Final (unsigned char digest[SHA1_DIGEST_LENGTH], SHA1_CTX *context)
Macro Definition Documentation
BIG_ENDIAN
#define BIG_ENDIAN 4321
Definition at line 34 of file sha1.c.
blk
#define blk (i)
Value:
(block->l[i & 15] =                                                                                                  \
     rol(block->l[(i + 13) & 15] ^ block->l[(i + 8) & 15] ^ block->l[(i + 2) & 15] ^ block->l[i & 15], 1))
Definition at line 47 of file sha1.c.
#define blk(i)                                                                                                         \
  (block->l[i & 15] =                                                                                                  \
       rol(block->l[(i + 13) & 15] ^ block->l[(i + 8) & 15] ^ block->l[(i + 2) & 15] ^ block->l[i & 15], 1))
blk0
#define blk0 (i)
Value:
(block->l[i] = (rol(block->l[i], 24) & 0xFF00FF00) | (rol(block->l[i], 8) & 0x00FF00FF))
Definition at line 43 of file sha1.c.
BYTE_ORDER
#define BYTE_ORDER 1234
Definition at line 32 of file sha1.c.
LITTLE_ENDIAN
#define LITTLE_ENDIAN 1234
Definition at line 33 of file sha1.c.
R0
#define R0 (v, w, x, y, z, i)
Value:
z += ((w & (x ^ y)) ^ y) + blk0(i) + 0x5A827999 + rol(v, 5);                                                         \
w = rol(w, 30);
Definition at line 52 of file sha1.c.
#define R0(v, w, x, y, z, i)                                                                                           \
  z += ((w & (x ^ y)) ^ y) + blk0(i) + 0x5A827999 + rol(v, 5);                                                         \
  w = rol(w, 30);
Referenced by SHA1Transform().
R1
#define R1 (v, w, x, y, z, i)
Value:
z += ((w & (x ^ y)) ^ y) + blk(i) + 0x5A827999 + rol(v, 5);                                                          \
w = rol(w, 30);
Definition at line 55 of file sha1.c.
#define R1(v, w, x, y, z, i)                                                                                           \
  z += ((w & (x ^ y)) ^ y) + blk(i) + 0x5A827999 + rol(v, 5);                                                          \
  w = rol(w, 30);
Referenced by SHA1Transform().
R2
#define R2 (v, w, x, y, z, i)
Value:
z += (w ^ x ^ y) + blk(i) + 0x6ED9EBA1 + rol(v, 5);                                                                  \
w = rol(w, 30);
Definition at line 58 of file sha1.c.
#define R2(v, w, x, y, z, i)                                                                                           \
  z += (w ^ x ^ y) + blk(i) + 0x6ED9EBA1 + rol(v, 5);                                                                  \
  w = rol(w, 30);
Referenced by SHA1Transform().
R3
#define R3 (v, w, x, y, z, i)
Value:
z += (((w | x) & y) | (w & x)) + blk(i) + 0x8F1BBCDC + rol(v, 5);                                                    \
w = rol(w, 30);
Definition at line 61 of file sha1.c.
#define R3(v, w, x, y, z, i)                                                                                           \
  z += (((w | x) & y) | (w & x)) + blk(i) + 0x8F1BBCDC + rol(v, 5);                                                    \
  w = rol(w, 30);
Referenced by SHA1Transform().
R4
#define R4 (v, w, x, y, z, i)
Value:
z += (w ^ x ^ y) + blk(i) + 0xCA62C1D6 + rol(v, 5);                                                                  \
w = rol(w, 30);
Definition at line 64 of file sha1.c.
#define R4(v, w, x, y, z, i)                                                                                           \
  z += (w ^ x ^ y) + blk(i) + 0xCA62C1D6 + rol(v, 5);                                                                  \
  w = rol(w, 30);
Referenced by SHA1Transform().
rol
#define rol (value, bits)
Value:
(((value) << (bits)) | ((value) >> (32 - (bits))))
Definition at line 38 of file sha1.c.
SHA1HANDSOFF
#define SHA1HANDSOFF
Definition at line 20 of file sha1.c.
Function Documentation
SHA1Final()
void SHA1Final (unsigned char digest[SHA1_DIGEST_LENGTH], SHA1_CTX * context)
Definition at line 219 of file sha1.c.
{
  unsigned int i;
  unsigned char finalcount[8];
  for (i = 0; i < 8; i++) {
    finalcount[i] = (unsigned char)((context->count >> ((7 - (i & 7)) * 8)) & 255); /* Endian independent */
  }
  SHA1Update(context, "\200", 1);
  while ((context->count & 504) != 448) {
    SHA1Update(context, "\0", 1);
  }
  SHA1Update(context, finalcount, 8); /* Should cause a SHA1Transform() */
  for (i = 0; i < SHA1_DIGEST_LENGTH; i++) {
    digest[i] = (unsigned char)((context->state[i >> 2] >> ((3 - (i & 3)) * 8)) & 255);
  }
  memset(&finalcount, 0, sizeof(finalcount));
  memset(context, 0, sizeof(*context));
}
References SHA1Update().
SHA1Init()
void SHA1Init (SHA1_CTX * context)
Definition at line 186 of file sha1.c.
{
  /* SHA1 initialization constants */
  context->count = 0;
  context->state[0] = 0x67452301;
  context->state[1] = 0xEFCDAB89;
  context->state[2] = 0x98BADCFE;
  context->state[3] = 0x10325476;
  context->state[4] = 0xC3D2E1F0;
}
SHA1Transform()
void SHA1Transform (uint32_t state[5], const unsigned char buffer[SHA1_BLOCK_LENGTH])
Definition at line 70 of file sha1.c.
{
  uint32_t a, b, c, d, e;
  typedef union {
    unsigned char c[64];
    uint32_t l[16];
  } CHAR64LONG16;
  CHAR64LONG16 *block;
#ifdef SHA1HANDSOFF
  unsigned char workspace[SHA1_BLOCK_LENGTH];
  block = (CHAR64LONG16 *)workspace;
  memcpy(block, buffer, SHA1_BLOCK_LENGTH);
#else
  block = (CHAR64LONG16 *)buffer;
#endif
  /* Copy context->state[] to working vars */
  a = state[0];
  b = state[1];
  c = state[2];
  d = state[3];
  e = state[4];
  /* 4 rounds of 20 operations each. Loop unrolled. */
  R0(a, b, c, d, e, 0);
  R0(e, a, b, c, d, 1);
  R0(d, e, a, b, c, 2);
  R0(c, d, e, a, b, 3);
  R0(b, c, d, e, a, 4);
  R0(a, b, c, d, e, 5);
  R0(e, a, b, c, d, 6);
  R0(d, e, a, b, c, 7);
  R0(c, d, e, a, b, 8);
  R0(b, c, d, e, a, 9);
  R0(a, b, c, d, e, 10);
  R0(e, a, b, c, d, 11);
  R0(d, e, a, b, c, 12);
  R0(c, d, e, a, b, 13);
  R0(b, c, d, e, a, 14);
  R0(a, b, c, d, e, 15);
  R1(e, a, b, c, d, 16);
  R1(d, e, a, b, c, 17);
  R1(c, d, e, a, b, 18);
  R1(b, c, d, e, a, 19);
  R2(a, b, c, d, e, 20);
  R2(e, a, b, c, d, 21);
  R2(d, e, a, b, c, 22);
  R2(c, d, e, a, b, 23);
  R2(b, c, d, e, a, 24);
  R2(a, b, c, d, e, 25);
  R2(e, a, b, c, d, 26);
  R2(d, e, a, b, c, 27);
  R2(c, d, e, a, b, 28);
  R2(b, c, d, e, a, 29);
  R2(a, b, c, d, e, 30);
  R2(e, a, b, c, d, 31);
  R2(d, e, a, b, c, 32);
  R2(c, d, e, a, b, 33);
  R2(b, c, d, e, a, 34);
  R2(a, b, c, d, e, 35);
  R2(e, a, b, c, d, 36);
  R2(d, e, a, b, c, 37);
  R2(c, d, e, a, b, 38);
  R2(b, c, d, e, a, 39);
  R3(a, b, c, d, e, 40);
  R3(e, a, b, c, d, 41);
  R3(d, e, a, b, c, 42);
  R3(c, d, e, a, b, 43);
  R3(b, c, d, e, a, 44);
  R3(a, b, c, d, e, 45);
  R3(e, a, b, c, d, 46);
  R3(d, e, a, b, c, 47);
  R3(c, d, e, a, b, 48);
  R3(b, c, d, e, a, 49);
  R3(a, b, c, d, e, 50);
  R3(e, a, b, c, d, 51);
  R3(d, e, a, b, c, 52);
  R3(c, d, e, a, b, 53);
  R3(b, c, d, e, a, 54);
  R3(a, b, c, d, e, 55);
  R3(e, a, b, c, d, 56);
  R3(d, e, a, b, c, 57);
  R3(c, d, e, a, b, 58);
  R3(b, c, d, e, a, 59);
  R4(a, b, c, d, e, 60);
  R4(e, a, b, c, d, 61);
  R4(d, e, a, b, c, 62);
  R4(c, d, e, a, b, 63);
  R4(b, c, d, e, a, 64);
  R4(a, b, c, d, e, 65);
  R4(e, a, b, c, d, 66);
  R4(d, e, a, b, c, 67);
  R4(c, d, e, a, b, 68);
  R4(b, c, d, e, a, 69);
  R4(a, b, c, d, e, 70);
  R4(e, a, b, c, d, 71);
  R4(d, e, a, b, c, 72);
  R4(c, d, e, a, b, 73);
  R4(b, c, d, e, a, 74);
  R4(a, b, c, d, e, 75);
  R4(e, a, b, c, d, 76);
  R4(d, e, a, b, c, 77);
  R4(c, d, e, a, b, 78);
  R4(b, c, d, e, a, 79);
  /* Add the working vars back into context.state[] */
  state[0] += a;
  state[1] += b;
  state[2] += c;
  state[3] += d;
  state[4] += e;
  /* Wipe variables */
  a = b = c = d = e = 0;
}
References R0, R1, R2, R3, and R4.
Referenced by SHA1Update().
SHA1Update()
void SHA1Update (SHA1_CTX * context, const void * dataptr, unsigned int len)
Definition at line 198 of file sha1.c.
{
  const uint8_t *data = dataptr;
  unsigned int i;
  unsigned int j;
  j = (uint32_t)((context->count >> 3) & 63);
  context->count += (len << 3);
  if ((j + len) > 63) {
    memcpy(&context->buffer[j], data, (i = 64 - j));
    SHA1Transform(context->state, context->buffer);
    for (; i + 63 < len; i += 64) {
      SHA1Transform(context->state, &data[i]);
    }
    j = 0;
  } else
    i = 0;
  memcpy(&context->buffer[j], &data[i], len - i);
}
References SHA1Transform().
Referenced by SHA1Final().