ascii-chat: signaling.c File Reference
signaling.c File Reference
Data Structures
struct find_client_context_t
Context for finding client by participant_id.
struct broadcast_context_t
Context for broadcasting to session participants.
Functions
asciichat_error_t signaling_relay_sdp (sqlite3 *db, tcp_server_t *tcp_server, const acip_webrtc_sdp_t *sdp, size_t total_packet_len)
Relay SDP offer/answer to recipient.
asciichat_error_t signaling_relay_ice (sqlite3 *db, tcp_server_t *tcp_server, const acip_webrtc_ice_t *ice, size_t total_packet_len)
Relay ICE candidate to recipient.
asciichat_error_t signaling_broadcast (sqlite3 *db, tcp_server_t *tcp_server, const uint8_t session_id[16], packet_type_t packet_type, const void *packet, size_t packet_len, const uint8_t *exclude_participant_id)
Broadcast packet to all session participants.
Function Documentation
signaling_broadcast()
asciichat_error_t signaling_broadcast (sqlite3 * db, tcp_server_t * tcp_server, const uint8_t session_id[16], packet_type_t packet_type, const void * packet, size_t packet_len, const uint8_t * exclude_participant_id)
Broadcast packet to all session participants.
Sends packet to all participants in a session (optionally excluding one). Used internally by SDP/ICE relay when recipient_id is all zeros.
Parameters
db SQLite database handle (for session validation)
tcp_server TCP server with client registry
session_id Session UUID
packet_type Packet type to send
packet Packet data to broadcast
packet_len Packet length
exclude_participant_id Participant to exclude (NULL = no exclusion, typically sender)
Returns
ASCIICHAT_OK on success, error code otherwise
Definition at line 216 of file signaling.c.
{
  if (!db || !tcp_server || !session_id || !packet) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "db, tcp_server, session_id, or packet is NULL");
  }
  /* Find session by UUID using database lookup */
  session_entry_t *session = database_session_find_by_id(db, session_id);
  if (!session) {
    return SET_ERRNO(ERROR_NETWORK_PROTOCOL, "Session not found for broadcast");
  }
  session_entry_destroy(session); // We only need to validate existence
  // Broadcast to all participants in session (excluding sender if specified)
  broadcast_context_t ctx = {.target_session_id = session_id,
                             .exclude_participant_id = exclude_participant_id,
                             .packet_type = packet_type,
                             .packet = packet,
                             .packet_len = packet_len,
                             .sent_count = 0};
  tcp_server_foreach_client(tcp_server, broadcast_callback, &ctx);
  if (ctx.sent_count == 0) {
    log_warn("Broadcast sent to 0 participants (all offline or not joined yet)");
  } else {
    log_debug("Broadcast sent to %zu participants", ctx.sent_count);
  }
  return ASCIICHAT_OK;
}
References database_session_find_by_id(), broadcast_context_t::sent_count, session_entry_destroy(), session_id, and tcp_server_foreach_client().
Referenced by signaling_relay_ice(), and signaling_relay_sdp().
signaling_relay_ice()
asciichat_error_t signaling_relay_ice (sqlite3 * db, tcp_server_t * tcp_server, const acip_webrtc_ice_t * ice, size_t total_packet_len)
Relay ICE candidate to recipient.
Relays ICE packet to specific participant or broadcasts to all participants in the session if recipient_id is all zeros.
Parameters
db SQLite database handle (for session validation)
tcp_server TCP server with client registry
ice ICE packet to relay (with variable-length candidate data following struct)
total_packet_len Total packet length including variable data
Returns
ASCIICHAT_OK on success, error code otherwise
Definition at line 174 of file signaling.c.
{
  if (!db || !tcp_server || !ice) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "db, tcp_server, or ice is NULL");
  }
  /* Find session by UUID using database lookup */
  session_entry_t *session = database_session_find_by_id(db, ice->session_id);
  if (!session) {
    return SET_ERRNO(ERROR_NETWORK_PROTOCOL, "Session not found for ICE relay");
  }
  session_entry_destroy(session); // We only need to validate existence
  // Check if broadcast (recipient_id all zeros) or unicast
  if (is_broadcast_uuid(ice->recipient_id)) {
    // Broadcast to all participants in session (except sender)
    log_debug("Broadcasting ICE candidate to all participants in session (excluding sender)");
    return signaling_broadcast(db, tcp_server, ice->session_id, PACKET_TYPE_ACIP_WEBRTC_ICE, ice, total_packet_len,
                               ice->sender_id);
  } else {
    // Unicast to specific recipient
    find_client_context_t ctx = {
        .target_participant_id = ice->recipient_id, .found_socket = INVALID_SOCKET_VALUE, .found = false};
    tcp_server_foreach_client(tcp_server, find_participant_callback, &ctx);
    if (!ctx.found) {
      return SET_ERRNO(ERROR_NETWORK_PROTOCOL, "Recipient participant not found (may be offline)");
    }
    // Send ICE packet to recipient
    int result = send_packet(ctx.found_socket, PACKET_TYPE_ACIP_WEBRTC_ICE, ice, total_packet_len);
    if (result != 0) {
      return SET_ERRNO(ERROR_NETWORK, "Failed to send ICE packet to recipient");
    }
    log_debug("Relayed ICE candidate from sender to recipient (socket=%d)", ctx.found_socket);
  }
  return ASCIICHAT_OK;
}
References database_session_find_by_id(), find_client_context_t::found, find_client_context_t::found_socket, send_packet(), session_entry_destroy(), signaling_broadcast(), and tcp_server_foreach_client().
signaling_relay_sdp()
asciichat_error_t signaling_relay_sdp (sqlite3 * db, tcp_server_t * tcp_server, const acip_webrtc_sdp_t * sdp, size_t total_packet_len)
Relay SDP offer/answer to recipient.
Relays SDP packet to specific participant or broadcasts to all participants in the session if recipient_id is all zeros.
Parameters
db SQLite database handle (for session validation)
tcp_server TCP server with client registry
sdp SDP packet to relay (with variable-length SDP data following struct)
total_packet_len Total packet length including variable data
Returns
ASCIICHAT_OK on success, error code otherwise
Definition at line 127 of file signaling.c.
{
  if (!db || !tcp_server || !sdp) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "db, tcp_server, or sdp is NULL");
  }
  /* Find session by UUID using database lookup */
  log_debug("SDP relay: Looking up session_id=%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x",
            sdp->session_id[0], sdp->session_id[1], sdp->session_id[2], sdp->session_id[3], sdp->session_id[4],
            sdp->session_id[5], sdp->session_id[6], sdp->session_id[7], sdp->session_id[8], sdp->session_id[9],
            sdp->session_id[10], sdp->session_id[11], sdp->session_id[12], sdp->session_id[13], sdp->session_id[14],
            sdp->session_id[15]);
  session_entry_t *session = database_session_find_by_id(db, sdp->session_id);
  if (!session) {
    return SET_ERRNO(ERROR_NETWORK_PROTOCOL, "Session not found for SDP relay");
  }
  session_entry_destroy(session); // We only need to validate existence
  // Check if broadcast (recipient_id all zeros) or unicast
  if (is_broadcast_uuid(sdp->recipient_id)) {
    // Broadcast to all participants in session (except sender)
    log_debug("Broadcasting SDP to all participants in session (excluding sender)");
    return signaling_broadcast(db, tcp_server, sdp->session_id, PACKET_TYPE_ACIP_WEBRTC_SDP, sdp, total_packet_len,
                               sdp->sender_id);
  } else {
    // Unicast to specific recipient
    find_client_context_t ctx = {
        .target_participant_id = sdp->recipient_id, .found_socket = INVALID_SOCKET_VALUE, .found = false};
    tcp_server_foreach_client(tcp_server, find_participant_callback, &ctx);
    if (!ctx.found) {
      return SET_ERRNO(ERROR_NETWORK_PROTOCOL, "Recipient participant not found (may be offline)");
    }
    // Send SDP packet to recipient
    int result = send_packet(ctx.found_socket, PACKET_TYPE_ACIP_WEBRTC_SDP, sdp, total_packet_len);
    if (result != 0) {
      return SET_ERRNO(ERROR_NETWORK, "Failed to send SDP packet to recipient");
    }
    log_debug("Relayed SDP from sender to recipient (socket=%d)", ctx.found_socket);
  }
  return ASCIICHAT_OK;
}
References database_session_find_by_id(), find_client_context_t::found, find_client_context_t::found_socket, send_packet(), session_entry_destroy(), signaling_broadcast(), and tcp_server_foreach_client().