ascii-chat: splash.c File Reference
splash.c File Reference
Session
Intro and status screen display implementation with animated rainbow effects.
Data Structures
struct splash_header_ctx_t
Context data for splash header rendering.
Macros
#define ASCII_LOGO_LINES 7
#define ASCII_LOGO_WIDTH 36
#define RAINBOW_COLOR_COUNT 7
Functions
void splash_log_init (void)
void splash_log_destroy (void)
void splash_log_clear (void)
bool splash_should_display (bool is_intro)
int splash_intro_start (session_display_ctx_t *ctx)
int splash_intro_done (void)
void splash_restore_stderr (void)
void splash_clear_display_context (void)
bool splash_is_running (void)
void splash_wait_for_animation (void)
void splash_set_update_notification (const char *notification)
Detailed Description
Intro and status screen display implementation with animated rainbow effects.
Implements splash screen functionality including:
TTY detection with stdin/stdout checks
Animated rainbow color generation and cycling
UTF-8 box drawing character support with ASCII fallback
Non-blocking animation that runs while app initializes
Clean integration with main frame rendering
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
February 2026
Definition in file splash.c.
Macro Definition Documentation
ASCII_LOGO_LINES
#define ASCII_LOGO_LINES 7
Definition at line 53 of file splash.c.
ASCII_LOGO_WIDTH
#define ASCII_LOGO_WIDTH 36
Definition at line 54 of file splash.c.
RAINBOW_COLOR_COUNT
#define RAINBOW_COLOR_COUNT 7
Definition at line 70 of file splash.c.
Function Documentation
splash_clear_display_context()
void splash_clear_display_context (void)
Definition at line 719 of file splash.c.
{
  // No-op: display context is no longer cached
}
Referenced by session_display_destroy().
splash_intro_done()
int splash_intro_done (void)
Definition at line 691 of file splash.c.
{
  // Record when intro_done was called - animation thread will use this to decide when to stop
  // Animation thread needs time to check the flag and perform cleanup, so this must happen
  // BEFORE we try to access the terminal for frame rendering
  atomic_store_u64(&g_splash_state.intro_done_time_ns, time_get_ns());
  // NOTE: Do NOT modify thread_created flag here!
  // splash_wait_for_animation() needs to see thread_created==true to know whether to join the thread.
  // If we set thread_created=false here, splash_wait_for_animation() won't join, and the render loop
  // will start while the animation thread is still running, causing frame output to conflict with splash.
  //
  // Instead, just signal the animation thread to stop via intro_done_time_ns, and let
  // splash_wait_for_animation() handle the actual thread join.
  // NOTE: DO NOT set is_running = false here! The animation thread sets it to false
  // when it actually exits (line 633). If we set it to false here, the render loop
  // guard will think splash is done while the animation thread is still running for
  // up to 2 more seconds, allowing ASCII frames to render simultaneously with splash.
  // The is_running flag MUST only be cleared by the animation thread when it finishes.
  return 0;
}
References atomic_store_u64(), and time_get_ns().
Referenced by display_disable_logging_for_first_frame(), session_client_like_run(), and session_display_write_ascii().
splash_intro_start()
int splash_intro_start (session_display_ctx_t * ctx)
Definition at line 638 of file splash.c.
{
  (void)ctx; // Not needed - display context is not actively used
  // Check if splash should display
  if (!splash_should_display(true)) {
    return 0;
  }
  // Check terminal size
  int width = (int)terminal_get_effective_width();
  int height = (int)terminal_get_effective_height();
  if (width < 50 || height < 20) {
    return 0;
  }
  // Redirect splash screen to stderr when stdout is piped (not a TTY)
  // This keeps stdout clean for frame data while splash goes to stderr
  if (!isatty(STDOUT_FILENO)) {
    terminal_screen_set_output_fd(STDERR_FILENO);
  }
  // Initialize log buffer (same pattern as server_status)
  splash_log_init();
  // Clear screen and show cursor
  terminal_clear_screen();
  (void)terminal_cursor_show();
  // Clear log buffer for clean slate
  splash_log_clear();
  // Set running flag
  atomic_store_bool(&g_splash_state.is_running, true);
  atomic_store_bool(&g_splash_state.should_stop, false);
  g_splash_state.frame = 0;
  g_splash_state.start_time_ns = time_get_ns();
  // Start animation thread (only create once)
  bool expected_false = false;
  if (!atomic_cas_bool(&g_splash_state.thread_created, &expected_false, true)) {
    return 0;
  }
  int err = asciichat_thread_create(&g_splash_state.anim_thread, "splash_anim", splash_animation_thread, NULL);
  if (err != ASCIICHAT_OK) {
    log_warn("Failed to create splash animation thread: error=%d", err);
    atomic_store_bool(&g_splash_state.thread_created, false);
    return 0;
  }
  return 0; // ASCIICHAT_OK
}
References asciichat_thread_create(), atomic_cas_bool(), atomic_store_bool(), splash_log_clear(), splash_log_init(), splash_should_display(), terminal_cursor_show(), terminal_get_effective_height(), terminal_get_effective_width(), terminal_screen_set_output_fd(), and time_get_ns().
Referenced by session_client_like_run().
splash_is_running()
bool splash_is_running (void)
Definition at line 723 of file splash.c.
{
  // Check if splash animation is currently rendering
  // Used to prevent ASCII art from rendering while splash is animating
  return atomic_load_bool(&g_splash_state.is_running);
}
References atomic_load_bool().
Referenced by session_render_loop().
splash_log_clear()
void splash_log_clear (void)
Definition at line 88 of file splash.c.
{
  terminal_screen_log_clear();
}
References terminal_screen_log_clear().
Referenced by splash_intro_start().
splash_log_destroy()
void splash_log_destroy (void)
Definition at line 83 of file splash.c.
{
  log_clear_session_log_buffer();
  terminal_screen_log_destroy();
}
References log_clear_session_log_buffer(), and terminal_screen_log_destroy().
splash_log_init()
void splash_log_init (void)
Definition at line 76 of file splash.c.
{
  session_log_buffer_t *buf = terminal_screen_log_init();
  if (buf) {
    log_set_session_log_buffer(buf);
  }
}
References log_set_session_log_buffer(), and terminal_screen_log_init().
Referenced by splash_intro_start().
splash_restore_stderr()
void splash_restore_stderr (void)
Definition at line 714 of file splash.c.
{
  // No-op: stderr suppression is no longer used
  // Logging works naturally through session_log_buffer
}
Referenced by session_client_like_run().
splash_set_update_notification()
void splash_set_update_notification (const char * notification)
Definition at line 774 of file splash.c.
{
  if (lifecycle_init_once(&g_update_notification_lifecycle)) {
    mutex_init(&g_update_notification_mutex, "update_notification");
    lifecycle_init_commit(&g_update_notification_lifecycle);
  }
  mutex_lock(&g_update_notification_mutex);
  if (!notification || notification[0] == '\0') {
    g_update_notification[0] = '\0';
    log_debug("Cleared update notification for splash/status screens");
  } else {
    SAFE_STRNCPY(g_update_notification, notification, sizeof(g_update_notification));
    log_debug("Set update notification for splash/status screens: %s", notification);
  }
  mutex_unlock(&g_update_notification_mutex);
}
References lifecycle_init_commit(), lifecycle_init_once(), and mutex_init().
Referenced by main().
splash_should_display()
bool splash_should_display (bool is_intro)
Definition at line 397 of file splash.c.
{
  // Check option flags (display splash if enabled, regardless of TTY for testing)
  if (is_intro) {
    // Allow splash in snapshot mode if loading from URL/file (has loading time)
    // Skip splash only for quick webcam snapshots (unless explicitly enabled)
    bool splash_screen_opt = GET_OPTION(splash_screen);
    bool splash_explicitly_set = GET_OPTION(splash_screen_explicitly_set);
    bool is_snapshot = GET_OPTION(snapshot_mode);
    bool has_media = (GET_OPTION(media_url) && strlen(GET_OPTION(media_url)) > 0) ||
                     (GET_OPTION(media_file) && strlen(GET_OPTION(media_file)) > 0);
    // Show splash if enabled, but in snapshot mode only if:
    // 1. Has media file/URL, OR
    // 2. Explicitly enabled with --splash-screen=true
    bool should_display = splash_screen_opt && (!is_snapshot || has_media || splash_explicitly_set);
    // Show splash if:
    // 1. Not in snapshot mode, OR
    // 2. In snapshot mode but loading from URL/file (needs splash during load)
    return should_display;
  } else {
    return GET_OPTION(status_screen);
  }
}
Referenced by splash_intro_start().
splash_wait_for_animation()
void splash_wait_for_animation (void)
Definition at line 729 of file splash.c.
{
  // Wait for animation thread to fully exit before rendering ASCII art
  // This prevents the splash and ASCII art from appearing simultaneously
  //
  // The animation thread will exit gracefully when:
  // - Intro done signal received AND 2 seconds have elapsed, OR
  // - 30 seconds have elapsed (safety timeout)
  // - OR a shutdown signal is received
  //
  // We block here indefinitely to ensure the splash animation completes before ASCII art starts
  // Only join if we successfully created the thread
  if (atomic_load_bool(&g_splash_state.thread_created)) {
    log_dev("[SPLASH_WAIT] Waiting for animation thread to exit...");
    // Check if shutdown was requested - handle it specially
    bool is_shutting_down = shutdown_is_requested();
    if (is_shutting_down) {
      log_dev("[SPLASH_WAIT] Shutdown requested, signaling animation thread to stop");
      atomic_store_bool(&g_splash_state.should_stop, true);
      // During shutdown, use a short timeout (100ms)
      uint64_t timeout_ns = 100LL * NS_PER_MS_INT;
      (void)asciichat_thread_join_timeout(&g_splash_state.anim_thread, NULL, timeout_ns);
    } else {
      // Normal operation: wait indefinitely for the animation thread to finish
      // This ensures splash animation is 100% done before ASCII art rendering starts
      asciichat_error_t err = asciichat_thread_join(&g_splash_state.anim_thread, NULL);
      if (err == ASCIICHAT_OK) {
        log_dev("[SPLASH_WAIT] Animation thread exited cleanly");
      } else {
        log_warn("[SPLASH_WAIT] Animation thread join failed: %s", asciichat_error_string(err));
        // Force stop the animation thread if join failed
        atomic_store_bool(&g_splash_state.should_stop, true);
        // Clear any partial splash output left on screen
        terminal_clear_screen();
        terminal_cursor_home(STDOUT_FILENO);
        terminal_flush(STDOUT_FILENO);
      }
    }
    // Mark that we've joined (safe to call multiple times - only joins once)
    atomic_store_bool(&g_splash_state.thread_created, false);
  }
}
References asciichat_thread_join(), atomic_load_bool(), atomic_store_bool(), shutdown_is_requested(), and terminal_flush().
Referenced by session_client_like_run(), and session_render_loop().
Variable Documentation
anim_thread
asciichat_thread_t anim_thread
Definition at line 100 of file splash.c.
frame
int frame
Definition at line 99 of file splash.c.
Referenced by ascii_pad_frame_height(), ascii_pad_frame_width(), ascii_write(), client_send_thread_func(), digital_rain_apply(), ascii_query::LLDBController::evaluateExpression(), ffmpeg_decoder_read_video_frame(), framebuffer_clear(), framebuffer_peek_latest_multi_frame(), framebuffer_read_frame(), framebuffer_read_multi_frame(), framebuffer_write_frame(), ascii_query::LLDBController::getFrame(), ascii_query::LLDBController::getFrames(), handle_image_frame_h265_packet(), handle_image_frame_packet(), ascii_query::LLDBController::listVariables(), media_source_read_video(), ascii_query::LLDBController::operator=(), ascii_query::LLDBController::readVariable(), session_capture_process_for_transmission(), session_capture_read_frame(), session_host_broadcast_frame(), session_host_inject_frame(), session_host_send_frame(), session_pipeline_run_main(), terminal_fd_writer_write(), and webcam_read().
intro_done_time_ns
atomic_t intro_done_time_ns
Definition at line 102 of file splash.c.
is_running
atomic_t is_running
Definition at line 96 of file splash.c.
should_stop
atomic_t should_stop
Definition at line 97 of file splash.c.
start_time_ns
uint64_t start_time_ns
Definition at line 101 of file splash.c.
thread_created
atomic_t thread_created
Definition at line 98 of file splash.c.