ascii-chat: display.c File Reference
display.c File Reference
💻 Client terminal display: TTY detection, frame rendering, and interactive/stdout output routing
Functions
void display_set_context (session_display_ctx_t *display_ctx)
Set the display context created by session_client_like framework.
int display_init ()
Initialize what is necessary to display ascii frames.
bool display_has_tty ()
Check if display has TTY capability.
void display_full_reset ()
Perform full display reset.
void display_reset_for_new_connection ()
Reset display state for new connection.
void display_disable_logging_for_first_frame ()
Disable terminal logging for first frame.
void display_render_frame (const char *frame_data)
Render ASCII frame to display.
void display_cleanup ()
Cleanup display subsystem.
Detailed Description
💻 Client terminal display: TTY detection, frame rendering, and interactive/stdout output routing
The display system supports dual output modes:
Interactive TTY Mode: Direct terminal control with cursor positioning
Redirect Mode: Plain text output for pipes and file redirection
Snapshot Mode: Single frame capture with minimal terminal control
TTY Detection and Management
Implements robust TTY detection across platforms:
Environment Variables: Check $TTY for explicit terminal path
Standard Streams: Test stdin/stdout/stderr for TTY status
Controlling Terminal: Fall back to /dev/tty (Unix) or CON (Windows)
Validation: Verify TTY path accessibility and permissions
Terminal Control Sequences
Uses platform abstraction layer for terminal operations:
Initialization: Set terminal to optimal display mode
Cursor Management: Hide cursor and position for frame updates
Screen Control: Clear screen and scrollback buffer
Reset Operations: Restore terminal to original state
Frame Rendering Pipeline
Frame display follows a structured pipeline:
Mode Detection: Determine output mode (TTY vs redirect)
Cursor Positioning: Position cursor for frame update (TTY mode)
Data Writing: Write frame data to appropriate file descriptor
Synchronization: Ensure data reaches terminal (fsync for redirect)
State Updates: Track frame dimensions and display state
Snapshot Mode Support
Special handling for single-frame capture:
Timing Control: Coordinate with protocol for snapshot timing
Output Routing: Final frame written to both TTY and stdout
Format Control: Skip terminal control sequences in snapshot output
Cleanup: Add newline terminator for proper file formatting
Platform Compatibility
Cross-platform terminal support:
Unix/Linux: Uses /dev/tty and POSIX terminal I/O
macOS: Enhanced TTY detection with $TTY environment variable
Windows: CON device for console output with Windows Console API
Error Handling: Graceful fallback for unsupported operations
Integration Points
main.c: Display subsystem initialization and lifecycle management
protocol.c: Frame data reception and rendering requests
server.c: Terminal capability reporting and resize handling
options.c: Display mode configuration from command line
Error Handling
Display errors handled with graceful degradation:
TTY Access Errors: Fall back to stdout redirection mode
Write Errors: Log errors but continue processing
Terminal Control Errors: Skip control sequences, continue with data
Permission Errors: Try alternative TTY paths before failing
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
September 2025
Version
2.0
Definition in file src/client/display.c.
Function Documentation
display_cleanup()
void display_cleanup ()
Cleanup display subsystem.
Destroys session display context and releases all resources including keyboard input handling.
Definition at line 363 of file src/client/display.c.
                       {
  // Cleanup keyboard input if it was initialized
  if (g_keyboard_enabled) {
    keyboard_destroy();
    g_keyboard_enabled = false;
  }
  // Cleanup optional local media capture context if it was created
  if (g_display_capture_ctx) {
    session_capture_destroy(g_display_capture_ctx);
    g_display_capture_ctx = NULL;
  }
  // Display context is now managed by session_client_like framework
  // Do not destroy it here - the framework will handle cleanup
  g_display_ctx = NULL;
}
References session_capture_destroy().
display_disable_logging_for_first_frame()
void display_disable_logging_for_first_frame ()
Disable terminal logging for first frame.
Disables terminal logging before clearing the display for the first frame to prevent log output from interfering with ASCII display.
Definition at line 290 of file src/client/display.c.
{
  // Atomically check if this is the first frame and mark as not-first
  // Avoids TOCTOU race where multiple threads could both think they're first
  bool was_first_frame = atomic_exchange_bool(&g_is_first_frame_of_connection, false);
  if (was_first_frame) {
    // Disable terminal logging before clearing display and rendering first frame
    log_set_terminal_output(false);
    // Signal the intro splash screen to stop - first frame is ready to render
    splash_intro_done();
  }
}
References atomic_exchange_bool(), log_set_terminal_output(), and splash_intro_done().
Referenced by display_render_frame().
display_full_reset()
void display_full_reset ()
Perform full display reset.
Executes complete terminal reset sequence for clean display state. Safe to call multiple times and handles mode-specific behavior.
Definition at line 264 of file src/client/display.c.
{
  if (g_display_ctx && !should_exit()) {
    session_display_reset(g_display_ctx);
  }
}
References session_display_reset(), and should_exit().
Referenced by server_connection_lost().
display_has_tty()
bool display_has_tty ()
Check if display has TTY capability.
Returns
true if TTY is available for interactive output, false otherwise
Definition at line 252 of file src/client/display.c.
                       {
  return session_display_has_tty(g_display_ctx);
}
References session_display_has_tty().
display_init()
int display_init ()
Initialize what is necessary to display ascii frames.
Initialize display subsystem.
Creates session display context for TTY management and frame rendering. Must be called once during client startup.
Returns
0 on success, negative on error
Definition at line 180 of file src/client/display.c.
                   {
  // Build display configuration from options
  session_display_config_t config = {
      .snapshot_mode = GET_OPTION(snapshot_mode),
      .palette_type = GET_OPTION(palette_type),
      .custom_palette = GET_OPTION(palette_custom_set) ? GET_OPTION(palette_custom) : NULL,
      .color_mode = TERM_COLOR_AUTO // Will be overridden by command-line options
  };
  // Create display context using session library
  g_display_ctx = session_display_create(&config);
  if (!g_display_ctx) {
    SET_ERRNO(ERROR_DISPLAY, "Failed to initialize display");
    return -1;
  }
  // Check if client mode should load local media (--file or --url)
  const char *media_url = GET_OPTION(media_url);
  const char *media_file = GET_OPTION(media_file);
  if ((media_url && strlen(media_url) > 0) || (media_file && strlen(media_file) > 0)) {
    // Client mode with local media file/URL - create capture context for keyboard controls
    session_capture_config_t capture_config = {0};
    capture_config.target_fps = 60;
    capture_config.resize_for_network = false;
    capture_config.should_exit_callback = NULL;
    capture_config.callback_data = NULL;
    if (media_url && strlen(media_url) > 0) {
      capture_config.type = MEDIA_SOURCE_FILE;
      capture_config.path = media_url;
    } else {
      if (strcmp(media_file, "-") == 0) {
        capture_config.type = MEDIA_SOURCE_STDIN;
        capture_config.path = NULL;
      } else {
        capture_config.type = MEDIA_SOURCE_FILE;
        capture_config.path = media_file;
      }
    }
    capture_config.loop = GET_OPTION(media_loop);
    capture_config.initial_seek_timestamp = GET_OPTION(media_seek_timestamp);
    g_display_capture_ctx = session_capture_create(&capture_config);
    if (!g_display_capture_ctx) {
      log_warn("Failed to create capture context for local media - keyboard seek/pause disabled");
      g_display_capture_ctx = NULL;
    }
  }
  // Keyboard is pre-initialized from asciichat_shared_init()
  // Only enable keyboard input if stdin is a TTY (avoid interfering with piped/redirected I/O)
  g_keyboard_enabled = terminal_is_stdin_tty();
  // Register display atomics with named debug registry
  static bool display_atomics_registered = false;
  if (!display_atomics_registered) {
    NAMED_REGISTER_ATOMIC(&g_is_first_frame_of_connection, "first_frame_of_display_connection", NULL);
    display_atomics_registered = true;
  }
  return 0;
}
References session_capture_config_t::callback_data, session_capture_config_t::initial_seek_timestamp, session_capture_config_t::loop, session_capture_config_t::path, session_capture_config_t::resize_for_network, session_capture_create(), session_display_create(), session_capture_config_t::should_exit_callback, session_capture_config_t::target_fps, terminal_is_stdin_tty(), and session_capture_config_t::type.
display_render_frame()
void display_render_frame (const char * frame_data)
Render ASCII frame to display.
Render ASCII frame to display
Uses session display library for frame output routing based on display mode and snapshot requirements. Also polls for keyboard input for interactive controls (volume, color mode, flip).
Parameters
frame_data ASCII frame data to render
is_snapshot_frame Whether this is the final snapshot frame
Definition at line 316 of file src/client/display.c.
{
  if (!frame_data) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Attempted to render NULL frame data");
    return;
  }
  // Stop splash screen animation on first frame
  // This must be called BEFORE any frame rendering to prevent splash/frame flickering
  display_disable_logging_for_first_frame();
  // Render help screen if active (suppresses frame rendering)
  if (keyboard_help_is_active(g_display_ctx)) {
    keyboard_help_render(g_display_ctx);
    // Still poll keyboard for interactive controls while help is visible
    if (g_keyboard_enabled) {
      keyboard_key_t key = keyboard_read_nonblocking();
      if (key != KEY_NONE) {
        session_handle_keyboard_input(g_display_capture_ctx, g_display_ctx, key);
      }
    }
    return; // Skip normal frame rendering
  }
  // Use session display library for frame rendering
  session_display_render_frame(g_display_ctx, frame_data);
  // Poll for keyboard input and handle interactive controls
  // - If client mode has local media (--file/--url), pass capture context for full controls
  //   (seek, pause, play, volume, color mode, flip)
  // - If client mode is network-only, pass NULL (volume, color mode, flip work; seek/pause ignored)
  if (g_keyboard_enabled) {
    keyboard_key_t key = keyboard_read_nonblocking();
    if (key != KEY_NONE) {
      session_handle_keyboard_input(g_display_capture_ctx, g_display_ctx, key);
    }
  }
}
References display_disable_logging_for_first_frame(), keyboard_help_is_active(), keyboard_help_render(), session_display_render_frame(), and session_handle_keyboard_input().
display_reset_for_new_connection()
void display_reset_for_new_connection ()
Reset display state for new connection.
Resets the first frame tracking flag to prepare for a new connection. Call this when starting a new connection to reset first frame tracking.
Definition at line 278 of file src/client/display.c.
{
  atomic_store_bool(&g_is_first_frame_of_connection, true);
}
References atomic_store_bool().
Referenced by protocol_start_connection().
display_set_context()
void display_set_context (session_display_ctx_t * display_ctx)
Set the display context created by session_client_like framework.
Set the display context (framework integration).
Client mode doesn't create its own display context anymore. Instead, session_client_like_run() creates it and passes it to client_run(). This setter allows client_run() to make the framework-created context available to protocol threads that need to render frames.
Parameters
display_ctx Display context created by framework (may be NULL)
Definition at line 162 of file src/client/display.c.
{
  g_display_ctx = display_ctx;
}