ascii-chat: display.c File Reference
display.c File Reference
Session
🖥️ Unified terminal display implementation
Data Structures
struct session_display_ctx
Internal session display context structure.
Typedefs
typedef struct session_display_ctx session_display_ctx_t
Internal session display context structure.
Functions
session_display_ctx_t * session_display_create (const session_display_config_t *config)
Perform complete terminal reset.
void session_display_destroy (session_display_ctx_t *ctx)
Destroy session display context and free resources.
void session_display_set_stdin_reader (session_display_ctx_t *ctx, void *reader)
Set stdin frame reader for ASCII-to-video rendering.
bool session_display_has_tty (session_display_ctx_t *ctx)
Check if display has a TTY (terminal) available.
const terminal_capabilities_t * session_display_get_caps (session_display_ctx_t *ctx)
Get detected terminal capabilities.
const char * session_display_get_palette_chars (session_display_ctx_t *ctx)
Get the palette characters string.
size_t session_display_get_palette_len (session_display_ctx_t *ctx)
Get the palette character count.
const char * session_display_get_luminance_palette (session_display_ctx_t *ctx)
Get the luminance mapping palette.
int session_display_get_tty_fd (session_display_ctx_t *ctx)
Get the TTY file descriptor.
void * session_display_get_stdin_reader (session_display_ctx_t *ctx)
Get the stdin frame reader for ASCII-to-video rendering.
uint32_t session_display_get_render_fps (session_display_ctx_t *ctx)
Get the render FPS configured for file output.
void session_display_set_render_fps (session_display_ctx_t *ctx, uint32_t fps)
Set the render FPS for file output encoding.
bool session_display_has_first_frame (session_display_ctx_t *ctx)
Check if the display has rendered its first frame.
void session_display_reset_first_frame (session_display_ctx_t *ctx)
Reset the first frame flag to allow splash screen to show again on next render.
bool session_display_has_render_file (session_display_ctx_t *ctx)
Check if display has render-file configured.
char * session_display_convert_to_ascii (session_display_ctx_t *ctx, const image_t *image)
Convert an image to ASCII art using display context and command-line options.
void session_display_render_fps_overlay (session_display_ctx_t *ctx)
Render FPS counter overlay in top-right corner.
void session_display_render_frame (session_display_ctx_t *ctx, const char *frame_data)
Render an ASCII frame to the terminal.
void session_display_write_ascii (session_display_ctx_t *ctx, const char *ascii)
Write ASCII frame to terminal only (no encoding).
void session_display_encode_frame (session_display_ctx_t *ctx, const image_t *image, uint64_t captured_ns)
Encode frame to render-file (FFmpeg only, no terminal output).
void session_display_write_raw (session_display_ctx_t *ctx, const char *data, size_t len)
Render raw bytes to the terminal without frame processing.
void session_display_reset (session_display_ctx_t *ctx)
Reset terminal to default state.
void session_display_clear (session_display_ctx_t *ctx)
Clear the terminal screen.
void session_display_cursor_home (session_display_ctx_t *ctx)
Move cursor to home position (top-left).
bool session_display_has_audio_playback (session_display_ctx_t *ctx)
Check if display has audio playback configured.
asciichat_error_t session_display_write_audio (session_display_ctx_t *ctx, const float *buffer, size_t num_samples)
Write audio samples to playback buffer.
void keyboard_help_toggle (session_display_ctx_t *ctx)
Toggle keyboard help on/off (implemented in display.c for struct access).
bool keyboard_help_is_active (session_display_ctx_t *ctx)
Check if keyboard help is currently active (implemented in display.c for struct access).
void session_display_set_snapshot_actual_duration (session_display_ctx_t *ctx, double actual_duration_sec)
Set the actual wall-clock duration for snapshot mode frame timing.
Detailed Description
🖥️ Unified terminal display implementation
Implements the session display abstraction layer for unified terminal rendering across client, mirror, and discovery modes.
Author
Zachary Fogg me@zf.nosp@m.o.gg
Date
January 2026
Definition in file src/common/session/display.c.
Function Documentation
keyboard_help_is_active()
bool keyboard_help_is_active (session_display_ctx_t * ctx)
Check if keyboard help is currently active (implemented in display.c for struct access).
Definition at line 1133 of file src/common/session/display.c.
{
  if (!ctx) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL");
    return false;
  }
  // Disable help in snapshot mode only - allow help state check even if stdin/stdout aren't TTYs
  if (GET_OPTION(snapshot_mode)) {
    return false;
  }
  return atomic_load_bool(&ctx->keyboard_help_active);
}
References atomic_load_bool(), and session_display_ctx::keyboard_help_active.
Referenced by display_render_frame(), session_handle_keyboard_input(), and session_render_loop().
keyboard_help_toggle()
void keyboard_help_toggle (session_display_ctx_t * ctx)
Toggle keyboard help on/off (implemented in display.c for struct access).
Definition at line 1114 of file src/common/session/display.c.
{
  if (!ctx) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Session display context is NULL");
    return;
  }
  // Disable help in snapshot mode only - allow help toggle even if stdin/stdout aren't TTYs
  // (the display context tracks has_tty independently)
  if (GET_OPTION(snapshot_mode)) {
    return;
  }
  bool current = atomic_load_bool(&ctx->keyboard_help_active);
  atomic_store_bool(&ctx->keyboard_help_active, !current);
}
References atomic_load_bool(), atomic_store_bool(), and session_display_ctx::keyboard_help_active.
Referenced by session_handle_keyboard_input().