ascii-chat: status.c File Reference
status.c File Reference
Status screen display with live log feed at FPS rate.
Functions
void ui_status_log_init (void)
void ui_status_log_destroy (void)
void ui_status_log_clear (void)
asciichat_error_t ui_status_gather (tcp_server_t *server, const char *session_string, const char *ipv4_address, const char *ipv6_address, uint16_t port, time_t start_time, const char *mode_name, bool session_is_mdns_only, ui_status_t *out_status)
void ui_status_display (const ui_status_t *status)
bool ui_status_display_interactive (const ui_status_t *status)
Display status screen with keyboard input support Returns true if status screen should continue, false if Escape was pressed to exit.
void ui_status_update (tcp_server_t *server, const char *session_string, const char *ipv4_address, const char *ipv6_address, uint16_t port, time_t start_time, const char *mode_name, bool session_is_mdns_only, uint64_t *last_update_ns)
Detailed Description
Status screen display with live log feed at FPS rate.
Definition in file status.c.
Function Documentation
ui_status_display()
void ui_status_display (const ui_status_t * status)
Definition at line 194 of file status.c.
{
  if (!status) {
    return;
  }
  // Only render the status screen if:
  // 1. Terminal is interactive (default behavior), OR
  // 2. User explicitly set --status-screen on command line (force it regardless of terminal)
  // In non-interactive mode without explicit flag, logs flow to stdout/stderr normally
  if (!terminal_is_interactive() && !GET_OPTION(status_screen_explicitly_set)) {
    return;
  }
  // Redirect status screen to stderr when stdout is piped (not a TTY)
  // This keeps stdout clean for frame data while status goes to stderr
  if (!isatty(STDOUT_FILENO)) {
    terminal_screen_set_output_fd(STDERR_FILENO);
  }
  // If --grep pattern was provided, enter interactive grep mode with it pre-populated
  // Only do this once (check if not already entering)
  static bool grep_mode_entered = false;
  if (!grep_mode_entered && grep_get_last_pattern() && grep_get_last_pattern()[0] != '\0') {
    log_search_enter_mode();
    grep_mode_entered = true;
  }
  // Use terminal_screen abstraction for rendering
  terminal_screen_config_t config = {
      .fixed_header_lines = 4,
      .render_header = render_ui_status_header,
      .user_data = (void *)status,
      .show_logs = true,
  };
  terminal_screen_render(&config);
}
References grep_get_last_pattern(), log_search_enter_mode(), terminal_is_interactive(), terminal_screen_render(), and terminal_screen_set_output_fd().
Referenced by ui_status_update().
ui_status_display_interactive()
bool ui_status_display_interactive (const ui_status_t * status)
Display status screen with keyboard input support Returns true if status screen should continue, false if Escape was pressed to exit.
Definition at line 236 of file status.c.
{
  if (!status) {
    return true;
  }
  // Only render the status screen if:
  // 1. Terminal is interactive (default behavior), OR
  // 2. User explicitly set --status-screen on command line (force it regardless of terminal)
  // In non-interactive mode without explicit flag, logs flow to stdout/stderr normally
  if (!terminal_is_interactive() && !GET_OPTION(status_screen_explicitly_set)) {
    return true;
  }
  // If --grep pattern was provided, enter interactive grep mode with it pre-populated
  static bool grep_mode_entered = false;
  if (!grep_mode_entered && grep_get_last_pattern() && grep_get_last_pattern()[0] != '\0') {
    log_search_enter_mode();
    grep_mode_entered = true;
  }
  // Initialize keyboard for interactive grep
  bool keyboard_enabled = false;
  if (keyboard_init() == ASCIICHAT_OK) {
    keyboard_enabled = true;
  }
  // Use terminal_screen abstraction for rendering
  terminal_screen_config_t config = {
      .fixed_header_lines = 4,
      .render_header = render_ui_status_header,
      .user_data = (void *)status,
      .show_logs = true,
  };
  terminal_screen_render(&config);
  // Poll keyboard for Escape to exit or for interactive grep
  bool should_exit_status = false;
  if (keyboard_enabled) {
    keyboard_key_t key = keyboard_read_nonblocking();
    if (key == KEY_ESCAPE) {
      // Escape key: cancel grep if active, otherwise exit status screen
      if (log_search_is_active()) {
        log_search_exit_mode(false); // Cancel grep without applying
      } else {
        should_exit_status = true; // Exit status screen
      }
    } else if (key != KEY_NONE && log_search_should_handle(key)) {
      log_search_handle_key(key);
    }
  }
  // Cleanup keyboard
  if (keyboard_enabled) {
    keyboard_destroy();
  }
  return !should_exit_status; // Return false if user wants to exit
}
References grep_get_last_pattern(), log_search_enter_mode(), log_search_exit_mode(), log_search_handle_key(), log_search_is_active(), log_search_should_handle(), terminal_is_interactive(), and terminal_screen_render().
ui_status_gather()
asciichat_error_t ui_status_gather (tcp_server_t * server, const char * session_string, const char * ipv4_address, const char * ipv6_address, uint16_t port, time_t start_time, const char * mode_name, bool session_is_mdns_only, ui_status_t * out_status)
Definition at line 52 of file status.c.
{
  if (!server || !out_status || !mode_name) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters for ui_status_gather");
  }
  memset(out_status, 0, sizeof(*out_status));
  // Copy session string
  if (session_string) {
    SAFE_STRNCPY(out_status->session_string, session_string, sizeof(out_status->session_string));
  }
  // Format IPv4 address
  out_status->ipv4_bound = (ipv4_address && ipv4_address[0] != '\0');
  if (out_status->ipv4_bound) {
    snprintf(out_status->ipv4_address, sizeof(out_status->ipv4_address), "%s:%u", ipv4_address, port);
  }
  // Format IPv6 address
  out_status->ipv6_bound = (ipv6_address && ipv6_address[0] != '\0');
  if (out_status->ipv6_bound) {
    snprintf(out_status->ipv6_address, sizeof(out_status->ipv6_address), "[%s]:%u", ipv6_address, port);
  }
  out_status->port = port;
  out_status->start_time = start_time;
  out_status->mode_name = mode_name;
  out_status->session_is_mdns_only = session_is_mdns_only;
  out_status->connected_count = tcp_server_get_client_count(server);
  return ASCIICHAT_OK;
}
References tcp_server_get_client_count().
Referenced by ui_status_update().
ui_status_log_clear()
void ui_status_log_clear (void)
Definition at line 43 of file status.c.
{
  // Delegate to terminal_screen log abstraction
  terminal_screen_log_clear();
}
References terminal_screen_log_clear().
Referenced by server_main().
ui_status_log_destroy()
void ui_status_log_destroy (void)
Definition at line 36 of file status.c.
{
  // Unregister from logger before destroying
  log_clear_session_log_buffer();
  // Cleanup the shared terminal screen log buffer
  terminal_screen_log_destroy();
}
References log_clear_session_log_buffer(), and terminal_screen_log_destroy().
Referenced by server_main().
ui_status_log_init()
void ui_status_log_init (void)
Definition at line 28 of file status.c.
{
  // Initialize the shared terminal screen log buffer
  session_log_buffer_t *buf = terminal_screen_log_init();
  if (buf) {
    log_set_session_log_buffer(buf);
  }
}
References log_set_session_log_buffer(), and terminal_screen_log_init().
Referenced by server_main().
ui_status_update()
void ui_status_update (tcp_server_t * server, const char * session_string, const char * ipv4_address, const char * ipv6_address, uint16_t port, time_t start_time, const char * mode_name, bool session_is_mdns_only, uint64_t * last_update_ns)
Definition at line 296 of file status.c.
{
  if (!server || !last_update_ns) {
    return;
  }
  // Update at FPS rate (60 Hz = 16.67ms by default)
  uint32_t fps = GET_OPTION(fps);
  if (fps == 0) {
    fps = 60; // Default
  }
  // Calculate frame interval in microseconds
  uint64_t frame_interval_us = US_PER_SEC_INT / fps;
  // Get current time in microseconds using platform abstraction
  uint64_t now_us = platform_get_monotonic_time_us();
  // Check if enough time has passed
  if ((now_us - *last_update_ns) < frame_interval_us) {
    return; // Too soon, skip frame
  }
  ui_status_t status;
  if (ui_status_gather(server, session_string, ipv4_address, ipv6_address, port, start_time, mode_name,
                           session_is_mdns_only, &status) == ASCIICHAT_OK) {
    ui_status_display(&status);
    *last_update_ns = now_us;
  }
}
References platform_get_monotonic_time_us(), ui_status_display(), and ui_status_gather().