ascii-chat: session_host_callbacks_t Struct Reference
session_host_callbacks_t Struct Reference
Session
Callback function prototypes for session host events.
#include <src/common/session/host.h>
Data Fields
void(* on_client_join)(session_host_t *h, uint32_t client_id, void *user_data)
Called when a client joins the session.
void(* on_client_leave)(session_host_t *h, uint32_t client_id, void *user_data)
Called when a client leaves the session.
void(* on_frame_received)(session_host_t *h, uint32_t client_id, const image_t *frame, void *user_data)
Called when video frame received from a client.
void(* on_audio_received)(session_host_t *h, uint32_t client_id, const float *samples, size_t count, void *user_data)
Called when audio samples received from a client.
void(* on_error)(session_host_t *h, asciichat_error_t error, const char *message, void *user_data)
Called when an error occurs.
Detailed Description
Callback function prototypes for session host events.
Definition at line 104 of file host.h.
Field Documentation
on_audio_received
void(* session_host_callbacks_t::on_audio_received) (session_host_t *h, uint32_t client_id, const float *samples, size_t count, void *user_data)
Called when audio samples received from a client.
Parameters
h Host handle
client_id Source client's ID
samples Audio sample buffer (float format)
count Number of samples
user_data User-provided context pointer
Definition at line 138 of file host.h.
on_client_join
void(* session_host_callbacks_t::on_client_join) (session_host_t *h, uint32_t client_id, void *user_data)
Called when a client joins the session.
Parameters
h Host handle
client_id New client's ID
user_data User-provided context pointer
Definition at line 111 of file host.h.
Referenced by session_host_add_client(), and session_host_add_memory_participant().
on_client_leave
void(* session_host_callbacks_t::on_client_leave) (session_host_t *h, uint32_t client_id, void *user_data)
Called when a client leaves the session.
Parameters
h Host handle
client_id Departing client's ID
user_data User-provided context pointer
Definition at line 119 of file host.h.
Referenced by session_host_remove_client(), and session_host_stop().
on_error
void(* session_host_callbacks_t::on_error) (session_host_t *h, asciichat_error_t error, const char *message, void *user_data)
Called when an error occurs.
Parameters
h Host handle
error Error code
message Error message
user_data User-provided context pointer
Definition at line 147 of file host.h.
Referenced by session_host_start().
on_frame_received
void(* session_host_callbacks_t::on_frame_received) (session_host_t *h, uint32_t client_id, const image_t *frame, void *user_data)
Called when video frame received from a client.
Parameters
h Host handle
client_id Source client's ID
frame Video frame image
user_data User-provided context pointer
Definition at line 128 of file host.h.
The documentation for this struct was generated from the following file:
host.h