ascii-chat: session_participant_callbacks_t Struct Reference
session_participant_callbacks_t Struct Reference
Session
Callback function prototypes for session participant events.
#include <src/common/session/participant.h>
Data Fields
void(* on_connected)(session_participant_t *p, uint32_t client_id, void *user_data)
Called when successfully connected to session.
void(* on_disconnected)(session_participant_t *p, void *user_data)
Called when disconnected from session.
void(* on_frame_received)(session_participant_t *p, const char *frame, void *user_data)
Called when ASCII frame received from server.
void(* on_audio_received)(session_participant_t *p, const float *samples, size_t count, void *user_data)
Called when audio samples received from server.
void(* on_settings_changed)(session_participant_t *p, const session_settings_t *settings, void *user_data)
Called when session settings change.
void(* on_error)(session_participant_t *p, asciichat_error_t error, const char *message, void *user_data)
Called when an error occurs.
Detailed Description
Callback function prototypes for session participant events.
Definition at line 77 of file participant.h.
Field Documentation
on_audio_received
void(* session_participant_callbacks_t::on_audio_received) (session_participant_t *p, const float *samples, size_t count, void *user_data)
Called when audio samples received from server.
Parameters
p Participant handle
samples Audio sample buffer (float format)
count Number of samples
user_data User-provided context pointer
Definition at line 108 of file participant.h.
on_connected
void(* session_participant_callbacks_t::on_connected) (session_participant_t *p, uint32_t client_id, void *user_data)
Called when successfully connected to session.
Parameters
p Participant handle
client_id Assigned client ID from server
user_data User-provided context pointer
Definition at line 84 of file participant.h.
Referenced by session_participant_connect().
on_disconnected
void(* session_participant_callbacks_t::on_disconnected) (session_participant_t *p, void *user_data)
Called when disconnected from session.
Parameters
p Participant handle
user_data User-provided context pointer
Definition at line 91 of file participant.h.
Referenced by session_participant_disconnect().
on_error
void(* session_participant_callbacks_t::on_error) (session_participant_t *p, asciichat_error_t error, const char *message, void *user_data)
Called when an error occurs.
Parameters
p Participant handle
error Error code
message Error message
user_data User-provided context pointer
Definition at line 125 of file participant.h.
Referenced by session_participant_connect().
on_frame_received
void(* session_participant_callbacks_t::on_frame_received) (session_participant_t *p, const char *frame, void *user_data)
Called when ASCII frame received from server.
Parameters
p Participant handle
frame ASCII frame data (null-terminated)
user_data User-provided context pointer
Definition at line 99 of file participant.h.
on_settings_changed
void(* session_participant_callbacks_t::on_settings_changed) (session_participant_t *p, const session_settings_t *settings, void *user_data)
Called when session settings change.
Parameters
p Participant handle
settings New session settings
user_data User-provided context pointer
Definition at line 116 of file participant.h.
The documentation for this struct was generated from the following file:
participant.h