ascii-chat: ascii_query::HttpResponse Struct Reference
ascii_query::HttpResponse Struct Reference
HTTP response builder.
#include <src/tooling/query/http_server.h>
Public Member Functions
HttpResponse ()=default
HttpResponse (int code, std::string text, std::string content_type, std::string response_body)
HttpResponse & setHeader (const std::string &name, const std::string &value)
Set a header.
std::string serialize () const
Serialize response to HTTP/1.1 format.
Static Public Member Functions
static HttpResponse ok (const std::string &content_type, const std::string &body)
static HttpResponse json (const std::string &body)
static HttpResponse html (const std::string &body)
static HttpResponse text (const std::string &body)
static HttpResponse notFound (const std::string &message="Not Found")
static HttpResponse badRequest (const std::string &message="Bad Request")
static HttpResponse serverError (const std::string &message="Internal Server Error")
static HttpResponse noContent ()
Data Fields
int status_code = 200
std::string status_text = "OK"
std::unordered_map< std::string, std::string > headers
std::string body
Detailed Description
HTTP response builder.
Definition at line 94 of file http_server.h.
Constructor & Destructor Documentation
HttpResponse() [1/2]
ascii_query::HttpResponse::HttpResponse () default
Referenced by badRequest(), html(), json(), noContent(), notFound(), ok(), serverError(), setHeader(), and text().
HttpResponse() [2/2]
ascii_query::HttpResponse::HttpResponse (int code, std::string text, std::string content_type, std::string response_body) inline
Definition at line 101 of file http_server.h.
      : status_code(code), status_text(std::move(text)), body(std::move(response_body)) {
    headers["Content-Type"] = std::move(content_type);
  }
References body, headers, status_code, status_text, and text().
Member Function Documentation
badRequest()
HttpResponse ascii_query::HttpResponse::badRequest (const std::string & message = "Bad Request") inline static
Definition at line 127 of file http_server.h.
{
    return HttpResponse(400, "Bad Request", "application/json", R"({"error":")" + json::escape(message) + R"("})");
  }
References ascii_query::json::escape(), and HttpResponse().
html()
HttpResponse ascii_query::HttpResponse::html (const std::string & body) inline static
Definition at line 115 of file http_server.h.
{
    return ok("text/html; charset=utf-8", body);
  }
References body, HttpResponse(), and ok().
json()
HttpResponse ascii_query::HttpResponse::json (const std::string & body) inline static
Definition at line 111 of file http_server.h.
{
    return ok("application/json", body);
  }
References body, HttpResponse(), and ok().
noContent()
HttpResponse ascii_query::HttpResponse::noContent () inline static
Definition at line 136 of file http_server.h.
{
    return HttpResponse(204, "No Content", "text/plain", "");
  }
References HttpResponse().
notFound()
HttpResponse ascii_query::HttpResponse::notFound (const std::string & message = "Not Found") inline static
Definition at line 123 of file http_server.h.
{
    return HttpResponse(404, "Not Found", "application/json", R"({"error":")" + json::escape(message) + R"("})");
  }
References ascii_query::json::escape(), and HttpResponse().
Referenced by ascii_query::HttpServer::HttpServer().
ok()
HttpResponse ascii_query::HttpResponse::ok (const std::string & content_type, const std::string & body) inline static
Definition at line 107 of file http_server.h.
{
    return HttpResponse(200, "OK", content_type, body);
  }
References body, and HttpResponse().
Referenced by html(), json(), and text().
serialize()
std::string ascii_query::HttpResponse::serialize () const nodiscard
Serialize response to HTTP/1.1 format.
Definition at line 62 of file http_server.cpp.
{
    std::ostringstream oss;
    // Status line
    oss << "HTTP/1.1 " << status_code << " " << status_text << "\r\n";
    // Headers
    bool has_content_length = false;
    bool has_connection = false;
    for (const auto &[key, value] : headers) {
        oss << key << ": " << value << "\r\n";
        std::string lower_key = key;
        std::transform(lower_key.begin(), lower_key.end(), lower_key.begin(),
                       [](unsigned char c) { return std::tolower(c); });
        if (lower_key == "content-length")
            has_content_length = true;
        if (lower_key == "connection")
            has_connection = true;
    }
    // Add Content-Length if not present
    if (!has_content_length) {
        oss << "Content-Length: " << body.size() << "\r\n";
    }
    // Add Connection: close if not present
    if (!has_connection) {
        oss << "Connection: close\r\n";
    }
    // CORS headers for browser access
    oss << "Access-Control-Allow-Origin: *\r\n";
    oss << "Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS\r\n";
    oss << "Access-Control-Allow-Headers: Content-Type\r\n";
    // End headers
    oss << "\r\n";
    // Body
    oss << body;
    return oss.str();
}
References body, headers, status_code, and status_text.
serverError()
HttpResponse ascii_query::HttpResponse::serverError (const std::string & message = "Internal Server Error") inline static
Definition at line 131 of file http_server.h.
{
    return HttpResponse(500, "Internal Server Error", "application/json",
                        R"({"error":")" + json::escape(message) + R"("})");
  }
References ascii_query::json::escape(), and HttpResponse().
setHeader()
HttpResponse & ascii_query::HttpResponse::setHeader (const std::string & name, const std::string & value) inline
Set a header.
Definition at line 143 of file http_server.h.
{
    headers[name] = value;
    return *this;
  }
References headers, and HttpResponse().
text()
HttpResponse ascii_query::HttpResponse::text (const std::string & body) inline static
Definition at line 119 of file http_server.h.
{
    return ok("text/plain", body);
  }
References body, HttpResponse(), and ok().
Referenced by HttpResponse().
Field Documentation
body
std::string ascii_query::HttpResponse::body
Definition at line 98 of file http_server.h.
Referenced by html(), HttpResponse(), json(), ok(), serialize(), and text().
headers
std::unordered_map<std::string, std::string> ascii_query::HttpResponse::headers
Definition at line 97 of file http_server.h.
Referenced by HttpResponse(), serialize(), and setHeader().
status_code
int ascii_query::HttpResponse::status_code = 200
Definition at line 95 of file http_server.h.
Referenced by HttpResponse(), and serialize().
status_text
std::string ascii_query::HttpResponse::status_text = "OK"
Definition at line 96 of file http_server.h.
Referenced by HttpResponse(), and serialize().
The documentation for this struct was generated from the following files:
http_server.h
http_server.cpp