ascii-chat: sync.c File Reference
sync.c File Reference
🔒 Synchronization primitive debugging with dynamic state inspection
Data Structures
struct sync_buffer_t
struct debug_state_request_t
Macros
#define SYNC_BUFFER_SIZE 65536
Enumerations
enum debug_request_type_t { DEBUG_REQUEST_STATE , DEBUG_REQUEST_BACKTRACE , DEBUG_REQUEST_MEMORY_REPORT }
Functions
void debug_sync_print_state (void)
void debug_sync_final_cleanup (void)
Final cleanup of all debug allocations at shutdown.
void debug_sync_print_state_delayed (uint64_t delay_ns)
Schedule delayed debug state printing on debug thread.
void debug_sync_print_backtrace_delayed (uint64_t delay_ns)
Schedule delayed backtrace printing on debug thread.
void debug_sync_set_memory_report_interval (uint64_t interval_ns)
Set periodic memory report interval.
void debug_sync_set_main_thread_id (void)
int debug_sync_init (void)
uint64_t debug_sync_get_main_thread_id (void)
bool debug_sync_is_cleanup_in_progress (void)
int debug_sync_start_thread (void)
void debug_sync_destroy (void)
void debug_sync_cleanup_thread (void)
void debug_sync_trigger_print (void)
void debug_sync_get_stats (uint64_t *total_acquired, uint64_t *total_released, uint32_t *currently_held)
int debug_sync_mutex_lock (mutex_t *mutex, const char *file_name, int line_number, const char *function_name)
int debug_sync_mutex_trylock (mutex_t *mutex, const char *file_name, int line_number, const char *function_name)
int debug_sync_mutex_unlock (mutex_t *mutex, const char *file_name, int line_number, const char *function_name)
int debug_sync_rwlock_rdlock (rwlock_t *lock, const char *file_name, int line_number, const char *function_name)
int debug_sync_rwlock_rdunlock (rwlock_t *lock, const char *file_name, int line_number, const char *function_name)
int debug_sync_rwlock_wrlock (rwlock_t *lock, const char *file_name, int line_number, const char *function_name)
int debug_sync_rwlock_wrunlock (rwlock_t *lock, const char *file_name, int line_number, const char *function_name)
int debug_sync_cond_wait (cond_t *cond, mutex_t *mutex, const char *file_name, int line_number, const char *function_name)
int debug_sync_cond_timedwait (cond_t *cond, mutex_t *mutex, uint64_t timeout_ns, const char *file_name, int line_number, const char *function_name)
int debug_sync_cond_signal (cond_t *cond, const char *file_name, int line_number, const char *function_name)
int debug_sync_cond_broadcast (cond_t *cond, const char *file_name, int line_number, const char *function_name)
bool debug_sync_is_initialized (void)
Detailed Description
🔒 Synchronization primitive debugging with dynamic state inspection
Date
February 2026
Clean architecture: queries named.c registry for current state. No internal collection overhead - inspects lock structs directly.
Definition in file sync.c.
Macro Definition Documentation
SYNC_BUFFER_SIZE
#define SYNC_BUFFER_SIZE 65536
Referenced by debug_sync_print_state().
Enumeration Type Documentation
debug_request_type_t
enum debug_request_type_t
Enumerator
DEBUG_REQUEST_STATE
DEBUG_REQUEST_BACKTRACE
DEBUG_REQUEST_MEMORY_REPORT
Definition at line 426 of file sync.c.
             {
  DEBUG_REQUEST_STATE,         // Print sync state
  DEBUG_REQUEST_BACKTRACE,     // Print backtrace
  DEBUG_REQUEST_MEMORY_REPORT, // Print memory report
} debug_request_type_t;
Function Documentation
debug_sync_cleanup_thread()
void debug_sync_cleanup_thread (void)
Definition at line 665 of file sync.c.
{
  log_debug("[DEBUG_SYNC_CLEANUP] Starting cleanup");
  // Only join if thread was actually created
  if (!g_debug_state_request.initialized) {
    log_debug("[DEBUG_SYNC_CLEANUP] Thread not initialized, returning");
    return;
  }
  // Set cleanup flag to prevent deadlock checks from accessing freed memory
  // Do this after checking initialization so we don't set it unnecessarily
  atomic_store_bool(&g_cleanup_in_progress, true);
  log_debug("[DEBUG_SYNC_CLEANUP] Thread was initialized, proceeding with cleanup");
  log_debug("[DEBUG_SYNC_CLEANUP] Setting initialized to false");
  g_debug_state_request.initialized = false; // Prevent double-join
  // Signal the thread to wake up immediately instead of waiting for 100ms timeout
  log_debug("[DEBUG_SYNC_CLEANUP] Signaling thread to exit");
  atomic_store_bool(&g_debug_state_request.should_exit, true);
  cond_signal(&g_debug_state_request.cond);
  log_debug("[DEBUG_SYNC_CLEANUP] Signal sent, about to join thread");
  // Use a timeout join to ensure we don't deadlock, but still unregister the thread
  // The debug thread should exit quickly after should_exit is set above
  int join_result = asciichat_thread_join_timeout(&g_debug_thread, NULL, 1000000000ULL); // 1 second timeout
  if (join_result == 0) {
    log_debug("[DEBUG_SYNC_CLEANUP] Thread joined successfully");
  } else if (join_result == -2) {
    log_debug("[DEBUG_SYNC_CLEANUP] Thread join timed out (thread may still be running)");
    // Don't unregister if timeout - thread is still alive
  } else {
    log_debug("[DEBUG_SYNC_CLEANUP] Thread join failed with error %d", join_result);
  }
}
References atomic_store_bool().
Referenced by asciichat_shared_destroy(), debug_sync_destroy(), and session_client_like_run().
debug_sync_cond_broadcast()
int debug_sync_cond_broadcast (cond_t * cond, const char * file_name, int line_number, const char * function_name)
Definition at line 802 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return cond_broadcast(cond);
}
debug_sync_cond_signal()
int debug_sync_cond_signal (cond_t * cond, const char * file_name, int line_number, const char * function_name)
Definition at line 795 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return cond_signal(cond);
}
debug_sync_cond_timedwait()
int debug_sync_cond_timedwait (cond_t * cond, mutex_t * mutex, uint64_t timeout_ns, const char * file_name, int line_number, const char * function_name)
Definition at line 786 of file sync.c.
{
  // Same as debug_sync_cond_wait(): skip tracking the atomic unlock/relock.
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return cond_timedwait_impl(cond, mutex, timeout_ns);
}
References mutex.
debug_sync_cond_wait()
int debug_sync_cond_wait (cond_t * cond, mutex_t * mutex, const char * file_name, int line_number, const char * function_name)
Definition at line 775 of file sync.c.
{
  // Note: pthread_cond_wait() atomically releases and re-acquires the mutex,
  // but this happens at the kernel level. Debug tracking can't monitor this atomic
  // operation properly, so we skip cond_on_wait() to avoid false deadlock reports.
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return cond_wait_impl(cond, mutex);
}
References mutex.
debug_sync_destroy()
void debug_sync_destroy (void)
Definition at line 661 of file sync.c.
{
  debug_sync_cleanup_thread();
}
References debug_sync_cleanup_thread().
Referenced by asciichat_shared_destroy(), and server_main().
debug_sync_final_cleanup()
void debug_sync_final_cleanup (void)
Final cleanup of all debug allocations at shutdown.
Definition at line 586 of file sync.c.
{
  // Clean up current thread's mutex stack explicitly
  mutex_stack_cleanup_current_thread();
}
References mutex_stack_cleanup_current_thread().
Referenced by asciichat_shared_destroy().
debug_sync_get_main_thread_id()
uint64_t debug_sync_get_main_thread_id (void)
Definition at line 640 of file sync.c.
{
  return g_debug_main_thread_id;
}
debug_sync_get_stats()
void debug_sync_get_stats (uint64_t * total_acquired, uint64_t * total_released, uint32_t * currently_held)
Definition at line 713 of file sync.c.
{
  if (total_acquired)
    *total_acquired = 0;
  if (total_released)
    *total_released = 0;
  if (currently_held)
    *currently_held = 0;
}
Referenced by stats_logger_thread().
debug_sync_init()
int debug_sync_init (void)
Definition at line 635 of file sync.c.
{
  // debug_sync_set_main_thread_id() should have already been called
  return 0;
}
Referenced by main().
debug_sync_is_cleanup_in_progress()
bool debug_sync_is_cleanup_in_progress (void)
Definition at line 644 of file sync.c.
{
  return atomic_load_bool(&g_cleanup_in_progress);
}
References atomic_load_bool().
Referenced by debug_sync_check_cond_deadlocks().
debug_sync_is_initialized()
bool debug_sync_is_initialized (void)
Definition at line 809 of file sync.c.
{
  return true;
}
Referenced by stats_logger_thread().
debug_sync_mutex_lock()
int debug_sync_mutex_lock (mutex_t * mutex, const char * file_name, int line_number, const char * function_name)
Definition at line 726 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return mutex_lock_impl(mutex);
}
References mutex, and mutex_lock_impl().
debug_sync_mutex_trylock()
int debug_sync_mutex_trylock (mutex_t * mutex, const char * file_name, int line_number, const char * function_name)
Definition at line 733 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return mutex_trylock_impl(mutex);
}
References mutex, and mutex_trylock_impl().
debug_sync_mutex_unlock()
int debug_sync_mutex_unlock (mutex_t * mutex, const char * file_name, int line_number, const char * function_name)
Definition at line 740 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return mutex_unlock_impl(mutex);
}
References mutex, and mutex_unlock_impl().
debug_sync_print_backtrace_delayed()
void debug_sync_print_backtrace_delayed (uint64_t delay_ns)
Schedule delayed backtrace printing on debug thread.
Parameters
delay_ns Nanoseconds to sleep before printing
Definition at line 608 of file sync.c.
{
  mutex_lock(&g_debug_state_request.mutex);
  g_debug_state_request.request_type = DEBUG_REQUEST_BACKTRACE;
  g_debug_state_request.delay_ns = delay_ns;
  atomic_store_bool(&g_debug_state_request.should_run, true);
  cond_signal(&g_debug_state_request.cond);
  mutex_unlock(&g_debug_state_request.mutex);
}
References atomic_store_bool(), and DEBUG_REQUEST_BACKTRACE.
debug_sync_print_state()
void debug_sync_print_state (void)
Definition at line 378 of file sync.c.
{
// Use a single large buffer for all sync state output
#define SYNC_BUFFER_SIZE 65536  // Increased from 8192 to handle many syncs
  log_debug("[debug_sync_print_state] ENTRY");
  char *buffer = SAFE_MALLOC(SYNC_BUFFER_SIZE, char *);
  if (!buffer) {
    log_debug("[debug_sync_print_state] Failed to allocate buffer");
    return;
  }
  sync_buffer_t buf = {.buffer = buffer, .buffer_size = SYNC_BUFFER_SIZE, .offset = 0};
  // Iterate through all registered syncs
  log_debug("[debug_sync_print_state] Iterating mutexes");
  named_registry_for_each(mutex_iter_callback, &buf);
  log_debug("[debug_sync_print_state] Iterating rwlocks");
  named_registry_for_each(rwlock_iter_callback, &buf);
  log_debug("[debug_sync_print_state] Iterating conds");
  named_registry_for_each(cond_iter_callback, &buf);
  named_registry_for_each(atomic_t_iter_callback, &buf);
  named_registry_for_each(atomic_ptr_iter_callback, &buf);
  // Print lock stacks for deadlock analysis
  log_debug("[debug_sync_print_state] Getting lock stacks");
  debug_sync_print_lock_stacks(buf.buffer, buf.buffer_size, &buf.offset);
  // Log everything in one call
  log_debug("[debug_sync_print_state] Buffer size: %zu bytes", buf.offset);
  if (buf.offset > 0) {
    log_info("SYNC_STATE:\n%s", buf.buffer);
  } else {
    log_info("SYNC_STATE: (empty)");
  }
  SAFE_FREE(buffer);
#undef SYNC_BUFFER_SIZE
}
References sync_buffer_t::buffer, sync_buffer_t::buffer_size, named_registry_for_each(), sync_buffer_t::offset, and SYNC_BUFFER_SIZE.
Referenced by crypto_handshake_init().
debug_sync_print_state_delayed()
void debug_sync_print_state_delayed (uint64_t delay_ns)
Schedule delayed debug state printing on debug thread.
Parameters
delay_ns Nanoseconds to sleep before printing
Definition at line 595 of file sync.c.
{
  mutex_lock(&g_debug_state_request.mutex);
  g_debug_state_request.request_type = DEBUG_REQUEST_STATE;
  g_debug_state_request.delay_ns = delay_ns;
  atomic_store_bool(&g_debug_state_request.should_run, true);
  cond_signal(&g_debug_state_request.cond);
  mutex_unlock(&g_debug_state_request.mutex);
}
References atomic_store_bool(), and DEBUG_REQUEST_STATE.
debug_sync_rwlock_rdlock()
int debug_sync_rwlock_rdlock (rwlock_t * lock, const char * file_name, int line_number, const char * function_name)
Definition at line 747 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return rwlock_rdlock_impl(lock);
}
References rwlock_rdlock_impl().
debug_sync_rwlock_rdunlock()
int debug_sync_rwlock_rdunlock (rwlock_t * lock, const char * file_name, int line_number, const char * function_name)
Definition at line 754 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return rwlock_rdunlock_impl(lock);
}
References rwlock_rdunlock_impl().
debug_sync_rwlock_wrlock()
int debug_sync_rwlock_wrlock (rwlock_t * lock, const char * file_name, int line_number, const char * function_name)
Definition at line 761 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return rwlock_wrlock_impl(lock);
}
References rwlock_wrlock_impl().
debug_sync_rwlock_wrunlock()
int debug_sync_rwlock_wrunlock (rwlock_t * lock, const char * file_name, int line_number, const char * function_name)
Definition at line 768 of file sync.c.
{
  (void)file_name;
  (void)line_number;
  (void)function_name;
  return rwlock_wrunlock_impl(lock);
}
References rwlock_wrunlock_impl().
debug_sync_set_main_thread_id()
void debug_sync_set_main_thread_id (void)
Definition at line 630 of file sync.c.
{
  // Save main thread ID for memory reporting (call very early)
  g_debug_main_thread_id = asciichat_thread_current_id();
}
References asciichat_thread_current_id().
Referenced by main().
debug_sync_set_memory_report_interval()
void debug_sync_set_memory_report_interval (uint64_t interval_ns)
Set periodic memory report interval.
Parameters
interval_ns Interval in nanoseconds (0 to disable)
Definition at line 621 of file sync.c.
{
  g_debug_state_request.memory_report_interval_ns = interval_ns;
  g_debug_state_request.last_memory_report_time_ns = 0; // Reset timer
}
debug_sync_start_thread()
int debug_sync_start_thread (void)
Definition at line 648 of file sync.c.
{
  // Initialize mutex and condition variable for signal wakeup
  if (!g_debug_state_request.initialized) {
    mutex_init(&g_debug_state_request.mutex, "debug_sync_state");
    cond_init(&g_debug_state_request.cond, "debug_sync_signal");
    g_debug_state_request.initialized = true;
  }
  atomic_store_bool(&g_debug_state_request.should_exit, false);
  int err = asciichat_thread_create(&g_debug_thread, "debug_sync", debug_print_thread_fn, NULL);
  return err;
}
References asciichat_thread_create(), atomic_store_bool(), and mutex_init().
Referenced by main().
debug_sync_trigger_print()
void debug_sync_trigger_print (void)
Definition at line 701 of file sync.c.
{
  // Set flag to trigger printing on debug thread (from SIGUSR1 handler).
  // We don't call debug_sync_print_state() directly here to avoid logging
  // in signal handler context, which could deadlock with logging mutexes.
  // Uses atomic_store for thread-safe flag setting from signal handler.
  //
  // Signal the condition variable to wake up the debug thread immediately
  // (without waiting for the 100ms timeout).
  atomic_store_bool(&g_debug_state_request.signal_triggered, true);
  cond_signal(&g_debug_state_request.cond);
}
References atomic_store_bool().
Referenced by session_handle_keyboard_input().