ascii-chat: system.c File Reference
system.c File Reference
🔧 Shared cross-platform system utilities (safe string functions, etc.)
Data Structures
struct bin_cache_entry_t
Cache entry for binary PATH lookup.
Macros
#define BIN_SUFFIX ""
#define PLATFORM_MAX_PATH_LENGTH 4096
Functions
bool check_binary_in_path_uncached (const char *bin_name)
void platform_cleanup_binary_path_cache (void)
Cleanup the binary PATH cache.
int safe_snprintf (char *buffer, size_t buffer_size, const char *format,...)
Safe formatted string printing to buffer.
int safe_fprintf (FILE *stream, const char *format,...)
Safe formatted output to file stream.
int safe_vsnprintf (char *buffer, size_t buffer_size, const char *format, va_list ap)
Safe formatted string printing with va_list.
Detailed Description
🔧 Shared cross-platform system utilities (safe string functions, etc.)
Definition in file system.c.
Macro Definition Documentation
BIN_SUFFIX
#define BIN_SUFFIX ""
Definition at line 27 of file system.c.
PLATFORM_MAX_PATH_LENGTH
#define PLATFORM_MAX_PATH_LENGTH 4096
Maximum path length supported by the operating system
Platform-specific values:
Windows: 32767 characters (extended-length path with \?\ prefix)
Linux: 4096 bytes (PATH_MAX from limits.h)
macOS: 1024 bytes (PATH_MAX from sys/syslimits.h)
Note: Windows legacy MAX_PATH (260) is too restrictive for modern use. We use the extended-length limit instead.
Definition at line 66 of file system.c.
Referenced by acds_identity_save(), acds_main(), discovery_keys_clear_cache(), discovery_keys_load_cached(), discovery_keys_save_cached(), get_binary_file_address_offsets(), get_log_dir(), gpg_agent_connect(), gpg_sign_with_key(), gpg_verify_detached_ed25519(), gpg_verify_signature_with_binary(), options_init(), parse_gpg_keys_from_response(), path_is_within_base(), path_validate_user_path(), and query_init().
Function Documentation
check_binary_in_path_uncached()
bool check_binary_in_path_uncached (const char * bin_name) extern
Referenced by platform_is_binary_in_path().
platform_cleanup_binary_path_cache()
void platform_cleanup_binary_path_cache (void)
Cleanup the binary PATH cache.
Definition at line 226 of file system.c.
{
  if (!lifecycle_shutdown(&g_cache_lc)) {
    return;
  }
  if (g_bin_path_cache) {
    rwlock_wrlock(&g_cache_rwlock);
    // Free all cached entries using uthash iteration
    bin_cache_entry_t *entry, *tmp;
    HASH_ITER(hh, g_bin_path_cache, entry, tmp) {
      HASH_DELETE(hh, g_bin_path_cache, entry);
      free_cache_entry(entry);
    }
    rwlock_wrunlock(&g_cache_rwlock);
    rwlock_destroy(&g_cache_rwlock);
    g_bin_path_cache = NULL;
  }
}
References lifecycle_shutdown().
safe_fprintf()
int safe_fprintf (FILE * stream, const char * format, ...)
Safe formatted output to file stream.
Parameters
stream Output file stream
format Printf-style format string
Returns
Number of characters written, or -1 on error
Safely formats and prints output to a file stream. Returns the number of characters written, or -1 on error.
Definition at line 287 of file system.c.
{
  if (!stream || !format) {
    return -1;
  }
  va_list args;
  va_start(args, format);
  int ret = vfprintf(stream, format, args);
  va_end(args);
  return ret;
}
References args.
Referenced by add_known_host(), asciichat_fatal_with_context(), asciichat_print_error_context(), log_init(), log_labeled(), log_msg(), log_plain_msg(), and webcam_print_init_error_help().
safe_snprintf()
int safe_snprintf (char * buffer, size_t buffer_size, const char * format, ...)
Safe formatted string printing to buffer.
Parameters
buffer Output buffer
buffer_size Size of output buffer
format Printf-style format string
Returns
Number of characters written, or -1 on error
Safely formats a string into a buffer with bounds checking. Uses platform_snprintf for cross-platform implementation. Returns the number of characters written (not including null terminator). Returns -1 if buffer is too small.
Definition at line 263 of file system.c.
{
  if (!buffer || !format || buffer_size == 0) {
    return -1;
  }
  va_list args;
  va_start(args, format);
  /* Delegate to platform_snprintf for actual formatting */
  int ret = platform_vsnprintf(buffer, buffer_size, format, args);
  va_end(args);
  return ret;
}
References args, buffer_size, and platform_vsnprintf().
Referenced by acds_client_connect(), acds_identity_default_path(), acds_identity_fingerprint(), acds_main(), acds_string_generate(), add_client(), asciichat_instr_log_line(), asciichat_instr_log_pc(), backtrace_format(), backtrace_print(), build_github_gpg_url(), build_github_ssh_url(), build_gitlab_gpg_url(), build_gitlab_ssh_url(), capture_init(), check_gpg_key_expiry(), check_known_host(), check_known_host_no_identity(), colored_string(), colorize_log_message(), colorize_named_string(), colorscheme_compile_scheme(), colorscheme_export_scheme(), config_load_and_apply(), create_client_render_threads(), crypto_get_rekey_status(), crypto_handshake_client_key_exchange(), crypto_handshake_server_auth_challenge(), crypto_handshake_server_start(), discovery_keys_fetch_github(), discovery_keys_fetch_gitlab(), discovery_keys_get_cache_path(), discovery_keys_save_cached(), display_mitm_warning(), expand_path(), find_similar_option_with_mode(), format_available_modes(), format_bytes_pretty(), format_gpg_key_display(), format_mode_names(), format_option_default_value_str(), format_public_key(), format_uptime_hms(), get_current_time_formatted(), get_discovery_database_dir(), get_known_hosts_path(), get_log_dir(), get_manpage_template(), gpg_agent_sign(), gpg_get_public_key(), gpg_sign_detached_ed25519(), gpg_sign_with_key(), gpg_verify_detached_ed25519(), gpg_verify_signature(), gpg_verify_signature_with_binary(), https_get(), ice_format_candidate(), image_print_color(), log_mmap_write(), log_recolor_plain_entry(), log_template_apply(), manpage_content_generate_environment(), manpage_content_generate_environment_with_manual(), manpage_content_generate_examples(), manpage_content_generate_options(), manpage_content_generate_positional(), manpage_content_generate_usage(), manpage_fmt_write_title(), manpage_merger_generate_synopsis(), manpage_merger_generate_usage(), nat_upnp_get_address(), options_config_calculate_max_col_width(), options_config_print_options_sections_with_width(), options_config_print_usage(), options_format_default_value(), options_init(), options_preset_unified(), options_print_help_for_mode(), parallel_connect(), parse_client_address(), parse_color_filter(), parse_color_mode(), parse_gpg_key(), parse_gpg_key_binary(), parse_gpg_keys_from_response(), parse_log_level(), parse_palette_chars(), parse_palette_type(), parse_port_option(), parse_private_key(), parse_render_mode(), parse_render_theme(), parse_server_bind_address(), parse_ssh_private_key(), path_validate_user_path(), prompt_unknown_host(), prompt_unknown_host_no_identity(), pubkey_to_hex(), query_init(), remove_known_host(), rgb_to_truecolor_ansi(), sdp_generate_answer(), sdp_generate_offer(), server_main(), session_capture_create(), session_network_capture_create(), stats_logger_thread(), test_get_binary_path(), time_pretty(), turn_generate_credentials(), and yt_dlp_extract_stream_url().
safe_vsnprintf()
int safe_vsnprintf (char * buffer, size_t buffer_size, const char * format, va_list ap)
Safe formatted string printing with va_list.
Parameters
buffer Output buffer (can be NULL if buffer_size is 0 for size calculation)
buffer_size Size of output buffer
format Printf-style format string
ap Variable argument list
Returns
Number of characters written, or -1 on error
Safely formats a string into a buffer with bounds checking using va_list. Uses platform_vsnprintf for cross-platform implementation. Returns the number of characters written (not including null terminator). Special case: NULL buffer with size 0 returns required buffer size for size calculation. Returns -1 if buffer is too small, format is invalid, or buffer is NULL with size > 0.
Definition at line 314 of file system.c.
{
  if (!format) {
    return -1;
  }
  // Allow NULL buffer with size 0 for size calculation (standard vsnprintf behavior)
  if (!buffer && buffer_size > 0) {
    return -1; // Non-NULL buffer required when buffer_size > 0
  }
  /* Delegate to platform_vsnprintf for actual formatting */
  return platform_vsnprintf(buffer, buffer_size, format, ap);
}
References buffer_size, and platform_vsnprintf().
Referenced by disconnect_client_for_bad_data(), format_message(), log_file_msg(), log_mmap_write(), log_msg(), and log_plain_msg().