ascii-chat: threading.c File Reference
threading.c File Reference
Threading abstraction for WASM/Emscripten using pthreads.
Functions
int mutex_init (mutex_t *mutex, const char *name)
int mutex_destroy (mutex_t *mutex)
int mutex_lock_impl (mutex_t *mutex)
int mutex_trylock_impl (mutex_t *mutex)
int mutex_unlock_impl (mutex_t *mutex)
int asciichat_thread_create (asciichat_thread_t *thread, const char *name, void *(*start_routine)(void *), void *arg)
int asciichat_thread_join (asciichat_thread_t *thread, void **retval)
int asciichat_thread_detach (asciichat_thread_t *thread)
asciichat_thread_t asciichat_thread_self (void)
int asciichat_thread_equal (asciichat_thread_t t1, asciichat_thread_t t2)
int rwlock_init (rwlock_t *rwlock, const char *name)
int rwlock_rdlock_impl (rwlock_t *rwlock)
int rwlock_wrlock_impl (rwlock_t *rwlock)
int rwlock_rdunlock_impl (rwlock_t *rwlock)
int rwlock_wrunlock_impl (rwlock_t *rwlock)
uint64_t asciichat_thread_current_id (void)
int ascii_tls_key_create (tls_key_t *key, void(*destructor)(void *))
int ascii_tls_key_delete (tls_key_t key)
void * ascii_tls_get (tls_key_t key)
int ascii_tls_set (tls_key_t key, void *value)
Detailed Description
Threading abstraction for WASM/Emscripten using pthreads.
Definition in file threading.c.
Function Documentation
ascii_tls_get()
void * ascii_tls_get (tls_key_t key)
Definition at line 100 of file threading.c.
{
  return pthread_getspecific(key);
}
Referenced by asciichat_instr_runtime_get(), and mutex_stack_cleanup_current_thread().
ascii_tls_key_create()
int ascii_tls_key_create (tls_key_t * key, void(* destructor)(void *))
Definition at line 92 of file threading.c.
{
  return pthread_key_create(key, destructor);
}
ascii_tls_key_delete()
int ascii_tls_key_delete (tls_key_t key)
Definition at line 96 of file threading.c.
{
  return pthread_key_delete(key);
}
Referenced by asciichat_instr_runtime_global_destroy(), and mutex_stack_cleanup().
ascii_tls_set()
int ascii_tls_set (tls_key_t key, void * value)
Definition at line 104 of file threading.c.
{
  return pthread_setspecific(key, value);
}
Referenced by asciichat_instr_runtime_get(), and mutex_stack_cleanup_current_thread().
asciichat_thread_create()
int asciichat_thread_create (asciichat_thread_t * thread, const char * name, void *(* start_routine)(void *), void * arg)
Definition at line 43 of file threading.c.
{
  (void)name;  // Unused in WASM - no thread registry
  return pthread_create(thread, NULL, start_routine, arg);
}
Referenced by acip_websocket_client_transport_create(), audio_start_duplex(), create_client_render_threads(), debug_sync_start_thread(), discover_session_parallel(), ffmpeg_decoder_start_prefetch(), mirror_main(), parallel_connect(), server_main(), session_host_start(), session_host_start_render(), session_participant_start_audio_capture(), session_participant_start_video_capture(), session_pipeline_create(), splash_intro_start(), tcp_server_run(), tcp_server_spawn_thread(), thread_create_or_fail(), thread_pool_create_with_workers(), and thread_pool_spawn().
asciichat_thread_current_id()
uint64_t asciichat_thread_current_id (void)
Definition at line 87 of file threading.c.
{
  return (uint64_t)pthread_self();
}
Referenced by asciichat_instr_runtime_get(), cond_on_wait(), debug_sync_set_main_thread_id(), log_json_async_safe(), log_json_write(), mutex_on_lock(), mutex_on_trylock(), rwlock_on_unlock(), and rwlock_on_wrlock().
asciichat_thread_detach()
int asciichat_thread_detach (asciichat_thread_t * thread)
Definition at line 52 of file threading.c.
{
  return pthread_detach(*thread);
}
asciichat_thread_equal()
int asciichat_thread_equal (asciichat_thread_t t1, asciichat_thread_t t2)
Definition at line 60 of file threading.c.
{
  return pthread_equal(t1, t2);
}
Referenced by mutex_stack_cleanup_current_thread(), and remove_client().
asciichat_thread_join()
int asciichat_thread_join (asciichat_thread_t * thread, void ** retval)
Definition at line 48 of file threading.c.
{
  return pthread_join(*thread, retval);
}
Referenced by audio_destroy(), audio_stop_duplex(), discover_session_parallel(), ffmpeg_decoder_destroy(), parallel_connect(), remove_client(), server_main(), session_host_start(), session_host_stop(), session_host_stop_render(), session_participant_stop_audio_capture(), session_participant_stop_video_capture(), session_pipeline_create(), session_pipeline_destroy(), splash_wait_for_animation(), stop_client_render_threads(), and stop_client_threads().
asciichat_thread_self()
asciichat_thread_t asciichat_thread_self (void)
Definition at line 56 of file threading.c.
{
  return pthread_self();
}
Referenced by backtrace_print(), client_receive_thread(), log_lock_terminal(), log_plain_msg(), main(), mutex_stack_cleanup_current_thread(), and remove_client().
mutex_destroy()
int mutex_destroy (mutex_t * mutex)
Definition at line 22 of file threading.c.
{
  (void)mutex;
  return 0; // Success
}
References mutex.
Referenced by acip_webrtc_transport_create(), acip_websocket_client_transport_create(), acip_websocket_server_transport_create(), app_client_create(), app_client_destroy(), audio_destroy(), audio_init(), audio_ring_buffer_destroy(), audio_sender_cleanup(), audio_sender_init(), buffer_pool_destroy(), colorscheme_destroy(), discover_session_parallel(), ffmpeg_decoder_create(), ffmpeg_decoder_create_stdin(), ffmpeg_decoder_destroy(), framebuffer_create(), framebuffer_create_multi(), framebuffer_destroy(), lifecycle_reset(), lifecycle_shutdown(), media_source_create(), media_source_destroy(), options_state_destroy(), options_state_init(), parallel_connect(), remove_client(), server_connection_cleanup(), server_main(), session_host_destroy(), session_log_buffer_destroy(), tcp_client_destroy(), thread_pool_create_with_workers(), thread_pool_destroy(), video_frame_buffer_destroy(), webrtc_peer_manager_destroy(), and websocket_client_destroy().
mutex_init()
int mutex_init (mutex_t * mutex, const char * name)
Definition at line 16 of file threading.c.
{
  (void)mutex;
  (void)name;
  return 0; // Success
}
References mutex.
Referenced by acip_tcp_transport_create(), acip_webrtc_transport_create(), acip_websocket_client_transport_create(), acip_websocket_server_transport_create(), add_client(), add_webrtc_client(), app_client_create(), audio_init(), audio_sender_init(), buffer_pool_create(), colorscheme_init(), debug_sync_start_thread(), discover_session_parallel(), ffmpeg_decoder_create(), ffmpeg_decoder_create_stdin(), framebuffer_create(), framebuffer_create_multi(), lifecycle_init(), media_source_create(), memory_backend_create(), mirror_main(), options_state_init(), parallel_connect(), server_connection_init(), server_main(), session_host_create(), session_log_buffer_create(), splash_set_update_notification(), tcp_client_create(), thread_pool_create(), thread_pool_create_with_workers(), video_frame_buffer_create(), webrtc_peer_manager_create(), and websocket_client_create().
mutex_lock_impl()
int mutex_lock_impl (mutex_t * mutex)
Definition at line 27 of file threading.c.
{
  (void)mutex;
  return 0; // Success - no-op
}
References mutex.
Referenced by debug_sync_mutex_lock().
mutex_trylock_impl()
int mutex_trylock_impl (mutex_t * mutex)
Definition at line 32 of file threading.c.
{
  (void)mutex;
  return 0; // Success - no-op
}
References mutex.
Referenced by debug_sync_mutex_trylock().
mutex_unlock_impl()
int mutex_unlock_impl (mutex_t * mutex)
Definition at line 37 of file threading.c.
{
  (void)mutex;
  return 0; // Success - no-op
}
References mutex.
Referenced by debug_sync_mutex_unlock().
rwlock_init()
int rwlock_init (rwlock_t * rwlock, const char * name)
Definition at line 65 of file threading.c.
{
  (void)name;
  return pthread_rwlock_init((pthread_rwlock_t *)rwlock, NULL);
}
References rwlock.
Referenced by lifecycle_init(), mixer_create(), named_init(), server_main(), symbol_cache_init(), and tcp_server_init().
rwlock_rdlock_impl()
int rwlock_rdlock_impl (rwlock_t * rwlock)
Definition at line 70 of file threading.c.
{
  return pthread_rwlock_rdlock((pthread_rwlock_t *)rwlock);
}
References rwlock.
Referenced by debug_sync_rwlock_rdlock().
rwlock_rdunlock_impl()
int rwlock_rdunlock_impl (rwlock_t * rwlock)
Definition at line 78 of file threading.c.
{
  return pthread_rwlock_unlock((pthread_rwlock_t *)rwlock);
}
References rwlock.
Referenced by debug_sync_rwlock_rdunlock().
rwlock_wrlock_impl()
int rwlock_wrlock_impl (rwlock_t * rwlock)
Definition at line 74 of file threading.c.
{
  return pthread_rwlock_wrlock((pthread_rwlock_t *)rwlock);
}
References rwlock.
Referenced by debug_sync_rwlock_wrlock().
rwlock_wrunlock_impl()
int rwlock_wrunlock_impl (rwlock_t * rwlock)
Definition at line 82 of file threading.c.
{
  return pthread_rwlock_unlock((pthread_rwlock_t *)rwlock);
}
References rwlock.
Referenced by debug_sync_rwlock_wrunlock().