ascii-chat: topology.c File Reference
topology.c File Reference
Ring topology implementation.
Data Structures
struct consensus_topology
Ring topology for consensus participants.
Typedefs
typedef struct consensus_topology consensus_topology_t
Ring topology for consensus participants.
Functions
asciichat_error_t consensus_topology_create (const uint8_t participant_ids[64][16], int num_participants, const uint8_t my_id[16], consensus_topology_t **out_topology)
void consensus_topology_destroy (consensus_topology_t *topology)
int consensus_topology_get_position (const consensus_topology_t *topology)
bool consensus_topology_am_leader (const consensus_topology_t *topology)
asciichat_error_t consensus_topology_get_next (const consensus_topology_t *topology, uint8_t out_id[16])
asciichat_error_t consensus_topology_get_prev (const consensus_topology_t *topology, uint8_t out_id[16])
asciichat_error_t consensus_topology_get_leader (const consensus_topology_t *topology, uint8_t out_id[16])
asciichat_error_t consensus_topology_get_all (const consensus_topology_t *topology, uint8_t out_ids[64][16], int *out_count)
Detailed Description
Ring topology implementation.
Definition in file topology.c.
Typedef Documentation
consensus_topology_t
typedef struct consensus_topology consensus_topology_t
Ring topology for consensus participants.
Maintains a sorted list of participant IDs for ring-based consensus algorithms and leader election.
Function Documentation
consensus_topology_am_leader()
bool consensus_topology_am_leader (const consensus_topology_t * topology)
Definition at line 76 of file topology.c.
{
  if (!topology)
    return false;
  return topology->my_position == (topology->num_participants - 1);
}
References consensus_topology::my_position, and consensus_topology::num_participants.
Referenced by consensus_coordinator_process(), consensus_state_collection_complete(), and consensus_state_is_leader().
consensus_topology_create()
asciichat_error_t consensus_topology_create (const uint8_t participant_ids[64][16], int num_participants, const uint8_t my_id[16], consensus_topology_t ** out_topology)
Definition at line 38 of file topology.c.
{
  if (!participant_ids || !my_id || !out_topology || num_participants <= 0 || num_participants > 64) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid topology creation parameters");
  }
  consensus_topology_t *topology = SAFE_MALLOC(sizeof(*topology), consensus_topology_t *);
  memset(topology, 0, sizeof(*topology));
  // Copy and sort participant IDs lexicographically
  memcpy(topology->participant_ids, participant_ids, num_participants * 16);
  topology->num_participants = num_participants;
  qsort(topology->participant_ids, num_participants, 16, qsort_uuid_compare);
  // Find my position
  topology->my_position = find_uuid_position(topology->participant_ids, num_participants, my_id);
  if (topology->my_position < 0) {
    SAFE_FREE(topology);
    return SET_ERRNO(ERROR_INVALID_PARAM, "My UUID not found in participant list");
  }
  *out_topology = topology;
  return ASCIICHAT_OK;
}
References consensus_topology::my_position, consensus_topology::num_participants, and consensus_topology::participant_ids.
Referenced by session_consensus_create(), and session_consensus_set_topology().
consensus_topology_destroy()
void consensus_topology_destroy (consensus_topology_t * topology)
Definition at line 64 of file topology.c.
{
  if (topology) {
    SAFE_FREE(topology);
  }
}
Referenced by session_consensus_create(), session_consensus_destroy(), and session_consensus_set_topology().
consensus_topology_get_all()
asciichat_error_t consensus_topology_get_all (const consensus_topology_t * topology, uint8_t out_ids[64][16], int * out_count)
Definition at line 111 of file topology.c.
{
  if (!topology || !out_ids || !out_count) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
  }
  memcpy(out_ids, topology->participant_ids, topology->num_participants * 16);
  *out_count = topology->num_participants;
  return ASCIICHAT_OK;
}
References consensus_topology::num_participants, and consensus_topology::participant_ids.
consensus_topology_get_leader()
asciichat_error_t consensus_topology_get_leader (const consensus_topology_t * topology, uint8_t out_id[16])
Definition at line 102 of file topology.c.
{
  if (!topology || !out_id) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
  }
  memcpy(out_id, topology->participant_ids[topology->num_participants - 1], 16);
  return ASCIICHAT_OK;
}
References consensus_topology::num_participants, and consensus_topology::participant_ids.
consensus_topology_get_next()
asciichat_error_t consensus_topology_get_next (const consensus_topology_t * topology, uint8_t out_id[16])
Definition at line 82 of file topology.c.
{
  if (!topology || !out_id) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
  }
  int next_pos = (topology->my_position + 1) % topology->num_participants;
  memcpy(out_id, topology->participant_ids[next_pos], 16);
  return ASCIICHAT_OK;
}
References consensus_topology::my_position, consensus_topology::num_participants, and consensus_topology::participant_ids.
consensus_topology_get_position()
int consensus_topology_get_position (const consensus_topology_t * topology)
Definition at line 70 of file topology.c.
{
  if (!topology)
    return -1;
  return topology->my_position;
}
References consensus_topology::my_position.
consensus_topology_get_prev()
asciichat_error_t consensus_topology_get_prev (const consensus_topology_t * topology, uint8_t out_id[16])
Definition at line 92 of file topology.c.
{
  if (!topology || !out_id) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Invalid parameters");
  }
  int prev_pos = (topology->my_position - 1 + topology->num_participants) % topology->num_participants;
  memcpy(out_id, topology->participant_ids[prev_pos], 16);
  return ASCIICHAT_OK;
}
References consensus_topology::my_position, consensus_topology::num_participants, and consensus_topology::participant_ids.