ascii-chat: mdns.c File Reference
mdns.c File Reference
mDNS service discovery UI wrapper for interactive server selection
Macros
#define ANSI_CLEAR "\033[2J\033[H"
ANSI escape codes for TUI.
#define ANSI_BOLD "\033[1m"
#define ANSI_RESET "\033[0m"
#define ANSI_CYAN "\033[36m"
#define ANSI_GREEN "\033[32m"
#define ANSI_YELLOW "\033[33m"
#define ANSI_CLEAR_LINE "\033[K"
Functions
void ui_mdns_log_init (void)
void ui_mdns_log_destroy (void)
void ui_mdns_log_clear (void)
void ui_mdns_log_append (const char *message)
ui_mdns_server_t * ui_mdns_query (const ui_mdns_config_t *config, int *out_count)
TUI wrapper around core mDNS discovery.
void ui_mdns_free_results (ui_mdns_server_t *servers)
Free results from mDNS discovery.
int ui_mdns_prompt_selection (const ui_mdns_server_t *servers, int count)
Interactive server selection.
int ui_mdns_select (const ui_mdns_server_t *servers, int count)
TUI-based server selection with formatted display.
const char * ui_mdns_get_best_address (const ui_mdns_server_t *server)
Get best address for a server.
Detailed Description
mDNS service discovery UI wrapper for interactive server selection
Pure TUI wrapper that calls discovery_mdns_query() from discovery.c. Provides interactive terminal UI for server selection and address resolution.
Definition in file ui/mdns.c.
Macro Definition Documentation
ANSI_BOLD
#define ANSI_BOLD "\033[1m"
Definition at line 129 of file ui/mdns.c.
Referenced by ui_mdns_select().
ANSI_CLEAR
#define ANSI_CLEAR "\033[2J\033[H"
ANSI escape codes for TUI.
Definition at line 128 of file ui/mdns.c.
Referenced by ui_mdns_select().
ANSI_CLEAR_LINE
#define ANSI_CLEAR_LINE "\033[K"
Definition at line 134 of file ui/mdns.c.
ANSI_CYAN
#define ANSI_CYAN "\033[36m"
Definition at line 131 of file ui/mdns.c.
Referenced by ui_mdns_select().
ANSI_GREEN
#define ANSI_GREEN "\033[32m"
Definition at line 132 of file ui/mdns.c.
Referenced by ui_mdns_select().
ANSI_RESET
#define ANSI_RESET "\033[0m"
Definition at line 130 of file ui/mdns.c.
Referenced by ui_mdns_select().
ANSI_YELLOW
#define ANSI_YELLOW "\033[33m"
Definition at line 133 of file ui/mdns.c.
Referenced by ui_mdns_select().
Function Documentation
ui_mdns_free_results()
void ui_mdns_free_results (ui_mdns_server_t * servers)
Free results from mDNS discovery.
Definition at line 76 of file ui/mdns.c.
{
  discovery_mdns_destroy(servers);
}
References discovery_mdns_destroy().
Referenced by client_main().
ui_mdns_get_best_address()
const char * ui_mdns_get_best_address (const ui_mdns_server_t * server)
Get best address for a server.
Definition at line 235 of file ui/mdns.c.
{
  if (!server) {
    return "";
  }
  // Prefer IPv4 > name > IPv6
  if (server->ipv4[0] != '\0') {
    return server->ipv4;
  }
  if (server->name[0] != '\0') {
    return server->name;
  }
  if (server->ipv6[0] != '\0') {
    return server->ipv6;
  }
  return server->address; // Fallback to address field
}
Referenced by client_main(), ui_mdns_prompt_selection(), and ui_mdns_select().
ui_mdns_log_append()
void ui_mdns_log_append (const char * message)
Definition at line 45 of file ui/mdns.c.
{
  if (message) {
    log_info("%s", message);
  }
}
ui_mdns_log_clear()
void ui_mdns_log_clear (void)
Definition at line 41 of file ui/mdns.c.
{
  terminal_screen_log_clear();
}
References terminal_screen_log_clear().
ui_mdns_log_destroy()
void ui_mdns_log_destroy (void)
Definition at line 36 of file ui/mdns.c.
{
  log_clear_session_log_buffer();
  terminal_screen_log_destroy();
}
References log_clear_session_log_buffer(), and terminal_screen_log_destroy().
ui_mdns_log_init()
void ui_mdns_log_init (void)
Definition at line 29 of file ui/mdns.c.
{
  session_log_buffer_t *buf = terminal_screen_log_init();
  if (buf) {
    log_set_session_log_buffer(buf);
  }
}
References log_set_session_log_buffer(), and terminal_screen_log_init().
ui_mdns_prompt_selection()
int ui_mdns_prompt_selection (const ui_mdns_server_t * servers, int count)
Interactive server selection.
Definition at line 83 of file ui/mdns.c.
{
  if (!servers || count <= 0) {
    return -1;
  }
  // Display available servers
  printf("\nAvailable ascii-chat servers on LAN:\n");
  for (int i = 0; i < count; i++) {
    const ui_mdns_server_t *srv = &servers[i];
    const char *addr = ui_mdns_get_best_address(srv);
    printf("  %d. %s (%s:%u)\n", i + 1, srv->name, addr, srv->port);
  }
  // Prompt for selection
  printf("\nSelect server (1-%d) or press Enter to cancel: ", count);
  fflush(stdout);
  // Read user input
  char input[32];
  if (fgets(input, sizeof(input), stdin) == NULL) {
    printf("\n");
    return -1; // EOF or error
  }
  // Check for empty input (Enter pressed)
  if (input[0] == '\n' || input[0] == '\r' || input[0] == '\0') {
    return -1; // User cancelled
  }
  // Parse input as number
  char *endptr;
  long selection = strtol(input, &endptr, 10);
  // Validate input
  if (selection < 1 || selection > count) {
    printf("⚠️  Invalid selection. Please enter a number between 1 and %d\n", count);
    return ui_mdns_prompt_selection(servers, count); // Re-prompt
  }
  return (int)(selection - 1); // Convert to 0-based index
}
References ui_mdns_get_best_address(), and ui_mdns_prompt_selection().
Referenced by ui_mdns_prompt_selection().
ui_mdns_query()
ui_mdns_server_t * ui_mdns_query (const ui_mdns_config_t * config, int * out_count)
TUI wrapper around core mDNS discovery.
Calls discovery_mdns_query() from discovery.c with TUI-friendly configuration.
Definition at line 56 of file ui/mdns.c.
{
  if (!out_count) {
    SET_ERRNO(ERROR_INVALID_PARAM, "out_count pointer is NULL");
    return NULL;
  }
  *out_count = 0;
  // Apply defaults if needed
  int timeout_ms = (config && config->timeout_ms > 0) ? config->timeout_ms : 2000;
  int max_servers = (config && config->max_servers > 0) ? config->max_servers : 20;
  bool quiet = (config && config->quiet);
  // Call the core mDNS discovery function from discovery.c
  return discovery_mdns_query(timeout_ms, max_servers, quiet, out_count);
}
References discovery_mdns_query().
Referenced by client_main().
ui_mdns_select()
int ui_mdns_select (const ui_mdns_server_t * servers, int count)
TUI-based server selection with formatted display.
Displays discovered servers in a terminal UI with the following features:
Clears terminal and displays formatted server list
Shows "No results" message if no servers available
Allows numeric input for selection
Shows helpful prompts and icons
Parameters
servers Array of discovered servers
count Number of servers
Returns
0-based index of selected server, or -1 to cancel
Definition at line 149 of file ui/mdns.c.
{
  if (!servers || count <= 0) {
    // No servers found - return special code
    // Message will be printed at exit in client main
    return -1;
  }
  // Lock terminal to prevent concurrent logging from overwriting TUI
  bool prev_lock_state = log_lock_terminal();
  // Clear terminal
  log_plain("%s", ANSI_CLEAR);
  // Display header
  log_plain("\n");
  log_plain("%s╭─ 🔍 ascii-chat Server Discovery %s────────────╮%s\n", ANSI_BOLD, ANSI_RESET, ANSI_BOLD);
  log_plain("│%s\n", ANSI_RESET);
  log_plain("%s│%s Found %d server%s on your local network:%s\n", ANSI_BOLD, ANSI_GREEN, count, count == 1 ? "" : "s",
            ANSI_RESET);
  log_plain("%s│%s\n", ANSI_BOLD, ANSI_RESET);
  // Display server list with formatting
  for (int i = 0; i < count; i++) {
    const ui_mdns_server_t *srv = &servers[i];
    const char *addr = ui_mdns_get_best_address(srv);
    log_plain("%s│%s  ", ANSI_BOLD, ANSI_RESET);
    log_plain("%s[%d]%s %-30s %s%s:%u%s", ANSI_CYAN, i + 1, ANSI_RESET, srv->name, ANSI_YELLOW, addr, srv->port,
              ANSI_RESET);
    log_plain("\n");
  }
  log_plain("%s│%s\n", ANSI_BOLD, ANSI_RESET);
  log_plain("%s╰────────────────────────────────────────────╯%s\n", ANSI_BOLD, ANSI_RESET);
  // Prompt for selection
  log_plain("\n");
  log_plain("Enter server number (1-%d) or press Enter to cancel: ", count);
  fflush(stdout);
  // Unlock before waiting for input (user might take time)
  log_unlock_terminal(prev_lock_state);
  // Read user input
  char input[32];
  if (fgets(input, sizeof(input), stdin) == NULL) {
    return -1;
  }
  // Check for empty input (Enter pressed)
  if (input[0] == '\n' || input[0] == '\r' || input[0] == '\0') {
    return -1;
  }
  // Parse input as number
  char *endptr;
  long selection = strtol(input, &endptr, 10);
  // Validate input
  if (selection < 1 || selection > count) {
    printf("%sError:%s Please enter a number between 1 and %d\n\n", ANSI_YELLOW, ANSI_RESET, count);
    return ui_mdns_select(servers, count); // Re-prompt
  }
  // Lock terminal again for final output
  prev_lock_state = log_lock_terminal();
  // Clear screen and show connection status
  log_plain("%s", ANSI_CLEAR);
  log_plain("\n");
  log_plain("%s🔗 Connecting to %s...%s\n", ANSI_GREEN, servers[selection - 1].name, ANSI_RESET);
  log_plain("\n");
  fflush(stdout);
  // Brief delay so user can see the selection before logs overwrite it
  platform_sleep_ms(200);
  // Unlock terminal now that TUI is complete
  log_unlock_terminal(prev_lock_state);
  return (int)(selection - 1); // Convert to 0-based index
}
References ANSI_BOLD, ANSI_CLEAR, ANSI_CYAN, ANSI_GREEN, ANSI_RESET, ANSI_YELLOW, log_lock_terminal(), log_unlock_terminal(), platform_sleep_ms(), ui_mdns_get_best_address(), and ui_mdns_select().
Referenced by client_main(), and ui_mdns_select().