ascii-chat: upnp.c File Reference
upnp.c File Reference
UPnP/NAT-PMP port mapping implementation.
Functions
asciichat_error_t nat_upnp_open (uint16_t internal_port, const char *description, nat_upnp_context_t **ctx)
void nat_upnp_close (nat_upnp_context_t **ctx)
bool nat_upnp_is_active (const nat_upnp_context_t *ctx)
asciichat_error_t nat_upnp_refresh (nat_upnp_context_t *ctx)
asciichat_error_t nat_upnp_get_address (const nat_upnp_context_t *ctx, char *addr, size_t addr_len)
Detailed Description
UPnP/NAT-PMP port mapping implementation.
Strategy for enabling direct TCP without WebRTC:
Try UPnP discovery (works on ~90% of consumer routers)
Fall back to NAT-PMP if UPnP fails (Apple/Time Capsule)
If both fail, client falls back to ACDS + WebRTC
This pragmatic approach provides direct connectivity for most home users while maintaining compatibility with stricter NATs via WebRTC fallback.
Definition in file upnp.c.
Function Documentation
nat_upnp_close()
void nat_upnp_close (nat_upnp_context_t ** ctx)
Definition at line 276 of file upnp.c.
{
  if (!ctx || !(*ctx)) {
    return;
  }
  if ((*ctx)->is_mapped) {
    // Note: In a real implementation, we'd remove the port mapping from the gateway.
    // For MVP, we just log and let the lease expire naturally (typically 1 hour).
    log_debug("NAT: Port mapping will expire in ~1 hour (cleanup handled by router)");
  }
  SAFE_FREE(*ctx);
  *ctx = NULL;
}
Referenced by acds_main().
nat_upnp_get_address()
asciichat_error_t nat_upnp_get_address (const nat_upnp_context_t * ctx, char * addr, size_t addr_len)
Definition at line 310 of file upnp.c.
{
  if (!ctx || !addr || addr_len < 22) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "NAT: Invalid arguments for get_address");
  }
  if (!ctx->is_mapped || ctx->external_ip[0] == '\0') {
    return SET_ERRNO(ERROR_NETWORK, "NAT: No active mapping to advertise");
  }
  // Format as "IP:port" (e.g., "203.0.113.42:27224")
  int written = safe_snprintf(addr, addr_len, "%s:%u", ctx->external_ip, ctx->mapped_port);
  if (written < 0 || (size_t)written >= addr_len) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "NAT: Address buffer too small");
  }
  return ASCIICHAT_OK;
}
References safe_snprintf().
Referenced by acds_main(), nat_detect_quality(), and server_main().
nat_upnp_is_active()
bool nat_upnp_is_active (const nat_upnp_context_t * ctx)
Definition at line 291 of file upnp.c.
{
  if (!ctx) {
    return false;
  }
  return ctx->is_mapped && ctx->external_ip[0] != '\0';
}
Referenced by nat_detect_quality().
nat_upnp_open()
asciichat_error_t nat_upnp_open (uint16_t internal_port, const char * description, nat_upnp_context_t ** ctx)
Definition at line 236 of file upnp.c.
{
  if (!ctx || !description) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "nat_upnp_open: Invalid arguments");
  }
  // Allocate context
  *ctx = SAFE_MALLOC(sizeof(nat_upnp_context_t), nat_upnp_context_t *);
  if (!(*ctx)) {
    return ERROR_MEMORY;
  }
  memset(*ctx, 0, sizeof(nat_upnp_context_t));
  // Try UPnP first (works on ~90% of home routers)
  log_info("NAT: Attempting UPnP port mapping for port %u...", internal_port);
  asciichat_error_t result = upnp_try_map_port(internal_port, description, *ctx);
  if (result == ASCIICHAT_OK) {
    log_info("NAT: ✓ UPnP port mapping successful!");
    return ASCIICHAT_OK;
  }
  log_info("NAT: UPnP failed, trying NAT-PMP fallback...");
  result = natpmp_try_map_port(internal_port, *ctx);
  if (result == ASCIICHAT_OK) {
    log_info("NAT: ✓ NAT-PMP port mapping successful!");
    return ASCIICHAT_OK;
  }
  // Both UPnP and NAT-PMP failed - this is OK, not fatal
  log_warn("NAT: Both UPnP and NAT-PMP failed. Direct TCP won't work, will use ACDS + WebRTC.");
  log_warn("NAT: This is normal for strict NATs. No action required.");
  SAFE_FREE(*ctx);
  *ctx = NULL;
  return SET_ERRNO(ERROR_NETWORK, "NAT: No automatic port mapping available (will use WebRTC)");
}
Referenced by acds_main(), nat_detect_quality(), and server_main().
nat_upnp_refresh()
asciichat_error_t nat_upnp_refresh (nat_upnp_context_t * ctx)
Definition at line 298 of file upnp.c.
{
  if (!ctx || !ctx->is_mapped) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "NAT: Cannot refresh - no active mapping");
  }
  log_debug("NAT: Refreshing port mapping (would extend lease in full implementation)");
  // In a real implementation, we'd re-register the port mapping to extend the lease.
  // For now, we just return success since the lease is 1 hour anyway.
  return ASCIICHAT_OK;
}