ascii-chat: time.c File Reference
time.c File Reference
⏱️ High-precision timing utilities implementation
Macros
#define SOKOL_TIME_IMPL
Functions
uint64_t time_get_ns (void)
uint64_t time_get_realtime_ns (void)
void time_sleep_ns (uint64_t ns)
uint64_t time_elapsed_ns (uint64_t start_ns, uint64_t end_ns)
uint64_t time_timespec_to_ns (const struct timespec *ts)
void time_ns_to_timespec (uint64_t ns, struct timespec *ts)
bool timer_system_init (void)
void timer_system_destroy (void)
bool timer_start (const char *name)
double timer_stop (const char *name)
bool timer_is_initialized (void)
int format_uptime_hms (int hours, int minutes, int seconds, char *buffer, size_t buffer_size)
int time_pretty (uint64_t nanoseconds, int decimals, char *buffer, size_t buffer_size)
int time_pretty_now (int decimals, char *buffer, size_t buffer_size)
int time_human_readable_unsigned (uint64_t nanoseconds, char *buffer, size_t buffer_size)
int time_human_readable (int64_t nanoseconds, char *buffer, size_t buffer_size)
int time_human_readable_now (char *buffer, size_t buffer_size)
void adaptive_sleep_init (adaptive_sleep_state_t *state, const adaptive_sleep_config_t *config)
uint64_t adaptive_sleep_calculate (adaptive_sleep_state_t *state, size_t queue_depth, size_t target_depth)
void adaptive_sleep_do (adaptive_sleep_state_t *state, size_t queue_depth, size_t target_depth)
bool time_format_is_valid_strftime (const char *format_str)
int time_format_now (const char *format_str, char *buf, size_t buf_size)
asciichat_error_t time_format_safe (const char *format_str, char *buf, size_t buf_size)
Detailed Description
⏱️ High-precision timing utilities implementation
Definition in file util/time.c.
Macro Definition Documentation
SOKOL_TIME_IMPL
#define SOKOL_TIME_IMPL
Definition at line 11 of file util/time.c.
Function Documentation
adaptive_sleep_calculate()
uint64_t adaptive_sleep_calculate (adaptive_sleep_state_t * state, size_t queue_depth, size_t target_depth)
Definition at line 622 of file util/time.c.
{
  if (!state) {
    return 0;
  }
  const adaptive_sleep_config_t *cfg = &state->config;
  // Determine if we need to speed up or slow down
  double desired_multiplier;
  if (queue_depth > target_depth) {
    // Queue is building up - speed up processing
    // The more items in queue, the faster we should process
    size_t backlog = queue_depth - target_depth;
    // Calculate desired speed based on backlog
    // Each item above target increases speed proportionally
    // This ensures we drain the queue faster the more backed up we are
    double backlog_factor = 1.0 + ((double)backlog / (double)(target_depth + 1));
    desired_multiplier = cfg->min_speed_multiplier * backlog_factor;
    // Clamp to max speed
    if (desired_multiplier > cfg->max_speed_multiplier) {
      desired_multiplier = cfg->max_speed_multiplier;
    }
    // Ramp up gradually based on speedup_rate
    double delta = desired_multiplier - state->current_speed_multiplier;
    state->current_speed_multiplier += delta * cfg->speedup_rate;
  } else {
    // Queue is at or below target - slow down to baseline
    desired_multiplier = cfg->min_speed_multiplier;
    // Ramp down gradually based on slowdown_rate
    double delta = desired_multiplier - state->current_speed_multiplier;
    state->current_speed_multiplier += delta * cfg->slowdown_rate;
  }
  // Ensure we stay within configured bounds
  if (state->current_speed_multiplier < cfg->min_speed_multiplier) {
    state->current_speed_multiplier = cfg->min_speed_multiplier;
  }
  if (state->current_speed_multiplier > cfg->max_speed_multiplier) {
    state->current_speed_multiplier = cfg->max_speed_multiplier;
  }
  // Calculate actual sleep time: baseline / speed_multiplier
  // Higher multiplier = shorter sleep = faster processing
  uint64_t sleep_ns = (uint64_t)(cfg->baseline_sleep_ns / state->current_speed_multiplier);
  // Store for debugging
  state->last_sleep_ns = sleep_ns;
  return sleep_ns;
}
Referenced by adaptive_sleep_do().
adaptive_sleep_do()
void adaptive_sleep_do (adaptive_sleep_state_t * state, size_t queue_depth, size_t target_depth)
Definition at line 679 of file util/time.c.
{
  uint64_t sleep_ns = adaptive_sleep_calculate(state, queue_depth, target_depth);
  if (sleep_ns > 0) {
    platform_sleep_ns(sleep_ns);
  }
}
References adaptive_sleep_calculate().
Referenced by client_audio_render_thread(), client_video_render_thread(), and session_capture_sleep_for_fps().
adaptive_sleep_init()
void adaptive_sleep_init (adaptive_sleep_state_t * state, const adaptive_sleep_config_t * config)
Definition at line 607 of file util/time.c.
{
  if (!state || !config) {
    return;
  }
  // Copy configuration
  state->config = *config;
  // Start at baseline speed (no speedup initially)
  state->current_speed_multiplier = config->min_speed_multiplier;
  // Initial sleep is the baseline
  state->last_sleep_ns = config->baseline_sleep_ns;
}
Referenced by client_audio_render_thread(), client_video_render_thread(), session_capture_create(), and session_network_capture_create().
format_uptime_hms()
int format_uptime_hms (int hours, int minutes, int seconds, char * buffer, size_t buffer_size)
Definition at line 348 of file util/time.c.
{
  if (!buffer || buffer_size == 0) {
    return -1;
  }
  // Validate components
  if (hours < 0 || minutes < 0 || minutes >= 60 || seconds < 0 || seconds >= 60) {
    return -1;
  }
  // Format as HH:MM:SS with zero-padding
  int written = safe_snprintf(buffer, buffer_size, "%02d:%02d:%02d", hours, minutes, seconds);
  if (written < 0 || (size_t)written >= buffer_size) {
    return -1;
  }
  return written;
}
References buffer_size, and safe_snprintf().
time_elapsed_ns()
uint64_t time_elapsed_ns (uint64_t start_ns, uint64_t end_ns)
Definition at line 150 of file util/time.c.
{
  // Handle wraparound (defensive - uint64_t won't wrap in practice at nanosecond resolution)
  // but this is safe and handles any theoretical edge cases
  if (end_ns >= start_ns) {
    return end_ns - start_ns;
  }
  // Wraparound case (extremely unlikely)
  return (UINT64_MAX - start_ns) + end_ns + 1;
}
Referenced by ascii_convert_with_capabilities(), asciichat_instr_log_line(), audio_analysis_print_report(), broadcast_server_state_to_all_clients(), client_send_thread_func(), fps_frame_ns(), media_source_read_video(), media_source_seek(), mixer_process_excluding_source(), session_capture_get_current_fps(), session_capture_read_frame(), and session_client_like_run().
time_format_is_valid_strftime()
bool time_format_is_valid_strftime (const char * format_str)
Definition at line 697 of file util/time.c.
{
  if (!format_str) {
    return false;
  }
  for (const char *p = format_str; *p; p++) {
    if (*p == '%') {
      p++;
      if (!*p) {
        /* Unterminated % at end of string */
        log_error("Invalid time format: unterminated %% at end");
        return false;
      }
      if (*p == '%') {
        /* Escaped %% - this is valid, just skip it */
        continue;
      }
      /* Optional: flag characters (-, 0, +, space) */
      if (*p == '-' || *p == '0' || *p == '+' || *p == ' ') {
        p++;
        if (!*p) {
          log_error("Invalid time format: flag character without specifier");
          return false;
        }
      }
      /* Optional: width specifier (digits or *) */
      if (*p == '*' || isdigit((unsigned char)*p)) {
        while (*p && (isdigit((unsigned char)*p) || *p == '*')) {
          p++;
        }
        if (!*p) {
          log_error("Invalid time format: width specifier without specifier character");
          return false;
        }
      }
      /* Optional: precision specifier (.digits or .*) */
      if (*p == '.') {
        p++;
        if (!*p) {
          log_error("Invalid time format: precision specifier incomplete");
          return false;
        }
        while (*p && (isdigit((unsigned char)*p) || *p == '*')) {
          p++;
        }
        if (!*p) {
          log_error("Invalid time format: precision specifier without specifier character");
          return false;
        }
      }
      /* Optional: modifier characters (E for %Ex, O for %Ox) */
      if (*p == 'E' || *p == 'O') {
        p++;
        if (!*p) {
          log_error("Invalid time format: modifier character without specifier");
          return false;
        }
      }
      /* Validate that the final character is a supported specifier */
      if (!strchr(SUPPORTED_SPECIFIERS, *p)) {
        log_error("Invalid time format: unsupported specifier %%%c (at position %ld)", *p, (p - format_str));
        return false;
      }
    }
  }
  return true;
}
Referenced by time_format_safe().
time_format_now()
int time_format_now (const char * format_str, char * buf, size_t buf_size)
Definition at line 772 of file util/time.c.
{
  if (!format_str || !buf || buf_size < 2) {
    SET_ERRNO(ERROR_INVALID_PARAM, "time_format_now: invalid arguments - format_str=%p, buf=%p, buf_size=%zu",
              format_str, buf, buf_size);
    return 0;
  }
  /* Get current wall-clock time in nanoseconds */
  uint64_t ts_ns = time_get_realtime_ns();
  /* Extract seconds and nanoseconds */
  time_t seconds = (time_t)(ts_ns / NS_PER_SEC_INT);
  /* Convert seconds to struct tm */
  struct tm tm_info;
  platform_localtime(&seconds, &tm_info);
  /* Format using strftime */
  size_t len = strftime(buf, buf_size, format_str, &tm_info);
  /* Check for strftime errors or buffer overflow */
  if (len == 0) {
    /* strftime returned 0 - either error or exact buffer fill */
    log_debug("strftime returned 0 for format: %s", format_str);
    return 0;
  }
  if (len >= buf_size - 1) {
    /* Buffer would overflow - strftime filled entire buffer or hit exact size */
    log_error("time_format_now: buffer too small (need %zu, have %zu)", len + 1, buf_size);
    return 0;
  }
  return (int)len;
}
References platform_localtime(), and time_get_realtime_ns().
Referenced by log_template_apply(), and time_format_safe().
time_format_safe()
asciichat_error_t time_format_safe (const char * format_str, char * buf, size_t buf_size)
Definition at line 808 of file util/time.c.
{
  /* Check NULL pointers */
  if (!format_str) {
    return SET_ERRNO(ERROR_INVALID_STATE, "time_format_safe: format_str is NULL");
  }
  if (!buf) {
    return SET_ERRNO(ERROR_INVALID_STATE, "time_format_safe: buf is NULL");
  }
  /* Check minimum buffer size */
  if (buf_size < 64) {
    return SET_ERRNO(ERROR_INVALID_STATE, "time_format_safe: buffer too small (minimum 64 bytes, got %zu)", buf_size);
  }
  /* Validate format string */
  if (!time_format_is_valid_strftime(format_str)) {
    return SET_ERRNO(ERROR_INVALID_STATE, "time_format_safe: invalid time format: %s", format_str);
  }
  /* Format the time */
  int result = time_format_now(format_str, buf, buf_size);
  if (result <= 0) {
    return SET_ERRNO(ERROR_INVALID_STATE, "time_format_safe: strftime formatting failed");
  }
  return ASCIICHAT_OK;
}
References time_format_is_valid_strftime(), and time_format_now().
time_get_ns()
uint64_t time_get_ns (void)
Definition at line 108 of file util/time.c.
{
  // sokol_time provides monotonic clock that never goes backwards
  // stm_ns() converts ticks to nanoseconds
  // Ensure sokol_time is initialized before use (defensive programming)
  if (!g_sokol_time_initialized) {
    stm_setup();
    g_sokol_time_initialized = true;
  }
  return (uint64_t)stm_ns(stm_now());
}
Referenced by acip_server_receive_and_dispatch(), ascii_convert_with_capabilities(), asciichat_instr_log_line(), atomic_on_cas(), atomic_on_fetch(), atomic_on_load(), atomic_on_store(), atomic_ptr_on_cas(), atomic_ptr_on_exchange(), atomic_ptr_on_load(), atomic_ptr_on_store(), audio_analysis_init(), audio_analysis_print_report(), audio_analysis_track_received_packet(), audio_analysis_track_sent_packet(), broadcast_server_state_to_all_clients(), buffer_pool_free(), buffer_pool_shrink(), client_audio_render_thread(), client_dispatch_thread(), client_send_thread_func(), client_video_render_thread(), cond_format_state(), cond_on_broadcast(), cond_on_signal(), cond_on_wait(), consensus_coordinator_create(), consensus_coordinator_on_collection_start(), consensus_coordinator_process(), consensus_coordinator_time_until_next_round(), create_mixed_ascii_frame_for_client(), debug_atomic_format_timing(), debug_atomic_ptr_format_timing(), discovery_mdns_query(), fps_counter_tick(), get_utf8_palette_cache(), media_source_read_video(), media_source_seek(), mixer_process_excluding_source(), mutex_format_state(), mutex_on_lock(), mutex_on_trylock(), mutex_on_unlock(), mutex_stack_mark_locked(), mutex_stack_push_pending(), nat_measure_bandwidth(), rwlock_format_state(), rwlock_on_rdlock(), rwlock_on_unlock(), rwlock_on_wrlock(), session_capture_create(), session_capture_get_current_fps(), session_capture_read_frame(), session_client_like_run(), session_display_convert_to_ascii(), session_display_create(), session_display_write_ascii(), session_network_capture_create(), session_pipeline_run_main(), session_render_loop(), simple_frame_swap_update(), splash_intro_done(), splash_intro_start(), time_human_readable_now(), time_pretty_now(), and websocket_server_run().
time_get_realtime_ns()
uint64_t time_get_realtime_ns (void)
Definition at line 119 of file util/time.c.
{
#ifdef _WIN32
  // Windows: Use GetSystemTimePreciseAsFileTime (Win8+) for high-precision wall clock
  // FILETIME is 100-nanosecond intervals since January 1, 1601
  FILETIME ft;
  GetSystemTimePreciseAsFileTime(&ft);
  // Convert FILETIME to nanoseconds
  uint64_t filetime = ((uint64_t)ft.dwHighDateTime << 32) | ft.dwLowDateTime;
  // Convert 100-nanosecond intervals to nanoseconds
  return filetime * 100;
#else
  // Get wall-clock (real-time) timestamp
  struct timespec ts;
  if (clock_gettime(CLOCK_REALTIME, &ts) != 0) {
    // Fallback on error (unlikely)
    return 0;
  }
  return time_timespec_to_ns(&ts);
#endif
}
References time_timespec_to_ns().
Referenced by acds_validate_timestamp(), asciichat_error_stats_record(), asciichat_instr_log_line(), asciichat_set_errno(), connection_attempt_tcp(), connection_attempt_websocket(), connection_check_timeout(), connection_context_init(), consensus_metrics_measure(), consensus_state_compute_election(), database_session_is_migration_ready(), database_session_start_migration(), get_current_time_formatted(), handle_image_frame_h265_packet(), log_json_async_safe(), log_msg(), log_plain_msg(), log_terminal_msg(), and time_format_now().
time_human_readable()
int time_human_readable (int64_t nanoseconds, char * buffer, size_t buffer_size)
Definition at line 570 of file util/time.c.
{
  if (!buffer || buffer_size == 0) {
    return -1;
  }
  // Determine direction (past vs future)
  bool is_future = nanoseconds < 0;
  uint64_t abs_ns = is_future ? (uint64_t)(-nanoseconds) : (uint64_t)nanoseconds;
  // Convert nanoseconds to seconds for threshold checking
  double total_seconds = (double)abs_ns / NS_PER_SEC;
  int minutes = (int)(total_seconds / 60);
  int hours = minutes / 60;
  int days = hours / 24;
  int months = days / 30; // Approximate
  int years = months / 12;
  const char *suffix = is_future ? "from now" : "ago";
  int written =
      format_human_readable_time_ago(total_seconds, minutes, hours, days, months, years, suffix, buffer, buffer_size);
  if (written < 0 || (size_t)written >= buffer_size) {
    return -1;
  }
  return written;
}
References buffer_size.
Referenced by time_human_readable_now().
time_human_readable_now()
int time_human_readable_now (char * buffer, size_t buffer_size)
Definition at line 598 of file util/time.c.
{
  int64_t ns = (int64_t)time_get_ns();
  return time_human_readable(ns, buffer, buffer_size);
}
References buffer_size, time_get_ns(), and time_human_readable().
time_human_readable_unsigned()
int time_human_readable_unsigned (uint64_t nanoseconds, char * buffer, size_t buffer_size)
Definition at line 547 of file util/time.c.
{
  if (!buffer || buffer_size == 0) {
    return -1;
  }
  // Convert nanoseconds to seconds for threshold checking
  double total_seconds = (double)nanoseconds / NS_PER_SEC;
  int minutes = (int)(total_seconds / 60);
  int hours = minutes / 60;
  int days = hours / 24;
  int months = days / 30; // Approximate
  int years = months / 12;
  int written =
      format_human_readable_time_ago(total_seconds, minutes, hours, days, months, years, "ago", buffer, buffer_size);
  if (written < 0 || (size_t)written >= buffer_size) {
    return -1;
  }
  return written;
}
References buffer_size.
time_ns_to_timespec()
void time_ns_to_timespec (uint64_t ns, struct timespec * ts)
Definition at line 172 of file util/time.c.
{
  if (!ts) {
    SET_ERRNO(ERROR_INVALID_PARAM, "null ts");
    return;
  }
  ts->tv_sec = (time_t)(ns / NS_PER_SEC_INT);
  ts->tv_nsec = (long)(ns % NS_PER_SEC_INT);
}
time_pretty()
int time_pretty (uint64_t nanoseconds, int decimals, char * buffer, size_t buffer_size)
Definition at line 418 of file util/time.c.
{
  if (!buffer || buffer_size == 0) {
    return -1;
  }
  // Handle zero
  if (nanoseconds == 0) {
    int written = safe_snprintf(buffer, buffer_size, "0 ns");
    return (written < 0 || (size_t)written >= buffer_size) ? -1 : written;
  }
  // Determine decimals for this range if not explicitly set
  int actual_decimals = decimals;
  if (decimals == -1) {
    if (nanoseconds < NS_PER_MS_INT) {
      actual_decimals = 3; // ns/µs
    } else if (nanoseconds < NS_PER_SEC_INT) {
      actual_decimals = 3; // ms
    } else if (nanoseconds < NS_PER_MIN_INT) {
      actual_decimals = 2; // seconds
    } else {
      actual_decimals = 3; // colon notation
    }
  }
  // Clamp decimals to valid range
  if (actual_decimals < 0)
    actual_decimals = 0;
  if (actual_decimals > 9)
    actual_decimals = 9;
  int written = 0;
  // Nanoseconds (< 1µs)
  if (nanoseconds < NS_PER_US_INT) {
    written = safe_snprintf(buffer, buffer_size, "%llu ns", (unsigned long long)nanoseconds);
  }
  // Microseconds (< 1ms)
  else if (nanoseconds < NS_PER_MS_INT) {
    double us = (double)nanoseconds / NS_PER_US;
    char temp_buf[64];
    // Use a direct snprintf with large enough buffer first
    snprintf(temp_buf, sizeof(temp_buf), "%.*f µs", actual_decimals, us);
    strip_trailing_zeros(temp_buf);
    written = (int)strlen(temp_buf);
    if (written > 0 && written < (int)buffer_size) {
      SAFE_STRNCPY(buffer, temp_buf, buffer_size);
    } else {
      written = -1;
    }
  }
  // Milliseconds (< 1s)
  else if (nanoseconds < NS_PER_SEC_INT) {
    double ms = (double)nanoseconds / NS_PER_MS;
    char temp_buf[64];
    snprintf(temp_buf, sizeof(temp_buf), "%.*f ms", actual_decimals, ms);
    strip_trailing_zeros(temp_buf);
    written = (int)strlen(temp_buf);
    if (written > 0 && written < (int)buffer_size) {
      SAFE_STRNCPY(buffer, temp_buf, buffer_size);
    } else {
      written = -1;
    }
  }
  // Seconds (< 1 minute)
  else if (nanoseconds < NS_PER_MIN_INT) {
    double s = (double)nanoseconds / NS_PER_SEC;
    char temp_buf[64];
    snprintf(temp_buf, sizeof(temp_buf), "%.*f s", actual_decimals, s);
    strip_trailing_zeros(temp_buf);
    written = (int)strlen(temp_buf);
    if (written > 0 && written < (int)buffer_size) {
      SAFE_STRNCPY(buffer, temp_buf, buffer_size);
    } else {
      written = -1;
    }
  }
  // Minutes (< 1 hour) - use colon notation: M:SS.frac
  else if (nanoseconds < NS_PER_HOUR_INT) {
    uint64_t total_seconds = nanoseconds / NS_PER_SEC_INT;
    uint64_t minutes = total_seconds / 60;
    uint64_t seconds = total_seconds % 60;
    uint64_t remainder_ns = nanoseconds % NS_PER_SEC_INT;
    double fraction = (double)remainder_ns / NS_PER_SEC;
    char temp_buf[64];
    if (actual_decimals == 0) {
      snprintf(temp_buf, sizeof(temp_buf), "%llu:%02llu", (unsigned long long)minutes, (unsigned long long)seconds);
    } else {
      snprintf(temp_buf, sizeof(temp_buf), "%llu:%02llu.%.*f", (unsigned long long)minutes, (unsigned long long)seconds,
               actual_decimals, fraction);
      strip_trailing_zeros(temp_buf);
    }
    written = (int)strlen(temp_buf);
    if (written > 0 && written < (int)buffer_size) {
      SAFE_STRNCPY(buffer, temp_buf, buffer_size);
    } else {
      written = -1;
    }
  }
  // Hours+ - use colon notation: H:MM:SS or HH:MM:SS
  else {
    uint64_t total_seconds = nanoseconds / NS_PER_SEC_INT;
    uint64_t hours = total_seconds / 3600;
    uint64_t remaining = total_seconds % 3600;
    uint64_t minutes = remaining / 60;
    uint64_t seconds = remaining % 60;
    written = safe_snprintf(buffer, buffer_size, "%llu:%02llu:%02llu", (unsigned long long)hours,
                            (unsigned long long)minutes, (unsigned long long)seconds);
  }
  if (written < 0 || (size_t)written >= buffer_size) {
    return -1;
  }
  return written;
}
References buffer_size, and safe_snprintf().
Referenced by acip_server_receive_and_dispatch(), ascii_convert_with_capabilities(), asciichat_instr_log_line(), broadcast_server_state_to_all_clients(), client_dispatch_thread(), client_send_thread_func(), client_video_render_thread(), cond_format_state(), connection_check_timeout(), create_mixed_ascii_frame_for_client(), crypto_init(), crypto_rekey_init(), debug_atomic_format_timing(), debug_atomic_ptr_format_timing(), media_source_seek(), mixer_process_excluding_source(), mutex_format_state(), rwlock_format_state(), session_display_convert_to_ascii(), session_display_write_ascii(), session_render_loop(), time_pretty_now(), and timer_stop().
time_pretty_now()
int time_pretty_now (int decimals, char * buffer, size_t buffer_size)
Definition at line 538 of file util/time.c.
{
  uint64_t ns = time_get_ns();
  return time_pretty(ns, decimals, buffer, buffer_size);
}
References buffer_size, time_get_ns(), and time_pretty().
time_sleep_ns()
void time_sleep_ns (uint64_t ns)
Definition at line 140 of file util/time.c.
{
  // Use platform abstraction for cross-platform sleep
  // Convert nanoseconds to microseconds (1 us = 1000 ns)
  unsigned int usec = (unsigned int)(ns / 1000);
  if (usec == 0 && ns > 0) {
    usec = 1; // Minimum 1 microsecond
  }
  platform_sleep_us(usec);
}
References platform_sleep_us().
time_timespec_to_ns()
uint64_t time_timespec_to_ns (const struct timespec * ts)
Definition at line 164 of file util/time.c.
{
  if (!ts) {
    SET_ERRNO(ERROR_INVALID_PARAM, "null ts");
    return 0;
  }
  return (uint64_t)ts->tv_sec * NS_PER_SEC_INT + (uint64_t)ts->tv_nsec;
}
Referenced by time_get_realtime_ns().
timer_is_initialized()
bool timer_is_initialized (void)
Definition at line 340 of file util/time.c.
{
  return lifecycle_is_initialized(&g_timer_manager.lifecycle);
}
References lifecycle_is_initialized().
timer_start()
bool timer_start (const char * name)
Definition at line 234 of file util/time.c.
{
  if (!lifecycle_is_initialized(&g_timer_manager.lifecycle)) {
    SET_ERRNO(ERROR_INVALID_STATE, "Timer system not initialized");
    return false;
  }
  if (!name) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Timer name is NULL");
    return false;
  }
  rwlock_wrlock(&g_timer_manager.rwlock);
  // Check if timer already exists - this is an error, timers must be unique
  timer_record_t *existing = NULL;
  HASH_FIND_STR(g_timer_manager.timers, name, existing);
  if (existing) {
    rwlock_wrunlock(&g_timer_manager.rwlock);
    SET_ERRNO(ERROR_INVALID_STATE, "Timer '%s' already exists - timers must have unique names", name);
    return false;
  }
  // Create new timer record
  timer_record_t *timer = SAFE_MALLOC(sizeof(timer_record_t), timer_record_t *);
  if (!timer) {
    rwlock_wrunlock(&g_timer_manager.rwlock);
    SET_ERRNO(ERROR_MEMORY, "Failed to allocate timer record");
    return false;
  }
  // Use platform-safe string duplication
  size_t name_len = strlen(name) + 1;
  timer->name = SAFE_MALLOC(name_len, char *);
  if (!timer->name) {
    SAFE_FREE(timer);
    rwlock_wrunlock(&g_timer_manager.rwlock);
    SET_ERRNO(ERROR_MEMORY, "Failed to allocate timer name");
    return false;
  }
  SAFE_STRNCPY(timer->name, name, name_len);
  timer->start_ticks = stm_now();
  // Add to hashtable
  HASH_ADD_KEYPTR(hh, g_timer_manager.timers, timer->name, strlen(timer->name), timer);
  rwlock_wrunlock(&g_timer_manager.rwlock);
  return true;
}
References lifecycle_is_initialized().
timer_stop()
double timer_stop (const char * name)
Definition at line 285 of file util/time.c.
{
  if (!lifecycle_is_initialized(&g_timer_manager.lifecycle)) {
    SET_ERRNO(ERROR_INVALID_STATE, "Timer system not initialized");
    return -1.0;
  }
  if (!name) {
    SET_ERRNO(ERROR_INVALID_PARAM, "Timer name is NULL");
    return -1.0;
  }
  rwlock_wrlock(&g_timer_manager.rwlock);
  // Find timer
  timer_record_t *timer = NULL;
  HASH_FIND_STR(g_timer_manager.timers, name, timer);
  if (!timer) {
    rwlock_wrunlock(&g_timer_manager.rwlock);
    log_dev("Timer '%s' not found (may have already been stopped)", name);
    return -1.0;
  }
  // Calculate elapsed time in nanoseconds for maximum precision
  uint64_t end_ticks = stm_now();
  uint64_t elapsed_ticks = stm_diff(end_ticks, timer->start_ticks);
  double elapsed_ns = stm_ns(elapsed_ticks);
  // Format duration for human-readable logging
  char duration_str[32];
  time_pretty((uint64_t)elapsed_ns, -1, duration_str, sizeof(duration_str));
  // Log the result (dev level - only shown with --verbose)
  log_dev("Timer '%s': %s", name, duration_str);
  // Save pointers to free BEFORE removing from hashtable
  char *timer_name = timer->name;
  // Remove from hashtable (HASH_DEL only removes from hash, doesn't free memory)
  HASH_DEL(g_timer_manager.timers, timer);
  // Free timer->name first (this was allocated separately)
  SAFE_FREE(timer_name);
  // Nullify the timer->name field so debug_free doesn't try to access it
  // when freeing the timer structure itself
  timer->name = NULL;
  // Free the timer record itself
  SAFE_FREE(timer);
  rwlock_wrunlock(&g_timer_manager.rwlock);
  return elapsed_ns; // Return nanoseconds
}
References lifecycle_is_initialized(), and time_pretty().
timer_system_destroy()
void timer_system_destroy (void)
Definition at line 207 of file util/time.c.
{
  if (!lifecycle_is_initialized(&g_timer_manager.lifecycle)) {
    return;
  }
  rwlock_wrlock(&g_timer_manager.rwlock);
  // Free all timer records
  int timer_count = 0;
  timer_record_t *current, *tmp;
  HASH_ITER(hh, g_timer_manager.timers, current, tmp) {
    HASH_DEL(g_timer_manager.timers, current);
    SAFE_FREE(current->name);
    SAFE_FREE(current);
    timer_count++;
  }
  g_timer_manager.timers = NULL;
  rwlock_wrunlock(&g_timer_manager.rwlock);
  /* Shutdown lifecycle and destroy rwlock together */
  lifecycle_shutdown(&g_timer_manager.lifecycle);
  log_debug("Timer system cleaned up (freed %d timers)", timer_count);
}
References lifecycle_is_initialized(), and lifecycle_shutdown().
Referenced by asciichat_shared_destroy().
timer_system_init()
bool timer_system_init (void)
Definition at line 185 of file util/time.c.
{
  if (lifecycle_is_initialized(&g_timer_manager.lifecycle)) {
    return true;
  }
  // Initialize sokol_time
  stm_setup();
  // Initialize rwlock and lifecycle together
  g_timer_manager.lifecycle.sync_type = LIFECYCLE_SYNC_RWLOCK;
  g_timer_manager.lifecycle.sync.rwlock = &g_timer_manager.rwlock;
  if (!lifecycle_init(&g_timer_manager.lifecycle, "timer_manager")) {
    SET_ERRNO(ERROR_PLATFORM_INIT, "Failed to initialize timer system (already initialized by another thread)");
    return true; // Another thread already initialized it
  }
  g_timer_manager.timers = NULL;
  log_dev("Timer system initialized");
  return true;
}
References lifecycle_init(), and lifecycle_is_initialized().
Referenced by asciichat_shared_init().
Variable Documentation
lifecycle
lifecycle_t lifecycle
Lifecycle state machine for init/shutdown synchronization.
Definition at line 35 of file util/time.c.
rwlock
rwlock_t rwlock
Read-write lock for thread-safe access (uthash requires external locking).
Definition at line 34 of file util/time.c.
Referenced by rwlock_format_state(), rwlock_init(), rwlock_log_state(), rwlock_on_rdlock(), rwlock_on_unlock(), rwlock_on_wrlock(), rwlock_rdlock_impl(), rwlock_rdunlock_impl(), rwlock_wrlock_impl(), and rwlock_wrunlock_impl().
timers
timer_record_t* timers
Hash table of active timers (uthash head pointer).
Definition at line 33 of file util/time.c.