ascii-chat: util.c File Reference
util.c File Reference
Utility stubs for WASM/Emscripten (backtrace, localtime).
Functions
int platform_backtrace (void **buffer, int size)
char ** platform_backtrace_symbols (void *const *buffer, int size)
void platform_backtrace_symbols_destroy (char **symbols)
void platform_print_backtrace_symbols (const char *label, char **symbols, int count, int skip_frames, int max_frames, backtrace_frame_filter_t filter)
void platform_print_backtrace (int skip_frames)
asciichat_error_t platform_localtime (const time_t *timer, struct tm *result)
int platform_isatty (int fd)
void platform_clear_error_state (void)
bool platform_get_temp_dir (char *temp_dir, size_t path_size)
bool platform_prompt_yes_no (const char *question, bool default_yes)
int platform_get_last_error (void)
const char * platform_get_home_dir (void)
void platform_normalize_path_separators (char *path)
char * platform_get_config_dir (void)
bool platform_get_cwd (char *cwd, size_t path_size)
int platform_path_strcasecmp (const char *a, const char *b, size_t n)
int platform_is_regular_file (const char *path)
Detailed Description
Utility stubs for WASM/Emscripten (backtrace, localtime).
Definition in file util.c.
Function Documentation
platform_backtrace()
int platform_backtrace (void ** buffer, int size)
Definition at line 15 of file util.c.
{
  (void)buffer;
  (void)size;
  return 0; // No backtrace support in WASM
}
Referenced by backtrace_capture(), and backtrace_print_simple().
platform_backtrace_symbols()
char ** platform_backtrace_symbols (void *const * buffer, int size)
Definition at line 21 of file util.c.
{
  (void)buffer;
  (void)size;
  return NULL; // No backtrace symbols in WASM
}
Referenced by backtrace_print_simple(), and backtrace_symbolize().
platform_backtrace_symbols_destroy()
void platform_backtrace_symbols_destroy (char ** symbols)
Definition at line 27 of file util.c.
{
  (void)symbols;
  // No-op
}
Referenced by backtrace_print_simple(), and backtrace_t_free().
platform_clear_error_state()
void platform_clear_error_state (void)
Definition at line 68 of file util.c.
{
  // No-op - error state is thread-local, nothing to clear in WASM
}
Referenced by asciichat_clear_errno().
platform_get_config_dir()
char * platform_get_config_dir (void)
Definition at line 103 of file util.c.
{
  static char config_dir[] = "/config";
  return config_dir; // WASM virtual filesystem config directory
}
Referenced by acds_identity_default_path(), and get_config_dir().
platform_get_cwd()
bool platform_get_cwd (char * cwd, size_t path_size)
Definition at line 109 of file util.c.
{
  if (!cwd || path_size == 0) {
    return false;
  }
  platform_strlcpy(cwd, "/", path_size);
  return true;
}
References platform_strlcpy().
Referenced by get_log_dir(), and path_validate_user_path().
platform_get_home_dir()
const char * platform_get_home_dir (void)
Definition at line 93 of file util.c.
{
  return "/home"; // WASM virtual filesystem home
}
Referenced by expand_path(), and path_validate_user_path().
platform_get_last_error()
int platform_get_last_error (void)
Definition at line 88 of file util.c.
{
  return 0; // No system error in WASM
}
platform_get_temp_dir()
bool platform_get_temp_dir (char * temp_dir, size_t path_size)
Definition at line 73 of file util.c.
{
  if (!temp_dir || path_size == 0) {
    return false;
  }
  platform_strlcpy(temp_dir, "/tmp", path_size);
  return true;
}
References platform_strlcpy().
Referenced by get_log_dir(), and path_validate_user_path().
platform_is_regular_file()
int platform_is_regular_file (const char * path)
Definition at line 123 of file util.c.
{
  (void)path;
  return 0; // No file system access in WASM mirror mode
}
Referenced by discovery_keys_clear_cache(), discovery_keys_load_cached(), and path_validate_user_path().
platform_isatty()
int platform_isatty (int fd)
Definition at line 62 of file util.c.
{
  (void)fd;
  return 1; // Always true for WASM terminal (xterm.js)
}
Referenced by session_display_create(), terminal_is_stderr_tty(), terminal_is_stdin_tty(), terminal_is_stdout_tty(), terminal_should_color_output(), and terminal_should_use_control_sequences().
platform_localtime()
asciichat_error_t platform_localtime (const time_t * timer, struct tm * result)
Definition at line 49 of file util.c.
{
  if (!timer || !result) {
    return ERROR_INVALID_PARAM;
  }
  // Use thread-safe localtime_r for both WASM and native builds
  // IMPORTANT: localtime() is NOT thread-safe and causes deadlocks in threaded WASM builds
  if (localtime_r(timer, result) != NULL) {
    return ASCIICHAT_OK;
  }
  return ERROR_PLATFORM_INIT;
}
Referenced by asciichat_error_stats_print(), asciichat_print_error_context(), get_current_time_formatted(), manpage_fmt_write_title(), and time_format_now().
platform_normalize_path_separators()
void platform_normalize_path_separators (char * path)
Definition at line 97 of file util.c.
{
  // No-op - WASM uses forward slashes (Unix-style)
  (void)path;
}
Referenced by expand_path().
platform_path_strcasecmp()
int platform_path_strcasecmp (const char * a, const char * b, size_t n)
Definition at line 118 of file util.c.
{
  return strncmp(a, b, n); // Case-sensitive on WASM
}
Referenced by path_is_within_base().
platform_print_backtrace()
void platform_print_backtrace (int skip_frames)
Definition at line 43 of file util.c.
{
  (void)skip_frames;
  // No-op - backtrace not supported in WASM
}
platform_print_backtrace_symbols()
void platform_print_backtrace_symbols (const char * label, char ** symbols, int count, int skip_frames, int max_frames, backtrace_frame_filter_t filter)
Definition at line 32 of file util.c.
{
  (void)label;
  (void)symbols;
  (void)count;
  (void)skip_frames;
  (void)max_frames;
  (void)filter;
  // No-op - backtrace not supported in WASM
}
platform_prompt_yes_no()
bool platform_prompt_yes_no (const char * question, bool default_yes)
Definition at line 82 of file util.c.
{
  (void)question;
  return default_yes; // Always return default in WASM
}
Referenced by action_completions(), client_crypto_handshake(), config_create_default(), discovery_keys_verify_change(), options_config_generate_manpage_merged(), prompt_unknown_host(), prompt_unknown_host_no_identity(), and server_main().