ascii-chat: version.c File Reference
version.c File Reference
🏷️ Binary-embedded version information in custom ELF/Mach-O sections for runtime inspection
Functions
semantic_version_t version_parse (const char *version_string)
int version_compare (semantic_version_t a, semantic_version_t b)
Detailed Description
🏷️ Binary-embedded version information in custom ELF/Mach-O sections for runtime inspection
Definition in file version.c.
Function Documentation
version_compare()
int version_compare (semantic_version_t a, semantic_version_t b)
Definition at line 112 of file version.c.
{
  // Compare major version
  if (a.major < b.major) {
    return -1;
  }
  if (a.major > b.major) {
    return 1;
  }
  // Major versions equal, compare minor
  if (a.minor < b.minor) {
    return -1;
  }
  if (a.minor > b.minor) {
    return 1;
  }
  // Minor versions equal, compare patch
  if (a.patch < b.patch) {
    return -1;
  }
  if (a.patch > b.patch) {
    return 1;
  }
  // All components equal
  return 0;
}
Referenced by update_check_load_cache(), and update_check_perform().
version_parse()
semantic_version_t version_parse (const char * version_string)
Definition at line 49 of file version.c.
{
  semantic_version_t result = {0, 0, 0, false};
  if (!version_string || version_string[0] == '\0') {
    return result;
  }
  const char *p = version_string;
  // Optionally skip 'v' prefix if present
  if (p[0] == 'v' || p[0] == 'V') {
    p++; // Skip 'v'
  }
  // Parse major version
  char *endptr = NULL;
  errno = 0; // Reset errno before strtol
  long major = strtol(p, &endptr, 10);
  if (errno == ERANGE || endptr == p || major < 0 || major > INT_MAX) {
    return result; // Invalid major version or overflow
  }
  result.major = (int)major;
  p = endptr;
  // Version must have all three components (major.minor.patch)
  if (*p != '.') {
    return result; // Invalid: missing minor version
  }
  p++; // Skip dot
  // Parse minor version
  errno = 0; // Reset errno before strtol
  long minor = strtol(p, &endptr, 10);
  if (errno == ERANGE || endptr == p || minor < 0 || minor > INT_MAX) {
    return result; // Invalid minor version or overflow
  }
  result.minor = (int)minor;
  p = endptr;
  // Version must have patch component
  if (*p != '.') {
    return result; // Invalid: missing patch version
  }
  p++; // Skip dot
  // Parse patch version
  errno = 0; // Reset errno before strtol
  long patch = strtol(p, &endptr, 10);
  if (errno == ERANGE || endptr == p || patch < 0 || patch > INT_MAX) {
    return result; // Invalid patch version or overflow
  }
  result.patch = (int)patch;
  p = endptr;
  // Reject prerelease tags (e.g., "v1.2.3-beta") - must end after patch number
  if (*p != '\0') {
    return result; // Invalid: has extra characters after version
  }
  result.valid = true;
  return result;
}
Referenced by update_check_load_cache(), and update_check_perform().