ascii-chat: filesystem.c File Reference
filesystem.c File Reference
File operation stubs for WASM.
Functions
FILE * platform_fopen (const char *name, const char *filename, const char *mode)
FILE * platform_tmpfile (void)
size_t platform_write_all (int fd, const void *buf, size_t count)
asciichat_error_t platform_mkdir_recursive (const char *path, int mode)
asciichat_error_t platform_find_config_file (const char *filename, config_file_list_t *list_out)
void config_file_list_destroy (config_file_list_t *list)
ssize_t platform_write (int fd, const void *buf, size_t count)
ssize_t platform_read (int fd, void *buf, size_t count)
int platform_open (const char *name, const char *pathname, int flags,...)
int platform_close (int fd)
int platform_access (const char *pathname, int mode)
char * platform_get_data_dir (void)
Detailed Description
File operation stubs for WASM.
Definition in file wasm/stubs/filesystem.c.
Function Documentation
config_file_list_destroy()
void config_file_list_destroy (config_file_list_t * list)
Definition at line 61 of file wasm/stubs/filesystem.c.
{
  (void)list;
  // No-op
}
Referenced by check_known_host(), and config_load_system_and_user().
platform_access()
int platform_access (const char * pathname, int mode)
Definition at line 112 of file wasm/stubs/filesystem.c.
{
  (void)pathname;
  (void)mode;
  return -1; // Not accessible in WASM
}
Referenced by get_discovery_database_dir(), get_log_dir(), and parse_mirror_media().
platform_close()
int platform_close (int fd)
Definition at line 108 of file wasm/stubs/filesystem.c.
{
  return close(fd);
}
Referenced by asciichat_instr_runtime_destroy(), check_known_host(), check_known_host_no_identity(), log_destroy(), log_disable_file_output(), log_init(), remove_known_host(), and session_display_destroy().
platform_find_config_file()
asciichat_error_t platform_find_config_file (const char * filename, config_file_list_t * list_out)
Definition at line 51 of file wasm/stubs/filesystem.c.
{
  (void)filename;
  if (list_out) {
    list_out->files = NULL;
    list_out->count = 0;
    list_out->capacity = 0;
  }
  return ASCIICHAT_OK; // No config files in WASM
}
Referenced by check_known_host(), and config_load_system_and_user().
platform_fopen()
FILE * platform_fopen (const char * name, const char * filename, const char * mode)
Definition at line 20 of file wasm/stubs/filesystem.c.
{
  if (!name) {
    return NULL;
  }
  FILE *stream = fopen(filename, mode); // Use standard fopen
  if (stream) {
    int fd = fileno(stream);
    if (fd >= 0) {
      NAMED_REGISTER_FD(fd, name);
    }
  }
  return stream;
}
Referenced by acds_identity_load(), action_completions(), add_known_host(), colorscheme_export_scheme(), config_create_default(), discovery_keys_save_cached(), get_manpage_template(), gpg_sign_with_key(), options_config_generate_manpage_merged(), options_config_generate_manpage_template(), parse_keys_from_file(), parse_manpage_sections(), parse_private_key(), parse_public_key(), parse_ssh_private_key(), update_check_load_cache(), update_check_save_cache(), validate_ssh_key_file(), and wav_writer_open().
platform_get_data_dir()
char * platform_get_data_dir (void)
Definition at line 118 of file wasm/stubs/filesystem.c.
{
  return NULL; // No data directory in WASM
}
Referenced by get_data_dir().
platform_mkdir_recursive()
asciichat_error_t platform_mkdir_recursive (const char * path, int mode)
Definition at line 45 of file wasm/stubs/filesystem.c.
{
  (void)path;
  (void)mode;
  return ERROR_PLATFORM_INIT; // Not implemented for WASM
}
Referenced by acds_identity_save(), config_create_default(), and get_discovery_database_dir().
platform_open()
int platform_open (const char * name, const char * pathname, int flags, ...)
Definition at line 82 of file wasm/stubs/filesystem.c.
{
  if (!name) {
    return -1;
  }
  // Handle optional mode parameter for O_CREAT
  int fd = -1;
  int mode = 0;
  if (flags & 0x0200) { // O_CREAT flag value
    va_list args;
    va_start(args, flags);
    mode = va_arg(args, int);
    va_end(args);
    fd = open(pathname, flags, mode);
  } else {
    fd = open(pathname, flags);
  }
  if (fd >= 0) {
    NAMED_REGISTER_FD(fd, name);
    log_dev("Opened file descriptor %d for %s at path %s", fd, name, pathname);
  }
  return fd;
}
References args.
Referenced by acds_identity_save(), check_known_host(), check_known_host_no_identity(), log_init(), main(), parse_gpg_keys_from_response(), remove_known_host(), and test_logging_disable().
platform_read()
ssize_t platform_read (int fd, void * buf, size_t count)
Definition at line 78 of file wasm/stubs/filesystem.c.
{
  return read(fd, buf, count);
}
platform_tmpfile()
FILE * platform_tmpfile (void)
Definition at line 34 of file wasm/stubs/filesystem.c.
{
  return tmpfile();
}
Referenced by manpage_parser_parse_memory().
platform_write()
ssize_t platform_write (int fd, const void * buf, size_t count)
Definition at line 67 of file wasm/stubs/filesystem.c.
{
  // For WASM, route stdout/stderr to browser console
  if ((fd == 1 || fd == 2) && buf && count > 0) {
    wasm_log_to_console(fd, (const uint8_t *)buf, count);
    return (ssize_t)count; // Report all bytes as written
  }
  // Fallback: use standard write for other fds
  return write(fd, buf, count);
}
References wasm_log_to_console().
Referenced by log_json_write(), and platform_write_all().
platform_write_all()
size_t platform_write_all (int fd, const void * buf, size_t count)
Definition at line 38 of file wasm/stubs/filesystem.c.
{
  (void)fd;
  (void)buf;
  (void)count;
  return 0; // Not implemented for WASM
}