ascii-chat: system.c File Reference
system.c File Reference
System utilities for WASM/Emscripten - includes generic implementations.
Functions
const char * platform_getenv (const char *name)
const char * platform_strerror (int errnum)
int platform_setenv (const char *name, const char *value)
int platform_unsetenv (const char *name)
pid_t platform_get_pid (void)
Detailed Description
System utilities for WASM/Emscripten - includes generic implementations.
This file is structured like posix/system.c and windows/system.c:
Platform-specific implementations go first
Generic implementations from ../system.c are included at the end
Definition in file wasm/system.c.
Function Documentation
platform_get_pid()
pid_t platform_get_pid (void)
Definition at line 61 of file wasm/system.c.
{
  return 1; // WASM runs in browser - no process ID concept
}
Referenced by asciichat_instr_runtime_get(), and options_state_init().
platform_getenv()
const char * platform_getenv (const char * name)
Definition at line 39 of file wasm/system.c.
{
  (void)name;
  // Environment variables not supported in WASM browser context
  // Calling getenv() causes "memory access out of bounds" errors
  return NULL;
}
Referenced by client_audio_pipeline_process_duplex(), client_crypto_handshake(), crypto_handshake_client_key_exchange(), ed25519_verify_signature(), get_discovery_database_dir(), options_init(), parse_ssh_private_key(), path_validate_user_path(), and prompt_unknown_host().
platform_setenv()
int platform_setenv (const char * name, const char * value)
Definition at line 50 of file wasm/system.c.
{
  (void)name;
  (void)value;
  return -1; // Not supported in WASM
}
Referenced by __attribute__().
platform_strerror()
const char * platform_strerror (int errnum)
Definition at line 46 of file wasm/system.c.
{
  return strerror(errnum);
}
Referenced by file_read_error_message(), and file_write_error_message().
platform_unsetenv()
int platform_unsetenv (const char * name)
Definition at line 56 of file wasm/system.c.
{
  (void)name;
  return -1; // Not supported in WASM
}