ascii-chat: zsh.c File Reference
zsh.c File Reference
Zsh shell completion script generator with category grouping.
Functions
asciichat_error_t completions_generate_zsh (FILE *output)
Detailed Description
Zsh shell completion script generator with category grouping.
Definition in file zsh.c.
Function Documentation
completions_generate_zsh()
asciichat_error_t completions_generate_zsh (FILE * output)
Definition at line 135 of file zsh.c.
{
  if (!output) {
    return SET_ERRNO(ERROR_INVALID_PARAM, "Output stream cannot be NULL");
  }
  fprintf(output, "#compdef _ascii_chat ascii-chat\n"
#ifndef NDEBUG
                  "#compdef _ascii_chat build/bin/ascii-chat ./build/bin/ascii-chat\n"
#endif
                  "# Zsh completion script for ascii-chat\n"
                  "# Generated from options registry - DO NOT EDIT MANUALLY\n"
                  "\n"
                  "_ascii_chat() {\n"
                  "  local curcontext=\"$curcontext\" state line modes\n"
                  "  _arguments \\\n"
                  "    '1:mode:->mode' \\\n"
                  "    '*::args:_ascii_chat_args'\n"
                  "  case $state in\n"
                  "    mode)\n"
                  "      local -a server_modes client_modes\n"
                  "      server_modes=(\n");
  /* Generate server-like modes from registry */
  size_t mode_server_count = 0;
  const mode_descriptor_t *mode_server_descs = get_modes_by_group("server-like", &mode_server_count);
  if (mode_server_descs) {
    for (size_t i = 0; i < mode_server_count; i++) {
      fprintf(output, "        '%s:%s'\n", mode_server_descs[i].name, mode_server_descs[i].description);
    }
    SAFE_FREE(mode_server_descs);
  }
  fprintf(output, "      )\n"
                  "      client_modes=(\n");
  /* Generate client-like modes from registry */
  size_t mode_client_count = 0;
  const mode_descriptor_t *mode_client_descs = get_modes_by_group("client-like", &mode_client_count);
  if (mode_client_descs) {
    for (size_t i = 0; i < mode_client_count; i++) {
      fprintf(output, "        '%s:%s'\n", mode_client_descs[i].name, mode_client_descs[i].description);
    }
    SAFE_FREE(mode_client_descs);
  }
  fprintf(output, "      )\n"
                  "      _describe -t server-modes 'server-like modes' server_modes\n"
                  "      _describe -t client-modes 'client-like modes' client_modes\n"
                  "      ;;\n"
                  "  esac\n"
                  "}\n"
                  "\n"
                  "_ascii_chat_args() {\n"
                  "  case $words[1] in\n"
                  "    # Server-like modes\n"
                  "    server)\n"
                  "      _ascii_chat_server\n"
                  "      ;;\n"
                  "    discovery-service)\n"
                  "      _ascii_chat_discovery_service\n"
                  "      ;;\n"
                  "\n"
                  "    # Client-like modes\n"
                  "    client)\n"
                  "      _ascii_chat_client\n"
                  "      ;;\n"
                  "    mirror)\n"
                  "      _ascii_chat_mirror\n"
                  "      ;;\n"
                  "\n"
                  "    *)\n"
                  "      # Binary-level options\n");
  /* Binary options - grouped by category */
  size_t binary_count = 0;
  const option_descriptor_t *binary_opts = options_registry_get_for_display(MODE_DISCOVERY, true, &binary_count);
  if (binary_opts) {
    zsh_write_options_grouped(output, binary_opts, binary_count, "binary");
    SAFE_FREE(binary_opts);
  }
  fprintf(output, "      ;;\n"
                  "  esac\n"
                  "}\n"
                  "\n"
                  "# Server-like modes: handle incoming connections and stream management\n"
                  "_ascii_chat_server() {\n");
  /* Server options - grouped by category */
  size_t server_count = 0;
  const option_descriptor_t *server_opts = options_registry_get_for_display(MODE_SERVER, false, &server_count);
  if (server_opts) {
    zsh_write_options_grouped(output, server_opts, server_count, "server");
    SAFE_FREE(server_opts);
  }
  fprintf(output, "}\n"
                  "\n"
                  "_ascii_chat_discovery_service() {\n");
  /* Discovery-service options - grouped by category */
  size_t discovery_svc_count = 0;
  const option_descriptor_t *discovery_svc_opts =
      options_registry_get_for_display(MODE_DISCOVERY_SERVICE, false, &discovery_svc_count);
  if (discovery_svc_opts) {
    zsh_write_options_grouped(output, discovery_svc_opts, discovery_svc_count, "discovery_service");
    SAFE_FREE(discovery_svc_opts);
  }
  fprintf(output, "}\n"
                  "\n"
                  "# Client-like modes: connect to servers or render local media\n"
                  "_ascii_chat_client() {\n");
  /* Client options - grouped by category */
  size_t client_count = 0;
  const option_descriptor_t *client_opts = options_registry_get_for_display(MODE_CLIENT, false, &client_count);
  if (client_opts) {
    zsh_write_options_grouped(output, client_opts, client_count, "client");
    SAFE_FREE(client_opts);
  }
  fprintf(output, "}\n"
                  "\n"
                  "_ascii_chat_mirror() {\n");
  /* Mirror options - grouped by category */
  size_t mirror_count = 0;
  const option_descriptor_t *mirror_opts = options_registry_get_for_display(MODE_MIRROR, false, &mirror_count);
  if (mirror_opts) {
    zsh_write_options_grouped(output, mirror_opts, mirror_count, "mirror");
    SAFE_FREE(mirror_opts);
  }
  fprintf(output, "}\n"
                  "\n"
                  "_ascii_chat \"$@\"\n");
  return ASCIICHAT_OK;
}
References get_modes_by_group(), and options_registry_get_for_display().
Referenced by completions_generate_for_shell().