name: 'Install Dependencies'
description: 'Install and cache build dependencies for ascii-chat'
inputs:
  os:
    description: 'Operating system (ubuntu, macos, or windows)'
    required: true
  extra-packages:
    description: 'Additional packages to install (space-separated)'
    required: false
    default: ''
  vcpkg-packages:
    description: 'Space-separated vcpkg packages to install for the primary triplet (Windows only)'
    required: false
    default: ''
  vcpkg-triplet:
    description: 'vcpkg triplet to use for primary packages (Windows only)'
    required: false
    default: 'x64-windows'
  vcpkg-static-packages:
    description: 'Space-separated vcpkg packages to install for the static triplet (Windows only)'
    required: false
    default: ''
  vcpkg-static-triplet:
    description: 'vcpkg triplet to use for static packages (Windows only)'
    required: false
    default: 'x64-windows-static'

runs:
  using: 'composite'
  steps:
    - name: Set up CMake dependency cache (All platforms)
      uses: actions/cache@v4
      with:
        path: |
          .deps-cache
          .deps-cache-musl
          deps/bearssl/build
        key: ${{ runner.os }}-cmake-deps-v1-${{ hashFiles('CMakeLists.txt', 'cmake/MuslDependencies.cmake', 'deps/bearssl/**') }}
        restore-keys: |
          ${{ runner.os }}-cmake-deps-v1-
          ${{ runner.os }}-cmake-deps-
        save-always: true

    - name: Set up Homebrew cache (macOS)
      if: inputs.os == 'macos'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/Cellar
          /opt/homebrew/opt
        key: ${{ runner.os }}-homebrew-v2-${{ inputs.extra-packages }}
        restore-keys: |
          ${{ runner.os }}-homebrew-v2-
          ${{ runner.os }}-homebrew-
        save-always: true

    - name: Install Homebrew packages (macOS)
      if: inputs.os == 'macos'
      shell: bash
      run: |
        # Update Homebrew
        brew update

        # Install packages
        PACKAGES="pkg-config llvm cmake make ninja zstd portaudio libsodium criterion coreutils ${{ inputs.extra-packages }}"

        echo "Installing Homebrew packages: $PACKAGES"
        for pkg in $PACKAGES; do
          if brew list --formula | grep -q "^${pkg}\$"; then
            echo "✓ $pkg already installed"
          else
            echo "Installing $pkg..."
            brew install "$pkg"
          fi
        done

        # Clean up to reduce cache size
        brew cleanup

    - name: Install and cache APT packages (Ubuntu)
      if: inputs.os == 'ubuntu'
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: clang cmake ninja-build zstd portaudio19-dev libjack-jackd2-0 libjack-jackd2-dev libasound2-dev libboxfort-dev libsodium-dev libcriterion-dev libgit2-dev libnanomsg-dev libnanomsg5 libprotobuf-c-dev libprotobuf-c1 libprotobuf-dev libssl-dev libssh2-1-dev libhttp-parser-dev libpcre2-dev libpcre2-8-0 libkrb5-dev krb5-multidev libgssapi-krb5-2 libkrb5-3 libk5crypto3 libcom-err2 libnanopb-dev pkg-config libxml2-utils python3-pip llvm musl-tools musl-dev ${{ inputs.extra-packages }}
        cache: yes

    - name: Cache vcpkg packages (Windows)
      if: inputs.os == 'windows' && env.VCPKG_ROOT != ''
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.VCPKG_ROOT }}/installed
          ${{ env.VCPKG_ROOT }}/packages
          ${{ env.VCPKG_ROOT }}/buildtrees
        key: ${{ runner.os }}-vcpkg-v1-${{ inputs.vcpkg-packages }}-${{ inputs.vcpkg-static-packages }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-v1-
        save-always: true

    - name: Set CSTD env var (POSIX)
      if: inputs.os != 'windows'
      shell: bash
      run: |
        # Setup CSTD
        export CSTD=c2x
        echo "CSTD=$CSTD" >> $GITHUB_ENV
        echo "Set CSTD to $CSTD"

    - name: Set CSTD env var (Windows)
      if: inputs.os == 'windows'
      shell: pwsh
      run: |
        $value = 'c2x'
        Add-Content -Path $env:GITHUB_ENV -Value "CSTD=$value"
        Write-Host "Set CSTD to $value"

    - name: Install Windows build tools
      if: inputs.os == 'windows'
      shell: pwsh
      run: |
        $basePackages = @('cmake', 'ninja', 'llvm', 'git', '7zip')
        $extra = @()
        if (-not [string]::IsNullOrWhiteSpace('${{ inputs.extra-packages }}')) {
          $extra = '${{ inputs.extra-packages }}'.Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
        }
        $packages = $basePackages + $extra

        foreach ($pkg in $packages) {
          Write-Host "Ensuring Chocolatey package '$pkg' is installed"
          choco install $pkg --no-progress -y
        }

        $llvmPath = 'C:\Program Files\LLVM\bin'
        if (Test-Path $llvmPath) {
          Write-Host "Adding LLVM to PATH"
          Add-Content -Path $env:GITHUB_PATH -Value $llvmPath
        }

    - name: Set up build environment (macOS)
      if: inputs.os == 'macos'
      shell: bash
      run: |
        # NOTE: `brew info make` says "make" is installed as "gmake", but they give us gnubin
        export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
        export PATH="/usr/local/opt/llvm/bin:$PATH"

        export PKG_CONFIG_LIBS=portaudio-2.0 criterion zstd libsodium

        # Set up PATH
        echo "PATH=$PATH" >> $GITHUB_ENV

        # Set up pkg-config path for Homebrew packages (always needed)
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CPPFLAGS=$CPPFLAGS" >> $GITHUB_ENV
        echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
        echo "PKG_CONFIG_LIBS=$PKG_CONFIG_LIBS" >> $GITHUB_ENV

        # Verify they will be set for subsequent steps
        echo "Set PKG_CONFIG_PATH to $PKG_CONFIG_PATH"
        echo "Set CPPFLAGS to $CPPFLAGS"
        echo "Set LDFLAGS to $LDFLAGS"

        # Debug: Check if pkg-config can find portaudio immediately after setting env vars
        echo "Debug: Testing pkg-config with PKG_CONFIG_PATH and PKG_CONFIG_LIBS..."
        pkg-config --libs --cflags "$PKG_CONFIG_LIBS"

        # Debug: Check if .pc files exist
        echo "Debug: Checking .pc files existence..."
        for lib in $PKG_CONFIG_LIBS; do
          ls -la /opt/homebrew/lib/pkgconfig/"$lib".pc || (
            echo "ERROR: No $lib .pc files in /opt/homebrew/lib/pkgconfig/"
            exit 1
          )
        done

        # Configure clang to work without Command Line Tools
        # This allows Homebrew LLVM to find the macOS SDK
        mkdir -p ~/.config/clang

        # Get Darwin version for config filename
        DARWIN_VERSION=$(uname -r | cut -d. -f1)
        SDK_PATH=$(xcrun --show-sdk-path 2>/dev/null || echo "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk")

        # Create x86_64 config
        cat > ~/.config/clang/x86_64-apple-darwin${DARWIN_VERSION}.cfg << EOF
        # Clang configuration for x86_64 macOS
        -isysroot ${SDK_PATH}
        -isystem ${SDK_PATH}/usr/include
        -stdlib=libc++
        -resource-dir /usr/local/opt/llvm/lib/clang/21
        EOF

        # Create ARM64 config
        cat > ~/.config/clang/arm64-apple-darwin${DARWIN_VERSION}.cfg << EOF
        # Clang configuration for ARM64 macOS
        -isysroot ${SDK_PATH}
        -isystem ${SDK_PATH}/usr/include
        -stdlib=libc++
        -resource-dir /usr/local/opt/llvm/lib/clang/21
        EOF

        echo "Created clang config files for darwin${DARWIN_VERSION}"
        ls -la ~/.config/clang/

    - name: Install vcpkg packages (Windows)
      if: inputs.os == 'windows'
      shell: pwsh
      run: |
        if (-not $env:VCPKG_ROOT) {
          Write-Host "VCPKG_ROOT is not set. Please run lukka/run-vcpkg before install-deps." -ForegroundColor Red
          exit 1
        }

        function Install-VcpkgPackages {
          param(
            [string]$PackageList,
            [string]$Triplet
          )

          if ([string]::IsNullOrWhiteSpace($PackageList)) {
            return
          }

          $packages = $PackageList.Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
          foreach ($pkg in $packages) {
            Write-Host "Installing vcpkg package: $pkg:$Triplet"
            vcpkg install "$pkg`:$Triplet"
          }
        }

        Install-VcpkgPackages -PackageList '${{ inputs.vcpkg-packages }}' -Triplet '${{ inputs.vcpkg-triplet }}'
        Install-VcpkgPackages -PackageList '${{ inputs.vcpkg-static-packages }}' -Triplet '${{ inputs.vcpkg-static-triplet }}'
