name: 'Install Dependencies'
description: 'Install and cache build dependencies for ASCII-Chat'
inputs:
  os:
    description: 'Operating system (ubuntu or macos)'
    required: true
  extra-packages:
    description: 'Additional packages to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install and cache Homebrew packages (macOS)
      if: inputs.os == 'macos'
      uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: portaudio libsodium criterion ${{ inputs.extra-packages }}
        cache: yes

    - name: Install and cache APT packages (Ubuntu)
      if: inputs.os == 'ubuntu'
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: clang libv4l-dev zlib1g-dev portaudio19-dev libsodium-dev libcriterion-dev pkg-config ${{ inputs.extra-packages }}
        cache: yes

    - name: Set up build environment (macOS)
      if: inputs.os == 'macos'
      shell: bash
      run: |
        # Set up pkg-config path for Homebrew packages (always needed)
        echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/opt/homebrew/include" >> $GITHUB_ENV
        echo "LDFLAGS=-L/opt/homebrew/lib" >> $GITHUB_ENV

        # Verify they will be set for subsequent steps
        echo "Set PKG_CONFIG_PATH to /opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig"
        echo "Set CPPFLAGS to -I/opt/homebrew/include"
        echo "Set LDFLAGS to -L/opt/homebrew/lib"

        # Debug: Check if pkg-config can find portaudio immediately after setting env vars
        echo "Debug: Testing pkg-config with PKG_CONFIG_PATH..."
        export PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig
        pkg-config --libs portaudio-2.0 || echo "ERROR: pkg-config cannot find portaudio-2.0"

        # Debug: Check if .pc files exist
        echo "Debug: Checking .pc files existence..."
        ls -la /opt/homebrew/lib/pkgconfig/portaudio* || echo "ERROR: No portaudio .pc files in /opt/homebrew/lib/pkgconfig/"
        ls -la /opt/homebrew/opt/portaudio/lib/pkgconfig/ || echo "ERROR: No portaudio directory in /opt/homebrew/opt/"
