/**
 * @file lib/font.c
 * @ingroup font
 * @brief Bundled font data storage
 *
 * The g_font_matrix_resurrected array is generated from lib/assets/fonts/Matrix-Resurrected.ttf
 * at build time using the bin2c.cmake tool.
 * Only compiled when render-file is enabled.
 */

#ifndef _WIN32
// Placeholder: the actual array is generated by CMake at build time
// This file exists to define the scope and documentation for the bundled font data.

// Generated font data will be linked in from the CMake-generated object file
// See: lib/video/ffmpeg/encoder.c for usage
#endif
