name: 'Cache CMake Build'
description: 'Restore the configured CMake build and dependency caches, and expose cache metadata for later save steps.'

inputs:
  build-directory:
    description: 'Absolute or relative path to the configured CMake build directory.'
    required: false
    default: build
  build-cache-key:
    description: 'Additional suffix applied to the build directory cache key (e.g. build type).'
    required: false
    default: ''
  deps-cache-directory:
    description: 'Path to the dependency cache directory (e.g. .deps-cache).'
    required: false
    default: .deps-cache
  cache-deps:
    description: 'Set to false to skip managing the dependency cache directory.'
    required: false
    default: 'true'
  ccache-directory:
    description: 'Path to the ccache directory to cache.'
    required: false
    default: ~/.ccache
  ccache-cache-key:
    description: 'Additional suffix applied to the ccache cache key (e.g. target triple).'
    required: false
    default: ''
  cache-ccache:
    description: 'Set to false to skip managing the ccache directory.'
    required: false
    default: 'true'
  cache-version:
    description: 'Version string used to invalidate both caches when inputs change.'
    required: false
    default: v3

outputs:
  build-cache-key:
    description: 'Fully qualified cache key for the build directory.'
    value: ${{ format('{0}-build-{1}-{2}-{3}-{4}-{5}', inputs.cache-version, runner.os, runner.arch, github.workflow, github.job, steps.cache-config.outputs.build_suffix) }}
  build-cache-hit:
    description: 'Whether the build directory cache was restored.'
    value: ${{ steps.cache-build-dir.outputs.cache-hit }}
  build-directory-path:
    description: 'Path to the build directory.'
    value: ${{ inputs.build-directory }}
  deps-cache-key:
    description: 'Fully qualified cache key for the dependency cache.'
    value: ${{ format('{0}-deps-{1}-{2}-{3}', inputs.cache-version, runner.os, runner.arch, steps.cache-config.outputs.build_suffix) }}
  deps-cache-hit:
    description: 'Whether the dependency cache was restored.'
    value: ${{ steps.cache-deps-dir.outputs.cache-hit }}
  cache-deps-enabled:
    description: 'Whether deps caching is enabled.'
    value: ${{ inputs.cache-deps }}
  deps-cache-path:
    description: 'Path to the dependency cache directory.'
    value: ${{ inputs.deps-cache-directory }}
  ccache-cache-key:
    description: 'Fully qualified cache key for ccache.'
    value: ${{ format('{0}-ccache-{1}-{2}-{3}', inputs.cache-version, runner.os, runner.arch, steps.cache-config.outputs.ccache_suffix) }}
  ccache-cache-hit:
    description: 'Whether the ccache directory was restored.'
    value: ${{ steps.cache-ccache.outputs.cache-hit }}
  cache-ccache-enabled:
    description: 'Whether ccache caching is enabled.'
    value: ${{ inputs.cache-ccache }}
  ccache-directory-path:
    description: 'Path to the ccache directory.'
    value: ${{ inputs.ccache-directory }}

runs:
  using: composite
  steps:
    - name: Prepare cache keys
      id: cache-config
      shell: bash
      env:
        BUILD_SUFFIX_INPUT: ${{ inputs.build-cache-key }}
        CCACHE_SUFFIX_INPUT: ${{ inputs.ccache-cache-key }}
        CACHE_HASH: ${{ hashFiles('CMakeLists.txt', 'cmake/**/*.cmake') }}
      run: |
        build_suffix="$CACHE_HASH"
        ccache_suffix="$CACHE_HASH"

        if [ -n "$BUILD_SUFFIX_INPUT" ]; then
          build_suffix="${BUILD_SUFFIX_INPUT}-${CACHE_HASH}"
        fi

        if [ -n "$CCACHE_SUFFIX_INPUT" ]; then
          ccache_suffix="${CCACHE_SUFFIX_INPUT}-${CACHE_HASH}"
        fi

        echo "build_suffix=${build_suffix}" >> "$GITHUB_OUTPUT"
        echo "ccache_suffix=${ccache_suffix}" >> "$GITHUB_OUTPUT"

    - name: Ensure cache directories exist
      shell: bash
      run: |
        mkdir -p "${{ inputs.build-directory }}"
        if [ "${{ inputs.cache-deps }}" = "true" ]; then
          mkdir -p "${{ inputs.deps-cache-directory }}"
        fi
        if [ "${{ inputs.cache-ccache }}" = "true" ]; then
          mkdir -p "${{ inputs.ccache-directory }}"
          echo "CCACHE_DIR=${{ inputs.ccache-directory }}" >> "${GITHUB_ENV}"
        fi

    - name: Restore build directory cache
      id: cache-build-dir
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.build-directory }}
        key: ${{ format('{0}-build-{1}-{2}-{3}-{4}-{5}', inputs.cache-version, runner.os, runner.arch, github.workflow, github.job, steps.cache-config.outputs.build_suffix) }}
        restore-keys: |
          ${{ format('{0}-build-{1}-{2}-{3}-{4}-', inputs.cache-version, runner.os, runner.arch, github.workflow, github.job) }}
          ${{ format('{0}-build-{1}-{2}-{3}-', inputs.cache-version, runner.os, runner.arch, github.workflow) }}
          ${{ format('{0}-build-{1}-{2}-', inputs.cache-version, runner.os, runner.arch) }}

    - name: Restore dependency cache directory
      if: inputs.cache-deps == 'true'
      id: cache-deps-dir
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.deps-cache-directory }}
        key: ${{ format('{0}-deps-{1}-{2}-{3}', inputs.cache-version, runner.os, runner.arch, steps.cache-config.outputs.build_suffix) }}
        restore-keys: |
          ${{ format('{0}-deps-{1}-{2}-', inputs.cache-version, runner.os, runner.arch) }}

    - name: Restore ccache directory
      if: inputs.cache-ccache == 'true'
      id: cache-ccache
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.ccache-directory }}
        key: ${{ format('{0}-ccache-{1}-{2}-{3}', inputs.cache-version, runner.os, runner.arch, steps.cache-config.outputs.ccache_suffix) }}
        restore-keys: |
          ${{ format('{0}-ccache-{1}-{2}-', inputs.cache-version, runner.os, runner.arch) }}
