/**
 * @file audio.c
 * @brief Audio processing options
 * @ingroup options
 *
 * Options for audio input/output devices, volume control, audio sources,
 * encoding, and mixing.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include <ascii-chat/options/registry/common.h>
#include <ascii-chat/options/registry/metadata.h>

#include <ascii-chat/options/parsers.h>

// ============================================================================
// AUDIO CATEGORY - Audio processing options
// ============================================================================
static bool validate_audio_fft_size(const void *data, char **error_msg) {
  const options_t *options = data;
  if (options->audio_fft_size == 512 || options->audio_fft_size == 1024 || options->audio_fft_size == 2048)
    return true;
  if (error_msg)
    *error_msg = platform_strdup("audio-fft-size must be 512, 1024, or 2048");
  return false;
}

static const bool default_audio_spectral = false;
static const bool default_audio_spectral_gate = true;
static const bool default_audio_multiband = false;
static const bool default_audio_adaptive_eq = false;
static const int default_audio_fft_size = 1024;
static const bool default_audio_pitch_correct = false;
static const bool default_audio_spectral_agc = false;
const registry_entry_t g_audio_entries[] = {
    {"audio-spectral-agc",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_spectral_agc),
     &default_audio_spectral_agc,
     sizeof(bool),
     "Enable spectral RMS gain control with --audio-spectral.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_SPECTRAL_AGC",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"audio-pitch-correct",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_pitch_correct),
     &default_audio_pitch_correct,
     sizeof(bool),
     "Experimental monophonic semitone correction with --audio-spectral.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_PITCH_CORRECT",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"audio-spectral",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_spectral),
     &default_audio_spectral,
     sizeof(bool),
     "Enable FFTW capture/mixer processing (adds FFT-size samples of latency).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_SPECTRAL",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"audio-spectral-gate",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_spectral_gate),
     &default_audio_spectral_gate,
     sizeof(bool),
     "Enable adaptive spectral noise reduction with --audio-spectral.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_SPECTRAL_GATE",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"audio-multiband",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_multiband),
     &default_audio_multiband,
     sizeof(bool),
     "Enable four-band compression with --audio-spectral.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_MULTIBAND",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"audio-adaptive-eq",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_adaptive_eq),
     &default_audio_adaptive_eq,
     sizeof(bool),
     "Enable bounded spectral EQ balancing with --audio-spectral.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_ADAPTIVE_EQ",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"audio-fft-size",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, audio_fft_size),
     &default_audio_fft_size,
     sizeof(int),
     "Spectral FFT size: 512, 1024, or 2048 (latency versus frequency resolution).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_FFT_SIZE",
     validate_audio_fft_size,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    // AUDIO GROUP (client, discovery)
    {"audio",
     'A',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_enabled),
     &default_audio_enabled_value,
     sizeof(bool),
     "Enable audio streaming (press 'm' during rendering to toggle).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"microphone-index",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, microphone_index),
     &default_microphone_index_value,
     sizeof(int),
     "Microphone device index for audio input.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_MICROPHONE_INDEX",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {.numeric_range = {-1, 10, 1}, .examples = g_mic_examples, .input_type = OPTION_INPUT_NUMERIC},
     NULL},
    {"speakers-index",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, speakers_index),
     &default_speakers_index_value,
     sizeof(int),
     "Speakers device index to use for audio output.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_SPEAKERS_INDEX",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {.numeric_range = {-1, 10, 1}, .examples = g_speakers_examples, .input_type = OPTION_INPUT_NUMERIC},
     NULL},
    {"microphone-volume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, microphone_sensitivity),
     &default_microphone_sensitivity_value,
     sizeof(float),
     "Microphone volume multiplier (0.0-1.0).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_MICROPHONE_VOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}},
     NULL},
    {"ivolume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, microphone_sensitivity),
     &default_microphone_sensitivity_value,
     sizeof(float),
     "Alias for --microphone-volume.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_IVOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}},
     NULL},
    {"speakers-volume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, speakers_volume),
     &default_speakers_volume_value,
     sizeof(float),
     "Speakers volume multiplier (0.0-1.0; press =/- during rendering to adjust).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_SPEAKERS_VOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}},
     NULL},
    {"volume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, speakers_volume),
     &default_speakers_volume_value,
     sizeof(float),
     "Alias for --speakers-volume.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_VOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}},
     NULL},
    {"audio-source",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, audio_source),
     &default_audio_source_value,
     sizeof(audio_source_t),
     "Select audio shown by --waveform/--fft: all (default), call, mic, or media.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_SOURCE",
     NULL,
     parse_audio_source,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_audio_source_values,
      .enum_descriptions = g_audio_source_descs,
      .enum_integer_values = g_audio_source_integers,
      .input_type = OPTION_INPUT_ENUM},
     NULL},
    {"audio-capture-source",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, audio_capture_source),
     &default_audio_capture_source_value,
     sizeof(audio_capture_source_t),
     "Select local audio capture and media playback: auto, mic, media, both, or remote.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_CAPTURE_SOURCE",
     NULL,
     parse_audio_capture_source,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_audio_capture_source_values,
      .enum_descriptions = g_audio_capture_source_descs,
      .enum_integer_values = g_audio_capture_source_integers,
      .input_type = OPTION_INPUT_ENUM},
     NULL},
#ifdef DEBUG
    {"audio-analysis",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_analysis_enabled),
     &default_audio_analysis_value,
     sizeof(bool),
     "Enable audio analysis (debug).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_ANALYSIS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
#endif
    {"no-audio-playback",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_no_playback),
     &default_no_audio_playback_value,
     sizeof(bool),
     "Disable speakers output.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_NO_AUDIO_PLAYBACK",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"encode-audio",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, encode_audio),
     &default_encode_audio_value,
     sizeof(bool),
     "Enable Opus audio encoding.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_ENCODE_AUDIO",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"no-encode-audio",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, encode_audio),
     &default_no_encode_audio_value,
     sizeof(bool),
     "Disable Opus audio encoding.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_NO_ENCODE_AUDIO",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"no-audio-mixer",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_audio_mixer),
     &default_no_audio_mixer_value,
     sizeof(bool),
     "Use simple audio mixing without ducking or compression (debug mode only).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_NO_AUDIO_MIXER",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER,
     {0},
     NULL},
    {"list-microphones",
     '\0',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "List available audio input devices by index and exit.",
     "AUDIO",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0},
     NULL},
    {"list-speakers",
     '\0',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "List available audio output devices by index and exit.",
     "AUDIO",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0},
     NULL},

    REGISTRY_TERMINATOR()};
