/**
 * @file audio.c
 * @brief Audio processing options
 * @ingroup options
 *
 * Options for audio input/output devices, volume control, audio sources,
 * encoding, and mixing.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include <ascii-chat/options/registry/common.h>
#include <ascii-chat/options/registry/metadata.h>

#include <ascii-chat/options/parsers.h>

// ============================================================================
// AUDIO CATEGORY - Audio processing options
// ============================================================================
const registry_entry_t g_audio_entries[] = {
    // AUDIO GROUP (client, discovery)
    {"audio",
     'A',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_enabled),
     &default_audio_enabled_value,
     sizeof(bool),
     "Enable audio streaming (press 'm' during rendering to toggle).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"microphone-index",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, microphone_index),
     &default_microphone_index_value,
     sizeof(int),
     "Microphone device index for audio input.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_MICROPHONE_INDEX",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {.numeric_range = {-1, 10, 1}, .examples = g_mic_examples, .input_type = OPTION_INPUT_NUMERIC}},
    {"speakers-index",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, speakers_index),
     &default_speakers_index_value,
     sizeof(int),
     "Speakers device index to use for audio output.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_SPEAKERS_INDEX",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {.numeric_range = {-1, 10, 1}, .examples = g_speakers_examples, .input_type = OPTION_INPUT_NUMERIC}},
    {"microphone-volume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, microphone_sensitivity),
     &default_microphone_sensitivity_value,
     sizeof(float),
     "Microphone volume multiplier (0.0-1.0).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_MICROPHONE_VOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}}},
    {"ivolume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, microphone_sensitivity),
     &default_microphone_sensitivity_value,
     sizeof(float),
     "Alias for --microphone-volume.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_IVOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}}},
    {"speakers-volume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, speakers_volume),
     &default_speakers_volume_value,
     sizeof(float),
     "Speakers volume multiplier (0.0-1.0; press ↑/↓ during rendering to adjust).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_SPEAKERS_VOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}}},
    {"volume",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, speakers_volume),
     &default_speakers_volume_value,
     sizeof(float),
     "Alias for --speakers-volume.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_VOLUME",
     NULL,
     parse_volume,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 1, 0}}},
    {"audio-source",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, audio_source),
     &default_audio_source_value,
     sizeof(audio_source_t),
     "Select which audio sources to use: auto (smart), mic, media, or both.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_SOURCE",
     NULL,
     parse_audio_source,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_audio_source_values,
      .enum_count = 4,
      .enum_descriptions = g_audio_source_descs,
      .enum_integer_values = g_audio_source_integers,
      .input_type = OPTION_INPUT_ENUM}},
#ifdef DEBUG
    {"audio-analysis",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_analysis_enabled),
     &default_audio_analysis_value,
     sizeof(bool),
     "Enable audio analysis (debug).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_AUDIO_ANALYSIS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
#endif
    {"no-audio-playback",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, audio_no_playback),
     &default_no_audio_playback_value,
     sizeof(bool),
     "Disable speakers output.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_NO_AUDIO_PLAYBACK",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
    {"encode-audio",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, encode_audio),
     &default_encode_audio_value,
     sizeof(bool),
     "Enable Opus audio encoding.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_ENCODE_AUDIO",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
    {"no-encode-audio",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, encode_audio),
     &default_no_encode_audio_value,
     sizeof(bool),
     "Disable Opus audio encoding.",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_NO_ENCODE_AUDIO",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
    {"no-audio-mixer",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_audio_mixer),
     &default_no_audio_mixer_value,
     sizeof(bool),
     "Use simple audio mixing without ducking or compression (debug mode only).",
     "AUDIO",
     NULL,
     false,
     "ASCII_CHAT_NO_AUDIO_MIXER",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER,
     {0}},
    {"list-microphones",
     '\0',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "List available audio input devices by index and exit.",
     "AUDIO",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0}},
    {"list-speakers",
     '\0',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "List available audio output devices by index and exit.",
     "AUDIO",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0}},

    REGISTRY_TERMINATOR()};
