/**
 * @file display.c
 * @brief Display layout and rendering options
 * @ingroup options
 *
 * Options for controlling rendering modes, palettes, color filters,
 * framerate, and snapshot mode.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include "common.h"
#include "metadata.h"

#include <ascii-chat/options/parsers.h>

// ============================================================================
// DISPLAY CATEGORY - Display layout options
// ============================================================================
const registry_entry_t g_display_entries[] = {
    // DISPLAY GROUP (client, mirror, discovery)
    {"color-filter",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, color_filter),
     &default_color_filter_value,
     sizeof(color_filter_t),
     "Apply a monochromatic color tint to grayscale video. Values: none, black, white, green, magenta, fuchsia, "
     "orange, "
     "teal, cyan, pink, red, yellow. Using --color-filter automatically sets --color-mode to mono.",
     "DISPLAY",
     NULL,
     false,
     "ASCII_CHAT_COLOR_FILTER",
     NULL,
     parse_color_filter,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_color_filter_values,
      .enum_count = 12,
      .enum_descriptions = g_color_filter_descs,
      .enum_integer_values = g_color_filter_integers,
      .input_type = OPTION_INPUT_ENUM}},
    {"render-mode",
     'M',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, render_mode),
     &default_render_mode_value,
     sizeof(render_mode_t),
     "Render mode of text for your client to display. Values: foreground, background, half-block. Press 'r' during "
     "rendering to cycle.",
     "DISPLAY",
     NULL,
     false,
     "ASCII_CHAT_RENDER_MODE",
     NULL,
     parse_render_mode,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_render_values,
      .enum_count = 5,
      .enum_descriptions = g_render_descs,
      .enum_integer_values = g_render_integers,
      .input_type = OPTION_INPUT_ENUM}},
    {"palette",
     'P',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, palette_type),
     &default_palette_type_value,
     sizeof(palette_type_t),
     "Palette type with which to render images to text art. Values: standard, blocks, digital, minimal, cool, "
     "custom. All but \"custom\" are built-in presets that all look different and nice. Try them out!",
     "DISPLAY",
     NULL,
     false,
     "ASCII_CHAT_PALETTE",
     NULL,
     parse_palette_type,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_palette_values,
      .enum_count = 6,
      .enum_descriptions = g_palette_descs,
      .enum_integer_values = g_palette_integers,
      .input_type = OPTION_INPUT_ENUM}},
    {"palette-chars",
     'C',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, palette_custom),
     "",
     0,
     "Ordered sequence of characters from darkest to brightest to use with custom palette (--palette=custom) for "
     "rendering images to text art for your client. These characters only will be used to create the rendered output. "
     "Can be UTF-8 content (see --utf8).",
     "DISPLAY",
     "STRING",
     false,
     "ASCII_CHAT_PALETTE_CHARS",
     NULL,
     parse_palette_chars,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"stretch",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, stretch),
     &default_stretch_value,
     sizeof(bool),
     "Allow aspect ratio distortion of image for rendering ascii output. This can allow the rendered ascii to fill "
     "your terminal.",
     "DISPLAY",
     NULL,
     false,
     "ASCII_CHAT_STRETCH",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"fps",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, fps),
     &default_fps_value,
     sizeof(int),
     "Target framerate for rendering (1-144).",
     "DISPLAY",
     NULL,
     false,
     "ASCII_CHAT_FPS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {1, 144, 1}, .examples = g_fps_examples, .input_type = OPTION_INPUT_NUMERIC}},
    {"snapshot",
     'S',
     OPTION_TYPE_BOOL,
     offsetof(options_t, snapshot_mode),
     &default_snapshot_mode_value,
     sizeof(bool),
     "Snapshot mode (one frame and exit).",
     "DISPLAY",
     NULL,
     false,
     "ASCII_CHAT_SNAPSHOT",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"snapshot-delay",
     'D',
     OPTION_TYPE_DOUBLE,
     offsetof(options_t, snapshot_delay),
     &default_snapshot_delay_value,
     sizeof(double),
     "Snapshot delay in seconds. The timer starts right before the client-side program prints the first frame. "
     "--snapshot --snapshot-delay=0 will print the first frame and exit.",
     "DISPLAY",
     "SECONDS",
     false,
     "ASCII_CHAT_SNAPSHOT_DELAY",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {0, 3600, 0}, .input_type = OPTION_INPUT_NUMERIC}},

    REGISTRY_TERMINATOR()};
