/**
 * @file general.c
 * @brief General options
 * @ingroup options
 *
 * General-purpose options including help, version, splash screen controls,
 * status screen controls, and keepawake settings.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include <ascii-chat/options/registry/common.h>

// ============================================================================
// GENERAL CATEGORY - General-purpose options
// ============================================================================
const registry_entry_t g_general_entries[] = {
    // GENERAL GROUP (binary-level + all modes)
    {"help",
     'h',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "Show this help message and exit.",
     "GENERAL",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY | OPTION_MODE_SERVER | OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY_SVC |
         OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"version",
     'v',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "Show version information and exit.",
     "GENERAL",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0},
     NULL},
    {"splash-screen",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, splash_screen),
     &default_splash_value,
     sizeof(bool),
     "Explicitly enable splash screen with ASCII art (overrides CLAUDECODE).",
     "GENERAL",
     NULL,
     false,
     "ASCII_CHAT_SPLASH_SCREEN",
     NULL,
     NULL,
     false,
     false, // no invert: --splash-screen enables splash
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"no-splash-screen",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, splash_screen),
     &default_splash_value,
     sizeof(bool),
     "Disable splash screen with ASCII art. Use --no-splash-screen to skip the splash screen on client, "
     "mirror, and discovery modes.",
     "GENERAL",
     NULL,
     false,
     "ASCII_CHAT_NO_SPLASH_SCREEN",
     NULL,
     NULL,
     false,
     true, // invert: default is true (splash shown), --no-splash-screen makes it false
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"status-screen",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, status_screen),
     &default_status_screen_value,
     sizeof(bool),
     "Explicitly enable status screen display (overrides non-interactive checks).",
     "GENERAL",
     NULL,
     false,
     "ASCII_CHAT_STATUS_SCREEN",
     NULL,
     NULL,
     false,
     false, // no invert: --status-screen enables status screen
     OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"no-status-screen",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, status_screen),
     &default_status_screen_value,
     sizeof(bool),
     "Disable status screen display on server and discovery-service modes.",
     "GENERAL",
     NULL,
     false,
     "ASCII_CHAT_NO_STATUS_SCREEN",
     NULL,
     NULL,
     false,
     true, // invert: default is true (status screen shown), --no-status-screen makes it false
     OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"keepawake",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, enable_keepawake),
     &default_enable_keepawake_value,
     sizeof(bool),
     "Explicitly enable system sleep prevention (keepawake mode).",
     "GENERAL",
     NULL,
     false,
     "ASCII_CHAT_KEEPAWAKE",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0},
     NULL},
    {"no-keepawake",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, disable_keepawake),
     &default_disable_keepawake_value,
     sizeof(bool),
     "Disable system sleep prevention (allow OS to sleep).",
     "GENERAL",
     NULL,
     false,
     "ASCII_CHAT_NO_KEEPAWAKE",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0},
     NULL},
    {"check-update",
     '\0',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "Check for updates from GitHub releases and exit.",
     "GENERAL",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0},
     NULL},
    {"no-check-update",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_check_update),
     &default_no_check_update_value,
     sizeof(bool),
     "Disable automatic update checks at startup.",
     "GENERAL",
     NULL,
     false,
     "ASCII_CHAT_NO_CHECK_UPDATE",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_ALL,
     {0},
     NULL},

    REGISTRY_TERMINATOR()};
