/**
 * @file media.c
 * @brief Media file and stream options
 * @ingroup options
 *
 * Options for streaming from media files, URLs, seeking, looping,
 * and cookie handling for streaming services.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include "common.h"
#include "metadata.h"

#include <ascii-chat/options/parsers.h>

// ============================================================================
// MEDIA CATEGORY - Media file and stream options
// ============================================================================
const registry_entry_t g_media_entries[] = {
    // Media File Streaming Options
    {"file",
     'f',
     OPTION_TYPE_STRING,
     offsetof(options_t, media_file),
     "",
     0,
     "Stream from media file or stdin (use '-' for stdin). Supported formats: see man ffmpeg-formats; codecs: see man "
     "ffmpeg-codecs",
     "MEDIA",
     NULL,
     false,
     "ASCII_CHAT_FILE",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"url",
     'u',
     OPTION_TYPE_STRING,
     offsetof(options_t, media_url),
     "",
     0,
     "Stream from network URL (HTTP/HTTPS/YouTube/RTSP). URL handler: see man yt-dlp; supported formats: see man "
     "ffmpeg-formats; codecs: see man ffmpeg-codecs.",
     "MEDIA",
     NULL,
     false,
     "ASCII_CHAT_URL",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"loop",
     'l',
     OPTION_TYPE_BOOL,
     offsetof(options_t, media_loop),
     &default_media_loop_value,
     sizeof(bool),
     "Loop media file playback (not supported for --url).",
     "MEDIA",
     NULL,
     false,
     "ASCII_CHAT_LOOP",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"pause",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, pause),
     &default_pause_value,
     sizeof(bool),
     "Start playback paused (toggle with spacebar, requires --file or --url).",
     "MEDIA",
     NULL,
     false,
     "ASCII_CHAT_PAUSE",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"seek",
     's',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, media_seek_timestamp),
     &default_media_seek_value,
     sizeof(double),
     "Seek to timestamp before playback (format: seconds, MM:SS, or HH:MM:SS.ms).",
     "MEDIA",
     NULL,
     false,
     "ASCII_CHAT_SEEK",
     NULL,
     parse_timestamp,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.examples = g_seek_examples, .input_type = OPTION_INPUT_STRING}},
    {"cookies-from-browser",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, cookies_from_browser),
     NULL,
     0,
     "yt-dlp option (man yt-dlp). Browser/keyring for reading cookies from. Defaults to 'chrome' if no "
     "argument provided. Any value is accepted and passed to yt-dlp; invalid values will produce an error "
     "from yt-dlp.",
     "MEDIA",
     NULL,
     false,
     "ASCII_CHAT_COOKIES_FROM_BROWSER",
     NULL,
     parse_cookies_from_browser,
     false,
     true,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},
    {"no-cookies-from-browser",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_cookies_from_browser),
     false,
     sizeof(bool),
     "yt-dlp option (man yt-dlp). Explicitly disable reading cookies from browser.",
     "MEDIA",
     NULL,
     false,
     "ASCII_CHAT_NO_COOKIES_FROM_BROWSER",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0}},

    REGISTRY_TERMINATOR()};
