/**
 * @file network.c
 * @brief Network protocol options
 * @ingroup options
 *
 * Options for controlling ports, compression, discovery, WebRTC, and network connectivity.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include "common.h"
#include "metadata.h"

#include <ascii-chat/options/parsers.h>

// ============================================================================
// NETWORK CATEGORY - Network protocol options
// ============================================================================
const registry_entry_t g_network_entries[] = {
    // NETWORK GROUP - port and client management
    {"port",
     'p',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, port),
     &default_port_value,
     sizeof(int),
     "Port to host a server or discovery-service on, or port to connect to a server as a client (default: 27224 for "
     "server/client, 27225 for discovery-service).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_PORT",
     NULL,
     parse_port_option,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC | OPTION_MODE_DISCOVERY,
     {.numeric_range = {1, 65535, 1}, .input_type = OPTION_INPUT_NUMERIC}},
    {"max-clients",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, max_clients),
     &default_max_clients_value,
     sizeof(int),
     "Maximum concurrent clients.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_MAX_CLIENTS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC,
     {.numeric_range = {1, 99, 1}, .examples = g_maxclients_examples, .input_type = OPTION_INPUT_NUMERIC}},
    {"reconnect-attempts",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, reconnect_attempts),
     &default_reconnect_attempts_value,
     sizeof(int),
     "Number of reconnection attempts before giving up (-1=infinite, 0=none).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_RECONNECT_ATTEMPTS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {.numeric_range = {-1, 99, 1}, .examples = g_reconnect_examples, .input_type = OPTION_INPUT_NUMERIC}},
    {"port-forwarding",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, enable_upnp),
     &default_enable_upnp_value,
     sizeof(bool),
     "Use UPnP/NAT-PMP port mapping to open a port in your router to ascii-chat (might fail with some routers).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_PORT_FORWARDING",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC,
     {0}},
    {"scan",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, lan_discovery),
     &default_lan_discovery_value,
     sizeof(bool),
     "Scan for servers on local network via mDNS.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_SCAN",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},

    // NETWORK GROUP - compression options
    {"compression-level",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, compression_level),
     &default_compression_level_value,
     sizeof(int),
     "zstd compression level (1-9).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_COMPRESSION_LEVEL",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {.numeric_range = {1, 9, 1}, .examples = g_compression_examples, .input_type = OPTION_INPUT_NUMERIC}},
    {"no-compress",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_compress),
     &default_no_compress_value,
     sizeof(bool),
     "Disable compression.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_NO_COMPRESS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {0}},

    // NETWORK GROUP - discovery service options
    {"discovery-service",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, discovery_server),
     OPT_ENDPOINT_DISCOVERY_SERVICE,
     0,
     "Discovery service endpoint (IP address or hostname).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_DISCOVERY_SERVER",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {0}},
    {"discovery-port",
     '\0',
     OPTION_TYPE_INT,
     offsetof(options_t, discovery_port),
     &default_discovery_port_value,
     sizeof(int),
     "Discovery service port (1-65535).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_DISCOVERY_PORT",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {0}},
    {"discovery-expose-ip",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, discovery_expose_ip),
     &default_discovery_expose_ip_value,
     sizeof(bool),
     "Allow public IP disclosure in discovery sessions (requires confirmation).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_DISCOVERY_EXPOSE_IP",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {0}},
    {"discovery",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, discovery),
     &default_discovery_value,
     sizeof(bool),
     "Enable discovery session registration.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_DISCOVERY",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER,
     {0}},

    // NETWORK GROUP - WebRTC options
    {"webrtc",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, webrtc),
     &default_webrtc_value,
     sizeof(bool),
     "Make calls using WebRTC p2p connections.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_WEBRTC",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {0}},
    {"no-webrtc",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_webrtc),
     &default_no_webrtc_value,
     sizeof(bool),
     "Disable WebRTC, use direct TCP only.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_NO_WEBRTC",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
    {"prefer-webrtc",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, prefer_webrtc),
     &default_prefer_webrtc_value,
     sizeof(bool),
     "Try WebRTC before direct TCP.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_PREFER_WEBRTC",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
    {"webrtc-skip-stun",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, webrtc_skip_stun),
     &default_webrtc_skip_stun_value,
     sizeof(bool),
     "Skip WebRTC+STUN stage, go straight to TURN relay.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_WEBRTC_SKIP_STUN",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
    {"webrtc-disable-turn",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, webrtc_disable_turn),
     &default_webrtc_disable_turn_value,
     sizeof(bool),
     "Disable WebRTC+TURN relay, use STUN only.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_WEBRTC_DISABLE_TURN",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0}},
    {"webrtc-skip-host",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, webrtc_skip_host),
     &default_webrtc_skip_host_value,
     sizeof(bool),
     "Skip host candidates, force STUN/TURN (for testing).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_WEBRTC_SKIP_HOST",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {0}},
    {"stun-servers",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, stun_servers),
     OPT_STUN_SERVERS_DEFAULT,
     0,
     "Comma-separated list of WebRTC+STUN server URLs.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_STUN_SERVERS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC | OPTION_MODE_DISCOVERY,
     {0}},
    {"turn-servers",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, turn_servers),
     OPT_TURN_SERVERS_DEFAULT,
     0,
     "Comma-separated list of WebRTC+TURN server URLs.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_TURN_SERVERS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC | OPTION_MODE_DISCOVERY,
     {0}},
    {"turn-username",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, turn_username),
     OPT_TURN_USERNAME_DEFAULT,
     0,
     "Username for WebRTC+TURN authentication.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_TURN_USERNAME",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC | OPTION_MODE_DISCOVERY,
     {0}},
    {"turn-credential",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, turn_credential),
     OPT_TURN_CREDENTIAL_DEFAULT,
     0,
     "Credential/password for WebRTC+TURN authentication.",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_TURN_CREDENTIAL",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC | OPTION_MODE_DISCOVERY,
     {0}},
    {"turn-secret",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, turn_secret),
     "",
     0,
     "Shared secret for dynamic WebRTC+TURN credential generation (HMAC-SHA1).",
     "NETWORK",
     NULL,
     false,
     "ASCII_CHAT_TURN_SECRET",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY_SVC | OPTION_MODE_DISCOVERY,
     {0}},

    REGISTRY_TERMINATOR()};
