/**
 * @file security.c
 * @brief Security and authentication options
 * @ingroup options
 *
 * Options for encryption, key management, and authentication.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include <ascii-chat/options/registry/common.h>
#include <ascii-chat/options/parsers.h>

// ============================================================================
// SECURITY CATEGORY - Security and authentication options
// ============================================================================
const registry_entry_t g_security_entries[] = {
    // SECURITY GROUP (client, server, discovery)
    {"encrypt",
     'E',
     OPTION_TYPE_BOOL,
     offsetof(options_t, encrypt_enabled),
     &default_encrypt_enabled_value,
     sizeof(bool),
     "Enable end-to-end encryption (requires the other party to be encrypted as well).",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_ENCRYPT",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"key",
     'K',
     OPTION_TYPE_STRING,
     offsetof(options_t, encrypt_key),
     "",
     0,
     "Server identity key (SSH Ed25519 or GPG key file, gpg:FINGERPRINT, github:USER[.gpg], gitlab:USER[.gpg], or "
     "HTTPS URL like https://example.com/key.pub or .gpg).",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_KEY",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"password",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, password),
     "",
     0,
     "Shared password for authentication (8-256 characters).",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_PASSWORD",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"no-encrypt",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_encrypt),
     &default_no_encrypt_value,
     sizeof(bool),
     "Disable encryption (requires the other party to be unencrypted as well).",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_NO_ENCRYPT",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"no-auth",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, no_auth),
     &default_no_auth_value,
     sizeof(bool),
     "Disable authentication layer (--no-auth). Use with --no-encrypt to bypass ACIP entirely.",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_NO_AUTH",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"server-key",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, server_key),
     "",
     0,
     "Expected server public key for verification. Supports: raw base64 public key (AAAAC3Nz...), "
     "SSH/GPG key files, gpg:FINGERPRINT, github:USER[.gpg], gitlab:USER[.gpg], "
     "or HTTP(S) URLs like https://github.com/zfogg.[keys|gpg].",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_SERVER_KEY",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"client-keys",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, client_keys),
     "",
     0,
     "Allowed client keys (comma-separated). Supports: raw base64 public keys (AAAAC3Nz...), "
     "file paths with one key per line, github:USER[.gpg], gitlab:USER[.gpg], gpg:KEYID, "
     "or HTTP(S) URLs like https://github.com/zfogg.[keys|gpg].",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_CLIENT_KEYS",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY | OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"discovery-insecure",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, discovery_insecure),
     &default_discovery_insecure_value,
     sizeof(bool),
     "Skip server key verification (MITM-vulnerable, requires explicit opt-in).",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_DISCOVERY_INSECURE",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"discovery-service-key",
     '\0',
     OPTION_TYPE_STRING,
     offsetof(options_t, discovery_service_key),
     "",
     0,
     "Discovery server public key for verification. Supports: raw base64 public key (AAAAC3Nz...), "
     "SSH/GPG key files, gpg:FINGERPRINT, github:USER[.gpg], gitlab:USER[.gpg], "
     "or HTTP(S) URLs like https://github.com/zfogg.[keys|gpg].",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_DISCOVERY_SERVER_KEY",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_SERVER | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"require-server-identity",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, require_server_identity),
     NULL,
     sizeof(bool),
     "Require servers to provide signed Ed25519 identity.",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_REQUIRE_SERVER_IDENTITY",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},
    {"require-client-identity",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, require_client_identity),
     NULL,
     sizeof(bool),
     "Require clients to provide signed Ed25519 identity.",
     "SECURITY",
     NULL,
     false,
     "ASCII_CHAT_REQUIRE_CLIENT_IDENTITY",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_DISCOVERY_SVC,
     {0},
     NULL},

    REGISTRY_TERMINATOR()};
