/**
 * @file terminal.c
 * @brief Terminal display options
 * @ingroup options
 *
 * Options for controlling terminal dimensions, color modes, UTF-8 support,
 * and terminal capabilities.
 *
 * @author Zachary Fogg <me@zfo.gg>
 * @date January 2026
 */

#include <ascii-chat/options/registry/common.h>
#include <ascii-chat/options/registry/metadata.h>

#include <ascii-chat/options/parsers.h>

// ============================================================================
// TERMINAL CATEGORY - Terminal display options
// ============================================================================
const registry_entry_t g_terminal_entries[] = {
    // TERMINAL GROUP (client, mirror, discovery)
    {"width",
     'x',
     OPTION_TYPE_INT,
     offsetof(options_t, width),
     &default_width_value,
     sizeof(int),
     "Terminal width in characters. Can be controlled using $COLUMNS. By default your terminal width is detected at "
     "runtime and this value is updated automatically.",
     "TERMINAL",
     NULL,
     false,
     "ASCII_CHAT_WIDTH",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {20, 512, 0}, .examples = g_width_examples, .input_type = OPTION_INPUT_NUMERIC},
     NULL},
    {"height",
     'y',
     OPTION_TYPE_INT,
     offsetof(options_t, height),
     &default_height_value,
     sizeof(int),
     "Terminal height in characters. Can be controlled using $ROWS. By default your terminal height is detected at "
     "runtime and this value is updated automatically.",
     "TERMINAL",
     NULL,
     false,
     "ASCII_CHAT_HEIGHT",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.numeric_range = {10, 256, 0}, .examples = g_height_examples, .input_type = OPTION_INPUT_NUMERIC},
     NULL},
    {"color-mode",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, color_mode),
     &default_color_mode_value,
     sizeof(terminal_color_mode_t),
     "Terminal color level (auto, none, 16, 256, truecolor). This controls what ANSI escape codes ascii-chat will use "
     "for console logging and display output if color is enabled. Press 'c' during rendering to cycle. See also "
     "--color.",
     "TERMINAL",
     NULL,
     false,
     "ASCII_CHAT_COLOR_MODE",
     NULL,
     parse_color_mode,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_color_mode_values,
      .enum_count = 5,
      .enum_descriptions = g_color_mode_descs,
      .enum_integer_values = g_color_mode_integers,
      .input_type = OPTION_INPUT_ENUM},
     NULL},
    {"show-capabilities",
     '\0',
     OPTION_TYPE_ACTION,
     0,
     NULL,
     0,
     "Show detected terminal capabilities and exit (useful for debugging and scripting).",
     "TERMINAL",
     NULL,
     false,
     NULL,
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_BINARY,
     {0},
     NULL},
    {"utf8",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, force_utf8),
     &default_force_utf8_value,
     sizeof(int),
     "UTF-8 support setting: 'auto' (default, auto-detect), 'true' (force UTF-8 on), or 'false' (force UTF-8 off).",
     "TERMINAL",
     NULL,
     false,
     "ASCII_CHAT_UTF8",
     NULL,
     parse_utf8_setting,
     false,
     true,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {.enum_values = g_utf8_setting_values,
      .enum_count = 3,
      .enum_descriptions = g_utf8_setting_descs,
      .enum_integer_values = g_utf8_setting_integers,
      .input_type = OPTION_INPUT_ENUM},
     NULL},
    {"strip-ansi",
     '\0',
     OPTION_TYPE_BOOL,
     offsetof(options_t, strip_ansi),
     &default_strip_ansi_value,
     sizeof(bool),
     "Strip ANSI escape sequences from output before printing. Useful for scripting and debugging.",
     "TERMINAL",
     NULL,
     false,
     "ASCII_CHAT_STRIP_ANSI",
     NULL,
     NULL,
     false,
     false,
     OPTION_MODE_CLIENT | OPTION_MODE_MIRROR | OPTION_MODE_DISCOVERY,
     {0},
     NULL},
    {"color",
     '\0',
     OPTION_TYPE_CALLBACK,
     offsetof(options_t, color),
     &default_color_value,
     sizeof(int),
     "Color output setting: 'auto' (default, smart detection), 'true' (force colors on), or 'false' (force colors "
     "off).",
     "TERMINAL",
     NULL,
     false,
     "ASCII_CHAT_COLOR",
     NULL,
     parse_color_setting,
     false,
     true,
     OPTION_MODE_BINARY,
     {.enum_values = g_color_setting_values,
      .enum_count = 3,
      .enum_descriptions = g_color_setting_descs,
      .enum_integer_values = g_color_setting_integers,
      .input_type = OPTION_INPUT_ENUM},
     NULL},

    REGISTRY_TERMINATOR()};
