/**
 * @file discovery/adjectives.h
 * @ingroup discovery
 * @brief TODO: Add Doxygen documentation for adjectives header
 *
 * Auto-generated header exporting adjective wordlist for session naming.
 * Needs documentation for: Function/variable declarations, usage examples
 *
 * Note: This file is auto-generated. Modify generation script, not this file directly.
 */

// Auto-generated by generate_wordlists.py
// Total words: 2500

#ifndef ADJECTIVES_H
#define ADJECTIVES_H

#include <stddef.h>

// Array of 2500 adjectives
extern const char *adjectives[];

// Number of words in adjectives array
extern const size_t adjectives_count;

#endif // ADJECTIVES_H
