/**
 * @file discovery/adjectives.h
 * @ingroup discovery
 * @brief Wordlist for generating friendly session identifiers in ACDS
 *
 * Exports an array of 2500 English adjectives used as the first component of memorable
 * session identifiers in the format "adjective-noun-noun" (e.g., "blue-mountain-tiger").
 *
 * This file is auto-generated by generate_wordlists.py and should not be modified directly.
 *
 * @note The adjectives are selected to be easily pronounceable, memorable, and suitable
 * for generating session strings that users can communicate verbally or write down by hand.
 */

// Auto-generated by generate_wordlists.py
// Total words: 2500

#ifndef ADJECTIVES_H
#define ADJECTIVES_H

#include <stddef.h>

/**
 * @brief Array of English adjectives for ACDS session naming
 *
 * A curated list of 2500 adjectives used to generate the first part of memorable
 * session identifiers. Combined with two nouns to create unique, pronounceable strings.
 *
 * Example values: "blue", "bright", "calm", "dark", "eager", "fresh", "gentle", ...
 *
 * @see adjectives_count
 * @see lib/discovery/nouns.h for the noun wordlist
 */
extern const char *adjectives[];

/**
 * @brief Count of adjectives in the adjectives array
 *
 * Always equals 2500. Used for bounds checking and random selection.
 *
 * @see adjectives
 */
extern const size_t adjectives_count;

#endif // ADJECTIVES_H
