// Auto-generated by generate_wordlists.py
// Total words: 5000

#ifndef NOUNS_H
#define NOUNS_H

#include <stddef.h>

// Array of 5000 nouns
extern const char *nouns[];

// Number of words in nouns array
extern const size_t nouns_count;

#endif // NOUNS_H
