// Auto-generated version header - DO NOT EDIT
// Generated by CMake from version.h.in

#pragma once

#define ASCII_CHAT_VERSION_MAJOR 0
#define ASCII_CHAT_VERSION_MINOR 7
#define ASCII_CHAT_VERSION_PATCH 7
#define ASCII_CHAT_VERSION_STRING "0.7.7"
#define ASCII_CHAT_GIT_VERSION "dev-109+g488b348f-dirty"
#define ASCII_CHAT_GIT_COMMIT_HASH "488b348fe220fa20b43a2ebc240de7a80cc79a9c"
#define ASCII_CHAT_GIT_IS_DIRTY true
#define ASCII_CHAT_BUILD_TYPE "Debug"
#define ASCII_CHAT_OS "Darwin"
#define ASCII_CHAT_BUILD_DATE "2026-02-02"
#define ASCII_CHAT_REPO_HASH ""

// Full version string like "v0.2.0-42+gf811525" (nvim-style)
// On clean release tags, this will be just "v0.3.0" without trailing dash
#define ASCII_CHAT_VERSION_FULL "v" ASCII_CHAT_VERSION_STRING "-" ASCII_CHAT_GIT_VERSION

// Description tagline
#define ASCII_CHAT_DESCRIPTION_EMOJI_L "💻📸"
#define ASCII_CHAT_DESCRIPTION_EMOJI_R "🔡💬"
#define ASCII_CHAT_DESCRIPTION_TEXT "Video chat in your terminal"
#define ASCII_CHAT_DESCRIPTION                                                                                         \
  ASCII_CHAT_DESCRIPTION_EMOJI_L " " ASCII_CHAT_DESCRIPTION_TEXT " " ASCII_CHAT_DESCRIPTION_EMOJI_R

// Full build info string used everywhere: "ascii-chat v0.2.0-... built on OS (yyyy-mm-dd, BuildType)"
#define ASCII_CHAT_BUILD_INFO_STRING                                                                                   \
  "ascii-chat " ASCII_CHAT_VERSION_FULL " built on " ASCII_CHAT_OS " (" ASCII_CHAT_BUILD_DATE                          \
  ", " ASCII_CHAT_BUILD_TYPE ")"

#define ASCII_CHAT_DOT_COMMENT_STRING                                                                                  \
  ASCII_CHAT_BUILD_INFO_STRING "\n" ASCII_CHAT_DESCRIPTION "\n"                                                        \
                               "https://github.com/zfogg/ascii-chat"

#define ASCII_CHAT_DOT_ASCII_CHAT_STRING                                                                               \
  ASCII_CHAT_DOT_COMMENT_STRING "\n"                                                                                   \
                                "coded with 🖤 by Zachary Fogg <me@zfo.gg>"

// Runtime version accessors
const char *ascii_chat_get_version(void);
const char *ascii_chat_get_comment(void);
const char *ascii_chat_get_build_info(void);
