# =============================================================================
# EmbedTextFile.cmake - Text-to-C-String Embedding Utility
# =============================================================================
#
# Converts a text file into a C source file containing an embedded string.
#
# Usage:
#   cmake -DINPUT_FILE=<path> -DOUTPUT_FILE=<path> -DVARIABLE_NAME=<name> \
#          -P cmake/utils/EmbedTextFile.cmake
#
# Parameters:
#   INPUT_FILE       Path to input text file to embed
#   OUTPUT_FILE      Path to output C source file to generate
#   VARIABLE_NAME    C variable name for the embedded string
#
# Generates:
#   - An extern declaration in the output file for the embedded data
#   - A const char array containing the file contents (escaped for C)
#   - A const size_t variable containing the string length
#

if(NOT DEFINED INPUT_FILE OR INPUT_FILE STREQUAL "")
    message(FATAL_ERROR "EmbedTextFile: INPUT_FILE not defined")
endif()

if(NOT DEFINED OUTPUT_FILE OR OUTPUT_FILE STREQUAL "")
    message(FATAL_ERROR "EmbedTextFile: OUTPUT_FILE not defined")
endif()

if(NOT DEFINED VARIABLE_NAME OR VARIABLE_NAME STREQUAL "")
    message(FATAL_ERROR "EmbedTextFile: VARIABLE_NAME not defined")
endif()

# Verify input file exists
if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "EmbedTextFile: Input file not found: ${INPUT_FILE}")
endif()

# Read the input file
file(READ "${INPUT_FILE}" CONTENT)

# Escape special characters for C string literal
# Order matters: backslash first, then quotes, then newlines
string(REPLACE "\\" "\\\\" CONTENT "${CONTENT}")   # Backslash → \\
string(REPLACE "\"" "\\\"" CONTENT "${CONTENT}")   # Quote → \"
string(REPLACE "\n" "\\n\"\n    \"" CONTENT "${CONTENT}")  # Newline → \n" + newline + "

# Generate C source file with embedded string
file(WRITE "${OUTPUT_FILE}" "/* =============================================================================
 * Auto-generated file: DO NOT EDIT
 * Generated from: ${INPUT_FILE}
 * =============================================================================
 */

#include <stddef.h>

/**
 * @brief Embedded content from: ${INPUT_FILE}
 * @note This is auto-generated by EmbedTextFile.cmake during build time
 */
const char ${VARIABLE_NAME}[] =
    \"${CONTENT}\";

/**
 * @brief Length of embedded content (excluding null terminator)
 */
const size_t ${VARIABLE_NAME}_len = sizeof(${VARIABLE_NAME}) - 1;
")

message(STATUS "Embedded ${INPUT_FILE} (${VARIABLE_NAME}) → ${OUTPUT_FILE}")
