/**
 * @file tooling/defer/defer.h
 * @brief Defer macro definition for source-to-source transformation
 *
 * This header provides the defer() macro syntax that is recognized by the
 * ascii-instr-defer tool. The tool transforms defer() calls into inlined
 * cleanup code at all function exit points.
 *
 * Example usage:
 *   FILE *f = fopen("file.txt", "r");
 *   defer(fclose(f));  // Will be called when function exits
 *
 * The defer transformer converts this to:
 *   FILE *f = fopen("file.txt", "r");
 *   // ... at every return point and function end:
 *   { fclose(f); }
 *
 * Note: This header only defines the macro for parsing. The actual cleanup
 * code is generated by the transformer - no runtime library is needed.
 */

#pragma once

/**
 * @brief Defer a cleanup action until function scope exit
 * @param action The cleanup expression to execute (e.g., fclose(f), free(ptr))
 *
 * The defer() macro marks cleanup code that should run when the function exits.
 * The ascii-instr-defer tool transforms these into inlined cleanup code.
 *
 * Multiple defers execute in LIFO (last-in-first-out) order.
 */
#define defer(action)                                                                                                  \
  do { /* transformed by ascii-instr-defer */                                                                          \
  } while (0)
