# =============================================================================
# Installation Configuration Module
# =============================================================================
# This module configures installation rules for ascii-chat
#
# Prerequisites:
#   - Target 'ascii-chat' must exist
#   - Must run after project() and target creation
#
# Outputs:
#   - Install rules for binary, documentation, and optional files
# =============================================================================

# Install binary
install(TARGETS ascii-chat
    RUNTIME DESTINATION bin
    COMPONENT Runtime
)

# Install documentation (if files exist)
if(EXISTS "${CMAKE_SOURCE_DIR}/README.md")
    install(FILES README.md
        DESTINATION share/doc/ascii-chat
        COMPONENT Documentation
        OPTIONAL
    )
endif()

# Install license (if exists)
if(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE")
    install(FILES LICENSE
        DESTINATION share/doc/ascii-chat
        COMPONENT Documentation
        OPTIONAL
    )
elseif(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE.txt")
    install(FILES LICENSE.txt
        DESTINATION share/doc/ascii-chat
        COMPONENT Documentation
        OPTIONAL
    )
endif()

# Install CHANGELOG if it exists
if(EXISTS "${CMAKE_SOURCE_DIR}/CHANGELOG.md")
    install(FILES CHANGELOG.md
        DESTINATION share/doc/ascii-chat
        COMPONENT Documentation
        OPTIONAL
    )
endif()

# Install manpages generated by Doxygen (if they exist)
# Manpages are generated in ${CMAKE_BINARY_DIR}/docs/man/man3/ with ascii-chat- prefix
# The install will only work if the docs target has been built first
# Using OPTIONAL ensures install doesn't fail if manpages don't exist yet
install(
    DIRECTORY "${CMAKE_BINARY_DIR}/docs/man/man3"
    DESTINATION share/man
    COMPONENT Manpages
    OPTIONAL
    FILES_MATCHING
    PATTERN "ascii-chat-*.3"  # Only install prefixed manpages (section 3)
    PATTERN "*.3.gz" EXCLUDE  # Exclude compressed manpages if any
    PATTERN "*.3.bz2" EXCLUDE
    PATTERN "*.3.xz" EXCLUDE
)

# Platform-specific installation paths
if(UNIX AND NOT APPLE)
    # Linux: Follow FHS (Filesystem Hierarchy Standard)
    # Binary goes to /usr/local/bin (or user-specified prefix)
    # Documentation goes to /usr/local/share/doc/ascii-chat
    set(INSTALL_DOC_DIR "share/doc/ascii-chat" CACHE PATH "Documentation install directory")
elseif(APPLE)
    # macOS: Follow macOS conventions
    # Binary goes to /usr/local/bin
    # Documentation goes to /usr/local/share/doc/ascii-chat
    set(INSTALL_DOC_DIR "share/doc/ascii-chat" CACHE PATH "Documentation install directory")
elseif(WIN32)
    # Windows: Follow Windows conventions
    # Binary goes to Program Files/ascii-chat/bin
    # Documentation goes to Program Files/ascii-chat/doc
    set(INSTALL_DOC_DIR "doc" CACHE PATH "Documentation install directory")
endif()

# Option to install example config files (if any exist in the future)
# if(EXISTS "${CMAKE_SOURCE_DIR}/examples")
#     install(DIRECTORY examples/
#         DESTINATION share/doc/ascii-chat/examples
#         COMPONENT Documentation
#         FILES_MATCHING
#         PATTERN "*.conf"
#         PATTERN "*.toml"
#     )
# endif()

# =============================================================================
# CPack Configuration (Optional Package Generation)
# =============================================================================
# Configure CPack for generating platform-specific packages
# Generates: DEB, RPM (Linux), DMG (macOS), ZIP, NSIS/EXE (Windows)
#
# Usage:
#   cmake --build build --target package
#   cmake --build build --target package_source
#
# Disable with: -DUSE_CPACK=OFF
# =============================================================================

option(USE_CPACK "Enable CPack package generation" ON)

if(USE_CPACK)
    # Check if CPack is available
    if(CMAKE_VERSION VERSION_LESS "3.16")
        message(WARNING "CPack requires CMake 3.16+ (current: ${CMAKE_VERSION}). Disabling CPack.")
        set(USE_CPACK OFF)
    else()
        # Set CPack variables BEFORE including CPack to prevent defaults
        # This ensures CPack uses the correct version and install directory
        set(CPACK_PACKAGE_INSTALL_DIRECTORY "ascii-chat" CACHE STRING "Installation directory (without version)" FORCE)
        # Set version from PROJECT_VERSION (should be overridden by Version.cmake if git is available)
        set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR} CACHE STRING "Package version major" FORCE)
        set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR} CACHE STRING "Package version minor" FORCE)
        set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH} CACHE STRING "Package version patch" FORCE)
        set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}" CACHE STRING "Package version" FORCE)
        include(CPack)
    endif()
endif()

if(USE_CPACK)

    # =========================================================================
    # Basic CPack Configuration
    # =========================================================================
    set(CPACK_PACKAGE_NAME "ascii-chat")
    set(CPACK_PACKAGE_VENDOR "zfogg")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Real-time terminal-based video chat with ASCII art conversion")
    set(CPACK_PACKAGE_DESCRIPTION "ascii-chat is a terminal-based video chat application that converts webcam video to ASCII art in real-time. It supports multiple clients connecting to a single server, with video mixing and audio streaming capabilities.")

    # Version is already set before include(CPack) above
    # Re-set with CACHE FORCE to ensure it's not overridden
    set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR} CACHE STRING "Package version major" FORCE)
    set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR} CACHE STRING "Package version minor" FORCE)
    set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH} CACHE STRING "Package version patch" FORCE)
    set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}" CACHE STRING "Package version" FORCE)

    # Log version being used for packages
    message(STATUS "CPack: Using version ${CPACK_PACKAGE_VERSION} for packages (from PROJECT_VERSION=${PROJECT_VERSION})")

    # Package metadata
    set(CPACK_PACKAGE_CONTACT "https://github.com/zfogg/ascii-chat")
    if(DEFINED PROJECT_HOMEPAGE_URL)
        set(CPACK_PACKAGE_HOMEPAGE_URL "${PROJECT_HOMEPAGE_URL}")
    endif()

    # Package file name format
    set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")

    # Output directory
    set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/packages")

    # Installation directory (without version for NSIS)
    # Set again after include(CPack) to ensure it overrides CPack's default
    # CPack's default is "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}" which we don't want
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}" CACHE STRING "Installation directory (without version)" FORCE)

    # =========================================================================
    # Platform-Specific Package Generators
    # =========================================================================

    if(UNIX AND NOT APPLE)
        # Linux: TGZ (always available), DEB, RPM (if tools found)
        set(CPACK_GENERATOR "TGZ")

        # Check for package tools and enable generators if available
        find_program(DPKG_BUILDPACKAGE_EXECUTABLE dpkg-buildpackage)
        find_program(RPMBUILD_EXECUTABLE rpmbuild)

        if(DPKG_BUILDPACKAGE_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "DEB")
            message(STATUS "CPack: DEB generator enabled (dpkg-buildpackage found)")
        else()
            message(STATUS "CPack: DEB generator disabled (dpkg-buildpackage not found)")
        endif()

        if(RPMBUILD_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "RPM")
            message(STATUS "CPack: RPM generator enabled (rpmbuild found)")
        else()
            message(STATUS "CPack: RPM generator disabled (rpmbuild not found)")
        endif()

        # DEB package configuration
        if("DEB" IN_LIST CPACK_GENERATOR)
            set(CPACK_DEBIAN_PACKAGE_NAME "ascii-chat")
            set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
            set(CPACK_DEBIAN_PACKAGE_SECTION "net")
            set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
            set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
                set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
            endif()
            set(CPACK_DEBIAN_PACKAGE_DEPENDS "")
            set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
            # Maintainer info (optional - can be set via environment)
            if(DEFINED ENV{DEBEMAIL})
                set(CPACK_DEBIAN_PACKAGE_MAINTAINER "$ENV{DEBEMAIL}")
            else()
                set(CPACK_DEBIAN_PACKAGE_MAINTAINER "ascii-chat <${CPACK_PACKAGE_CONTACT}>")
            endif()
        endif()

        # RPM package configuration
        if("RPM" IN_LIST CPACK_GENERATOR)
            set(CPACK_RPM_PACKAGE_NAME "ascii-chat")
            set(CPACK_RPM_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
            set(CPACK_RPM_PACKAGE_GROUP "Applications/Networking")
            set(CPACK_RPM_PACKAGE_LICENSE "MIT")
            set(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
                set(CPACK_RPM_PACKAGE_ARCHITECTURE "aarch64")
            endif()
            set(CPACK_RPM_PACKAGE_REQUIRES "")
            set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
            # Vendor info (optional)
            if(DEFINED ENV{RPM_VENDOR})
                set(CPACK_RPM_PACKAGE_VENDOR "$ENV{RPM_VENDOR}")
            else()
                set(CPACK_RPM_PACKAGE_VENDOR "${CPACK_PACKAGE_VENDOR}")
            endif()
        endif()

        message(STATUS "CPack: Enabled generators for Linux: ${CPACK_GENERATOR}")

    elseif(APPLE)
        # macOS: TGZ (always available), DragNDrop/DMG (if hdiutil available)
        set(CPACK_GENERATOR "TGZ")

        # Check for hdiutil (macOS DMG creation tool - usually always available on macOS)
        find_program(HDIUTIL_EXECUTABLE hdiutil)
        if(HDIUTIL_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "DragNDrop")
            message(STATUS "CPack: DMG generator enabled (hdiutil found)")
        else()
            message(STATUS "CPack: DMG generator disabled (hdiutil not found)")
        endif()

        # DMG package configuration
        if("DragNDrop" IN_LIST CPACK_GENERATOR)
            set(CPACK_DMG_FORMAT "UDZO")  # Compressed UDIF (read-only)
            set(CPACK_DMG_VOLUME_NAME "${CPACK_PACKAGE_NAME}")
            set(CPACK_DMG_BACKGROUND_IMAGE "")  # Optional: path to background image
            set(CPACK_DMG_DS_STORE_SETUP_SCRIPT "")  # Optional: custom setup script
            set(CPACK_DMG_SLA_DIR "")  # Optional: Software License Agreement directory
        endif()

        message(STATUS "CPack: Enabled generators for macOS: ${CPACK_GENERATOR}")

    elseif(WIN32)
        # Windows: ZIP (always available), NSIS/EXE (if makensis found)
        set(CPACK_GENERATOR "ZIP")

        # Check for NSIS (Nullsoft Scriptable Install System)
        find_program(NSIS_EXECUTABLE makensis)
        if(NOT NSIS_EXECUTABLE)
            # Try alternative NSIS locations (common Windows install paths)
            # Handle ProgramFiles(x86) separately due to CMake variable parsing
            if(DEFINED ENV{ProgramFiles})
                set(PROGRAM_FILES_PATH "$ENV{ProgramFiles}")
            else()
                set(PROGRAM_FILES_PATH "C:/Program Files")
            endif()

            if(DEFINED ENV{ProgramFiles\(x86\)})
                set(PROGRAM_FILES_X86_PATH "$ENV{ProgramFiles\(x86\)}")
            else()
                set(PROGRAM_FILES_X86_PATH "C:/Program Files (x86)")
            endif()

            find_program(NSIS_EXECUTABLE
                NAMES makensis
                PATHS
                    "${PROGRAM_FILES_PATH}/NSIS"
                    "${PROGRAM_FILES_X86_PATH}/NSIS"
                    "C:/Program Files/NSIS"
                    "C:/Program Files (x86)/NSIS"
                PATH_SUFFIXES bin
                NO_DEFAULT_PATH
            )
        endif()

        if(NSIS_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "NSIS")
            message(STATUS "CPack: NSIS generator enabled (makensis found at ${NSIS_EXECUTABLE})")
        else()
            message(STATUS "CPack: NSIS generator disabled (makensis not found - install NSIS to create EXE installers)")
        endif()

        # NSIS installer configuration
        if("NSIS" IN_LIST CPACK_GENERATOR)
            set(CPACK_NSIS_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
            # Display name without version (just "ascii-chat")
            set(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_NAME}")
            # CPACK_PACKAGE_INSTALL_DIRECTORY is set above and controls the install directory
            # This ensures NSIS installs to "ascii-chat" instead of "ascii-chat 0.3.2"
            # Note: CPACK_PACKAGE_INSTALL_DIRECTORY is already set to "${CPACK_PACKAGE_NAME}" above
            set(CPACK_NSIS_HELP_LINK "${CPACK_PACKAGE_HOMEPAGE_URL}")
            set(CPACK_NSIS_URL_INFO_ABOUT "${CPACK_PACKAGE_HOMEPAGE_URL}")
            set(CPACK_NSIS_CONTACT "${CPACK_PACKAGE_CONTACT}")

            # Add installation directory to PATH
            # This ensures 'ascii-chat' can be run from any directory
            # The installer will add to system PATH if running with admin privileges,
            # or user PATH if running without admin (per-user installation)
            set(CPACK_NSIS_MODIFY_PATH ON)

            # Enable uninstall before install (clean upgrade)
            set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)

            # Optional: Custom installer icon
            # set(CPACK_NSIS_INSTALLED_ICON_NAME "${CMAKE_SOURCE_DIR}/resources/icon.ico")
        endif()

        message(STATUS "CPack: Enabled generators for Windows: ${CPACK_GENERATOR}")

    else()
        # Unknown platform: fallback to TGZ
        set(CPACK_GENERATOR "TGZ")
        message(STATUS "CPack: Using fallback generator TGZ for unknown platform")
    endif()

    # =========================================================================
    # Source Package Configuration (optional)
    # =========================================================================
    set(CPACK_SOURCE_GENERATOR "TGZ")
    if(UNIX AND NOT APPLE)
        find_program(ZIP_EXECUTABLE zip)
        if(ZIP_EXECUTABLE)
            list(APPEND CPACK_SOURCE_GENERATOR "ZIP")
        endif()
    endif()

    # Source package ignore patterns
    set(CPACK_SOURCE_IGNORE_FILES
        "/build/"
        "/build_release/"
        "/\\.git/"
        "/deps/"
        "/\\.deps-cache/"
        "/\\.deps-cache-musl/"
        "/\\.vscode/"
        "/\\.idea/"
        "/CMakeFiles/"
        "/CMakeCache\\.txt$"
        "/cmake_install\\.cmake$"
        "/\\.ninja_log$"
        "/\\.ninja_deps$"
        "/compile_commands\\.json$"
    )

    # =========================================================================
    # Component Configuration
    # =========================================================================
    # Configure components for installation (Runtime, Documentation)
    set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Binary")
    set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "ascii-chat executable")
    set(CPACK_COMPONENT_RUNTIME_REQUIRED ON)

    set(CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME "Documentation")
    set(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "README, LICENSE, and CHANGELOG")
    set(CPACK_COMPONENT_DOCUMENTATION_DEPENDS Runtime)

    # Manpages component (optional - depends on docs being built)
    set(CPACK_COMPONENT_MANPAGES_DISPLAY_NAME "Man Pages")
    set(CPACK_COMPONENT_MANPAGES_DESCRIPTION "Unix manual pages (man pages) for API documentation")
    set(CPACK_COMPONENT_MANPAGES_DEPENDS Runtime)

    # Group components
    set(CPACK_COMPONENT_GROUP_APPLICATIONS_DISPLAY_NAME "Application")
    set(CPACK_COMPONENT_GROUP_APPLICATIONS_DESCRIPTION "ASCII video chat application")
    set(CPACK_COMPONENT_RUNTIME_GROUP "Applications")
    set(CPACK_COMPONENT_DOCUMENTATION_GROUP "Applications")
    set(CPACK_COMPONENT_MANPAGES_GROUP "Applications")

    message(STATUS "CPack: Package generation enabled")
    message(STATUS "CPack: Package will be created in: ${CPACK_PACKAGE_DIRECTORY}")
    message(STATUS "CPack: Generators: ${CPACK_GENERATOR}")
else()
    message(STATUS "CPack: Package generation disabled (set USE_CPACK=ON to enable)")
endif()

