# =============================================================================
# Installation Configuration Module
# =============================================================================
# This module configures installation rules for ascii-chat
#
# Prerequisites:
#   - Target 'ascii-chat' must exist
#   - Must run after project() and target creation
#
# Outputs:
#   - Install rules for binary, documentation, and optional files
# =============================================================================

# Install binary
install(TARGETS ascii-chat
    RUNTIME DESTINATION bin
    COMPONENT Runtime
)

# Install DLL dependencies on Windows (for non-static builds)
# These DLLs are copied to build/bin by vcpkg's applocal.ps1 script during linking
# We need to explicitly install them so CPack includes them in the installer
if(WIN32 AND NOT CMAKE_BUILD_TYPE MATCHES "Release")
    # Only install DLLs for non-static builds (Debug, Dev builds use dynamic libraries)
    # Release builds use static libraries so no DLLs needed

    # Install DLLs from build/bin directory
    # vcpkg's applocal.ps1 script copies DLLs to build/bin during linking
    # We install them here so CPack includes them in the installer
    # Use trailing slash to install contents of bin directory, not bin directory itself
    # Note: FILES_MATCHING handles the case where no DLLs exist (no files match)
    install(DIRECTORY "${CMAKE_BINARY_DIR}/bin/"
        DESTINATION bin
        COMPONENT Runtime
        FILES_MATCHING
        PATTERN "*.dll"
        PATTERN "*.exe" EXCLUDE  # Exclude exe (already installed by install(TARGETS))
    )
    message(STATUS "Configured DLL installation for CPack (non-static builds only)")
endif()

# Platform-specific installation paths (must be set before using INSTALL_DOC_DIR)
# Windows uses doc/ instead of share/doc/ to avoid creating share/ directory
# Unix/macOS follow FHS and use share/doc/ascii-chat
if(UNIX AND NOT APPLE)
    # Linux: Follow FHS (Filesystem Hierarchy Standard)
    # Binary goes to /usr/local/bin (or user-specified prefix)
    # Documentation goes to /usr/local/share/doc/ascii-chat
    set(INSTALL_DOC_DIR "share/doc/ascii-chat" CACHE PATH "Documentation install directory")
elseif(APPLE)
    # macOS: Follow macOS conventions
    # Binary goes to /usr/local/bin
    # Documentation goes to /usr/local/share/doc/ascii-chat
    set(INSTALL_DOC_DIR "share/doc/ascii-chat" CACHE PATH "Documentation install directory")
elseif(WIN32)
    # Windows: Follow Windows conventions
    # Binary goes to Program Files/ascii-chat/bin
    # Documentation goes to Program Files/ascii-chat/doc (not share/doc/ascii-chat)
    set(INSTALL_DOC_DIR "doc" CACHE PATH "Documentation install directory")
endif()

# Install documentation (if files exist)
# Use INSTALL_DOC_DIR which is platform-specific (doc on Windows, share/doc/ascii-chat on Unix)
if(EXISTS "${CMAKE_SOURCE_DIR}/README.md")
    install(FILES README.md
        DESTINATION ${INSTALL_DOC_DIR}
        COMPONENT Documentation
        OPTIONAL
    )
endif()

# Install license (if exists)
if(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE")
    install(FILES LICENSE
        DESTINATION ${INSTALL_DOC_DIR}
        COMPONENT Documentation
        OPTIONAL
    )
elseif(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE.txt")
    install(FILES LICENSE.txt
        DESTINATION ${INSTALL_DOC_DIR}
        COMPONENT Documentation
        OPTIONAL
    )
endif()

# Install CHANGELOG if it exists
if(EXISTS "${CMAKE_SOURCE_DIR}/CHANGELOG.md")
    install(FILES CHANGELOG.md
        DESTINATION ${INSTALL_DOC_DIR}
        COMPONENT Documentation
        OPTIONAL
    )
endif()

# Install Doxygen HTML documentation (if generated)
# Doxygen HTML docs are generated in ${CMAKE_BINARY_DIR}/docs/html/
# Similar to DLLs, we need to explicitly install from build directory
# Platform-specific: Windows uses doc/html, Unix/macOS uses share/doc/ascii-chat/html
install(DIRECTORY "${CMAKE_BINARY_DIR}/docs/html/"
    DESTINATION ${INSTALL_DOC_DIR}/html
    COMPONENT Documentation
    FILES_MATCHING
    PATTERN "*.html"
    PATTERN "*.css"
    PATTERN "*.js"
    PATTERN "*.png"
    PATTERN "*.jpg"
    PATTERN "*.gif"
    PATTERN "*.svg"
)

# Install manpages generated by Doxygen (if they exist)
# Manpages are generated in ${CMAKE_BINARY_DIR}/docs/man/man3/ with ascii-chat- prefix
# The install will only work if the docs target has been built first
# Note: OPTIONAL cannot be used with FILES_MATCHING, but FILES_MATCHING handles no matches gracefully
# Unix/macOS install to man/man3 (not share/man/man3) to avoid creating share/ directory
# Windows installs to doc/man/man3 (no share/ directory) - check WIN32 first to ensure only one rule executes
if(WIN32)
    # Windows: Install manpages to doc/man/man3 (no standard location on Windows)
    # This is the ONLY install rule for manpages on Windows - no share/ directory
    install(DIRECTORY "${CMAKE_BINARY_DIR}/docs/man/man3/"
        DESTINATION ${INSTALL_DOC_DIR}/man/man3
        COMPONENT Manpages
        FILES_MATCHING
        PATTERN "ascii-chat-*.3"  # Only install prefixed manpages (section 3)
        PATTERN "*.3.gz" EXCLUDE  # Exclude compressed manpages if any
        PATTERN "*.3.bz2" EXCLUDE
        PATTERN "*.3.xz" EXCLUDE
    )
elseif(UNIX AND NOT APPLE)
    # Unix/Linux: Install to man/man3 (not share/man/man3 to avoid share/ directory)
    install(DIRECTORY "${CMAKE_BINARY_DIR}/docs/man/man3/"
        DESTINATION man/man3
        COMPONENT Manpages
        FILES_MATCHING
        PATTERN "ascii-chat-*.3"  # Only install prefixed manpages (section 3)
        PATTERN "*.3.gz" EXCLUDE  # Exclude compressed manpages if any
        PATTERN "*.3.bz2" EXCLUDE
        PATTERN "*.3.xz" EXCLUDE
    )
elseif(APPLE)
    # macOS: Install to man/man3 (not share/man/man3 to avoid share/ directory)
    install(DIRECTORY "${CMAKE_BINARY_DIR}/docs/man/man3/"
        DESTINATION man/man3
        COMPONENT Manpages
        FILES_MATCHING
        PATTERN "ascii-chat-*.3"  # Only install prefixed manpages (section 3)
        PATTERN "*.3.gz" EXCLUDE  # Exclude compressed manpages if any
        PATTERN "*.3.bz2" EXCLUDE
        PATTERN "*.3.xz" EXCLUDE
    )
endif()

# Platform-specific installation paths are set earlier in the file (before using INSTALL_DOC_DIR)

# Option to install example config files (if any exist in the future)
# if(EXISTS "${CMAKE_SOURCE_DIR}/examples")
#     install(DIRECTORY examples/
#         DESTINATION share/doc/ascii-chat/examples
#         COMPONENT Documentation
#         FILES_MATCHING
#         PATTERN "*.conf"
#         PATTERN "*.toml"
#     )
# endif()

# =============================================================================
# CPack Configuration (Optional Package Generation)
# =============================================================================
# Configure CPack for generating platform-specific packages
# Generates: DEB, RPM (Linux), DMG (macOS), ZIP, NSIS/EXE (Windows)
#
# Usage:
#   cmake --build build --target package
#   cmake --build build --target package_source
#
# Disable with: -DUSE_CPACK=OFF
# =============================================================================

option(USE_CPACK "Enable CPack package generation" ON)

if(USE_CPACK)
    # Check if CPack is available
    if(CMAKE_VERSION VERSION_LESS "3.16")
        message(WARNING "CPack requires CMake 3.16+ (current: ${CMAKE_VERSION}). Disabling CPack.")
        set(USE_CPACK OFF)
    else()
        # Set CPack variables BEFORE including CPack to prevent defaults
        # This ensures CPack uses the correct version and install directory
        set(CPACK_PACKAGE_INSTALL_DIRECTORY "ascii-chat" CACHE STRING "Installation directory (without version)" FORCE)
        # Set version from PROJECT_VERSION (should be overridden by Version.cmake if git is available)
        set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR} CACHE STRING "Package version major" FORCE)
        set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR} CACHE STRING "Package version minor" FORCE)
        set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH} CACHE STRING "Package version patch" FORCE)
        set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}" CACHE STRING "Package version" FORCE)
        # Set license file BEFORE include(CPack) to prevent CPack from using default
        if(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE.txt")
            set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt" CACHE FILEPATH "License file for installers" FORCE)
        elseif(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE")
            set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE" CACHE FILEPATH "License file for installers" FORCE)
        endif()
        # On Windows, explicitly prevent CPack from creating share/ directory
        # CPack should only install what we explicitly tell it to via install() commands
        # All our install() commands use doc/ (not share/doc/) on Windows, so CPack shouldn't create share/
        # Explicitly set CPack to not create empty directories or use share/ structure
        if(WIN32)
            # Ensure CPack only installs explicitly defined components
            # This prevents CPack from creating empty directories based on CMAKE_INSTALL_PREFIX structure
            # CPack will only install files/directories we explicitly install via install() commands
            # Since all install() commands use doc/ (not share/doc/), no share/ directory should be created
            # Note: CPACK_COMPONENTS_ALL is set later in the component configuration section,
            # but we set it here early to ensure CPack respects it
            set(CPACK_COMPONENTS_ALL Runtime Documentation Manpages CACHE STRING "CPack components to install" FORCE)
            # Explicitly set packaging install prefix to empty to prevent CPack from creating share/ structure
            # CPack will use CMAKE_INSTALL_PREFIX directly without adding share/ subdirectories
            set(CPACK_PACKAGING_INSTALL_PREFIX "" CACHE STRING "Installation prefix for CPack (empty = use CMAKE_INSTALL_PREFIX directly)" FORCE)
            # Ensure CPack installs only what we explicitly define
            set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_BINARY_DIR};${PROJECT_NAME};ALL;/" CACHE STRING "CPack install projects" FORCE)
        endif()
        include(CPack)
    endif()
endif()

if(USE_CPACK)

    # =========================================================================
    # Basic CPack Configuration
    # =========================================================================
    set(CPACK_PACKAGE_NAME "ascii-chat")
    set(CPACK_PACKAGE_VENDOR "zfogg")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Real-time terminal-based video chat with ASCII art conversion")
    set(CPACK_PACKAGE_DESCRIPTION "ascii-chat is a terminal-based video chat application that converts webcam video to ASCII art in real-time. It supports multiple clients connecting to a single server, with video mixing and audio streaming capabilities.")

    # Version is already set before include(CPack) above
    # Re-set with CACHE FORCE to ensure it's not overridden
    set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR} CACHE STRING "Package version major" FORCE)
    set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR} CACHE STRING "Package version minor" FORCE)
    set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH} CACHE STRING "Package version patch" FORCE)
    set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}" CACHE STRING "Package version" FORCE)

    # Log version being used for packages
    message(STATUS "CPack: Using version ${CPACK_PACKAGE_VERSION} for packages (from PROJECT_VERSION=${PROJECT_VERSION})")

    # Package metadata
    set(CPACK_PACKAGE_CONTACT "https://github.com/zfogg/ascii-chat")
    if(DEFINED PROJECT_HOMEPAGE_URL)
        set(CPACK_PACKAGE_HOMEPAGE_URL "${PROJECT_HOMEPAGE_URL}")
    endif()

    # License file is already set before include(CPack) above
    # Re-set with CACHE FORCE to ensure CPack doesn't override it
    if(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE.txt")
        set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt" CACHE FILEPATH "License file for installers" FORCE)
        message(STATUS "CPack: Using LICENSE.txt for installers")
    elseif(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE")
        set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE" CACHE FILEPATH "License file for installers" FORCE)
        message(STATUS "CPack: Using LICENSE for installers")
    endif()

    # Package file name format (use PROJECT_VERSION directly to ensure git version is used)
    set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")

    # Output directory
    set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/packages")

    # Installation directory (without version for NSIS)
    # Set again after include(CPack) to ensure it overrides CPack's default
    # CPack's default is "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}" which we don't want
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}" CACHE STRING "Installation directory (without version)" FORCE)

    # =========================================================================
    # Platform-Specific Package Generators
    # =========================================================================

    if(UNIX AND NOT APPLE)
        # Linux: TGZ (always available), DEB, RPM (if tools found)
        set(CPACK_GENERATOR "TGZ")

        # Check for package tools and enable generators if available
        find_program(DPKG_BUILDPACKAGE_EXECUTABLE dpkg-buildpackage)
        find_program(RPMBUILD_EXECUTABLE rpmbuild)

        if(DPKG_BUILDPACKAGE_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "DEB")
            message(STATUS "CPack: DEB generator enabled (dpkg-buildpackage found)")
        else()
            message(STATUS "CPack: DEB generator disabled (dpkg-buildpackage not found)")
        endif()

        if(RPMBUILD_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "RPM")
            message(STATUS "CPack: RPM generator enabled (rpmbuild found)")
        else()
            message(STATUS "CPack: RPM generator disabled (rpmbuild not found)")
        endif()

        # DEB package configuration
        if("DEB" IN_LIST CPACK_GENERATOR)
            set(CPACK_DEBIAN_PACKAGE_NAME "ascii-chat")
            set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
            set(CPACK_DEBIAN_PACKAGE_SECTION "net")
            set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
            set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
                set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
            endif()
            set(CPACK_DEBIAN_PACKAGE_DEPENDS "")
            set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
            # Maintainer info (optional - can be set via environment)
            if(DEFINED ENV{DEBEMAIL})
                set(CPACK_DEBIAN_PACKAGE_MAINTAINER "$ENV{DEBEMAIL}")
            else()
                set(CPACK_DEBIAN_PACKAGE_MAINTAINER "ascii-chat <${CPACK_PACKAGE_CONTACT}>")
            endif()
        endif()

        # RPM package configuration
        if("RPM" IN_LIST CPACK_GENERATOR)
            set(CPACK_RPM_PACKAGE_NAME "ascii-chat")
            set(CPACK_RPM_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
            set(CPACK_RPM_PACKAGE_GROUP "Applications/Networking")
            set(CPACK_RPM_PACKAGE_LICENSE "MIT")
            set(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
                set(CPACK_RPM_PACKAGE_ARCHITECTURE "aarch64")
            endif()
            set(CPACK_RPM_PACKAGE_REQUIRES "")
            set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
            # Vendor info (optional)
            if(DEFINED ENV{RPM_VENDOR})
                set(CPACK_RPM_PACKAGE_VENDOR "$ENV{RPM_VENDOR}")
            else()
                set(CPACK_RPM_PACKAGE_VENDOR "${CPACK_PACKAGE_VENDOR}")
            endif()
        endif()

        message(STATUS "CPack: Enabled generators for Linux: ${CPACK_GENERATOR}")

    elseif(APPLE)
        # macOS: TGZ (always available), DragNDrop/DMG (if hdiutil available)
        set(CPACK_GENERATOR "TGZ")

        # Check for hdiutil (macOS DMG creation tool - usually always available on macOS)
        find_program(HDIUTIL_EXECUTABLE hdiutil)
        if(HDIUTIL_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "DragNDrop")
            message(STATUS "CPack: DMG generator enabled (hdiutil found)")
        else()
            message(STATUS "CPack: DMG generator disabled (hdiutil not found)")
        endif()

        # DMG package configuration
        if("DragNDrop" IN_LIST CPACK_GENERATOR)
            set(CPACK_DMG_FORMAT "UDZO")  # Compressed UDIF (read-only)
            set(CPACK_DMG_VOLUME_NAME "${CPACK_PACKAGE_NAME}")
            set(CPACK_DMG_BACKGROUND_IMAGE "")  # Optional: path to background image
            set(CPACK_DMG_DS_STORE_SETUP_SCRIPT "")  # Optional: custom setup script
            set(CPACK_DMG_SLA_DIR "")  # Optional: Software License Agreement directory
        endif()

        message(STATUS "CPack: Enabled generators for macOS: ${CPACK_GENERATOR}")

    elseif(WIN32)
        # Windows: ZIP (always available), NSIS/EXE (if makensis found)
        set(CPACK_GENERATOR "ZIP")

        # Check for NSIS (Nullsoft Scriptable Install System)
        find_program(NSIS_EXECUTABLE makensis)
        if(NOT NSIS_EXECUTABLE)
            # Try alternative NSIS locations (common Windows install paths)
            # Handle ProgramFiles(x86) separately due to CMake variable parsing
            if(DEFINED ENV{ProgramFiles})
                set(PROGRAM_FILES_PATH "$ENV{ProgramFiles}")
            else()
                set(PROGRAM_FILES_PATH "C:/Program Files")
            endif()

            if(DEFINED ENV{ProgramFiles\(x86\)})
                set(PROGRAM_FILES_X86_PATH "$ENV{ProgramFiles\(x86\)}")
            else()
                set(PROGRAM_FILES_X86_PATH "C:/Program Files (x86)")
            endif()

            find_program(NSIS_EXECUTABLE
                NAMES makensis
                PATHS
                    "${PROGRAM_FILES_PATH}/NSIS"
                    "${PROGRAM_FILES_X86_PATH}/NSIS"
                    "C:/Program Files/NSIS"
                    "C:/Program Files (x86)/NSIS"
                PATH_SUFFIXES bin
                NO_DEFAULT_PATH
            )
        endif()

        if(NSIS_EXECUTABLE)
            list(APPEND CPACK_GENERATOR "NSIS")
            message(STATUS "CPack: NSIS generator enabled (makensis found at ${NSIS_EXECUTABLE})")
        else()
            message(STATUS "CPack: NSIS generator disabled (makensis not found - install NSIS to create EXE installers)")
        endif()

        # NSIS installer configuration
        if("NSIS" IN_LIST CPACK_GENERATOR)
            set(CPACK_NSIS_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
            # Display name without version (just "ascii-chat")
            set(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_NAME}")
            # CPACK_PACKAGE_INSTALL_DIRECTORY is set above and controls the install directory
            # This ensures NSIS installs to "ascii-chat" instead of "ascii-chat 0.3.2"
            # Note: CPACK_PACKAGE_INSTALL_DIRECTORY is already set to "${CPACK_PACKAGE_NAME}" above
            set(CPACK_NSIS_HELP_LINK "${CPACK_PACKAGE_HOMEPAGE_URL}")
            set(CPACK_NSIS_URL_INFO_ABOUT "${CPACK_PACKAGE_HOMEPAGE_URL}")
            set(CPACK_NSIS_CONTACT "${CPACK_PACKAGE_CONTACT}")

            # Add installation directory to PATH
            # This ensures 'ascii-chat' can be run from any directory
            # The installer will add to system PATH if running with admin privileges,
            # or user PATH if running without admin (per-user installation)
            set(CPACK_NSIS_MODIFY_PATH ON)

            # Enable uninstall before install (clean upgrade)
            set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)

            # Optional: Custom installer icon
            # set(CPACK_NSIS_INSTALLED_ICON_NAME "${CMAKE_SOURCE_DIR}/resources/icon.ico")
        endif()

        message(STATUS "CPack: Enabled generators for Windows: ${CPACK_GENERATOR}")

    else()
        # Unknown platform: fallback to TGZ
        set(CPACK_GENERATOR "TGZ")
        message(STATUS "CPack: Using fallback generator TGZ for unknown platform")
    endif()

    # =========================================================================
    # Source Package Configuration (optional)
    # =========================================================================
    set(CPACK_SOURCE_GENERATOR "TGZ")
    if(UNIX AND NOT APPLE)
        find_program(ZIP_EXECUTABLE zip)
        if(ZIP_EXECUTABLE)
            list(APPEND CPACK_SOURCE_GENERATOR "ZIP")
        endif()
    endif()

    # Source package ignore patterns
    set(CPACK_SOURCE_IGNORE_FILES
        "/build/"
        "/build_release/"
        "/\\.git/"
        "/deps/"
        "/\\.deps-cache/"
        "/\\.deps-cache-musl/"
        "/\\.vscode/"
        "/\\.idea/"
        "/CMakeFiles/"
        "/CMakeCache\\.txt$"
        "/cmake_install\\.cmake$"
        "/\\.ninja_log$"
        "/\\.ninja_deps$"
        "/compile_commands\\.json$"
    )

    # =========================================================================
    # Component Configuration
    # =========================================================================
    # Configure components for installation (Runtime, Documentation)
    set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Binary")
    set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "ascii-chat executable")
    set(CPACK_COMPONENT_RUNTIME_REQUIRED ON)

    set(CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME "Documentation")
    set(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "README, LICENSE, and CHANGELOG")
    set(CPACK_COMPONENT_DOCUMENTATION_DEPENDS Runtime)

    # Manpages component (optional - depends on docs being built)
    set(CPACK_COMPONENT_MANPAGES_DISPLAY_NAME "Man Pages")
    set(CPACK_COMPONENT_MANPAGES_DESCRIPTION "Unix manual pages (man pages) for API documentation")
    set(CPACK_COMPONENT_MANPAGES_DEPENDS Runtime)

    # Group components
    set(CPACK_COMPONENT_GROUP_APPLICATIONS_DISPLAY_NAME "Application")
    set(CPACK_COMPONENT_GROUP_APPLICATIONS_DESCRIPTION "ASCII video chat application")
    set(CPACK_COMPONENT_RUNTIME_GROUP "Applications")
    set(CPACK_COMPONENT_DOCUMENTATION_GROUP "Applications")
    set(CPACK_COMPONENT_MANPAGES_GROUP "Applications")

    message(STATUS "CPack: Package generation enabled")
    message(STATUS "CPack: Package will be created in: ${CPACK_PACKAGE_DIRECTORY}")
    message(STATUS "CPack: Generators: ${CPACK_GENERATOR}")
else()
    message(STATUS "CPack: Package generation disabled (set USE_CPACK=ON to enable)")
endif()

