/**
 * @file crypto_client.c
 * @brief Client-side crypto handshake integration
 *
 * This module integrates the crypto handshake into the client connection flow.
 * It handles the client-side crypto handshake after TCP connection is established
 * but before sending application data.
 */

#include "crypto.h"
#include "server.h"
#include "options.h"
#include "common.h"
#include "crypto/handshake.h"
#include "crypto/keys.h"
#include "crypto/known_hosts.h"

#include <string.h>
#include <stdio.h>
#include <sodium.h>

// Global crypto handshake context for this client connection
// NOTE: We use the crypto context from server.c to match the handshake
extern crypto_handshake_context_t g_crypto_ctx;
static bool g_crypto_initialized = false;

/**
 * Initialize client crypto handshake
 *
 * @return 0 on success, -1 on failure
 */
int client_crypto_init(void) {
  log_debug("CLIENT_CRYPTO_INIT: Starting crypto initialization");
  if (g_crypto_initialized) {
    log_debug("CLIENT_CRYPTO_INIT: Already initialized, cleaning up and reinitializing");
    crypto_handshake_cleanup(&g_crypto_ctx);
    g_crypto_initialized = false;
  }

  // Check if encryption is disabled
  if (opt_no_encrypt) {
    log_info("Encryption disabled via --no-encrypt");
    log_debug("CLIENT_CRYPTO_INIT: Encryption disabled, returning 0");
    return 0;
  }

  log_debug("CLIENT_CRYPTO_INIT: Initializing crypto handshake context");

  // Check if we have an SSH key, password, or neither
  int result;
  bool is_ssh_key = false;
  private_key_t private_key;

  // Try to detect SSH key by attempting to parse as SSH key first
  if (strlen(opt_encrypt_key) > 0) {
    // First check if it's a readable file
    FILE *test_file = fopen(opt_encrypt_key, "r");
    if (test_file != NULL) {
      fclose(test_file);

      // Try to parse as Ed25519 SSH key
      log_debug("CLIENT_CRYPTO_INIT: Attempting to parse as SSH key: %s", opt_encrypt_key);
      if (parse_private_key(opt_encrypt_key, &private_key) == 0) {
        log_info("Successfully parsed SSH private key");
        is_ssh_key = true;
      } else {
        // File exists but isn't a valid SSH key - will fall through to password handling
        log_debug("CLIENT_CRYPTO_INIT: Not a valid SSH key, will treat as password file");
      }
    }
  }

  if (is_ssh_key) {
    // Use SSH private key for authentication
    log_debug("CLIENT_CRYPTO_INIT: Using SSH key for authentication");

    // Initialize crypto context (generates ephemeral X25519 keys)
    result = crypto_handshake_init(&g_crypto_ctx, false); // false = client
    if (result != 0) {
      log_error("Failed to initialize crypto handshake");
      return -1;
    }

    // Store the Ed25519 keys for authentication
    memcpy(&g_crypto_ctx.client_private_key, &private_key, sizeof(private_key_t));

    // Extract Ed25519 public key from private key
    g_crypto_ctx.client_public_key.type = KEY_TYPE_ED25519;
    memcpy(g_crypto_ctx.client_public_key.key, private_key.public_key, 32);
    SAFE_STRNCPY(g_crypto_ctx.client_public_key.comment, private_key.key_comment,
                 sizeof(g_crypto_ctx.client_public_key.comment) - 1);

    if (private_key.use_ssh_agent) {
      // Mode 1: SSH agent mode - use ephemeral keys for encryption, agent for identity
      log_info("Using SSH agent for authentication (ephemeral keys for encryption)");
      // Keep the ephemeral X25519 keys generated by crypto_handshake_init()
      // We'll use ed25519_sign_message() for authentication challenges later
    } else {
      // Mode 2/3: In-memory mode - use same key for both identity and encryption
      // Convert Ed25519 private key to X25519 for DH
      uint8_t x25519_sk[32];
      if (private_key_to_x25519(&private_key, x25519_sk) != 0) {
        log_error("Failed to convert Ed25519 key to X25519");
        return -1;
      }

      // Override the generated keys with our SSH key
      memcpy(g_crypto_ctx.crypto_ctx.private_key, x25519_sk, 32);

      // Derive public key from private key
      crypto_scalarmult_base(g_crypto_ctx.crypto_ctx.public_key, x25519_sk);

      // Clear sensitive data
      sodium_memzero(x25519_sk, sizeof(x25519_sk));

      log_info("Using SSH key for authentication and encryption");
    }

    // Clear the temporary private_key variable (we've already copied it to g_crypto_ctx)
    sodium_memzero(&private_key, sizeof(private_key));

  } else if (strlen(opt_encrypt_key) > 0 && strncmp(opt_encrypt_key, "gpg:", 4) != 0) {
    // It's a password - use password-based initialization
    log_debug("CLIENT_CRYPTO_INIT: Using password authentication");
    result = crypto_handshake_init_with_password(&g_crypto_ctx, false, opt_encrypt_key); // false = client
    if (result != 0) {
      log_error("Failed to initialize crypto handshake with password");
      log_debug("CLIENT_CRYPTO_INIT: crypto_handshake_init_with_password failed with result=%d", result);
      return -1;
    }
  } else {
    // No password or SSH key - use standard initialization with random keys
    log_debug("CLIENT_CRYPTO_INIT: Using standard initialization");
    result = crypto_handshake_init(&g_crypto_ctx, false); // false = client
    if (result != 0) {
      log_error("Failed to initialize crypto handshake");
      log_debug("CLIENT_CRYPTO_INIT: crypto_handshake_init failed with result=%d", result);
      return -1;
    }
  }

  log_debug("CLIENT_CRYPTO_INIT: crypto_handshake_init succeeded");

  // Set up server connection info for known_hosts
  SAFE_STRNCPY(g_crypto_ctx.server_hostname, opt_address, sizeof(g_crypto_ctx.server_hostname) - 1);
  g_crypto_ctx.server_port = (uint16_t)strtoint_safe(opt_port);

  // Configure server key verification if specified
  if (strlen(opt_server_key) > 0) {
    g_crypto_ctx.verify_server_key = true;
    SAFE_STRNCPY(g_crypto_ctx.expected_server_key, opt_server_key, sizeof(g_crypto_ctx.expected_server_key) - 1);
    log_info("Server key verification enabled: %s", opt_server_key);
  }

  g_crypto_initialized = true;
  log_info("Client crypto handshake initialized");
  log_debug("CLIENT_CRYPTO_INIT: Initialization complete, g_crypto_initialized=true");
  return 0;
}

/**
 * Perform crypto handshake with server
 *
 * @param socket Connected socket to server
 * @return 0 on success, -1 on failure
 */
int client_crypto_handshake(socket_t socket) {
  log_debug("CLIENT_CRYPTO_HANDSHAKE: Starting crypto handshake");
  log_debug("CLIENT_CRYPTO_HANDSHAKE: g_crypto_initialized=%d, opt_no_encrypt=%d", g_crypto_initialized,
            opt_no_encrypt);

  if (!g_crypto_initialized || opt_no_encrypt) {
    log_debug("Crypto handshake skipped (disabled or not initialized)");
    log_debug("CLIENT_CRYPTO_HANDSHAKE: Skipping handshake, returning 0");
    return 0;
  }

  log_info("Starting crypto handshake with server...");
  log_debug("CLIENT_CRYPTO: Starting crypto handshake with server...");

  // Step 1: Receive server's public key and send our public key
  log_debug("CLIENT_CRYPTO_HANDSHAKE: Starting key exchange");
  int result = crypto_handshake_client_key_exchange(&g_crypto_ctx, socket);
  if (result != 0) {
    log_error("Crypto key exchange failed");
    log_debug("CLIENT_CRYPTO_HANDSHAKE: Key exchange failed with result=%d", result);
    return -1;
  }
  log_debug("CLIENT_CRYPTO_HANDSHAKE: Key exchange completed successfully");

  // Step 2: Receive auth challenge and send response
  log_debug("CLIENT_CRYPTO: Sending auth response to server...");
  log_debug("CLIENT_CRYPTO_HANDSHAKE: Starting auth response");
  result = crypto_handshake_client_auth_response(&g_crypto_ctx, socket);
  if (result != 0) {
    log_error("Crypto authentication failed");
    log_debug("CLIENT_CRYPTO_HANDSHAKE: Auth response failed with result=%d", result);
    return result; // Propagate error code (-2 for auth failure, -1 for other errors)
  }
  log_debug("CLIENT_CRYPTO: Auth response sent successfully");
  log_debug("CLIENT_CRYPTO_HANDSHAKE: Auth response completed successfully");

  // Check if handshake completed during auth response (no authentication needed)
  if (g_crypto_ctx.state == CRYPTO_HANDSHAKE_READY) {
    log_info("Crypto handshake completed successfully (no authentication)");
    return 0;
  }

  // Step 3: Receive handshake complete message
  log_debug("CLIENT_CRYPTO_HANDSHAKE: Waiting for handshake complete message");
  result = crypto_handshake_client_complete(&g_crypto_ctx, socket);
  if (result != 0) {
    log_error("Crypto handshake completion failed");
    log_debug("CLIENT_CRYPTO_HANDSHAKE: Handshake completion failed with result=%d", result);
    return result; // Propagate error code (-2 for auth failure, -1 for other errors)
  }

  log_info("Crypto handshake completed successfully");
  log_debug("CLIENT_CRYPTO_HANDSHAKE: Handshake completed successfully, state=%d", g_crypto_ctx.state);
  return 0;
}

/**
 * Check if crypto handshake is ready
 *
 * @return true if encryption is ready, false otherwise
 */
bool crypto_client_is_ready(void) {
  if (!g_crypto_initialized || opt_no_encrypt) {
    log_debug("CLIENT_CRYPTO_READY: Not ready - initialized=%d, no_encrypt=%d", g_crypto_initialized, opt_no_encrypt);
    return false;
  }

  bool ready = crypto_handshake_is_ready(&g_crypto_ctx);
  log_debug("CLIENT_CRYPTO_READY: handshake_ready=%d, state=%d", ready, g_crypto_ctx.state);
  return ready;
}

/**
 * Get crypto context for encryption/decryption
 *
 * @return crypto context or NULL if not ready
 */
const crypto_context_t *crypto_client_get_context(void) {
  if (!crypto_client_is_ready()) {
    return NULL;
  }

  return crypto_handshake_get_context(&g_crypto_ctx);
}

/**
 * Encrypt a packet for transmission
 *
 * @param plaintext Plaintext data to encrypt
 * @param plaintext_len Length of plaintext data
 * @param ciphertext Output buffer for encrypted data
 * @param ciphertext_size Size of output buffer
 * @param ciphertext_len Output length of encrypted data
 * @return 0 on success, -1 on failure
 */
int crypto_client_encrypt_packet(const uint8_t *plaintext, size_t plaintext_len, uint8_t *ciphertext,
                                 size_t ciphertext_size, size_t *ciphertext_len) {
  if (!crypto_client_is_ready()) {
    // No encryption - just copy data
    if (plaintext_len > ciphertext_size) {
      return -1;
    }
    memcpy(ciphertext, plaintext, plaintext_len);
    *ciphertext_len = plaintext_len;
    return 0;
  }

  return crypto_handshake_encrypt_packet(&g_crypto_ctx, plaintext, plaintext_len, ciphertext, ciphertext_size,
                                         ciphertext_len);
}

/**
 * Decrypt a received packet
 *
 * @param ciphertext Encrypted data to decrypt
 * @param ciphertext_len Length of encrypted data
 * @param plaintext Output buffer for decrypted data
 * @param plaintext_size Size of output buffer
 * @param plaintext_len Output length of decrypted data
 * @return 0 on success, -1 on failure
 */
int crypto_client_decrypt_packet(const uint8_t *ciphertext, size_t ciphertext_len, uint8_t *plaintext,
                                 size_t plaintext_size, size_t *plaintext_len) {
  if (!crypto_client_is_ready()) {
    // No encryption - just copy data
    if (ciphertext_len > plaintext_size) {
      return -1;
    }
    memcpy(plaintext, ciphertext, ciphertext_len);
    *plaintext_len = ciphertext_len;
    return 0;
  }

  return crypto_handshake_decrypt_packet(&g_crypto_ctx, ciphertext, ciphertext_len, plaintext, plaintext_size,
                                         plaintext_len);
}

/**
 * Cleanup crypto client resources
 */
void crypto_client_cleanup(void) {
  if (g_crypto_initialized) {
    crypto_handshake_cleanup(&g_crypto_ctx);
    g_crypto_initialized = false;
    log_debug("Client crypto handshake cleaned up");
  }
}
