name: Security

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.c'
      - '**.h'
      - '**.m'
  pull_request:
    branches: [ '*' ]
    paths:
      - '**.c'
      - '**.h'
      - '**.m'

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql/codeql-config.yml

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libv4l-dev zlib1g-dev portaudio19-dev pkg-config

    - name: Build for analysis
      run: |
        make CSTD=c2x clean debug

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang pkg-config libv4l-dev zlib1g-dev portaudio19-dev

    - name: Check for known vulnerabilities in system packages
      run: |
        # Check libv4l version
        if pkg-config --exists libv4l2; then
          libv4l2_version=$(pkg-config --modversion libv4l2)
          echo "libv4l2 version: $libv4l2_version"
        fi

        # Check zlib version
        if pkg-config --exists zlib; then
          zlib_version=$(pkg-config --modversion zlib)
          echo "zlib version: $zlib_version"
        fi

        # Check portaudio version
        if pkg-config --exists portaudio-2.0; then
          portaudio_version=$(pkg-config --modversion portaudio-2.0)
          echo "portaudio version: $portaudio_version"
        fi

    - name: Run basic security checks
      run: |
        echo "Checking for insecure function usage..."
        
        # Check for potentially unsafe functions
        echo "=== Checking for unsafe string functions ==="
        if grep -n "strcpy\|strcat\|sprintf\|gets" *.c *.h 2>/dev/null; then
          echo "⚠️  Found potentially unsafe string functions"
        else
          echo "✅ No unsafe string functions found"
        fi
        
        echo "=== Checking for unsafe memory functions ==="
        if grep -n "alloca" *.c *.h 2>/dev/null; then
          echo "⚠️  Found alloca usage (stack overflow risk)"
        else
          echo "✅ No alloca usage found"
        fi
        
        echo "=== Checking for proper bounds checking ==="
        if grep -n "malloc\|calloc\|realloc" *.c | grep -v "SAFE_MALLOC\|DEBUG_MEMORY"; then
          echo "⚠️  Found direct malloc usage without SAFE_MALLOC wrapper"
        else
          echo "✅ All allocations use safe wrappers"
        fi

  format-security:
    name: Format String Security Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang clang-tools libv4l-dev zlib1g-dev portaudio19-dev pkg-config

    - name: Build with format security warnings
      run: |
        CFLAGS="-Wformat -Wformat-security -Werror=format-security"
        CXXFLAGS="-Wformat -Wformat-security -Werror=format-security"
        make CSTD=c2x CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" clean debug

    - name: Run static security analysis
      run: |
        # Use clang static analyzer for security issues
        scan-build --status-bugs make CSTD=c2x clean c-objs