# Build availability is determined by the target toolchain, never the host CPU.
include(CheckCSourceCompiles)
set(ASCIICHAT_SIMD_MODE "auto" CACHE STRING "SIMD backends: auto, scalar, sse2, ssse3, avx2, neon, sve")
set_property(CACHE ASCIICHAT_SIMD_MODE PROPERTY STRINGS auto scalar sse2 ssse3 avx2 neon sve)
if(NOT ASCIICHAT_SIMD_MODE MATCHES "^(auto|scalar|sse2|ssse3|avx2|neon|sve)$")
    message(FATAL_ERROR "Unknown ASCIICHAT_SIMD_MODE: ${ASCIICHAT_SIMD_MODE}")
endif()

foreach(isa SSE2 SSSE3 AVX2 NEON SVE)
    set(ENABLE_SIMD_${isa} FALSE)
endforeach()

function(asciichat_check_simd isa flags header expression)
    string(TOLOWER "${isa}" name)
    if(NOT ASCIICHAT_SIMD_MODE STREQUAL "auto" AND NOT ASCIICHAT_SIMD_MODE STREQUAL "${name}")
        return()
    endif()
    set(CMAKE_REQUIRED_FLAGS "${flags}")
    # Compile only: cross compilers and non-SVE build hosts can build SVE objects.
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    check_c_source_compiles("#include <${header}>
int main(void) { ${expression}; return 0; }" ASCIICHAT_CAN_COMPILE_${isa})
    set(ENABLE_SIMD_${isa} ${ASCIICHAT_CAN_COMPILE_${isa}} PARENT_SCOPE)
endfunction()

if(ASCIICHAT_IS_X86_64)
    asciichat_check_simd(SSE2 "-msse2" emmintrin.h "(void)_mm_setzero_si128()")
    asciichat_check_simd(SSSE3 "-mssse3" tmmintrin.h "(void)_mm_shuffle_epi8(_mm_setzero_si128(), _mm_setzero_si128())")
    asciichat_check_simd(AVX2 "-mavx2" immintrin.h "(void)_mm256_setzero_si256()")
elseif(ASCIICHAT_IS_ARM64)
    asciichat_check_simd(NEON "-march=armv8-a" arm_neon.h "(void)vdup_n_u8(0)")
    # SVE dispatch currently has an OS capability probe on Linux only.
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        asciichat_check_simd(SVE "-march=armv8-a+sve" arm_sve.h "(void)svcntb()")
    endif()
elseif(ASCIICHAT_IS_ARM32)
    asciichat_check_simd(NEON "-mfpu=neon" arm_neon.h "(void)vdup_n_u8(0)")
endif()

if(NOT ASCIICHAT_SIMD_MODE MATCHES "^(auto|scalar)$")
    string(TOUPPER "${ASCIICHAT_SIMD_MODE}" requested)
    if(NOT ENABLE_SIMD_${requested})
        message(FATAL_ERROR "Requested SIMD backend ${ASCIICHAT_SIMD_MODE} is unavailable for this target/toolchain")
    endif()
endif()
foreach(isa SSE2 SSSE3 AVX2 NEON SVE)
    if(ENABLE_SIMD_${isa})
        add_compile_definitions(SIMD_SUPPORT_${isa}=1)
    else()
        add_compile_definitions(SIMD_SUPPORT_${isa}=0)
    endif()
endforeach()
